export const lessonContent = {
  id: "lb1-00-module-overview",
  extractionStatus: "real slide screenshots extracted from all 31 slides of 0-Module-LSB1-2.pdf",
  whyThisMatters: "LB1 is not a list of tools to memorize. The course asks you to connect a biological question to a computational method, then defend what can and cannot be inferred from sequence, structure, alignments, probabilistic models and database evidence.",
  objectives: [
    "Explain the main aims of the Capriotti module: sequence/structure analysis tools, functional annotation, probabilistic models, HMMs, HMMER and applied protein reasoning.",
    "Place each deck in the course route from structural bioinformatics to profile-HMM project work and protein applications.",
    "State what it means to transfer knowledge from known proteins to an unknown sequence under explicit constraints.",
    "Choose a study route depending on whether the immediate target is exam preparation, HMM understanding, the Kunitz project or structure/function reasoning.",
    "Avoid treating tool output as biological truth without checking model assumptions, evidence quality and annotation scope.",
  ],
  coreConcepts: [
    {
      title: "Tools answer biological questions",
      body: "The guide should always start from the biological problem: compare structures, infer family membership, search homologs, map annotations, reason about complexes or predict variant effects. A method is useful only when its assumptions fit that problem.",
      keywords: ["question first", "method choice", "assumptions"],
    },
    {
      title: "Transfer of knowledge is conditional",
      body: "Functional annotation by similarity is strongest when proteins belong to the same family, preserve relevant residues or structures, and are supported by reliable prior annotation. Similarity alone is evidence, not proof.",
      keywords: ["family", "evidence", "annotation"],
    },
    {
      title: "Structure can preserve signal",
      body: "Protein structures can remain similar even when sequence identity is low. That is why structural alignment, RMSD and fold-level reasoning can recover relationships missed by simple sequence comparison.",
      keywords: ["fold", "RMSD", "low identity"],
    },
    {
      title: "Pairwise alignment is evidence with assumptions",
      body: "Substitution matrices, gap penalties, global/local dynamic programming and score significance define what a pairwise alignment is allowed to reward, penalize and claim.",
      keywords: ["BLOSUM62", "gaps", "significance"],
    },
    {
      title: "Twilight zones are problem-specific",
      body: "The sequence-identity threshold for transferring structure is not the same as the threshold for transferring localization or precise function. Each annotation type has its own risk zone.",
      keywords: ["HSSP", "threshold", "feature transfer"],
    },
    {
      title: "Profiles beat one-sequence thinking",
      body: "Multiple alignments and profile HMMs use a family-level pattern: conserved positions, tolerated substitutions and indel tendencies. This is stronger than searching with one sequence and one substitution matrix.",
      keywords: ["MSA", "profile HMM", "family model"],
    },
    {
      title: "Probabilities need interpretation",
      body: "Model-based sequence analysis asks different questions: how likely is a sequence under a model, which model explains a sequence, and which hidden path best explains the observed symbols.",
      keywords: ["likelihood", "Bayes", "hidden path"],
    },
    {
      title: "Applications return to biology",
      body: "Mapping, complexes and variants are where computational evidence must be translated back into residues, structures, interactions, function and disease relevance.",
      keywords: ["mapping", "interfaces", "variants"],
    },
  ],
  routeSteps: [
    {
      title: "Structural foundations",
      body: "Start with structure alignment and multiple alignments. Learn what similarity means before using it to transfer annotation.",
    },
    {
      title: "Model-based sequence analysis",
      body: "Move to probabilistic models, HMMs and profile HMMs. Keep observed sequence, hidden path and model parameters separate.",
    },
    {
      title: "HMMER and the Kunitz project",
      body: "Use family profiles in practice: build a model, search databases, inspect hits and justify why the Kunitz domain is a good target.",
    },
    {
      title: "Annotation and applications",
      body: "Finish with mapping, structure analysis, complexes and variants. The final skill is explaining what the evidence supports biologically.",
    },
  ],
  walkthroughSections: [
    {
      range: "Slides 1-3",
      title: "What this module is trying to teach",
      intro: "Read the overview deck as the contract for the module. It tells you that LB1 is about understanding tools for biological inference, not only pressing buttons.",
      slides: [
        {
          label: "Course overview",
          page: 1,
          image: "../lb1-slides/00-module-overview/slide-01.jpg",
          alt: "Slide 1 from 0-Module-LSB1-2.pdf introducing Laboratory of Bioinformatics I Module 2",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Laboratory of Bioinformatics I - Module 2",
          slideBullets: ["Introduction and basic concepts", "Sequence and structure analysis", "Protein functional annotation"],
          title: "Sequence and structure analysis tools",
          comment: "The course begins with the toolkit: methods for analyzing biological sequences and structures, then uses those tools to support functional annotation and problem solving.",
          teaching: "Study interpretation: when you learn a tool, write down the biological question it answers and the evidence it produces.",
          remember: "A good answer names the method, the input, the output and the biological interpretation.",
          prompt: "Give an example of a biological question that requires structure analysis rather than sequence search alone.",
        },
        {
          label: "Main aims",
          page: 2,
          image: "../lb1-slides/00-module-overview/slide-02.jpg",
          alt: "Slide 2 from 0-Module-LSB1-2.pdf listing the main aims of the module",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Main aims",
          slideBullets: ["Tools for sequence/structure analysis and development", "Protein functional annotation", "Machine-learning background", "Problem-solving and basic tools"],
          title: "Functional annotation is evidence transfer",
          comment: "The overview frames functional annotation as a central aim. That means inferring properties of an unknown protein from known sequences, structures, domains or families.",
          teaching: "Study interpretation: transfer is valid only under constraints such as same family, conserved region, similar structure and reliable source annotation.",
          remember: "Do not write 'similar sequence therefore same function' without stating the conditions.",
          trap: "The classic trap is over-annotation: transferring a precise function from weak similarity or from a different domain context.",
        },
        {
          label: "Topic map",
          page: 3,
          image: "../lb1-slides/00-module-overview/slide-03.jpg",
          alt: "Slide 3 from 0-Module-LSB1-2.pdf listing the module topics",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Topics",
          slideBullets: ["Structural alignment and MSA", "HMMs, profile HMMs and HMMER", "Mapping and structure analysis", "Machine learning, prediction and project work"],
          title: "The course route is a dependency graph",
          comment: "The topic slide gives the chronological path: structures and alignments first, probabilistic models next, then HMMER/project work and biological applications.",
          teaching: "Study interpretation: do not study HMMER before you can explain what a profile represents and what an alignment has conserved.",
          remember: "Each later tool depends on an earlier concept: correspondence, conservation, probability, significance and annotation scope.",
          prompt: "Which earlier ideas do you need before you can justify a profile-HMM database hit?",
        },
      ],
    },
    {
      range: "Slides 4-12",
      title: "Why structure enters before the HMM chapters",
      intro: "The overview deck uses structure as the first high-yield example of evidence that can survive sequence divergence.",
      slides: [
        {
          label: "Structural bioinformatics",
          page: 4,
          image: "../lb1-slides/00-module-overview/slide-04.jpg",
          alt: "Slide 4 from 0-Module-LSB1-2.pdf introducing structural alignment concepts",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Structural alignment",
          slideBullets: ["Protein structure can be more conserved than sequence", "Compare structures through a correspondence and a transformation", "Use RMSD and aligned length carefully"],
          title: "Structure alignment before profile modeling",
          comment: "Protein geometrical features, structural alignment and multiple alignments come first because they define what similarity and conservation mean.",
          teaching: "Study interpretation: if you cannot explain correspondence, RMSD or conserved positions, HMMER hits will feel like unexplained magic.",
          remember: "Structure and alignment concepts are the vocabulary for later family models.",
          prompt: "Why can a structural comparison be informative when sequence identity is low?",
        },
        {
          label: "Structural alignment formalism",
          page: 5,
          image: "../lb1-slides/00-module-overview/slide-05.jpg",
          alt: "Slide 5 from 0-Module-LSB1-2.pdf formally defining structural alignment",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Structural Alignment",
          slideBullets: ["Find optimal subsets of points", "Find a rigid-body transformation", "Minimize a distance metric", "Correspondence and transformation are separate pieces"],
          title: "Structural alignment means correspondence plus fit",
          comment: "The slide formalizes structural alignment as finding matching subsets of points and the rigid transformation that minimizes distance. This is the preview for lesson 01: alignment is not only drawing two structures together.",
          teaching: "Study interpretation: even in the overview, Capriotti is already separating the hard correspondence problem from the geometric fitting problem.",
          remember: "Structural alignment = choose what corresponds + superimpose + evaluate distance.",
          trap: "Do not reduce structural alignment to RMSD alone; RMSD depends on the correspondence and aligned region.",
          prompt: "What are the two tasks hidden inside the phrase 'structural alignment'?",
        },
        {
          label: "Foundational relation",
          page: 6,
          image: "../lb1-slides/00-module-overview/slide-06.jpg",
          alt: "Slide 6 from 0-Module-LSB1-2.pdf citing Chothia and Lesk as foundation of structural bioinformatics",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "The foundation of structural bioinformatics",
          slideBullets: ["Chothia and Lesk 1986", "Sequence similarity relates to structural similarity", "Empirical foundation for transfer reasoning"],
          title: "Sequence-structure relationships are empirical",
          comment: "The overview points to the classic observation that sequence similarity and structural similarity are related. This is the basis for using alignment evidence, but the rest of the deck shows where the relationship becomes unsafe.",
          teaching: "Study interpretation: this slide justifies why sequence comparison is useful, not why it is always sufficient.",
          remember: "High identity often supports structural transfer; low identity requires more careful evidence.",
          trap: "Do not turn an empirical trend into an absolute rule.",
        },
        {
          label: "Sequence alignment recap",
          page: 7,
          image: "../lb1-slides/00-module-overview/slide-07.jpg",
          alt: "Slide 7 from 0-Module-LSB1-2.pdf explaining why sequence alignment is used",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Why Sequence Alignment?",
          slideBullets: ["Measure sequence similarity", "Estimate structural similarity", "Define distance", "Find and evaluate alignments"],
          title: "Sequence alignment is a route to inference",
          comment: "The slide explains why alignment matters: it gives a way to measure similarity, define sequence distance, search for an optimal alignment and evaluate whether the result supports a relationship.",
          teaching: "Study interpretation: sequence alignment is not the final answer; it is a controlled way to gather evidence for structure/function inference.",
          remember: "Alignment gives evidence; interpretation depends on score, significance, coverage and biological question.",
          trap: "Do not stop at 'the sequences align'. Ask what the alignment is being used to infer.",
        },
        {
          label: "Substitution score",
          page: 8,
          image: "../lb1-slides/00-module-overview/slide-08.jpg",
          alt: "Slide 8 from 0-Module-LSB1-2.pdf introducing substitution matrices and residue mutation scores",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Sequence Distance Score",
          slideBullets: ["Mutation event", "Residue i to residue j", "Substitution matrix", "BLOSUM62 example"],
          title: "Substitution matrices encode biological assumptions",
          comment: "This slide introduces the idea that replacing one residue with another has a score. Matrices such as BLOSUM62 summarize which substitutions are plausible in related proteins.",
          teaching: "Study interpretation: a substitution score is not arbitrary math; it reflects observed evolutionary tolerance.",
          remember: "Positive, zero and negative substitution scores guide the alignment path.",
          trap: "Do not treat all amino-acid changes as equally bad; chemically/evolutionarily similar substitutions may be tolerated.",
        },
        {
          label: "Gap events",
          page: 9,
          image: "../lb1-slides/00-module-overview/slide-09.jpg",
          alt: "Slide 9 from 0-Module-LSB1-2.pdf introducing insertion, deletion and gap penalties",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Other events",
          slideBullets: ["Insertion", "Deletion", "Linear gap penalty", "Affine gap penalty with opening and extension"],
          title: "Indels need their own scoring logic",
          comment: "The deck adds insertions and deletions as evolutionary events. Gap penalties can be linear or affine, with separate costs for opening and extending a gap.",
          teaching: "Study interpretation: gap scoring controls whether an alignment prefers one long gap or many short gaps.",
          remember: "A gap is not a missing detail; it changes the alignment and therefore the inference.",
          trap: "Do not compare alignments without knowing how gaps were penalized.",
        },
        {
          label: "Global and local alignment",
          page: 10,
          image: "../lb1-slides/00-module-overview/slide-10.jpg",
          alt: "Slide 10 from 0-Module-LSB1-2.pdf comparing Needleman-Wunsch and Smith-Waterman algorithms",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Alignment Algorithms",
          slideBullets: ["Global alignment", "Needleman-Wunsch", "Local alignment", "Smith-Waterman"],
          title: "Algorithm choice changes the biological question",
          comment: "The slide distinguishes global alignment over the full length from local alignment over the most similar subsequences. This matters for domains, fragments and multidomain proteins.",
          teaching: "Study interpretation: before interpreting identity, ask whether the algorithm compared whole sequences or only a local region.",
          remember: "Global asks full-length similarity; local asks best matching region.",
          trap: "Do not transfer whole-protein function from a short local match without checking coverage and domain context.",
        },
        {
          label: "Alignment significance",
          page: 11,
          image: "../lb1-slides/00-module-overview/slide-11.jpg",
          alt: "Slide 11 from 0-Module-LSB1-2.pdf discussing alignment score significance",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Alignment Significance",
          slideBullets: ["Alignment score S", "Is it significant?", "Compare with random alignments", "Score distribution"],
          title: "A score needs a null comparison",
          comment: "The deck asks whether an alignment score is significant. The answer is to compare the score to what random alignments would produce.",
          teaching: "Study interpretation: significance is what stops you from treating every score as biological evidence.",
          remember: "A raw score alone is incomplete; ask how surprising it is under random comparison.",
          trap: "Do not interpret high-looking scores without considering sequence length and search space.",
        },
        {
          label: "HSSP relation",
          page: 12,
          image: "../lb1-slides/00-module-overview/slide-12.jpg",
          alt: "Slide 12 from 0-Module-LSB1-2.pdf about HSSP and the relation between sequence similarity, structure similarity and alignment length",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Structural Homology",
          slideBullets: ["HSSP database", "Sequence similarity", "Structure similarity", "Alignment length"],
          title: "Identity thresholds depend on alignment length",
          comment: "This slide introduces the HSSP-style relationship between sequence similarity, structural similarity and alignment length. A short alignment needs more identity to support the same confidence.",
          teaching: "Study interpretation: percent identity without alignment length is not enough.",
          remember: "Identity, length and structural evidence must be interpreted together.",
          trap: "Do not quote a fixed identity threshold without saying what length and question it applies to.",
        },
      ],
    },
    {
      range: "Slides 13-16",
      title: "Twilight zone and structure prediction",
      intro: "After basic sequence alignment, the deck shows where sequence identity becomes uncertain and how comparative modeling depends on template similarity.",
      slides: [
        {
          label: "Twilight zone",
          page: 13,
          image: "../lb1-slides/00-module-overview/slide-13.jpg",
          alt: "Slide 13 from 0-Module-LSB1-2.pdf about the sequence identity twilight zone",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Twilight Zone",
          slideBullets: ["Above about 20% identity many alignments are homologous", "Below about 25% few are reliable", "Identity thresholds are uncertain", "Rost 1999"],
          title: "Identity thresholds are not magic buttons",
          comment: "The overview stresses that high sequence identity often allows transfer of structural information, but remote homologs can share structure at low identity.",
          teaching: "Study interpretation: sequence identity is a confidence clue, not an automatic permission to transfer every annotation.",
          remember: "At low identity, combine evidence: aligned region, conserved residues, structural fold, profile support and statistical significance.",
          trap: "Do not say 'below 30 percent identity means unrelated'. The course uses low-identity structural examples precisely to break that shortcut.",
          prompt: "How would you explain the twilight-zone problem in one exam paragraph?",
        },
        {
          label: "Comparative modeling",
          page: 14,
          image: "../lb1-slides/00-module-overview/slide-14.jpg",
          alt: "Slide 14 from 0-Module-LSB1-2.pdf showing a comparative modeling flow chart",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Comparative Modeling",
          slideBullets: ["Template selection", "Sequence alignment", "Model building", "Model evaluation"],
          title: "Homology modeling depends on the alignment",
          comment: "The slide lays out the comparative modeling workflow: choose a template, align target and template, build the model and evaluate quality.",
          teaching: "Study interpretation: the predicted structure inherits the strengths and weaknesses of the template and alignment.",
          remember: "Template choice plus alignment quality controls model reliability.",
          trap: "Do not trust a model just because software produced coordinates.",
          prompt: "Where can comparative modeling fail even if a template exists?",
        },
        {
          label: "Predicted-structure use",
          page: 15,
          image: "../lb1-slides/00-module-overview/slide-15.jpg",
          alt: "Slide 15 from 0-Module-LSB1-2.pdf showing uses of predicted structures by similarity level",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Use of Predicted Structures",
          slideBullets: ["Comparative modeling", "Threading", "Ab initio or de novo prediction", "Use depends on sequence similarity"],
          title: "The use of a predicted structure depends on confidence",
          comment: "This slide separates comparative modeling, threading and ab initio/de novo prediction, emphasizing that lower similarity changes what you can safely do with a predicted structure.",
          teaching: "Study interpretation: the same predicted model may be useful for fold-level reasoning but unsafe for detailed active-site conclusions.",
          remember: "Model resolution of inference decreases as template similarity weakens.",
          trap: "Do not use a low-confidence model for atom-level claims.",
        },
        {
          label: "Remote homologs",
          page: 16,
          image: "../lb1-slides/00-module-overview/slide-16.jpg",
          alt: "Slide 16 from 0-Module-LSB1-2.pdf about remote homologs and low sequence identity structural similarity",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Remote homologs",
          slideBullets: ["More than 30% identity often implies similar structures for long sequences", "Lower identity can still preserve structure", "Examples motivate structure/profile methods"],
          title: "Low identity does not erase structural relationships",
          comment: "The deck explicitly warns that the usual identity rule does not exclude similar structures below the threshold. This prepares the need for structural alignment, profiles and HMMER.",
          teaching: "Study interpretation: remote homology is exactly why LB1 cannot stop at pairwise sequence identity.",
          remember: "Low identity means more evidence is needed, not that the relationship is impossible.",
          prompt: "Why are profile HMMs and structure alignment useful for remote homologs?",
        },
      ],
    },
    {
      range: "Slides 17-24",
      title: "Transfer of knowledge: useful, powerful, dangerous",
      intro: "A major hidden theme of the overview is annotation discipline: what can you safely infer from a similar protein?",
      slides: [
        {
          label: "Annotation transfer",
          page: 17,
          image: "../lb1-slides/00-module-overview/slide-17.jpg",
          alt: "Slide 17 from 0-Module-LSB1-2.pdf about sequence identity inference and problem-specific thresholds",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Sequence Identity Inference",
          slideBullets: ["Predict features of unknown proteins", "Define reliable sequence-similarity thresholds", "Problem-specific twilight region"],
          title: "Feature transfer has its own twilight zone",
          comment: "The deck asks whether sequence similarity can predict other features of an unknown protein. The answer is to define problem-specific thresholds for reliable transfer.",
          teaching: "Study interpretation: structure, localization and function do not share one universal identity cutoff.",
          remember: "Transfer the right level of annotation: family may be safe when precise activity is not.",
          trap: "Do not use a structural-similarity threshold to justify every functional annotation.",
          prompt: "Why is the twilight zone problem-specific?",
        },
        {
          label: "Localization threshold",
          page: 18,
          image: "../lb1-slides/00-module-overview/slide-18.jpg",
          alt: "Slide 18 from 0-Module-LSB1-2.pdf about sequence identity thresholds for subcellular localization",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Subcellular Localization",
          slideBullets: ["Localization transfer needs higher identity", "Threshold differs from structure transfer", "Rost and Nair 2002"],
          title: "Localization is harder to transfer than structure",
          comment: "The slide states that reliably transferring subcellular localization requires higher sequence identity than transferring structure.",
          teaching: "Study interpretation: different biological features have different dependence on sequence similarity.",
          remember: "The safer the annotation needs to be, the more specific evidence you need.",
          trap: "Do not infer localization just because two proteins share a fold.",
        },
        {
          label: "False positive",
          page: 19,
          image: "../lb1-slides/00-module-overview/slide-19.jpg",
          alt: "Slide 19 from 0-Module-LSB1-2.pdf showing a subcellular localization false positive at high identity",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "A false positive",
          slideBullets: ["Peroxisomal ICDH", "Cytosolic ICDH", "84.2% identity", "Different localization"],
          title: "High identity can still mislead feature transfer",
          comment: "The example compares two highly similar isocitrate dehydrogenases with different subcellular localization, showing that even high identity can fail for some features.",
          teaching: "Study interpretation: Capriotti is warning against blind transfer, not against using similarity at all.",
          remember: "Always ask which feature is being transferred and whether the evidence supports that feature.",
          trap: "Do not transfer localization automatically from high sequence identity.",
          prompt: "Why is this a stronger warning than a low-identity example?",
        },
        {
          label: "GO functional annotation",
          page: 20,
          image: "../lb1-slides/00-module-overview/slide-20.jpg",
          alt: "Slide 20 from 0-Module-LSB1-2.pdf about functional annotation using Gene Ontology similarity",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Functional Annotation",
          slideBullets: ["Sequence identity", "GO term identity/similarity", "Feature transfer thresholds"],
          title: "Function transfer can be measured at different specificity",
          comment: "The deck moves from localization to functional annotation, where similarity between GO terms can be used to evaluate how well annotation transfers.",
          teaching: "Study interpretation: exact function, broad process and family membership are different annotation levels.",
          remember: "Annotation specificity matters: broad transfer may be safe when precise transfer is not.",
          trap: "Do not collapse all GO/function statements into one yes/no claim.",
        },
        {
          label: "Counterexamples",
          page: 21,
          image: "../lb1-slides/00-module-overview/slide-21.jpg",
          alt: "Slide 21 from 0-Module-LSB1-2.pdf comparing GAL1 and GAL3 with similar sequence but dissimilar functions",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Dissimilar functions",
          slideBullets: ["Similar proteins can diverge in function", "Domain context matters", "Annotations can be too specific"],
          title: "The deck teaches by warning you",
          comment: "Examples such as related proteins with different functional roles are meant to stop you from treating similarity as a full functional proof.",
          teaching: "Study interpretation: the professor's likely target is your reasoning, not whether you can repeat one example name.",
          remember: "Similarity supports hypotheses; curated evidence and conserved mechanism make them stronger.",
          trap: "Do not ignore negative evidence such as missing catalytic residues, changed binding sites or different cellular context.",
        },
        {
          label: "Cytochrome C function",
          page: 22,
          image: "../lb1-slides/00-module-overview/slide-22.jpg",
          alt: "Slide 22 from 0-Module-LSB1-2.pdf introducing cytochrome c as an electron carrier case study",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Case Study",
          slideBullets: ["Electron carrier protein", "Cytochrome c heme group", "Electron transfer chain", "Binding/function context"],
          title: "The case study defines the functional question",
          comment: "Before comparing sequences and structures, the deck explains what cytochrome c does. That matters because the alignment must be judged against the functionally relevant sites.",
          teaching: "Study interpretation: always define the biological function before deciding whether an alignment preserves it.",
          remember: "Local binding-site conservation can matter more than global similarity.",
          prompt: "Which residues or regions would you inspect if function depends on electron transfer?",
        },
        {
          label: "High-identity comparison",
          page: 23,
          image: "../lb1-slides/00-module-overview/slide-23.jpg",
          alt: "Slide 23 from 0-Module-LSB1-2.pdf comparing human and horse cytochrome c",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Homo vs Horse",
          slideBullets: ["Human cytochrome c", "Equine cytochrome c", "RMSD 0.035 nm", "88% sequence identity"],
          title: "High identity gives a clean transfer case",
          comment: "Human and horse cytochrome c have very high identity and extremely low RMSD, so sequence and structure evidence agree.",
          teaching: "Study interpretation: this is the easy case that defines what strong evidence looks like.",
          remember: "High identity plus low RMSD plus conserved functional sites supports confident transfer.",
        },
        {
          label: "Sequence equals structure",
          page: 24,
          image: "../lb1-slides/00-module-overview/slide-24.jpg",
          alt: "Slide 24 from 0-Module-LSB1-2.pdf showing sequence alignment identical to structural alignment in the high-identity cytochrome case",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Sequence vs Structure",
          slideBullets: ["88% identity", "Sequence alignment identical to structural alignment", "Binding sites conserved"],
          title: "When identity is high, pairwise alignment can be enough",
          comment: "In this case the sequence alignment matches the structural alignment and binding-site positions are conserved. This is the safest transfer scenario shown in the deck.",
          teaching: "Study interpretation: the deck uses this case as a contrast for the harder low-identity examples that follow.",
          remember: "The safe inference comes from agreement among identity, structure and functional-site conservation.",
          trap: "Do not generalize this clean case to all homologs.",
        },
      ],
    },
    {
      range: "Slides 25-31",
      title: "From better alignments to the rest of LB1",
      intro: "The final overview logic is that single pairwise comparisons are often not enough. The rest of the course builds richer family and structure-aware evidence.",
      slides: [
        {
          label: "Cytochrome C cases",
          page: 25,
          image: "../lb1-slides/00-module-overview/slide-25.jpg",
          alt: "Slide 25 from 0-Module-LSB1-2.pdf with a cytochrome C comparison example",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Similar structures, shifted details",
          slideBullets: ["Compare sequence and structure", "Look at binding or active regions", "Do not overread global similarity"],
          title: "Global similarity and local function are different questions",
          comment: "The cytochrome-style examples show why you should inspect the part of the protein that matters for the biological question, not only the global alignment.",
          teaching: "Study interpretation: when function depends on a site, ask whether that site is aligned and conserved.",
          remember: "A good workflow checks both overall relationship and local functional evidence.",
          prompt: "Why can two proteins be globally similar but still differ in a functionally important detail?",
        },
        {
          label: "Needs refinement",
          page: 26,
          image: "../lb1-slides/00-module-overview/slide-26.jpg",
          alt: "Slide 26 from 0-Module-LSB1-2.pdf showing sequence versus structure for human and Rhodobacter cytochrome c",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Sequence vs Structure (I)",
          slideBullets: ["28% identity", "RMSD 0.18 nm", "Homology modeling possible after refinement", "One binding site not conserved"],
          title: "Moderate-low identity requires alignment refinement",
          comment: "The sequence alignment can still support homology modeling, but only after refinement because one binding site is not conserved.",
          teaching: "Study interpretation: this is the middle case: not hopeless, but not automatic.",
          remember: "Refine the alignment when functional sites do not line up.",
          trap: "Do not assume the first pairwise alignment is the modeling alignment.",
        },
        {
          label: "Another low-identity structure match",
          page: 27,
          image: "../lb1-slides/00-module-overview/slide-27.jpg",
          alt: "Slide 27 from 0-Module-LSB1-2.pdf comparing human and Rhodopseudomonas cytochrome c",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Homo vs Rhodobacter Pal.",
          slideBullets: ["RMSD 0.13 nm", "29% sequence identity", "Structural similarity remains visible"],
          title: "Structure can remain close near the twilight zone",
          comment: "This example again shows low sequence identity but strong structural similarity, setting up why sequence alignment alone can misplace important residues.",
          teaching: "Study interpretation: use structure as an independent check on sequence-based inference.",
          remember: "Low identity examples must be interpreted with aligned sites, not identity alone.",
        },
        {
          label: "Binding sites shifted",
          page: 28,
          image: "../lb1-slides/00-module-overview/slide-28.jpg",
          alt: "Slide 28 from 0-Module-LSB1-2.pdf showing shifted binding sites in sequence versus structural alignment",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Sequence vs Structure (II)",
          slideBullets: ["29% identity", "Binding sites shifted", "Sequence alignment needs fixing", "Structural alignment reveals the issue"],
          title: "A global hit can misplace functional sites",
          comment: "The deck shows that all binding sites can shift under a naive sequence alignment, even when the structures are similar.",
          teaching: "Study interpretation: this is the exam trap: global similarity does not guarantee local functional correspondence.",
          remember: "Check whether important residues align to important residues.",
          trap: "Do not transfer active/binding-site annotation from a shifted alignment.",
        },
        {
          label: "Very remote case",
          page: 29,
          image: "../lb1-slides/00-module-overview/slide-29.jpg",
          alt: "Slide 29 from 0-Module-LSB1-2.pdf comparing human cytochrome c and Arabidopsis cytochrome c6A",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Homo vs Arabidopsis",
          slideBullets: ["RMSD 0.35 nm", "13% sequence identity", "Very low sequence identity", "Structure still provides evidence"],
          title: "At very low identity, sequence and structure can diverge strongly",
          comment: "The Arabidopsis example pushes the lesson further: at 13% identity, structural comparison may still show a relationship, but pairwise sequence alignment becomes much less reliable.",
          teaching: "Study interpretation: this motivates multiple alignments and profile methods as better evidence sources.",
          remember: "The lower the identity, the more you need structural/profile/context evidence.",
          trap: "Do not use a low-identity sequence alignment as if it were residue-level truth.",
        },
        {
          label: "Better alignment",
          page: 30,
          image: "../lb1-slides/00-module-overview/slide-30.jpg",
          alt: "Slide 30 from 0-Module-LSB1-2.pdf motivating better alignments and profile information",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Search for better alignment",
          slideBullets: ["Use multiple sequences and structures", "Detect position-specific constraints", "Represent family patterns"],
          title: "This is the bridge to profiles and HMMs",
          comment: "The overview ends by motivating multiple alignments and position-specific information. That is exactly what profile HMMs formalize later.",
          teaching: "Study interpretation: the HMM chapters are not isolated math; they are a solution to a biological pattern-recognition problem.",
          remember: "Profiles capture what a family conserves, tolerates and deletes at each position.",
          trap: "Do not describe profile HMMs as just 'BLAST but stronger'. They encode position-specific match, insert and delete behavior.",
        },
        {
          label: "Search for better alignment",
          page: 31,
          image: "../lb1-slides/00-module-overview/slide-31.jpg",
          alt: "Slide 31 from 0-Module-LSB1-2.pdf explaining why simple sequence alignment is insufficient at low identity",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Search for Better Alignment",
          slideBullets: ["Low identity makes sequence alignment insufficient", "Important residues are not treated specially", "Use multiple structures/sequences", "Need position-specific information"],
          title: "The final slide states the reason for the rest of the module",
          comment: "The deck closes by asking why sequence alignment is insufficient at low identity: it treats positions generically and does not know which sites are important. The solution is richer evidence from multiple sequences, structures and profiles.",
          teaching: "Study interpretation: this is the conceptual handoff to multiple alignments, profile HMMs and HMMER.",
          remember: "Better alignment means position-aware, family-aware and structure-aware evidence.",
          trap: "Do not expect one pairwise sequence alignment to recover important residues in remote homologs.",
          prompt: "How does this slide justify the next lessons on MSA and profile HMMs?",
        },
      ],
    },
  ],
  miniLabs: [
    {
      title: "Annotation transfer audit",
      goal: "Practice deciding how much annotation you are allowed to transfer from a known protein to an unknown sequence.",
      steps: [
        "Write a one-line claim: family membership, broad function, exact activity, localization or binding specificity.",
        "List the evidence you would need: sequence identity, aligned coverage, conserved residues, domain boundaries, structure or curated source.",
        "Downgrade the claim if the evidence only supports a broader statement.",
      ],
      output: "A cautious annotation sentence plus one caveat.",
      check: "Strong answers separate 'same family' from 'same exact function'.",
      trap: "The unsafe move is transferring the most specific annotation because the hit looks similar.",
    },
    {
      title: "Twilight-zone explainer",
      goal: "Turn a vague threshold rule into a biological explanation.",
      steps: [
        "Explain why sequence identity drops as proteins diverge.",
        "Explain why fold, active-site geometry or domain architecture can remain recognizable.",
        "State which extra methods help: structure alignment, multiple alignment, profiles and statistical significance.",
      ],
      output: "A 5-sentence oral answer suitable for a quick exam prompt.",
      check: "You should mention both the power and the limits of structural similarity.",
      trap: "Avoid saying low sequence identity proves homology or disproves it by itself.",
    },
    {
      title: "Choose your LB1 route",
      goal: "Use the course map to pick a study path for a concrete goal.",
      steps: [
        "Pick one goal: exam, Kunitz project, HMM theory or variant interpretation.",
        "Choose the next four lessons in order.",
        "For each lesson, write the one concept you must carry forward.",
      ],
      output: "A personal route with four lesson codes and four carry-forward concepts.",
      check: "The best routes preserve prerequisites: alignments before profiles, profiles before HMMER, mapping before final interpretation.",
    },
    {
      title: "Comparative-model confidence check",
      goal: "Practice deciding what a predicted structure can safely be used for.",
      steps: [
        "Choose a target-template pair and write the sequence identity and aligned coverage you would want to know.",
        "State whether the model is suitable for fold-level reasoning, domain placement, active-site interpretation or atom-level claims.",
        "Add one quality-control step: template choice, alignment inspection or model evaluation.",
      ],
      output: "A confidence-limited modeling claim.",
      check: "Strong answers scale the claim to the evidence: fold-level claims are easier than atomic mechanism claims.",
      trap: "Do not trust a predicted structure for detailed functional claims when the alignment is low-confidence.",
    },
    {
      title: "Cytochrome alignment triage",
      goal: "Use the three cytochrome examples to decide when sequence alignment is enough and when structure/profile evidence is needed.",
      steps: [
        "Classify the high-identity human/horse case as safe, the 28-29% cases as needing refinement, and the 13% case as remote.",
        "For each case, state whether binding-site positions are conserved, shifted or uncertain.",
        "Write the safest annotation transfer you would make.",
      ],
      output: "A three-row evidence table: identity, RMSD, site alignment, safe inference.",
      check: "The correct answer pays attention to functional-site alignment, not only global sequence identity.",
      trap: "Do not transfer binding-site details when the sequence alignment shifts important residues.",
    },
  ],
  checkpoints: [
    {
      question: "What does Capriotti expect you to be able to do beyond running tools?",
      answer: "You should explain what each tool assumes, what input it uses, what output it produces, and how that output supports or does not support a biological inference.",
    },
    {
      question: "Why is transfer of knowledge conditional?",
      answer: "Because similarity does not automatically imply identical function. The transfer is stronger when the proteins belong to the same family, preserve relevant residues or structures, and the source annotation is reliable.",
    },
    {
      question: "Why does the course move from alignments to HMMs and HMMER?",
      answer: "Alignments reveal conserved and variable family patterns. HMMs and profile HMMs turn those patterns into probabilistic models that can search databases and detect remote homologs more sensitively.",
    },
    {
      question: "Which route should you use if your goal is the Kunitz project?",
      answer: "Start with multiple alignments and profile HMMs, then study HMMER, then the Kunitz project, and finally mapping problems so hits and domain annotations are interpreted carefully.",
    },
  ],
  modelAnswer: {
    question: "What is the main logic of Laboratory of Bioinformatics I?",
    answer: "LB1 teaches how to connect biological questions to computational evidence. The course starts from sequence and structure analysis, then uses alignments to detect conserved family patterns, introduces probabilistic models and HMMs, applies profile HMMs through HMMER and the Kunitz-domain project, and finishes with mapping, structure analysis, complexes and variants. The central skill is not only running a tool, but explaining why the method is appropriate, what assumptions it makes, and how confidently its output can support functional annotation.",
  },
  sourceNotes: [
    "Primary source: 0-Module-LSB1-2.pdf in the Capriotti LB1 Drive folder.",
    "Supporting source folders for transcriptions and recordings are linked, but this first pass avoids transcript-specific quotes unless a class match is verified.",
    "All 31 slide screenshots were extracted from the source PDF and are shown with slide/page labels.",
  ],
};
