export const lessonContent = {
  id: "lb1-00-module-overview",
  extractionStatus: "real slide screenshots extracted from 0-Module-LSB1-2.pdf",
  whyThisMatters: "LB1 is not a list of tools to memorize. The course asks you to connect a biological question to a computational method, then defend what can and cannot be inferred from sequence, structure, alignments, probabilistic models and database evidence.",
  objectives: [
    "Explain the main aims of the Capriotti module: sequence/structure analysis tools, functional annotation, probabilistic models, HMMs, HMMER and applied protein reasoning.",
    "Place each deck in the course route from structural bioinformatics to profile-HMM project work and protein applications.",
    "State what it means to transfer knowledge from known proteins to an unknown sequence under explicit constraints.",
    "Choose a study route depending on whether the immediate target is exam preparation, HMM understanding, the Kunitz project or structure/function reasoning.",
    "Avoid treating tool output as biological truth without checking model assumptions, evidence quality and annotation scope.",
  ],
  coreConcepts: [
    {
      title: "Tools answer biological questions",
      body: "The guide should always start from the biological problem: compare structures, infer family membership, search homologs, map annotations, reason about complexes or predict variant effects. A method is useful only when its assumptions fit that problem.",
      keywords: ["question first", "method choice", "assumptions"],
    },
    {
      title: "Transfer of knowledge is conditional",
      body: "Functional annotation by similarity is strongest when proteins belong to the same family, preserve relevant residues or structures, and are supported by reliable prior annotation. Similarity alone is evidence, not proof.",
      keywords: ["family", "evidence", "annotation"],
    },
    {
      title: "Structure can preserve signal",
      body: "Protein structures can remain similar even when sequence identity is low. That is why structural alignment, RMSD and fold-level reasoning can recover relationships missed by simple sequence comparison.",
      keywords: ["fold", "RMSD", "low identity"],
    },
    {
      title: "Profiles beat one-sequence thinking",
      body: "Multiple alignments and profile HMMs use a family-level pattern: conserved positions, tolerated substitutions and indel tendencies. This is stronger than searching with one sequence and one substitution matrix.",
      keywords: ["MSA", "profile HMM", "family model"],
    },
    {
      title: "Probabilities need interpretation",
      body: "Model-based sequence analysis asks different questions: how likely is a sequence under a model, which model explains a sequence, and which hidden path best explains the observed symbols.",
      keywords: ["likelihood", "Bayes", "hidden path"],
    },
    {
      title: "Applications return to biology",
      body: "Mapping, complexes and variants are where computational evidence must be translated back into residues, structures, interactions, function and disease relevance.",
      keywords: ["mapping", "interfaces", "variants"],
    },
  ],
  routeSteps: [
    {
      title: "Structural foundations",
      body: "Start with structure alignment and multiple alignments. Learn what similarity means before using it to transfer annotation.",
    },
    {
      title: "Model-based sequence analysis",
      body: "Move to probabilistic models, HMMs and profile HMMs. Keep observed sequence, hidden path and model parameters separate.",
    },
    {
      title: "HMMER and the Kunitz project",
      body: "Use family profiles in practice: build a model, search databases, inspect hits and justify why the Kunitz domain is a good target.",
    },
    {
      title: "Annotation and applications",
      body: "Finish with mapping, structure analysis, complexes and variants. The final skill is explaining what the evidence supports biologically.",
    },
  ],
  walkthroughSections: [
    {
      range: "Slides 1-3",
      title: "What this module is trying to teach",
      intro: "Read the overview deck as the contract for the module. It tells you that LB1 is about understanding tools for biological inference, not only pressing buttons.",
      slides: [
        {
          label: "Course overview",
          page: 1,
          image: "/lb1-slides/00-module-overview/slide-01.jpg",
          alt: "Slide 1 from 0-Module-LSB1-2.pdf introducing Laboratory of Bioinformatics I Module 2",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Laboratory of Bioinformatics I - Module 2",
          slideBullets: ["Introduction and basic concepts", "Sequence and structure analysis", "Protein functional annotation"],
          title: "Sequence and structure analysis tools",
          comment: "The course begins with the toolkit: methods for analyzing biological sequences and structures, then uses those tools to support functional annotation and problem solving.",
          teaching: "Study interpretation: when you learn a tool, write down the biological question it answers and the evidence it produces.",
          remember: "A good answer names the method, the input, the output and the biological interpretation.",
          prompt: "Give an example of a biological question that requires structure analysis rather than sequence search alone.",
        },
        {
          label: "Main aims",
          page: 2,
          image: "/lb1-slides/00-module-overview/slide-02.jpg",
          alt: "Slide 2 from 0-Module-LSB1-2.pdf listing the main aims of the module",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Main aims",
          slideBullets: ["Tools for sequence/structure analysis and development", "Protein functional annotation", "Machine-learning background", "Problem-solving and basic tools"],
          title: "Functional annotation is evidence transfer",
          comment: "The overview frames functional annotation as a central aim. That means inferring properties of an unknown protein from known sequences, structures, domains or families.",
          teaching: "Study interpretation: transfer is valid only under constraints such as same family, conserved region, similar structure and reliable source annotation.",
          remember: "Do not write 'similar sequence therefore same function' without stating the conditions.",
          trap: "The classic trap is over-annotation: transferring a precise function from weak similarity or from a different domain context.",
        },
        {
          label: "Topic map",
          page: 3,
          image: "/lb1-slides/00-module-overview/slide-03.jpg",
          alt: "Slide 3 from 0-Module-LSB1-2.pdf listing the module topics",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Topics",
          slideBullets: ["Structural alignment and MSA", "HMMs, profile HMMs and HMMER", "Mapping and structure analysis", "Machine learning, prediction and project work"],
          title: "The course route is a dependency graph",
          comment: "The topic slide gives the chronological path: structures and alignments first, probabilistic models next, then HMMER/project work and biological applications.",
          teaching: "Study interpretation: do not study HMMER before you can explain what a profile represents and what an alignment has conserved.",
          remember: "Each later tool depends on an earlier concept: correspondence, conservation, probability, significance and annotation scope.",
          prompt: "Which earlier ideas do you need before you can justify a profile-HMM database hit?",
        },
      ],
    },
    {
      range: "Slides 4-12",
      title: "Why structure enters before the HMM chapters",
      intro: "The overview deck uses structure as the first high-yield example of evidence that can survive sequence divergence.",
      slides: [
        {
          label: "Structural bioinformatics",
          page: 4,
          image: "/lb1-slides/00-module-overview/slide-04.jpg",
          alt: "Slide 4 from 0-Module-LSB1-2.pdf introducing structural alignment concepts",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Structural alignment",
          slideBullets: ["Protein structure can be more conserved than sequence", "Compare structures through a correspondence and a transformation", "Use RMSD and aligned length carefully"],
          title: "Structure alignment before profile modeling",
          comment: "Protein geometrical features, structural alignment and multiple alignments come first because they define what similarity and conservation mean.",
          teaching: "Study interpretation: if you cannot explain correspondence, RMSD or conserved positions, HMMER hits will feel like unexplained magic.",
          remember: "Structure and alignment concepts are the vocabulary for later family models.",
          prompt: "Why can a structural comparison be informative when sequence identity is low?",
        },
        {
          label: "Sequence alignment recap",
          page: 6,
          image: "/lb1-slides/00-module-overview/slide-06.jpg",
          alt: "Slide 6 from 0-Module-LSB1-2.pdf reviewing sequence alignment scoring ideas",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Sequence alignment",
          slideBullets: ["Substitution scores", "Gap penalties", "Global/local dynamic programming", "Statistical significance"],
          title: "Pairwise alignment is the scoring baseline",
          comment: "The deck revisits substitution matrices, positive/zero/negative scores, gap penalties and dynamic programming because profile methods are built on this scoring intuition.",
          teaching: "Study interpretation: an alignment score is not only a number; it is a sum of biological assumptions about substitutions and gaps.",
          remember: "Before profiles, you need to know what a simple alignment rewards, penalizes and ignores.",
          trap: "Do not interpret a raw score without asking whether it is statistically significant for the search space.",
        },
        {
          label: "Twilight zone",
          page: 10,
          image: "/lb1-slides/00-module-overview/slide-10.jpg",
          alt: "Slide 10 from 0-Module-LSB1-2.pdf about sequence identity and structural similarity",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Sequence identity and structure similarity",
          slideBullets: ["High identity usually supports structural similarity", "Low identity can still preserve fold", "Remote homologs require stronger evidence"],
          title: "Identity thresholds are not magic buttons",
          comment: "The overview stresses that high sequence identity often allows transfer of structural information, but remote homologs can share structure at low identity.",
          teaching: "Study interpretation: sequence identity is a confidence clue, not an automatic permission to transfer every annotation.",
          remember: "At low identity, combine evidence: aligned region, conserved residues, structural fold, profile support and statistical significance.",
          trap: "Do not say 'below 30 percent identity means unrelated'. The course uses low-identity structural examples precisely to break that shortcut.",
          prompt: "How would you explain the twilight-zone problem in one exam paragraph?",
        },
      ],
    },
    {
      range: "Slides 13-24",
      title: "Transfer of knowledge: useful, powerful, dangerous",
      intro: "A major hidden theme of the overview is annotation discipline: what can you safely infer from a similar protein?",
      slides: [
        {
          label: "Annotation transfer",
          page: 13,
          image: "/lb1-slides/00-module-overview/slide-13.jpg",
          alt: "Slide 13 from 0-Module-LSB1-2.pdf about transferring information from known proteins",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Transfer of information",
          slideBullets: ["Known sequence or structure", "Unknown target", "Transfer only when evidence supports it"],
          title: "Annotation transfer needs constraints",
          comment: "The deck moves from similarity to annotation, showing that functional information can be transferred only when the similarity is relevant to the property being transferred.",
          teaching: "Study interpretation: an exam answer should mention source reliability, family/domain context and conservation of functional residues.",
          remember: "Transfer the right level of annotation: family may be safe when precise activity is not.",
          trap: "Do not transfer subcellular localization, binding specificity or exact enzymatic role from weak or partial similarity.",
          prompt: "What evidence would make a transferred annotation more reliable?",
        },
        {
          label: "Counterexamples",
          page: 17,
          image: "/lb1-slides/00-module-overview/slide-17.jpg",
          alt: "Slide 17 from 0-Module-LSB1-2.pdf showing annotation-transfer caveats",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Same family, different function",
          slideBullets: ["Similar proteins can diverge in function", "Domain context matters", "Annotations can be too specific"],
          title: "The deck teaches by warning you",
          comment: "Examples such as related proteins with different functional roles are meant to stop you from treating similarity as a full functional proof.",
          teaching: "Study interpretation: the professor's likely target is your reasoning, not whether you can repeat one example name.",
          remember: "Similarity supports hypotheses; curated evidence and conserved mechanism make them stronger.",
          trap: "Do not ignore negative evidence such as missing catalytic residues, changed binding sites or different cellular context.",
        },
      ],
    },
    {
      range: "Slides 25-end",
      title: "From better alignments to the rest of LB1",
      intro: "The final overview logic is that single pairwise comparisons are often not enough. The rest of the course builds richer family and structure-aware evidence.",
      slides: [
        {
          label: "Cytochrome C cases",
          page: 25,
          image: "/lb1-slides/00-module-overview/slide-25.jpg",
          alt: "Slide 25 from 0-Module-LSB1-2.pdf with a cytochrome C comparison example",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Similar structures, shifted details",
          slideBullets: ["Compare sequence and structure", "Look at binding or active regions", "Do not overread global similarity"],
          title: "Global similarity and local function are different questions",
          comment: "The cytochrome-style examples show why you should inspect the part of the protein that matters for the biological question, not only the global alignment.",
          teaching: "Study interpretation: when function depends on a site, ask whether that site is aligned and conserved.",
          remember: "A good workflow checks both overall relationship and local functional evidence.",
          prompt: "Why can two proteins be globally similar but still differ in a functionally important detail?",
        },
        {
          label: "Better alignment",
          page: 30,
          image: "/lb1-slides/00-module-overview/slide-30.jpg",
          alt: "Slide 30 from 0-Module-LSB1-2.pdf motivating better alignments and profile information",
          deckLabel: "0-Module-LSB1-2.pdf",
          slideTitle: "Search for better alignment",
          slideBullets: ["Use multiple sequences and structures", "Detect position-specific constraints", "Represent family patterns"],
          title: "This is the bridge to profiles and HMMs",
          comment: "The overview ends by motivating multiple alignments and position-specific information. That is exactly what profile HMMs formalize later.",
          teaching: "Study interpretation: the HMM chapters are not isolated math; they are a solution to a biological pattern-recognition problem.",
          remember: "Profiles capture what a family conserves, tolerates and deletes at each position.",
          trap: "Do not describe profile HMMs as just 'BLAST but stronger'. They encode position-specific match, insert and delete behavior.",
        },
      ],
    },
  ],
  miniLabs: [
    {
      title: "Annotation transfer audit",
      goal: "Practice deciding how much annotation you are allowed to transfer from a known protein to an unknown sequence.",
      steps: [
        "Write a one-line claim: family membership, broad function, exact activity, localization or binding specificity.",
        "List the evidence you would need: sequence identity, aligned coverage, conserved residues, domain boundaries, structure or curated source.",
        "Downgrade the claim if the evidence only supports a broader statement.",
      ],
      output: "A cautious annotation sentence plus one caveat.",
      check: "Strong answers separate 'same family' from 'same exact function'.",
      trap: "The unsafe move is transferring the most specific annotation because the hit looks similar.",
    },
    {
      title: "Twilight-zone explainer",
      goal: "Turn a vague threshold rule into a biological explanation.",
      steps: [
        "Explain why sequence identity drops as proteins diverge.",
        "Explain why fold, active-site geometry or domain architecture can remain recognizable.",
        "State which extra methods help: structure alignment, multiple alignment, profiles and statistical significance.",
      ],
      output: "A 5-sentence oral answer suitable for a quick exam prompt.",
      check: "You should mention both the power and the limits of structural similarity.",
      trap: "Avoid saying low sequence identity proves homology or disproves it by itself.",
    },
    {
      title: "Choose your LB1 route",
      goal: "Use the course map to pick a study path for a concrete goal.",
      steps: [
        "Pick one goal: exam, Kunitz project, HMM theory or variant interpretation.",
        "Choose the next four lessons in order.",
        "For each lesson, write the one concept you must carry forward.",
      ],
      output: "A personal route with four lesson codes and four carry-forward concepts.",
      check: "The best routes preserve prerequisites: alignments before profiles, profiles before HMMER, mapping before final interpretation.",
    },
  ],
  checkpoints: [
    {
      question: "What does Capriotti expect you to be able to do beyond running tools?",
      answer: "You should explain what each tool assumes, what input it uses, what output it produces, and how that output supports or does not support a biological inference.",
    },
    {
      question: "Why is transfer of knowledge conditional?",
      answer: "Because similarity does not automatically imply identical function. The transfer is stronger when the proteins belong to the same family, preserve relevant residues or structures, and the source annotation is reliable.",
    },
    {
      question: "Why does the course move from alignments to HMMs and HMMER?",
      answer: "Alignments reveal conserved and variable family patterns. HMMs and profile HMMs turn those patterns into probabilistic models that can search databases and detect remote homologs more sensitively.",
    },
    {
      question: "Which route should you use if your goal is the Kunitz project?",
      answer: "Start with multiple alignments and profile HMMs, then study HMMER, then the Kunitz project, and finally mapping problems so hits and domain annotations are interpreted carefully.",
    },
  ],
  modelAnswer: {
    question: "What is the main logic of Laboratory of Bioinformatics I?",
    answer: "LB1 teaches how to connect biological questions to computational evidence. The course starts from sequence and structure analysis, then uses alignments to detect conserved family patterns, introduces probabilistic models and HMMs, applies profile HMMs through HMMER and the Kunitz-domain project, and finishes with mapping, structure analysis, complexes and variants. The central skill is not only running a tool, but explaining why the method is appropriate, what assumptions it makes, and how confidently its output can support functional annotation.",
  },
  sourceNotes: [
    "Primary source: 0-Module-LSB1-2.pdf in the Capriotti LB1 Drive folder.",
    "Supporting source folders for transcriptions and recordings are linked, but this first pass avoids transcript-specific quotes unless a class match is verified.",
    "Curated slide screenshots were extracted from the source PDF and are shown with slide/page labels; use the PDF link for the complete deck.",
  ],
};
