export const AG_SOURCE_FOLDER =
  "https://drive.google.com/drive/folders/1pVJWcKkzsFhUuYXKdrO0wPqNRW-5_zuY";

export const AG_TRANSCRIPT_FOLDER =
  "https://drive.google.com/drive/folders/1uHiEwDxCwRd7ntMcamNOLy6hF-swgcAQ";

export const AG_SOURCE_FILES = [
  { title: "Introduction to the course.pdf", driveId: "1X5TcBk-I5CbiLcVlkrCzZjUw_ya63tfy" },
  { title: "Lecture 1.pdf", driveId: "1GGqi8rrq0Z8ORBogw3fD3OLkyrkuX8UF" },
  { title: "lecture 2.pdf", driveId: "1x9tHG-Kqd4VjU6xeO8Qze67k6ZU4LDL3" },
  { title: "lecture 3.pdf", driveId: "1m65lSmHUiNJGnw1Q_3C_tPeRdC2PKEL4" },
  { title: "Lecture 4.pdf", driveId: "1bay_I_LbVKbVRXm2P8XVHx-iVRpgRiWL" },
  { title: "Lecture 6.pdf", driveId: "1HAkFM_QXEkiJKLB75un9pXbpA2YSYgzf" },
  { title: "Lecture 7.pdf", driveId: "15NDDFJWx7IrNTOvofUTrdoJg4djvYSHp" },
  { title: "Lecture 8.pdf", driveId: "1vg6217xrGBXeHiBpZDRUV5bRGZBmnlmr" },
  { title: "Lecture 9.pdf", driveId: "1LjHBqmL4HcCqa8kyJcDm3tSWttSlNe7u" },
  { title: "Lecture 10.pdf", driveId: "1sWhbrBeIUgxjLqOc8gkjy3CFZeGwZST5" },
  { title: "Lecture 11.pdf", driveId: "1uh1Jb5XDBNi0Nam1m3Mo0TTMciQTgcz5" },
  { title: "Lecture 12.pdf", driveId: "1WaMS62rtxK909jD2ic1It768b5bKFZ-b" },
  { title: "Lecture 13.pdf", driveId: "1BMhbocY8foIlMWgYpdWKpfjL0cIi7G9t" },
  { title: "Lecture 14.pdf", driveId: "18NVbdsGiseBo9vVX00VOAMGXJAX7xdfT" },
  { title: "PlanningGenomicProject.pdf", driveId: "1SN0AtCCsmILc1RAKJgo_wcEyq1IDvwPn" },
  { title: "Final_exam.pdf", driveId: "1CDomzIsd0k464D8yyEhYRswpg4cpRucT" },
  { title: "Applied Genomics - examples of questions.docx", driveId: "11rUA-WR9zhw6whNWzVoOJ92mUn-3N68f" },
];

export const AG_SLIDE_SELECTION = [
  { id: "final-exam-format", source: "Final_exam.pdf", page: 3, topic: "Written exam format", asset: "ag-slides/final-exam-format-p003.webp" },
  { id: "intro-course-program", source: "Introduction to the course.pdf", page: 10, topic: "Chronological course program", asset: "ag-slides/intro-course-program-p010.webp" },
  { id: "intro-assessment", source: "Introduction to the course.pdf", page: 11, topic: "Assessment and project components", asset: "ag-slides/intro-assessment-p011.webp" },
  { id: "lecture01-alleles", source: "Lecture 1.pdf", page: 11, topic: "Gene, allele, genotype and phenotype", asset: "ag-slides/lecture01-alleles-p011.webp" },
  { id: "lecture01-plink-fam", source: "Lecture 1.pdf", page: 13, topic: "Sample metadata in PLINK .fam", asset: "ag-slides/lecture01-plink-fam-p013.webp" },
  { id: "lecture01-popgen", source: "Lecture 1.pdf", page: 43, topic: "Population genetics frame", asset: "ag-slides/lecture01-popgen-p043.webp" },
  { id: "lecture01-allele-freq", source: "Lecture 1.pdf", page: 44, topic: "Allele and genotype frequencies", asset: "ag-slides/lecture01-allele-freq-p044.webp" },
  { id: "lecture01-hwe-formula", source: "Lecture 1.pdf", page: 45, topic: "Hardy-Weinberg formula", asset: "ag-slides/lecture01-hwe-formula-p045.webp" },
  { id: "lecture01-hwe-assumptions", source: "Lecture 1.pdf", page: 47, topic: "Hardy-Weinberg assumptions", asset: "ag-slides/lecture01-hwe-assumptions-p047.webp" },
  { id: "lecture02-sanger-ngs", source: "lecture 2.pdf", page: 6, topic: "Sanger sequencing vs NGS", asset: "ag-slides/lecture02-sanger-ngs-p006.webp" },
  { id: "lecture02-cost-capacity", source: "lecture 2.pdf", page: 12, topic: "Cost per genome and sequencing capacity", asset: "ag-slides/lecture02-cost-capacity-p012.webp" },
  { id: "lecture02-ion-torrent", source: "lecture 2.pdf", page: 17, topic: "Ion Torrent sequencing", asset: "ag-slides/lecture02-ion-torrent-p017.webp" },
  { id: "lecture02-ion-data-flow", source: "lecture 2.pdf", page: 57, topic: "Ion Torrent data flow and output files", asset: "ag-slides/lecture02-ion-data-flow-p057.webp" },
  { id: "lecture02-file-definitions", source: "lecture 2.pdf", page: 58, topic: "Common NGS file definitions", asset: "ag-slides/lecture02-file-definitions-p058.webp" },
  { id: "lecture03-454-pyro", source: "lecture 3.pdf", page: 5, topic: "Roche 454 pyrosequencing principle", asset: "ag-slides/lecture03-454-pyro-p005.webp" },
  { id: "lecture03-solid-overview", source: "lecture 3.pdf", page: 8, topic: "ABI SOLiD ligation chemistry", asset: "ag-slides/lecture03-solid-overview-p008.webp" },
  { id: "lecture03-illumina-bridge", source: "lecture 3.pdf", page: 33, topic: "Illumina bridge amplification", asset: "ag-slides/lecture03-illumina-bridge-p033.webp" },
  { id: "lecture03-flowcells", source: "lecture 3.pdf", page: 38, topic: "Random vs patterned Illumina flow cells", asset: "ag-slides/lecture03-flowcells-p038.webp" },
  { id: "lecture03-illumina-sbs", source: "lecture 3.pdf", page: 43, topic: "Illumina reversible terminator chemistry", asset: "ag-slides/lecture03-illumina-sbs-p043.webp" },
  { id: "lecture03-sbs-readout", source: "lecture 3.pdf", page: 44, topic: "Sequencing by synthesis readout", asset: "ag-slides/lecture03-sbs-readout-p044.webp" },
  { id: "lecture03-nanopore-principle", source: "lecture 3.pdf", page: 81, topic: "Nanopore direct real-time sequencing", asset: "ag-slides/lecture03-nanopore-principle-p081.webp" },
  { id: "lecture03-nanopore-signal", source: "lecture 3.pdf", page: 85, topic: "Nanopore current signal interpretation", asset: "ag-slides/lecture03-nanopore-signal-p085.webp" },
  { id: "lecture03-pacbio-smrt", source: "lecture 3.pdf", page: 93, topic: "PacBio SMRT sequencing", asset: "ag-slides/lecture03-pacbio-smrt-p093.webp" },
  { id: "lecture03-pacbio-ccs", source: "lecture 3.pdf", page: 97, topic: "PacBio circular consensus sequencing", asset: "ag-slides/lecture03-pacbio-ccs-p097.webp" },
  { id: "lecture03-pacbio-accuracy", source: "lecture 3.pdf", page: 100, topic: "Long-read accuracy comparison", asset: "ag-slides/lecture03-pacbio-accuracy-p100.webp" },
  { id: "lecture04-dna-requirements", source: "Lecture 4.pdf", page: 9, topic: "DNA requirements for NGS", asset: "ag-slides/lecture04-dna-requirements-p009.webp" },
  { id: "lecture04-dna-purity-260280", source: "Lecture 4.pdf", page: 10, topic: "DNA purity: 260/280 ratio", asset: "ag-slides/lecture04-dna-purity-260280-p010.webp" },
  { id: "lecture04-sequencing-report", source: "Lecture 4.pdf", page: 15, topic: "Sequencing report and expected data output", asset: "ag-slides/lecture04-sequencing-report-p015.webp" },
  { id: "lecture04-coverage-depth", source: "Lecture 4.pdf", page: 16, topic: "Depth and breadth of coverage", asset: "ag-slides/lecture04-coverage-depth-p016.webp" },
  { id: "lecture04-variant-pipeline", source: "Lecture 4.pdf", page: 31, topic: "Simple variant-discovery pipeline", asset: "ag-slides/lecture04-variant-pipeline-p031.webp" },
  { id: "lecture04-alignment-bwa", source: "Lecture 4.pdf", page: 33, topic: "Read alignment with BWA and BAM output", asset: "ag-slides/lecture04-alignment-bwa-p033.webp" },
  { id: "lecture04-fastq-format", source: "Lecture 4.pdf", page: 44, topic: "FASTQ four-line record", asset: "ag-slides/lecture04-fastq-format-p044.webp" },
  { id: "lecture04-phred", source: "Lecture 4.pdf", page: 46, topic: "Phred quality score", asset: "ag-slides/lecture04-phred-p046.webp" },
  { id: "lecture04-paired-end-files", source: "Lecture 4.pdf", page: 50, topic: "Paired-end sequencing FASTQ files", asset: "ag-slides/lecture04-paired-end-files-p050.webp" },
  { id: "lecture04-preprocessing-pipeline", source: "Lecture 4.pdf", page: 52, topic: "Pre-processing and QC tools", asset: "ag-slides/lecture04-preprocessing-pipeline-p052.webp" },
  { id: "lecture04-fastqc-trimming", source: "Lecture 4.pdf", page: 58, topic: "Bad per-base quality: trimming required", asset: "ag-slides/lecture04-fastqc-trimming-p058.webp" },
  { id: "lecture04-gc-content", source: "Lecture 4.pdf", page: 61, topic: "GC content distribution in FastQC", asset: "ag-slides/lecture04-gc-content-p061.webp" },
  { id: "lecture04-vcf-fields", source: "Lecture 4.pdf", page: 85, topic: "VCF fields and sample genotypes", asset: "ag-slides/lecture04-vcf-fields-p085.webp" },
  { id: "lecture04-fastqc-quality", source: "Lecture 4.pdf", page: 39, topic: "FastQC per-base sequence quality", asset: "ag-slides/lecture04-fastqc-quality-p039.webp" },
  { id: "lecture04-sam-cigar", source: "Lecture 4.pdf", page: 60, topic: "SAM/BAM and CIGAR strings", asset: "ag-slides/lecture04-sam-cigar-p060.webp" },
  { id: "lecture06-mapping-assembly", source: "Lecture 6.pdf", page: 4, topic: "Mapping versus de novo assembly", asset: "ag-slides/lecture06-mapping-assembly-p004.webp" },
  { id: "lecture06-do-you-need-assembly", source: "Lecture 6.pdf", page: 5, topic: "Do you really need an assembled genome?", asset: "ag-slides/lecture06-do-you-need-assembly-p005.webp" },
  { id: "lecture06-shotgun", source: "Lecture 6.pdf", page: 6, topic: "Shotgun method for sequence assembly", asset: "ag-slides/lecture06-shotgun-p006.webp" },
  { id: "lecture06-genome-size", source: "Lecture 6.pdf", page: 12, topic: "Genome size and coverage planning", asset: "ag-slides/lecture06-genome-size-p012.webp" },
  { id: "lecture06-workflow-design", source: "Lecture 6.pdf", page: 23, topic: "Experimental workflow design for assembly", asset: "ag-slides/lecture06-workflow-design-p023.webp" },
  { id: "lecture06-sgs-tgs", source: "Lecture 6.pdf", page: 27, topic: "Short-read versus long-read assembly", asset: "ag-slides/lecture06-sgs-tgs-p027.webp" },
  { id: "lecture06-assemble-quality", source: "Lecture 6.pdf", page: 31, topic: "Assembly pipeline and validation", asset: "ag-slides/lecture06-assemble-quality-p031.webp" },
  { id: "lecture06-olc", source: "Lecture 6.pdf", page: 42, topic: "Overlap-layout-consensus approach", asset: "ag-slides/lecture06-olc-p042.webp" },
  { id: "lecture06-dbg-kmers", source: "Lecture 6.pdf", page: 44, topic: "de Bruijn graph and k-mers", asset: "ag-slides/lecture06-dbg-kmers-p044.webp" },
  { id: "lecture06-mate-pair", source: "Lecture 6.pdf", page: 60, topic: "Mate-pair sequencing for scaffolding", asset: "ag-slides/lecture06-mate-pair-p060.webp" },
  { id: "lecture06-long-read-assembly", source: "Lecture 6.pdf", page: 61, topic: "Long-read genome assembly", asset: "ag-slides/lecture06-long-read-assembly-p061.webp" },
  { id: "lecture06-polishing", source: "Lecture 6.pdf", page: 64, topic: "Assembly polishing", asset: "ag-slides/lecture06-polishing-p064.webp" },
  { id: "lecture06-n50-example", source: "Lecture 6.pdf", page: 68, topic: "Worked N50 calculation", asset: "ag-slides/lecture06-n50-example-p068.webp" },
  { id: "lecture06-dbg", source: "Lecture 6.pdf", page: 52, topic: "de Bruijn graph and Eulerian path", asset: "ag-slides/lecture06-dbg-p052.webp" },
  { id: "lecture06-n50", source: "Lecture 6.pdf", page: 67, topic: "N50 calculation", asset: "ag-slides/lecture06-n50-p067.webp" },
  { id: "lecture07-n50-gene-sized", source: "Lecture 7.pdf", page: 3, topic: "N50 and gene-sized scaffolds", asset: "ag-slides/lecture07-n50-gene-sized-p003.webp" },
  { id: "lecture07-genome-gene-coverage", source: "Lecture 7.pdf", page: 6, topic: "Genome coverage versus gene coverage", asset: "ag-slides/lecture07-genome-gene-coverage-p006.webp" },
  { id: "lecture07-busco-metrics", source: "Lecture 7.pdf", page: 8, topic: "BUSCO notation: C, D, F and M", asset: "ag-slides/lecture07-busco-metrics-p008.webp" },
  { id: "lecture07-annotation-main-steps", source: "Lecture 7.pdf", page: 11, topic: "Main steps of genome annotation", asset: "ag-slides/lecture07-annotation-main-steps-p011.webp" },
  { id: "lecture07-genome-annotation-def", source: "Lecture 7.pdf", page: 12, topic: "Genome annotation definition", asset: "ag-slides/lecture07-genome-annotation-def-p012.webp" },
  { id: "lecture07-repeat-annotation", source: "Lecture 7.pdf", page: 13, topic: "Repeat identification and masking", asset: "ag-slides/lecture07-repeat-annotation-p013.webp" },
  { id: "lecture07-te-problems", source: "Lecture 7.pdf", page: 16, topic: "Why repeats are difficult to annotate", asset: "ag-slides/lecture07-te-problems-p016.webp" },
  { id: "lecture07-structural-annotation", source: "Lecture 7.pdf", page: 28, topic: "Structural annotation approaches", asset: "ag-slides/lecture07-structural-annotation-p028.webp" },
  { id: "lecture07-eukaryote-orf", source: "Lecture 7.pdf", page: 32, topic: "Why eukaryotic gene prediction is harder", asset: "ag-slides/lecture07-eukaryote-orf-p032.webp" },
  { id: "lecture07-annotation-targets", source: "Lecture 7.pdf", page: 43, topic: "Annotation targets beyond protein-coding genes", asset: "ag-slides/lecture07-annotation-targets-p043.webp" },
  { id: "lecture07-gff-fields", source: "Lecture 7.pdf", page: 48, topic: "GFF fields", asset: "ag-slides/lecture07-gff-fields-p048.webp" },
  { id: "lecture07-gff-example", source: "Lecture 7.pdf", page: 49, topic: "Example GFF3 gene annotation", asset: "ag-slides/lecture07-gff-example-p049.webp" },
  { id: "lecture07-bed", source: "Lecture 7.pdf", page: 50, topic: "BED feature-coordinate format", asset: "ag-slides/lecture07-bed-p050.webp" },
  { id: "lecture07-functional-annotation", source: "Lecture 7.pdf", page: 52, topic: "Functional annotation", asset: "ag-slides/lecture07-functional-annotation-p052.webp" },
  { id: "lecture07-data-submission", source: "Lecture 7.pdf", page: 54, topic: "Data submission to public repositories", asset: "ag-slides/lecture07-data-submission-p054.webp" },
  { id: "lecture07-busco", source: "Lecture 7.pdf", page: 7, topic: "BUSCO completeness", asset: "ag-slides/lecture07-busco-p007.webp" },
  { id: "lecture07-gff", source: "Lecture 7.pdf", page: 48, topic: "GFF3 annotation fields", asset: "ag-slides/lecture07-gff-p048.webp" },
  { id: "lecture08-galaxy-workflow", source: "Lecture 8.pdf", page: 27, topic: "Galaxy variant-calling workflow", asset: "ag-slides/lecture08-galaxy-workflow-p027.webp" },
  { id: "lecture09-ngs-applications", source: "Lecture 9.pdf", page: 4, topic: "NGS application types", asset: "ag-slides/lecture09-ngs-applications-p004.webp" },
  { id: "lecture10-plink-files", source: "Lecture 10.pdf", page: 6, topic: "PLINK PED/MAP and BED/BIM/FAM", asset: "ag-slides/lecture10-plink-files-p006.webp" },
  { id: "lecture11-acgh", source: "Lecture 11.pdf", page: 40, topic: "aCGH and CNV detection", asset: "ag-slides/lecture11-acgh-p040.webp" },
  { id: "lecture12-roh", source: "Lecture 12.pdf", page: 68, topic: "Runs of homozygosity", asset: "ag-slides/lecture12-roh-p068.webp" },
  { id: "lecture13-gwas-design", source: "Lecture 13.pdf", page: 12, topic: "GWAS design issues", asset: "ag-slides/lecture13-gwas-design-p012.webp" },
  { id: "lecture13-manhattan", source: "Lecture 13.pdf", page: 17, topic: "Manhattan plot output", asset: "ag-slides/lecture13-manhattan-p017.webp" },
  { id: "lecture13-ora", source: "Lecture 13.pdf", page: 76, topic: "Over-representation analysis", asset: "ag-slides/lecture13-ora-p076.webp" },
  { id: "lecture14-plink-gwas", source: "Lecture 14.pdf", page: 70, topic: "GWAS with PLINK", asset: "ag-slides/lecture14-plink-gwas-p070.webp" },
  { id: "project-design", source: "PlanningGenomicProject.pdf", page: 4, topic: "Project plan structure", asset: "ag-slides/project-design-p004.webp" },
];

export function driveFileUrl(driveId) {
  return `https://drive.google.com/file/d/${driveId}/view`;
}
