import { AG_SLIDE_SELECTION } from "./agSources.js";

const slideById = Object.fromEntries(AG_SLIDE_SELECTION.map((slide) => [slide.id, slide]));

export const AG_PROGRESS_KEY = "ag_progress_v1";

export const AG_GUIDE_SECTIONS = [
  {
    id: "exam-orientation",
    number: 0,
    title: "Exam orientation",
    sources: ["Final_exam.pdf", "Introduction to the course.pdf", "Applied Genomics - examples of questions.docx"],
    slides: ["final-exam-format", "intro-course-program", "intro-assessment"],
    studyBlocks: [
      {
        title: "How the written exam is built",
        slide: "final-exam-format",
        what: "The written test is not a long essay exam: it is a 60-minute written test with 30 questions. The official format is 25 closed-answer multiple-choice questions plus 5 short written-answer questions. Passing requires at least 22 correct answers and submission of the genomic project.",
        why: "This changes how to study. Multiple choice rewards precise distinctions between similar concepts, while short answers reward a compact explanation with the key formula, method or biological interpretation.",
        examFocus: "Do not spend the last two days memorizing every slide. Train the question formats: definition questions, technology-identification questions, file-format questions, plot-interpretation questions and calculation exercises.",
        answerTemplate: "For a short answer, use this structure: define the term, name the input/output, state why it is used, then add one limitation or exam-relevant caveat.",
        traps: [
          "The practice examples are representative of the wording style: one correct option only, with distractors that look plausible.",
          "Project submission is part of the exam pipeline. Do not prepare the written test as if the project/interview did not exist.",
        ],
      },
      {
        title: "Why the course order matters",
        slide: "intro-course-program",
        what: "The course is deliberately chronological: genetics foundations first, then NGS technologies, then NGS data analysis, assembly and annotation, applications, genotyping/population genomics, GWAS and software/project design.",
        why: "Many exam questions combine lectures. For example, a GWAS question needs genetics, genotyping, population structure, multiple testing and post-GWAS interpretation. A genome assembly question needs sequencing technology, read length, repeats, N50 and BUSCO.",
        examFocus: "When revising, connect the lectures rather than treating each PDF as isolated. The professor’s sample questions mix definitions, technologies, file formats and downstream analysis outputs.",
        answerTemplate: "If asked to explain a workflow, answer in chronological order: biological question -> sample/DNA/RNA -> technology -> raw data -> QC -> analysis -> biological interpretation.",
      },
      {
        title: "How to use this guide in two days",
        slide: "intro-assessment",
        what: "The official evaluation includes written exam, genomic project and interview/project discussion. The project must contain introduction, aim, materials and methods, expected results/impact and a cost table.",
        why: "Even when you study for MCQs, keep project logic in mind: the course is applied genomics, so method choice, sample design, platform choice and realistic budget matter.",
        examFocus: "For the first pass, prioritize topics seen in sample/past questions: allele, Sanger, Ion Torrent, FASTQ, SAM, SOLiD, PacBio, Illumina, LD, inbreeding, ROH, CIGAR, BWA, paired-end, VCF, annotation, de Bruijn/Eulerian path, GWAS, BUSCO, HWE, MDS and ORA.",
        exercise: {
          prompt: "Two-day drill: name 5 topics that are likely to be asked as definitions and 3 topics that are likely to be asked as calculations.",
          answer: "Definitions: allele, LD, ROH, BUSCO, SAM/FASTQ/VCF, GWAS, ORA, aCGH. Calculations: coverage, N50 and Hardy-Weinberg equilibrium.",
        },
      },
    ],
    bullets: [
      "Written exam: 30 questions in 60 minutes, with 25 close-answer multiple-choice questions and 5 short written-answer questions.",
      "Pass condition: at least 22 correct answers out of 30 and genomic project submission.",
      "Multiple-choice prep: distinguish similar technologies, files, plots and biological concepts.",
      "Short-answer prep: define the method, identify input/output and state the reason for using it.",
      "The fastest high-yield loop is: read guide block -> inspect original slide -> answer a mini question -> verify with practice exam.",
    ],
    remember: "For the next 2 days, prioritize objective exam targets: coverage, N50, HWE, Manhattan plot, LD, BUSCO, FASTQ/SAM/VCF, PLINK files, CNV/aCGH and GWAS design.",
    traps: [
      "Do not prepare only for MCQs. The 5 written answers reward compact explanations, not memorized slide text.",
      "Do not ignore the project. The exam file ties written-test eligibility to project submission and the interview/project part affects the final score.",
    ],
    checklist: ["Open the practice exam once before reviewing.", "Mark all formulas for a same-day redo.", "Prepare a 60-second explanation of your project aim and method choice."],
  },
  {
    id: "foundations",
    number: 1,
    title: "Foundations of genetics and genomics",
    sources: ["Lecture 1.pdf", "Applied Genomics - examples of questions.docx"],
    slides: ["lecture01-alleles", "lecture01-plink-fam", "lecture01-popgen", "lecture01-allele-freq", "lecture01-hwe-formula", "lecture01-hwe-assumptions"],
    studyBlocks: [
      {
        title: "Gene, allele, genotype and phenotype",
        slide: "lecture01-alleles",
        what: "The slide gives the foundational vocabulary: Mendel’s particulate heredity elements are genes; different forms of the same gene are alleles; genotype is the genetic constitution; phenotype is the observable property of an organism.",
        why: "Several later topics rely on these words. GWAS associates genotype with phenotype; HWE predicts genotype frequencies from allele frequencies; population genomics tracks alleles across groups.",
        examFocus: "Past exam wording explicitly includes 'definition of allele'. The safest answer is: an allele is an alternative form of a gene or locus, not an entire chromosome, not a phenotype and not a sequencing read.",
        answerTemplate: "An allele is one of the alternative forms of a gene or genetic locus. A genotype is the allele combination carried by an individual, while the phenotype is the observed trait.",
        traps: ["Do not define allele as a mutation only. A mutant allele can be an allele, but allele is a broader term."],
      },
      {
        title: "Why sample metadata already looks like genomics",
        slide: "lecture01-plink-fam",
        what: "The .fam example stores family ID, individual ID, father, mother, sex and phenotype. Even before population genomics software is introduced, the course is already linking individuals, pedigrees and phenotypes to genotype data.",
        why: "This prepares you for PLINK, GWAS and population stratification. A GWAS is not only a list of SNPs; it is a matrix of genotypes attached to sample identity, phenotype and often pedigree/population information.",
        examFocus: "If a question asks why phenotype definition matters, connect it to this structure: the phenotype column is what the genotypes will be tested against.",
        answerTemplate: "Genomic analyses require both molecular data and sample metadata. Without correct individual IDs, pedigree/sex information and phenotype labels, association or population analyses can be invalid.",
      },
      {
        title: "Population genetics as the bridge to applied genomics",
        slide: "lecture01-popgen",
        what: "Population genetics studies the genetic composition of groups of individuals and how this composition changes over time. The focus shifts from a single organism to the gene pool of a population.",
        why: "This is why the course later asks about HWE, MDS, ROH, LD and GWAS. These are population-level tools: they interpret genome-wide variation across many individuals.",
        examFocus: "When asked why population structure matters, say that individuals are not independent genetic points if ancestry differs. Structure can produce false associations in GWAS.",
        answerTemplate: "Population genetics provides the allele-frequency logic behind population genomics. It allows us to describe variation, test equilibrium assumptions and detect structure, selection or inbreeding.",
      },
      {
        title: "Allele and genotype frequency calculations",
        slide: "lecture01-allele-freq",
        what: "Allele frequency is the number of copies of a specific allele divided by the total number of alleles. Genotype frequency is the number of individuals with a genotype divided by the total number of individuals.",
        why: "This is the first step in HWE exercises and also appears implicitly in MAF filtering, GWAS quality control and population comparisons.",
        examFocus: "For diploids, total alleles = 2N. Homozygotes contribute two copies of their allele; heterozygotes contribute one copy of each allele.",
        answerTemplate: "For 500 AA, 200 Aa and 300 aa, A copies = 2*500 + 200 = 1200, total alleles = 2000, so p = 0.6 and q = 0.4.",
        exercise: {
          prompt: "If a population has 30 AA, 40 Aa and 30 aa individuals, calculate p and q.",
          answer: "Total alleles = 200. A copies = 2*30 + 40 = 100, so p = 0.5. a copies = 100, so q = 0.5.",
        },
      },
      {
        title: "Hardy-Weinberg equilibrium",
        slide: "lecture01-hwe-formula",
        what: "The formula expands (p + q)^2 = 1 into p^2 + 2pq + q^2 = 1. These terms correspond to expected genotype frequencies AA, Aa and aa under Hardy-Weinberg assumptions.",
        why: "HWE is both a conceptual population-genetics model and a practical quality-control check in genomic datasets. Large deviations can mean biology, structure, selection, non-random mating or technical problems.",
        examFocus: "Past questions include a full HWE calculation. Show p and q first, calculate expected counts, then compare observed vs expected. A short qualitative statement is not enough if numbers are provided.",
        answerTemplate: "Under HWE, genotype frequencies are p^2, 2pq and q^2. After calculating allele frequencies, multiply these expected frequencies by the number of individuals and compare them with observed counts.",
      },
      {
        title: "HWE assumptions and why deviations are informative",
        slide: "lecture01-hwe-assumptions",
        what: "The slide lists the assumptions: diploid organisms, sexual reproduction, non-overlapping generations, random mating, infinitely large population, equal allele frequencies in sexes, no migration/gene flow/admixture/mutation/selection.",
        why: "Real populations often violate at least one assumption. That is why deviations from HWE can be informative but also why they must be interpreted carefully.",
        examFocus: "For an open question, do not just write the formula. Mention at least random mating, no selection, no migration and large population size, then explain what a deviation may imply.",
        answerTemplate: "A population is in Hardy-Weinberg equilibrium when allele and genotype frequencies remain stable across generations under ideal assumptions. If observed and expected genotype counts differ strongly, the population is not in HWE.",
        traps: ["Do not conclude 'not in HWE' only because one genotype is common. You must compare observed counts to expected counts derived from p and q."],
      },
    ],
    bullets: [
      "Allele = alternative form of a gene/locus; genotype = allele combination; phenotype = observable trait.",
      "Population genetics moves the focus from individual inheritance to allele/genotype frequencies in groups.",
      "For a diploid locus, allele frequency uses 2N total allele copies.",
      "HWE expected genotype frequencies are p^2, 2pq and q^2.",
      "HWE deviations may reflect population structure, inbreeding, selection, migration, mutation, non-random mating or genotyping problems.",
      "These definitions are not isolated: they support LD, MDS, ROH and GWAS interpretation later in the course.",
    ],
    remember: "Know the definitions cold, then practice converting genotype counts into allele frequencies and expected HWE counts.",
    formulas: [
      {
        title: "Hardy-Weinberg equilibrium",
        expression: "p + q = 1; expected genotypes = p^2, 2pq, q^2",
        variables: ["p = frequency of allele A", "q = frequency of allele a", "N = number of diploid individuals"],
        example: "If p = 0.6 and q = 0.4 in 1000 individuals, expected AA = 360, Aa = 480, aa = 160.",
      },
    ],
    exercises: [
      {
        prompt: "Sample-question drill: 500 AA, 200 Aa, 300 aa. Calculate p and q, then expected counts.",
        answer: "Total alleles = 2000. A alleles = 2*500 + 200 = 1200, so p = 0.60; q = 0.40. Expected counts: AA = 0.36*1000 = 360, Aa = 0.48*1000 = 480, aa = 0.16*1000 = 160. Observed differs strongly, so the population is not in HWE.",
      },
    ],
  },
  {
    id: "ngs-tech-i",
    number: 2,
    title: "NGS technologies I",
    sources: ["lecture 2.pdf", "lecture 3.pdf", "Transcript AG - 25-11-12 Mod_1"],
    slides: ["lecture02-sanger-ngs", "lecture02-cost-capacity", "lecture02-ion-torrent", "lecture02-ion-data-flow", "lecture03-illumina-bridge", "lecture03-flowcells", "lecture03-illumina-sbs", "lecture03-sbs-readout"],
    studyBlocks: [
      {
        title: "Sanger sequencing versus NGS",
        slide: "lecture02-sanger-ngs",
        what: "Sanger sequencing is the first-generation chain-termination method. The NGS conceptual change is massive parallelization: instead of sequencing one DNA fragment at a time, millions of DNA molecules/fragments are sequenced in parallel.",
        why: "This explains why NGS changed genomics: it reduced cost per base, increased throughput and made whole-genome resequencing, variant discovery and large-scale studies practical.",
        examFocus: "Past questions explicitly test Sanger as a chain-termination method. If the answer options include ligation, H+ release or real-time single-molecule sequencing, those belong to other platforms.",
        answerTemplate: "Sanger is based on dideoxy chain termination. NGS differs because it sequences many molecules in parallel, producing large numbers of short or long reads depending on the platform.",
        traps: ["Do not say Sanger is an NGS technology. It is first-generation sequencing."],
      },
      {
        title: "Cost, throughput and the project-design mindset",
        slide: "lecture02-cost-capacity",
        what: "The slide links technology history to falling cost per genome and increasing sequencing capacity. The key point is not only that sequencing became cheaper; it became scalable enough for population and applied-genomics questions.",
        why: "This connects directly to the genomic project. Platform choice is constrained by budget, required coverage, genome size, number of samples and the type of result needed.",
        examFocus: "If asked which technology is appropriate, do not choose by brand alone. Mention read length, throughput, accuracy, cost and the biological question.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor emphasized that running sequencing as a service is not only buying a machine: maintenance, servers, alignment of the system and technical support are major practical constraints.",
        },
        answerTemplate: "A good platform choice balances genome size, desired depth, read length, expected error profile, number of samples and budget.",
      },
      {
        title: "Ion Torrent: nucleotide incorporation detected as pH change",
        slide: "lecture02-ion-torrent",
        what: "Ion Torrent detects the hydrogen ion released when a nucleotide is incorporated. The signal is electronic/pH-based rather than optical fluorescence-based.",
        why: "It is a classic MCQ topic because the principle is easy to confuse with Roche 454 pyrosequencing, which detects light generated from pyrophosphate chemistry.",
        examFocus: "Past questions mention exactly this: when a nucleotide is incorporated, H+ is released. That is Ion Torrent.",
        answerTemplate: "Ion Torrent sequencing detects H+ ions released during nucleotide incorporation; the pH change is converted into a sequencing signal.",
        traps: [
          "Do not answer 'light signal' for Ion Torrent. Light/pyrogram language points to 454 pyrosequencing.",
          "Homopolymer regions are a known error-prone context because signal intensity must be translated into the number of repeated bases.",
        ],
      },
      {
        title: "From instrument output to files",
        slide: "lecture02-ion-data-flow",
        what: "The slide shows that sequencing is followed by data processing, base calling, filtering and alignment/variant-calling outputs. Even a technology lecture already introduces FASTQ, BAM and VCF as downstream products.",
        why: "File-format questions are frequent because they test whether you understand the pipeline order: raw reads first, alignments second, variants after that.",
        examFocus: "FASTQ = reads and qualities; SAM/BAM = alignments; VCF = variant calls. This exact distinction appears in the sample questions.",
        answerTemplate: "A sequencer produces reads that are stored with quality scores in FASTQ. After mapping, alignments are stored in SAM/BAM. After variant calling, variants and genotypes are stored in VCF.",
      },
      {
        title: "Illumina library clusters and bridge amplification",
        slide: "lecture03-illumina-bridge",
        what: "Illumina sequencing does not read a single isolated molecule directly. DNA fragments are bound to a flow cell and amplified into clusters so the imaging system can detect a strong enough signal.",
        why: "This matters because base calling depends on imaging many identical copies in each cluster. Cluster density and signal overlap affect data quality.",
        examFocus: "If an option says Illumina is a short-read, high-throughput sequencing-by-synthesis platform, that is the high-yield description.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor explained that a cluster means the DNA fragment is amplified thousands of times because the system needs enough signal; it is not sensing information from one DNA molecule only.",
        },
        answerTemplate: "Illumina uses bridge amplification to create clusters on a flow cell, followed by sequencing by synthesis with imaging-based base calling.",
      },
      {
        title: "Random versus patterned flow cells",
        slide: "lecture03-flowcells",
        what: "Earlier flow cells had randomly positioned clusters, while patterned flow cells organize cluster positions more precisely. The aim is to reduce overlap and improve imaging/base calling.",
        why: "This is the technical reason behind many Illumina improvements: better spatial control means cleaner signal detection, higher throughput and more reliable base calls.",
        examFocus: "You probably will not be asked to draw the flow cell, but it helps explain why sequencing errors and throughput depend on platform generation.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor highlighted that randomly distributed clusters can overlap in the light signal, making it harder to capture the correct base signal.",
        },
      },
      {
        title: "Reversible terminator chemistry",
        slide: "lecture03-illumina-sbs",
        what: "Illumina adds all four modified nucleotides together. Each nucleotide has a fluorescent label and a reversible blocking group, so only one base is incorporated per cycle before imaging and chemical removal of the blocker.",
        why: "This is the core logic of sequencing by synthesis. It explains why Illumina is accurate but cycle-based, and why read quality tends to decline with longer reads.",
        examFocus: "Do not confuse Illumina with Ion Torrent. Illumina uses fluorescent reversible terminators and imaging; Ion Torrent detects H+ release.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor emphasized that Illumina nucleotides are modified in two ways: one modification identifies the nucleotide by fluorescence, and another blocks further extension until it is removed.",
        },
        answerTemplate: "Illumina sequencing by synthesis repeatedly incorporates one fluorescent reversible-terminator nucleotide, images the cluster, removes the dye/blocker and continues to the next cycle.",
      },
    ],
    bullets: [
      "Sanger = first-generation chain termination; NGS = massively parallel sequencing.",
      "Ion Torrent detects H+ release during nucleotide incorporation and is classically sensitive to homopolymer interpretation.",
      "Illumina is high-throughput short-read sequencing by synthesis with cluster generation and imaging.",
      "Reversible terminators allow one base per cycle, then imaging, cleaning and the next cycle.",
      "Instrument choice depends on throughput, read length, error profile, cost, support and the research question.",
      "Data outputs begin as FASTQ and later become alignment/variant files after analysis.",
    ],
    remember: "For exam answers, compare platforms by read length, throughput, error type and the downstream question they support.",
    professorNote: {
      source: "Transcript AG - 25-11-12 Mod_1",
      text: "The professor repeatedly framed sequencing technologies as practical choices: technical support, maintenance, servers, coverage and throughput affect whether a platform is realistic for a project.",
    },
    traps: [
      "Illumina does not read one isolated molecule directly; clusters amplify the signal.",
      "Do not describe all NGS platforms as having the same error profile.",
    ],
  },
  {
    id: "ngs-tech-ii",
    number: 3,
    title: "NGS technologies II",
    sources: ["lecture 3.pdf", "Transcript AG - 25-11-12 Mod_1", "Applied Genomics - examples of questions.docx"],
    slides: ["lecture03-454-pyro", "lecture03-solid-overview", "lecture03-nanopore-principle", "lecture03-nanopore-signal", "lecture03-pacbio-smrt", "lecture03-pacbio-ccs", "lecture03-pacbio-accuracy"],
    studyBlocks: [
      {
        title: "Roche 454: pyrosequencing and light signal",
        slide: "lecture03-454-pyro",
        what: "454 sequencing is based on pyrosequencing. When a nucleotide is incorporated, pyrophosphate is released and converted through enzymatic reactions into a light signal recorded as peaks in a pyrogram.",
        why: "It is historically important and conceptually useful because it contrasts with Ion Torrent: both involve nucleotide-by-nucleotide incorporation, but the measured signal differs.",
        examFocus: "If the wording mentions pyrophosphate, luciferase, light or pyrogram, think Roche 454/pyrosequencing rather than Ion Torrent.",
        answerTemplate: "Roche 454 uses pyrosequencing: nucleotide incorporation releases PPi, which is converted into a light signal used to infer the DNA sequence.",
        traps: ["Do not call Roche 454 the long-read technology typically selected today for de novo genome assembly. In exam MCQs, PacBio is the expected modern long-read answer."],
      },
      {
        title: "ABI SOLiD: sequencing by ligation and two-base encoding",
        slide: "lecture03-solid-overview",
        what: "SOLiD uses ligation chemistry rather than polymerase-driven sequencing by synthesis. Its hallmark is two-base encoding, where each color call contains information about adjacent bases.",
        why: "This is a common trap because the technology is not commonly used today, but it is still a distinctive exam definition.",
        examFocus: "Past questions explicitly list ABI SOLiD as a two-base encoding system. If you see 'sequencing by ligation', that points to SOLiD.",
        answerTemplate: "ABI SOLiD is a short-read sequencing-by-ligation platform known for two-base encoding, not for H+ detection or single-molecule long reads.",
      },
      {
        title: "Nanopore: current signal through a pore",
        slide: "lecture03-nanopore-principle",
        what: "Nanopore sequencing passes DNA or RNA through a protein nanopore and detects changes in ionic current. The signal is decoded into sequence by base-calling algorithms.",
        why: "It is different from synthesis-based platforms: there is no cycle of nucleotide incorporation, imaging and washing. This enables direct, real-time sequencing and very long reads.",
        examFocus: "Nanopore is a long-read platform. If asked about portability or direct real-time DNA/RNA sequencing, Nanopore is the key example.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor emphasized that the key point in Nanopore is translating complex current changes into sequence; modern algorithms reduced the historically high error rate.",
        },
        answerTemplate: "Oxford Nanopore detects changes in electrical current as nucleic acids pass through a pore, enabling real-time long-read sequencing.",
      },
      {
        title: "Nanopore signal interpretation and error profile",
        slide: "lecture03-nanopore-signal",
        what: "The current signal is not a simple one-base-one-signal system; it reflects the nucleotides occupying the pore and must be decoded computationally.",
        why: "This explains why error rates historically depended strongly on base calling and why improvements in algorithms can improve sequencing accuracy without changing the basic biological sample.",
        examFocus: "For project design, Nanopore can be useful for rapid checks, field/portable sequencing and long-read assembly, but error profile and polishing strategy matter.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor noted that even when long-read error rates are higher than Illumina, they can still be useful for genome assembly because the main need is to place large puzzle pieces across repeats.",
        },
        traps: ["Do not say long reads are always more accurate than short reads. The advantage is length and structural context; accuracy depends on platform and correction strategy."],
      },
      {
        title: "PacBio SMRT sequencing",
        slide: "lecture03-pacbio-smrt",
        what: "PacBio SMRT sequencing observes single DNA polymerases in zero-mode waveguides. Modified nucleotides emit light during incorporation, and the system records base incorporation in real time.",
        why: "PacBio is a high-yield answer for long reads and de novo genome assembly because reads can span repetitive regions and structural variants.",
        examFocus: "The sample multiple-choice question asks which technology produces long reads often used in de novo genome assembly. The expected answer is PacBio.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor described PacBio nucleotides as modified on the longer pyrophosphate tail so the incorporation signal can be captured in real time.",
        },
        answerTemplate: "PacBio SMRT sequencing is a single-molecule real-time long-read technology useful for de novo genome assembly because long reads span repeats and complex regions.",
      },
      {
        title: "Circular consensus sequencing corrects random errors",
        slide: "lecture03-pacbio-ccs",
        what: "PacBio circular consensus sequencing ligates adapters to create a circular template and sequences the same insert multiple times. Repeated passes allow a consensus sequence to be built.",
        why: "This is the key to HiFi reads: if errors are mostly random, repeated sequencing of the same molecule makes it unlikely that the same wrong base appears in the same position every pass.",
        examFocus: "For an open answer, connect long read length to assembly and CCS/HiFi to accuracy improvement.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor stressed that PacBio errors are random enough that multiple passes through a circularized molecule allow software to correct the sequence by consensus.",
        },
        answerTemplate: "PacBio CCS/HiFi improves accuracy by sequencing the same circularized DNA insert multiple times and building a consensus from independent subreads.",
      },
      {
        title: "Choosing long reads for complex genomes",
        slide: "lecture03-pacbio-accuracy",
        what: "The comparison slide summarizes the trade-off: short reads are very accurate but short; long-read platforms generate larger pieces of the genome puzzle and can resolve repeats, phasing and structural variation.",
        why: "This is exactly why long reads are linked to de novo assembly in the exam. Assembly of complex genomes is limited by repeats and structural complexity, not just by the number of bases sequenced.",
        examFocus: "If the question asks 'often used in de novo genome assembly', choose a long-read platform, especially PacBio in the provided sample options.",
        answerTemplate: "Long reads are useful in de novo assembly because they span repetitive regions and connect genomic segments that short reads cannot uniquely place.",
        traps: ["Do not choose Illumina for the sample MCQ asking specifically about long reads for de novo assembly. Illumina is short-read/high-throughput."],
      },
    ],
    bullets: [
      "Roche 454 = pyrosequencing, PPi release and light/pyrogram signal.",
      "ABI SOLiD = sequencing by ligation and two-base encoding.",
      "Nanopore = direct current changes through a pore, real-time and portable long-read sequencing.",
      "PacBio SMRT = single-molecule real-time sequencing in zero-mode waveguides.",
      "PacBio CCS/HiFi improves accuracy through repeated passes of the same circularized insert.",
      "Long reads help de novo genome assembly because they span repeats and preserve long-range context.",
    ],
    remember: "If the question says de novo assembly of a complex genome, long reads are usually the high-yield answer; in the sample MCQ, PacBio is the correct choice.",
    professorNote: {
      source: "Transcript AG - 25-11-12 Mod_1",
      text: "Long reads were framed as bigger puzzle pieces: rougher at first, but very useful for placing repetitive regions, phasing variation and then polishing or correcting errors.",
    },
    traps: [
      "PacBio and Nanopore are both long-read technologies, but their signal generation is different.",
      "Nanopore portability is a practical project-design point, not just a technical curiosity.",
    ],
  },
  {
    id: "ngs-data-primers",
    number: 4,
    title: "NGS data analysis primers",
    sources: ["Lecture 4.pdf", "AG - 25-11-24 Mod_1", "AG - 25-11-26 Mod_1", "AG - 25-11-28 Mod_1", "Applied Genomics - examples of questions.docx"],
    slides: [
      "lecture04-dna-requirements",
      "lecture04-sequencing-report",
      "lecture04-coverage-depth",
      "lecture04-variant-pipeline",
      "lecture04-fastq-format",
      "lecture04-phred",
      "lecture04-paired-end-files",
      "lecture04-preprocessing-pipeline",
      "lecture04-fastqc-quality",
      "lecture04-fastqc-trimming",
      "lecture04-sam-cigar",
      "lecture04-vcf-fields",
    ],
    studyBlocks: [
      {
        title: "Before analysis: understand what you have",
        slide: "lecture04-dna-requirements",
        what: "The lecture starts before the FASTQ file. DNA concentration, purity and integrity affect library preparation and sequencing. A bioinformatician should ask for the project rationale, sample information, DNA quality, sequencing platform, read length, insert size, library type and expected coverage before launching a pipeline.",
        why: "The same raw-looking dataset can have different constraints depending on whether it came from ancient DNA, amplicon sequencing, WGS, RNA-seq or a long-read assembly project. The wrong assumptions lead to technically coherent but biologically wrong results.",
        examFocus: "This is the professor's recurring practical warning: do not start data analysis blindly. For exam answers, connect wet-lab choices to computational choices: technology, library preparation and DNA quality determine which tools and filters are appropriate.",
        answerTemplate: "Before analysing NGS data, I would ask why the data were produced, which sample and species they represent, which platform/library was used, the read layout and expected coverage, and whether the DNA passed quality checks.",
        professorNote: {
          source: "Transcript AG - 25-11-24 Mod_1",
          text: "The professor stressed that you should not move directly to analysis: first ask for the project, sequencing details and DNA quality, otherwise results can make computational sense but be biologically wrong.",
        },
        traps: [
          "Do not treat FASTQ as enough metadata. A FASTQ file tells you reads and qualities, not whether the experiment design makes sense.",
          "Ancient or degraded DNA is a bad match for long-read assembly unless quality and fragment length are compatible.",
        ],
      },
      {
        title: "Depth and breadth of sequencing coverage",
        slide: "lecture04-coverage-depth",
        what: "Depth of coverage is the average number of times each base is sequenced. Breadth of coverage is the fraction of the target genome covered at a given depth. The slide formalizes depth as LN/G, where L is read length, N is the number of reads and G is haploid genome size.",
        why: "Coverage is both an exam calculation and a project-planning tool. If the genome is large or the desired depth is high, the required number of gigabases and cost increase quickly.",
        examFocus: "The sample exam includes a direct coverage exercise. Always write the formula, substitute units consistently, and report the answer as x coverage.",
        answerTemplate: "Average depth = total sequenced bases / genome size = (number of reads x read length) / haploid genome length.",
        professorNote: {
          source: "Transcript AG - 25-11-26 Mod_1",
          text: "Coverage was tied to budget planning: if you know genome size, desired depth and cost per gigabase, you can estimate how many samples your project can afford.",
        },
        exercise: {
          prompt: "A 2.8 Gb genome is sequenced with 350 million paired-end read pairs of 150 bp from each end. Estimate average depth.",
          answer: "Each read pair contributes 300 bp. Sequenced bases = 350,000,000 x 300 = 105,000,000,000 bp. Depth = 105 Gb / 2.8 Gb = 37.5x.",
        },
      },
      {
        title: "The variant discovery pipeline: FASTQ -> BAM -> VCF -> annotation",
        slide: "lecture04-variant-pipeline",
        what: "The core DNA variant-discovery workflow starts with sequencing data in FASTQ, aligns reads to a reference genome, stores alignments in BAM, calls variants into VCF and finally annotates variants as intronic, missense, frameshift, regulatory and so on.",
        why: "This pipeline links several exam traps: FASTQ contains raw reads and quality; SAM/BAM contain alignments; VCF contains variant calls; annotation interprets possible biological consequences.",
        examFocus: "If the question asks which file stores alignments, the answer is SAM/BAM, not FASTQ or VCF. If it asks where inferred genotypes and variant calls are stored, the answer is VCF.",
        answerTemplate: "A simple WGS variant pipeline is: QC and trim FASTQ reads, align them to a reference with a mapper such as BWA, store alignments as BAM, filter by mapping quality, call SNPs/indels into VCF and annotate their consequences.",
        professorNote: {
          source: "Transcript AG - 25-11-28 Mod_1",
          text: "The professor summarized variant discovery as four steps: data, alignment, variant calling and annotation; he also stressed that tool name and version should be tracked for reproducibility.",
        },
        traps: [
          "Do not call a BAM file a variant file. It stores reads aligned to positions, not final variant genotypes.",
          "Different tools can give different results, so a reproducible pipeline should record tools, versions and filtering parameters.",
        ],
      },
      {
        title: "FASTQ and Phred quality scores",
        slide: "lecture04-fastq-format",
        what: "A FASTQ record has four lines: read identifier, nucleotide sequence, plus separator, and a quality string with one encoded symbol per base. The quality values are usually Phred scores, where Q = -10 log10(Perror).",
        why: "The FASTQ structure is one of the easiest multiple-choice targets. The quality line is not decorative: it allows later QC, trimming and error-aware interpretation.",
        examFocus: "Remember: Q30 means an error probability of 1/1000 and about 99.9% base-call accuracy. The quality string must have the same length as the read sequence.",
        answerTemplate: "FASTQ stores raw sequencing reads together with base-quality information. Each read is represented by four lines: ID, sequence, plus line and encoded quality values.",
        exercise: {
          prompt: "What is the probability of error for Q20 and Q30?",
          answer: "Q20: Perror = 10^(-20/10) = 0.01 = 1/100, about 99% accuracy. Q30: Perror = 10^(-30/10) = 0.001 = 1/1000, about 99.9% accuracy.",
        },
      },
      {
        title: "Paired-end sequencing files",
        slide: "lecture04-paired-end-files",
        what: "In paired-end sequencing, both ends of the same DNA fragment are sequenced. This usually produces two FASTQ files, one for read 1 and one for read 2, with reads stored in the same order so pair relationships can be reconstructed.",
        why: "Paired-end information helps alignment and later assembly because the two reads are physically linked by an insert of approximately known size.",
        examFocus: "A paired-end question is usually asking for the strategy: sequencing both ends of a fragment, not sequencing two unrelated samples.",
        answerTemplate: "Paired-end sequencing generates two reads from the two ends of the same DNA fragment, usually stored in two synchronized FASTQ files, often named R1 and R2 or _1 and _2.",
        professorNote: {
          source: "Transcript AG - 25-11-26 Mod_1",
          text: "The professor emphasized that paired-end data can return two FASTQ files, one forward and one reverse, and that the paired reads follow the same order in both files.",
        },
      },
      {
        title: "FastQC: per-base quality and trimming",
        slide: "lecture04-fastqc-quality",
        what: "FastQC summarizes read quality in modules. The per-base sequence quality module shows quality distributions at each position along the read. It often decreases toward the end of reads, especially in short-read sequencing.",
        why: "This is a known open-question target: describe the boxplot and when trimming should be applied. The boxplot summarizes the distribution of Phred scores across all reads at each base position.",
        examFocus: "Apply trimming when low-quality tails, adapters or problematic regions are present. Then rerun QC to check whether quality improved without losing too much useful data.",
        answerTemplate: "In the per-base quality plot, the x-axis is read position and the y-axis is Phred quality. Each boxplot summarizes the quality distribution for all reads at that position. If the 3-prime end drops into poor-quality zones, trimming should be applied.",
        professorNote: {
          source: "Transcript AG - 25-11-26 Mod_1",
          text: "The professor explained that if quality drops at the end of the reads, the graph is telling you that something is wrong there; after trimming, a second QC round should verify improvement.",
        },
        traps: [
          "A failed FastQC module is not always interpreted the same way across WGS, RNA-seq, amplicon or reduced-representation data.",
          "Low-quality reads can generate false SNPs because sequencing errors may be mistaken for biological variation.",
        ],
      },
      {
        title: "Alignment, mapping quality, SAM/BAM and CIGAR",
        slide: "lecture04-sam-cigar",
        what: "Alignment places each read on a reference genome. BWA is a common short-read aligner. SAM is a text alignment format, BAM is its compressed binary version, and the CIGAR string encodes how a read aligns: matches, insertions, deletions and clipping.",
        why: "The exam list includes BWA, SAM and CIGAR. These are not isolated acronyms: they belong to the alignment stage of the variant-discovery workflow.",
        examFocus: "CIGAR is about the read-reference alignment pattern, not base quality and not variant annotation. Mapping quality is a Phred-scaled confidence that the read was placed correctly.",
        answerTemplate: "After QC, reads are aligned to a reference, for example with BWA. The result is stored as SAM/BAM; the CIGAR string summarizes alignment operations such as soft clipping, matches, insertions and deletions.",
        traps: [
          "Do not confuse base quality in FASTQ with mapping quality in BAM/SAM.",
          "Repeats and low-complexity regions can reduce mapping confidence because reads may align equally well in multiple places.",
        ],
      },
      {
        title: "VCF and variant annotation",
        slide: "lecture04-vcf-fields",
        what: "VCF stores called variants and genotype information. Core columns include chromosome, position, ID, reference allele, alternate allele, quality, filter and info. Per-sample genotype fields appear after FORMAT.",
        why: "VCF is the transition from aligned reads to biological interpretation. Genotype notation such as 0|1 or 0/1 tells how the sample relates to the reference and alternate alleles; annotation tells whether a variant might affect a gene or regulatory feature.",
        examFocus: "A phased genotype such as 0|1 means one reference and one alternate allele with phase information. 0/1 is unphased heterozygous. REF and ALT are alleles, not individuals.",
        answerTemplate: "VCF contains variant calls and sample genotypes. CHROM and POS locate the variant, REF and ALT define alleles, QUAL/FILTER summarize confidence and filtering, and FORMAT/sample columns store genotype-level information.",
      },
    ],
    bullets: [
      "Start from metadata and DNA quality: project aim, species, samples, library type, platform, read length, insert size and expected coverage.",
      "Coverage formula: depth = (number of reads x read length) / haploid genome size; paired-end reads contribute both ends.",
      "FASTQ = raw reads + base qualities; SAM/BAM = alignments; VCF = variant calls and genotypes; annotation interprets variant consequences.",
      "FastQC per-base quality shows how Phred scores change along reads; trimming is used when low-quality tails or adapters would harm downstream analysis.",
      "BWA is a short-read aligner; mapping quality measures confidence of placement; CIGAR encodes alignment operations.",
      "Pipeline logic: QC -> preprocessing/trimming -> alignment -> alignment filtering -> variant calling -> variant annotation.",
    ],
    remember: "For Lecture 4, exam success is mainly file formats, coverage, FastQC/trimming, BWA/SAM/BAM/CIGAR, VCF genotype notation and the logic of the variant-discovery pipeline.",
    formulas: [
      {
        title: "Sequencing depth",
        expression: "depth = (N x L) / G",
        variables: ["N = number of reads", "L = read length", "G = haploid genome length"],
        example: "100,000,000 reads x 100 bp / 1,000,000,000 bp = 10x coverage.",
      },
      {
        title: "Phred quality",
        expression: "Q = -10 log10(Perror)",
        variables: ["Q = Phred quality score", "Perror = probability that the base call is wrong"],
        example: "Q30 means Perror = 0.001, or one expected wrong base call per 1000 bases.",
      },
    ],
    exercises: [
      {
        prompt: "A genome is 1 Gb. You obtained 100 million reads of 100 bp. Estimate average depth.",
        answer: "Depth = 100,000,000 x 100 / 1,000,000,000 = 10x.",
      },
      {
        prompt: "Classify these files: FASTQ, BAM, VCF.",
        answer: "FASTQ stores reads and quality scores. BAM stores compressed alignments to a reference. VCF stores variant calls, alleles, filters and sample genotypes.",
      },
    ],
    traps: [
      "FASTQ is not an alignment file; SAM/BAM is not a variant-call file; VCF is not a raw-read file.",
      "A nice-looking computational result can still be biologically wrong if technology, library type, contaminants or sample design were misunderstood.",
    ],
  },
  {
    id: "genome-assembly",
    number: 5,
    title: "Genome assembly",
    sources: ["Lecture 6.pdf", "AG - 25-12-10 Mod_2", "Applied Genomics - examples of questions.docx"],
    slides: [
      "lecture06-mapping-assembly",
      "lecture06-do-you-need-assembly",
      "lecture06-shotgun",
      "lecture06-genome-size",
      "lecture06-workflow-design",
      "lecture06-sgs-tgs",
      "lecture06-assemble-quality",
      "lecture06-olc",
      "lecture06-dbg-kmers",
      "lecture06-dbg-eulerian",
      "lecture06-mate-pair",
      "lecture06-long-read-assembly",
      "lecture06-polishing",
      "lecture06-n50",
      "lecture06-n50-example",
    ],
    studyBlocks: [
      {
        title: "Mapping is not the same as de novo assembly",
        slide: "lecture06-mapping-assembly",
        what: "Mapping aligns reads onto an existing reference genome. De novo assembly reconstructs the genome sequence from reads without relying on a close reference. Assembly is followed by annotation if the goal is to produce a usable genome resource.",
        why: "This distinction decides the whole workflow. If a reference exists and your aim is variant discovery, mapping may be enough. If no reference exists, you may need de novo assembly, which is more expensive and computationally demanding.",
        examFocus: "If asked 'what is next after sequencing?', the answer depends on the aim: variant discovery usually maps reads; a new genome project assembles reads first.",
        answerTemplate: "Mapping places reads on a known reference; de novo assembly reconstructs longer contigs/scaffolds directly from read overlaps or graph structure when a suitable reference is absent.",
        traps: ["Do not say every NGS project needs a new genome assembly. The lecture explicitly asks whether you really need an assembled and annotated genome."],
      },
      {
        title: "Planning an assembly project before ordering data",
        slide: "lecture06-genome-size",
        what: "Genome size determines how much sequence data is needed. The slide highlights that coverage depends on number of reads, read length and target size, and that genome size can be estimated from C-value/flow cytometry or related species.",
        why: "This connects assembly to project design and coverage exercises. Bigger genomes and repeat-rich genomes require more data, more memory and often a more careful technology mix.",
        examFocus: "Past open questions include genome-size estimation before sequencing. A safe answer mentions C-value/flow cytometry and, for sequencing-based estimation, k-mer distributions.",
        answerTemplate: "Before sequencing, estimate genome size using C-value or flow cytometry, compare with related reference genomes, and use that estimate to calculate the data needed for the desired coverage.",
        exercise: {
          prompt: "Why does a 3 Gb genome need more sequencing data than a 1 Gb genome at the same target depth?",
          answer: "Because depth = sequenced bases / genome size. At 30x, a 1 Gb genome needs 30 Gb of sequence, while a 3 Gb genome needs 90 Gb.",
        },
      },
      {
        title: "Choosing short reads, long reads or a hybrid approach",
        slide: "lecture06-sgs-tgs",
        what: "Short-read sequencing is accurate, high-throughput and cheaper, but struggles with repeats and complex heterozygous regions. Third-generation long reads from PacBio or Oxford Nanopore span repeats and increase contiguity, but raw long reads can be more expensive and error-prone.",
        why: "The exam asks which technology produces long reads used in de novo assembly. The deeper reason is that longer reads act like larger puzzle pieces and can bridge repetitive or ambiguous regions.",
        examFocus: "PacBio and Nanopore are the long-read technologies to associate with de novo assembly. Illumina is excellent for short accurate reads and polishing/hybrid correction, not the classic long-read answer.",
        answerTemplate: "For a complex de novo assembly, long reads help resolve repeats and improve contiguity; short reads can be used for low-cost high-depth correction or variant discovery. A hybrid assembly combines the strengths of both.",
        traps: [
          "Do not confuse high accuracy with high contiguity: accurate short reads can still produce fragmented assemblies in repetitive genomes.",
          "Long reads help assembly because they span repeats, not because every long read is error-free.",
        ],
      },
      {
        title: "From shotgun reads to graph-based assembly",
        slide: "lecture06-dbg-kmers",
        what: "Shotgun sequencing breaks DNA into many fragments, sequences them and reconstructs a master sequence. Older overlap-layout-consensus approaches compare reads to reads; de Bruijn graph strategies split reads into k-mers and build a graph from k-1-mers and k-mer edges.",
        why: "This is an explicit exam topic: the algorithm used in de Bruijn graph assembly is linked to an Eulerian path. You do not need to derive the full algorithm, but you must know the logic.",
        examFocus: "de Bruijn graph = k-mers; vertices are usually k-1-mers; edges are k-mers; assembly asks whether there is a path that visits every edge exactly once.",
        answerTemplate: "In a de Bruijn graph, reads are decomposed into k-mers. The graph connects k-1-mer prefixes and suffixes, and the assembled sequence is reconstructed by finding an Eulerian path through the edges.",
        professorNote: {
          source: "Transcript AG - 25-12-10 Mod_2",
          text: "The professor said he would focus on de Bruijn graph algorithms because they are the most used method to understand the algorithmic logic of assembly, rather than asking details on other approaches.",
        },
      },
      {
        title: "Paired-end, mate-pair and long reads bridge difficult regions",
        slide: "lecture06-mate-pair",
        what: "Paired-end reads provide two linked reads from the same fragment. Mate-pair libraries use larger inserts, often kilobases long, so the ends can anchor across repeats and help order/orient contigs into scaffolds. Long reads can directly span repeats.",
        why: "Assemblers often fail at repeats because multiple genomic regions look identical. Physical linkage information helps choose the correct path through ambiguous graph regions.",
        examFocus: "Paired-end and mate-pair information are not just 'two reads'. Their value is the known relationship between read ends and approximate insert size.",
        answerTemplate: "Paired-end and mate-pair reads help scaffold assemblies because the two reads come from the same DNA fragment and can link contigs across regions that are not fully sequenced or are repetitive.",
        professorNote: {
          source: "Transcript AG - 25-12-10 Mod_2",
          text: "Mate-pair sequencing was described as using larger inserts than paired-end sequencing, so the reads represent the beginning and end of a larger fragment.",
        },
      },
      {
        title: "Polishing and assembly quality checks",
        slide: "lecture06-polishing",
        what: "Assembly does not end when contigs are produced. Polishing corrects residual sequencing errors in draft assemblies, especially in long-read assemblies. Quality checks then evaluate contiguity, completeness, misassemblies and read support.",
        why: "A long contig is not automatically correct. Errors can remain because of repeats, incorrect graph paths, read errors or collapsed haplotypes.",
        examFocus: "Remember the professor's phrase: N50 measures contiguity, not correctness. Completeness is different and is evaluated with tools such as BUSCO.",
        answerTemplate: "After assembly, polishing improves base accuracy by reusing read evidence. Quality is then checked using metrics such as N50 for contiguity and BUSCO for gene-space completeness, plus read remapping and gap/misassembly inspection.",
        traps: ["High N50 can be produced by aggressive assemblers that incorrectly join regions; therefore N50 alone is not enough."],
      },
      {
        title: "N50 calculation",
        slide: "lecture06-n50-example",
        what: "To compute N50, sort contigs from longest to shortest and add their lengths until the cumulative sum reaches at least 50% of the total assembly length. The contig that crosses this halfway point defines the N50.",
        why: "This is one of the clearest calculation exercises in the exam examples. The trick is not averaging contig lengths: it is a weighted contiguity statistic.",
        examFocus: "Show the total, half of total, cumulative sum and final N50. For 100, 70, 60, 50, 50, 40 and 30 kb, the total is 400 kb, half is 200 kb, and N50 is 60 kb.",
        answerTemplate: "N50 is the length of the shortest contig needed, after sorting contigs from longest to shortest, for the cumulative length to cover at least half of the total assembly length.",
        exercise: {
          prompt: "Calculate N50 for contigs 90, 80, 30, 20 and 10 kb.",
          answer: "Total = 230 kb; half = 115 kb. Sorted already: 90 is below 115; 90 + 80 = 170 crosses 115. N50 = 80 kb.",
        },
      },
    ],
    bullets: [
      "Mapping uses an existing reference; de novo assembly reconstructs contigs/scaffolds from reads.",
      "Assembly planning requires genome size, repeat content, heterozygosity, GC bias, platform choice, coverage and computational resources.",
      "Short reads are accurate and cheap but fragment assemblies in repeats; long reads span repeats but need correction/polishing.",
      "de Bruijn graph assembly decomposes reads into k-mers and reconstructs sequence through an Eulerian path.",
      "Paired-end, mate-pair and long-read information help scaffold contigs and resolve repeated regions.",
      "N50 measures contiguity; polishing and BUSCO/completeness checks are needed to evaluate assembly quality more broadly.",
    ],
    remember: "For Lecture 6, the high-yield exam core is mapping vs assembly, genome-size/coverage planning, short vs long reads, de Bruijn graph/Eulerian path, mate-pair logic and N50 calculation.",
    formulas: [
      {
        title: "N50",
        expression: "Sort contigs longest to shortest; cumulate lengths until reaching 50% of total length.",
        variables: ["Total assembly length = sum of all contigs", "N50 = length of the contig crossing half of that total"],
        example: "100 + 70 + 60 crosses 200 kb in a 400 kb assembly, so N50 = 60 kb.",
      },
      {
        title: "Assembly coverage planning",
        expression: "sequenced bases needed = desired depth x genome size",
        variables: ["Desired depth is often much higher for assembly than for simple low-depth surveys", "Genome size should be estimated before ordering sequencing"],
        example: "For 60x coverage of a 2.5 Gb genome, plan for about 150 Gb of sequence data.",
      },
    ],
    professorNote: {
      source: "Transcript AG - 25-12-10 Mod_2",
      text: "The professor explicitly flagged assembly contiguity as a test-relevant concept and emphasized that N50 is a measure of contiguity, not correctness.",
    },
    traps: [
      "Do not answer 'Hamiltonian path' for de Bruijn graph assembly in this course context; the expected answer is Eulerian path.",
      "Do not interpret N50 as a measure of biological correctness or gene completeness.",
      "Do not choose Illumina as the long-read technology for de novo assembly MCQs; PacBio/Nanopore are the long-read options.",
    ],
  },
  {
    id: "annotation-databases",
    number: 6,
    title: "Genome annotation and databases",
    sources: ["Lecture 7.pdf", "AG - 25-12-10 Mod_2", "Applied Genomics - examples of questions.docx"],
    slides: [
      "lecture07-n50-gene-sized",
      "lecture07-genome-gene-coverage",
      "lecture07-busco",
      "lecture07-busco-metrics",
      "lecture07-annotation-main-steps",
      "lecture07-genome-annotation-def",
      "lecture07-repeat-annotation",
      "lecture07-te-problems",
      "lecture07-structural-annotation",
      "lecture07-eukaryote-orf",
      "lecture07-annotation-targets",
      "lecture07-gff-fields",
      "lecture07-gff-example",
      "lecture07-bed",
      "lecture07-functional-annotation",
      "lecture07-data-submission",
    ],
    studyBlocks: [
      {
        title: "Assembly quality beyond N50",
        slide: "lecture07-genome-gene-coverage",
        what: "Lecture 7 continues assembly evaluation. Genome coverage is the percentage of the estimated genome contained in the assembly, while gene coverage is the percentage of genes represented. They can differ because repetitive regions are hard to assemble and often gene-poor.",
        why: "This explains why N50 is not enough. A genome can have acceptable gene coverage even if some repetitive genomic regions are missing, or have a high N50 but still miss biologically important genes.",
        examFocus: "If asked about assembly quality, mention contiguity, gaps, genome coverage, gene coverage and BUSCO completeness rather than only N50.",
        answerTemplate: "Assembly quality can be evaluated by contiguity statistics such as N50, gap content, genome coverage, gene coverage and gene-space completeness using BUSCO.",
      },
      {
        title: "BUSCO completeness",
        slide: "lecture07-busco",
        what: "BUSCO stands for Benchmarking Universal Single-Copy Orthologs. It checks whether conserved genes expected to be present as single copies in a lineage are complete, duplicated, fragmented or missing in an assembly/annotation.",
        why: "BUSCO is a frequent exam target because it gives a biological measure of completeness, not just a length statistic. It asks whether expected genes can be recovered.",
        examFocus: "Know the notation: C = complete, D = duplicated, F = fragmented, M = missing, n = number of BUSCO genes used. Duplicated BUSCOs can suggest duplicated haplotypes or assembly issues.",
        answerTemplate: "BUSCO evaluates genome completeness by searching for conserved single-copy orthologs expected in a given clade and reporting complete, duplicated, fragmented and missing genes.",
        professorNote: {
          source: "Transcript AG - 25-12-10 Mod_2",
          text: "The professor framed BUSCO as asking whether expected genes can be located in the assembled genome; if not, something may have gone wrong in the assembly project.",
        },
        traps: [
          "BUSCO is not used to calculate coverage depth and not used to call variants.",
          "A high N50 and a poor BUSCO score point to different problems: contiguity may be high while gene completeness is low.",
        ],
      },
      {
        title: "What genome annotation means",
        slide: "lecture07-annotation-main-steps",
        what: "Genome annotation assigns roles and functions to genome sequence. The main steps are repeat annotation, structural annotation of genes/transcripts, functional annotation of gene products, and later submission/maintenance/refinement.",
        why: "The exam list explicitly includes structural vs functional annotation. This is a distinction you should be able to write in one or two sentences.",
        examFocus: "Structural annotation answers 'where is the feature and what is its structure?' Functional annotation answers 'what does it probably do?'.",
        answerTemplate: "Structural annotation identifies genomic features such as genes, exons, introns and transcripts. Functional annotation assigns biological meaning, such as gene name, domain, GO term or putative protein function.",
        traps: ["Do not call functional annotation the same as variant annotation. They overlap conceptually, but here genome annotation focuses on features and gene functions in an assembled genome."],
      },
      {
        title: "Repeat annotation comes first",
        slide: "lecture07-repeat-annotation",
        what: "The computation phase begins with identifying and masking repetitive elements, including low-complexity sequences and transposable elements such as LINEs, SINEs and LTR retrotransposons. Repeats can represent a large fraction of complex genomes.",
        why: "Repeats create two problems: they complicate assembly and they confuse gene prediction. If repeats are not masked, algorithms may incorrectly predict genes inside transposable elements or duplicated fragments.",
        examFocus: "For a short answer, say that repeat annotation/masking reduces false gene predictions and helps downstream structural annotation.",
        answerTemplate: "Repeat annotation identifies repetitive and transposable elements and masks or labels them so that later gene prediction is not misled by repetitive sequence.",
      },
      {
        title: "Structural annotation: predicting gene models",
        slide: "lecture07-structural-annotation",
        what: "Structural annotation determines the location and structure of protein-coding genes and transcripts. Approaches include intrinsic/ab initio prediction, extrinsic evidence-based prediction and combiners that integrate multiple sources of evidence.",
        why: "Eukaryotic gene prediction is difficult because genes are split into exons and introns, intergenic regions are large, and boundaries are consensus signals rather than perfectly fixed motifs.",
        examFocus: "If asked why annotation is harder in eukaryotes, mention introns, non-contiguous ORFs, large intergenic regions and multiple transcript models.",
        answerTemplate: "Structural annotation predicts gene and transcript coordinates using ab initio signals, evidence such as EST/RNA/protein alignments, and combiner tools that synthesize multiple predictions into gene models.",
      },
      {
        title: "Annotation targets are not only protein-coding genes",
        slide: "lecture07-annotation-targets",
        what: "The lecture emphasizes that annotation projects target transcripts broadly, not only protein-coding genes. Eukaryotic genomes also contain pseudogenes, lncRNAs, tRNAs, snoRNAs and other RNA categories.",
        why: "This prevents a common oversimplification: genome annotation is not simply scanning for long ORFs. In complex genomes, transcript models and non-coding features matter.",
        examFocus: "For the exam, know that structural annotation creates transcript/gene models and functional annotation assigns biological meaning to predicted products/features.",
        answerTemplate: "Gene annotation in complex genomes builds transcript models, including protein-coding and non-coding transcripts, rather than only identifying uninterrupted ORFs.",
      },
      {
        title: "Annotation output formats: GFF, GTF and BED",
        slide: "lecture07-gff-fields",
        what: "Annotation pipelines commonly output feature coordinates in GFF/GTF or BED-like formats. GFF contains one line per feature and nine tab-separated columns, including sequence name, source, feature type, start, end, score, strand, frame and attributes.",
        why: "These formats are the bridge between annotation and downstream analyses/visualization. They describe where features are, but usually do not contain the sequence itself.",
        examFocus: "Do not confuse annotation formats with raw sequence reads. FASTQ is reads, SAM/BAM is alignments, VCF is variants and GFF/GTF/BED are genomic features.",
        answerTemplate: "A GFF file stores genomic features as coordinate-based records, usually one feature per line with fields describing chromosome/scaffold, feature type, coordinates, strand and attributes.",
      },
      {
        title: "Functional annotation and database submission",
        slide: "lecture07-functional-annotation",
        what: "Functional annotation assigns biological information to predicted products, such as gene names, GO terms, protein domains and functional sites. This can be inferred by sequence similarity against databases or profile methods such as HMMs.",
        why: "An assembled and structurally annotated genome becomes useful only when features can be interpreted. Submission to databases such as GenBank or ENA improves findability and preserves workflow metadata.",
        examFocus: "Functional annotation is about meaning. Data submission is about making sequences, reads, assemblies and annotations available with metadata.",
        answerTemplate: "Functional annotation links predicted genes or proteins to known biological functions using similarity searches, domains, GO terms, UniProt-like databases or profile models, then results can be submitted to public repositories.",
      },
    ],
    bullets: [
      "Genome assembly evaluation includes N50, gaps, genome coverage, gene coverage and BUSCO completeness.",
      "BUSCO reports complete, duplicated, fragmented and missing conserved single-copy orthologs and is frequently asked in exams.",
      "Genome annotation has a logical order: repeat annotation -> structural annotation -> functional annotation -> submission/maintenance.",
      "Repeat masking reduces false gene predictions and is crucial in complex genomes rich in transposable elements.",
      "Structural annotation predicts feature coordinates and transcript models; functional annotation assigns biological meaning.",
      "GFF/GTF/BED are feature-coordinate formats; GenBank/ENA submissions preserve sequence and workflow metadata.",
    ],
    remember: "For Lecture 7, master BUSCO and structural vs functional annotation. These are high-yield because they appear directly in past-question lists and connect assembly quality with biological interpretation.",
    traps: [
      "Do not define BUSCO as a general alignment tool. It is a completeness assessment based on conserved single-copy orthologs.",
      "Structural annotation is not the same as functional annotation: one locates features, the other assigns meaning.",
      "Do not rely on N50 alone to say an assembly is good enough for annotation.",
    ],
  },
  {
    id: "ngs-applications",
    number: 7,
    title: "NGS applications and case studies",
    sources: ["Lecture 8.pdf", "Lecture 9.pdf", "Applied Genomics - examples of questions.docx"],
    slides: ["lecture08-galaxy-workflow", "lecture09-ngs-applications"],
    bullets: [
      "Galaxy is a web platform for accessible, reproducible and transparent analyses; the case study workflow goes FASTQ QC, trimming, BWA mapping, duplicate removal, variant calling and VEP annotation.",
      "Pool-seq sequences pooled individuals and estimates allele-frequency differences cost-effectively.",
      "Targeted sequencing and WES focus sequencing effort on selected regions, genes or exons.",
      "Bisulfite sequencing studies methylation, but C-to-T conversion must be interpreted carefully with SNPs.",
      "ChIP-seq identifies DNA regions bound by a protein or carrying a histone mark; RNA-seq measures transcript abundance and transcript structure.",
    ],
    remember: "For each application, answer: input material, biological question, main output and one analysis caveat.",
    traps: [
      "ChIP-seq is not an expression assay; it maps protein-DNA interactions or chromatin marks.",
      "RNA-seq reads usually need alignment/counting/normalization before expression interpretation.",
    ],
  },
  {
    id: "genotyping-cnvs",
    number: 8,
    title: "High-throughput genotyping, SNP arrays and CNVs",
    sources: ["Lecture 11.pdf", "Lecture 12.pdf", "Lecture 14.pdf", "Applied Genomics - examples of questions.docx"],
    slides: ["lecture11-acgh"],
    bullets: [
      "High-throughput genotyping determines genotypes at many polymorphic loci and powers GWAS, genomic selection, MAS/MAB, parentage and population genomics.",
      "Microarrays are used for large-scale genotyping because per-sample cost is low, throughput is scalable and data quality is standardized.",
      "Illumina/Affymetrix-style SNP chips call genotypes from probe signal intensity and clustering.",
      "aCGH compares labeled test and reference DNA on an array to detect copy-number gains and losses.",
      "CNVs can also be detected from sequencing using read-pair, split-read, read-depth or assembly-based approaches.",
      "Array-based genotyping assays known sites; sequencing-based approaches can discover new variants but are typically more data-intensive.",
    ],
    remember: "aCGH is a microarray-based CNV method. CNV does not automatically mean sequencing.",
    traps: ["The sample questions explicitly test that aCGH is used to detect CNVs using microarray technology."],
  },
  {
    id: "population-genomics",
    number: 9,
    title: "Population genomics",
    sources: ["Lecture 10.pdf", "Lecture 11.pdf", "Lecture 12.pdf", "Lecture 14.pdf"],
    slides: ["lecture10-plink-files", "lecture12-roh"],
    bullets: [
      "PLINK text input uses PED for individuals/genotypes/phenotypes and MAP for marker positions; binary input uses BED/BIM/FAM.",
      "QC filters include missing samples (`--mind`), missing SNPs (`--geno`), minor allele frequency (`--maf`) and HWE p-value (`--hwe`).",
      "Allele/genotype frequencies and HWE output are first-pass checks before downstream population analyses.",
      "MDS/PCA-like dimension reduction compresses many SNPs into axes that reveal population structure.",
      "ROH are uninterrupted homozygous chromosome stretches; FROH = total ROH length / autosomal genome length.",
      "FST measures population differentiation; LD measures non-random allele association at loci.",
    ],
    remember: "Population structure is both a biological result and a confounder for GWAS.",
    formulas: [
      {
        title: "Genomic inbreeding from ROH",
        expression: "FROH = SROH / LGEN",
        variables: ["SROH = summed ROH length for an individual", "LGEN = autosomal genome length considered"],
        example: "If ROH sum to 420 Mb and autosomal length is 2800 Mb, FROH = 0.15.",
      },
    ],
  },
  {
    id: "gwas",
    number: 10,
    title: "GWAS",
    sources: ["Lecture 11.pdf", "Lecture 12.pdf", "Lecture 13.pdf", "Lecture 14.pdf", "Applied Genomics - examples of questions.docx"],
    slides: ["lecture13-gwas-design", "lecture13-manhattan", "lecture13-ora", "lecture14-plink-gwas"],
    bullets: [
      "GWAS tests genetic variants across many individuals to find genotype-phenotype associations.",
      "Design starts with phenotype definition: case/control for binary traits or quantitative models for continuous traits.",
      "LD lets tag SNPs represent nearby causal variants, but it also means association is not automatically causation.",
      "Sample size, allele frequency, effect size, LD with the tested marker and multiple testing drive statistical power.",
      "Population stratification can create false associations; inspect MDS/PCA and QQ plots and use appropriate covariates/models.",
      "Manhattan plots show genomic position vs -log10(P); QQ plots diagnose inflation; Bonferroni uses alpha/N.",
      "Post-GWAS work prioritizes nearby/candidate genes, uses databases and can run ORA to test over-represented functions.",
    ],
    remember: "A good GWAS answer includes phenotype, genotype platform, QC, association model, population-structure correction, multiple testing and post-GWAS interpretation.",
    formulas: [
      {
        title: "Bonferroni correction",
        expression: "threshold = alpha / N",
        variables: ["alpha = desired experiment-wise error rate", "N = number of tests"],
        example: "For alpha = 0.05 and 20 SNPs, threshold = 0.0025.",
      },
    ],
    traps: [
      "The y-axis of a Manhattan plot is -log10(P), not raw genomic position or effect size.",
      "A significant tag SNP may be a proxy in LD with the causal variant.",
    ],
  },
  {
    id: "project-preparation",
    number: 11,
    title: "Genomic project preparation",
    sources: ["PlanningGenomicProject.pdf", "Final_exam.pdf", "Introduction to the course.pdf", "Transcript AG - 25-11-12 Mod_1"],
    slides: ["project-design"],
    bullets: [
      "The project should include introduction/problem, aim, materials and methods, expected results/impact and a cost table.",
      "The budget should cover sampling, DNA extraction, sequencing/high-throughput genotyping outsourcing and computational costs when relevant.",
      "Aim, budget, methods and expected results must fit each other; a too-large aim with a small budget is a design failure.",
      "For complex genomes, justify sample choice, DNA/RNA quality, sequencing platform, coverage, assembly/annotation or variant workflow and computing resources.",
      "For GWAS, justify phenotype definition, sample size, heritability, stratification control, genotyping/sequencing choice and post-GWAS analysis.",
      "The oral/interview can use the project as a starting point, so every method choice should have a one-sentence reason.",
    ],
    remember: "The project is not a shopping list. It is an argument that the design can answer the biological question within budget.",
    professorNote: {
      source: "Transcript AG - 25-11-12 Mod_1",
      text: "Applied genomics was framed as practical work: permissions, sample movement, field constraints and budget can decide which technology is realistic.",
    },
    traps: ["Do not plan a complex reference genome without considering DNA quality, long reads, coverage, repeats, heterozygosity and compute resources."],
  },
  {
    id: "cram-checklist",
    number: 12,
    title: "Final 2-day cram checklist",
    sources: ["Final_exam.pdf", "Applied Genomics - examples of questions.docx", "All lecture PDFs"],
    slides: [],
    bullets: [
      "Day 1: read sections 0-7 and immediately redo coverage, HWE and N50 without looking.",
      "Day 1 evening: practice explaining FASTQ, SAM/BAM, VCF, CIGAR, FastQC and BWA in one sentence each.",
      "Day 2 morning: read sections 8-11 and drill PLINK files, ROH/FROH, aCGH/CNV, GWAS design and plot interpretation.",
      "Day 2 afternoon: take the practice exam, then review wrong options as distractor training.",
      "Final hour: rehearse project aim, method choice, budget logic and expected result.",
    ],
    remember: "If time is tight, prioritize terms that appear in the sample questions and concepts that connect multiple lectures.",
    checklist: [
      "Definitions: gene, allele, genotype, phenotype, SNP, CNV, LD, ROH, FST, BUSCO.",
      "Formats: FASTQ, SAM/BAM, VCF, GFF/BED, PED/MAP, BED/BIM/FAM.",
      "Formulas: coverage, HWE, N50, Bonferroni, FROH.",
      "Plots: FastQC per-base quality, Manhattan plot, QQ plot, MDS/PCA scatter, aCGH log2 ratio.",
      "Methods: Sanger, Illumina, Ion Torrent, SOLiD, PacBio, Nanopore, Pool-seq, RNA-seq, ChIP-seq, bisulfite-seq, WES.",
    ],
    traps: [
      "Long reads are high-yield for de novo assembly because they span repeats.",
      "Multiple testing is not optional in GWAS.",
      "Genome coverage and gene coverage are related but not identical.",
    ],
  },
];

export const AG_EXAM_STATS = [
  { label: "Written questions", value: "30" },
  { label: "MCQ + short", value: "25 + 5" },
  { label: "Pass mark", value: "22/30" },
  { label: "Time", value: "60 min" },
];

export function getSlidesForSection(section) {
  return (section.slides || []).map((id) => slideById[id]).filter(Boolean);
}
