import { AG_SLIDE_SELECTION } from "./agSources.js";

const slideById = Object.fromEntries(AG_SLIDE_SELECTION.map((slide) => [slide.id, slide]));

export const AG_PROGRESS_KEY = "ag_progress_v1";

export const AG_GUIDE_SECTIONS = [
  {
    id: "exam-orientation",
    number: 0,
    title: "Exam orientation",
    sources: ["Final_exam.pdf", "Introduction to the course.pdf", "Applied Genomics - examples of questions.docx"],
    slides: ["final-exam-format", "intro-course-program", "intro-assessment"],
    studyBlocks: [
      {
        title: "How the written exam is built",
        slide: "final-exam-format",
        what: "The written test is not a long essay exam: it is a 60-minute written test with 30 questions. The official format is 25 closed-answer multiple-choice questions plus 5 short written-answer questions. Passing requires at least 22 correct answers and submission of the genomic project.",
        why: "This changes how to study. Multiple choice rewards precise distinctions between similar concepts, while short answers reward a compact explanation with the key formula, method or biological interpretation.",
        examFocus: "Do not spend the last two days memorizing every slide. Train the question formats: definition questions, technology-identification questions, file-format questions, plot-interpretation questions and calculation exercises.",
        answerTemplate: "For a short answer, use this structure: define the term, name the input/output, state why it is used, then add one limitation or exam-relevant caveat.",
        traps: [
          "The practice examples are representative of the wording style: one correct option only, with distractors that look plausible.",
          "Project submission is part of the exam pipeline. Do not prepare the written test as if the project/interview did not exist.",
        ],
      },
      {
        title: "Why the course order matters",
        slide: "intro-course-program",
        what: "The course is deliberately chronological: genetics foundations first, then NGS technologies, then NGS data analysis, assembly and annotation, applications, genotyping/population genomics, GWAS and software/project design.",
        why: "Many exam questions combine lectures. For example, a GWAS question needs genetics, genotyping, population structure, multiple testing and post-GWAS interpretation. A genome assembly question needs sequencing technology, read length, repeats, N50 and BUSCO.",
        examFocus: "When revising, connect the lectures rather than treating each PDF as isolated. The professor’s sample questions mix definitions, technologies, file formats and downstream analysis outputs.",
        answerTemplate: "If asked to explain a workflow, answer in chronological order: biological question -> sample/DNA/RNA -> technology -> raw data -> QC -> analysis -> biological interpretation.",
      },
      {
        title: "How to use this guide in two days",
        slide: "intro-assessment",
        what: "The official evaluation includes written exam, genomic project and interview/project discussion. The project must contain introduction, aim, materials and methods, expected results/impact and a cost table.",
        why: "Even when you study for MCQs, keep project logic in mind: the course is applied genomics, so method choice, sample design, platform choice and realistic budget matter.",
        examFocus: "For the first pass, prioritize topics seen in sample/past questions: allele, Sanger, Ion Torrent, FASTQ, SAM, SOLiD, PacBio, Illumina, LD, inbreeding, ROH, CIGAR, BWA, paired-end, VCF, annotation, de Bruijn/Eulerian path, GWAS, BUSCO, HWE, MDS and ORA.",
        exercise: {
          prompt: "Two-day drill: name 5 topics that are likely to be asked as definitions and 3 topics that are likely to be asked as calculations.",
          answer: "Definitions: allele, LD, ROH, BUSCO, SAM/FASTQ/VCF, GWAS, ORA, aCGH. Calculations: coverage, N50 and Hardy-Weinberg equilibrium.",
        },
      },
    ],
    bullets: [
      "Written exam: 30 questions in 60 minutes, with 25 close-answer multiple-choice questions and 5 short written-answer questions.",
      "Pass condition: at least 22 correct answers out of 30 and genomic project submission.",
      "Multiple-choice prep: distinguish similar technologies, files, plots and biological concepts.",
      "Short-answer prep: define the method, identify input/output and state the reason for using it.",
      "The fastest high-yield loop is: read guide block -> inspect original slide -> answer a mini question -> verify with practice exam.",
    ],
    remember: "For the next 2 days, prioritize objective exam targets: coverage, N50, HWE, Manhattan plot, LD, BUSCO, FASTQ/SAM/VCF, PLINK files, CNV/aCGH and GWAS design.",
    traps: [
      "Do not prepare only for MCQs. The 5 written answers reward compact explanations, not memorized slide text.",
      "Do not ignore the project. The exam file ties written-test eligibility to project submission and the interview/project part affects the final score.",
    ],
    checklist: ["Open the practice exam once before reviewing.", "Mark all formulas for a same-day redo.", "Prepare a 60-second explanation of your project aim and method choice."],
  },
  {
    id: "foundations",
    number: 1,
    title: "Foundations of genetics and genomics",
    sources: ["Lecture 1.pdf", "Applied Genomics - examples of questions.docx"],
    slides: ["lecture01-alleles", "lecture01-plink-fam", "lecture01-popgen", "lecture01-allele-freq", "lecture01-hwe-formula", "lecture01-hwe-assumptions"],
    studyBlocks: [
      {
        title: "Gene, allele, genotype and phenotype",
        slide: "lecture01-alleles",
        what: "The slide gives the foundational vocabulary: Mendel’s particulate heredity elements are genes; different forms of the same gene are alleles; genotype is the genetic constitution; phenotype is the observable property of an organism.",
        why: "Several later topics rely on these words. GWAS associates genotype with phenotype; HWE predicts genotype frequencies from allele frequencies; population genomics tracks alleles across groups.",
        examFocus: "Past exam wording explicitly includes 'definition of allele'. The safest answer is: an allele is an alternative form of a gene or locus, not an entire chromosome, not a phenotype and not a sequencing read.",
        answerTemplate: "An allele is one of the alternative forms of a gene or genetic locus. A genotype is the allele combination carried by an individual, while the phenotype is the observed trait.",
        traps: ["Do not define allele as a mutation only. A mutant allele can be an allele, but allele is a broader term."],
      },
      {
        title: "Why sample metadata already looks like genomics",
        slide: "lecture01-plink-fam",
        what: "The .fam example stores family ID, individual ID, father, mother, sex and phenotype. Even before population genomics software is introduced, the course is already linking individuals, pedigrees and phenotypes to genotype data.",
        why: "This prepares you for PLINK, GWAS and population stratification. A GWAS is not only a list of SNPs; it is a matrix of genotypes attached to sample identity, phenotype and often pedigree/population information.",
        examFocus: "If a question asks why phenotype definition matters, connect it to this structure: the phenotype column is what the genotypes will be tested against.",
        answerTemplate: "Genomic analyses require both molecular data and sample metadata. Without correct individual IDs, pedigree/sex information and phenotype labels, association or population analyses can be invalid.",
      },
      {
        title: "Population genetics as the bridge to applied genomics",
        slide: "lecture01-popgen",
        what: "Population genetics studies the genetic composition of groups of individuals and how this composition changes over time. The focus shifts from a single organism to the gene pool of a population.",
        why: "This is why the course later asks about HWE, MDS, ROH, LD and GWAS. These are population-level tools: they interpret genome-wide variation across many individuals.",
        examFocus: "When asked why population structure matters, say that individuals are not independent genetic points if ancestry differs. Structure can produce false associations in GWAS.",
        answerTemplate: "Population genetics provides the allele-frequency logic behind population genomics. It allows us to describe variation, test equilibrium assumptions and detect structure, selection or inbreeding.",
      },
      {
        title: "Allele and genotype frequency calculations",
        slide: "lecture01-allele-freq",
        what: "Allele frequency is the number of copies of a specific allele divided by the total number of alleles. Genotype frequency is the number of individuals with a genotype divided by the total number of individuals.",
        why: "This is the first step in HWE exercises and also appears implicitly in MAF filtering, GWAS quality control and population comparisons.",
        examFocus: "For diploids, total alleles = 2N. Homozygotes contribute two copies of their allele; heterozygotes contribute one copy of each allele.",
        answerTemplate: "For 500 AA, 200 Aa and 300 aa, A copies = 2*500 + 200 = 1200, total alleles = 2000, so p = 0.6 and q = 0.4.",
        exercise: {
          prompt: "If a population has 30 AA, 40 Aa and 30 aa individuals, calculate p and q.",
          answer: "Total alleles = 200. A copies = 2*30 + 40 = 100, so p = 0.5. a copies = 100, so q = 0.5.",
        },
      },
      {
        title: "Hardy-Weinberg equilibrium",
        slide: "lecture01-hwe-formula",
        what: "The formula expands (p + q)^2 = 1 into p^2 + 2pq + q^2 = 1. These terms correspond to expected genotype frequencies AA, Aa and aa under Hardy-Weinberg assumptions.",
        why: "HWE is both a conceptual population-genetics model and a practical quality-control check in genomic datasets. Large deviations can mean biology, structure, selection, non-random mating or technical problems.",
        examFocus: "Past questions include a full HWE calculation. Show p and q first, calculate expected counts, then compare observed vs expected. A short qualitative statement is not enough if numbers are provided.",
        answerTemplate: "Under HWE, genotype frequencies are p^2, 2pq and q^2. After calculating allele frequencies, multiply these expected frequencies by the number of individuals and compare them with observed counts.",
      },
      {
        title: "HWE assumptions and why deviations are informative",
        slide: "lecture01-hwe-assumptions",
        what: "The slide lists the assumptions: diploid organisms, sexual reproduction, non-overlapping generations, random mating, infinitely large population, equal allele frequencies in sexes, no migration/gene flow/admixture/mutation/selection.",
        why: "Real populations often violate at least one assumption. That is why deviations from HWE can be informative but also why they must be interpreted carefully.",
        examFocus: "For an open question, do not just write the formula. Mention at least random mating, no selection, no migration and large population size, then explain what a deviation may imply.",
        answerTemplate: "A population is in Hardy-Weinberg equilibrium when allele and genotype frequencies remain stable across generations under ideal assumptions. If observed and expected genotype counts differ strongly, the population is not in HWE.",
        traps: ["Do not conclude 'not in HWE' only because one genotype is common. You must compare observed counts to expected counts derived from p and q."],
      },
    ],
    bullets: [
      "Allele = alternative form of a gene/locus; genotype = allele combination; phenotype = observable trait.",
      "Population genetics moves the focus from individual inheritance to allele/genotype frequencies in groups.",
      "For a diploid locus, allele frequency uses 2N total allele copies.",
      "HWE expected genotype frequencies are p^2, 2pq and q^2.",
      "HWE deviations may reflect population structure, inbreeding, selection, migration, mutation, non-random mating or genotyping problems.",
      "These definitions are not isolated: they support LD, MDS, ROH and GWAS interpretation later in the course.",
    ],
    remember: "Know the definitions cold, then practice converting genotype counts into allele frequencies and expected HWE counts.",
    formulas: [
      {
        title: "Hardy-Weinberg equilibrium",
        expression: "p + q = 1; expected genotypes = p^2, 2pq, q^2",
        variables: ["p = frequency of allele A", "q = frequency of allele a", "N = number of diploid individuals"],
        example: "If p = 0.6 and q = 0.4 in 1000 individuals, expected AA = 360, Aa = 480, aa = 160.",
      },
    ],
    exercises: [
      {
        prompt: "Sample-question drill: 500 AA, 200 Aa, 300 aa. Calculate p and q, then expected counts.",
        answer: "Total alleles = 2000. A alleles = 2*500 + 200 = 1200, so p = 0.60; q = 0.40. Expected counts: AA = 0.36*1000 = 360, Aa = 0.48*1000 = 480, aa = 0.16*1000 = 160. Observed differs strongly, so the population is not in HWE.",
      },
    ],
  },
  {
    id: "ngs-tech-i",
    number: 2,
    title: "NGS technologies I",
    sources: ["lecture 2.pdf", "lecture 3.pdf", "Transcript AG - 25-11-12 Mod_1"],
    slides: ["lecture02-sanger-ngs", "lecture02-cost-capacity", "lecture02-ion-torrent", "lecture02-ion-data-flow", "lecture03-illumina-bridge", "lecture03-flowcells", "lecture03-illumina-sbs", "lecture03-sbs-readout"],
    studyBlocks: [
      {
        title: "Sanger sequencing versus NGS",
        slide: "lecture02-sanger-ngs",
        what: "Sanger sequencing is the first-generation chain-termination method. The NGS conceptual change is massive parallelization: instead of sequencing one DNA fragment at a time, millions of DNA molecules/fragments are sequenced in parallel.",
        why: "This explains why NGS changed genomics: it reduced cost per base, increased throughput and made whole-genome resequencing, variant discovery and large-scale studies practical.",
        examFocus: "Past questions explicitly test Sanger as a chain-termination method. If the answer options include ligation, H+ release or real-time single-molecule sequencing, those belong to other platforms.",
        answerTemplate: "Sanger is based on dideoxy chain termination. NGS differs because it sequences many molecules in parallel, producing large numbers of short or long reads depending on the platform.",
        traps: ["Do not say Sanger is an NGS technology. It is first-generation sequencing."],
      },
      {
        title: "Cost, throughput and the project-design mindset",
        slide: "lecture02-cost-capacity",
        what: "The slide links technology history to falling cost per genome and increasing sequencing capacity. The key point is not only that sequencing became cheaper; it became scalable enough for population and applied-genomics questions.",
        why: "This connects directly to the genomic project. Platform choice is constrained by budget, required coverage, genome size, number of samples and the type of result needed.",
        examFocus: "If asked which technology is appropriate, do not choose by brand alone. Mention read length, throughput, accuracy, cost and the biological question.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor emphasized that running sequencing as a service is not only buying a machine: maintenance, servers, alignment of the system and technical support are major practical constraints.",
        },
        answerTemplate: "A good platform choice balances genome size, desired depth, read length, expected error profile, number of samples and budget.",
      },
      {
        title: "Ion Torrent: nucleotide incorporation detected as pH change",
        slide: "lecture02-ion-torrent",
        what: "Ion Torrent detects the hydrogen ion released when a nucleotide is incorporated. The signal is electronic/pH-based rather than optical fluorescence-based.",
        why: "It is a classic MCQ topic because the principle is easy to confuse with Roche 454 pyrosequencing, which detects light generated from pyrophosphate chemistry.",
        examFocus: "Past questions mention exactly this: when a nucleotide is incorporated, H+ is released. That is Ion Torrent.",
        answerTemplate: "Ion Torrent sequencing detects H+ ions released during nucleotide incorporation; the pH change is converted into a sequencing signal.",
        traps: [
          "Do not answer 'light signal' for Ion Torrent. Light/pyrogram language points to 454 pyrosequencing.",
          "Homopolymer regions are a known error-prone context because signal intensity must be translated into the number of repeated bases.",
        ],
      },
      {
        title: "From instrument output to files",
        slide: "lecture02-ion-data-flow",
        what: "The slide shows that sequencing is followed by data processing, base calling, filtering and alignment/variant-calling outputs. Even a technology lecture already introduces FASTQ, BAM and VCF as downstream products.",
        why: "File-format questions are frequent because they test whether you understand the pipeline order: raw reads first, alignments second, variants after that.",
        examFocus: "FASTQ = reads and qualities; SAM/BAM = alignments; VCF = variant calls. This exact distinction appears in the sample questions.",
        answerTemplate: "A sequencer produces reads that are stored with quality scores in FASTQ. After mapping, alignments are stored in SAM/BAM. After variant calling, variants and genotypes are stored in VCF.",
      },
      {
        title: "Illumina library clusters and bridge amplification",
        slide: "lecture03-illumina-bridge",
        what: "Illumina sequencing does not read a single isolated molecule directly. DNA fragments are bound to a flow cell and amplified into clusters so the imaging system can detect a strong enough signal.",
        why: "This matters because base calling depends on imaging many identical copies in each cluster. Cluster density and signal overlap affect data quality.",
        examFocus: "If an option says Illumina is a short-read, high-throughput sequencing-by-synthesis platform, that is the high-yield description.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor explained that a cluster means the DNA fragment is amplified thousands of times because the system needs enough signal; it is not sensing information from one DNA molecule only.",
        },
        answerTemplate: "Illumina uses bridge amplification to create clusters on a flow cell, followed by sequencing by synthesis with imaging-based base calling.",
      },
      {
        title: "Random versus patterned flow cells",
        slide: "lecture03-flowcells",
        what: "Earlier flow cells had randomly positioned clusters, while patterned flow cells organize cluster positions more precisely. The aim is to reduce overlap and improve imaging/base calling.",
        why: "This is the technical reason behind many Illumina improvements: better spatial control means cleaner signal detection, higher throughput and more reliable base calls.",
        examFocus: "You probably will not be asked to draw the flow cell, but it helps explain why sequencing errors and throughput depend on platform generation.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor highlighted that randomly distributed clusters can overlap in the light signal, making it harder to capture the correct base signal.",
        },
      },
      {
        title: "Reversible terminator chemistry",
        slide: "lecture03-illumina-sbs",
        what: "Illumina adds all four modified nucleotides together. Each nucleotide has a fluorescent label and a reversible blocking group, so only one base is incorporated per cycle before imaging and chemical removal of the blocker.",
        why: "This is the core logic of sequencing by synthesis. It explains why Illumina is accurate but cycle-based, and why read quality tends to decline with longer reads.",
        examFocus: "Do not confuse Illumina with Ion Torrent. Illumina uses fluorescent reversible terminators and imaging; Ion Torrent detects H+ release.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor emphasized that Illumina nucleotides are modified in two ways: one modification identifies the nucleotide by fluorescence, and another blocks further extension until it is removed.",
        },
        answerTemplate: "Illumina sequencing by synthesis repeatedly incorporates one fluorescent reversible-terminator nucleotide, images the cluster, removes the dye/blocker and continues to the next cycle.",
      },
    ],
    bullets: [
      "Sanger = first-generation chain termination; NGS = massively parallel sequencing.",
      "Ion Torrent detects H+ release during nucleotide incorporation and is classically sensitive to homopolymer interpretation.",
      "Illumina is high-throughput short-read sequencing by synthesis with cluster generation and imaging.",
      "Reversible terminators allow one base per cycle, then imaging, cleaning and the next cycle.",
      "Instrument choice depends on throughput, read length, error profile, cost, support and the research question.",
      "Data outputs begin as FASTQ and later become alignment/variant files after analysis.",
    ],
    remember: "For exam answers, compare platforms by read length, throughput, error type and the downstream question they support.",
    professorNote: {
      source: "Transcript AG - 25-11-12 Mod_1",
      text: "The professor repeatedly framed sequencing technologies as practical choices: technical support, maintenance, servers, coverage and throughput affect whether a platform is realistic for a project.",
    },
    traps: [
      "Illumina does not read one isolated molecule directly; clusters amplify the signal.",
      "Do not describe all NGS platforms as having the same error profile.",
    ],
  },
  {
    id: "ngs-tech-ii",
    number: 3,
    title: "NGS technologies II",
    sources: ["lecture 3.pdf", "Transcript AG - 25-11-12 Mod_1", "Applied Genomics - examples of questions.docx"],
    slides: ["lecture03-454-pyro", "lecture03-solid-overview", "lecture03-nanopore-principle", "lecture03-nanopore-signal", "lecture03-pacbio-smrt", "lecture03-pacbio-ccs", "lecture03-pacbio-accuracy"],
    studyBlocks: [
      {
        title: "Roche 454: pyrosequencing and light signal",
        slide: "lecture03-454-pyro",
        what: "454 sequencing is based on pyrosequencing. When a nucleotide is incorporated, pyrophosphate is released and converted through enzymatic reactions into a light signal recorded as peaks in a pyrogram.",
        why: "It is historically important and conceptually useful because it contrasts with Ion Torrent: both involve nucleotide-by-nucleotide incorporation, but the measured signal differs.",
        examFocus: "If the wording mentions pyrophosphate, luciferase, light or pyrogram, think Roche 454/pyrosequencing rather than Ion Torrent.",
        answerTemplate: "Roche 454 uses pyrosequencing: nucleotide incorporation releases PPi, which is converted into a light signal used to infer the DNA sequence.",
        traps: ["Do not call Roche 454 the long-read technology typically selected today for de novo genome assembly. In exam MCQs, PacBio is the expected modern long-read answer."],
      },
      {
        title: "ABI SOLiD: sequencing by ligation and two-base encoding",
        slide: "lecture03-solid-overview",
        what: "SOLiD uses ligation chemistry rather than polymerase-driven sequencing by synthesis. Its hallmark is two-base encoding, where each color call contains information about adjacent bases.",
        why: "This is a common trap because the technology is not commonly used today, but it is still a distinctive exam definition.",
        examFocus: "Past questions explicitly list ABI SOLiD as a two-base encoding system. If you see 'sequencing by ligation', that points to SOLiD.",
        answerTemplate: "ABI SOLiD is a short-read sequencing-by-ligation platform known for two-base encoding, not for H+ detection or single-molecule long reads.",
      },
      {
        title: "Nanopore: current signal through a pore",
        slide: "lecture03-nanopore-principle",
        what: "Nanopore sequencing passes DNA or RNA through a protein nanopore and detects changes in ionic current. The signal is decoded into sequence by base-calling algorithms.",
        why: "It is different from synthesis-based platforms: there is no cycle of nucleotide incorporation, imaging and washing. This enables direct, real-time sequencing and very long reads.",
        examFocus: "Nanopore is a long-read platform. If asked about portability or direct real-time DNA/RNA sequencing, Nanopore is the key example.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor emphasized that the key point in Nanopore is translating complex current changes into sequence; modern algorithms reduced the historically high error rate.",
        },
        answerTemplate: "Oxford Nanopore detects changes in electrical current as nucleic acids pass through a pore, enabling real-time long-read sequencing.",
      },
      {
        title: "Nanopore signal interpretation and error profile",
        slide: "lecture03-nanopore-signal",
        what: "The current signal is not a simple one-base-one-signal system; it reflects the nucleotides occupying the pore and must be decoded computationally.",
        why: "This explains why error rates historically depended strongly on base calling and why improvements in algorithms can improve sequencing accuracy without changing the basic biological sample.",
        examFocus: "For project design, Nanopore can be useful for rapid checks, field/portable sequencing and long-read assembly, but error profile and polishing strategy matter.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor noted that even when long-read error rates are higher than Illumina, they can still be useful for genome assembly because the main need is to place large puzzle pieces across repeats.",
        },
        traps: ["Do not say long reads are always more accurate than short reads. The advantage is length and structural context; accuracy depends on platform and correction strategy."],
      },
      {
        title: "PacBio SMRT sequencing",
        slide: "lecture03-pacbio-smrt",
        what: "PacBio SMRT sequencing observes single DNA polymerases in zero-mode waveguides. Modified nucleotides emit light during incorporation, and the system records base incorporation in real time.",
        why: "PacBio is a high-yield answer for long reads and de novo genome assembly because reads can span repetitive regions and structural variants.",
        examFocus: "The sample multiple-choice question asks which technology produces long reads often used in de novo genome assembly. The expected answer is PacBio.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor described PacBio nucleotides as modified on the longer pyrophosphate tail so the incorporation signal can be captured in real time.",
        },
        answerTemplate: "PacBio SMRT sequencing is a single-molecule real-time long-read technology useful for de novo genome assembly because long reads span repeats and complex regions.",
      },
      {
        title: "Circular consensus sequencing corrects random errors",
        slide: "lecture03-pacbio-ccs",
        what: "PacBio circular consensus sequencing ligates adapters to create a circular template and sequences the same insert multiple times. Repeated passes allow a consensus sequence to be built.",
        why: "This is the key to HiFi reads: if errors are mostly random, repeated sequencing of the same molecule makes it unlikely that the same wrong base appears in the same position every pass.",
        examFocus: "For an open answer, connect long read length to assembly and CCS/HiFi to accuracy improvement.",
        professorNote: {
          source: "Transcript AG - 25-11-12 Mod_1",
          text: "The professor stressed that PacBio errors are random enough that multiple passes through a circularized molecule allow software to correct the sequence by consensus.",
        },
        answerTemplate: "PacBio CCS/HiFi improves accuracy by sequencing the same circularized DNA insert multiple times and building a consensus from independent subreads.",
      },
      {
        title: "Choosing long reads for complex genomes",
        slide: "lecture03-pacbio-accuracy",
        what: "The comparison slide summarizes the trade-off: short reads are very accurate but short; long-read platforms generate larger pieces of the genome puzzle and can resolve repeats, phasing and structural variation.",
        why: "This is exactly why long reads are linked to de novo assembly in the exam. Assembly of complex genomes is limited by repeats and structural complexity, not just by the number of bases sequenced.",
        examFocus: "If the question asks 'often used in de novo genome assembly', choose a long-read platform, especially PacBio in the provided sample options.",
        answerTemplate: "Long reads are useful in de novo assembly because they span repetitive regions and connect genomic segments that short reads cannot uniquely place.",
        traps: ["Do not choose Illumina for the sample MCQ asking specifically about long reads for de novo assembly. Illumina is short-read/high-throughput."],
      },
    ],
    bullets: [
      "Roche 454 = pyrosequencing, PPi release and light/pyrogram signal.",
      "ABI SOLiD = sequencing by ligation and two-base encoding.",
      "Nanopore = direct current changes through a pore, real-time and portable long-read sequencing.",
      "PacBio SMRT = single-molecule real-time sequencing in zero-mode waveguides.",
      "PacBio CCS/HiFi improves accuracy through repeated passes of the same circularized insert.",
      "Long reads help de novo genome assembly because they span repeats and preserve long-range context.",
    ],
    remember: "If the question says de novo assembly of a complex genome, long reads are usually the high-yield answer; in the sample MCQ, PacBio is the correct choice.",
    professorNote: {
      source: "Transcript AG - 25-11-12 Mod_1",
      text: "Long reads were framed as bigger puzzle pieces: rougher at first, but very useful for placing repetitive regions, phasing variation and then polishing or correcting errors.",
    },
    traps: [
      "PacBio and Nanopore are both long-read technologies, but their signal generation is different.",
      "Nanopore portability is a practical project-design point, not just a technical curiosity.",
    ],
  },
  {
    id: "ngs-data-primers",
    number: 4,
    title: "NGS data analysis primers",
    sources: ["Lecture 4.pdf", "Lecture 8.pdf", "Applied Genomics - examples of questions.docx"],
    slides: ["lecture02-file-definitions", "lecture04-fastqc-quality", "lecture04-sam-cigar"],
    bullets: [
      "Start with DNA purity, integrity and enough material; poor input limits library choice and data quality.",
      "FASTQ stores read identifier, sequence, separator and encoded quality line; Phred Q = -10 log10(Perror).",
      "FastQC per-base sequence quality helps decide whether 3-prime trimming is needed; overrepresented sequences can indicate primers/adapters.",
      "BWA/Bowtie map reads to a reference; SAM/BAM store alignments; CIGAR summarizes match, insertion, deletion and clipping patterns.",
      "VCF stores variant calls; genotype notation such as 0|1 means phased heterozygous alleles relative to REF/ALT.",
      "Depth asks how many reads cover a base; breadth asks what fraction of the genome is covered.",
    ],
    remember: "A common exam pattern is 'which file contains what?' FASTQ = reads/qualities, SAM/BAM = alignments, VCF = variants, BED/GFF = genomic features.",
    formulas: [
      {
        title: "Sequencing coverage",
        expression: "coverage = (N x L) / G",
        variables: ["N = number of reads", "L = read length", "G = genome size"],
        example: "100,000,000 reads x 100 bp / 1,000,000,000 bp = 10x coverage.",
      },
    ],
    exercises: [
      {
        prompt: "A sample has 35,358 deduplicated reads averaging about 212 bp for a 16,679 bp mitochondrial genome. Estimate depth.",
        answer: "Depth is roughly (35,358 x 212) / 16,679 = about 449x. Using the deck's rounded data gives about 500x.",
      },
    ],
    traps: ["Do not confuse a SAM alignment file with a VCF variant file; the sample questions explicitly test this."],
  },
  {
    id: "genome-assembly",
    number: 5,
    title: "Genome assembly",
    sources: ["Lecture 6.pdf", "Applied Genomics - examples of questions.docx"],
    slides: ["lecture06-dbg", "lecture06-n50"],
    bullets: [
      "Mapping aligns reads to an existing reference; de novo assembly reconstructs a genome without relying on a close reference.",
      "Shotgun sequencing fragments DNA, sequences many pieces and assembles them by overlap or graph logic.",
      "Contigs are contiguous assembled sequences; scaffolds order/orient contigs and may contain gaps represented by Ns.",
      "Paired-end and mate-pair information can bridge repeats because both read ends come from the same physical fragment.",
      "de Bruijn graphs split reads into k-mers; assembly becomes finding an Eulerian path through edges.",
      "Inbreeding/homozygosity can simplify assembly because highly heterozygous regions may assemble separately and fragment the assembly.",
    ],
    remember: "N50 measures contiguity, not correctness. A high N50 from a misassembled genome can still be bad.",
    formulas: [
      {
        title: "N50",
        expression: "Sort contigs longest to shortest; add lengths until reaching at least 50% of total assembly length.",
        variables: ["Total assembly length = sum of contigs", "N50 = length of the contig that crosses the halfway point"],
        example: "Contigs 100, 70, 60, 50, 50, 40, 30 kb sum to 400 kb; halfway is 200 kb; 100 + 70 + 60 crosses 200, so N50 = 60 kb.",
      },
    ],
    professorNote: {
      source: "Transcript AG - 25-11-12 Mod_1",
      text: "Paired-end reads were emphasized as physically linked: even if the middle is not sequenced, the two ends still help place fragments.",
    },
  },
  {
    id: "annotation-databases",
    number: 6,
    title: "Genome annotation and databases",
    sources: ["Lecture 7.pdf"],
    slides: ["lecture07-busco", "lecture07-gff"],
    bullets: [
      "Annotation assigns roles to genome sequence: repeats, genes, transcripts, regulatory features and functional meaning.",
      "Repeat annotation and masking come first because unmasked repeats can create false gene-prediction evidence.",
      "Structural annotation asks where genes/transcripts are and what their exon-intron structures look like.",
      "Functional annotation assigns meaning using similarity, domains, GO terms and databases such as UniProt or HMM resources.",
      "BUSCO estimates completeness using expected single-copy orthologs and reports complete, duplicated, fragmented and missing genes.",
      "Genome coverage and gene coverage differ because repeats are often hard to assemble while gene-rich regions can be more complete.",
    ],
    remember: "BUSCO is about completeness; GFF/GTF/BED are annotation feature formats, not raw reads.",
    traps: ["Do not use N50 alone to judge annotation readiness; gene coverage and BUSCO can tell a different story."],
  },
  {
    id: "ngs-applications",
    number: 7,
    title: "NGS applications and case studies",
    sources: ["Lecture 8.pdf", "Lecture 9.pdf", "Applied Genomics - examples of questions.docx"],
    slides: ["lecture08-galaxy-workflow", "lecture09-ngs-applications"],
    bullets: [
      "Galaxy is a web platform for accessible, reproducible and transparent analyses; the case study workflow goes FASTQ QC, trimming, BWA mapping, duplicate removal, variant calling and VEP annotation.",
      "Pool-seq sequences pooled individuals and estimates allele-frequency differences cost-effectively.",
      "Targeted sequencing and WES focus sequencing effort on selected regions, genes or exons.",
      "Bisulfite sequencing studies methylation, but C-to-T conversion must be interpreted carefully with SNPs.",
      "ChIP-seq identifies DNA regions bound by a protein or carrying a histone mark; RNA-seq measures transcript abundance and transcript structure.",
    ],
    remember: "For each application, answer: input material, biological question, main output and one analysis caveat.",
    traps: [
      "ChIP-seq is not an expression assay; it maps protein-DNA interactions or chromatin marks.",
      "RNA-seq reads usually need alignment/counting/normalization before expression interpretation.",
    ],
  },
  {
    id: "genotyping-cnvs",
    number: 8,
    title: "High-throughput genotyping, SNP arrays and CNVs",
    sources: ["Lecture 11.pdf", "Lecture 12.pdf", "Lecture 14.pdf", "Applied Genomics - examples of questions.docx"],
    slides: ["lecture11-acgh"],
    bullets: [
      "High-throughput genotyping determines genotypes at many polymorphic loci and powers GWAS, genomic selection, MAS/MAB, parentage and population genomics.",
      "Microarrays are used for large-scale genotyping because per-sample cost is low, throughput is scalable and data quality is standardized.",
      "Illumina/Affymetrix-style SNP chips call genotypes from probe signal intensity and clustering.",
      "aCGH compares labeled test and reference DNA on an array to detect copy-number gains and losses.",
      "CNVs can also be detected from sequencing using read-pair, split-read, read-depth or assembly-based approaches.",
      "Array-based genotyping assays known sites; sequencing-based approaches can discover new variants but are typically more data-intensive.",
    ],
    remember: "aCGH is a microarray-based CNV method. CNV does not automatically mean sequencing.",
    traps: ["The sample questions explicitly test that aCGH is used to detect CNVs using microarray technology."],
  },
  {
    id: "population-genomics",
    number: 9,
    title: "Population genomics",
    sources: ["Lecture 10.pdf", "Lecture 11.pdf", "Lecture 12.pdf", "Lecture 14.pdf"],
    slides: ["lecture10-plink-files", "lecture12-roh"],
    bullets: [
      "PLINK text input uses PED for individuals/genotypes/phenotypes and MAP for marker positions; binary input uses BED/BIM/FAM.",
      "QC filters include missing samples (`--mind`), missing SNPs (`--geno`), minor allele frequency (`--maf`) and HWE p-value (`--hwe`).",
      "Allele/genotype frequencies and HWE output are first-pass checks before downstream population analyses.",
      "MDS/PCA-like dimension reduction compresses many SNPs into axes that reveal population structure.",
      "ROH are uninterrupted homozygous chromosome stretches; FROH = total ROH length / autosomal genome length.",
      "FST measures population differentiation; LD measures non-random allele association at loci.",
    ],
    remember: "Population structure is both a biological result and a confounder for GWAS.",
    formulas: [
      {
        title: "Genomic inbreeding from ROH",
        expression: "FROH = SROH / LGEN",
        variables: ["SROH = summed ROH length for an individual", "LGEN = autosomal genome length considered"],
        example: "If ROH sum to 420 Mb and autosomal length is 2800 Mb, FROH = 0.15.",
      },
    ],
  },
  {
    id: "gwas",
    number: 10,
    title: "GWAS",
    sources: ["Lecture 11.pdf", "Lecture 12.pdf", "Lecture 13.pdf", "Lecture 14.pdf", "Applied Genomics - examples of questions.docx"],
    slides: ["lecture13-gwas-design", "lecture13-manhattan", "lecture13-ora", "lecture14-plink-gwas"],
    bullets: [
      "GWAS tests genetic variants across many individuals to find genotype-phenotype associations.",
      "Design starts with phenotype definition: case/control for binary traits or quantitative models for continuous traits.",
      "LD lets tag SNPs represent nearby causal variants, but it also means association is not automatically causation.",
      "Sample size, allele frequency, effect size, LD with the tested marker and multiple testing drive statistical power.",
      "Population stratification can create false associations; inspect MDS/PCA and QQ plots and use appropriate covariates/models.",
      "Manhattan plots show genomic position vs -log10(P); QQ plots diagnose inflation; Bonferroni uses alpha/N.",
      "Post-GWAS work prioritizes nearby/candidate genes, uses databases and can run ORA to test over-represented functions.",
    ],
    remember: "A good GWAS answer includes phenotype, genotype platform, QC, association model, population-structure correction, multiple testing and post-GWAS interpretation.",
    formulas: [
      {
        title: "Bonferroni correction",
        expression: "threshold = alpha / N",
        variables: ["alpha = desired experiment-wise error rate", "N = number of tests"],
        example: "For alpha = 0.05 and 20 SNPs, threshold = 0.0025.",
      },
    ],
    traps: [
      "The y-axis of a Manhattan plot is -log10(P), not raw genomic position or effect size.",
      "A significant tag SNP may be a proxy in LD with the causal variant.",
    ],
  },
  {
    id: "project-preparation",
    number: 11,
    title: "Genomic project preparation",
    sources: ["PlanningGenomicProject.pdf", "Final_exam.pdf", "Introduction to the course.pdf", "Transcript AG - 25-11-12 Mod_1"],
    slides: ["project-design"],
    bullets: [
      "The project should include introduction/problem, aim, materials and methods, expected results/impact and a cost table.",
      "The budget should cover sampling, DNA extraction, sequencing/high-throughput genotyping outsourcing and computational costs when relevant.",
      "Aim, budget, methods and expected results must fit each other; a too-large aim with a small budget is a design failure.",
      "For complex genomes, justify sample choice, DNA/RNA quality, sequencing platform, coverage, assembly/annotation or variant workflow and computing resources.",
      "For GWAS, justify phenotype definition, sample size, heritability, stratification control, genotyping/sequencing choice and post-GWAS analysis.",
      "The oral/interview can use the project as a starting point, so every method choice should have a one-sentence reason.",
    ],
    remember: "The project is not a shopping list. It is an argument that the design can answer the biological question within budget.",
    professorNote: {
      source: "Transcript AG - 25-11-12 Mod_1",
      text: "Applied genomics was framed as practical work: permissions, sample movement, field constraints and budget can decide which technology is realistic.",
    },
    traps: ["Do not plan a complex reference genome without considering DNA quality, long reads, coverage, repeats, heterozygosity and compute resources."],
  },
  {
    id: "cram-checklist",
    number: 12,
    title: "Final 2-day cram checklist",
    sources: ["Final_exam.pdf", "Applied Genomics - examples of questions.docx", "All lecture PDFs"],
    slides: [],
    bullets: [
      "Day 1: read sections 0-7 and immediately redo coverage, HWE and N50 without looking.",
      "Day 1 evening: practice explaining FASTQ, SAM/BAM, VCF, CIGAR, FastQC and BWA in one sentence each.",
      "Day 2 morning: read sections 8-11 and drill PLINK files, ROH/FROH, aCGH/CNV, GWAS design and plot interpretation.",
      "Day 2 afternoon: take the practice exam, then review wrong options as distractor training.",
      "Final hour: rehearse project aim, method choice, budget logic and expected result.",
    ],
    remember: "If time is tight, prioritize terms that appear in the sample questions and concepts that connect multiple lectures.",
    checklist: [
      "Definitions: gene, allele, genotype, phenotype, SNP, CNV, LD, ROH, FST, BUSCO.",
      "Formats: FASTQ, SAM/BAM, VCF, GFF/BED, PED/MAP, BED/BIM/FAM.",
      "Formulas: coverage, HWE, N50, Bonferroni, FROH.",
      "Plots: FastQC per-base quality, Manhattan plot, QQ plot, MDS/PCA scatter, aCGH log2 ratio.",
      "Methods: Sanger, Illumina, Ion Torrent, SOLiD, PacBio, Nanopore, Pool-seq, RNA-seq, ChIP-seq, bisulfite-seq, WES.",
    ],
    traps: [
      "Long reads are high-yield for de novo assembly because they span repeats.",
      "Multiple testing is not optional in GWAS.",
      "Genome coverage and gene coverage are related but not identical.",
    ],
  },
];

export const AG_EXAM_STATS = [
  { label: "Written questions", value: "30" },
  { label: "MCQ + short", value: "25 + 5" },
  { label: "Pass mark", value: "22/30" },
  { label: "Time", value: "60 min" },
];

export function getSlidesForSection(section) {
  return (section.slides || []).map((id) => slideById[id]).filter(Boolean);
}
