import React, { useMemo, useState } from "react";
import titleSlide from "../../assets/drd/lesson05/title.jpg";
import illuminaHqSlide from "../../assets/drd/lesson05/illumina-hq-beadchip.jpg";
import beadarrayHistorySlide from "../../assets/drd/lesson05/beadarray-history.jpg";
import beadarrayPitsSlide from "../../assets/drd/lesson05/beadarray-pits-beads.jpg";
import transcriptomeSlide from "../../assets/drd/lesson05/transcriptome-beadchip.jpg";
import methylationWhySlide from "../../assets/drd/lesson05/dna-methylation-why.jpg";
import cytosineMethylationSlide from "../../assets/drd/lesson05/dna-cytosine-methylation.jpg";
import measuringPercentSlide from "../../assets/drd/lesson05/measuring-methylation-percent.jpg";
import tissueDistributionSlide from "../../assets/drd/lesson05/tissue-distribution-same-beta.jpg";
import cpgContextSlide from "../../assets/drd/lesson05/cpg-island-context.jpg";
import platformEvolutionSlide from "../../assets/drd/lesson05/27k-to-450k.jpg";
import cpgDistributionSlide from "../../assets/drd/lesson05/450k-cpg-distribution.jpg";
import epicV1Slide from "../../assets/drd/lesson05/epic-version1.jpg";
import epicV2Slide from "../../assets/drd/lesson05/epic-v2-features.jpg";
import samplePrepSlide from "../../assets/drd/lesson05/sample-preparation.jpg";
import bisulfiteSlide from "../../assets/drd/lesson05/bisulfite-conversion.jpg";
import mainStrategySlide from "../../assets/drd/lesson05/beadchip-main-strategy.jpg";
import infiniumOneSummarySlide from "../../assets/drd/lesson05/infinium-one-summary.jpg";
import infiniumOneUSlide from "../../assets/drd/lesson05/infinium-one-unmethylated.jpg";
import infiniumOneMSlide from "../../assets/drd/lesson05/infinium-one-methylated.jpg";
import infiniumOverviewSlide from "../../assets/drd/lesson05/infinium-overview.jpg";
import infiniumOneReadingSlide from "../../assets/drd/lesson05/infinium-one-reading.jpg";
import infiniumTwoReadingSlide from "../../assets/drd/lesson05/infinium-two-reading.jpg";
import betaFormulaSlide from "../../assets/drd/lesson05/beta-value-formula.jpg";
import betaBimodalSlide from "../../assets/drd/lesson05/beta-distribution-bimodal.jpg";
import probeTypeDifferencesSlide from "../../assets/drd/lesson05/probe-type-differences.jpg";
import probeTypeBiasSlide from "../../assets/drd/lesson05/probe-type-bias.jpg";
import betaMValuesSlide from "../../assets/drd/lesson05/beta-m-values.jpg";
import normalizationOverviewSlide from "../../assets/drd/lesson05/normalization-overview.jpg";
import dmrInterpretationSlide from "../../assets/drd/lesson05/dmr-interpretation.jpg";
import epigeneticClockSlide from "../../assets/drd/lesson05/epigenetic-clock.jpg";
import clockDescriptionSlide from "../../assets/drd/lesson05/clock-description.jpg";
import elovl2ClockSlide from "../../assets/drd/lesson05/elovl2-clock.jpg";
import ageAlgorithmSlide from "../../assets/drd/lesson05/dna-methylation-age-algorithm.jpg";
import currentConsensusSlide from "../../assets/drd/lesson05/current-consensus.jpg";

const SLIDES_URL = "https://drive.google.com/file/d/1L_othy-SIJtV_pjzDEDluVK5RmZYQ4TI/view?usp=drivesdk";
const TRANSCRIPT_URL = "https://docs.google.com/document/d/1TH6GF5k0goaPW4BISg3D63sVvanGC6UI9m0x1I_Tg1M/edit?usp=drivesdk";
const RECORDING_URL = "https://www.youtube.com/watch?v=DCv9v8sUnnU&list=PLZSGWjLWZL3KQFkSCUbUXWEVHeF0MTYZV&index=5";

const IMG = {
  title: { src: titleSlide, slide: 1 }, illuminaHq: { src: illuminaHqSlide, slide: 4 }, beadHistory: { src: beadarrayHistorySlide, slide: 5 }, beadPits: { src: beadarrayPitsSlide, slide: 6 }, transcriptome: { src: transcriptomeSlide, slide: 8 }, methylationWhy: { src: methylationWhySlide, slide: 9 }, cytosine: { src: cytosineMethylationSlide, slide: 10 }, percent: { src: measuringPercentSlide, slide: 12 }, tissue: { src: tissueDistributionSlide, slide: 13 }, cpgContext: { src: cpgContextSlide, slide: 14 }, platforms: { src: platformEvolutionSlide, slide: 16 }, cpgDistribution: { src: cpgDistributionSlide, slide: 17 }, epic1: { src: epicV1Slide, slide: 18 }, epic2: { src: epicV2Slide, slide: 19 }, prep: { src: samplePrepSlide, slide: 22 }, bisulfite: { src: bisulfiteSlide, slide: 24 }, mainStrategy: { src: mainStrategySlide, slide: 27 }, inf1summary: { src: infiniumOneSummarySlide, slide: 29 }, inf1u: { src: infiniumOneUSlide, slide: 30 }, inf1m: { src: infiniumOneMSlide, slide: 31 }, overview: { src: infiniumOverviewSlide, slide: 36 }, inf1read: { src: infiniumOneReadingSlide, slide: 40 }, inf2read: { src: infiniumTwoReadingSlide, slide: 41 }, beta: { src: betaFormulaSlide, slide: 42 }, bimodal: { src: betaBimodalSlide, slide: 43 }, diffs: { src: probeTypeDifferencesSlide, slide: 45 }, bias: { src: probeTypeBiasSlide, slide: 46 }, mvalues: { src: betaMValuesSlide, slide: 47 }, normalization: { src: normalizationOverviewSlide, slide: 50 }, dmr: { src: dmrInterpretationSlide, slide: 53 }, clock: { src: epigeneticClockSlide, slide: 55 }, clockDesc: { src: clockDescriptionSlide, slide: 56 }, elovl2: { src: elovl2ClockSlide, slide: 59 }, ageAlgo: { src: ageAlgorithmSlide, slide: 60 }, consensus: { src: currentConsensusSlide, slide: 61 }
};

const COPY = {
  en: {
    mark: "Mark completed", done: "Completed", previous: "Previous", next: "Next", current: "Lesson 5", dashboard: "DRD dashboard", previousTitle: "M1.3 Affymetrix GeneChip", nextTitle: "M2.1 R/Bioconductor intro", resources: "Class resources", slides: "Slides", transcript: "Transcript", recording: "Recording", open: "Open", zoom: "Click to zoom", close: "Close zoom", slide: "Slide", professor: "Professor emphasis", exam: "Exam watch", report: "Open expanded answer", include: "What to include", trap: "Common trap", model: "Sample answer", checkpoint: "Checkpoint", correct: "Correct", tryAgain: "Try again", words: "words", heroEyebrow: "Module 1 · May 12 · Illumina Inc. and BeadChip", heroTitle: "Illumina BeadChip and methylation-array logic", heroSubtitle: "A slide-guided lesson on bead-based arrays, bisulfite conversion, Infinium I/II chemistry, beta values, probe-type bias and epigenetic-clock applications.", flow: ["beads", "CpG methylation", "27K/450K/EPIC", "bisulfite", "Infinium I/II", "beta values", "normalization", "applications"],
    sections: [
      { title: "1. Why Illumina is a different array logic", intro: "The professor changes technology again: after Stanford spotting and Affymetrix photolithography, Illumina uses beads that carry oligonucleotides and are assembled into a BeadChip.", slides: [
        { img: "title", title: "Where this lesson sits", body: "The lecture is still Module 1 theory, but it is the bridge toward the methylation dataset used later in Module 2." },
        { img: "illuminaHq", title: "Illumina: arrays plus sequencing", body: "Illumina competed with Affymetrix in arrays, but the professor stresses that the company also evolved strongly toward next-generation sequencing." },
        { img: "beadHistory", title: "Beads are prepared separately", body: "Unlike Affymetrix, the oligonucleotides are not synthesized in situ on the chip. They are prepared on beads and then placed into the array." },
        { img: "beadPits", title: "Pits, beads and replicated probes", body: "The BeadChip has pits on a silicon support. Each bead carries many identical oligos, and bead types can appear as technical replicates across the array.", professor: "She contrasts this with previous manufacturing strategies: competitive arrays use spotting; Affymetrix uses in situ photolithography; Illumina uses pre-made beads assembled into pits." }
      ]},
      { title: "2. From transcriptome arrays to methylation arrays", intro: "Illumina old transcriptome BeadArrays are mostly historical here. The real focus of the course is DNA methylation, because you will analyze methylation-array data later.", slides: [
        { img: "transcriptome", title: "Transcriptome BeadChips are background knowledge", body: "The transcriptome format helps understand the bead idea, but the professor explicitly redirects the class toward DNA methylation." },
        { img: "methylationWhy", title: "DNA methylation connects environment and genome", body: "Methylation is presented as a way to study how the exposome, aging and disease interact with DNA regulation." },
        { img: "cytosine", title: "CpG methylation in mammalian cells", body: "CpG cytosine can be methylated at the 5 position. The lecture recalls the very large number of CpGs across the genome and the role of dynamic methylation/demethylation." }
      ], extra: "fraction"},
      { title: "3. Beta values are population-level measurements", intro: "Before chemistry, the professor insists on a conceptual trap: with a pool of cells, methylation is not simply yes/no. The same percentage can hide different tissue compositions.", slides: [
        { img: "percent", title: "0%, 50%, 100% and intermediate methylation", body: "Counting methylated cytosines across many DNA molecules gives a percentage. This is why array results are quantitative rather than a binary state." },
        { img: "tissue", title: "The same beta can hide different biology", body: "Two tissues can produce the same overall methylation percentage but have different underlying cell-level distributions.", professor: "This is one of the strongest interpretation warnings in the class: do not infer the original tissue architecture from a single beta value.", exam: { question: "Possible question: why are methylation-array results quantitative instead of simply methylated/unmethylated?", include: ["Mention that samples are pools of cells/DNA molecules.", "Explain that the same CpG can be methylated in some molecules and unmethylated in others.", "Connect fluorescence intensity to a percentage or beta value between 0 and 1."], trap: "Do not answer as if every CpG in a sample has only one state. That would only be true for a single molecule or very simplified single-cell reasoning.", answer: "Illumina methylation arrays measure a pool of DNA molecules. At the same CpG site, some molecules can carry the methylated state while others are unmethylated, especially because tissues contain multiple cells and sometimes different cell types. Therefore the output is a quantitative methylation level, commonly expressed as a beta value between 0 and 1, rather than a binary yes/no label." } },
        { img: "cpgContext", title: "Island, shore, shelf and open sea", body: "CpGs are interpreted by genomic context. Shores can be highly informative for gene expression, but the correlation is not always direct." }
      ]},
      { title: "4. Platform evolution: 27K → 450K → EPIC", intro: "The professor links array design to biological knowledge: new arrays add CpGs because new projects identify new informative genomic regions.", slides: [
        { img: "platforms", title: "27K and 450K", body: "27K interrogated a small subset of CpGs. 450K greatly expanded coverage and is the reference platform for your Module 2 dataset." },
        { img: "cpgDistribution", title: "What the 450K covers", body: "The distribution includes promoters, gene bodies, UTRs, intergenic loci and CpG island-related categories." },
        { img: "epic1", title: "EPIC version 1", body: "EPIC increased coverage to more than 850K sites and preserved most 450K CpGs, making comparison with older datasets possible." },
        { img: "epic2", title: "EPIC version 2", body: "EPIC v2 approaches one million sites and adds regions informed by cancer, stem-cell and regulatory-genome projects.", professor: "Her take-home idea is not just the number of probes. Arrays improve because biological knowledge improves.", exam: { question: "Possible question: explain the evolution from 27K to 450K and EPIC.", include: ["State that coverage increases across generations.", "Mention that 450K is the key reference for the course dataset.", "Explain that EPIC keeps much of the previous content while adding new CpGs from updated genome/regulatory knowledge."], trap: "Do not say EPIC covers the whole methylome. Even around one million CpGs is still far below the roughly 28 million CpG sites in the human genome.", answer: "The evolution from 27K to 450K and EPIC reflects increasing genomic coverage and increasing biological knowledge. The 27K array measured a limited set of CpGs, while the 450K platform covered many more CpGs across promoters, gene bodies, UTRs and island-related contexts. EPIC arrays expanded coverage further while retaining many 450K CpGs, allowing comparison with older studies. However, even EPIC is still targeted and does not cover the entire methylome." } }
      ], extra: "platforms"},
      { title: "5. Bisulfite conversion: the essential trick", intro: "The professor repeatedly states that this must be clear: PCR alone would erase methylation information, so bisulfite creates a sequence-level memory of methylation state.", slides: [
        { img: "prep", title: "Sample preparation workflow", body: "The workflow starts from DNA extraction, then bisulfite conversion, amplification, fragmentation and hybridization." },
        { img: "bisulfite", title: "C/T after bisulfite + PCR", body: "Unmethylated C becomes U after bisulfite and T after PCR; methylated C remains read as C. Therefore C means originally methylated and T means originally unmethylated.", professor: "She calls bisulfite a necessary trick: without it, PCR would lose the methylation information.", exam: { question: "Possible question: explain bisulfite conversion in methylation arrays.", include: ["Explain why PCR alone is not enough.", "State unmethylated C → U → T.", "State methylated C → C after conversion/PCR.", "Connect this to the array's C/T genotyping logic."], trap: "Do not say bisulfite directly measures methylation. It converts the methylation state into a sequence difference that the array can interrogate.", answer: "Bisulfite conversion is used because ordinary amplification would erase the methyl group and the original methylation information. After bisulfite treatment, unmethylated cytosines are converted to uracil and then read as thymine after PCR, whereas methylated cytosines remain as cytosine. The array can therefore interrogate whether, at a known CpG position, the target contains C or T after conversion. C indicates an originally methylated cytosine, while T indicates an originally unmethylated cytosine." } }
      ], extra: "bisulfite"},
      { title: "6. Infinium I and Infinium II strategies", intro: "This is the core chemistry. Both strategies are present in Illumina methylation arrays, but they read methylation differently.", slides: [
        { img: "mainStrategy", title: "Main BeadChip strategy", body: "After bisulfite conversion, the array performs a genotyping-like readout: C near G means methylated; T near G means unmethylated." },
        { img: "inf1summary", title: "Infinium I: two beads, two probes", body: "Infinium I uses a U bead and an M bead for the same CpG. The two probes differ at the informative end." },
        { img: "inf1u", title: "Infinium I unmethylated channel", body: "The U probe is compatible with T after bisulfite conversion, so fluorescence from the U bead supports the unmethylated state." },
        { img: "inf1m", title: "Infinium I methylated channel", body: "The M probe is compatible with C after bisulfite conversion, so fluorescence from the M bead supports the methylated state." },
        { img: "overview", title: "Overview of Infinium I vs II", body: "Infinium I: two beads/probes. Infinium II: one bead/probe and two-colour single-base extension. The CpGs interrogated by the two strategies are different.", professor: "She explicitly says this is a very possible question for the verification/exam: know Infinium I and Infinium II before leaving the room.", exam: { question: "Possible question: compare Infinium I and Infinium II strategies.", include: ["Infinium I uses two bead types/probes for the same CpG: U and M.", "Infinium II uses one bead/probe and distinguishes C/T by the nucleotide added in single-base extension.", "Explain fluorescence origin: bead identity in Infinium I, colour identity on the same bead in Infinium II.", "Mention that both strategies are present in the same array but interrogate different CpGs."], trap: "Do not confuse Illumina two-colour readout with Stanford competitive arrays. Here colours identify nucleotide/methylation state, not two biological samples on the same array.", answer: "Infinium I and Infinium II are two Illumina strategies for reading methylation after bisulfite conversion. Infinium I uses two bead types for the same CpG, one for the unmethylated state and one for the methylated state, so fluorescence is interpreted by bead identity. Infinium II uses one bead and one probe ending before the interrogated position; the added labelled nucleotide distinguishes T from C. Thus Infinium II can generate red and green signals on the same bead. Both strategies coexist in the array but interrogate different CpG sites." } }
      ], extra: "infinium"},
      { title: "7. Beta values and raw data matrix", intro: "After the chemistry, the data become a matrix: CpG identifiers as rows, samples as columns, beta values as quantitative methylation levels.", slides: [
        { img: "inf1read", title: "Reading Infinium I", body: "Methylated and unmethylated intensities come from different beads/probes for the same CpG." },
        { img: "inf2read", title: "Reading Infinium II", body: "Methylated and unmethylated signals come from different colours on the same bead." },
        { img: "beta", title: "Beta value formula", body: "Beta is methylated intensity divided by total methylated plus unmethylated intensity plus a constant, usually 100, to avoid 0/0 errors.", professor: "She stresses that beta values are between 0 and 1 and represent methylation level, not a direct cell-by-cell state.", exam: { question: "Possible question: define beta value and interpret its range.", include: ["Give the formula conceptually: M/(M+U+100).", "Explain the +100 constant as protection from zero/zero errors.", "Interpret 0, 1 and intermediate values.", "Link beta values to the CpG-by-sample matrix."], trap: "Do not interpret beta 0.5 as exactly one allele methylated in every cell. It is an aggregate intensity ratio from a DNA pool.", answer: "The beta value is the usual Illumina methylation measure. Conceptually, it is the methylated intensity divided by the total methylated plus unmethylated intensity, with a constant such as 100 added to avoid undefined values when signals are very low. Beta values range from 0 to 1: values near 0 indicate little methylation, values near 1 indicate high methylation, and intermediate values reflect mixed methylation states in the DNA pool." } },
        { img: "bimodal", title: "Expected bimodal distribution", body: "Beta values often show peaks near 0 and 1, with intermediate values in between. This is a first sanity check of methylation data." }
      ], extra: "beta"},
      { title: "8. Probe-type bias and normalization", intro: "Because Infinium I and II are different designs, they can have different distributions and variance. This motivates normalization, but the detailed pipeline is left for Module 2.", slides: [
        { img: "diffs", title: "Infinium I and II differ", body: "The two probe types do not have identical signal behavior. They are different technologies inside the same array." },
        { img: "bias", title: "Systematic bias between probe types", body: "The professor compares this to earlier bias problems: not the same as Cy3/Cy5, but still a technical consequence of a design decision.", professor: "Her phrase is essentially: take a decision, you have a consequence. The design enables methylation measurement but creates normalization problems.", exam: { question: "Possible question: why do Illumina methylation arrays need normalization?", include: ["Mention Infinium I/II probe-type differences.", "Explain that their distributions/variances may not align.", "State that intra-array normalization can align probe-type behavior.", "Acknowledge that detailed normalization choices belong to Module 2."], trap: "Do not say normalization is only for competitive arrays. Illumina avoids the Stanford design but introduces its own probe-type and colour/intensity issues.", answer: "Illumina methylation arrays need normalization because the Infinium I and Infinium II probe designs do not produce perfectly comparable distributions. They interrogate different CpGs and use different bead/colour logic, so their intensity distributions and variance can differ. To analyze all CpGs together, preprocessing may include intra-array normalization to reduce systematic probe-type bias. The detailed choice of normalization method is part of the Module 2 data-analysis pipeline." } },
        { img: "mvalues", title: "Beta values and M values", body: "Beta values are intuitive but heteroscedastic. M values use a log ratio of methylated/unmethylated signal and can be useful in statistical analysis." },
        { img: "normalization", title: "Normalization overview", body: "Early proposals tried to align Infinium II to Infinium I peaks; later pipelines offer multiple choices that will be compared in Module 2." }
      ], extra: "bias"},
      { title: "9. Biological interpretation and epigenetic clocks", intro: "The final part moves from chemistry to applications: methylation can be related to gene expression, disease, aging and biological clocks.", slides: [
        { img: "dmr", title: "Interpreting regions and differential methylation", body: "Methylated CpGs may be interpreted in relation to islands, shores, shelves, open sea, genes and regulatory regions, but correlation with expression is not automatic." },
        { img: "clock", title: "Epigenetic clocks", body: "Specific CpGs can be used to estimate biological age or age acceleration, linking methylation to aging and disease." },
        { img: "clockDesc", title: "Horvath and GrimAge logic", body: "Horvath-type clocks use selected CpGs to estimate age; GrimAge-like clocks relate methylation signatures to mortality risk." },
        { img: "elovl2", title: "ELOVL2 as an aging marker", body: "The professor highlights ELOVL2 CpGs as a striking example of methylation strongly correlating with chronological age." },
        { img: "ageAlgo", title: "From CpG values to an age algorithm", body: "Clock models combine multiple CpGs to estimate epigenetic age or age acceleration." },
        { img: "consensus", title: "Current clinical consensus", body: "The last slide frames GrimAge/GrimAge2 as strong clinical-age predictors, while reminding us that clocks are model-based biomarkers.", professor: "The application point is not memorizing every clock name; it is understanding that targeted CpG methylation profiles can become biomarkers.", exam: { question: "Possible question: give an application of methylation arrays beyond technical measurement.", include: ["Mention epigenetic clocks as methylation-based biomarkers.", "Explain that selected CpGs correlate with age or mortality risk.", "Connect this to biological questions such as aging, disease, exposome or lifestyle."], trap: "Do not present epigenetic clocks as measuring chronological age only. Their value is estimating biological age, acceleration or risk-related methylation patterns.", answer: "One important application of methylation arrays is the construction of epigenetic clocks. These models use selected CpG methylation levels to estimate biological age or age acceleration. Some clocks, such as Horvath-type clocks, focus on age prediction, while GrimAge-like clocks are linked to mortality risk and health status. This makes DNA methylation a useful biomarker layer for studying aging, disease, exposome effects and lifestyle-related changes." } }
      ]}
    ],
    fraction: { title: "Methylation fraction mini-lab", intro: "Move the number of methylated CpGs in a toy DNA pool and watch the methylation percentage change.", methylated: "Methylated molecules", total: "Total molecules", interpretation: "Interpretation", low: "mostly unmethylated", mid: "mixed methylation state", high: "mostly methylated" },
    platform: { title: "Platform comparison", prompt: "Choose a platform to review what it means for the course.", items: { "27K": "First methylation BeadChip generation: limited CpG coverage.", "450K": "Reference platform for the Module 2 dataset and a major expansion of CpG coverage.", "EPIC v1": "More than 850K CpGs and high overlap with 450K for comparability.", "EPIC v2": "Nearly one million CpGs with additional regulatory and disease-relevant loci." } },
    bisulfite: { title: "Bisulfite rule checkpoint", prompt: "After bisulfite + PCR, what does each base mean?", scenarios: [{ q: "CpG position is read as C", a: "Originally methylated" }, { q: "CpG position is read as T", a: "Originally unmethylated" }, { q: "PCR is done without bisulfite", a: "Methylation information is lost" }] },
    infinium: { title: "Infinium strategy sorter", prompt: "Assign each statement to Infinium I or Infinium II.", items: [{ text: "Two bead types: U and M", answer: "Infinium I" }, { text: "One bead and one probe per CpG", answer: "Infinium II" }, { text: "Colour identifies the added nucleotide on the same bead", answer: "Infinium II" }, { text: "Fluorescence is interpreted mainly by bead identity", answer: "Infinium I" }] },
    betaLab: { title: "Beta value calculator", m: "Methylated intensity", u: "Unmethylated intensity", beta: "Beta", note: "Formula: M / (M + U + 100). Intermediate values reflect a DNA pool." },
    biasLab: { title: "Probe-type bias checkpoint", question: "Infinium I and II distributions are not aligned. What is the best interpretation?", options: ["This proves a biological difference", "This is a technical probe-type bias that may need normalization", "This means beta values are impossible to use"], answer: 1 },
    quiz: { title: "Quick quiz", items: [
      { q: "What is the key manufacturing difference of Illumina BeadChip compared with Affymetrix?", options: ["Spotting of cDNA", "Beads with pre-made oligos assembled into pits", "Only sequencing", "No probes"], answer: 1 },
      { q: "After bisulfite + PCR, T at a CpG position indicates:", options: ["original methylated C", "original unmethylated C", "protein methylation", "no DNA"], answer: 1 },
      { q: "Infinium I uses:", options: ["one bead only", "two beads/probes for U and M", "no bisulfite", "RNA targets"], answer: 1 },
      { q: "Infinium II distinguishes states mainly by:", options: ["DAT/CEL files", "single-base extension colour on one bead", "dye swap", "PM/MM probes"], answer: 1 },
      { q: "Beta values range from:", options: ["-1 to 1", "0 to 1", "0 to 1000", "any real number"], answer: 1 },
      { q: "Why is +100 added in the beta formula?", options: ["To make values larger", "To avoid 0/0 problems", "To convert to p-value", "To remove CpGs"], answer: 1 },
      { q: "The expected beta distribution is often:", options: ["bimodal", "always flat", "always normal", "impossible to plot"], answer: 0 },
      { q: "A main source of Illumina normalization issues is:", options: ["no CpG IDs", "Infinium I/II probe-type differences", "absence of DNA", "lack of fluorescence"], answer: 1 }
    ]},
    written: { title: "Written exam trainer", prompt: "Practice answer: Explain how Illumina BeadChip arrays measure DNA methylation, including bisulfite conversion, Infinium I/II logic and beta values.", placeholder: "Write a 10–12 line answer here...", model: "Illumina methylation BeadChips measure DNA methylation at known CpG sites using a bead-based array. DNA is first extracted and treated with bisulfite, because PCR alone would erase methylation information. After conversion, originally unmethylated cytosines become uracil and then thymine, whereas originally methylated cytosines remain read as cytosine. The array therefore performs a genotyping-like interrogation of C or T at a known CpG. Infinium I uses two bead/probe types for the same CpG, one unmethylated and one methylated. Infinium II uses one bead and identifies the added labelled nucleotide by colour. The final signal is summarized as a beta value, M divided by M plus U plus 100, ranging from 0 to 1. Intermediate beta values reflect mixed methylation states in a DNA pool. Because Infinium I and II have different signal distributions, normalization may be required before downstream analysis." }
  },
  es: {
    mark: "Marcar completada", done: "Completada", previous: "Anterior", next: "Siguiente", current: "Lección 5", dashboard: "Panel DRD", previousTitle: "M1.3 Affymetrix GeneChip", nextTitle: "M2.1 R/Bioconductor intro", resources: "Recursos de clase", slides: "Slides", transcript: "Transcripción", recording: "Grabación", open: "Abrir", zoom: "Clic para ampliar", close: "Cerrar zoom", slide: "Slide", professor: "Énfasis de la profesora", exam: "Ojo para examen", report: "Abrir respuesta desarrollada", include: "Qué incluir", trap: "Trampa frecuente", model: "Respuesta modelo", checkpoint: "Checkpoint", correct: "Correcto", tryAgain: "Inténtalo de nuevo", words: "palabras", heroEyebrow: "Module 1 · 12 de mayo · Illumina Inc. and BeadChip", heroTitle: "Illumina BeadChip y lógica de arrays de metilación", heroSubtitle: "Lección guiada por slides sobre arrays basados en beads, conversión con bisulfito, química Infinium I/II, beta values, bias por tipo de probe y aplicaciones de epigenetic clocks.", flow: ["beads", "metilación CpG", "27K/450K/EPIC", "bisulfito", "Infinium I/II", "beta values", "normalización", "aplicaciones"]
  },
  fa: {
    mark: "علامت‌گذاری به‌عنوان کامل", done: "کامل شد", previous: "قبلی", next: "بعدی", current: "درس ۵", dashboard: "داشبورد DRD", previousTitle: "M1.3 Affymetrix GeneChip", nextTitle: "M2.1 R/Bioconductor intro", resources: "منابع کلاس", slides: "اسلایدها", transcript: "رونوشت", recording: "ضبط", open: "باز کردن", zoom: "برای بزرگ‌نمایی کلیک کنید", close: "بستن بزرگ‌نمایی", slide: "اسلاید", professor: "تأکید استاد", exam: "نکتهٔ امتحان", report: "باز کردن پاسخ کامل", include: "چه چیزهایی بیاوریم", trap: "دام رایج", model: "پاسخ نمونه", checkpoint: "چک‌پوینت", correct: "درست", tryAgain: "دوباره تلاش کنید", words: "کلمه", heroEyebrow: "Module 1 · ۱۲ مه · Illumina Inc. and BeadChip", heroTitle: "Illumina BeadChip و منطق آرایه‌های متیلاسیون", heroSubtitle: "درسی بر اساس اسلایدها دربارهٔ bead arrays، تبدیل bisulfite، شیمی Infinium I/II، beta value، bias نوع probe و کاربردهای epigenetic clock.", flow: ["beads", "متیلاسیون CpG", "27K/450K/EPIC", "bisulfite", "Infinium I/II", "beta value", "normalization", "کاربردها"]
  }
};

function localize(lang) {
  if (lang === "es") return { ...COPY.en, ...COPY.es };
  if (lang === "fa") return { ...COPY.en, ...COPY.fa };
  return COPY.en;
}

function Pill({ children, tone = "red" }) {
  const tones = { red: "border-red-200 bg-red-50 text-red-700", stone: "border-stone-200 bg-stone-50 text-stone-700", amber: "border-amber-200 bg-amber-50 text-amber-800" };
  return <span className={`inline-flex w-fit rounded-full border px-3 py-1 text-[11px] font-black uppercase tracking-[0.18em] ${tones[tone]}`}>{children}</span>;
}
function SectionHeader({ eyebrow, title, children }) { return <div className="mb-5"><Pill>{eyebrow}</Pill><h2 className="mt-3 text-3xl font-black tracking-tight text-stone-950 md:text-4xl">{title}</h2>{children ? <p className="mt-3 max-w-4xl text-sm font-semibold leading-7 text-stone-600 md:text-base">{children}</p> : null}</div>; }
function ResourceButton({ href, label }) { return <a href={href} target="_blank" rel="noreferrer" className="rounded-2xl border border-stone-200 bg-white px-4 py-3 text-sm font-black text-stone-700 shadow-sm transition hover:-translate-y-0.5 hover:border-red-200 hover:text-red-700">{label} ↗</a>; }
function Navigation({ copy, isDone, toggle, position = "top" }) { return <nav className={`${position === "bottom" ? "mt-10" : "mb-6"} rounded-[2rem] border border-stone-200 bg-white/85 p-3 shadow-sm`} aria-label="Lesson navigation"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><a href="#/lesson/m1-affy" className="rounded-full border border-stone-200 bg-stone-50 px-4 py-2 text-sm font-black text-stone-700 transition hover:-translate-y-0.5 hover:bg-white hover:shadow-md">← {copy.previous}: {copy.previousTitle}</a><div className="flex flex-col items-stretch gap-2 sm:flex-row sm:items-center sm:justify-center"><a href="#/" className="rounded-full border border-stone-200 bg-white px-4 py-2 text-center text-xs font-black uppercase tracking-[0.2em] text-stone-500 transition hover:bg-stone-50">{copy.current} · {copy.dashboard}</a><button onClick={toggle} className={`rounded-full px-4 py-2 text-sm font-black shadow-sm transition hover:-translate-y-0.5 ${isDone ? "bg-emerald-600 text-white" : "bg-stone-950 text-white"}`}>{isDone ? copy.done : copy.mark}</button></div><a href="#/lesson/m2-r" className="rounded-full bg-stone-950 px-4 py-2 text-sm font-black text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-red-700 hover:shadow-md">{copy.next}: {copy.nextTitle} →</a></div></nav>; }
function ExamWatch({ copy, data }) { if (!data) return null; return <div className="mt-4 rounded-[1.75rem] border border-red-200 bg-red-50/80 p-4 text-sm font-bold leading-6 text-red-950"><div className="text-xs font-black uppercase tracking-[0.22em] text-red-700">{copy.exam}</div><p className="mt-2 font-black">{data.question}</p><details className="mt-4 rounded-2xl border border-red-200 bg-white/80 p-4"><summary className="cursor-pointer text-sm font-black text-red-800">{copy.report}</summary><div className="mt-4 grid gap-3"><div><div className="text-xs font-black uppercase tracking-[0.2em] text-stone-500">{copy.include}</div><ul className="mt-2 list-disc space-y-2 pl-5">{data.include.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-3"><div className="text-xs font-black uppercase tracking-[0.2em] text-amber-800">{copy.trap}</div><p className="mt-2">{data.trap}</p></div><div className="rounded-2xl border border-stone-200 bg-stone-50 p-3"><div className="text-xs font-black uppercase tracking-[0.2em] text-stone-500">{copy.model}</div><p className="mt-2">{data.answer}</p></div></div></details></div>; }
function ProfessorNote({ copy, children }) { if (!children) return null; return <div className="mt-4 rounded-[1.5rem] border border-amber-200 bg-amber-50 p-4 text-sm font-bold leading-6 text-amber-950"><div className="text-xs font-black uppercase tracking-[0.22em] text-amber-800">{copy.professor}</div><p className="mt-2">{children}</p></div>; }
function SlideCard({ copy, item, idx, total, openZoom }) { const img = IMG[item.img]; const full = item.spotlight || (total % 2 === 1 && idx === total - 1) || item.exam; return <article className={`${full ? "lg:col-span-2" : ""} overflow-hidden rounded-[2rem] border border-stone-200 bg-white shadow-sm`}><button type="button" onClick={() => openZoom({ ...item, ...img })} className="group block w-full border-b border-stone-200 bg-stone-50 p-3 text-left"><img src={img.src} alt={item.title} loading="lazy" className="h-full max-h-[520px] w-full rounded-2xl object-contain transition group-hover:scale-[1.01]"/><div className="mt-2 text-xs font-black uppercase tracking-[0.18em] text-red-700">{copy.zoom}</div></button><div className="p-5"><Pill>{copy.slide} {img.slide}</Pill><h3 className="mt-3 text-2xl font-black text-stone-950">{item.title}</h3><p className="mt-2 text-sm font-semibold leading-7 text-stone-600">{item.body}</p><ProfessorNote copy={copy}>{item.professor}</ProfessorNote><ExamWatch copy={copy} data={item.exam}/></div></article>; }
function SlideGrid({ copy, slides, openZoom }) { return <div className="grid gap-5 lg:grid-cols-2">{slides.map((item, idx) => <SlideCard key={`${item.img}-${idx}`} copy={copy} item={item} idx={idx} total={slides.length} openZoom={openZoom}/>)}</div>; }
function ZoomModal({ copy, zoom, setZoom }) { if (!zoom) return null; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-stone-950/80 p-4" onClick={() => setZoom(null)}><div className="max-h-[92vh] w-[min(1200px,96vw)] overflow-auto rounded-[2rem] bg-white p-4 shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="mb-3 flex items-center justify-between gap-3"><div><Pill>{copy.slide} {zoom.slide}</Pill><h3 className="mt-2 text-xl font-black text-stone-950">{zoom.title}</h3></div><button onClick={() => setZoom(null)} className="rounded-full bg-stone-950 px-4 py-2 text-sm font-black text-white">{copy.close}</button></div><img src={zoom.src} alt={zoom.title} className="w-full rounded-2xl object-contain"/></div></div>; }
function FractionLab({ copy }) { const [m, setM] = useState(6); const total = 24; const pct = Math.round((m / total) * 100); const label = pct < 30 ? copy.fraction.low : pct > 70 ? copy.fraction.high : copy.fraction.mid; return <InteractiveShell title={copy.fraction.title} intro={copy.fraction.intro}><label className="text-sm font-black text-stone-700">{copy.fraction.methylated}: {m}/{total}</label><input className="mt-3 w-full accent-red-700" type="range" min="0" max={total} value={m} onChange={(e) => setM(Number(e.target.value))}/><div className="mt-4 rounded-2xl bg-stone-950 p-5 text-white"><div className="text-4xl font-black">{pct}%</div><p className="mt-2 text-sm font-bold text-stone-200">{copy.fraction.interpretation}: {label}</p></div></InteractiveShell>; }
function PlatformComparator({ copy }) { const [active, setActive] = useState("450K"); return <InteractiveShell title={copy.platform.title} intro={copy.platform.prompt}><div className="grid gap-2 sm:grid-cols-4">{Object.keys(copy.platform.items).map((key) => <button key={key} onClick={() => setActive(key)} className={`rounded-2xl border px-3 py-3 text-sm font-black transition ${active === key ? "border-red-300 bg-red-50 text-red-800" : "border-stone-200 bg-white text-stone-700 hover:bg-stone-50"}`}>{key}</button>)}</div><p className="mt-4 rounded-2xl border border-stone-200 bg-stone-50 p-4 text-sm font-bold leading-6 text-stone-700">{copy.platform.items[active]}</p></InteractiveShell>; }
function BisulfiteQuiz({ copy }) { const [choices, setChoices] = useState({}); return <InteractiveShell title={copy.bisulfite.title} intro={copy.bisulfite.prompt}><div className="grid gap-3">{copy.bisulfite.scenarios.map((s) => <div key={s.q} className="rounded-2xl border border-stone-200 bg-white p-4"><div className="font-black text-stone-950">{s.q}</div><div className="mt-3 flex flex-wrap gap-2">{copy.bisulfite.scenarios.map((o) => <button key={o.a} onClick={() => setChoices({ ...choices, [s.q]: o.a })} className={`rounded-full border px-3 py-1 text-xs font-black ${choices[s.q] === o.a ? (o.a === s.a ? "border-emerald-300 bg-emerald-50 text-emerald-700" : "border-red-300 bg-red-50 text-red-700") : "border-stone-200 bg-stone-50 text-stone-600"}`}>{o.a}</button>)}</div></div>)}</div></InteractiveShell>; }
function InfiniumSorter({ copy }) { const [answers, setAnswers] = useState({}); return <InteractiveShell title={copy.infinium.title} intro={copy.infinium.prompt}><div className="grid gap-3 md:grid-cols-2">{copy.infinium.items.map((item) => <div key={item.text} className="rounded-2xl border border-stone-200 bg-white p-4"><div className="font-black text-stone-950">{item.text}</div><div className="mt-3 flex gap-2"><button onClick={() => setAnswers({ ...answers, [item.text]: "Infinium I" })} className={`rounded-full border px-3 py-1 text-xs font-black ${answers[item.text] === "Infinium I" ? (item.answer === "Infinium I" ? "border-emerald-300 bg-emerald-50 text-emerald-700" : "border-red-300 bg-red-50 text-red-700") : "border-stone-200 bg-stone-50"}`}>Infinium I</button><button onClick={() => setAnswers({ ...answers, [item.text]: "Infinium II" })} className={`rounded-full border px-3 py-1 text-xs font-black ${answers[item.text] === "Infinium II" ? (item.answer === "Infinium II" ? "border-emerald-300 bg-emerald-50 text-emerald-700" : "border-red-300 bg-red-50 text-red-700") : "border-stone-200 bg-stone-50"}`}>Infinium II</button></div></div>)}</div></InteractiveShell>; }
function BetaCalculator({ copy }) { const [m, setM] = useState(800); const [u, setU] = useState(200); const beta = m / (m + u + 100); return <InteractiveShell title={copy.betaLab.title} intro={copy.betaLab.note}><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-black text-stone-700">{copy.betaLab.m}<input type="number" value={m} onChange={(e) => setM(Math.max(0, Number(e.target.value)))} className="mt-2 w-full rounded-2xl border border-stone-200 bg-white px-4 py-3"/></label><label className="text-sm font-black text-stone-700">{copy.betaLab.u}<input type="number" value={u} onChange={(e) => setU(Math.max(0, Number(e.target.value)))} className="mt-2 w-full rounded-2xl border border-stone-200 bg-white px-4 py-3"/></label></div><div className="mt-4 rounded-2xl bg-stone-950 p-5 text-white"><div className="text-sm font-black uppercase tracking-[0.2em] text-stone-300">{copy.betaLab.beta}</div><div className="mt-1 text-4xl font-black">{beta.toFixed(3)}</div></div></InteractiveShell>; }
function BiasCheckpoint({ copy }) { const [choice, setChoice] = useState(null); return <InteractiveShell title={copy.biasLab.title} intro={copy.biasLab.question}><div className="grid gap-2">{copy.biasLab.options.map((option, idx) => <button key={option} onClick={() => setChoice(idx)} className={`rounded-2xl border px-4 py-3 text-left text-sm font-black transition ${choice === idx ? (idx === copy.biasLab.answer ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-red-300 bg-red-50 text-red-800") : "border-stone-200 bg-white text-stone-700 hover:bg-stone-50"}`}>{option}</button>)}</div></InteractiveShell>; }
function InteractiveShell({ title, intro, children }) { return <section className="my-8 rounded-[2rem] border border-stone-200 bg-white/85 p-6 shadow-sm"><h3 className="text-2xl font-black text-stone-950">{title}</h3><p className="mt-2 text-sm font-semibold leading-6 text-stone-600">{intro}</p><div className="mt-5">{children}</div></section>; }
function Quiz({ copy }) { const [answers, setAnswers] = useState({}); const score = copy.quiz.items.reduce((acc, item, i) => acc + (answers[i] === item.answer ? 1 : 0), 0); return <section className="mt-10 rounded-[2rem] border border-stone-200 bg-white p-6 shadow-sm"><SectionHeader eyebrow={copy.checkpoint} title={copy.quiz.title}>Score: {score}/{copy.quiz.items.length}</SectionHeader><div className="grid gap-4 md:grid-cols-2">{copy.quiz.items.map((item, i) => <div key={item.q} className="rounded-2xl border border-stone-200 bg-stone-50 p-4"><p className="font-black text-stone-950">{i + 1}. {item.q}</p><div className="mt-3 grid gap-2">{item.options.map((option, j) => <button key={option} onClick={() => setAnswers({ ...answers, [i]: j })} className={`rounded-xl border px-3 py-2 text-left text-sm font-bold ${answers[i] === j ? (j === item.answer ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-red-300 bg-red-50 text-red-800") : "border-stone-200 bg-white text-stone-700"}`}>{option}</button>)}</div></div>)}</div></section>; }
function WrittenTrainer({ copy }) { const [text, setText] = useState(""); const wc = text.trim() ? text.trim().split(/\s+/).length : 0; return <section className="mt-10 rounded-[2rem] border border-stone-200 bg-white p-6 shadow-sm"><SectionHeader eyebrow={copy.exam} title={copy.written.title}>{copy.written.prompt}</SectionHeader><textarea value={text} onChange={(e) => setText(e.target.value)} placeholder={copy.written.placeholder} className="min-h-[220px] w-full rounded-[1.5rem] border border-stone-200 bg-stone-50 p-4 text-sm font-semibold leading-6 outline-none focus:border-red-300"/><div className="mt-2 text-xs font-black uppercase tracking-[0.18em] text-stone-500">{wc} {copy.words}</div><details className="mt-4 rounded-[1.5rem] border border-stone-200 bg-stone-50 p-4"><summary className="cursor-pointer font-black text-red-800">{copy.model}</summary><p className="mt-3 text-sm font-semibold leading-7 text-stone-700">{copy.written.model}</p></details></section>; }

export default function DRDLesson05({ lang = "es", isDone = false, toggle = () => {} }) {
  const copy = localize(lang);
  const [zoom, setZoom] = useState(null);
  const extras = { fraction: <FractionLab copy={copy}/>, platforms: <PlatformComparator copy={copy}/>, bisulfite: <BisulfiteQuiz copy={copy}/>, infinium: <InfiniumSorter copy={copy}/>, beta: <BetaCalculator copy={copy}/>, bias: <BiasCheckpoint copy={copy}/> };
  const sections = useMemo(() => COPY.en.sections, []);
  return <main className="mx-auto w-[min(1180px,calc(100%-24px))] pb-16 pt-8 text-stone-900"><Navigation copy={copy} isDone={isDone} toggle={toggle}/><section className="grid gap-6 lg:grid-cols-[1.3fr_0.7fr]"><div className="rounded-[2.5rem] border border-red-100 bg-gradient-to-br from-white to-red-50 p-7 shadow-sm md:p-10"><Pill>{copy.heroEyebrow}</Pill><h1 className="mt-4 text-4xl font-black tracking-tight text-stone-950 md:text-6xl">{copy.heroTitle}</h1><p className="mt-4 max-w-3xl text-lg font-semibold leading-8 text-stone-700">{copy.heroSubtitle}</p><div className="mt-6 flex flex-wrap gap-2">{copy.flow.map((tag) => <Pill key={tag} tone="stone">{tag}</Pill>)}</div></div><aside className="rounded-[2.5rem] border border-stone-200 bg-white/90 p-6 shadow-sm"><h2 className="text-2xl font-black text-stone-950">{copy.resources}</h2><div className="mt-5 grid gap-3"><ResourceButton href={SLIDES_URL} label={copy.slides}/><ResourceButton href={TRANSCRIPT_URL} label={copy.transcript}/><ResourceButton href={RECORDING_URL} label={copy.recording}/></div></aside></section>{sections.map((section, idx) => <section key={section.title} className="mt-10 rounded-[2.5rem] border border-stone-200 bg-white/70 p-5 shadow-sm md:p-7"><SectionHeader eyebrow={`Part ${idx + 1}`} title={section.title}>{section.intro}</SectionHeader><SlideGrid copy={copy} slides={section.slides} openZoom={setZoom}/>{section.extra ? extras[section.extra] : null}</section>)}<Quiz copy={copy}/><WrittenTrainer copy={copy}/><Navigation copy={copy} isDone={isDone} toggle={toggle} position="bottom"/><ZoomModal copy={copy} zoom={zoom} setZoom={setZoom}/></main>;
}
