import React, { useMemo, useState } from "react";
import titleSlide from "../../assets/drd/lesson07/title.jpg";
import rykTTestSlide from "../../assets/drd/lesson07/ryk-t-test.jpg";
import bootstrapResamplingSlide from "../../assets/drd/lesson07/bootstrap-resampling.jpg";
import bootstrapMillionSlide from "../../assets/drd/lesson07/bootstrap-million.jpg";
import bootstrapHistogramSlide from "../../assets/drd/lesson07/bootstrap-histogram.jpg";
import testComparisonSlide from "../../assets/drd/lesson07/test-comparison.jpg";
import anovaOverviewSlide from "../../assets/drd/lesson07/anova-overview.jpg";
import anovaFStatisticSlide from "../../assets/drd/lesson07/anova-f-statistic.jpg";
import fDistributionSlide from "../../assets/drd/lesson07/f-distribution.jpg";
import anovaAssumptionsSlide from "../../assets/drd/lesson07/anova-assumptions.jpg";
import anovaDataSlide from "../../assets/drd/lesson07/anova-data.jpg";
import anovaGroupMeansSlide from "../../assets/drd/lesson07/anova-group-means.jpg";
import anovaTableFSlide from "../../assets/drd/lesson07/anova-table-f.jpg";
import anovaCriticalSlide from "../../assets/drd/lesson07/anova-critical.jpg";
import anovaConclusionSlide from "../../assets/drd/lesson07/anova-conclusion.jpg";
import kruskalOverviewSlide from "../../assets/drd/lesson07/kruskal-overview.jpg";
import kruskalChiSquareSlide from "../../assets/drd/lesson07/kruskal-chi-square.jpg";
import kruskalFormulaSlide from "../../assets/drd/lesson07/kruskal-formula.jpg";
import kruskalDataSlide from "../../assets/drd/lesson07/kruskal-data.jpg";
import kruskalSortSlide from "../../assets/drd/lesson07/kruskal-sort.jpg";
import kruskalRanksSlide from "../../assets/drd/lesson07/kruskal-ranks.jpg";
import kruskalHSlide from "../../assets/drd/lesson07/kruskal-h.jpg";
import kruskalDecisionSlide from "../../assets/drd/lesson07/kruskal-decision.jpg";
import kruskalCurveSlide from "../../assets/drd/lesson07/kruskal-curve.jpg";
import multipleTestingWhySlide from "../../assets/drd/lesson07/multiple-testing-why.jpg";
import fwer226Slide from "../../assets/drd/lesson07/fwer-226.jpg";
import bonferroniFormulaSlide from "../../assets/drd/lesson07/bonferroni-formula.jpg";
import dataset6350Slide from "../../assets/drd/lesson07/dataset-6350.jpg";
import pvalueMatrixSlide from "../../assets/drd/lesson07/pvalue-matrix.jpg";
import pAdjustedFormulaSlide from "../../assets/drd/lesson07/p-adjusted-formula.jpg";
import bonferroniStringentSlide from "../../assets/drd/lesson07/bonferroni-stringent.jpg";
import fdrExpectedSlide from "../../assets/drd/lesson07/fdr-expected.jpg";
import fdrFormulaSlide from "../../assets/drd/lesson07/fdr-formula.jpg";
import fdrStepsSlide from "../../assets/drd/lesson07/fdr-steps.jpg";
import bhOverviewSlide from "../../assets/drd/lesson07/bh-overview.jpg";
import bhPvaluesSlide from "../../assets/drd/lesson07/bh-pvalues.jpg";
import bhCriticalSlide from "../../assets/drd/lesson07/bh-critical.jpg";
import degRulesSlide from "../../assets/drd/lesson07/deg-rules.jpg";
import gseaIntroSlide from "../../assets/drd/lesson07/gsea-intro.jpg";
import gseaDefinitionSlide from "../../assets/drd/lesson07/gsea-definition.jpg";
import gseaOutputsSlide from "../../assets/drd/lesson07/gsea-outputs.jpg";
import nesDefinitionSlide from "../../assets/drd/lesson07/nes-definition.jpg";
import nesFdrSlide from "../../assets/drd/lesson07/nes-fdr.jpg";

const SLIDES_URL = "https://drive.google.com/file/d/1mgvgsmiFN2nAh6nT3-RRiUslcDaMZWvX/view?usp=drivesdk";
const TRANSCRIPT_URL = "https://docs.google.com/document/d/145GkBXGfP4tngdTcFf5LjMxFMI8Hqi5QgeZy2aJtnkA/edit?usp=drivesdk";
const RECORDING_URL = "https://www.youtube.com/watch?v=HvS_eWmN5Us&list=PLZSGWjLWZL3KQFkSCUbUXWEVHeF0MTYZV&index=11";

const IMG = {
  title: { src: titleSlide, slide: 1 }, ryk: { src: rykTTestSlide, slide: 3 }, bootMethod: { src: bootstrapResamplingSlide, slide: 4 }, bootMillion: { src: bootstrapMillionSlide, slide: 5 }, bootHist: { src: bootstrapHistogramSlide, slide: 6 }, comparison: { src: testComparisonSlide, slide: 8 }, anovaOverview: { src: anovaOverviewSlide, slide: 9 }, anovaF: { src: anovaFStatisticSlide, slide: 10 }, fDist: { src: fDistributionSlide, slide: 12 }, anovaAssumptions: { src: anovaAssumptionsSlide, slide: 14 }, anovaData: { src: anovaDataSlide, slide: 15 }, anovaMeans: { src: anovaGroupMeansSlide, slide: 17 }, anovaTable: { src: anovaTableFSlide, slide: 20 }, anovaCritical: { src: anovaCriticalSlide, slide: 22 }, anovaConclusion: { src: anovaConclusionSlide, slide: 23 }, kruskalOverview: { src: kruskalOverviewSlide, slide: 24 }, kruskalChi: { src: kruskalChiSquareSlide, slide: 25 }, kruskalFormula: { src: kruskalFormulaSlide, slide: 26 }, kruskalData: { src: kruskalDataSlide, slide: 27 }, kruskalSort: { src: kruskalSortSlide, slide: 28 }, kruskalRanks: { src: kruskalRanksSlide, slide: 29 }, kruskalH: { src: kruskalHSlide, slide: 30 }, kruskalDecision: { src: kruskalDecisionSlide, slide: 31 }, kruskalCurve: { src: kruskalCurveSlide, slide: 33 }, multiWhy: { src: multipleTestingWhySlide, slide: 35 }, fwer: { src: fwer226Slide, slide: 36 }, bonferroniFormula: { src: bonferroniFormulaSlide, slide: 37 }, dataset: { src: dataset6350Slide, slide: 38 }, pMatrix: { src: pvalueMatrixSlide, slide: 39 }, pAdjusted: { src: pAdjustedFormulaSlide, slide: 40 }, bonferroniStringent: { src: bonferroniStringentSlide, slide: 41 }, fdrExpected: { src: fdrExpectedSlide, slide: 42 }, fdrFormula: { src: fdrFormulaSlide, slide: 43 }, fdrSteps: { src: fdrStepsSlide, slide: 44 }, bhOverview: { src: bhOverviewSlide, slide: 45 }, bhPvalues: { src: bhPvaluesSlide, slide: 46 }, bhCritical: { src: bhCriticalSlide, slide: 47 }, degRules: { src: degRulesSlide, slide: 48 }, gseaIntro: { src: gseaIntroSlide, slide: 49 }, gseaDefinition: { src: gseaDefinitionSlide, slide: 50 }, gseaOutputs: { src: gseaOutputsSlide, slide: 51 }, nesDefinition: { src: nesDefinitionSlide, slide: 52 }, nesFdr: { src: nesFdrSlide, slide: 53 }
};

const UI = {
  en: { current: "Lesson 7", dashboard: "DRD dashboard", previous: "Previous", next: "Next", previousTitle: "M1.5 DE genes I", nextTitle: "M1.7 Samples and genes I", mark: "Mark completed", done: "Completed", resources: "Class resources", slides: "Slides", transcript: "Transcript", recording: "Recording", slide: "Slide", zoom: "Click to zoom", close: "Close zoom", professor: "Professor emphasis", exam: "Exam watch", expand: "Open expanded answer", include: "What to include", trap: "Common trap", model: "Sample answer", checkpoint: "Checkpoint", words: "words", module: "Module", writtenExam: "Written test", answerLines: "Answer lines", core: "Core idea", bigIdea: "Big idea", heroEyebrow: "Module 1 · May 27 · Differentially expressed genes II", heroTitle: "From significant genes to reliable biological interpretation", heroSubtitle: "A slide-guided lesson on bootstrap confirmation, one-way ANOVA, Kruskal–Wallis, multiple testing, Bonferroni/FDR/BH correction and gene-set enrichment analysis.", tags: ["bootstrap", "ANOVA", "Kruskal–Wallis", "FWER", "FDR", "GSEA"], bigIdeaText: "After you obtain p-values, the work is not finished: you must ask whether the signal is reproducible, whether the design has more than two groups, whether thousands of tests inflate false positives, and how the final list becomes a biological story." },
  es: { current: "Lección 7", dashboard: "Dashboard DRD", previous: "Anterior", next: "Siguiente", previousTitle: "M1.5 DE genes I", nextTitle: "M1.7 Muestras y genes I", mark: "Marcar completada", done: "Completada", resources: "Recursos de clase", slides: "Slides", transcript: "Transcripción", recording: "Grabación", slide: "Diapo", zoom: "Clic para ampliar", close: "Cerrar zoom", professor: "Énfasis de la profesora", exam: "Ojo para examen", expand: "Abrir respuesta desarrollada", include: "Qué incluir", trap: "Trampa frecuente", model: "Respuesta modelo", checkpoint: "Checkpoint", words: "palabras", module: "Módulo", writtenExam: "Examen escrito", answerLines: "Líneas", core: "Idea clave", bigIdea: "Idea central", heroEyebrow: "Módulo 1 · 27 de mayo · Differentially expressed genes II", heroTitle: "De genes significativos a interpretación biológica fiable", heroSubtitle: "Lección guiada por slides sobre bootstrap, one-way ANOVA, Kruskal–Wallis, multiple testing, correcciones Bonferroni/FDR/BH y gene-set enrichment analysis.", tags: ["bootstrap", "ANOVA", "Kruskal–Wallis", "FWER", "FDR", "GSEA"], bigIdeaText: "Después de obtener p-values, el análisis no termina: hay que preguntar si la señal es reproducible, si el diseño tiene más de dos grupos, si miles de tests inflan falsos positivos y cómo la lista final se convierte en una historia biológica." },
  fa: { current: "درس ۷", dashboard: "داشبورد DRD", previous: "قبلی", next: "بعدی", previousTitle: "M1.5 DE genes I", nextTitle: "M1.7 نمونه‌ها و ژن‌ها I", mark: "علامت‌گذاری به‌عنوان کامل", done: "کامل شد", resources: "منابع کلاس", slides: "اسلایدها", transcript: "رونوشت", recording: "ضبط", slide: "اسلاید", zoom: "برای بزرگ‌نمایی کلیک کنید", close: "بستن بزرگ‌نمایی", professor: "تأکید استاد", exam: "نکتهٔ امتحان", expand: "پاسخ کامل را باز کنید", include: "چه چیزهایی بیاوریم", trap: "اشتباه رایج", model: "پاسخ نمونه", checkpoint: "چک‌پوینت", words: "کلمه", module: "ماژول", writtenExam: "آزمون کتبی", answerLines: "خط پاسخ", core: "ایدهٔ اصلی", bigIdea: "ایدهٔ مرکزی", heroEyebrow: "Module 1 · May 27 · Differentially expressed genes II", heroTitle: "از ژن‌های معنی‌دار تا تفسیر زیستی قابل اعتماد", heroSubtitle: "درس مبتنی بر اسلاید دربارهٔ bootstrap، one-way ANOVA، Kruskal–Wallis، multiple testing، Bonferroni/FDR/BH و gene-set enrichment analysis.", tags: ["bootstrap", "ANOVA", "Kruskal–Wallis", "FWER", "FDR", "GSEA"], bigIdeaText: "پس از گرفتن p-value کار تمام نمی‌شود: باید ببینید سیگنال پایدار است یا نه، طراحی بیش از دو گروه دارد یا نه، هزاران آزمون خطای مثبت کاذب را زیاد می‌کند یا نه، و فهرست نهایی چگونه به تفسیر زیستی تبدیل می‌شود." }
};
function getUi(lang = "es") { return UI[lang] || UI.es; }

const COPY = {
  en: {
    sections: [
      { title: "1. Bootstrap: confirm whether a significant result may be chance", intro: "The professor starts by connecting to the previous t-test result: even p < 0.01 still carries risk. Bootstrap asks whether the observed statistic remains extreme after resampling under the null.", slides: [
        { img: "title", title: "Part II of differential expression", body: "The pipeline now moves from choosing a test to confirming results, handling more than two groups and interpreting gene lists." },
        { img: "ryk", title: "The starting problem: p < 0.01 is not the end", body: "RYK appears significant in ALL vs AML after Welch's t-test, but the professor asks whether the result could still be due to chance." },
        { img: "bootMethod", title: "Resampling under H0", body: "Combine the two groups, reshuffle/resample while keeping the original group sizes, recompute t, and build a null distribution of t statistics." },
        { img: "bootHist", title: "Observed t at the edge", body: "If the original t is in the extreme tail of the bootstrap distribution, the first significant result is supported rather than dismissed as chance.", emphasis: "She says the key idea is conceptual: compare your real statistic with a distribution generated from reshuffled data with similar properties.", exam: { q: "Possible question: when and why would you apply bootstrap?", include: ["Say it is a confirmation/resampling procedure, not a replacement for choosing the correct first test.", "Mention reshuffling/resampling under the null while preserving group sizes.", "Explain that the observed statistic is compared with the bootstrap distribution; extreme observed values support significance."], trap: "Do not describe bootstrap as simply increasing sample size. It creates many resampled datasets to estimate how likely the observed statistic is under H0.", answer: "I would apply bootstrap after an apparently significant result when I want to check whether that result could have arisen by chance. The original groups are combined and repeatedly resampled or reshuffled under the null hypothesis, keeping the same group sizes. For each replicate, the test statistic is recalculated. If the real statistic lies at the extreme tail of the bootstrap distribution, the result is supported; if it falls inside the random distribution, the original significance is less convincing." } }
      ], lab: "bootstrap" },
      { title: "2. Parametric more-than-two groups: one-way ANOVA", intro: "When the biological question has more than two groups, the t-test logic is no longer enough. If the data are parametric and variances are similar, one-way ANOVA compares between-group variability with within-group variability.", slides: [
        { img: "comparison", title: "Student, non-parametric and bootstrap are not the same tool", body: "The professor contrasts power, robustness and goal: t-tests are powerful but assumption-sensitive; non-parametric tests are robust but less powerful; bootstrap confirms chance risk." },
        { img: "anovaOverview", title: "One-way vs two-way ANOVA", body: "One-way means one explanatory variable with more than two levels. Two-way means two variables, for example sex plus treatment dose." },
        { img: "anovaF", title: "F = MS between / MS within", body: "The F statistic becomes large when differences among group means are large relative to variability inside groups." },
        { img: "anovaAssumptions", title: "Assumptions matter", body: "Use ANOVA when distributions are treated as parametric and variances are similar. Otherwise, move toward Kruskal–Wallis." },
        { img: "anovaTable", title: "From SS to MS to F", body: "The example produces F = 3.316 with df1 = 2 and df2 = 10." },
        { img: "anovaConclusion", title: "Decision and post-hoc logic", body: "Because Fcritical = 4.10 is greater than Fobserved = 3.316, H0 is not rejected at 95% confidence. If ANOVA were significant, a post-hoc pairwise test would identify which groups differ.", emphasis: "She stresses that ANOVA can say that something differs, but not automatically which specific pair differs.", exam: { q: "Possible question: when and why do you apply one-way ANOVA?", include: ["Use it for one variable with more than two independent groups.", "State H0: all group means are equal.", "Explain F as between-group variance divided by within-group variance.", "Mention assumptions: parametric distribution and similar variances.", "Add that significant ANOVA requires post-hoc pairwise testing."], trap: "Do not run many independent t-tests instead of ANOVA without correction; that inflates Type I error.", answer: "I would use one-way ANOVA when the biological question compares more than two groups for one variable, for example wild type, mutant and double mutant mice. The null hypothesis is that all group means are equal. ANOVA uses an F statistic, the ratio of mean square between groups to mean square within groups. If between-group variability is large compared with within-group variability, F becomes extreme and p becomes small. It is a parametric test, so I assume normality and similar variances. If the global test is significant, I still need a post-hoc pairwise test to identify which groups differ." } }
      ], lab: "anova" },
      { title: "3. Non-parametric more-than-two groups: Kruskal–Wallis", intro: "If the more-than-two-groups design is not normally distributed or is better represented by ranks, Kruskal–Wallis extends Mann–Whitney logic to three or more groups.", slides: [
        { img: "kruskalOverview", title: "H0: medians are equal", body: "Kruskal–Wallis is non-parametric, rank-based and compares between-group rank variability with overall rank variability." },
        { img: "kruskalChi", title: "H is approximately chi-square distributed", body: "The decision uses a chi-square-like distribution with k − 1 degrees of freedom." },
        { img: "kruskalData", title: "The example starts with three groups", body: "Control, treatment 1 and treatment 2 are pooled into one ranked list." },
        { img: "kruskalH", title: "Rank sums produce H = 6.72", body: "The example sums ranks per group and inserts those sums into the simplified H formula." },
        { img: "kruskalDecision", title: "Hobs > Hcritical", body: "With df = 2 and α = 0.05, Hcritical = 5.99. Because 6.72 is more extreme, H0 is rejected.", emphasis: "She repeats that the test gives the global result; then software/post-hoc tests must clarify which groups differ.", exam: { q: "Possible question: compare ANOVA and Kruskal–Wallis.", include: ["Both answer a more-than-two-groups question.", "ANOVA is parametric and compares means through F.", "Kruskal–Wallis is non-parametric and rank-based, comparing medians/distributions.", "Both may need post-hoc pairwise comparisons after a significant global result."], trap: "Do not say Kruskal–Wallis tells you directly which pair is significant. It gives a global test first.", answer: "Both tests are used when the biological design has more than two groups. One-way ANOVA is parametric: it assumes normality and similar variance and tests equality of means using the F statistic. Kruskal–Wallis is the non-parametric alternative: it ranks all observations and tests whether the groups have equal medians or comparable rank distributions. If either global test is significant, it does not by itself identify which pair differs; a post-hoc pairwise comparison with correction is needed." } }
      ], lab: "kruskal" },
      { title: "4. Multiple testing: why one p-value rule breaks in transcriptomics", intro: "The lesson then shifts from one gene to thousands. If each transcript receives a test, p ≤ 0.05 can produce many false positives just by chance.", slides: [
        { img: "multiWhy", title: "FWER grows with the number of tests", body: "The familywise error rate is the probability of at least one Type I error across a family of hypothesis tests." },
        { img: "fwer", title: "Only five tests already inflate the risk", body: "With α = 0.05 and n = 5 tests, FWER is about 22.6%. The professor calls this an enormous error rate for only five hypotheses." },
        { img: "bonferroniFormula", title: "Bonferroni controls FWER", body: "New α = 0.05 / m. For 1,000 genes this becomes 0.00005." },
        { img: "dataset", title: "A realistic matrix has thousands of rows", body: "In the example there are 6,350 mRNAs, two unrelated groups and one p-value for each gene." },
        { img: "bonferroniStringent", title: "Bonferroni can become too stringent", body: "For 6,350 tests, α becomes 7.9 × 10⁻⁶. The professor says this can remove all significant genes in transcriptomics.", emphasis: "She explicitly warns that Bonferroni is useful for small numbers of tests, but often too strict for thousands of transcriptomic tests.", exam: { q: "Possible question: why is multiple testing correction necessary?", include: ["Explain Type I error and FWER.", "Give the formula 1 − (1 − α)^n conceptually.", "Show why thousands of tests create many false positives.", "Mention Bonferroni and why it can be too stringent in transcriptomics."], trap: "Do not interpret p ≤ 0.05 gene-by-gene as safe when thousands of genes are tested.", answer: "Multiple testing correction is necessary because each hypothesis test has a probability α of a Type I error. When thousands of genes are tested, the chance of at least one false positive increases dramatically: FWER = 1 − (1 − α)^n. Therefore, using p ≤ 0.05 for every gene independently would produce many false discoveries. Bonferroni controls FWER by dividing α by the number of tests, but in transcriptomics this can be too stringent because m is very large, so the cutoff may become so small that no gene remains significant." } }
      ], lab: "fwer" },
      { title: "5. FDR and Benjamini–Hochberg: a more useful transcriptomic correction", intro: "Because Bonferroni can be too harsh for thousands of genes, the professor introduces FDR and the Benjamini–Hochberg procedure as the more common solution for transcriptomics and methylation datasets.", slides: [
        { img: "fdrExpected", title: "Expected false positives at several thresholds", body: "The table compares expected false positives under different α thresholds with the number of observed significant genes." },
        { img: "fdrFormula", title: "FDR = expected false positives / observed significant genes", body: "FDR estimates the proportion of false discoveries among the selected discoveries." },
        { img: "fdrSteps", title: "Four-step FDR logic", body: "Choose thresholds, count significant genes, estimate expected false positives, then choose an acceptable false positive rate and correct p-values." },
        { img: "bhOverview", title: "BH sorts p-values and applies a rank-based threshold", body: "P-values are sorted from smallest to largest; each rank receives a critical value (i/m)q." },
        { img: "bhCritical", title: "The critical BH cutoff", body: "The largest p-value satisfying p(i) ≤ (i/m)q is retained; genes below that rank are considered significant.", emphasis: "A student asked about the stopping rule; the professor clarified that once the BH threshold is violated, the remaining larger p-values are not considered significant.", exam: { q: "Possible question: explain FDR and Benjamini–Hochberg correction.", include: ["Define FDR as the expected proportion of false positives among declared positives.", "State that BH orders p-values and assigns thresholds (i/m)q.", "Find the largest p-value satisfying p(i) ≤ (i/m)q.", "Explain that BH is more common than Bonferroni for large omics datasets."], trap: "Do not confuse FWER and FDR. Bonferroni controls the chance of any false positive; FDR controls the proportion of false discoveries among selected results.", answer: "FDR is the expected proportion of false discoveries among the genes called significant. Benjamini–Hochberg controls FDR by ordering p-values from smallest to largest and assigning each p-value a threshold equal to (i/m)q, where i is the rank, m is the number of tests and q is the chosen FDR. The largest p-value that is still less than or equal to its BH threshold defines the cutoff. This is commonly used in transcriptomics and methylation because Bonferroni is often too stringent when thousands of tests are performed." } }
      ], lab: "bh" },
      { title: "6. From lists to biology: gene-set enrichment analysis", intro: "The final goal is not just a list of up- and down-regulated genes. GSEA helps answer which pathways, GO terms or KEGG/Reactome categories are over-represented in the changed genes.", slides: [
        { img: "degRules", title: "Rules for identifying DE genes", body: "Start from normalized data, define the biological question and design, choose the correct test, correct multiple testing and interpret up/down lists." },
        { img: "gseaIntro", title: "Gene-set enrichment starts from gene lists", body: "GSEA or functional enrichment asks whether biological classes are over-represented in a large set of modified genes." },
        { img: "gseaDefinition", title: "Defined gene sets are compared between states", body: "The GSEA definition emphasizes statistically significant concordant differences between biological states." },
        { img: "gseaOutputs", title: "Typical outputs: GO, KEGG, Reactome", body: "Outputs can include apoptosis, T-cell activation, MAPK signaling, oxidative phosphorylation and directionality." },
        { img: "nesDefinition", title: "NES normalizes enrichment", body: "NES corrects enrichment score by gene-set size and variability across permutations." },
        { img: "nesFdr", title: "NES plus FDR ranks the interpretation", body: "The professor says biologists often inspect top terms with high NES and low FDR to build the biological interpretation.", emphasis: "She closes by saying the gene list alone means little; the biological interpretation comes from connecting lists to pathways and functions.", exam: { q: "Possible question: why use GSEA after differential expression?", include: ["You usually end with long up/down gene lists.", "GSEA maps those lists to predefined GO/KEGG/Reactome gene sets.", "Permutation/internal statistics test whether enrichment is stronger than expected by chance.", "NES and FDR help rank pathway-level results."], trap: "Do not present GSEA as a test for a single gene. It interprets gene sets/pathways from a list or ranked list.", answer: "After differential expression, the result is often a long list of up- and down-regulated genes. This list is hard to interpret gene by gene. GSEA or functional enrichment analysis maps the list to predefined biological categories such as GO terms, KEGG pathways or Reactome pathways. It tests whether genes from a pathway are over-represented or concordantly changed compared with expectation, often using permutations. The output is interpreted through metrics such as NES and FDR, so the final biological story can focus on pathways and functions rather than isolated genes." } }
      ], lab: "gsea" }
    ]
  },
  es: {
    sections: [
      { title: "1. Bootstrap: confirmar si un resultado significativo puede ser azar", intro: "La profesora empieza conectando con el t-test anterior: incluso p < 0.01 mantiene un riesgo. Bootstrap pregunta si el estadístico observado sigue siendo extremo después de remuestrear bajo H0.", slides: [
        { img: "title", title: "Parte II de expresión diferencial", body: "El pipeline pasa de elegir un test a confirmar resultados, manejar más de dos grupos e interpretar listas de genes." },
        { img: "ryk", title: "Problema inicial: p < 0.01 no es el final", body: "RYK parece significativo en ALL vs AML con Welch, pero la profesora pregunta si el resultado aún podría deberse al azar." },
        { img: "bootMethod", title: "Resampling bajo H0", body: "Se combinan los dos grupos, se remezclan manteniendo los tamaños originales, se recalcula t y se construye una distribución nula." },
        { img: "bootHist", title: "t observado en el extremo", body: "Si el t original cae en la cola extrema de la distribución bootstrap, el primer resultado significativo queda respaldado.", emphasis: "La idea clave que remarca: comparar el estadístico real con una distribución generada al remezclar datos con propiedades similares.", exam: { q: "Pregunta posible: ¿cuándo y por qué aplicar bootstrap?", include: ["Decir que es una confirmación por resampling, no un sustituto de elegir el test correcto.", "Mencionar reshuffling/resampling bajo H0 preservando tamaños de grupo.", "Explicar que se compara el estadístico observado con la distribución bootstrap."], trap: "No describas bootstrap como simplemente ‘aumentar’ el sample size. Crea datasets remuestreados para estimar qué tan probable es el estadístico observado bajo H0.", answer: "Aplicaría bootstrap después de un resultado aparentemente significativo cuando quiero comprobar si podría haber ocurrido por azar. Se combinan los grupos originales y se remuestrean o remezclan muchas veces bajo la hipótesis nula, manteniendo los tamaños de grupo. En cada réplica se recalcula el estadístico. Si el estadístico real queda en la cola extrema de la distribución bootstrap, el resultado se confirma; si cae dentro de la distribución aleatoria, la significancia inicial es menos convincente." } }
      ], lab: "bootstrap" },
      { title: "2. Más de dos grupos paramétricos: one-way ANOVA", intro: "Cuando la pregunta biológica tiene más de dos grupos, la lógica de t-test ya no basta. Si los datos son paramétricos y las varianzas son similares, one-way ANOVA compara variabilidad entre grupos contra variabilidad dentro de grupos.", slides: [
        { img: "comparison", title: "Student, no paramétricos y bootstrap no son la misma herramienta", body: "t-test es potente pero sensible a supuestos; los no paramétricos son robustos pero menos potentes; bootstrap confirma riesgo de azar." },
        { img: "anovaOverview", title: "One-way vs two-way ANOVA", body: "One-way significa una variable explicativa con más de dos niveles. Two-way significa dos variables, por ejemplo sexo y dosis." },
        { img: "anovaF", title: "F = MS between / MS within", body: "F se vuelve grande cuando las diferencias entre medias de grupos son grandes respecto a la variabilidad dentro de grupos." },
        { img: "anovaAssumptions", title: "Los supuestos importan", body: "Usa ANOVA si asumes distribución paramétrica y varianzas similares. Si no, pasa a Kruskal–Wallis." },
        { img: "anovaTable", title: "De SS a MS y F", body: "El ejemplo produce F = 3.316 con df1 = 2 y df2 = 10." },
        { img: "anovaConclusion", title: "Decisión y post-hoc", body: "Como Fcrit = 4.10 es mayor que Fobs = 3.316, no se rechaza H0 al 95%. Si ANOVA fuera significativa, un post-hoc identificaría qué grupos difieren.", emphasis: "Remarca que ANOVA puede decir que algo difiere, pero no automáticamente qué par específico difiere.", exam: { q: "Pregunta posible: ¿cuándo y por qué aplicar one-way ANOVA?", include: ["Usarla para una variable con más de dos grupos independientes.", "H0: todas las medias de grupo son iguales.", "F compara varianza entre grupos / varianza dentro de grupos.", "Mencionar supuestos: distribución paramétrica y varianzas similares.", "Añadir que una ANOVA significativa requiere post-hoc."], trap: "No hagas muchos t-tests independientes en lugar de ANOVA sin corrección; inflas el error tipo I.", answer: "Usaría one-way ANOVA cuando la pregunta biológica compara más de dos grupos para una sola variable, por ejemplo wild type, mutant y double mutant. La hipótesis nula es que todas las medias son iguales. ANOVA usa un estadístico F, que es la razón entre mean square between groups y mean square within groups. Si la variabilidad entre grupos es grande comparada con la variabilidad dentro de grupos, F se vuelve extremo y p disminuye. Es un test paramétrico, por lo que asumo normalidad y varianzas similares. Si el test global es significativo, aún necesito un post-hoc para saber qué grupos difieren." } }
      ], lab: "anova" },
      { title: "3. Más de dos grupos no paramétricos: Kruskal–Wallis", intro: "Si el diseño tiene más de dos grupos pero los datos no son normales o conviene tratarlos como rangos, Kruskal–Wallis extiende la lógica de Mann–Whitney a tres o más grupos.", slides: [
        { img: "kruskalOverview", title: "H0: las medianas son iguales", body: "Kruskal–Wallis es no paramétrico, basado en rangos, y compara la variabilidad de rangos entre grupos con la variabilidad global." },
        { img: "kruskalChi", title: "H es aproximadamente chi-square", body: "La decisión usa una distribución parecida a chi-square con k − 1 grados de libertad." },
        { img: "kruskalData", title: "El ejemplo inicia con tres grupos", body: "Control, treatment 1 y treatment 2 se juntan en una lista común y se rankean." },
        { img: "kruskalH", title: "Las sumas de rangos dan H = 6.72", body: "El ejemplo suma los rangos por grupo e inserta esos valores en la fórmula simplificada de H." },
        { img: "kruskalDecision", title: "Hobs > Hcrit", body: "Con df = 2 y α = 0.05, Hcrit = 5.99. Como 6.72 es más extremo, se rechaza H0.", emphasis: "Repite que el test da el resultado global; luego software/post-hoc debe aclarar qué grupos difieren.", exam: { q: "Pregunta posible: compara ANOVA y Kruskal–Wallis.", include: ["Ambos responden una pregunta con más de dos grupos.", "ANOVA es paramétrico y compara medias usando F.", "Kruskal–Wallis es no paramétrico y basado en rangos, compara medianas/distribuciones.", "Ambos pueden requerir comparaciones post-hoc tras un resultado global significativo."], trap: "No digas que Kruskal–Wallis te dice directamente qué par es significativo. Primero da un test global.", answer: "Ambos se usan cuando el diseño biológico tiene más de dos grupos. One-way ANOVA es paramétrico: asume normalidad y varianza similar, y prueba igualdad de medias mediante F. Kruskal–Wallis es la alternativa no paramétrica: transforma todos los datos en rangos y evalúa si los grupos tienen medianas o distribuciones de rangos comparables. Si cualquiera de los dos tests globales es significativo, no identifica por sí solo qué par difiere; se necesita una comparación post-hoc con corrección." } }
      ], lab: "kruskal" },
      { title: "4. Multiple testing: por qué la regla de un p-value se rompe en transcriptómica", intro: "La lección pasa de un gen a miles. Si cada transcript recibe un test, p ≤ 0.05 puede producir muchos falsos positivos por azar.", slides: [
        { img: "multiWhy", title: "FWER crece con el número de tests", body: "Familywise error rate es la probabilidad de al menos un error tipo I dentro de una familia de tests." },
        { img: "fwer", title: "Solo cinco tests ya inflan el riesgo", body: "Con α = 0.05 y n = 5 tests, FWER es ~22.6%. La profesora lo llama enorme para solo cinco hipótesis." },
        { img: "bonferroniFormula", title: "Bonferroni controla FWER", body: "Nuevo α = 0.05 / m. Para 1,000 genes se vuelve 0.00005." },
        { img: "dataset", title: "Una matriz realista tiene miles de filas", body: "El ejemplo tiene 6,350 mRNAs, dos grupos no relacionados y un p-value por cada gen." },
        { img: "bonferroniStringent", title: "Bonferroni puede ser demasiado estricto", body: "Para 6,350 tests, α se vuelve 7.9 × 10⁻⁶. La profesora dice que esto puede eliminar todos los genes significativos.", emphasis: "Advierte explícitamente que Bonferroni sirve para pocos tests, pero suele ser demasiado estricto para miles de tests transcriptómicos.", exam: { q: "Pregunta posible: ¿por qué hace falta corrección por multiple testing?", include: ["Explicar error tipo I y FWER.", "Usar la idea 1 − (1 − α)^n.", "Mostrar por qué miles de tests crean falsos positivos.", "Mencionar Bonferroni y por qué puede ser demasiado estricto."], trap: "No interpretes p ≤ 0.05 gen por gen como seguro cuando se testean miles de genes.", answer: "La corrección por multiple testing es necesaria porque cada test tiene probabilidad α de error tipo I. Cuando se testean miles de genes, la probabilidad de al menos un falso positivo aumenta mucho: FWER = 1 − (1 − α)^n. Por eso, usar p ≤ 0.05 para cada gen de forma independiente produciría muchos falsos descubrimientos. Bonferroni controla FWER dividiendo α entre el número de tests, pero en transcriptómica puede ser demasiado estricto porque m es enorme y el cutoff puede volverse tan pequeño que ningún gen quede significativo." } }
      ], lab: "fwer" },
      { title: "5. FDR y Benjamini–Hochberg: corrección más útil en ómicas", intro: "Como Bonferroni puede ser demasiado duro para miles de genes, la profesora introduce FDR y Benjamini–Hochberg como la solución más común para transcriptómica y metilación.", slides: [
        { img: "fdrExpected", title: "Falsos positivos esperados a varios thresholds", body: "La tabla compara falsos positivos esperados con genes observados significativos bajo distintos α." },
        { img: "fdrFormula", title: "FDR = falsos positivos esperados / genes observados", body: "FDR estima la proporción de falsos descubrimientos dentro de los resultados seleccionados." },
        { img: "fdrSteps", title: "Lógica FDR en cuatro pasos", body: "Elegir thresholds, contar genes significativos, estimar falsos positivos esperados, elegir una tasa aceptable y corregir p-values." },
        { img: "bhOverview", title: "BH ordena p-values y aplica umbral por rango", body: "Los p-values se ordenan de menor a mayor; cada rango recibe un critical value (i/m)q." },
        { img: "bhCritical", title: "El cutoff crítico de BH", body: "Se retiene el p-value más grande que cumple p(i) ≤ (i/m)q; los genes por debajo de ese rango se consideran significativos.", emphasis: "Una estudiante preguntó por la regla de parada; la profesora aclaró que cuando se viola el threshold de BH, los p-values mayores restantes no se consideran significativos.", exam: { q: "Pregunta posible: explica FDR y Benjamini–Hochberg.", include: ["Definir FDR como proporción esperada de falsos positivos entre positivos declarados.", "BH ordena p-values y asigna thresholds (i/m)q.", "Se busca el mayor p-value que cumple p(i) ≤ (i/m)q.", "Es más común que Bonferroni para datasets ómicos grandes."], trap: "No confundas FWER con FDR. Bonferroni controla la probabilidad de cualquier falso positivo; FDR controla la proporción de falsos descubrimientos entre resultados seleccionados.", answer: "FDR es la proporción esperada de falsos descubrimientos entre los genes llamados significativos. Benjamini–Hochberg controla FDR ordenando los p-values de menor a mayor y asignando a cada uno un umbral (i/m)q, donde i es el rango, m es el número de tests y q es el FDR elegido. El mayor p-value que aún es menor o igual que su umbral BH define el cutoff. Esto se usa mucho en transcriptómica y metilación porque Bonferroni suele ser demasiado estricto cuando se realizan miles de tests." } }
      ], lab: "bh" },
      { title: "6. De listas a biología: gene-set enrichment analysis", intro: "El objetivo final no es solo una lista de genes up/down. GSEA ayuda a responder qué pathways, GO terms o categorías KEGG/Reactome están sobrerrepresentadas.", slides: [
        { img: "degRules", title: "Reglas para identificar genes diferencialmente expresados", body: "Partir de datos normalizados, definir pregunta y diseño, elegir test correcto, corregir multiple testing e interpretar listas up/down." },
        { img: "gseaIntro", title: "GSEA parte de listas de genes", body: "GSEA o functional enrichment pregunta si clases biológicas están sobrerrepresentadas en un conjunto grande de genes modificados." },
        { img: "gseaDefinition", title: "Gene sets definidos se comparan entre estados", body: "La definición de GSEA enfatiza diferencias concordantes y estadísticamente significativas entre estados biológicos." },
        { img: "gseaOutputs", title: "Outputs típicos: GO, KEGG, Reactome", body: "Puede devolver apoptosis, T-cell activation, MAPK signaling, oxidative phosphorylation y dirección up/down." },
        { img: "nesDefinition", title: "NES normaliza el enrichment", body: "NES corrige el enrichment score por tamaño del gene set y variabilidad entre permutaciones." },
        { img: "nesFdr", title: "NES + FDR ordenan la interpretación", body: "La profesora dice que los biólogos suelen mirar los top terms con NES alto y FDR bajo para construir la interpretación.", emphasis: "Cierra remarcando que la lista de genes sola significa poco; la interpretación biológica surge al conectarla con pathways y funciones.", exam: { q: "Pregunta posible: ¿por qué usar GSEA tras differential expression?", include: ["Normalmente terminas con listas largas de genes up/down.", "GSEA mapea esas listas a gene sets GO/KEGG/Reactome.", "Permutaciones/estadística interna evalúan si el enriquecimiento es mayor al azar.", "NES y FDR ayudan a priorizar resultados de pathway."], trap: "No presentes GSEA como un test para un solo gen. Interpreta conjuntos/pathways a partir de una lista de genes.", answer: "Después del análisis de expresión diferencial, el resultado suele ser una lista larga de genes up- y down-regulated. Esa lista es difícil de interpretar gen por gen. GSEA o functional enrichment analysis mapea la lista a categorías biológicas predefinidas como GO, KEGG o Reactome. Evalúa si los genes de una vía están sobrerrepresentados o cambian de manera concordante más de lo esperado por azar, usando a menudo permutaciones. La salida se interpreta con métricas como NES y FDR, de modo que la historia biológica final se centra en pathways y funciones, no en genes aislados." } }
      ], lab: "gsea" }
    ]
  },
  fa: { sections: [] }
};
COPY.fa.sections = COPY.en.sections.map((section) => ({ ...section, intro: section.intro, title: section.title }));

const LAB_COPY = {
  en: {
    h0: "Null hypothesis", pSoftware: "Auto p-value (approx.)", alpha: "Alpha decision", reject: "Reject H0", retain: "Do not reject H0", reset: "Reset example", group: "Group", labWarning: "This mini-lab calculates an approximate p-value in-browser. For real work, confirm exact p-values, assumptions and diagnostics in R/software.",
    bootstrap: { title: "Bootstrap p-value mini-lab", intro: "Keep the preloaded result or change the number of bootstrap replicates and extreme statistics.", reps: "Bootstrap replicates", extreme: "Replicates as or more extreme than observed", observed: "Observed statistic", h0: "H0: the observed group difference could be produced by random reshuffling under the null." },
    anova: { title: "Editable one-way ANOVA walkthrough", intro: "Use three or more groups. The lab calculates group means, grand mean, SSB, SSW, MS, F and an approximate p-value automatically.", h0: "H0: all group means are equal.", groups: ["Normal / wild type", "Mutant", "Double mutant"] },
    kruskal: { title: "Editable Kruskal–Wallis walkthrough", intro: "Use three or more groups. The lab pools all values, assigns ranks with averaged ties, sums ranks by group and calculates H.", h0: "H0: the medians/rank distributions of all groups are equal.", groups: ["Control", "Treatment 1", "Treatment 2"] },
    fwer: { title: "FWER and Bonferroni mini-lab", intro: "Change alpha and number of tests to see why thousands of genes make p ≤ 0.05 unsafe.", tests: "Number of tests", bonferroni: "Bonferroni threshold", fwer: "FWER", h0: "Family of H0 tests: each gene has no true differential expression unless evidence survives correction." },
    fdr: { title: "FDR expectation mini-lab", intro: "Estimate expected false positives and FDR from a chosen threshold, total genes and observed significant genes.", total: "Total tests/genes", observed: "Observed genes under threshold", expected: "Expected false positives", fdr: "FDR" },
    bh: { title: "Benjamini–Hochberg editable table", intro: "Paste p-values, choose q, and find the largest p-value satisfying p(i) ≤ (i/m)q.", pvalues: "P-values", q: "Chosen FDR q", cutoff: "BH cutoff", significant: "Significant p-values" },
    gsea: { title: "GSEA interpretation sorter", intro: "Select what each output tells you. The goal is to translate a long gene list into a biological interpretation.", items: ["NES", "FDR", "GO term", "KEGG/Reactome", "Permutation"], answers: { NES: "Normalized enrichment strength, adjusted for set size and permutations.", FDR: "Expected false-discovery proportion for the enriched term.", "GO term": "Functional category such as apoptosis or T-cell activation.", "KEGG/Reactome": "Pathway-level interpretation such as MAPK signaling or oxidative phosphorylation.", Permutation: "Internal reshuffling used to test whether enrichment is stronger than expected by chance." } }
  },
  es: {
    h0: "Hipótesis nula", pSoftware: "p-value automático (aprox.)", alpha: "Decisión por alpha", reject: "Rechazar H0", retain: "No rechazar H0", reset: "Restaurar ejemplo", group: "Grupo", labWarning: "Este mini-lab calcula un p-value aproximado en el navegador. En un análisis real, confirma p-values exactos, supuestos y diagnósticos en R/software.",
    bootstrap: { title: "Mini-lab de p-value bootstrap", intro: "Mantén el resultado precargado o cambia el número de réplicas bootstrap y estadísticas extremas.", reps: "Réplicas bootstrap", extreme: "Réplicas tan extremas o más que la observada", observed: "Estadístico observado", h0: "H0: la diferencia observada entre grupos podría producirse por remezcla aleatoria bajo la nula." },
    anova: { title: "Walkthrough editable de one-way ANOVA", intro: "Usa tres o más grupos. El lab calcula medias, grand mean, SSB, SSW, MS, F y un p-value aproximado automáticamente.", h0: "H0: todas las medias de grupo son iguales.", groups: ["Normal / wild type", "Mutant", "Double mutant"] },
    kruskal: { title: "Walkthrough editable de Kruskal–Wallis", intro: "Usa tres o más grupos. El lab junta valores, asigna rangos con empates promediados, suma rangos por grupo y calcula H.", h0: "H0: las medianas/distribuciones de rangos de todos los grupos son iguales.", groups: ["Control", "Treatment 1", "Treatment 2"] },
    fwer: { title: "Mini-lab de FWER y Bonferroni", intro: "Cambia alpha y número de tests para ver por qué miles de genes vuelven inseguro p ≤ 0.05.", tests: "Número de tests", bonferroni: "Threshold Bonferroni", fwer: "FWER", h0: "Familia de H0: cada gen no tiene expresión diferencial real salvo que la evidencia sobreviva la corrección." },
    fdr: { title: "Mini-lab de FDR esperado", intro: "Estima falsos positivos esperados y FDR a partir de threshold, total de genes y genes observados significativos.", total: "Tests/genes totales", observed: "Genes observados bajo threshold", expected: "Falsos positivos esperados", fdr: "FDR" },
    bh: { title: "Tabla editable de Benjamini–Hochberg", intro: "Pega p-values, elige q y encuentra el p-value más grande que cumple p(i) ≤ (i/m)q.", pvalues: "P-values", q: "FDR q elegido", cutoff: "Cutoff BH", significant: "P-values significativos" },
    gsea: { title: "Sorter de interpretación GSEA", intro: "Selecciona qué indica cada output. El objetivo es convertir una lista larga de genes en interpretación biológica.", items: ["NES", "FDR", "GO term", "KEGG/Reactome", "Permutation"], answers: { NES: "Fuerza de enriquecimiento normalizada por tamaño del set y permutaciones.", FDR: "Proporción esperada de falsos descubrimientos para el término enriquecido.", "GO term": "Categoría funcional como apoptosis o T-cell activation.", "KEGG/Reactome": "Interpretación de pathway como MAPK signaling u oxidative phosphorylation.", Permutation: "Remezcla interna para probar si el enriquecimiento supera lo esperado por azar." } }
  },
  fa: {}
};
LAB_COPY.fa = LAB_COPY.en;

const EXAM_BANK = {
  en: [
    { q: "What is the coefficient of variability? When is it used, why is it used, and what does it mean?", a: "The coefficient of variability is a normalized measure of dispersion, usually CV = standard deviation / mean, often expressed as a percentage. It is used when comparing variability between measurements with different scales or means, for example technical replicates or biological samples. A low CV suggests more reproducible measurements; a high CV means larger variability relative to the mean. In this course, it helps distinguish technical variability from biological variability and judge whether data are reliable enough for interpretation." },
    { q: "What is an MA-plot? Why is it used and what is its goal?", a: "An MA-plot represents M, the log2 ratio or difference between conditions, against A, the average signal intensity. It is used after array measurement and normalization to see whether ratios depend on intensity. A good normalized dataset should show points distributed around M = 0 without a strong intensity-dependent trend. It helps detect dye bias, array effects and normalization problems before calling genes differentially expressed." },
    { q: "Describe the characteristics of competitive arrays.", a: "Competitive arrays are two-colour arrays where two biological samples are labelled separately, often with Cy3 and Cy5, and hybridized on the same slide. The readout is based on the ratio between the two colour channels. Their advantage is direct comparison on the same array, but they suffer from dye bias, intensity-dependent effects and technical variability. Therefore, intra-array normalization, dye swap or self-self controls, background correction and image QC are essential." },
    { q: "Describe the characteristics of noncompetitive arrays.", a: "Noncompetitive arrays are one-colour platforms such as Affymetrix GeneChip, where one sample is hybridized on one chip and comparisons occur across chips. They avoid Cy3/Cy5 competition and dye bias, but they require careful among-array normalization because each sample is measured on a different array. The workflow includes target preparation, hybridization, scanning, DAT/CEL/CDF mapping, QC, background correction, quantile normalization and summarization, often through RMA." },
    { q: "Explain Illumina BeadChip methylation chemistry and the trick used to measure methylated or unmethylated cytosines.", a: "Illumina methylation arrays exploit bisulfite conversion. Unmethylated cytosine is converted to uracil and then read as thymine after PCR, whereas methylated cytosine remains cytosine at the sequence level. The array therefore converts methylation into a C/T genotyping-like problem at known CpG sites. Infinium I uses two bead/probe types for methylated and unmethylated states, while Infinium II uses one bead/probe and two-colour single-base extension. The beta value summarizes methylated signal relative to total methylated plus unmethylated signal." },
    { q: "Explain normalization procedures in competitive and noncompetitive arrays.", a: "In competitive arrays, normalization must correct differences between Cy3 and Cy5 on the same slide, so intra-array normalization is essential, often inspected with MA-plots and supported by dye swap/self-self controls. In noncompetitive arrays, the main issue is comparability across different chips, so among-array normalization is essential. In Affymetrix, RMA includes background correction, quantile normalization and summarization to make probe-set expression values comparable across chips." },
    { q: "When and why do you apply a specific statistical test in differential expression analysis?", a: "The statistical test is chosen from the biological question and experimental design. For two paired/dependent measurements such as before and after treatment, use paired t-test if differences are normal or Wilcoxon signed-rank if not. For two independent groups, use unpaired/Welch t-test if parametric, or Mann–Whitney if non-parametric. For more than two groups, use ANOVA if parametric with similar variance, or Kruskal–Wallis if non-parametric. After thousands of genes, correct p-values for multiple testing, often with FDR/BH." },
    { q: "When and why do you apply paired/unpaired Student, Wilcoxon signed-rank or Mann–Whitney?", a: "A paired Student t-test is used for two dependent measurements from the same subjects or matched samples when the distribution of differences is approximately normal. An unpaired Student or Welch test is used for two independent groups, with Welch preferred when variances or sample sizes differ. Wilcoxon signed-rank is the non-parametric paired alternative and works on ranked paired differences. Mann–Whitney U is the non-parametric unpaired alternative and compares rank distributions between independent groups." }
  ],
  es: [
    { q: "¿Qué es el coeficiente de variabilidad? ¿Cuándo se usa, por qué se usa y qué significa?", a: "El coeficiente de variabilidad es una medida normalizada de dispersión, normalmente CV = desviación estándar / media, a menudo expresada en porcentaje. Se usa para comparar variabilidad entre mediciones con medias o escalas distintas, por ejemplo réplicas técnicas o muestras biológicas. Un CV bajo sugiere mediciones más reproducibles; un CV alto indica mayor variabilidad relativa a la media. En esta materia ayuda a distinguir variabilidad técnica de biológica y a juzgar si los datos son fiables para interpretar." },
    { q: "¿Qué es un MA-plot? ¿Por qué se usa y cuál es su objetivo?", a: "Un MA-plot representa M, el log2 ratio o diferencia entre condiciones, contra A, la intensidad media de señal. Se usa después de medir y normalizar arrays para ver si los ratios dependen de la intensidad. Un dataset bien normalizado debería mostrar puntos alrededor de M = 0 sin una tendencia fuerte dependiente de intensidad. Sirve para detectar dye bias, efectos de array y problemas de normalización antes de llamar genes diferencialmente expresados." },
    { q: "Describe las características de los competitive arrays.", a: "Los competitive arrays son arrays two-colour donde dos muestras biológicas se etiquetan por separado, típicamente con Cy3 y Cy5, y se hibridan en el mismo slide. La lectura se basa en el ratio entre canales. Su ventaja es la comparación directa en el mismo array, pero sufren dye bias, efectos dependientes de intensidad y variabilidad técnica. Por eso son esenciales la normalización intra-array, dye swap o self-self controls, background correction y QC de imagen." },
    { q: "Describe las características de los noncompetitive arrays.", a: "Los noncompetitive arrays son plataformas one-colour como Affymetrix GeneChip, donde una muestra se hibrida en un chip y la comparación ocurre entre chips. Evitan la competencia Cy3/Cy5 y el dye bias, pero requieren normalización entre arrays porque cada muestra se mide en un chip distinto. El workflow incluye preparación de target, hibridación, escaneo, archivos DAT/CEL/CDF, QC, background correction, quantile normalization y summarization, a menudo con RMA." },
    { q: "Explica la química de Illumina BeadChip de metilación y el truco para medir citosinas metiladas/no metiladas.", a: "Los arrays de metilación de Illumina explotan la conversión con bisulfito. La citosina no metilada se convierte en uracilo y luego se lee como timina tras PCR, mientras que la citosina metilada permanece como citosina a nivel de secuencia. Así, la metilación se convierte en un problema tipo genotyping C/T en CpGs conocidos. Infinium I usa dos tipos de bead/probe para estados metilado y no metilado; Infinium II usa un bead/probe y extensión de una base con dos colores. El beta value resume la señal metilada respecto a la señal total metilada + no metilada." },
    { q: "Explica los procedimientos de normalización en competitive y noncompetitive arrays.", a: "En competitive arrays, la normalización corrige diferencias Cy3/Cy5 dentro del mismo slide, por lo que la normalización intra-array es esencial y se evalúa con MA-plots, dye swap o self-self controls. En noncompetitive arrays, el problema principal es la comparabilidad entre chips, así que la normalización among-array es esencial. En Affymetrix, RMA incluye background correction, quantile normalization y summarization para obtener valores comparables de expresión por probe set." },
    { q: "¿Cuándo y por qué se aplica un test estadístico específico en análisis de expresión diferencial?", a: "El test se elige a partir de la pregunta biológica y el diseño experimental. Para dos mediciones pareadas/dependientes, como antes y después de tratamiento, usa paired t-test si las diferencias son normales o Wilcoxon signed-rank si no lo son. Para dos grupos independientes, usa unpaired/Welch t-test si son paramétricos, o Mann–Whitney si no son paramétricos. Para más de dos grupos, usa ANOVA si los datos son paramétricos y con varianza similar, o Kruskal–Wallis si no lo son. Si hay miles de genes, corrige p-values por multiple testing, usualmente con FDR/BH." },
    { q: "¿Cuándo y por qué aplicar Student paired/unpaired, Wilcoxon signed-rank o Mann–Whitney?", a: "El paired Student t-test se usa para dos mediciones dependientes del mismo sujeto o muestras pareadas cuando la distribución de las diferencias es aproximadamente normal. El unpaired Student o Welch se usa para dos grupos independientes; Welch es preferible cuando las varianzas o tamaños muestrales difieren. Wilcoxon signed-rank es la alternativa no paramétrica pareada y trabaja con rangos de diferencias. Mann–Whitney U es la alternativa no paramétrica no pareada y compara distribuciones de rangos entre grupos independientes." }
  ],
  fa: []
};
EXAM_BANK.fa = EXAM_BANK.en;

function parseNumbers(text) {
  return String(text || "").split(/[\s,;]+/).map(Number).filter((x) => Number.isFinite(x));
}
function mean(arr) { return arr.reduce((a, b) => a + b, 0) / arr.length; }
function variance(arr) { const m = mean(arr); return arr.reduce((a, b) => a + (b - m) ** 2, 0) / Math.max(1, arr.length - 1); }
function rankValues(values) {
  const sorted = values.map((v, i) => ({ v, i })).sort((a, b) => a.v - b.v);
  const ranks = Array(values.length).fill(0);
  let i = 0;
  while (i < sorted.length) {
    let j = i + 1;
    while (j < sorted.length && sorted[j].v === sorted[i].v) j += 1;
    const avg = (i + 1 + j) / 2;
    for (let k = i; k < j; k++) ranks[sorted[k].i] = avg;
    i = j;
  }
  return ranks;
}
function fmt(x, digits = 3) { return Number.isFinite(x) ? x.toFixed(digits).replace(/\.0+$/, "") : "—"; }

function alphaRows(p, lab) {
  return [0.05, 0.01, 0.001].map((alpha) => ({ alpha, decision: p <= alpha ? lab.reject : lab.retain, confidence: `${fmt((1 - alpha) * 100, 1)}%` }));
}

function Navigation({ ui, isDone, toggle, position = "top" }) { return <nav className={`${position === "bottom" ? "mt-10" : "mb-6"} rounded-[2rem] border border-stone-200 bg-white/85 p-3 shadow-sm`} aria-label="Lesson navigation"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><a href="#/lesson/m1-deg-i" className="rounded-full border border-stone-200 bg-stone-50 px-4 py-2 text-sm font-black text-stone-700 transition hover:-translate-y-0.5 hover:bg-white hover:shadow-md">← {ui.previous}: {ui.previousTitle}</a><div className="flex flex-col items-stretch gap-2 sm:flex-row sm:items-center sm:justify-center"><a href="#/" className="rounded-full border border-stone-200 bg-white px-4 py-2 text-center text-xs font-black uppercase tracking-[0.2em] text-stone-500 transition hover:bg-stone-50">{ui.current} · {ui.dashboard}</a><button onClick={toggle} className={`rounded-full px-4 py-2 text-sm font-black shadow-sm transition hover:-translate-y-0.5 ${isDone ? "bg-emerald-600 text-white" : "bg-stone-950 text-white"}`}>{isDone ? ui.done : ui.mark}</button></div><a href="#/" className="rounded-full bg-stone-950 px-4 py-2 text-sm font-black text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-red-700 hover:shadow-md">{ui.next}: {ui.nextTitle} →</a></div></nav>; }
function HeroEyebrow({ children }) { return <div className="inline-flex rounded-full border border-red-200 bg-red-50 px-4 py-2 text-xs font-black uppercase tracking-[0.22em] text-red-700">{children}</div>; }
function Pill({ children, tone = "stone" }) { const cls = tone === "red" ? "border-red-200 bg-red-50 text-red-700" : "border-stone-200 bg-white/80 text-stone-700"; return <span className={`rounded-full border px-3 py-1 text-xs font-black uppercase tracking-[0.16em] ${cls}`}>{children}</span>; }
function StatCard({ label, value, tone = "stone" }) { return <div className={`rounded-2xl border p-4 ${tone === "red" ? "border-red-200 bg-red-50" : "border-stone-200 bg-stone-50"}`}><div className="text-xs font-black uppercase tracking-[0.2em] text-stone-500">{label}</div><div className="mt-2 text-2xl font-black text-stone-950">{value}</div></div>; }
function ResourceLinks({ ui }) { const linkBase = "rounded-2xl border px-4 py-3 text-sm font-black transition hover:-translate-y-0.5 hover:shadow-sm"; return <div className="mt-4 rounded-3xl border border-stone-200 bg-stone-50 p-4"><div className="mb-3 text-xs font-black uppercase tracking-[0.18em] text-stone-500">{ui.resources}</div><div className="grid gap-2 sm:grid-cols-3"><a href={SLIDES_URL} target="_blank" rel="noreferrer" className={`${linkBase} border-red-200 bg-red-50 text-red-800 hover:bg-white`}>{ui.slides}</a><a href={TRANSCRIPT_URL} target="_blank" rel="noreferrer" className={`${linkBase} border-stone-200 bg-white text-stone-800 hover:bg-stone-50`}>{ui.transcript}</a><a href={RECORDING_URL} target="_blank" rel="noreferrer" className={`${linkBase} border-stone-800 bg-stone-950 text-white hover:bg-red-700`}>{ui.recording}</a></div></div>; }
function SectionHeader({ eyebrow, title, children }) { return <div className="mb-6"><div className="text-xs font-black uppercase tracking-[0.22em] text-red-700">{eyebrow}</div><h2 className="mt-2 text-3xl font-black tracking-tight text-stone-950 md:text-4xl">{title}</h2>{children ? <p className="mt-3 max-w-4xl text-base font-semibold leading-7 text-stone-600">{children}</p> : null}</div>; }
function NoteBox({ ui, type, children }) { const isExam = type === "exam"; return <div className={`mt-4 rounded-2xl border p-4 ${isExam ? "border-red-200 bg-red-50" : "border-amber-200 bg-amber-50"}`}><div className={`text-xs font-black uppercase tracking-[0.2em] ${isExam ? "text-red-700" : "text-amber-800"}`}>{isExam ? ui.exam : ui.professor}</div><div className="mt-2 text-sm font-bold leading-6 text-stone-800">{children}</div></div>; }
function ExamWatch({ ui, data }) { if (!data) return null; const model = data.model || data.answer; return <details className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4"><summary className="cursor-pointer text-sm font-black text-red-800">{ui.exam}: {data.q}</summary><div className="mt-4 rounded-2xl border border-red-100 bg-white p-4"><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">{ui.include}</div><ul className="mt-3 space-y-2 text-sm font-semibold leading-6 text-stone-700">{data.include.map((x) => <li key={x}>• {x}</li>)}</ul><div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="text-xs font-black uppercase tracking-[0.18em] text-amber-800">{ui.trap}</div><p className="mt-2 text-sm font-bold leading-6 text-amber-950">{data.trap}</p></div><div className="mt-4 rounded-2xl border border-stone-200 bg-stone-50 p-4"><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">{ui.model}</div><p className="mt-2 text-sm font-bold leading-7 text-stone-800">{model}</p></div></div></details>; }
function SlideCard({ ui, item, openZoom, spanFull }) { const figure = IMG[item.img]; if (!figure) return null; return <article className={`overflow-hidden rounded-[2rem] border border-stone-200 bg-stone-50 shadow-sm ${spanFull ? "md:col-span-2" : ""}`}><button onClick={() => openZoom({ ...figure, title: item.title })} className="group block w-full border-b border-stone-200 bg-white p-3 text-left"><div className={`${spanFull ? "aspect-[16/9]" : "aspect-[4/3]"} overflow-hidden rounded-2xl bg-white`}><img src={figure.src} alt={item.title} loading="lazy" className="h-full w-full object-contain transition duration-300 group-hover:scale-[1.02]" /></div></button><div className="p-5"><div className="flex flex-wrap items-center gap-2"><Pill tone="red">{ui.slide} {figure.slide}</Pill><span className="text-xs font-black uppercase tracking-[0.16em] text-stone-400">{ui.zoom}</span></div><h3 className="mt-3 text-xl font-black text-stone-950">{item.title}</h3><p className="mt-2 text-sm font-semibold leading-6 text-stone-600">{item.body}</p>{(item.professor || item.emphasis) ? <NoteBox ui={ui}>{item.professor || item.emphasis}</NoteBox> : null}<ExamWatch ui={ui} data={item.exam}/></div></article>; }
function SlideGrid({ ui, slides, openZoom }) { return <div className="grid gap-5 md:grid-cols-2">{slides.map((item, idx) => <SlideCard key={`${item.img}-${idx}`} ui={ui} item={item} openZoom={openZoom} spanFull={slides.length % 2 === 1 && idx === slides.length - 1}/>)}</div>; }
function ZoomModal({ ui, zoom, setZoom }) { if (!zoom) return null; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-stone-950/80 p-4" onClick={() => setZoom(null)}><div className="max-h-[92vh] w-[min(1100px,96vw)] overflow-auto rounded-[2rem] bg-white p-4 shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="mb-3 flex items-center justify-between gap-3"><div><Pill tone="red">{ui.slide} {zoom.slide}</Pill><h3 className="mt-2 text-xl font-black text-stone-950">{zoom.title}</h3></div><button onClick={() => setZoom(null)} className="rounded-full bg-stone-950 px-4 py-2 text-sm font-black text-white">{ui.close}</button></div><img src={zoom.src} alt={zoom.title} className="max-h-[78vh] w-full rounded-2xl object-contain" /></div></div>; }
function InteractiveShell({ title, intro, children }) { return <div className="mt-6 rounded-[2rem] border border-stone-200 bg-stone-50 p-5"><h3 className="text-2xl font-black text-stone-950">{title}</h3><p className="mt-2 text-sm font-semibold leading-6 text-stone-600">{intro}</p><div className="mt-5">{children}</div></div>; }

const ALPHA_LEVELS = [0.05, 0.01, 0.001];
function labLang(lab) { return String(lab.h0 || "").toLowerCase().includes("hip") ? "es" : "en"; }
function confidenceLabel(alpha) { return `${fmt((1 - alpha) * 100, alpha === 0.001 ? 1 : 0)}%`; }
function labLabels(lab) {
  const es = labLang(lab) === "es";
  return es ? {
    h0: "Hipótesis nula (H0)", decision: "Decisión contra thresholds fijos", pValue: "p-value usado para decidir", approx: "aprox.", exact: "software/exacto", alpha: "alpha", confidence: "confianza", noP: "p-value no disponible", rejectMeaning: "Significativo: hay evidencia contra H0.", retainMeaning: "No significativo: no hay evidencia suficiente para rechazar H0.", warning: "En análisis real, confirma el p-value exacto y supuestos con R/software.", steps: "Paso a paso", reset: "Restaurar ejemplo", input: "Datos editables"
  } : {
    h0: "Null hypothesis (H0)", decision: "Decision against fixed alpha thresholds", pValue: "p-value used for decision", approx: "approx.", exact: "software/exact", alpha: "alpha", confidence: "confidence", noP: "p-value unavailable", rejectMeaning: "Significant: there is evidence against H0.", retainMeaning: "Not significant: there is not enough evidence to reject H0.", warning: "For real analysis, confirm the exact p-value and assumptions with R/software.", steps: "Step by step", reset: "Reset example", input: "Editable data"
  };
}

function clamp01(x) { return Number.isFinite(x) ? Math.min(1, Math.max(0, x)) : NaN; }
function logGamma(z) {
  const cof = [76.18009172947146, -86.50532032941677, 24.01409824083091, -1.231739572450155, 0.001208650973866179, -0.000005395239384953];
  let x = z - 1;
  let tmp = x + 5.5;
  tmp -= (x + 0.5) * Math.log(tmp);
  let ser = 1.000000000190015;
  for (const c of cof) { x += 1; ser += c / x; }
  return -tmp + Math.log(2.5066282746310005 * ser);
}
function betaContinuedFraction(a, b, x) {
  const maxIter = 100;
  const eps = 3e-7;
  const fpMin = 1e-30;
  const qab = a + b;
  const qap = a + 1;
  const qam = a - 1;
  let c = 1;
  let d = 1 - (qab * x) / qap;
  if (Math.abs(d) < fpMin) d = fpMin;
  d = 1 / d;
  let h = d;
  for (let m = 1; m <= maxIter; m += 1) {
    const m2 = 2 * m;
    let aa = (m * (b - m) * x) / ((qam + m2) * (a + m2));
    d = 1 + aa * d;
    if (Math.abs(d) < fpMin) d = fpMin;
    c = 1 + aa / c;
    if (Math.abs(c) < fpMin) c = fpMin;
    d = 1 / d;
    h *= d * c;
    aa = -((a + m) * (qab + m) * x) / ((a + m2) * (qap + m2));
    d = 1 + aa * d;
    if (Math.abs(d) < fpMin) d = fpMin;
    c = 1 + aa / c;
    if (Math.abs(c) < fpMin) c = fpMin;
    d = 1 / d;
    const del = d * c;
    h *= del;
    if (Math.abs(del - 1) < eps) break;
  }
  return h;
}
function regularizedBeta(x, a, b) {
  if (!Number.isFinite(x) || !Number.isFinite(a) || !Number.isFinite(b) || a <= 0 || b <= 0) return NaN;
  if (x <= 0) return 0;
  if (x >= 1) return 1;
  const bt = Math.exp(logGamma(a + b) - logGamma(a) - logGamma(b) + a * Math.log(x) + b * Math.log(1 - x));
  if (x < (a + 1) / (a + b + 2)) return clamp01((bt * betaContinuedFraction(a, b, x)) / a);
  return clamp01(1 - (bt * betaContinuedFraction(b, a, 1 - x)) / b);
}
function fSurvival(f, df1, df2) {
  if (!Number.isFinite(f) || f < 0 || df1 <= 0 || df2 <= 0) return NaN;
  const x = (df1 * f) / (df1 * f + df2);
  return clamp01(1 - regularizedBeta(x, df1 / 2, df2 / 2));
}
function gammaP(a, x) {
  if (!Number.isFinite(a) || !Number.isFinite(x) || a <= 0 || x < 0) return NaN;
  if (x === 0) return 0;
  const maxIter = 100;
  const eps = 3e-7;
  const fpMin = 1e-30;
  if (x < a + 1) {
    let ap = a;
    let sum = 1 / a;
    let del = sum;
    for (let n = 1; n <= maxIter; n += 1) {
      ap += 1;
      del *= x / ap;
      sum += del;
      if (Math.abs(del) < Math.abs(sum) * eps) break;
    }
    return clamp01(sum * Math.exp(-x + a * Math.log(x) - logGamma(a)));
  }
  let b = x + 1 - a;
  let c = 1 / fpMin;
  let d = 1 / Math.max(b, fpMin);
  let h = d;
  for (let i = 1; i <= maxIter; i += 1) {
    const an = -i * (i - a);
    b += 2;
    d = an * d + b;
    if (Math.abs(d) < fpMin) d = fpMin;
    c = b + an / c;
    if (Math.abs(c) < fpMin) c = fpMin;
    d = 1 / d;
    const del = d * c;
    h *= del;
    if (Math.abs(del - 1) < eps) break;
  }
  return clamp01(1 - Math.exp(-x + a * Math.log(x) - logGamma(a)) * h);
}
function chiSquareSurvival(x, df) {
  if (!Number.isFinite(x) || x < 0 || df <= 0) return NaN;
  return clamp01(1 - gammaP(df / 2, x / 2));
}

function ResultPill({ label, value, tone = "stone" }) { return <div className={`rounded-2xl border p-4 ${tone === "red" ? "border-red-200 bg-red-50" : "border-stone-200 bg-white"}`}><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">{label}</div><div className="mt-1 text-xl font-black text-stone-950">{value}</div></div>; }
function DataBox({ label, value, onChange, rows = 5 }) { return <label className="text-sm font-black text-stone-700">{label}<textarea value={value} rows={rows} onChange={(e) => onChange(e.target.value)} className="mt-2 min-h-[120px] w-full rounded-2xl border border-stone-200 bg-white px-4 py-3 font-mono text-sm leading-6 outline-none focus:border-red-300"/></label>; }
function NumberInput({ label, value, setValue, step = "1" }) { return <label className="text-sm font-black text-stone-700">{label}<input type="number" step={step} value={value} onChange={(e) => setValue(Number(e.target.value))} className="mt-2 w-full rounded-2xl border border-stone-200 bg-white px-4 py-3 font-black outline-none focus:border-red-300"/></label>; }
function StepsPanel({ lab, steps }) { const t = labLabels(lab); return <div className="rounded-2xl border border-stone-200 bg-white p-4"><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">{t.steps}</div><ol className="mt-3 space-y-2 text-sm font-bold leading-6 text-stone-700">{steps.map((step, i) => <li key={step} className="flex gap-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-stone-950 text-xs text-white">{i + 1}</span><span>{step}</span></li>)}</ol></div>; }
function DecisionPanel({ lab, h0, pValue, approximate = false, label }) { const t = labLabels(lab); const validP = Number.isFinite(pValue) && pValue >= 0 && pValue <= 1; return <div className="mt-4 rounded-[1.5rem] border border-stone-200 bg-white p-5"><div className="grid gap-4 lg:grid-cols-[0.9fr_1.1fr]"><div className="rounded-2xl bg-stone-50 p-4"><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">{t.h0}</div><p className="mt-2 text-sm font-bold leading-6 text-stone-800">{h0}</p><div className="mt-3 rounded-xl bg-white p-3 text-xs font-black text-stone-600">{label || t.pValue}: {validP ? `${fmt(pValue, 5)} (${approximate ? t.approx : t.exact})` : t.noP}</div></div><div><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">{t.decision}</div><div className="mt-3 grid gap-3 md:grid-cols-3">{ALPHA_LEVELS.map((alpha) => { const reject = validP && pValue <= alpha; return <div key={alpha} className={`rounded-2xl border p-4 ${reject ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50"}`}><div className="text-xs font-black uppercase tracking-[0.16em] text-stone-500">{t.alpha} = {alpha}</div><div className={`mt-1 text-lg font-black ${reject ? "text-emerald-800" : "text-amber-900"}`}>{reject ? lab.reject : lab.retain}</div><div className="mt-1 text-xs font-bold text-stone-600">{confidenceLabel(alpha)} {t.confidence}</div><p className="mt-2 text-xs font-semibold leading-5 text-stone-600">{reject ? t.rejectMeaning : t.retainMeaning}</p></div>; })}</div></div></div></div>; }
function GroupInputs({ labels, values, setValues, lab }) { return <div className="grid gap-4 md:grid-cols-3">{values.map((value, i) => <DataBox key={i} label={labels[i] || `${lab.group} ${i + 1}`} value={value} onChange={(next) => setValues(values.map((v, j) => j === i ? next : v))}/>)}</div>; }
function BootstrapLab({ lab }) { const [reps, setReps] = useState(1000000); const [extreme, setExtreme] = useState(9750); const [obs, setObs] = useState(3.1596); const p = Math.max(0, extreme) / Math.max(1, reps); const es = labLang(lab) === "es"; const steps = es ? ["Mantén el diseño original: dos grupos con sus tamaños de muestra.", "Remezcla los datos bajo H0 y repite el test muchas veces.", "Cuenta cuántas estadísticas bootstrap son tan extremas o más que la observada.", "Calcula p = eventos extremos / réplicas totales y compara con alpha."] : ["Keep the original design: two groups with their sample sizes.", "Reshuffle data under H0 and repeat the test many times.", "Count how many bootstrap statistics are as or more extreme than the observed one.", "Compute p = extreme events / total replicates and compare it with alpha."]; return <InteractiveShell title={lab.bootstrap.title} intro={lab.bootstrap.intro}><div className="grid gap-4 md:grid-cols-3"><NumberInput label={lab.bootstrap.reps} value={reps} setValue={setReps}/><NumberInput label={lab.bootstrap.extreme} value={extreme} setValue={setExtreme}/><NumberInput label={lab.bootstrap.observed} value={obs} setValue={setObs} step="0.0001"/></div><div className="mt-4 grid gap-3 md:grid-cols-3"><ResultPill label="p bootstrap" value={fmt(p, 5)} tone="red"/><ResultPill label="observed t" value={fmt(obs, 4)}/><ResultPill label="extreme / total" value={`${extreme}/${reps}`}/></div><DecisionPanel lab={lab} h0={lab.bootstrap.h0} pValue={p} label="bootstrap p-value"/><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_0.9fr]"><p className="rounded-2xl bg-stone-950 p-4 text-sm font-black leading-6 text-white">{p <= 0.01 ? (es ? "La estadística observada queda en el extremo de la distribución bootstrap: confirma que el resultado difícilmente se explica por azar." : "The observed statistic is at the edge of the bootstrap distribution: this confirms that chance alone is unlikely.") : (es ? "La estadística no queda suficientemente en el extremo: la señal no queda confirmada con este bootstrap." : "The statistic is not extreme enough: the signal is not confirmed by this bootstrap.")}</p><StepsPanel lab={lab} steps={steps}/></div><p className="mt-4 text-sm font-bold leading-6 text-stone-600">{lab.labWarning}</p></InteractiveShell>; }
function AnovaLab({ lab }) {
  const defaults = ["0.46, 0.30, 0.80, 1.51, 0.90", "-0.10, 0.49, 0.24, 0.06, 0.46", "-0.34, 0.56, 0.33"];
  const [values, setValues] = useState(defaults);
  const groups = values.map(parseNumbers).filter((g) => g.length > 0);
  const all = groups.flat();
  const grand = all.length ? mean(all) : 0;
  const ssb = groups.reduce((acc, g) => acc + g.length * (mean(g) - grand) ** 2, 0);
  const ssw = groups.reduce((acc, g) => acc + g.reduce((a, x) => a + (x - mean(g)) ** 2, 0), 0);
  const dfb = Math.max(0, groups.length - 1);
  const dfw = Math.max(0, all.length - groups.length);
  const msb = dfb ? ssb / dfb : NaN;
  const msw = dfw ? ssw / dfw : NaN;
  const f = msb / msw;
  const p = fSurvival(f, dfb, dfw);
  const es = labLang(lab) === "es";
  const steps = es ? ["Calcula la media de cada grupo y la grand mean.", "Calcula SS between: cuánto se alejan las medias de grupo de la grand mean.", "Calcula SS within: cuánto varían los individuos dentro de cada grupo.", "Divide por los grados de libertad para obtener MSB y MSW.", "F = MSB/MSW; el lab calcula automáticamente un p-value aproximado con la distribución F.", "Compara ese p-value contra α = 0.05, 0.01 y 0.001."] : ["Compute each group mean and the grand mean.", "Compute SS between: how far group means are from the grand mean.", "Compute SS within: how much individuals vary inside each group.", "Divide by degrees of freedom to obtain MSB and MSW.", "F = MSB/MSW; the lab automatically computes an approximate p-value from the F distribution.", "Compare that p-value against α = 0.05, 0.01 and 0.001."];
  return <InteractiveShell title={lab.anova.title} intro={lab.anova.intro}><GroupInputs labels={lab.anova.groups} values={values} setValues={setValues} lab={lab}/><button onClick={() => setValues(defaults)} className="mt-3 rounded-full border border-stone-200 bg-white px-4 py-2 text-xs font-black text-stone-700">{lab.reset}</button><div className="mt-4 grid gap-3 md:grid-cols-5"><ResultPill label="SS between" value={fmt(ssb, 4)}/><ResultPill label="SS within" value={fmt(ssw, 4)}/><ResultPill label="df" value={`${dfb}, ${dfw}`}/><ResultPill label="F observed" value={fmt(f, 3)} tone="red"/><ResultPill label={lab.pSoftware} value={fmt(p, 4)} tone="red"/></div><DecisionPanel lab={lab} h0={lab.anova.h0} pValue={p}/><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_0.9fr]"><p className="rounded-2xl bg-stone-950 p-4 text-sm font-black leading-6 text-white">{p <= 0.05 ? (es ? "Resultado global significativo: ANOVA dice que al menos un grupo difiere, pero necesitas post-hoc para saber cuál." : "Global significant result: ANOVA says at least one group differs, but post-hoc testing is needed to identify which one.") : (es ? "Resultado no significativo en el ejemplo de la clase: F observado no supera el valor crítico y no se rechaza H0." : "Non-significant result in the class example: observed F does not exceed the critical value and H0 is not rejected.")}</p><StepsPanel lab={lab} steps={steps}/></div><p className="mt-4 text-sm font-bold leading-6 text-stone-600">{lab.labWarning}</p></InteractiveShell>;
}
function KruskalLab({ lab }) {
  const defaults = ["23, 41, 54, 66, 78", "45, 55, 60, 70, 72", "18, 30, 34, 40, 44"];
  const [values, setValues] = useState(defaults);
  const groups = values.map(parseNumbers).filter((g) => g.length > 0);
  const combined = groups.flat();
  const ranks = rankValues(combined);
  let offset = 0;
  const rankSums = groups.map((g) => { const sum = ranks.slice(offset, offset + g.length).reduce((a, b) => a + b, 0); offset += g.length; return sum; });
  const n = combined.length;
  const h = n ? (12 / (n * (n + 1))) * rankSums.reduce((acc, r, i) => acc + (r * r) / groups[i].length, 0) - 3 * (n + 1) : NaN;
  const df = Math.max(0, groups.length - 1);
  const p = chiSquareSurvival(h, df);
  const es = labLang(lab) === "es";
  const steps = es ? ["Junta los valores de todos los grupos.", "Ordénalos y asigna rangos; si hay empates, usa el rango promedio.", "Devuelve cada rango a su grupo original y suma rangos por grupo.", "Calcula H y el lab estima automáticamente el p-value con una distribución chi-square de k − 1 grados de libertad.", "Si H/p es significativo, usa post-hoc para identificar los pares que difieren."] : ["Pool values from all groups.", "Order them and assign ranks; use averaged ranks for ties.", "Return each rank to its original group and sum ranks by group.", "Compute H and the lab automatically estimates the p-value with a chi-square distribution using k − 1 degrees of freedom.", "If H/p is significant, use post-hoc testing to identify which pairs differ."];
  return <InteractiveShell title={lab.kruskal.title} intro={lab.kruskal.intro}><GroupInputs labels={lab.kruskal.groups} values={values} setValues={setValues} lab={lab}/><button onClick={() => setValues(defaults)} className="mt-3 rounded-full border border-stone-200 bg-white px-4 py-2 text-xs font-black text-stone-700">{lab.reset}</button><div className="mt-4 grid gap-3 md:grid-cols-5"><ResultPill label="N" value={n}/><ResultPill label="rank sums" value={rankSums.map((x) => fmt(x, 1)).join(" / ")}/><ResultPill label="df = k − 1" value={df}/><ResultPill label="H observed" value={fmt(h, 3)} tone="red"/><ResultPill label={lab.pSoftware} value={fmt(p, 4)} tone="red"/></div><DecisionPanel lab={lab} h0={lab.kruskal.h0} pValue={p}/><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_0.9fr]"><p className="rounded-2xl bg-stone-950 p-4 text-sm font-black leading-6 text-white">{p <= 0.05 ? (es ? "Como alternativa no paramétrica, Kruskal–Wallis detecta una diferencia global entre rangos/medianas, no el par exacto." : "As a non-parametric alternative, Kruskal–Wallis detects a global rank/median difference, not the exact pair.") : (es ? "El patrón de rangos no es suficientemente extremo para rechazar H0." : "The rank pattern is not extreme enough to reject H0.")}</p><StepsPanel lab={lab} steps={steps}/></div><p className="mt-4 text-sm font-bold leading-6 text-stone-600">{lab.labWarning}</p></InteractiveShell>;
}
function FwerLab({ lab }) { const [alpha, setAlpha] = useState(0.05); const [m, setM] = useState(6350); const fwer = 1 - Math.pow(1 - alpha, m); const bon = alpha / Math.max(1, m); const es = labLang(lab) === "es"; const steps = es ? ["Define alpha para un test individual.", "Multiplica el problema por m tests: genes, transcripts o CpGs.", "FWER = 1 − (1 − alpha)^m estima el riesgo de al menos un falso positivo.", "Bonferroni controla FWER usando alpha/m como cutoff nuevo."] : ["Set alpha for one individual test.", "Multiply the problem by m tests: genes, transcripts or CpGs.", "FWER = 1 − (1 − alpha)^m estimates the risk of at least one false positive.", "Bonferroni controls FWER using alpha/m as the new cutoff."]; return <InteractiveShell title={lab.fwer.title} intro={lab.fwer.intro}><div className="grid gap-4 md:grid-cols-2"><NumberInput label="α" value={alpha} setValue={setAlpha} step="0.001"/><NumberInput label={lab.fwer.tests} value={m} setValue={setM}/></div><div className="mt-4 grid gap-3 md:grid-cols-3"><ResultPill label={lab.fwer.fwer} value={`${fmt(fwer * 100, 2)}%`} tone="red"/><ResultPill label={lab.fwer.bonferroni} value={bon.toExponential(2)}/><ResultPill label="expected false positives" value={fmt(alpha * m, 2)}/></div><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_0.9fr]"><p className="rounded-2xl bg-stone-950 p-4 text-sm font-black leading-6 text-white">{es ? "La idea clave es que p ≤ 0.05 parece seguro para un gen, pero no para miles de genes: el riesgo familiar se dispara." : "The key idea is that p ≤ 0.05 may look safe for one gene, but not for thousands: family-wise risk explodes."}</p><StepsPanel lab={lab} steps={steps}/></div></InteractiveShell>; }
function FdrLab({ lab }) { const [alpha, setAlpha] = useState(0.001); const [total, setTotal] = useState(6350); const [obs, setObs] = useState(35); const expected = alpha * total; const fdr = obs ? (expected / obs) * 100 : NaN; const es = labLang(lab) === "es"; const steps = es ? ["Elige un threshold de p-value.", "Calcula falsos positivos esperados = total de tests × threshold.", "Cuenta cuántos genes observaste bajo ese threshold.", "FDR = esperados / observados × 100."] : ["Choose a p-value threshold.", "Compute expected false positives = total tests × threshold.", "Count how many genes were observed below that threshold.", "FDR = expected / observed × 100."]; return <InteractiveShell title={lab.fdr.title} intro={lab.fdr.intro}><div className="grid gap-4 md:grid-cols-3"><NumberInput label="threshold α" value={alpha} setValue={setAlpha} step="0.0001"/><NumberInput label={lab.fdr.total} value={total} setValue={setTotal}/><NumberInput label={lab.fdr.observed} value={obs} setValue={setObs}/></div><div className="mt-4 grid gap-3 md:grid-cols-2"><ResultPill label={lab.fdr.expected} value={fmt(expected, 3)}/><ResultPill label={lab.fdr.fdr} value={`${fmt(fdr, 2)}%`} tone="red"/></div><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_0.9fr]"><p className="rounded-2xl bg-stone-950 p-4 text-sm font-black leading-6 text-white">{es ? "FDR no intenta eliminar todos los falsos positivos; intenta controlar la proporción esperada dentro de la lista que decides reportar." : "FDR does not try to remove every false positive; it controls the expected proportion inside the list you report."}</p><StepsPanel lab={lab} steps={steps}/></div></InteractiveShell>; }
function BhLab({ lab }) { const [pvals, setPvals] = useState("0.001, 0.004, 0.006, 0.009, 0.015, 0.023, 0.045, 0.051, 0.078, 0.11"); const [q, setQ] = useState(0.05); const sorted = parseNumbers(pvals).filter((p) => p >= 0 && p <= 1).sort((a, b) => a - b); const m = sorted.length || 1; const rows = sorted.map((p, idx) => ({ p, rank: idx + 1, crit: ((idx + 1) / m) * q, pass: p <= ((idx + 1) / m) * q })); const passing = rows.filter((r) => r.pass); const cutoff = passing.length ? passing[passing.length - 1].p : NaN; const es = labLang(lab) === "es"; const steps = es ? ["Ordena todos los p-values de menor a mayor.", "Asigna un rango i a cada p-value.", "Calcula el threshold BH: (i/m)q.", "Busca el mayor p(i) que todavía cumple p(i) ≤ (i/m)q.", "Reporta como significativos los p-values hasta ese cutoff."] : ["Sort all p-values from smallest to largest.", "Assign rank i to each p-value.", "Compute the BH threshold: (i/m)q.", "Find the largest p(i) that still satisfies p(i) ≤ (i/m)q.", "Report p-values up to that cutoff as significant."]; return <InteractiveShell title={lab.bh.title} intro={lab.bh.intro}><div className="grid gap-4 md:grid-cols-[1.2fr_0.8fr]"><DataBox label={lab.bh.pvalues} value={pvals} onChange={setPvals} rows={4}/><NumberInput label={lab.bh.q} value={q} setValue={setQ} step="0.001"/></div><div className="mt-4 grid gap-3 md:grid-cols-2"><ResultPill label={lab.bh.cutoff} value={Number.isFinite(cutoff) ? fmt(cutoff, 4) : "none"} tone="red"/><ResultPill label={lab.bh.significant} value={passing.length}/></div><div className="mt-4 overflow-x-auto rounded-2xl border border-stone-200 bg-white"><table className="w-full min-w-[560px] text-left text-sm"><thead className="bg-stone-50 text-xs font-black uppercase tracking-[0.14em] text-stone-500"><tr><th className="p-3">rank</th><th className="p-3">p(i)</th><th className="p-3">(i/m)q</th><th className="p-3">decision</th></tr></thead><tbody>{rows.map((r) => <tr key={`${r.rank}-${r.p}`} className="border-t border-stone-100"><td className="p-3 font-bold">{r.rank}</td><td className="p-3 font-mono">{fmt(r.p, 4)}</td><td className="p-3 font-mono">{fmt(r.crit, 4)}</td><td className={`p-3 font-black ${r.pass ? "text-emerald-700" : "text-stone-500"}`}>{r.pass ? lab.reject : lab.retain}</td></tr>)}</tbody></table></div><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_0.9fr]"><p className="rounded-2xl bg-stone-950 p-4 text-sm font-black leading-6 text-white">{es ? "Regla de parada de la clase: cuando el threshold deja de cumplirse, los p-values mayores restantes no se consideran significativos." : "Class stopping rule: once the threshold is no longer satisfied, larger remaining p-values are not considered significant."}</p><StepsPanel lab={lab} steps={steps}/></div></InteractiveShell>; }
function GseaLab({ lab }) { const [selected, setSelected] = useState("NES"); return <InteractiveShell title={lab.gsea.title} intro={lab.gsea.intro}><div className="grid gap-4 md:grid-cols-[0.8fr_1.2fr]"><div className="grid gap-2">{lab.gsea.items.map((item) => <button key={item} onClick={() => setSelected(item)} className={`rounded-2xl border px-4 py-3 text-left text-sm font-black ${selected === item ? "border-red-200 bg-red-50 text-red-800" : "border-stone-200 bg-white text-stone-700"}`}>{item}</button>)}</div><div className="rounded-2xl bg-stone-950 p-6 text-white"><div className="text-xs font-black uppercase tracking-[0.18em] text-red-200">{selected}</div><p className="mt-3 text-xl font-black leading-8">{lab.gsea.answers[selected]}</p></div></div></InteractiveShell>; }
function renderLab(name, lab) { if (name === "bootstrap") return <BootstrapLab lab={lab}/>; if (name === "anova") return <AnovaLab lab={lab}/>; if (name === "kruskal") return <KruskalLab lab={lab}/>; if (name === "fwer") return <><FwerLab lab={lab}/><FdrLab lab={lab}/></>; if (name === "bh") return <BhLab lab={lab}/>; if (name === "gsea") return <GseaLab lab={lab}/>; return null; }
function Quiz({ ui }) { const items = [
  { q: "Bootstrap is mainly used here to…", options: ["replace normalization", "confirm whether an observed statistic is extreme under resampling", "avoid choosing a test"], answer: 1 },
  { q: "One-way ANOVA is appropriate when…", options: ["one variable has more than two groups and parametric assumptions are acceptable", "only two paired samples exist", "data must be ranked"], answer: 0 },
  { q: "Kruskal–Wallis is closest to…", options: ["a non-parametric extension of Mann–Whitney", "a dye-swap control", "a quantile normalization method"], answer: 0 },
  { q: "Bonferroni can be problematic in transcriptomics because…", options: ["it never corrects p-values", "it becomes extremely stringent with thousands of tests", "it ignores alpha"], answer: 1 },
  { q: "BH correction controls…", options: ["FDR", "raw intensity", "sample size"], answer: 0 },
  { q: "GSEA helps transform…", options: ["a gene list into pathway/function interpretation", "a DAT file into a CEL file", "Cy3 into Cy5"], answer: 0 }
]; const [answers, setAnswers] = useState({}); const score = items.reduce((acc, item, i) => acc + (answers[i] === item.answer ? 1 : 0), 0); return <section className="mt-10 rounded-[2rem] border border-stone-200 bg-white p-6 shadow-sm"><SectionHeader eyebrow={ui.checkpoint} title="Interactive quiz">Score: {score}/{items.length}</SectionHeader><div className="grid gap-4 md:grid-cols-2">{items.map((item, i) => <div key={item.q} className="rounded-2xl border border-stone-200 bg-stone-50 p-4"><p className="font-black text-stone-950">{i + 1}. {item.q}</p><div className="mt-3 grid gap-2">{item.options.map((option, j) => <button key={option} onClick={() => setAnswers({ ...answers, [i]: j })} className={`rounded-xl border px-3 py-2 text-left text-sm font-bold ${answers[i] === j ? (j === item.answer ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-red-300 bg-red-50 text-red-800") : "border-stone-200 bg-white text-stone-700"}`}>{option}</button>)}</div></div>)}</div></section>; }
function WrittenTrainer({ ui, lang }) { const questions = EXAM_BANK[lang] || EXAM_BANK.es; const [idx, setIdx] = useState(0); const [text, setText] = useState(""); const wc = text.trim() ? text.trim().split(/\s+/).length : 0; const current = questions[idx]; return <section className="mt-10 rounded-[2rem] border border-stone-200 bg-white p-6 shadow-sm"><SectionHeader eyebrow={ui.exam} title="Written exam trainer">{questions.length} possible questions from the final class list</SectionHeader><div className="grid gap-4 lg:grid-cols-[0.9fr_1.1fr]"><div className="rounded-[1.5rem] border border-stone-200 bg-stone-50 p-4"><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">All possible questions mentioned at the end</div><div className="mt-3 grid gap-2">{questions.map((item, i) => <button key={item.q} onClick={() => { setIdx(i); setText(""); }} className={`rounded-2xl border px-4 py-3 text-left text-sm font-black ${idx === i ? "border-red-300 bg-red-50 text-red-800" : "border-stone-200 bg-white text-stone-700"}`}>{i + 1}. {item.q}</button>)}</div></div><div><div className="rounded-[1.5rem] border border-stone-200 bg-stone-50 p-4"><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">Selected prompt</div><p className="mt-2 text-lg font-black leading-7 text-stone-950">{current.q}</p></div><textarea value={text} onChange={(e) => setText(e.target.value)} placeholder="Write your 10–12 line answer here…" className="mt-4 min-h-[230px] w-full rounded-[1.5rem] border border-stone-200 bg-stone-50 p-4 text-sm font-semibold leading-6 outline-none focus:border-red-300"/><div className="mt-2 text-xs font-black uppercase tracking-[0.18em] text-stone-500">{wc} {ui.words}</div><details className="mt-4 rounded-[1.5rem] border border-stone-200 bg-stone-50 p-4"><summary className="cursor-pointer font-black text-red-800">{ui.model}</summary><p className="mt-3 text-sm font-semibold leading-7 text-stone-700">{current.a}</p></details></div></div></section>; }

export default function DRDLesson07({ lang = "es", isDone = false, toggle = () => {} }) {
  const ui = getUi(lang);
  const copy = (COPY[lang] && COPY[lang].sections.length ? COPY[lang] : COPY.es);
  const lab = LAB_COPY[lang] || LAB_COPY.es;
  const [zoom, setZoom] = useState(null);
  const sections = useMemo(() => copy.sections, [copy]);
  return <main className="mx-auto w-[min(1180px,calc(100%-24px))] pb-16 pt-8 md:pt-12 text-stone-900"><Navigation ui={ui} isDone={isDone} toggle={toggle}/>
    <section className="overflow-hidden rounded-[2.5rem] border border-stone-200 bg-[#fffaf0]/92 shadow-xl shadow-stone-900/5"><div className="grid gap-0 lg:grid-cols-[1.05fr_0.95fr]"><div className="p-7 md:p-10 lg:p-12"><HeroEyebrow>{ui.heroEyebrow}</HeroEyebrow><h1 className="mt-5 max-w-4xl text-4xl font-black leading-[0.96] tracking-tight text-stone-950 md:text-6xl">{ui.heroTitle}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-stone-700">{ui.heroSubtitle}</p><div className="mt-6 flex flex-wrap gap-2">{ui.tags.map((tag) => <Pill key={tag} tone={tag === "FDR" || tag === "FWER" || tag.toLowerCase().includes("bh") ? "red" : "stone"}>{tag}</Pill>)}</div></div><div className="border-t border-stone-200 bg-white/70 p-5 lg:border-l lg:border-t-0"><div className="h-full rounded-[2rem] border border-stone-200 bg-white p-5 shadow-inner"><div className="grid grid-cols-2 gap-3"><StatCard label={ui.module} value="1" tone="red"/><StatCard label={ui.writtenExam} value="4Q"/><StatCard label={ui.answerLines} value="10–12"/><StatCard label={ui.core} value="FDR/BH" tone="red"/></div><div className="mt-5 rounded-3xl bg-stone-950 p-5 text-white"><div className="text-xs font-black uppercase tracking-[0.18em] text-red-200">{ui.bigIdea}</div><p className="mt-2 text-lg font-bold leading-7">{ui.bigIdeaText}</p></div><ResourceLinks ui={ui}/></div></div></div></section>
    {sections.map((section, idx) => <section key={section.title} className="mt-10 rounded-[2.5rem] border border-stone-200 bg-white/80 p-6 shadow-sm md:p-8"><SectionHeader eyebrow={`Part ${idx + 1}`} title={section.title}>{section.intro}</SectionHeader><SlideGrid ui={ui} slides={section.slides} openZoom={setZoom}/>{renderLab(section.lab, lab)}</section>)}
    <Quiz ui={ui}/><WrittenTrainer ui={ui} lang={lang}/><Navigation ui={ui} isDone={isDone} toggle={toggle} position="bottom"/><ZoomModal ui={ui} zoom={zoom} setZoom={setZoom}/>
  </main>;
}
