import React, { useMemo, useState } from "react";

const SLIDES_URL = "https://drive.google.com/file/d/1gKWjGYlPriXXt1xH5aurc6GJHakDJl4T/view?usp=drivesdk";
const TRANSCRIPT_URL = "https://docs.google.com/document/d/13Wu08yLvUaTITj3PmAC8yupFHzC6g8_zXbmVaGxAsUA/edit?usp=drivesdk";
const RECORDING_URL = "https://www.youtube.com/playlist?list=PLZSGWjLWZL3KQFkSCUbUXWEVHeF0MTYZV";

const UI = {
  en: {
    current: "M1.7", dashboard: "DRD dashboard", previous: "Previous", next: "Next", previousTitle: "M1.6 DE genes II", nextTitle: "M1.8 Samples and genes II", mark: "Mark completed", done: "Completed", resources: "Class resources", slides: "Slides", transcript: "Transcript", recording: "Recording", slide: "Source slide", zoom: "Open detail", close: "Close", professor: "Professor emphasis", exam: "Exam watch", expand: "Open expanded answer", include: "What to include", trap: "Common trap", model: "Sample answer", checkpoint: "Checkpoint", written: "Written exam trainer", yourAnswer: "Your answer", reveal: "Reveal model answer", hide: "Hide model answer", module: "Module", writtenExam: "Written test", answerLines: "Answer lines", core: "Core idea", bigIdea: "Big idea", lab: "Mini-lab", heroEyebrow: "Module 1 · June 5 · Relationship between samples and genes I", heroTitle: "From gene lists to sample-and-gene relationships", heroSubtitle: "A theoretical Module 1 lesson on unsupervised analysis, gene × sample matrices, similarity, distance, Pearson correlation, distance metrics, heatmaps and hierarchical clustering.", tags: ["matrix", "distance", "Pearson r", "heatmap", "clustering", "linkage"], bigIdeaText: "Once genes or probes have been measured and corrected, the next question is not only which feature is significant, but how samples and genes relate to each other as patterns in a matrix." },
  es: {
    current: "M1.7", dashboard: "Dashboard DRD", previous: "Anterior", next: "Siguiente", previousTitle: "M1.6 DE genes II", nextTitle: "M1.8 Muestras y genes II", mark: "Marcar completada", done: "Completada", resources: "Recursos de clase", slides: "Slides", transcript: "Transcripción", recording: "Grabación", slide: "Diapo fuente", zoom: "Abrir detalle", close: "Cerrar", professor: "Énfasis de la profesora", exam: "Ojo para examen", expand: "Abrir respuesta desarrollada", include: "Qué incluir", trap: "Trampa frecuente", model: "Respuesta modelo", checkpoint: "Checkpoint", written: "Entrenador de examen escrito", yourAnswer: "Tu respuesta", reveal: "Mostrar respuesta modelo", hide: "Ocultar respuesta modelo", module: "Módulo", writtenExam: "Examen escrito", answerLines: "Líneas", core: "Idea clave", bigIdea: "Idea central", lab: "Mini-lab", heroEyebrow: "Módulo 1 · 5 de junio · Relación entre muestras y genes I", heroTitle: "De listas de genes a relaciones entre muestras y genes", heroSubtitle: "Lección teórica del Módulo 1 sobre análisis no supervisado, matrices gen/probe × muestra, similitud, distancia, correlación de Pearson, métricas de distancia, heatmaps y clustering jerárquico.", tags: ["matriz", "distancia", "Pearson r", "heatmap", "clustering", "linkage"], bigIdeaText: "Una vez medidos y corregidos los genes o probes, la siguiente pregunta no es solo qué feature es significativa, sino cómo se relacionan muestras y genes como patrones dentro de una matriz." },
  fa: {
    current: "M1.7", dashboard: "داشبورد DRD", previous: "قبلی", next: "بعدی", previousTitle: "M1.6 ژن‌های با بیان متفاوت II", nextTitle: "M1.8 نمونه‌ها و ژن‌ها II", mark: "علامت‌گذاری به‌عنوان کامل", done: "کامل شد", resources: "منابع کلاس", slides: "اسلایدها", transcript: "رونوشت", recording: "ضبط", slide: "اسلاید منبع", zoom: "باز کردن جزئیات", close: "بستن", professor: "تأکید استاد", exam: "نکتهٔ امتحان", expand: "پاسخ کامل را باز کنید", include: "چه چیزهایی بیاوریم", trap: "اشتباه رایج", model: "پاسخ نمونه", checkpoint: "چک‌پوینت", written: "تمرین امتحان نوشتاری", yourAnswer: "پاسخ شما", reveal: "نمایش پاسخ نمونه", hide: "پنهان کردن پاسخ نمونه", module: "ماژول", writtenExam: "آزمون کتبی", answerLines: "خط پاسخ", core: "ایدهٔ اصلی", bigIdea: "ایدهٔ مرکزی", lab: "مینی‌لب", heroEyebrow: "Module 1 · June 5 · Relationship between samples and genes I", heroTitle: "از فهرست ژن‌ها تا رابطهٔ میان نمونه‌ها و ژن‌ها", heroSubtitle: "درس نظری دربارهٔ تحلیل بدون‌ناظر، ماتریس ژن/پروب × نمونه، شباهت، فاصله، همبستگی Pearson، معیارهای فاصله، heatmap و خوشه‌بندی سلسله‌مراتبی.", tags: ["matrix", "distance", "Pearson r", "heatmap", "clustering", "linkage"], bigIdeaText: "پس از اندازه‌گیری و اصلاح ژن‌ها یا پروب‌ها، پرسش فقط این نیست که کدام feature معنی‌دار است؛ بلکه این است که نمونه‌ها و ژن‌ها چگونه به‌صورت الگوهای ماتریسی با هم ارتباط دارند." }
};
function getUi(lang) { return UI[lang] || UI.en; }

const COPY = {
  en: {
    sections: [
      { eyebrow: "Bridge", title: "Why this lesson starts after differential analysis", body: "The professor framed this as the final Module 1 block: after preprocessing, normalization and statistical testing, we move to exploratory techniques that describe relationships among samples and among genes.", slides: [{n:1, t:"Multiple testing correction as bridge", text:"P-value cutoffs over hundreds of thousands of probes generate many false positives by chance, so corrected lists are needed before downstream interpretation."}], emphasis: "The professor explicitly moved from classical statistical tests to exploratory analysis: unsupervised analysis first, then supervised methods later.", exam: {q:"Possible question: why do we study sample/gene relationships after calling significant genes?", include:["Mention matrix output from omics experiments.", "Explain that statistics identify features, while unsupervised analysis studies global structure.", "Connect normalization/correction to reliable pattern interpretation."], trap:"Do not describe clustering as a replacement for statistical testing. It answers a different question: pattern/relationship rather than significance of one gene.", sample:"After an omics experiment we obtain a matrix, usually features in rows and samples in columns. Statistical tests identify genes or probes that differ between conditions, but unsupervised analysis asks whether samples and genes show coherent global patterns. This helps detect groups, outliers, similarity between biological profiles and possible technical structure before interpreting the biology."}},
      { eyebrow: "Matrix logic", title: "Rows, columns and the two directions of comparison", body: "A gene-expression or methylation dataset can be read in two directions: compare samples using all genes/probes, or compare genes/probes using all samples.", slides: [{n:2, t:"Gene/probe × sample matrix", text:"Columns are samples; rows are genes or CpGs. Similarity can be studied between samples or between genes/probes."}], emphasis: "She stressed that both directions matter: pairwise samples measured by all genes, or pairwise genes measured across all samples.", exam: {q:"Possible question: how is similarity defined in a gene × sample matrix?", include:["Define rows and columns.", "Explain sample-wise and gene-wise comparison.", "Use the near/far distance interpretation."], trap:"Do not say the matrix has only one correct orientation. In practice, the same matrix can be transposed depending on whether you cluster samples or features.", sample:"In a typical omics matrix, rows represent genes, transcripts or CpG probes, and columns represent samples. To compare samples, each sample is represented by its values across all features. To compare genes, each gene is represented by its profile across all samples. Profiles that are close according to a chosen metric are considered similar; profiles that are far apart are considered dissimilar."}},
      { eyebrow: "Geometry", title: "Distance is the language of similarity", body: "The basic idea is geometric: put profiles in a coordinate system and measure how far apart they are. A valid distance is never negative, is zero for identical profiles, is symmetric and respects the triangle inequality.", slides: [{n:3, t:"Distance rules", text:"d(A,B) ≥ 0; d(A,A)=0; d(A,B)=d(B,A); d(A,C) ≤ d(A,B)+d(B,C)."}], emphasis: "The professor repeated the intuitive rule: near profiles mean similarity; far profiles mean dissimilarity.", exam: {q:"Possible question: explain the geometrical properties of a distance metric.", include:["Non-negativity.", "Identity: distance from a profile to itself is zero.", "Symmetry and triangle inequality.", "Connect these rules to samples/genes in a coordinate space."], trap:"Do not let negative correlation values confuse the distance concept. If you use a correlation-derived distance, transform it so the distance is non-negative.", sample:"A distance metric formalizes dissimilarity between profiles. It must be non-negative, equal to zero when a profile is compared with itself, symmetric between A and B, and must satisfy the triangle inequality. In omics, this lets us treat each sample or gene profile as an object in a coordinate space and quantify how similar or different profiles are."}},
      { eyebrow: "Pearson r", title: "Correlation can be converted into a distance", body: "Pearson r measures linear covariation between two profiles. Because r ranges from -1 to +1, the professor emphasized using a non-negative transformation for distance: 1 - |r|.", slides: [{n:4, t:"Pearson r and correlation distance", text:"r = +1 or -1 gives distance 0 using 1 - |r|; r = 0 gives distance 1."}, {n:5, t:"Real paper example", text:"In the Stanford lymphoma example, two genes with r ≈ 0.97 have distance ≈ 0.03: very similar, but not identical."}], emphasis: "She said not to memorize the formula for Pearson r; understand the concept. She also explicitly warned: correlation does not mean causality.", exam: {q:"Possible question: explain how Pearson correlation can be used as a distance and its limitations.", include:["Pearson measures linear correlation/covariance.", "r close to ±1 means strong relationship; r close to 0 means no linear relationship.", "Distance can be computed as 1 - |r|.", "Mention outlier sensitivity and correlation ≠ causation."], trap:"Do not interpret negative correlation as ‘far’ when the chosen distance is 1 - |r|. Strong anti-correlation still gives small distance because the absolute value is used.", sample:"Pearson r measures how two gene or sample profiles covary linearly. It ranges from -1 to +1. To use it as a distance, we can compute 1 - |r|, so strong positive and strong negative correlations both give a small distance, while r close to 0 gives a large distance. This is useful for clustering profiles with similar patterns, but Pearson is sensitive to outliers and correlation must not be interpreted as causality."}},
      { eyebrow: "Distance metrics", title: "Euclidean, Manhattan and Chebyshev distances", body: "Different metrics emphasize different types of difference. The slides later summarize Euclidean as straight-line distance, Manhattan as sum of absolute differences, and Chebyshev as the maximum coordinate difference.", slides: [{n:6, t:"Euclidean distance", text:"Straight-line distance; useful for continuous data."}, {n:7, t:"Manhattan distance", text:"Sum of absolute distances; often more robust and meaningful in high-dimensional data."}, {n:8, t:"Maximum/Chebyshev distance", text:"Maximum absolute coordinate difference; highlights the largest discrepancy in a single dimension."}], emphasis: "She stressed that every metric has pros and cons; choose the distance according to the analysis and the kind of outliers/noise you expect.", exam: {q:"Possible question: compare Euclidean, Manhattan and Chebyshev distance in high-throughput data.", include:["Define each metric in words.", "Explain what kind of difference each metric emphasizes.", "Mention continuous/high-dimensional data and outlier sensitivity.", "Connect metric choice to clustering results."], trap:"Do not assume all distance metrics give the same clusters. The metric changes what ‘similar’ means.", sample:"Euclidean distance is the straight-line distance between profiles and is intuitive for continuous data. Manhattan distance sums absolute differences across dimensions and can be more robust in high-dimensional settings because each coordinate contributes linearly. Chebyshev distance uses the maximum single-coordinate difference, so it highlights the largest discrepancy between profiles. Since clustering depends on the distance matrix, the metric choice can change the biological interpretation."}},
      { eyebrow: "Visualization", title: "Heatmaps turn matrices into visual biological patterns", body: "A heatmap represents individual matrix values as colors. When paired with clustering, it shows whether samples or genes group together according to their global profiles.", slides: [{n:9, t:"Heatmap + hierarchical clustering", text:"Matrix values are represented by colors; dendrograms summarize similarity among rows and/or columns."}], emphasis: "The point is not only to make a pretty plot: the heatmap is a way to evaluate whether the pattern agrees with phenotype, treatment, tissue, batch or outlier structure.", exam: {q:"Possible question: what does a heatmap with hierarchical clustering show?", include:["Color-coded matrix values.", "Rows/columns can both be clustered.", "Dendrograms reflect similarity based on distance and linkage.", "Interpret clusters in relation to biological/technical variables."], trap:"Do not read a heatmap as proof of differential expression by itself. It is exploratory and descriptive unless combined with statistical testing.", sample:"A heatmap is a color-coded representation of a data matrix. In omics, rows can be genes/probes and columns can be samples. Hierarchical clustering can be added to group similar rows or columns, producing dendrograms. If samples cluster by phenotype or treatment, that supports a biological pattern; if they cluster by processing date or chip, that suggests a technical or batch effect."}},
      { eyebrow: "Clustering", title: "Hierarchical clustering: AGNES, DIANA and linkage", body: "Hierarchical clustering can be agglomerative or divisive. Agglomerative clustering starts with single objects and joins similar clusters; divisive clustering starts with one large group and splits it.", slides: [{n:10, t:"AGNES vs DIANA", text:"AGNES = bottom-up; DIANA = top-down. AGNES is good for small clusters; DIANA can be useful for larger structures."}, {n:11, t:"Hierarchical clustering algorithm", text:"Calculate distances, find the most similar clusters, fuse them, update the distance matrix, repeat."}, {n:12, t:"Linkage methods", text:"Single linkage uses closest objects, complete linkage uses furthest objects, average linkage uses average distances."}], emphasis: "The professor’s practical message: hierarchical clustering is simple and widely used, but sensitive to small changes in the data.", exam: {q:"Possible question: explain hierarchical clustering and linkage methods.", include:["Define agglomerative and divisive logic.", "Describe the iterative steps.", "Compare single, complete and average linkage.", "Mention advantages and drawbacks."], trap:"Do not confuse distance metric with linkage method. The metric defines pairwise distances; the linkage method defines how to compute distance between clusters.", sample:"Hierarchical clustering groups objects according to a distance matrix. In AGNES, each object starts as its own cluster and the algorithm repeatedly joins the two closest clusters. In DIANA, all objects start in one cluster and are progressively split. Linkage defines how cluster-to-cluster distance is measured: single linkage uses the closest pair and can form loose chains, complete linkage uses the furthest pair and tends to form compact clusters, and average linkage is intermediate. The method is intuitive and widely used, but can be sensitive to small data changes."}}
    ],
    labs: { pearsonTitle:"Pearson distance lab", pearsonBody:"Move r and see how 1 - |r| changes.", r:"Pearson r", distance:"Distance", interpretation:"Interpretation", near:"very similar", mid:"moderately distant", far:"dissimilar", vectorsTitle:"Distance metrics lab", vectorsBody:"Edit two profiles separated by commas.", profileA:"Profile A", profileB:"Profile B", euclid:"Euclidean", manhattan:"Manhattan", cheb:"Chebyshev", linkageTitle:"Linkage method quick sorter", linkageBody:"Choose the linkage that matches the rule.", single:"Single linkage", complete:"Complete linkage", average:"Average linkage", correct:"Correct", wrong:"Try again" },
    trainerIntro: "Write a 10-12 line answer first, then open the model answer.", questions: [
      ["Explain unsupervised analysis in the context of gene/sample matrices.", "Unsupervised analysis explores intrinsic structure without using predefined group labels as the main guide. In an omics matrix, features are usually rows and samples are columns. After preprocessing, normalization and statistical testing, unsupervised methods ask whether samples or genes are globally similar. They can reveal clusters, outliers, technical effects and phenotype-related structure. This does not replace statistical testing; it complements it by showing how the whole dataset behaves."],
      ["How can Pearson correlation be transformed into a distance and what are the caveats?", "Pearson r measures linear covariation between two profiles and ranges from -1 to +1. A distance can be defined as 1 - |r|, so strong positive or negative correlation gives a small distance and r near zero gives a large distance. This is useful when the pattern is more important than absolute magnitude. The caveats are that Pearson assumes linear relationships, is sensitive to outliers and correlation must not be interpreted as causality."],
      ["Compare Euclidean, Manhattan and Chebyshev distance.", "Euclidean distance is the straight-line distance between profiles and is intuitive for continuous data. Manhattan distance is the sum of absolute coordinate differences and can be more robust in high-dimensional data because all coordinates contribute linearly. Chebyshev distance is the maximum absolute coordinate difference and highlights the largest single discrepancy. Since clustering depends on the distance matrix, the metric changes what the analysis calls similar."],
      ["Explain hierarchical clustering, AGNES/DIANA and linkage methods.", "Hierarchical clustering builds a tree of similarity relationships. AGNES is agglomerative: it starts with single objects and joins the closest clusters step by step. DIANA is divisive: it starts with all objects in one cluster and splits them. Linkage decides how distance between clusters is computed. Single linkage uses the closest pair and can make chains; complete linkage uses the furthest pair and gives compact clusters; average linkage is intermediate. The method is easy to interpret but sensitive to metric and data changes."],
      ["How should a heatmap with clustering be interpreted biologically?", "A heatmap displays matrix values as colors, often with dendrograms for rows and columns. In omics, row clusters may identify genes or probes with similar profiles, and column clusters may identify samples with similar global patterns. Interpretation requires checking whether clusters match phenotype, treatment, tissue, sex, batch, chip or outliers. A heatmap is exploratory: it supports biological interpretation but does not alone prove differential expression or methylation."],
    ]
  },
  es: {
    sections: [
      { eyebrow: "Puente", title: "Por qué esta lección viene después del análisis diferencial", body: "La profesora planteó esta clase como el bloque final del Módulo 1: después de preprocessing, normalización y tests estadísticos, pasamos a técnicas exploratorias que describen relaciones entre muestras y entre genes.", slides: [{n:1, t:"Multiple testing correction como puente", text:"Si aplicas un cutoff de p-value a cientos de miles de probes, aparecen muchos falsos positivos por azar; por eso se necesitan listas corregidas antes de interpretar."}], emphasis: "La profesora movió explícitamente la clase desde los tests estadísticos clásicos hacia el análisis exploratorio: primero análisis no supervisado y luego, más adelante, supervisado.", exam: {q:"Posible pregunta: ¿por qué estudiamos relaciones entre muestras/genes después de llamar genes significativos?", include:["Menciona el output matricial de los experimentos ómicos.", "Explica que los tests identifican features, mientras el análisis no supervisado estudia estructura global.", "Conecta normalización/corrección con interpretación fiable de patrones."], trap:"No describas clustering como reemplazo de los tests estadísticos. Responde otra pregunta: patrón/relación, no significancia de un gen aislado.", sample:"Después de un experimento ómico obtenemos una matriz, normalmente features en filas y muestras en columnas. Los tests estadísticos identifican genes o probes que cambian entre condiciones, pero el análisis no supervisado pregunta si muestras y genes muestran patrones globales coherentes. Esto ayuda a detectar grupos, outliers, similitud entre perfiles biológicos y posible estructura técnica antes de interpretar la biología."}},
      { eyebrow: "Lógica de matriz", title: "Filas, columnas y las dos direcciones de comparación", body: "Un dataset de expresión o metilación puede leerse en dos direcciones: comparar muestras usando todos los genes/probes, o comparar genes/probes usando todas las muestras.", slides: [{n:2, t:"Matriz gen/probe × muestra", text:"Las columnas son muestras; las filas son genes o CpGs. La similitud puede estudiarse entre muestras o entre genes/probes."}], emphasis: "Remarcó que ambas direcciones importan: pares de muestras medidas por todos los genes, o pares de genes medidos a través de todas las muestras.", exam: {q:"Posible pregunta: ¿cómo se define similitud en una matriz gen × muestra?", include:["Define filas y columnas.", "Explica comparación sample-wise y gene-wise.", "Usa la interpretación cerca/lejos de la distancia."], trap:"No digas que la matriz tiene una única orientación correcta. En la práctica puede transponerse según quieras clusterizar muestras o features.", sample:"En una matriz ómica típica, las filas representan genes, transcriptos o CpG probes, y las columnas representan muestras. Para comparar muestras, cada muestra se representa por sus valores en todos los features. Para comparar genes, cada gen se representa por su perfil a través de las muestras. Los perfiles cercanos según una métrica son similares; los perfiles lejanos son disimilares."}},
      { eyebrow: "Geometría", title: "La distancia es el lenguaje de la similitud", body: "La idea básica es geométrica: ubicar perfiles en coordenadas y medir qué tan lejos están. Una distancia válida nunca es negativa, es cero para perfiles idénticos, es simétrica y respeta la desigualdad triangular.", slides: [{n:3, t:"Reglas de distancia", text:"d(A,B) ≥ 0; d(A,A)=0; d(A,B)=d(B,A); d(A,C) ≤ d(A,B)+d(B,C)."}], emphasis: "La profesora repitió la regla intuitiva: perfiles cercanos significan similitud; perfiles lejanos significan disimilitud.", exam: {q:"Posible pregunta: explica las propiedades geométricas de una métrica de distancia.", include:["No negatividad.", "Identidad: distancia de un perfil consigo mismo es cero.", "Simetría y desigualdad triangular.", "Conecta estas reglas con muestras/genes en coordenadas."], trap:"No dejes que valores negativos de correlación confundan el concepto de distancia. Si usas distancia derivada de correlación, transfórmala para que sea no negativa.", sample:"Una métrica de distancia formaliza la disimilitud entre perfiles. Debe ser no negativa, valer cero cuando un perfil se compara consigo mismo, ser simétrica entre A y B, y cumplir la desigualdad triangular. En ómicas, esto permite tratar cada muestra o perfil génico como un objeto en un espacio de coordenadas y cuantificar qué tan similares o diferentes son."}},
      { eyebrow: "Pearson r", title: "La correlación puede convertirse en distancia", body: "Pearson r mide covariación lineal entre dos perfiles. Como r va de -1 a +1, la profesora enfatizó usar una transformación no negativa para distancia: 1 - |r|.", slides: [{n:4, t:"Pearson r y distancia por correlación", text:"r = +1 o -1 da distancia 0 usando 1 - |r|; r = 0 da distancia 1."}, {n:5, t:"Ejemplo de paper real", text:"En el ejemplo de lymphoma de Stanford, dos genes con r ≈ 0.97 tienen distancia ≈ 0.03: muy similares, pero no idénticos."}], emphasis: "Dijo que no hace falta memorizar la fórmula de Pearson r; hay que entender el concepto. También avisó explícitamente: correlación no significa causalidad.", exam: {q:"Posible pregunta: explica cómo Pearson puede usarse como distancia y sus limitaciones.", include:["Pearson mide correlación/covarianza lineal.", "r cerca de ±1 indica relación fuerte; r cerca de 0 indica ausencia de relación lineal.", "La distancia puede ser 1 - |r|.", "Menciona sensibilidad a outliers y correlación ≠ causalidad."], trap:"No interpretes correlación negativa como ‘lejos’ cuando la distancia elegida es 1 - |r|. Una anticorrelación fuerte también da distancia pequeña porque se usa valor absoluto.", sample:"Pearson r mide cómo covarían linealmente dos perfiles génicos o de muestras. Va de -1 a +1. Para usarlo como distancia se puede calcular 1 - |r|, de modo que correlaciones positivas o negativas fuertes dan distancia pequeña, mientras que r cercano a cero da distancia grande. Esto sirve cuando importa el patrón, pero Pearson es sensible a outliers y la correlación no debe interpretarse como causalidad."}},
      { eyebrow: "Métricas", title: "Distancias Euclídea, Manhattan y Chebyshev", body: "Cada métrica enfatiza un tipo distinto de diferencia. Las slides resumen Euclídea como línea recta, Manhattan como suma de diferencias absolutas y Chebyshev como la diferencia máxima en una coordenada.", slides: [{n:6, t:"Distancia Euclídea", text:"Distancia en línea recta; útil para datos continuos."}, {n:7, t:"Distancia Manhattan", text:"Suma de diferencias absolutas; suele ser más robusta y significativa en datos de alta dimensión."}, {n:8, t:"Distancia máxima/Chebyshev", text:"Máxima diferencia absoluta por coordenada; resalta la discrepancia más grande en una dimensión."}], emphasis: "Remarcó que cada métrica tiene pros y contras; se elige según el análisis y el tipo de outliers/ruido esperado.", exam: {q:"Posible pregunta: compara distancia Euclídea, Manhattan y Chebyshev en datos high-throughput.", include:["Define cada métrica en palabras.", "Explica qué diferencia enfatiza cada una.", "Menciona datos continuos/alta dimensión y outliers.", "Conecta elección de métrica con resultados de clustering."], trap:"No asumas que todas las métricas dan los mismos clusters. La métrica cambia qué significa ‘similar’." , sample:"La distancia Euclídea es la línea recta entre perfiles y es intuitiva para datos continuos. Manhattan suma diferencias absolutas y puede ser más robusta en alta dimensión porque cada coordenada contribuye linealmente. Chebyshev usa la mayor diferencia absoluta en una coordenada y destaca la discrepancia máxima entre perfiles. Como el clustering depende de la matriz de distancias, la elección de métrica puede cambiar la interpretación biológica."}},
      { eyebrow: "Visualización", title: "Los heatmaps convierten matrices en patrones biológicos visuales", body: "Un heatmap representa los valores de una matriz con colores. Combinado con clustering, muestra si muestras o genes se agrupan según perfiles globales.", slides: [{n:9, t:"Heatmap + clustering jerárquico", text:"Los valores de matriz se representan como colores; los dendrogramas resumen similitud entre filas y/o columnas."}], emphasis: "El punto no es solo hacer una figura bonita: el heatmap permite evaluar si el patrón coincide con fenotipo, tratamiento, tejido, batch u outliers.", exam: {q:"Posible pregunta: ¿qué muestra un heatmap con clustering jerárquico?", include:["Valores de matriz codificados por color.", "Pueden clusterizarse filas y columnas.", "Los dendrogramas reflejan similitud según distancia y linkage.", "Interpreta clusters en relación con variables biológicas/técnicas."], trap:"No leas un heatmap como prueba de expresión diferencial por sí solo. Es exploratorio y descriptivo si no se combina con tests estadísticos.", sample:"Un heatmap es una representación por color de una matriz de datos. En ómicas, las filas pueden ser genes/probes y las columnas muestras. El clustering jerárquico agrupa filas o columnas similares y produce dendrogramas. Si las muestras se agrupan por fenotipo o tratamiento, apoya un patrón biológico; si se agrupan por fecha de procesamiento o chip, sugiere un efecto técnico o batch."}},
      { eyebrow: "Clustering", title: "Clustering jerárquico: AGNES, DIANA y linkage", body: "El clustering jerárquico puede ser aglomerativo o divisivo. El aglomerativo empieza con objetos individuales y une clusters similares; el divisivo empieza con un grupo grande y lo separa.", slides: [{n:10, t:"AGNES vs DIANA", text:"AGNES = bottom-up; DIANA = top-down. AGNES va bien para clusters pequeños; DIANA puede ayudar con estructuras grandes."}, {n:11, t:"Algoritmo de clustering jerárquico", text:"Calcular distancias, encontrar clusters más similares, fusionarlos, actualizar la matriz de distancias y repetir."}, {n:12, t:"Métodos de linkage", text:"Single usa los objetos más cercanos, complete usa los más lejanos, average usa distancias promedio."}], emphasis: "Mensaje práctico de la profesora: el clustering jerárquico es simple y muy usado, pero sensible a pequeños cambios en los datos.", exam: {q:"Posible pregunta: explica clustering jerárquico y métodos de linkage.", include:["Define lógica aglomerativa y divisiva.", "Describe los pasos iterativos.", "Compara single, complete y average linkage.", "Menciona ventajas y desventajas."], trap:"No confundas métrica de distancia con método de linkage. La métrica define distancias entre pares; el linkage define cómo calcular distancia entre clusters.", sample:"El clustering jerárquico agrupa objetos según una matriz de distancias. En AGNES, cada objeto empieza como su propio cluster y el algoritmo une repetidamente los clusters más cercanos. En DIANA, todos los objetos empiezan en un cluster y se van separando. El linkage define cómo se mide distancia entre clusters: single usa el par más cercano y puede formar cadenas; complete usa el par más lejano y genera clusters compactos; average es intermedio. Es intuitivo y muy usado, pero sensible a la métrica y a cambios en los datos."}}
    ],
    labs: { pearsonTitle:"Mini-lab de distancia Pearson", pearsonBody:"Mueve r y observa cómo cambia 1 - |r|.", r:"Pearson r", distance:"Distancia", interpretation:"Interpretación", near:"muy similar", mid:"distancia moderada", far:"disimilar", vectorsTitle:"Mini-lab de métricas de distancia", vectorsBody:"Edita dos perfiles separados por comas.", profileA:"Perfil A", profileB:"Perfil B", euclid:"Euclídea", manhattan:"Manhattan", cheb:"Chebyshev", linkageTitle:"Selector rápido de linkage", linkageBody:"Elige el linkage que corresponde a la regla.", single:"Single linkage", complete:"Complete linkage", average:"Average linkage", correct:"Correcto", wrong:"Intenta otra vez" },
    trainerIntro: "Escribe primero una respuesta de 10-12 líneas y luego abre la respuesta modelo.", questions: [
      ["Explica el análisis no supervisado en el contexto de matrices genes/muestras.", "El análisis no supervisado explora la estructura intrínseca sin usar etiquetas de grupo predefinidas como guía principal. En una matriz ómica, los features suelen estar en filas y las muestras en columnas. Después de preprocessing, normalización y estadística, los métodos no supervisados preguntan si muestras o genes son globalmente similares. Pueden revelar clusters, outliers, efectos técnicos y estructura relacionada con fenotipo. No reemplazan los tests estadísticos; los complementan mostrando cómo se comporta todo el dataset."],
      ["¿Cómo se transforma Pearson en distancia y cuáles son sus caveats?", "Pearson r mide covariación lineal entre dos perfiles y va de -1 a +1. Una distancia puede definirse como 1 - |r|, de modo que una correlación positiva o negativa fuerte da distancia pequeña y r cercano a cero da distancia grande. Sirve cuando importa el patrón más que la magnitud absoluta. Los caveats son que Pearson asume relaciones lineales, es sensible a outliers y correlación no significa causalidad."],
      ["Compara distancia Euclídea, Manhattan y Chebyshev.", "La distancia Euclídea es la línea recta entre perfiles y es intuitiva para datos continuos. Manhattan es la suma de diferencias absolutas por coordenada y puede ser más robusta en datos de alta dimensión porque todas las coordenadas contribuyen linealmente. Chebyshev es la máxima diferencia absoluta y resalta la mayor discrepancia individual. Como el clustering depende de la matriz de distancias, la métrica cambia lo que el análisis considera similar."],
      ["Explica clustering jerárquico, AGNES/DIANA y linkage.", "El clustering jerárquico construye un árbol de relaciones de similitud. AGNES es aglomerativo: empieza con objetos individuales y une los clusters más cercanos paso a paso. DIANA es divisivo: empieza con todos los objetos en un cluster y los separa. El linkage decide cómo calcular distancia entre clusters. Single usa el par más cercano y puede crear cadenas; complete usa el par más lejano y genera clusters compactos; average es intermedio. Es fácil de interpretar, pero sensible a métrica y cambios en datos."],
      ["¿Cómo interpretar biológicamente un heatmap con clustering?", "Un heatmap muestra valores de matriz como colores, a menudo con dendrogramas para filas y columnas. En ómicas, clusters de filas pueden indicar genes o probes con perfiles similares, y clusters de columnas pueden indicar muestras con patrones globales similares. La interpretación requiere comprobar si los clusters coinciden con fenotipo, tratamiento, tejido, sexo, batch, chip u outliers. Es una herramienta exploratoria: apoya la interpretación, pero no prueba por sí sola expresión o metilación diferencial."],
    ]
  }
};
COPY.fa = {
  sections: [
    { eyebrow: "پل مفهومی", title: "چرا این درس بعد از تحلیل افتراقی می‌آید", body: "استاد این جلسه را به‌عنوان بخش پایانی ماژول ۱ معرفی کرد: پس از preprocessing، نرمال‌سازی و آزمون‌های آماری، حالا به روش‌های اکتشافی می‌رسیم که رابطهٔ میان نمونه‌ها و میان ژن‌ها را توصیف می‌کنند.", slides: [{n:1, t:"تصحیح آزمون‌های چندگانه به‌عنوان پل", text:"اگر cutoff مربوط به p-value را روی صدها هزار probe اعمال کنیم، تعداد زیادی false positive فقط به‌دلیل شانس ظاهر می‌شود؛ بنابراین پیش از تفسیر downstream به فهرست تصحیح‌شده نیاز داریم."}], emphasis: "استاد به‌طور واضح کلاس را از آزمون‌های آماری کلاسیک به سمت تحلیل اکتشافی برد: ابتدا تحلیل بدون‌ناظر و سپس در جلسات بعدی روش‌های دیگر.", exam: {q:"پرسش احتمالی: چرا پس از یافتن ژن‌های معنی‌دار، رابطهٔ نمونه‌ها و ژن‌ها را بررسی می‌کنیم؟", include:["به خروجی ماتریسی آزمایش‌های omics اشاره کنید.", "توضیح دهید آزمون‌ها featureها را پیدا می‌کنند، اما تحلیل بدون‌ناظر ساختار کلی را بررسی می‌کند.", "نرمال‌سازی و تصحیح را به تفسیر قابل‌اعتماد الگوها وصل کنید."], trap:"clustering را جایگزین آزمون آماری معرفی نکنید. این روش پرسش دیگری را پاسخ می‌دهد: الگو و رابطه، نه معنی‌داری یک ژن منفرد.", sample:"پس از یک آزمایش omics معمولاً ماتریسی داریم که featureها در ردیف‌ها و نمونه‌ها در ستون‌ها قرار دارند. آزمون‌های آماری ژن‌ها یا probeهایی را پیدا می‌کنند که بین شرایط متفاوت‌اند، اما تحلیل بدون‌ناظر می‌پرسد آیا نمونه‌ها و ژن‌ها الگوهای کلی منسجم نشان می‌دهند یا نه. این کار به شناسایی گروه‌ها، outlierها، شباهت بین پروفایل‌های زیستی و ساختار فنی احتمالی کمک می‌کند."}},
    { eyebrow: "منطق ماتریس", title: "ردیف‌ها، ستون‌ها و دو جهت مقایسه", body: "یک dataset بیان ژن یا متیلاسیون را می‌توان از دو جهت خواند: مقایسهٔ نمونه‌ها با استفاده از همهٔ ژن‌ها/پروب‌ها، یا مقایسهٔ ژن‌ها/پروب‌ها با استفاده از همهٔ نمونه‌ها.", slides: [{n:2, t:"ماتریس ژن/پروب × نمونه", text:"ستون‌ها نمونه‌ها هستند؛ ردیف‌ها ژن‌ها یا CpGها هستند. شباهت می‌تواند میان نمونه‌ها یا میان ژن‌ها/پروب‌ها بررسی شود."}], emphasis: "استاد تأکید کرد که هر دو جهت مهم‌اند: جفت نمونه‌ها که با همهٔ ژن‌ها سنجیده می‌شوند، یا جفت ژن‌ها که در همهٔ نمونه‌ها بررسی می‌شوند.", exam: {q:"پرسش احتمالی: شباهت در ماتریس ژن × نمونه چگونه تعریف می‌شود؟", include:["ردیف‌ها و ستون‌ها را تعریف کنید.", "مقایسهٔ sample-wise و gene-wise را توضیح دهید.", "از تفسیر نزدیک/دور برای فاصله استفاده کنید."], trap:"نگویید ماتریس فقط یک جهت درست دارد. بسته به اینکه نمونه‌ها یا featureها را خوشه‌بندی کنیم، ماتریس می‌تواند transposed شود.", sample:"در یک ماتریس omics معمولی، ردیف‌ها ژن‌ها، transcriptها یا CpG probeها هستند و ستون‌ها نمونه‌ها. برای مقایسهٔ نمونه‌ها، هر نمونه با مقادیر خود در همهٔ featureها نمایش داده می‌شود. برای مقایسهٔ ژن‌ها، هر ژن با پروفایل خود در همهٔ نمونه‌ها نمایش داده می‌شود. پروفایل‌هایی که طبق یک metric نزدیک‌اند مشابه‌اند و پروفایل‌های دورتر نامشابه‌اند."}},
    { eyebrow: "هندسه", title: "فاصله زبان شباهت است", body: "ایدهٔ اصلی هندسی است: پروفایل‌ها را در یک دستگاه مختصات قرار می‌دهیم و فاصلهٔ آن‌ها را می‌سنجیم. فاصلهٔ معتبر منفی نیست، برای پروفایل یکسان صفر است، متقارن است و نامساوی مثلثی را رعایت می‌کند.", slides: [{n:3, t:"قواعد فاصله", text:"d(A,B) ≥ 0; d(A,A)=0; d(A,B)=d(B,A); d(A,C) ≤ d(A,B)+d(B,C)."}], emphasis: "استاد قانون شهودی را تکرار کرد: پروفایل‌های نزدیک یعنی شباهت؛ پروفایل‌های دور یعنی عدم شباهت.", exam: {q:"پرسش احتمالی: ویژگی‌های هندسی یک metric فاصله را توضیح دهید.", include:["غیرمنفی بودن.", "هویت: فاصلهٔ یک پروفایل از خودش صفر است.", "تقارن و نامساوی مثلثی.", "اتصال این قواعد به نمونه‌ها/ژن‌ها در فضای مختصات."], trap:"مقادیر منفی همبستگی را با مفهوم فاصله اشتباه نگیرید. اگر از فاصلهٔ مشتق از correlation استفاده می‌کنید، آن را غیرمنفی کنید.", sample:"یک metric فاصله، عدم شباهت میان پروفایل‌ها را رسمی می‌کند. این مقدار باید غیرمنفی باشد، هنگام مقایسهٔ یک پروفایل با خودش صفر شود، بین A و B متقارن باشد و نامساوی مثلثی را رعایت کند. در omics، این قواعد اجازه می‌دهند هر نمونه یا پروفایل ژنی را به‌عنوان یک شیء در فضای مختصات ببینیم و میزان شباهت یا تفاوت آن‌ها را بسنجیم."}},
    { eyebrow: "Pearson r", title: "همبستگی را می‌توان به فاصله تبدیل کرد", body: "Pearson r هم‌تغییری خطی بین دو پروفایل را می‌سنجد. چون r بین -1 و +1 است، استاد بر تبدیل غیرمنفی برای فاصله تأکید کرد: 1 - |r|.", slides: [{n:4, t:"Pearson r و فاصلهٔ همبستگی", text:"r = +1 یا -1 با فرمول 1 - |r| فاصلهٔ 0 می‌دهد؛ r = 0 فاصلهٔ 1 می‌دهد."}, {n:5, t:"نمونهٔ یک مقالهٔ واقعی", text:"در مثال lymphoma مربوط به Stanford، دو ژن با r ≈ 0.97 فاصلهٔ ≈ 0.03 دارند: بسیار مشابه، ولی نه کاملاً یکسان."}], emphasis: "او گفت لازم نیست فرمول Pearson r را حفظ کنید؛ مفهوم مهم است. همچنین صریحاً هشدار داد: correlation به معنی causality نیست.", exam: {q:"پرسش احتمالی: توضیح دهید Pearson چگونه به‌عنوان فاصله استفاده می‌شود و محدودیت‌های آن چیست.", include:["Pearson همبستگی/کوواریانس خطی را می‌سنجد.", "r نزدیک ±1 رابطهٔ قوی و r نزدیک 0 نبود رابطهٔ خطی را نشان می‌دهد.", "فاصله می‌تواند 1 - |r| باشد.", "حساسیت به outlier و correlation ≠ causality را ذکر کنید."], trap:"وقتی distance برابر 1 - |r| است، correlation منفی را الزاماً «دور» تفسیر نکنید. anti-correlation قوی هم چون قدرمطلق استفاده می‌شود فاصلهٔ کوچک می‌دهد.", sample:"Pearson r نشان می‌دهد دو پروفایل ژنی یا نمونه‌ای چگونه به‌صورت خطی با هم تغییر می‌کنند. مقدار آن از -1 تا +1 است. برای استفاده به‌عنوان فاصله می‌توان 1 - |r| را محاسبه کرد؛ بنابراین correlation مثبت یا منفی قوی فاصلهٔ کوچک می‌دهد و r نزدیک صفر فاصلهٔ بزرگ. این روش وقتی الگوی تغییر مهم‌تر از مقدار مطلق است مفید است، اما Pearson به outlier حساس است و correlation نباید به‌عنوان causal relationship تفسیر شود."}},
    { eyebrow: "معیارهای فاصله", title: "فاصله‌های Euclidean، Manhattan و Chebyshev", body: "هر metric نوع متفاوتی از اختلاف را برجسته می‌کند. اسلایدها Euclidean را فاصلهٔ مستقیم، Manhattan را مجموع اختلافات مطلق، و Chebyshev را بیشترین اختلاف در یک مختصات معرفی می‌کنند.", slides: [{n:6, t:"فاصلهٔ Euclidean", text:"فاصلهٔ مستقیم؛ برای داده‌های پیوسته مناسب است."}, {n:7, t:"فاصلهٔ Manhattan", text:"مجموع اختلافات مطلق؛ در داده‌های با ابعاد بالا اغلب robustتر و معنادارتر است."}, {n:8, t:"فاصلهٔ Maximum/Chebyshev", text:"بیشترین اختلاف مطلق در یک مختصات؛ بزرگ‌ترین discrepancy در یک بعد را برجسته می‌کند."}], emphasis: "استاد تأکید کرد که هر metric مزایا و معایب دارد و باید براساس تحلیل و نوع outlier/noise انتخاب شود.", exam: {q:"پرسش احتمالی: Euclidean، Manhattan و Chebyshev را در داده‌های high-throughput مقایسه کنید.", include:["هر metric را با کلمات تعریف کنید.", "بگویید هر کدام چه نوع اختلافی را برجسته می‌کند.", "به داده‌های پیوسته/ابعاد بالا و outlier اشاره کنید.", "انتخاب metric را به نتایج clustering وصل کنید."], trap:"فرض نکنید همهٔ metricها clusterهای یکسان می‌دهند. metric تعیین می‌کند «مشابه» یعنی چه.", sample:"Euclidean فاصلهٔ خط مستقیم میان پروفایل‌هاست و برای داده‌های پیوسته شهودی است. Manhattan مجموع اختلافات مطلق در مختصات است و در داده‌های با ابعاد بالا می‌تواند robustتر باشد، چون هر مختصات به‌صورت خطی مشارکت می‌کند. Chebyshev بیشترین اختلاف مطلق در یک مختصات را می‌گیرد و بنابراین بزرگ‌ترین discrepancy را برجسته می‌کند. چون clustering به ماتریس فاصله وابسته است، انتخاب metric می‌تواند تفسیر زیستی را تغییر دهد."}},
    { eyebrow: "visualization", title: "Heatmap ماتریس را به الگوی زیستی قابل مشاهده تبدیل می‌کند", body: "Heatmap مقادیر ماتریس را با رنگ نشان می‌دهد. همراه با clustering می‌تواند نشان دهد آیا نمونه‌ها یا ژن‌ها بر اساس پروفایل‌های کلی کنار هم قرار می‌گیرند یا نه.", slides: [{n:9, t:"Heatmap + hierarchical clustering", text:"مقادیر ماتریس به رنگ تبدیل می‌شوند؛ dendrogramها شباهت میان ردیف‌ها و/یا ستون‌ها را خلاصه می‌کنند."}], emphasis: "هدف فقط ساختن یک شکل زیبا نیست؛ heatmap کمک می‌کند ببینیم الگو با phenotype، treatment، tissue، batch یا outlierها همخوانی دارد یا نه.", exam: {q:"پرسش احتمالی: heatmap همراه با hierarchical clustering چه چیزی نشان می‌دهد؟", include:["مقادیر ماتریس به‌صورت رنگ نمایش داده می‌شوند.", "ردیف‌ها و ستون‌ها هر دو می‌توانند cluster شوند.", "dendrogramها شباهت را بر اساس distance و linkage نشان می‌دهند.", "clusterها را نسبت به متغیرهای زیستی/فنی تفسیر کنید."], trap:"heatmap را به‌تنهایی به‌عنوان اثبات differential expression نخوانید. این ابزار exploratory و descriptive است مگر اینکه با آزمون آماری ترکیب شود.", sample:"Heatmap نمایش رنگی یک ماتریس داده است. در omics، ردیف‌ها می‌توانند ژن‌ها یا probeها و ستون‌ها نمونه‌ها باشند. Hierarchical clustering می‌تواند ردیف‌ها یا ستون‌های مشابه را گروه‌بندی کند و dendrogram بسازد. اگر نمونه‌ها بر اساس phenotype یا treatment خوشه‌بندی شوند، از یک الگوی زیستی حمایت می‌کند؛ اگر براساس تاریخ پردازش یا chip خوشه‌بندی شوند، احتمال اثر فنی یا batch مطرح می‌شود."}},
    { eyebrow: "clustering", title: "Hierarchical clustering: AGNES، DIANA و linkage", body: "Hierarchical clustering می‌تواند agglomerative یا divisive باشد. روش agglomerative با objectهای منفرد شروع می‌کند و clusterهای مشابه را ادغام می‌کند؛ روش divisive با یک گروه بزرگ شروع می‌کند و آن را می‌شکند.", slides: [{n:10, t:"AGNES در برابر DIANA", text:"AGNES = bottom-up؛ DIANA = top-down. AGNES برای clusterهای کوچک خوب است؛ DIANA می‌تواند برای ساختارهای بزرگ مفید باشد."}, {n:11, t:"الگوریتم hierarchical clustering", text:"فاصله‌ها را محاسبه کنید، نزدیک‌ترین clusterها را پیدا کنید، آن‌ها را ادغام کنید، ماتریس فاصله را به‌روزرسانی کنید و تکرار کنید."}, {n:12, t:"روش‌های linkage", text:"Single نزدیک‌ترین objectها، complete دورترین objectها، و average میانگین فاصله‌ها را استفاده می‌کند."}], emphasis: "پیام عملی استاد: hierarchical clustering ساده و بسیار رایج است، اما به تغییرات کوچک داده حساس است.", exam: {q:"پرسش احتمالی: hierarchical clustering و linkage methods را توضیح دهید.", include:["منطق agglomerative و divisive را تعریف کنید.", "مراحل تکراری را شرح دهید.", "single، complete و average linkage را مقایسه کنید.", "مزایا و محدودیت‌ها را ذکر کنید."], trap:"metric فاصله را با linkage اشتباه نگیرید. metric فاصلهٔ جفتی را تعریف می‌کند؛ linkage فاصلهٔ میان clusterها را تعریف می‌کند.", sample:"Hierarchical clustering objectها را بر اساس ماتریس فاصله گروه‌بندی می‌کند. در AGNES هر object ابتدا cluster خودش است و الگوریتم نزدیک‌ترین clusterها را مرحله‌به‌مرحله ادغام می‌کند. در DIANA همهٔ objectها ابتدا در یک cluster هستند و سپس جدا می‌شوند. Linkage تعیین می‌کند فاصلهٔ بین clusterها چگونه اندازه‌گیری شود: single از نزدیک‌ترین جفت استفاده می‌کند و می‌تواند chain بسازد؛ complete از دورترین جفت استفاده می‌کند و clusterهای compact می‌دهد؛ average حالت میانی است. روش شهودی و رایج است، اما به metric و تغییرات داده حساس است."}}
  ],
  labs: { pearsonTitle:"مینی‌لب فاصلهٔ Pearson", pearsonBody:"r را تغییر دهید و ببینید 1 - |r| چگونه عوض می‌شود.", r:"Pearson r", distance:"فاصله", interpretation:"تفسیر", near:"بسیار مشابه", mid:"فاصلهٔ متوسط", far:"نامشابه", vectorsTitle:"مینی‌لب معیارهای فاصله", vectorsBody:"دو پروفایل را با کاما ویرایش کنید.", profileA:"پروفایل A", profileB:"پروفایل B", euclid:"Euclidean", manhattan:"Manhattan", cheb:"Chebyshev", linkageTitle:"مرتب‌ساز سریع linkage", linkageBody:"linkage مطابق با قاعده را انتخاب کنید.", single:"Single linkage", complete:"Complete linkage", average:"Average linkage", correct:"درست", wrong:"دوباره تلاش کنید" },
  trainerIntro: "ابتدا یک پاسخ ۱۰ تا ۱۲ خطی بنویسید، سپس پاسخ نمونه را باز کنید.",
  questions: [
    ["تحلیل بدون‌ناظر را در زمینهٔ ماتریس ژن/نمونه توضیح دهید.", "تحلیل بدون‌ناظر ساختار درونی داده را بدون تکیهٔ اصلی بر برچسب‌های گروهی از پیش تعیین‌شده بررسی می‌کند. در یک ماتریس omics، featureها معمولاً در ردیف و نمونه‌ها در ستون هستند. پس از preprocessing، نرمال‌سازی و آزمون آماری، این روش‌ها می‌پرسند آیا نمونه‌ها یا ژن‌ها در سطح کلی مشابه هستند یا نه. آن‌ها می‌توانند cluster، outlier، اثر فنی و ساختار مربوط به phenotype را آشکار کنند. این کار جایگزین آزمون آماری نیست؛ مکمل آن است."],
    ["Pearson چگونه به فاصله تبدیل می‌شود و caveatهای آن چیست؟", "Pearson r هم‌تغییری خطی بین دو پروفایل را می‌سنجد و از -1 تا +1 است. می‌توان فاصله را 1 - |r| تعریف کرد؛ بنابراین correlation مثبت یا منفی قوی فاصلهٔ کوچک می‌دهد و r نزدیک صفر فاصلهٔ بزرگ. این روش زمانی مفید است که الگو مهم‌تر از مقدار مطلق باشد. محدودیت‌ها: فرض رابطهٔ خطی، حساسیت به outlier و اینکه correlation به معنی causality نیست."],
    ["Euclidean، Manhattan و Chebyshev را مقایسه کنید.", "Euclidean فاصلهٔ مستقیم میان پروفایل‌هاست و برای داده‌های پیوسته شهودی است. Manhattan مجموع اختلافات مطلق در مختصات است و در داده‌های high-dimensional می‌تواند robustتر باشد. Chebyshev بیشترین اختلاف مطلق در یک مختصات را می‌گیرد و بزرگ‌ترین discrepancy را برجسته می‌کند. چون clustering به ماتریس فاصله وابسته است، metric انتخابی معنای similarity را تغییر می‌دهد."],
    ["Hierarchical clustering، AGNES/DIANA و linkage را توضیح دهید.", "Hierarchical clustering یک درخت از روابط شباهت می‌سازد. AGNES agglomerative است: از objectهای منفرد شروع می‌کند و نزدیک‌ترین clusterها را ادغام می‌کند. DIANA divisive است: از یک cluster شامل همهٔ objectها شروع می‌کند و آن‌ها را جدا می‌کند. Linkage نحوهٔ محاسبهٔ فاصلهٔ بین clusterهاست: single نزدیک‌ترین جفت، complete دورترین جفت و average میانگین فاصله‌ها را استفاده می‌کند. روش قابل‌فهم است ولی به metric و تغییرات داده حساس است."],
    ["یک heatmap با clustering را چگونه زیستی تفسیر می‌کنیم؟", "Heatmap مقادیر ماتریس را با رنگ نشان می‌دهد و اغلب dendrogram برای ردیف‌ها و ستون‌ها دارد. در omics، clusterهای ردیفی می‌توانند ژن‌ها یا probeهای با پروفایل مشابه را نشان دهند و clusterهای ستونی نمونه‌های مشابه را. برای تفسیر باید بررسی کنیم clusterها با phenotype، treatment، tissue، sex، batch، chip یا outlierها همخوانی دارند یا نه. heatmap ابزار exploratory است و به‌تنهایی differential expression یا methylation را ثابت نمی‌کند."],
  ]
};

function parseNums(text) { return String(text || "").split(/[\s,;]+/).map(Number).filter(Number.isFinite); }
function euclidean(a,b){ return Math.sqrt(a.reduce((s,x,i)=>s+(x-(b[i]??0))**2,0)); }
function manhattan(a,b){ return a.reduce((s,x,i)=>s+Math.abs(x-(b[i]??0)),0); }
function cheb(a,b){ return Math.max(...a.map((x,i)=>Math.abs(x-(b[i]??0))),0); }
function fmt(x,d=3){ return Number.isFinite(x) ? x.toFixed(d).replace(/\.0+$/,"") : "—"; }

export default function DRDLesson11({ lang = "es", isDone = false, toggle = () => {} }) {
  const ui = getUi(lang);
  const copy = COPY[lang] || COPY.en;
  const [zoom, setZoom] = useState(null);
  return <main className="mx-auto w-[min(1180px,calc(100%-24px))] pb-16 pt-6 text-stone-950">
    <Navigation ui={ui} isDone={isDone} toggle={toggle} />
    <section className="overflow-hidden rounded-[2.5rem] border border-stone-200 bg-white shadow-sm">
      <div className="grid lg:grid-cols-[1.08fr_0.92fr]">
        <div className="bg-[#fff8ee] p-8 md:p-12">
          <HeroEyebrow>{ui.heroEyebrow}</HeroEyebrow>
          <h1 className="mt-7 max-w-3xl text-5xl font-black leading-[0.94] tracking-[-0.06em] md:text-6xl lg:text-7xl">{ui.heroTitle}</h1>
          <p className="mt-7 max-w-3xl text-lg font-semibold leading-8 text-stone-700 md:text-xl">{ui.heroSubtitle}</p>
          <div className="mt-7 flex flex-wrap gap-2">{ui.tags.map((tag, i) => <Pill key={tag} tone={i === 1 ? "red" : "stone"}>{tag}</Pill>)}</div>
        </div>
        <aside className="border-t border-stone-200 bg-white p-8 lg:border-l lg:border-t-0">
          <div className="grid grid-cols-2 gap-3">
            <StatCard label={ui.module} value="1" tone="red" />
            <StatCard label={ui.writtenExam} value="4Q" />
            <StatCard label={ui.answerLines} value="10-12" />
            <StatCard label={ui.core} value="DIST" tone="red" />
          </div>
          <div className="mt-5 rounded-3xl bg-stone-950 p-6 text-white"><div className="text-xs font-black uppercase tracking-[0.2em] text-red-200">{ui.bigIdea}</div><p className="mt-3 text-lg font-black leading-7">{ui.bigIdeaText}</p></div>
          <ResourceLinks ui={ui} />
        </aside>
      </div>
    </section>

    <section className="mt-8 grid gap-6">
      {copy.sections.map((section, idx) => <FlowBlock key={section.title} ui={ui} section={section} idx={idx} setZoom={setZoom} />)}
    </section>

    <section className="mt-10 rounded-[2.5rem] border border-stone-200 bg-white/90 p-6 shadow-sm md:p-8">
      <SectionHeader eyebrow={ui.lab} title={copy.labs.pearsonTitle}>{copy.labs.pearsonBody}</SectionHeader>
      <div className="grid gap-5 lg:grid-cols-3">
        <PearsonLab lab={copy.labs} />
        <VectorDistanceLab lab={copy.labs} />
        <LinkageLab lab={copy.labs} />
      </div>
    </section>

    <WrittenTrainer ui={ui} copy={copy} />
    <Navigation ui={ui} isDone={isDone} toggle={toggle} position="bottom" />
    {zoom ? <ZoomModal ui={ui} slide={zoom} onClose={() => setZoom(null)} /> : null}
  </main>;
}

function Navigation({ ui, isDone, toggle, position = "top" }) { return <nav className={`${position === "bottom" ? "mt-10" : "mb-6"} rounded-[2rem] border border-stone-200 bg-white/85 p-3 shadow-sm`} aria-label="Lesson navigation"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><a href="#/lesson/m1-deg-ii" className="rounded-full border border-stone-200 bg-stone-50 px-4 py-2 text-sm font-black text-stone-700 transition hover:-translate-y-0.5 hover:bg-white hover:shadow-md">← {ui.previous}: {ui.previousTitle}</a><div className="flex flex-col items-stretch gap-2 sm:flex-row sm:items-center sm:justify-center"><a href="#/" className="rounded-full border border-stone-200 bg-white px-4 py-2 text-center text-xs font-black uppercase tracking-[0.2em] text-stone-500 transition hover:bg-stone-50">{ui.current} · {ui.dashboard}</a><button onClick={toggle} className={`rounded-full px-4 py-2 text-sm font-black shadow-sm transition hover:-translate-y-0.5 ${isDone ? "bg-emerald-600 text-white" : "bg-stone-950 text-white"}`}>{isDone ? ui.done : ui.mark}</button></div><a href="#/lesson/m1-samples-genes-ii" className="rounded-full bg-stone-950 px-4 py-2 text-sm font-black text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-red-700 hover:shadow-md">{ui.next}: {ui.nextTitle} →</a></div></nav>; }
function HeroEyebrow({ children }) { return <div className="inline-flex rounded-full border border-red-200 bg-red-50 px-4 py-2 text-xs font-black uppercase tracking-[0.22em] text-red-700">{children}</div>; }
function Pill({ children, tone = "stone" }) { const cls = tone === "red" ? "border-red-200 bg-red-50 text-red-700" : "border-stone-200 bg-white/80 text-stone-700"; return <span className={`rounded-full border px-3 py-1 text-xs font-black uppercase tracking-[0.16em] ${cls}`}>{children}</span>; }
function StatCard({ label, value, tone = "stone" }) { return <div className={`rounded-2xl border p-4 ${tone === "red" ? "border-red-200 bg-red-50" : "border-stone-200 bg-stone-50"}`}><div className="text-xs font-black uppercase tracking-[0.2em] text-stone-500">{label}</div><div className="mt-2 text-2xl font-black text-stone-950">{value}</div></div>; }
function ResourceLinks({ ui }) { const linkBase = "rounded-2xl border px-4 py-3 text-sm font-black transition hover:-translate-y-0.5 hover:shadow-sm"; return <div className="mt-4 rounded-3xl border border-stone-200 bg-stone-50 p-4"><div className="mb-3 text-xs font-black uppercase tracking-[0.18em] text-stone-500">{ui.resources}</div><div className="grid gap-2 sm:grid-cols-3"><a href={SLIDES_URL} target="_blank" rel="noreferrer" className={`${linkBase} border-red-200 bg-red-50 text-red-800 hover:bg-white`}>{ui.slides}</a><a href={TRANSCRIPT_URL} target="_blank" rel="noreferrer" className={`${linkBase} border-stone-200 bg-white text-stone-800 hover:bg-stone-50`}>{ui.transcript}</a><a href={RECORDING_URL} target="_blank" rel="noreferrer" className={`${linkBase} border-stone-800 bg-stone-950 text-white hover:bg-red-700`}>{ui.recording}</a></div></div>; }
function SectionHeader({ eyebrow, title, children }) { return <div className="mb-6"><div className="text-xs font-black uppercase tracking-[0.22em] text-red-700">{eyebrow}</div><h2 className="mt-2 text-3xl font-black tracking-tight text-stone-950 md:text-4xl">{title}</h2>{children ? <p className="mt-3 max-w-4xl text-base font-semibold leading-7 text-stone-600">{children}</p> : null}</div>; }
function NoteBox({ ui, type, children }) { const isExam = type === "exam"; return <div className={`mt-4 rounded-2xl border p-4 ${isExam ? "border-red-200 bg-red-50" : "border-amber-200 bg-amber-50"}`}><div className={`text-xs font-black uppercase tracking-[0.2em] ${isExam ? "text-red-700" : "text-amber-800"}`}>{isExam ? ui.exam : ui.professor}</div><div className="mt-2 text-sm font-bold leading-6 text-stone-800">{children}</div></div>; }

function FlowBlock({ ui, section, idx, setZoom }) {
  const full = idx % 3 === 0;
  return <article className="rounded-[2.5rem] border border-stone-200 bg-white/90 p-5 shadow-sm md:p-6">
    <SectionHeader eyebrow={section.eyebrow} title={section.title}>{section.body}</SectionHeader>
    <div className={`grid gap-5 ${full ? "lg:grid-cols-1" : "lg:grid-cols-2"}`}>
      {section.slides.map(slide => <SlideTextCard key={slide.n + slide.t} ui={ui} slide={slide} setZoom={setZoom} wide={full || section.slides.length % 2 === 1 && section.slides.length === 1} />)}
    </div>
    <NoteBox ui={ui}>{section.emphasis}</NoteBox>
    <ExamWatch ui={ui} exam={section.exam} />
  </article>;
}
function SlideTextCard({ ui, slide, setZoom }) { return <button onClick={() => setZoom(slide)} className="group rounded-[2rem] border border-stone-200 bg-[#fffaf0] p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="rounded-[1.4rem] border border-stone-200 bg-white p-5"><div className="inline-flex rounded-full border border-red-200 bg-red-50 px-3 py-1 text-xs font-black text-red-700">{ui.slide} {slide.n}</div><h3 className="mt-4 text-2xl font-black tracking-tight text-stone-950">{slide.t}</h3><p className="mt-3 text-sm font-bold leading-6 text-stone-700">{slide.text}</p><div className="mt-4 text-xs font-black uppercase tracking-[0.18em] text-stone-400">{ui.zoom}</div></div></button>; }
function ZoomModal({ ui, slide, onClose }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-stone-950/75 p-4" onClick={onClose}><div className="w-[min(900px,95vw)] rounded-[2rem] border border-white/20 bg-white p-6 shadow-2xl" onClick={e => e.stopPropagation()}><div className="flex items-center justify-between gap-4"><div className="inline-flex rounded-full border border-red-200 bg-red-50 px-3 py-1 text-xs font-black text-red-700">{ui.slide} {slide.n}</div><button onClick={onClose} className="rounded-full bg-stone-950 px-4 py-2 text-sm font-black text-white">{ui.close}</button></div><h3 className="mt-5 text-4xl font-black tracking-tight text-stone-950">{slide.t}</h3><p className="mt-4 text-lg font-bold leading-8 text-stone-700">{slide.text}</p><a href={SLIDES_URL} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-full border border-red-200 bg-red-50 px-5 py-3 text-sm font-black text-red-700">{ui.slides} ↗</a></div></div>; }
function ExamWatch({ ui, exam }) { const [open, setOpen] = useState(false); return <div className="mt-5 rounded-[2rem] border border-red-200 bg-red-50 p-5"><div className="text-xs font-black uppercase tracking-[0.22em] text-red-700">{ui.exam}</div><p className="mt-2 text-base font-black leading-7 text-stone-900">{exam.q}</p><button onClick={() => setOpen(!open)} className="mt-4 rounded-2xl border border-red-200 bg-white px-4 py-3 text-sm font-black text-red-800 shadow-sm">{open ? ui.hide : ui.expand}</button>{open ? <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_1.2fr]"><div className="rounded-2xl border border-red-100 bg-white p-4"><div className="text-xs font-black uppercase tracking-[0.2em] text-stone-500">{ui.include}</div><ul className="mt-3 space-y-2 text-sm font-bold leading-6 text-stone-700">{exam.include.map(item => <li key={item}>• {item}</li>)}</ul><div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="text-xs font-black uppercase tracking-[0.2em] text-amber-800">{ui.trap}</div><p className="mt-2 text-sm font-black leading-6 text-stone-800">{exam.trap}</p></div></div><div className="rounded-2xl border border-stone-200 bg-white p-4"><div className="text-xs font-black uppercase tracking-[0.2em] text-stone-500">{ui.model}</div><p className="mt-3 text-sm font-black leading-7 text-stone-900">{exam.sample}</p></div></div> : null}</div>; }

function PearsonLab({ lab }) { const [r,setR] = useState(0.97); const dist = 1 - Math.abs(Number(r)); const label = dist < 0.1 ? lab.near : dist < 0.6 ? lab.mid : lab.far; return <div className="rounded-[2rem] border border-stone-200 bg-white p-5 shadow-sm"><h3 className="text-xl font-black">{lab.pearsonTitle}</h3><p className="mt-2 text-sm font-semibold leading-6 text-stone-600">{lab.pearsonBody}</p><label className="mt-4 block text-xs font-black uppercase tracking-[0.18em] text-stone-500">{lab.r}</label><input type="range" min="-1" max="1" step="0.01" value={r} onChange={e=>setR(e.target.value)} className="mt-3 w-full"/><div className="mt-4 grid grid-cols-2 gap-3"><StatCard label={lab.r} value={fmt(Number(r),2)} /><StatCard label={lab.distance} value={fmt(dist,2)} tone="red" /></div><div className="mt-4 rounded-2xl bg-stone-950 p-4 text-white"><div className="text-xs font-black uppercase tracking-[0.2em] text-red-200">{lab.interpretation}</div><div className="mt-2 text-2xl font-black">{label}</div></div></div>; }
function VectorDistanceLab({ lab }) { const [a,setA] = useState("2, 5, 8, 10"); const [b,setB] = useState("3, 5, 6, 13"); const va=parseNums(a); const vb=parseNums(b); const n=Math.min(va.length,vb.length); const aa=va.slice(0,n), bb=vb.slice(0,n); return <div className="rounded-[2rem] border border-stone-200 bg-white p-5 shadow-sm"><h3 className="text-xl font-black">{lab.vectorsTitle}</h3><p className="mt-2 text-sm font-semibold leading-6 text-stone-600">{lab.vectorsBody}</p><label className="mt-4 block text-xs font-black uppercase tracking-[0.18em] text-stone-500">{lab.profileA}</label><input value={a} onChange={e=>setA(e.target.value)} className="mt-2 w-full rounded-2xl border border-stone-200 px-4 py-3 text-sm font-bold outline-none focus:border-red-300"/><label className="mt-3 block text-xs font-black uppercase tracking-[0.18em] text-stone-500">{lab.profileB}</label><input value={b} onChange={e=>setB(e.target.value)} className="mt-2 w-full rounded-2xl border border-stone-200 px-4 py-3 text-sm font-bold outline-none focus:border-red-300"/><div className="mt-4 grid gap-2"><StatCard label={lab.euclid} value={fmt(euclidean(aa,bb),2)} tone="red"/><StatCard label={lab.manhattan} value={fmt(manhattan(aa,bb),2)}/><StatCard label={lab.cheb} value={fmt(cheb(aa,bb),2)}/></div></div>; }
function LinkageLab({ lab }) { const questions = useMemo(() => [{q:"closest objects between clusters", a:lab.single}, {q:"furthest objects between clusters", a:lab.complete}, {q:"mean of all pairwise cluster distances", a:lab.average}], [lab]); const [ans,setAns]=useState({}); return <div className="rounded-[2rem] border border-stone-200 bg-white p-5 shadow-sm"><h3 className="text-xl font-black">{lab.linkageTitle}</h3><p className="mt-2 text-sm font-semibold leading-6 text-stone-600">{lab.linkageBody}</p><div className="mt-4 space-y-3">{questions.map((item,idx)=><div key={item.q} className="rounded-2xl border border-stone-200 bg-stone-50 p-3"><div className="text-sm font-black text-stone-900">{item.q}</div><div className="mt-3 flex flex-wrap gap-2">{[lab.single,lab.complete,lab.average].map(opt=><button key={opt} onClick={()=>setAns({...ans,[idx]:opt})} className={`rounded-full border px-3 py-1 text-xs font-black ${ans[idx]===opt ? (opt===item.a ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-red-300 bg-red-50 text-red-800") : "border-stone-200 bg-white text-stone-700"}`}>{opt}</button>)}</div>{ans[idx] ? <div className="mt-2 text-xs font-black uppercase tracking-[0.14em] text-stone-500">{ans[idx] === item.a ? lab.correct : lab.wrong}</div> : null}</div>)}</div></div>; }

function WrittenTrainer({ ui, copy }) { const [open,setOpen]=useState({}); const [answers,setAnswers]=useState({}); return <section className="mt-10 rounded-[2.5rem] border border-stone-200 bg-white/90 p-6 shadow-sm md:p-8"><SectionHeader eyebrow={ui.written} title={ui.written}>{copy.trainerIntro}</SectionHeader><div className="grid gap-5">{copy.questions.map(([q,a],idx)=><div key={q} className="rounded-[2rem] border border-stone-200 bg-stone-50 p-5"><h3 className="text-xl font-black text-stone-950">{idx+1}. {q}</h3><label className="mt-4 block text-xs font-black uppercase tracking-[0.18em] text-stone-500">{ui.yourAnswer}</label><textarea value={answers[idx] || ""} onChange={e=>setAnswers({...answers,[idx]:e.target.value})} className="mt-2 min-h-32 w-full rounded-2xl border border-stone-200 bg-white p-4 text-sm font-semibold leading-6 outline-none focus:border-red-300"/><button onClick={()=>setOpen({...open,[idx]:!open[idx]})} className="mt-3 rounded-full bg-stone-950 px-4 py-2 text-sm font-black text-white">{open[idx] ? ui.hide : ui.reveal}</button>{open[idx] ? <div className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4"><div className="text-xs font-black uppercase tracking-[0.2em] text-red-700">{ui.model}</div><p className="mt-2 text-sm font-black leading-7 text-stone-900">{a}</p></div> : null}</div>)}</div></section>; }
