import React, { useMemo, useState } from "react";
import slide01 from "../../assets/drd/lesson11/slide-01.jpg";
import slide02 from "../../assets/drd/lesson11/slide-02.jpg";
import slide03 from "../../assets/drd/lesson11/slide-03.jpg";
import slide04 from "../../assets/drd/lesson11/slide-04.jpg";
import slide05 from "../../assets/drd/lesson11/slide-05.jpg";
import slide06 from "../../assets/drd/lesson11/slide-06.jpg";
import slide07 from "../../assets/drd/lesson11/slide-07.jpg";
import slide08 from "../../assets/drd/lesson11/slide-08.jpg";
import slide09 from "../../assets/drd/lesson11/slide-09.jpg";
import slide10 from "../../assets/drd/lesson11/slide-10.jpg";
import slide11 from "../../assets/drd/lesson11/slide-11.jpg";
import slide12 from "../../assets/drd/lesson11/slide-12.jpg";
import slide13 from "../../assets/drd/lesson11/slide-13.jpg";
import slide14 from "../../assets/drd/lesson11/slide-14.jpg";
import slide15 from "../../assets/drd/lesson11/slide-15.jpg";
import slide16 from "../../assets/drd/lesson11/slide-16.jpg";
import slide17 from "../../assets/drd/lesson11/slide-17.jpg";
import slide18 from "../../assets/drd/lesson11/slide-18.jpg";
import slide19 from "../../assets/drd/lesson11/slide-19.jpg";
import slide20 from "../../assets/drd/lesson11/slide-20.jpg";
import slide21 from "../../assets/drd/lesson11/slide-21.jpg";
import slide22 from "../../assets/drd/lesson11/slide-22.jpg";
import slide23 from "../../assets/drd/lesson11/slide-23.jpg";
import slide24 from "../../assets/drd/lesson11/slide-24.jpg";
import slide25 from "../../assets/drd/lesson11/slide-25.jpg";
import slide26 from "../../assets/drd/lesson11/slide-26.jpg";
import slide27 from "../../assets/drd/lesson11/slide-27.jpg";
import slide28 from "../../assets/drd/lesson11/slide-28.jpg";
import slide29 from "../../assets/drd/lesson11/slide-29.jpg";
import slide30 from "../../assets/drd/lesson11/slide-30.jpg";
import slide31 from "../../assets/drd/lesson11/slide-31.jpg";
import slide32 from "../../assets/drd/lesson11/slide-32.jpg";
import slide33 from "../../assets/drd/lesson11/slide-33.jpg";
import slide34 from "../../assets/drd/lesson11/slide-34.jpg";
import slide35 from "../../assets/drd/lesson11/slide-35.jpg";
import slide36 from "../../assets/drd/lesson11/slide-36.jpg";
import slide37 from "../../assets/drd/lesson11/slide-37.jpg";
import slide38 from "../../assets/drd/lesson11/slide-38.jpg";
import slide39 from "../../assets/drd/lesson11/slide-39.jpg";
import slide40 from "../../assets/drd/lesson11/slide-40.jpg";
import slide41 from "../../assets/drd/lesson11/slide-41.jpg";
import slide42 from "../../assets/drd/lesson11/slide-42.jpg";
import slide43 from "../../assets/drd/lesson11/slide-43.jpg";
import slide44 from "../../assets/drd/lesson11/slide-44.jpg";
import slide45 from "../../assets/drd/lesson11/slide-45.jpg";
import slide46 from "../../assets/drd/lesson11/slide-46.jpg";
import slide47 from "../../assets/drd/lesson11/slide-47.jpg";
import slide48 from "../../assets/drd/lesson11/slide-48.jpg";
import slide49 from "../../assets/drd/lesson11/slide-49.jpg";
import slide50 from "../../assets/drd/lesson11/slide-50.jpg";
import slide51 from "../../assets/drd/lesson11/slide-51.jpg";
import slide52 from "../../assets/drd/lesson11/slide-52.jpg";
import slide53 from "../../assets/drd/lesson11/slide-53.jpg";
import slide54 from "../../assets/drd/lesson11/slide-54.jpg";
import slide55 from "../../assets/drd/lesson11/slide-55.jpg";
import slide56 from "../../assets/drd/lesson11/slide-56.jpg";
import slide57 from "../../assets/drd/lesson11/slide-57.jpg";
import slide58 from "../../assets/drd/lesson11/slide-58.jpg";
import slide59 from "../../assets/drd/lesson11/slide-59.jpg";

const SLIDES_URL = "https://drive.google.com/file/d/1JSN_XP7mF2r39TUzdiSOMW2Rum5Ij7ya/view?usp=drivesdk";
const TRANSCRIPT_URL = "https://docs.google.com/document/d/13Wu08yLvUaTITj3PmAC8yupFHzC6g8_zXbmVaGxAsUA/edit?usp=drivesdk";
const RECORDING_URL = "https://www.youtube.com/watch?v=YjqoFPQxKJU&list=PLZSGWjLWZL3KQFkSCUbUXWEVHeF0MTYZV&index=12";

const IMG = { s01: { src: slide01, slide: 1 }, s02: { src: slide02, slide: 2 }, s03: { src: slide03, slide: 3 }, s04: { src: slide04, slide: 4 }, s05: { src: slide05, slide: 5 }, s06: { src: slide06, slide: 6 }, s07: { src: slide07, slide: 7 }, s08: { src: slide08, slide: 8 }, s09: { src: slide09, slide: 9 }, s10: { src: slide10, slide: 10 }, s11: { src: slide11, slide: 11 }, s12: { src: slide12, slide: 12 }, s13: { src: slide13, slide: 13 }, s14: { src: slide14, slide: 14 }, s15: { src: slide15, slide: 15 }, s16: { src: slide16, slide: 16 }, s17: { src: slide17, slide: 17 }, s18: { src: slide18, slide: 18 }, s19: { src: slide19, slide: 19 }, s20: { src: slide20, slide: 20 }, s21: { src: slide21, slide: 21 }, s22: { src: slide22, slide: 22 }, s23: { src: slide23, slide: 23 }, s24: { src: slide24, slide: 24 }, s25: { src: slide25, slide: 25 }, s26: { src: slide26, slide: 26 }, s27: { src: slide27, slide: 27 }, s28: { src: slide28, slide: 28 }, s29: { src: slide29, slide: 29 }, s30: { src: slide30, slide: 30 }, s31: { src: slide31, slide: 31 }, s32: { src: slide32, slide: 32 }, s33: { src: slide33, slide: 33 }, s34: { src: slide34, slide: 34 }, s35: { src: slide35, slide: 35 }, s36: { src: slide36, slide: 36 }, s37: { src: slide37, slide: 37 }, s38: { src: slide38, slide: 38 }, s39: { src: slide39, slide: 39 }, s40: { src: slide40, slide: 40 }, s41: { src: slide41, slide: 41 }, s42: { src: slide42, slide: 42 }, s43: { src: slide43, slide: 43 }, s44: { src: slide44, slide: 44 }, s45: { src: slide45, slide: 45 }, s46: { src: slide46, slide: 46 }, s47: { src: slide47, slide: 47 }, s48: { src: slide48, slide: 48 }, s49: { src: slide49, slide: 49 }, s50: { src: slide50, slide: 50 }, s51: { src: slide51, slide: 51 }, s52: { src: slide52, slide: 52 }, s53: { src: slide53, slide: 53 }, s54: { src: slide54, slide: 54 }, s55: { src: slide55, slide: 55 }, s56: { src: slide56, slide: 56 }, s57: { src: slide57, slide: 57 }, s58: { src: slide58, slide: 58 }, s59: { src: slide59, slide: 59 } };

const UI = {
  es: {
    current: "M1.7", dashboard: "Dashboard DRD", previous: "Anterior", next: "Siguiente", previousTitle: "M1.6 DE genes II", nextTitle: "M1.8 Samples and genes II",
    mark: "Marcar completada", done: "Completada", resources: "Recursos de clase", slides: "Slides", transcript: "Transcripción", recording: "Grabación", slide: "Diapo", zoom: "Clic para ampliar", close: "Cerrar zoom",
    professor: "Énfasis de la profesora", exam: "Ojo para examen", expand: "Abrir respuesta desarrollada", include: "Qué incluir", trap: "Trampa frecuente", model: "Respuesta modelo", checkpoint: "Checkpoint",
    words: "palabras", module: "Módulo", writtenExam: "Examen escrito", answerLines: "Líneas", core: "Idea clave", bigIdea: "Idea central",
    heroEyebrow: "Módulo 1 · 5 de junio · Relationship between genes/samples I",
    heroTitle: "Relaciones entre genes, muestras, distancias y clusters",
    heroSubtitle: "Lección guiada por las slides reales y la transcripción de clase: matriz genes × muestras, análisis no supervisado, Pearson, Spearman, distancia Euclídea, MDS, clustering jerárquico, bootstrap validation y heatmaps.",
    tags: ["matrix", "distance", "Pearson", "Spearman", "MDS", "clustering", "heatmap"],
    bigIdeaText: "Después de normalizar y hacer tests diferenciales, el dataset sigue siendo una matriz. Aquí aprendemos a dejar que los datos se organicen para revelar qué genes, CpGs o muestras son similares o disimilares."
  },
  en: {
    current: "M1.7", dashboard: "DRD dashboard", previous: "Previous", next: "Next", previousTitle: "M1.6 DE genes II", nextTitle: "M1.8 Samples and genes II",
    mark: "Mark completed", done: "Completed", resources: "Class resources", slides: "Slides", transcript: "Transcript", recording: "Recording", slide: "Slide", zoom: "Click to zoom", close: "Close zoom",
    professor: "Professor emphasis", exam: "Exam watch", expand: "Open expanded answer", include: "What to include", trap: "Common trap", model: "Sample answer", checkpoint: "Checkpoint",
    words: "words", module: "Module", writtenExam: "Written test", answerLines: "Answer lines", core: "Core idea", bigIdea: "Big idea",
    heroEyebrow: "Module 1 · June 5 · Relationship between genes/samples I",
    heroTitle: "Relationships among genes, samples, distances and clusters",
    heroSubtitle: "A lesson guided by the real slides and class transcript: gene × sample matrices, unsupervised analysis, Pearson, Spearman, Euclidean distance, MDS, hierarchical clustering, bootstrap validation and heatmaps.",
    tags: ["matrix", "distance", "Pearson", "Spearman", "MDS", "clustering", "heatmap"],
    bigIdeaText: "After normalization and differential testing, the dataset is still a matrix. Here we let the data organize itself to reveal which genes, CpGs or samples are similar or dissimilar."
  },
  fa: {
    current: "M1.7", dashboard: "داشبورد DRD", previous: "قبلی", next: "بعدی", previousTitle: "M1.6 DE genes II", nextTitle: "M1.8 Samples and genes II",
    mark: "علامت‌گذاری کامل", done: "کامل شد", resources: "منابع کلاس", slides: "اسلایدها", transcript: "رونوشت", recording: "ضبط", slide: "اسلاید", zoom: "برای بزرگ‌نمایی کلیک کنید", close: "بستن بزرگ‌نمایی",
    professor: "تأکید استاد", exam: "نکته امتحان", expand: "باز کردن پاسخ کامل", include: "چه چیزهایی بیاوریم", trap: "اشتباه رایج", model: "پاسخ نمونه", checkpoint: "چک‌پوینت",
    words: "کلمه", module: "ماژول", writtenExam: "آزمون کتبی", answerLines: "خط پاسخ", core: "ایده اصلی", bigIdea: "ایده مرکزی",
    heroEyebrow: "Module 1 · June 5 · Relationship between genes/samples I",
    heroTitle: "Relationships among genes, samples, distances and clusters",
    heroSubtitle: "A slide-guided lesson on unsupervised analysis, distance metrics, MDS, hierarchical clustering, bootstrap validation and heatmaps.",
    tags: ["matrix", "distance", "Pearson", "Spearman", "MDS", "clustering", "heatmap"],
    bigIdeaText: "After normalization and differential testing, the dataset is still a matrix; now we ask how genes or samples organize by similarity."
  }
};
function getUi(lang = "es") { return UI[lang] || UI.es; }

const COPY = {
  es: {
    sections: [
      {
        title: "1. De una matriz a relaciones entre perfiles",
        intro: "La clase cambia el foco: ya no miramos solo si un gen es significativo, sino cómo se organiza internamente todo el dataset. La profesora insiste en que esto es análisis no supervisado y visualización.",
        lab: "matrix",
        slides: [
          { img: "s01", title: "Objetivo de la clase", body: "La primera slide define el objetivo: entender características y relaciones intrínsecas dentro de los datos mediante análisis no supervisado y visualización.", professor: "La idea es dejar que el dataset muestre estructura antes de imponer una interpretación biológica.", exam: { q: "¿Qué significa análisis no supervisado en esta clase?", include: ["No parte de grupos definidos a priori", "Busca estructura interna", "Sirve para genes, CpGs o muestras"], trap: "No lo presentes como un test de expresión diferencial; es exploratorio." } },
          { img: "s02", title: "Pipeline general de análisis", body: "La slide separa matriz, procesamiento y estadística; dentro de estadística aparecen técnicas descriptivas/exploratorias para definir similitud o distancia.", professor: "La profesora lo conecta con las clases anteriores: tras normalizar y testar, también hay que mirar la forma global del dataset.", exam: { q: "¿Dónde entra clustering dentro del pipeline?", include: ["Después de construir y procesar la matriz", "Como técnica exploratoria", "Para visualizar similitud/diferencia"], trap: "No lo confundas con normalización." } },
          { img: "s03", title: "La misma matriz tiene dos lecturas", body: "La matriz m muestras × n genes se puede leer por filas para comparar genes o por columnas para comparar muestras.", professor: "En la transcripción, la profesora aclara una duda: las variables pueden ser genes o muestras; lo importante es decir qué perfil se compara.", exam: { q: "¿Qué cambia al comparar genes o muestras?", include: ["Genes: perfil a través de muestras", "Muestras: perfil a través de genes", "Cambia la interpretación biológica"], trap: "No mezcles filas y columnas sin especificarlo." } },
          { img: "s04", title: "Pairwise genes vs pairwise samples", body: "Dos genes pueden compararse usando todas las muestras; dos muestras pueden compararse usando todos los genes.", professor: "La palabra clave es profile: un gen o una muestra se vuelven vectores de valores cuantitativos.", exam: { q: "¿Qué representa cada punto en un gráfico gene-gene?", include: ["Una muestra/paciente", "Coordenadas dadas por dos genes", "Permite evaluar similitud entre perfiles génicos"], trap: "No digas que cada punto es un gen en ese tipo de gráfico." } }
        ]
      },
      {
        title: "2. Similitud expresada como distancia",
        intro: "Para que los algoritmos trabajen, la idea cualitativa de parecido se transforma en números: distancias. Cerca significa similar; lejos significa disimilar, siempre según la métrica elegida.",
        lab: "distance",
        slides: [
          { img: "s05", title: "Propiedades geométricas de la distancia", body: "La distancia no puede ser negativa, la distancia de un perfil consigo mismo es cero y la distancia debe ser simétrica.", professor: "No se trata de memorizar geometría, sino de entender por qué luego podemos construir mapas y dendrogramas.", exam: { q: "¿Qué significa distancia baja?", include: ["Alta similitud", "Perfiles próximos", "Depende de la métrica"], trap: "No digas que distancia baja siempre significa causalidad o mismo mecanismo." } },
          { img: "s06", title: "Inequidad triangular", body: "La slide muestra que si las distancias se igualan, los puntos están en línea recta; esto introduce la lógica geométrica detrás de las métricas.", professor: "Esta parte prepara la intuición para MDS: convertir distancias entre perfiles en posiciones visualizables.", exam: { q: "¿Por qué importa pensar geométricamente?", include: ["Los perfiles se tratan como puntos", "Las distancias permiten mapearlos", "Los algoritmos usan proximidad"], trap: "No hace falta derivar el teorema; explica su rol conceptual." } }
        ]
      },
      {
        title: "3. Pearson: correlación lineal convertida en distancia",
        intro: "Pearson mide relación lineal entre dos perfiles. En esta clase se convierte en distancia usando d = 1 - |r|, por eso correlaciones fuertes positivas o negativas pueden quedar cerca.",
        lab: "pearson",
        slides: [
          { img: "s07", title: "Coeficiente de Pearson r", body: "Pearson cuantifica la relación lineal entre dos variables: r = +1 fuerte positiva, r = -1 fuerte negativa y r = 0 no correlación.", professor: "La profesora remarca: correlación no implica causalidad. Solo describe relación entre perfiles.", exam: { q: "¿Qué mide Pearson?", include: ["Relación lineal", "Entre dos perfiles/variables", "No causalidad"], trap: "No escribas que Pearson demuestra que un gen regula al otro." } },
          { img: "s08", title: "De correlación a distancia", body: "La distancia usada es d = 1 - |r|. Si r = +1 o -1, d = 0; si r = 0, d = 1.", professor: "Este detalle explica por qué perfiles opuestos pueden quedar juntos con distancia de correlación.", exam: { q: "Si r = -1, ¿cuál es d y qué significa?", include: ["d = 0", "Correlación perfecta negativa", "Cerca según distancia de correlación"], trap: "No pongas d = 2; se usa valor absoluto." } },
          { img: "s09", title: "Dataset DLBCL", body: "La clase usa arrays competitivos two-colour en pacientes con diffuse large B-cell lymphoma como ejemplo histórico.", professor: "Este ejemplo conecta M1.7 con las plataformas ya estudiadas: datos de expresión normalizados y centrados.", exam: { q: "¿Por qué reaparecen los arrays competitivos?", include: ["El dataset original usa two-colour arrays", "Los valores son log I/reference", "Sirven para perfiles de expresión"], trap: "No lo conviertas en una pregunta de tecnología; aquí se usa para análisis de perfiles." } },
          { img: "s10", title: "IGKC vs NKG7: correlación fuerte", body: "Cada punto es un paciente. r = 0.97 indica correlación fuerte y d = 0.03 indica distancia muy baja.", professor: "El ejemplo es perfecto para examen: mirar genes a través de muestras.", exam: { q: "Interpreta r = 0.97 y d = 0.03.", include: ["Correlación positiva fuerte", "Distancia baja", "Perfiles muy similares entre pacientes"], trap: "No digas que IGKC causa NKG7." } },
          { img: "s11", title: "Significancia de r", body: "La significancia de Pearson puede evaluarse con Student t usando n - 2 grados de libertad.", professor: "La profesora lo menciona para conectar con estadística previa: incluso correlaciones pueden tener p-value.", exam: { q: "¿Puede Pearson tener p-value?", include: ["Sí", "Se usa t de Student", "df = n - 2"], trap: "No confundas el p-value de Pearson con distancia." } },
          { img: "s12", title: "Pearson y outliers", body: "La slide muestra correlación débil o nula y advierte que r puede sesgarse por outliers.", professor: "Este es el puente hacia Spearman: si hay outliers, Pearson puede no ser la mejor métrica.", exam: { q: "¿Cuál es una limitación de Pearson?", include: ["Asume linealidad", "Es sensible a outliers", "Debe interpretarse con el plot"], trap: "No uses Pearson automáticamente en todos los datasets." } }
        ]
      },
      {
        title: "4. Time series: Spearman y Euclidean distance",
        intro: "La clase compara un dataset de sporulation en budding yeast. El diseño temporal muestra por qué la métrica debe elegirse según el experimento: outliers, dirección up/down y scaling importan.",
        lab: "metric",
        slides: [
          { img: "s13", title: "Dataset de sporulation", body: "Chu et al. siguieron expresión génica en levadura a 30 min, 2, 5, 7, 9 y 11 horas usando arrays competitivos.", professor: "La profesora recalca que un time series permite seguir el mismo sistema biológico a lo largo del tiempo.", exam: { q: "¿Por qué un time series es especial?", include: ["Tiene orden temporal", "Importa la tendencia", "Up/down puede cambiar con el tiempo"], trap: "No trates los puntos como si fueran muestras independientes sin tiempo." } },
          { img: "s14", title: "Pearson afectado por un outlier", body: "ENB1 y NPR2 tienen r = 0.63 y d = 0.37, pero un punto extremo influye mucho en el resultado.", professor: "La profesora dice que borrar el primer punto haría subir mucho la correlación; los outliers afectan el resultado final.", exam: { q: "¿Qué problema muestra esta slide?", include: ["Outlier", "Pearson sensible", "La métrica puede engañar"], trap: "No concluyas solo mirando r sin ver la gráfica." } },
          { img: "s15", title: "Spearman usa rangos", body: "Spearman es no paramétrico, más robusto a outliers y reemplaza los valores por rangos.", professor: "La fortaleza de Spearman es la robustez; su costo es perder información de magnitud y dirección fina.", exam: { q: "¿Cuándo puede servir Spearman?", include: ["Outliers", "Datos rankeables", "Relación monotónica"], trap: "No digas que siempre es mejor por ser robusto." } },
          { img: "s16", title: "Problema de Spearman en time series", body: "Con rangos, rho = -0.09 y d = 0.91; la dirección up/down se pierde durante el ranking.", professor: "La profesora insiste: en time series con subidas y bajadas, Spearman puede no captar lo que biológicamente importa.", exam: { q: "¿Por qué Spearman puede fallar en time series?", include: ["Convierte a rangos", "Pierde dirección up/down", "Puede perder patrón temporal"], trap: "No interpretes rangos como valores de expresión reales." } },
          { img: "s17", title: "Significancia de Spearman", body: "Como Pearson, Spearman puede evaluarse con una distribución t con n - 2 grados de libertad.", professor: "La clase no pide memorizar el cálculo, pero sí entender que rho también puede evaluarse estadísticamente.", exam: { q: "¿Qué símbolo usa Spearman?", include: ["rho", "Correlación por rangos", "Puede tener p-value"], trap: "No lo llames r de Pearson." } },
          { img: "s18", title: "Distancia Euclídea", body: "La distancia Euclídea viene del teorema de Pitágoras y se extiende a más dimensiones sumando diferencias cuadradas.", professor: "La interpretación es muy intuitiva: número grande = perfiles más lejanos.", exam: { q: "¿Qué conserva Euclidean distance mejor?", include: ["Separación geométrica", "Magnitud de diferencias", "Dirección up/down si los datos están bien escalados"], trap: "No olvides que depende del scaling." } },
          { img: "s19", title: "Scaling cambia Euclidean distance", body: "En BUR6 e IDH1, la distancia pasa de 5.8 a 0.88 al escalar los datos.", professor: "La profesora remarca que la distancia Euclídea no es scale invariant: normalización y scaling importan muchísimo.", exam: { q: "¿Por qué escalar antes de Euclidean?", include: ["Evita que la magnitud domine", "Hace comparables perfiles", "Cambia la distancia final"], trap: "No compares distancias Euclídeas sin saber cómo se escalaron los datos." } },
          { img: "s20", title: "Diferentes datasets, mejor métrica distinta", body: "En DLBCL, Spearman puede ser mejor; en time series centrado, Euclidean puede representar mejor perfiles opuestos.", professor: "No existe una regla única: se comparan métricas y se interpreta según diseño y biología.", exam: { q: "¿Cuál es la regla práctica?", include: ["Mirar diseño", "Comparar métricas", "Justificar biológicamente"], trap: "No afirmes que Pearson/Spearman/Euclidean siempre es la mejor." } },
          { img: "s21", title: "Fortalezas y debilidades", body: "La tabla resume pros y contras: Pearson es potente pero sensible a outliers; Spearman es robusto pero pierde información; Euclidean es geométrica pero depende del scaling.", professor: "Esta tabla es material de respuesta escrita: compara métricas con ventajas y límites.", exam: { q: "Compara Pearson, Spearman y Euclidean.", include: ["Pearson: lineal y sensible a outliers", "Spearman: rangos y robustez", "Euclidean: geometría y scaling"], trap: "No listes nombres sin explicar cuándo usarlos." } }
        ]
      },
      {
        title: "5. MDS: visualizar distancias en menos dimensiones",
        intro: "MDS no es una métrica. Es un algoritmo que toma una matriz de distancias y coloca los perfiles en 2D o 3D intentando preservar esas distancias.",
        lab: "mds",
        slides: [
          { img: "s22", title: "Unsupervised analysis", body: "Las técnicas no supervisadas son exploratorias: dejan que los datos se organicen y luego se intenta encontrar significado biológico.", professor: "La profesora lo dijo de forma clara: primero se mira qué pasa sin assumptions, luego viene la interpretación biológica.", exam: { q: "¿Qué métodos no supervisados aparecen?", include: ["MDS", "Hierarchical clustering", "K-means", "PCA"], trap: "No digas que MDS es supervisado o que requiere etiquetas." } },
          { img: "s23", title: "Objetivo de MDS", body: "MDS mapea distancias de un espacio de alta dimensión a un espacio de menor dimensión con mínima pérdida de información.", professor: "La aclaración de clase: MDS es algoritmo, no métrica; usa distancias calculadas previamente.", exam: { q: "¿MDS es métrica o algoritmo?", include: ["Algoritmo", "Usa una matriz de distancias", "Busca representación 2D/3D"], trap: "No respondas que MDS calcula Pearson o Euclidean por sí mismo." } },
          { img: "s24", title: "Matriz triangular", body: "La matriz contiene distancias entre perfiles; los valores entre paréntesis son las distancias escaladas por MDS.", professor: "La profesora explicó que la diagonal sería cero y que solo se muestran distancias útiles.", exam: { q: "¿Por qué triangular?", include: ["La distancia A-B = B-A", "La diagonal es cero", "Evita repetir valores"], trap: "No interpretes la matriz como tabla de p-values." } },
          { img: "s25", title: "Mapas MDS con diferentes distancias", body: "Con Euclidean o correlation distance, los puntos pueden moverse; se interpreta la proximidad relativa, no el valor absoluto de los ejes.", professor: "La profesora recalca: no te preocupes por números negativos en los ejes; mira qué perfiles quedan cerca o lejos.", exam: { q: "¿Cómo se lee un MDS?", include: ["Cercanía = similitud", "Lejanía = disimilitud", "Ejes son dimensiones de visualización"], trap: "No des significado biológico directo a la coordenada x o y." } }
        ]
      },
      {
        title: "6. Hierarchical clustering: del perfil más cercano al dendrograma",
        intro: "El clustering jerárquico es aglomerativo o bottom-up. Empieza uniendo los perfiles más próximos y termina en un árbol binario o dendrograma.",
        lab: "linkage",
        slides: [
          { img: "s26", title: "Definición de hierarchical clustering", body: "Perfiles similares aparecen próximos y con ramas cortas; ramas largas indican mayor distancia.", professor: "La profesora dice que esta es una pregunta probable de examen: concepto, tarea y utilidad del algoritmo.", exam: { q: "¿Qué es hierarchical clustering?", include: ["Análisis no supervisado", "Agrupa genes o muestras por distancia", "Produce dendrograma"], trap: "No lo describas como un test paramétrico." } },
          { img: "s27", title: "Inicio del algoritmo", body: "La secuencia de slides muestra cómo el algoritmo empieza desde elementos individuales y va creando nodos internos.", professor: "El dendrograma no aparece mágicamente: se construye paso a paso desde las distancias más pequeñas.", exam: { q: "¿Qué une primero el algoritmo?", include: ["Los perfiles más cercanos", "La distancia más baja", "Genes o muestras según el análisis"], trap: "No digas que une por nombre de gen o por grupo conocido." } },
          { img: "s28", title: "Primeras uniones", body: "Los perfiles cercanos forman un primer cluster; después hay que recalcular distancias entre cluster nuevo y elementos restantes.", professor: "Aquí aparece la necesidad de elegir linkage: cómo medir la distancia entre clusters, no solo entre genes individuales.", exam: { q: "¿Por qué hace falta linkage?", include: ["Se forman clusters", "Hay que medir cluster vs cluster", "Diferentes reglas dan árboles distintos"], trap: "No confundas métrica con linkage." } },
          { img: "s29", title: "Construcción progresiva", body: "Cada nuevo nodo refleja una distancia de unión; a medida que se agregan elementos, las ramas suelen hacerse más largas.", professor: "La longitud de rama es información: no basta mirar solo quién queda al lado de quién.", exam: { q: "¿Cómo se interpreta una rama corta?", include: ["Alta proximidad", "Perfiles similares", "Unión temprana"], trap: "No ignores la escala del dendrograma." } },
          { img: "s30", title: "Nodos y clusters", body: "El árbol va acumulando nodos internos hasta conectar todos los perfiles.", professor: "La profesora menciona vocabulario básico: external nodes, internal nodes, n-1 nodos internos.", exam: { q: "Si hay n genes, ¿cuántos nodos internos?", include: ["n - 1", "En árbol binario", "Total nodes = 2n - 1"], trap: "No respondas n nodos internos." } },
          { img: "s31", title: "Dendrograma final", body: "El dendrograma resume similitud y disimilitud entre perfiles usando ramas y nodos.", professor: "Siempre hay que mirar la estructura y la longitud de las ramas para establecer proximidad.", exam: { q: "¿Qué aporta el dendrograma?", include: ["Visualiza clusters", "Muestra proximidad/distancia", "Sugiere patrones comunes"], trap: "No lo trates como conclusión biológica definitiva." } },
          { img: "s32", title: "Repetición del principio", body: "La serie de slides refuerza que clustering es una construcción iterativa basada en distancias.", professor: "La clase vuelve varias veces a la misma idea para que quede clara: distancia baja = unión temprana.", exam: { q: "¿Qué significa unión temprana?", include: ["Distancia baja", "Mayor similitud", "Cluster inicial"], trap: "No significa necesariamente función biológica idéntica." } },
          { img: "s33", title: "Algoritmo en 4 pasos", body: "Mirar la matriz, unir los más cercanos, recalcular distancia del nuevo cluster y repetir hasta conectar todo.", professor: "Este es el esquema que debes poder escribir en 10-12 líneas.", exam: { q: "Resume el algoritmo", include: ["Matriz de distancia", "Nearest entries", "Linkage/recalculation", "Dendrograma final"], trap: "No saltes el paso de recalcular distancias." } },
          { img: "s34", title: "Matriz triangular y primera unión", body: "En el ejemplo de 5 genes, CREME9 y RDHL tienen distancia 0.03 y se unen con rama corta.", professor: "La primera unión sale de la distancia mínima en la matriz.", exam: { q: "¿Qué indica distancia 0.03?", include: ["Genes muy cercanos", "Se unen primero", "Rama corta"], trap: "No interpretes 0.03 como p-value." } },
          { img: "s35", title: "Linkage methods", body: "Single usa distancia mínima, complete la máxima y average el promedio entre clusters.", professor: "Average linkage se presenta como una opción que suele funcionar bien en muchas aplicaciones.", exam: { q: "Compara single, complete y average linkage.", include: ["Single: nearest", "Complete: farthest", "Average: promedio pairwise"], trap: "No digas que linkage y distancia son lo mismo." } },
          { img: "s36", title: "Resumen de linkage", body: "Single puede causar chaining, complete evita chaining con clusters compactos, average es general-purpose y Ward minimiza incremento de varianza.", professor: "Chaining es una palabra clave de clase y de examen.", exam: { q: "¿Qué es chaining?", include: ["Elementos añadidos uno por uno", "Estructura poco clara", "Frecuente con single linkage"], trap: "No lo confundas con una buena cadena biológica." } },
          { img: "s37", title: "Average linkage en acción", body: "El algoritmo recalcula la distancia del cluster nuevo respecto a otros genes usando la media.", professor: "Una vez elegido un linkage, se mantiene durante toda la construcción del árbol.", exam: { q: "¿Qué pasa tras formar un cluster?", include: ["Se recalculan distancias", "Se usa el linkage elegido", "Se busca nueva distancia mínima"], trap: "No cambies de linkage a mitad del algoritmo." } },
          { img: "s38", title: "Cálculo con average linkage", body: "La slide muestra cómo se promedian distancias entre el cluster CREME9-RDHL y genes restantes.", professor: "No necesitas hacer todos los cálculos en examen, pero sí explicar la lógica.", exam: { q: "¿Qué calcula average linkage?", include: ["Promedio de distancias pairwise", "Entre clusters", "Divide por n1*n2"], trap: "No uses solo la distancia mínima." } },
          { img: "s39", title: "Matriz actualizada", body: "Después de cada unión, se actualiza la matriz triangular y se repite el proceso.", professor: "Esta slide refuerza que el dendrograma depende de decisiones previas: métrica y linkage.", exam: { q: "¿Por qué pueden cambiar los dendrogramas?", include: ["Métrica diferente", "Linkage diferente", "Matriz recalculada"], trap: "No digas que hay un único dendrograma verdadero." } },
          { img: "s40", title: "Ramas cortas = genes cercanos", body: "La slide resume una regla visual: cuanto más cercanos los genes, más cortas son las ramas.", professor: "Esta frase se puede usar casi literal en una respuesta escrita.", exam: { q: "Interpreta ramas cortas y largas.", include: ["Cortas = similitud", "Largas = disimilitud", "Depende de escala y métrica"], trap: "No ignores la longitud." } },
          { img: "s41", title: "Isomorfismos y nodos", body: "Árboles con la misma estructura pueden verse rotados; siempre mira longitudes de ramas y nodos.", professor: "El orden visual izquierda-derecha no siempre es lo importante; lo importante es la estructura del árbol.", exam: { q: "¿Qué revisar en un dendrograma?", include: ["Longitud de ramas", "Nodos internos", "Estructura de clusters"], trap: "No concluyas solo por la posición horizontal de una etiqueta." } }
        ]
      },
      {
        title: "7. Comparar métricas/linkage y validar clusters",
        intro: "La profesora usa los 15 genes de sporulation para mostrar que diferentes combinaciones producen dendrogramas distintos. La interpretación debe considerar artefactos y validación.",
        lab: "bootstrap",
        slides: [
          { img: "s42", title: "15 genes en time series", body: "El diseño permite reconocer clusters naturales: transcripts persistentes y transcripts transitorios.", professor: "Antes de mirar el dendrograma, la profesora pide observar visualmente las tendencias.", exam: { q: "¿Qué son clusters naturales aquí?", include: ["Persistentes", "Transitorios", "Patrones temporales visibles"], trap: "No todos los clusters salen de etiquetas previas; aquí sirven como intuición." } },
          { img: "s43", title: "Pearson + single linkage", body: "Single linkage genera chaining: un cluster grande se identifica, pero otros genes se añaden uno por uno.", professor: "Chaining debe evitarse cuando impide ver estructura clara.", exam: { q: "¿Qué problema muestra single linkage?", include: ["Chaining", "Genes añadidos de uno en uno", "Estructura débil"], trap: "No presentes chaining como resultado ideal." } },
          { img: "s44", title: "Complete vs average linkage", body: "Complete define dos clusters principales; average suele aplicarse mucho y separa persistentes y transitorios bastante bien.", professor: "La profesora comenta que Pearson + average linkage suele ser una primera combinación práctica.", exam: { q: "¿Por qué probar varias combinaciones?", include: ["Resultados distintos", "Visualizaciones distintas", "Se elige con criterio biológico y técnico"], trap: "No elijas la más bonita sin justificar." } },
          { img: "s45", title: "Spearman y Euclidean con average linkage", body: "Spearman puede producir muchas distancias cero y perder estructura fina; Euclidean puede dejar algunos genes muy lejos.", professor: "Mismo dataset, resultados diferentes: por eso la métrica se interpreta junto con el diseño.", exam: { q: "¿Qué problema puede tener Spearman en dendrogramas?", include: ["Distancia cero", "Pérdida de fine structure", "Efecto de ranks"], trap: "No ignores los artefactos de la métrica." } },
          { img: "s46", title: "Tres reglas para recordar", body: "Pearson/Spearman pueden acercar perfiles opuestos, Spearman puede producir d = 0 y Euclidean genera distancias mayores.", professor: "Esta slide es una checklist de examen para interpretar diferencias entre dendrogramas.", exam: { q: "¿Por qué Euclidean separa perfiles opuestos?", include: ["Conserva diferencia geométrica", "No usa valor absoluto de correlación", "Puede producir distancias grandes"], trap: "No confundas distancia de correlación con Euclidean distance." } },
          { img: "s47", title: "Take-home de clustering", body: "Clustering identifica genes o muestras relacionados, hay muchas variantes y los resultados deben validarse estadísticamente.", professor: "La profesora dice explícitamente que hierarchical clustering puede ser pregunta de examen.", exam: { q: "¿Qué debe incluir una respuesta sobre clustering?", include: ["Unsupervised", "Dendrograma", "Métrica + linkage", "Validación"], trap: "No lo cierres sin mencionar validación." } },
          { img: "s48", title: "Bootstrap validation", body: "Se generan datasets bootstrap, se repite clustering muchas veces y se calcula cuántas veces reaparece cada cluster.", professor: "Bootstrap pregunta si un nodo es estable y reproducible, no solo visualmente atractivo.", exam: { q: "¿Para qué sirve bootstrap validation?", include: ["Estabilidad", "Reproducibilidad", "Soporte de clusters"], trap: "No lo confundas con corrección por multiple testing." } },
          { img: "s49", title: "Bootstrap support", body: "95% es evidencia muy fuerte; 80-95% buena; 70-80% moderada; menos de 70% débil.", professor: "Si el soporte es bajo, hay que ser prudente o probar otra combinación métrica/linkage.", exam: { q: "Interpreta soporte bootstrap de 65%.", include: ["Soporte débil", "Cluster poco estable", "Conclusión prudente"], trap: "No lo llames fuerte porque supera 50%." } }
        ]
      },
      {
        title: "8. Heatmaps: dendrograma + patrón visual",
        intro: "El cierre de la clase conecta dendrogramas con heatmaps. El heatmap facilita ver patrones globales, pero la leyenda decide qué significan los colores.",
        lab: "zscore",
        slides: [
          { img: "s50", title: "Heat map", body: "Rows suelen ser genes y columns muestras. Los colores representan nivel relativo de expresión o estadísticas up/down.", professor: "La profesora insiste: mira siempre la leyenda; red/green pueden invertirse entre ejemplos.", exam: { q: "¿Qué hay que mirar en un heatmap?", include: ["Filas y columnas", "Leyenda", "Dendrograma", "Escala relativa"], trap: "No asumas que rojo siempre es up-regulation." } },
          { img: "s51", title: "Z-score conceptual", body: "El z-score indica cuántas desviaciones estándar está una observación por encima o por debajo de la media.", professor: "La clave es que se calcula para cada gen a través de las muestras.", exam: { q: "¿Qué mide un z-score en heatmap?", include: ["Desviaciones estándar", "Respecto a la media del gen", "Valor relativo"], trap: "No lo interpretes como expresión absoluta." } },
          { img: "s52", title: "Fórmula de z-score", body: "Zij = (xij - μi) / σi. Ejemplo: 10, 20, 30 da z = -1, 0, +1.", professor: "Esta es una mini-respuesta perfecta si te preguntan cómo se colorea un heatmap por z-score.", exam: { q: "Interpreta z = +1.", include: ["Por encima de la media del gen", "Una desviación estándar", "Relativo a ese gen"], trap: "No compares z-score entre genes como expresión absoluta." } },
          { img: "s53", title: "Ejemplo visual de heatmap", body: "La figura de clase combina dendrograma y colores para mostrar patrones de expresión en muchas muestras.", professor: "La visualización correcta es crucial para comunicar resultados de datasets grandes.", exam: { q: "¿Por qué asociar heatmap y dendrograma?", include: ["El dendrograma agrupa", "El color muestra patrón", "Juntos facilitan interpretación"], trap: "No uses solo colores sin ver clusters." } },
          { img: "s54", title: "Leyenda y fold change", body: "La clase muestra que los colores pueden representar fold change u otras escalas, no solo z-score.", professor: "La profesora advierte que debes leer la leyenda para saber qué significa cada color.", exam: { q: "¿Qué error común hay en heatmaps?", include: ["Ignorar leyenda", "Invertir up/down", "Creer que color = valor absoluto"], trap: "No traduzcas colores sin verificar escala." } },
          { img: "s55", title: "Fold change en heatmap", body: "El ejemplo histórico usa cambios de expresión para separar grandes grupos de muestras.", professor: "El heatmap ayuda a ver grupos y subgrupos en datasets grandes, pero hay que volver a los genes para interpretar biológicamente.", exam: { q: "¿Qué aporta el heatmap al paper?", include: ["Visualización compacta", "Patrones de grupos", "Comunicación clara"], trap: "No afirmes mecanismo sin mirar genes concretos." } },
          { img: "s56", title: "Modelos celulares del ejemplo", body: "DLBCL, FL, CLL, linfocitos activados/normales y líneas celulares permiten comparar perfiles patológicos y normales.", professor: "La profesora usa este ejemplo para mostrar que muestras patológicas pueden compartir perfiles con células B normales de origen relacionado.", exam: { q: "¿Por qué comparar con muestras normales?", include: ["Contexto biológico", "Origen celular", "Distinguir patología de fisiología"], trap: "No interpretes cluster cercano como identidad absoluta." } },
          { img: "s57", title: "Take-home final", body: "Cluster analysis identifica similitud/disimilitud y heatmap es relevante para visualizar; siempre hay que mirar la leyenda.", professor: "Esta es la frase final de la clase y resume qué debes recordar para examen.", exam: { q: "Resume el mensaje final de M1.7.", include: ["Clustering encuentra patrones", "Heatmap visualiza", "Leyenda es esencial"], trap: "No olvides mencionar similitud/disimilitud." } }
        ]
      }
    ],
    labs: {
      matrix: { title: "Mini-lab · ¿Qué dirección de la matriz estás leyendo?", intro: "Selecciona si la pregunta compara genes a través de muestras o muestras a través de genes.", genes: "Genes", samples: "Muestras", items: [
        { q: "¿IGKC y NKG7 se comportan parecido en 38 pacientes DLBCL?", a: "genes", why: "Comparas dos genes usando todos los pacientes como mediciones." },
        { q: "¿Las muestras 7 h y 9 h del time series son parecidas al considerar muchos transcritos?", a: "samples", why: "Comparas dos muestras/tiempos usando perfiles de muchos genes." },
        { q: "¿Qué transcritos muestran patrón persistente durante la sporulation?", a: "genes", why: "Agrupas genes por su comportamiento a lo largo del tiempo." }
      ] },
      distance: { title: "Mini-lab · Intuición de distancia", intro: "Marca qué afirmaciones son compatibles con una distancia útil.", trueLabel: "Verdadero", falseLabel: "Falso", correct: "Correcto", items: [
        { q: "La distancia de un perfil consigo mismo debe ser 0.", a: true, why: "Un perfil idéntico no debe estar separado de sí mismo." },
        { q: "Una distancia puede ser negativa si la correlación es negativa.", a: false, why: "La distancia nunca debe ser negativa; por eso d = 1 - |r| usa valor absoluto." },
        { q: "Distancia baja significa perfiles similares según la métrica elegida.", a: true, why: "Cerca/lejos siempre depende de la métrica." }
      ] },
      pearson: { title: "Mini-lab · Pearson r → distancia", intro: "Mueve r y observa d = 1 - |r|. Nota que +1 y -1 producen distancia 0.", r: "Pearson r", d: "Distancia d", meaning: "Interpretación" },
      metric: { title: "Mini-lab · Elegir métrica", intro: "Elige la métrica inicial más razonable para cada situación.", choose: "Elegir", items: [
        { q: "Hay un outlier grande y quieres una medida robusta de relación.", a: "Spearman", options: ["Pearson", "Spearman", "Euclidean"], why: "Spearman usa rangos y reduce la influencia de valores extremos." },
        { q: "En un time series, dos genes tienen perfiles opuestos y quieres que queden lejos.", a: "Euclidean", options: ["Pearson", "Spearman", "Euclidean"], why: "Euclidean puede preservar separación geométrica entre perfiles opuestos." },
        { q: "Perfiles normalizados parecen linealmente relacionados y no hay outliers fuertes.", a: "Pearson", options: ["Pearson", "Spearman", "Euclidean"], why: "Pearson es potente para relaciones lineales si los supuestos son razonables." }
      ] },
      mds: { title: "Mini-lab · MDS no es métrica", intro: "Cambia la matriz de distancia y observa que el mapa se reacomoda. Interpreta proximidad relativa, no los valores de los ejes.", euclidean: "Euclidean distance", correlation: "Correlation distance", note: "Lo importante es cerca/lejos entre puntos, no el nombre de los ejes." },
      linkage: { title: "Mini-lab · Linkage methods", intro: "Selecciona un linkage y revisa qué comportamiento puede producir.", methods: {
        single: { name: "Single / minimum", text: "Usa vecinos más cercanos. Puede capturar clusters alargados, pero puede causar chaining." },
        complete: { name: "Complete / maximum", text: "Usa los más lejanos. Tiende a clusters compactos y reduce chaining." },
        average: { name: "Average / UPGMA", text: "Promedia distancias pairwise. Es una opción general muy usada." },
        ward: { name: "Ward", text: "Une elementos minimizando el aumento de varianza; suele ir bien con datos Euclidean compactos." }
      } },
      bootstrap: { title: "Mini-lab · Bootstrap support", intro: "Calcula soporte = clusters recuperados / réplicas totales × 100.", total: "Réplicas totales", recovered: "Réplicas con el cluster", support: "Soporte", verdict: "Veredicto", strong: "Muy fuerte", good: "Bueno", moderate: "Moderado", weak: "Débil" },
      zscore: { title: "Mini-lab · Z-score de heatmap", intro: "Introduce valores de expresión de un gen a través de muestras. El z-score se calcula dentro de ese gen.", values: "Valores de expresión", mean: "Media", sd: "SD", z: "Z-scores" },
      quiz: { title: "Checkpoint final", score: "Puntaje", items: [
        { q: "MDS es mejor descrito como…", options: ["una corrección de p-values", "una métrica", "un algoritmo que mapea distancias", "un test pareado"], answer: 2 },
        { q: "Con d = 1 - |r|, si r = -1 entonces…", options: ["d = 2", "d = 1", "d = 0", "d = -1"], answer: 2 },
        { q: "El warning clásico de single linkage es…", options: ["heteroscedasticity", "chaining", "bisulfite failure", "FDR inflation"], answer: 1 },
        { q: "Los z-scores de heatmap son normalmente…", options: ["expresión absoluta", "valores relativos de cada gen a través de muestras", "raw CEL intensities", "bootstrap p-values"], answer: 1 },
        { q: "Spearman puede ser problemático en time series porque…", options: ["no tiene p-value", "usa rangos y puede perder dirección up/down", "solo funciona con dos muestras", "requiere methylation arrays"], answer: 1 }
      ] },
      written: { title: "Entrenador de examen escrito", prompt: "Responde en 10-12 líneas: Explica hierarchical clustering y heatmaps en datos transcriptómicos.", placeholder: "Escribe aquí tu respuesta…", model: "Hierarchical clustering es un método no supervisado para identificar similitud y disimilitud entre genes o muestras. Parte de una matriz de perfiles y calcula distancias pairwise con una métrica como Pearson, Spearman o Euclidean distance. El algoritmo es aglomerativo: une primero los perfiles más cercanos y después recalcula distancias entre clusters usando un linkage method, por ejemplo single, complete o average. El resultado es un dendrograma, donde ramas cortas indican perfiles similares y ramas largas mayor distancia. Como distintas métricas y linkages pueden producir árboles diferentes, se deben comparar alternativas y validar nodos importantes con bootstrap support. El heatmap se asocia al dendrograma para visualizar patrones de expresión en una matriz, usualmente genes en filas y muestras en columnas. Los colores representan valores relativos, por ejemplo z-scores o fold change, por lo que siempre hay que leer la leyenda antes de interpretar up/down regulation." }
    }
  }
};
COPY.en = COPY.es;
COPY.fa = COPY.es;
function getCopy(lang = "es") { return COPY[lang] || COPY.es; }

function parseNumbers(text) { return String(text).split(/[,;\s]+/).map((x) => Number(x.trim())).filter(Number.isFinite); }
function mean(xs) { return xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : NaN; }
function sd(xs) { const m = mean(xs); if (xs.length < 2 || !Number.isFinite(m)) return NaN; return Math.sqrt(xs.reduce((a, x) => a + (x - m) ** 2, 0) / (xs.length - 1)); }
function fmt(x, digits = 2) { return Number.isFinite(x) ? x.toFixed(digits).replace(/\.00$/, "") : "—"; }

function Navigation({ ui, isDone, toggle, position = "top" }) { return <nav className={`${position === "bottom" ? "mt-10" : "mb-6"} rounded-[2rem] border border-stone-200 bg-white/85 p-3 shadow-sm`} aria-label="Lesson navigation"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><a href="#/lesson/m1-deg-ii" className="rounded-full border border-stone-200 bg-stone-50 px-4 py-2 text-sm font-black text-stone-700 transition hover:-translate-y-0.5 hover:bg-white hover:shadow-md">← {ui.previous}: {ui.previousTitle}</a><div className="flex flex-col items-stretch gap-2 sm:flex-row sm:items-center sm:justify-center"><a href="#/" className="rounded-full border border-stone-200 bg-white px-4 py-2 text-center text-xs font-black uppercase tracking-[0.2em] text-stone-500 transition hover:bg-stone-50">{ui.current} · {ui.dashboard}</a><button onClick={toggle} className={`rounded-full px-4 py-2 text-sm font-black shadow-sm transition hover:-translate-y-0.5 ${isDone ? "bg-emerald-600 text-white" : "bg-stone-950 text-white"}`}>{isDone ? ui.done : ui.mark}</button></div><a href="#/lesson/m1-samples-genes-ii" className="rounded-full bg-stone-950 px-4 py-2 text-sm font-black text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-red-700 hover:shadow-md">{ui.next}: {ui.nextTitle} →</a></div></nav>; }
function HeroEyebrow({ children }) { return <div className="inline-flex rounded-full border border-red-200 bg-red-50 px-4 py-2 text-xs font-black uppercase tracking-[0.22em] text-red-700">{children}</div>; }
function Pill({ children, tone = "stone" }) { const cls = tone === "red" ? "border-red-200 bg-red-50 text-red-700" : "border-stone-200 bg-white/80 text-stone-700"; return <span className={`rounded-full border px-3 py-1 text-xs font-black uppercase tracking-[0.16em] ${cls}`}>{children}</span>; }
function StatCard({ label, value, tone = "stone" }) { return <div className={`rounded-2xl border p-4 ${tone === "red" ? "border-red-200 bg-red-50" : "border-stone-200 bg-stone-50"}`}><div className="text-xs font-black uppercase tracking-[0.2em] text-stone-500">{label}</div><div className="mt-2 text-2xl font-black text-stone-950">{value}</div></div>; }
function ResourceLinks({ ui }) { const linkBase = "rounded-2xl border px-4 py-3 text-sm font-black transition hover:-translate-y-0.5 hover:shadow-sm"; return <div className="mt-4 rounded-3xl border border-stone-200 bg-stone-50 p-4"><div className="mb-3 text-xs font-black uppercase tracking-[0.18em] text-stone-500">{ui.resources}</div><div className="grid gap-2 sm:grid-cols-3"><a href={SLIDES_URL} target="_blank" rel="noreferrer" className={`${linkBase} border-red-200 bg-red-50 text-red-800 hover:bg-white`}>{ui.slides}</a><a href={TRANSCRIPT_URL} target="_blank" rel="noreferrer" className={`${linkBase} border-stone-200 bg-white text-stone-800 hover:bg-stone-50`}>{ui.transcript}</a><a href={RECORDING_URL} target="_blank" rel="noreferrer" className={`${linkBase} border-stone-800 bg-stone-950 text-white hover:bg-red-700`}>{ui.recording}</a></div></div>; }
function SectionHeader({ eyebrow, title, children }) { return <div className="mb-6"><div className="text-xs font-black uppercase tracking-[0.22em] text-red-700">{eyebrow}</div><h2 className="mt-2 text-3xl font-black tracking-tight text-stone-950 md:text-4xl">{title}</h2>{children ? <p className="mt-3 max-w-4xl text-base font-semibold leading-7 text-stone-600">{children}</p> : null}</div>; }
function NoteBox({ ui, type, children }) { const isExam = type === "exam"; return <div className={`mt-4 rounded-2xl border p-4 ${isExam ? "border-red-200 bg-red-50" : "border-amber-200 bg-amber-50"}`}><div className={`text-xs font-black uppercase tracking-[0.2em] ${isExam ? "text-red-700" : "text-amber-800"}`}>{isExam ? ui.exam : ui.professor}</div><div className="mt-2 text-sm font-bold leading-6 text-stone-800">{children}</div></div>; }
function ExamWatch({ ui, data }) { if (!data) return null; const model = data.model || data.answer || ""; return <details className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4"><summary className="cursor-pointer text-sm font-black text-red-800">{ui.exam}: {data.q}</summary><div className="mt-4 rounded-2xl border border-red-100 bg-white p-4"><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">{ui.include}</div><ul className="mt-3 space-y-2 text-sm font-semibold leading-6 text-stone-700">{data.include.map((x) => <li key={x}>• {x}</li>)}</ul><div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="text-xs font-black uppercase tracking-[0.18em] text-amber-800">{ui.trap}</div><p className="mt-2 text-sm font-bold leading-6 text-amber-950">{data.trap}</p></div>{model ? <div className="mt-4 rounded-2xl border border-stone-200 bg-stone-50 p-4"><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">{ui.model}</div><p className="mt-2 text-sm font-bold leading-7 text-stone-800">{model}</p></div> : null}</div></details>; }
function SlideCard({ ui, item, openZoom, spanFull }) { const figure = IMG[item.img]; if (!figure) return null; return <article className={`overflow-hidden rounded-[2rem] border border-stone-200 bg-stone-50 shadow-sm ${spanFull ? "md:col-span-2" : ""}`}><button onClick={() => openZoom({ ...figure, title: item.title })} className="group block w-full border-b border-stone-200 bg-white p-3 text-left"><div className={`${spanFull ? "aspect-[16/9]" : "aspect-[4/3]"} overflow-hidden rounded-2xl bg-white`}><img src={figure.src} alt={item.title} loading="lazy" className="h-full w-full object-contain transition duration-300 group-hover:scale-[1.02]" /></div></button><div className="p-5"><div className="flex flex-wrap items-center gap-2"><Pill tone="red">{ui.slide} {figure.slide}</Pill><span className="text-xs font-black uppercase tracking-[0.16em] text-stone-400">{ui.zoom}</span></div><h3 className="mt-3 text-xl font-black text-stone-950">{item.title}</h3><p className="mt-2 text-sm font-semibold leading-6 text-stone-600">{item.body}</p>{(item.professor || item.emphasis) ? <NoteBox ui={ui}>{item.professor || item.emphasis}</NoteBox> : null}<ExamWatch ui={ui} data={item.exam}/></div></article>; }
function SlideGrid({ ui, slides, openZoom }) { return <div className="grid gap-5 md:grid-cols-2">{slides.map((item, idx) => <SlideCard key={`${item.img}-${idx}`} ui={ui} item={item} openZoom={openZoom} spanFull={slides.length % 2 === 1 && idx === slides.length - 1}/>)}</div>; }
function ZoomModal({ ui, zoom, setZoom }) { if (!zoom) return null; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-stone-950/80 p-4" onClick={() => setZoom(null)}><div className="max-h-[92vh] w-[min(1100px,96vw)] overflow-auto rounded-[2rem] bg-white p-4 shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="mb-3 flex items-center justify-between gap-3"><div><Pill tone="red">{ui.slide} {zoom.slide}</Pill><h3 className="mt-2 text-xl font-black text-stone-950">{zoom.title}</h3></div><button onClick={() => setZoom(null)} className="rounded-full bg-stone-950 px-4 py-2 text-sm font-black text-white">{ui.close}</button></div><img src={zoom.src} alt={zoom.title} className="max-h-[78vh] w-full rounded-2xl object-contain" /></div></div>; }
function InteractiveShell({ title, intro, children }) { return <div className="mt-6 rounded-[2rem] border border-stone-200 bg-stone-50 p-5"><h3 className="text-2xl font-black text-stone-950">{title}</h3><p className="mt-2 text-sm font-semibold leading-6 text-stone-600">{intro}</p><div className="mt-5">{children}</div></div>; }
function ResultPill({ label, value, tone = "stone" }) { return <div className={`rounded-2xl border p-4 ${tone === "red" ? "border-red-200 bg-red-50" : "border-stone-200 bg-white"}`}><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">{label}</div><div className="mt-1 text-xl font-black text-stone-950">{value}</div></div>; }
function DataBox({ label, value, onChange, rows = 3 }) { return <label className="text-sm font-black text-stone-700">{label}<textarea value={value} rows={rows} onChange={(e) => onChange(e.target.value)} className="mt-2 min-h-[90px] w-full rounded-2xl border border-stone-200 bg-white px-4 py-3 font-mono text-sm leading-6 outline-none focus:border-red-300"/></label>; }

function DirectionLab({ lab }) { const [answers, setAnswers] = useState({}); return <InteractiveShell title={lab.title} intro={lab.intro}><div className="grid gap-4 md:grid-cols-3">{lab.items.map((item, i) => { const ok = answers[i] === item.a; return <div key={item.q} className="rounded-2xl border border-stone-200 bg-white p-4"><p className="font-black leading-6 text-stone-900">{item.q}</p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={() => setAnswers({ ...answers, [i]: "genes" })} className={`rounded-xl border px-3 py-2 text-sm font-black ${answers[i] === "genes" ? (ok ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-red-300 bg-red-50 text-red-800") : "border-stone-200 bg-stone-50"}`}>{lab.genes}</button><button onClick={() => setAnswers({ ...answers, [i]: "samples" })} className={`rounded-xl border px-3 py-2 text-sm font-black ${answers[i] === "samples" ? (ok ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-red-300 bg-red-50 text-red-800") : "border-stone-200 bg-stone-50"}`}>{lab.samples}</button></div>{answers[i] ? <p className="mt-3 text-sm font-bold leading-6 text-stone-600">{item.why}</p> : null}</div>; })}</div></InteractiveShell>; }
function DistanceLab({ lab }) { const [answers, setAnswers] = useState({}); return <InteractiveShell title={lab.title} intro={lab.intro}><div className="grid gap-4 md:grid-cols-3">{lab.items.map((item, i) => { const ok = answers[i] === item.a; return <div key={item.q} className="rounded-2xl border border-stone-200 bg-white p-4"><p className="font-black leading-6 text-stone-900">{item.q}</p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={() => setAnswers({ ...answers, [i]: true })} className={`rounded-xl border px-3 py-2 text-sm font-black ${answers[i] === true ? (ok ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-red-300 bg-red-50 text-red-800") : "border-stone-200 bg-stone-50"}`}>{lab.trueLabel}</button><button onClick={() => setAnswers({ ...answers, [i]: false })} className={`rounded-xl border px-3 py-2 text-sm font-black ${answers[i] === false ? (ok ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-red-300 bg-red-50 text-red-800") : "border-stone-200 bg-stone-50"}`}>{lab.falseLabel}</button></div>{answers[i] !== undefined ? <p className="mt-3 text-sm font-bold leading-6 text-stone-600">{item.why}</p> : null}</div>; })}</div></InteractiveShell>; }
function PearsonLab({ lab }) { const [r, setR] = useState(0.97); const d = 1 - Math.abs(r); const abs = Math.abs(r); const meaning = abs > 0.8 ? "Relación fuerte; distancia baja." : abs > 0.5 ? "Relación moderada; revisa el plot." : "Relación débil o nula; distancia alta."; return <InteractiveShell title={lab.title} intro={lab.intro}><div className="grid gap-4 md:grid-cols-[1fr_1fr_1fr]"><label className="rounded-2xl border border-stone-200 bg-white p-4"><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">{lab.r}</div><input type="range" min="-1" max="1" step="0.01" value={r} onChange={(e) => setR(Number(e.target.value))} className="mt-4 w-full"/><div className="mt-2 text-2xl font-black text-stone-950">{fmt(r, 2)}</div></label><ResultPill label={lab.d} value={fmt(d, 2)} tone="red"/><div className="rounded-2xl border border-stone-200 bg-white p-4"><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">{lab.meaning}</div><p className="mt-2 text-sm font-bold leading-6 text-stone-700">{meaning}</p></div></div></InteractiveShell>; }
function MetricLab({ lab }) { const [answers, setAnswers] = useState({}); return <InteractiveShell title={lab.title} intro={lab.intro}><div className="grid gap-4 md:grid-cols-3">{lab.items.map((item, i) => <div key={item.q} className="rounded-2xl border border-stone-200 bg-white p-4"><p className="font-black leading-6 text-stone-900">{item.q}</p><div className="mt-3 grid gap-2">{item.options.map((op) => { const chosen = answers[i] === op; const ok = op === item.a; return <button key={op} onClick={() => setAnswers({ ...answers, [i]: op })} className={`rounded-xl border px-3 py-2 text-left text-sm font-black ${chosen ? (ok ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-red-300 bg-red-50 text-red-800") : "border-stone-200 bg-stone-50"}`}>{op}</button>; })}</div>{answers[i] ? <p className="mt-3 text-sm font-bold leading-6 text-stone-600">{item.why}</p> : null}</div>)}</div></InteractiveShell>; }
function MdsLab({ lab }) { const [metric, setMetric] = useState("euclidean"); const points = metric === "euclidean" ? [[15,80,"0.5h"],[30,22,"2h"],[58,14,"5h"],[78,32,"7h"],[82,62,"9h"],[90,86,"11h"]] : [[12,82,"0.5h"],[26,18,"2h"],[62,25,"5h"],[75,70,"7h"],[81,68,"9h"],[88,78,"11h"]]; return <InteractiveShell title={lab.title} intro={lab.intro}><div className="grid gap-4 lg:grid-cols-[0.75fr_1.25fr]"><div className="grid gap-2"><button onClick={() => setMetric("euclidean")} className={`rounded-2xl border px-4 py-3 text-left font-black ${metric === "euclidean" ? "border-red-200 bg-red-50 text-red-800" : "border-stone-200 bg-white"}`}>{lab.euclidean}</button><button onClick={() => setMetric("correlation")} className={`rounded-2xl border px-4 py-3 text-left font-black ${metric === "correlation" ? "border-red-200 bg-red-50 text-red-800" : "border-stone-200 bg-white"}`}>{lab.correlation}</button><p className="rounded-2xl bg-stone-950 p-4 text-sm font-black leading-6 text-white">{lab.note}</p></div><svg viewBox="0 0 100 100" className="min-h-[260px] rounded-[1.5rem] border border-stone-200 bg-white p-3"><line x1="8" y1="92" x2="95" y2="92" stroke="#d6d3d1"/><line x1="8" y1="8" x2="8" y2="92" stroke="#d6d3d1"/>{points.map(([x,y,label]) => <g key={label}><circle cx={x} cy={y} r="3.5" fill="#dc2626"/><text x={x + 3} y={y - 3} fontSize="5" fontWeight="700" fill="#292524">{label}</text></g>)}</svg></div></InteractiveShell>; }
function LinkageLab({ lab }) { const [method, setMethod] = useState("average"); const info = lab.methods[method]; return <InteractiveShell title={lab.title} intro={lab.intro}><div className="grid gap-4 md:grid-cols-[0.8fr_1.2fr]"><div className="grid gap-2">{Object.entries(lab.methods).map(([key, item]) => <button key={key} onClick={() => setMethod(key)} className={`rounded-2xl border px-4 py-3 text-left text-sm font-black ${method === key ? "border-red-200 bg-red-50 text-red-800" : "border-stone-200 bg-white text-stone-700"}`}>{item.name}</button>)}</div><div className="rounded-[1.5rem] bg-stone-950 p-6 text-white"><div className="text-xs font-black uppercase tracking-[0.18em] text-red-200">{info.name}</div><p className="mt-3 text-xl font-black leading-8">{info.text}</p></div></div></InteractiveShell>; }
function BootstrapLab({ lab }) { const [total, setTotal] = useState(1000); const [recovered, setRecovered] = useState(950); const support = Math.max(0, Math.min(100, (Number(recovered) / Math.max(1, Number(total))) * 100)); const verdict = support >= 95 ? lab.strong : support >= 80 ? lab.good : support >= 70 ? lab.moderate : lab.weak; return <InteractiveShell title={lab.title} intro={lab.intro}><div className="grid gap-4 md:grid-cols-4"><label className="text-sm font-black text-stone-700">{lab.total}<input type="number" value={total} onChange={(e) => setTotal(Number(e.target.value))} className="mt-2 w-full rounded-2xl border border-stone-200 bg-white px-4 py-3 font-black outline-none focus:border-red-300"/></label><label className="text-sm font-black text-stone-700">{lab.recovered}<input type="number" value={recovered} onChange={(e) => setRecovered(Number(e.target.value))} className="mt-2 w-full rounded-2xl border border-stone-200 bg-white px-4 py-3 font-black outline-none focus:border-red-300"/></label><ResultPill label={lab.support} value={`${fmt(support, 1)}%`} tone="red"/><ResultPill label={lab.verdict} value={verdict}/></div></InteractiveShell>; }
function ZScoreLab({ lab }) { const [values, setValues] = useState("10, 20, 30"); const xs = parseNumbers(values); const m = mean(xs); const s = sd(xs); const zs = xs.map((x) => Number.isFinite(s) && s > 0 ? (x - m) / s : NaN); return <InteractiveShell title={lab.title} intro={lab.intro}><div className="grid gap-4 md:grid-cols-[1fr_1fr]"><DataBox label={lab.values} value={values} onChange={setValues}/><div className="grid gap-3 sm:grid-cols-3"><ResultPill label={lab.mean} value={fmt(m, 2)}/><ResultPill label={lab.sd} value={fmt(s, 2)}/><ResultPill label={lab.z} value={zs.map((z) => fmt(z, 2)).join(", ")} tone="red"/></div></div></InteractiveShell>; }
function renderLab(name, copy) { const lab = copy.labs[name]; if (!lab) return null; if (name === "matrix") return <DirectionLab lab={lab}/>; if (name === "distance") return <DistanceLab lab={lab}/>; if (name === "pearson") return <PearsonLab lab={lab}/>; if (name === "metric") return <MetricLab lab={lab}/>; if (name === "mds") return <MdsLab lab={lab}/>; if (name === "linkage") return <LinkageLab lab={lab}/>; if (name === "bootstrap") return <BootstrapLab lab={lab}/>; if (name === "zscore") return <ZScoreLab lab={lab}/>; return null; }
function Quiz({ ui, copy }) { const items = copy.labs.quiz.items; const [answers, setAnswers] = useState({}); const score = items.reduce((acc, item, i) => acc + (answers[i] === item.answer ? 1 : 0), 0); return <section className="mt-10 rounded-[2rem] border border-stone-200 bg-white p-6 shadow-sm"><SectionHeader eyebrow={ui.checkpoint} title={copy.labs.quiz.title}>{copy.labs.quiz.score}: {score}/{items.length}</SectionHeader><div className="grid gap-4 md:grid-cols-2">{items.map((item, i) => <div key={item.q} className="rounded-2xl border border-stone-200 bg-stone-50 p-4"><p className="font-black text-stone-950">{i + 1}. {item.q}</p><div className="mt-3 grid gap-2">{item.options.map((option, j) => <button key={option} onClick={() => setAnswers({ ...answers, [i]: j })} className={`rounded-xl border px-3 py-2 text-left text-sm font-bold ${answers[i] === j ? (j === item.answer ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-red-300 bg-red-50 text-red-800") : "border-stone-200 bg-white text-stone-700"}`}>{option}</button>)}</div></div>)}</div></section>; }
function WrittenTrainer({ ui, copy }) { const lab = copy.labs.written; const [text, setText] = useState(""); const wc = text.trim() ? text.trim().split(/\s+/).length : 0; return <section className="mt-10 rounded-[2rem] border border-stone-200 bg-white p-6 shadow-sm"><SectionHeader eyebrow={ui.exam} title={lab.title}>{lab.prompt}</SectionHeader><textarea value={text} onChange={(e) => setText(e.target.value)} placeholder={lab.placeholder} className="min-h-[230px] w-full rounded-[1.5rem] border border-stone-200 bg-stone-50 p-4 text-sm font-semibold leading-6 outline-none focus:border-red-300"/><div className="mt-2 text-xs font-black uppercase tracking-[0.18em] text-stone-500">{wc} {ui.words}</div><details className="mt-4 rounded-[1.5rem] border border-stone-200 bg-stone-50 p-4"><summary className="cursor-pointer font-black text-red-800">{ui.model}</summary><p className="mt-3 text-sm font-semibold leading-7 text-stone-700">{lab.model}</p></details></section>; }

export default function DRDLesson11({ lang = "es", isDone = false, toggle = () => {} }) {
  const ui = getUi(lang);
  const copy = getCopy(lang);
  const [zoom, setZoom] = useState(null);
  const sections = useMemo(() => copy.sections, [copy]);
  return <main className="mx-auto w-[min(1180px,calc(100%-24px))] pb-16 pt-8 md:pt-12 text-stone-900"><Navigation ui={ui} isDone={isDone} toggle={toggle}/>
    <section className="overflow-hidden rounded-[2.5rem] border border-stone-200 bg-[#fffaf0]/92 shadow-xl shadow-stone-900/5"><div className="grid gap-0 lg:grid-cols-[1.05fr_0.95fr]"><div className="p-7 md:p-10 lg:p-12"><HeroEyebrow>{ui.heroEyebrow}</HeroEyebrow><h1 className="mt-5 max-w-4xl text-4xl font-black leading-[0.96] tracking-tight text-stone-950 md:text-6xl">{ui.heroTitle}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-stone-700">{ui.heroSubtitle}</p><div className="mt-6 flex flex-wrap gap-2">{ui.tags.map((tag) => <Pill key={tag} tone={tag === "MDS" || tag === "clustering" || tag === "heatmap" ? "red" : "stone"}>{tag}</Pill>)}</div></div><div className="border-t border-stone-200 bg-white/70 p-5 lg:border-l lg:border-t-0"><div className="h-full rounded-[2rem] border border-stone-200 bg-white p-5 shadow-inner"><div className="grid grid-cols-2 gap-3"><StatCard label={ui.module} value="1" tone="red"/><StatCard label={ui.writtenExam} value="4Q"/><StatCard label={ui.answerLines} value="10–12"/><StatCard label={ui.core} value="MDS/HC" tone="red"/></div><div className="mt-5 rounded-3xl bg-stone-950 p-5 text-white"><div className="text-xs font-black uppercase tracking-[0.18em] text-red-200">{ui.bigIdea}</div><p className="mt-2 text-lg font-bold leading-7">{ui.bigIdeaText}</p></div><ResourceLinks ui={ui}/></div></div></div></section>
    {sections.map((section, idx) => <section key={section.title} className="mt-10 rounded-[2.5rem] border border-stone-200 bg-white/80 p-6 shadow-sm md:p-8"><SectionHeader eyebrow={`Part ${idx + 1}`} title={section.title}>{section.intro}</SectionHeader><SlideGrid ui={ui} slides={section.slides} openZoom={setZoom}/>{renderLab(section.lab, copy)}</section>)}
    <Quiz ui={ui} copy={copy}/><WrittenTrainer ui={ui} copy={copy}/><Navigation ui={ui} isDone={isDone} toggle={toggle} position="bottom"/><ZoomModal ui={ui} zoom={zoom} setZoom={setZoom}/>
  </main>;
}
