import React, { useMemo, useState } from "react";
import dnaMethylation from "../../assets/drd/lesson08/01-dna-methylation.png";
import cpgContext from "../../assets/drd/lesson08/02-cpg-context.png";
import arrayFamily from "../../assets/drd/lesson08/03-array-family.png";
import bisulfiteLogic from "../../assets/drd/lesson08/04-bisulfite.png";
import infiniumChemistry from "../../assets/drd/lesson08/05-infinium-i-ii.png";
import manifestVisual from "../../assets/drd/lesson08/06-manifest.png";
import rImportVisual from "../../assets/drd/lesson08/07-r-import.png";
import filterPlotVisual from "../../assets/drd/lesson08/08-filter-plot.png";

const SLIDES_URL = "https://drive.google.com/file/d/1sN2mGi86239wfQ8w8K-PYtKeF4pWQXAR/view?usp=drivesdk";
const TRANSCRIPT_URL = "https://docs.google.com/document/d/1StKS_UrrCBaIIvwsyz-vhmfrFQoxWy5HiAo8JFN3kHs/edit?usp=drivesdk";
const CLASS_RECORDING_URL = "https://www.youtube.com/watch?v=prqxPH0DZ_s&list=PLZSGWjLWZL3KQFkSCUbUXWEVHeF0MTYZV&index=6";

const IMG = {
  dnaMethylation: { src: dnaMethylation, slide: 1 },
  cpgContext: { src: cpgContext, slide: 1 },
  arrayFamily: { src: arrayFamily, slide: 3 },
  bisulfiteLogic: { src: bisulfiteLogic, slide: 8 },
  infiniumChemistry: { src: infiniumChemistry, slide: 9 },
  manifestVisual: { src: manifestVisual, slide: 17 },
  rImportVisual: { src: rImportVisual, slide: "practical" },
  filterPlotVisual: { src: filterPlotVisual, slide: "practical" }
};

const COPY = {
  en: {
    mark: "Mark completed", done: "Completed", dashboard: "DRD dashboard", previous: "Previous", next: "Next", current: "M2.2", previousTitle: "M2.1 R/Bioconductor intro", nextTitle: "M2.3 Data import + QC",
    heroEyebrow: "Module 2 · May 13/14 · DNA methylation + manifest practice", heroTitle: "From methylation chemistry to manifest-file thinking", heroSubtitle: "A practical Module 2 lesson connecting Illumina Infinium chemistry, probe annotation and R exploration of the 450K manifest file.",
    flow: ["beta values", "CpG context", "bisulfite", "Infinium I/II", "manifest", "R filtering"], resources: "Class resources", slides: "Slides", transcript: "Transcript", recording: "Recording", open: "Open", zoom: "Click to zoom", close: "Close zoom", visualLabel: "Source slide", professor: "Professor emphasis", report: "Report watch", more: "Open expanded answer", include: "What to include", trap: "Common trap", model: "Sample report phrasing", checkpoint: "Checkpoint", selected: "Selected", correct: "Correct — that is the logic used in the practical.", wrong: "Not quite — check the lecture logic again.", lab: "Mini-lab", code: "R code", result: "Expected interpretation", quiz: "Quick checkpoint quiz", trainer: "Report paragraph trainer", placeholder: "Write your own report-style explanation here...", reveal: "Show model answer", hide: "Hide model answer"
  },
  es: {
    mark: "Marcar completada", done: "Completada", dashboard: "Panel DRD", previous: "Anterior", next: "Siguiente", current: "M2.2", previousTitle: "M2.1 Intro R/Bioconductor", nextTitle: "M2.3 Importación + QC",
    heroEyebrow: "Módulo 2 · 13/14 mayo · Metilación + práctica de manifest", heroTitle: "De la química de metilación al razonamiento con manifest files", heroSubtitle: "Una lección práctica del Módulo 2 que conecta química Illumina Infinium, anotación de probes y exploración en R del manifest 450K.",
    flow: ["beta values", "contexto CpG", "bisulfito", "Infinium I/II", "manifest", "filtrado en R"], resources: "Recursos de clase", slides: "Diapositivas", transcript: "Transcripción", recording: "Recording", open: "Abrir", zoom: "Click para ampliar", close: "Cerrar zoom", visualLabel: "Diapositiva fuente", professor: "Énfasis del profesor", report: "Report watch", more: "Abrir respuesta ampliada", include: "Qué incluir", trap: "Trampa común", model: "Frase modelo para el reporte", checkpoint: "Checkpoint", selected: "Seleccionado", correct: "Correcto — esa es la lógica usada en la práctica.", wrong: "No del todo — revisa la lógica de la clase.", lab: "Mini-lab", code: "Código R", result: "Interpretación esperada", quiz: "Quiz rápido", trainer: "Entrenador de párrafo para reporte", placeholder: "Escribe aquí tu explicación estilo reporte...", reveal: "Mostrar respuesta modelo", hide: "Ocultar respuesta modelo"
  },
  fa: {
    mark: "علامت‌گذاری به‌عنوان کامل", done: "کامل شد", dashboard: "داشبورد DRD", previous: "قبلی", next: "بعدی", current: "M2.2", previousTitle: "M2.1 مقدمه R/Bioconductor", nextTitle: "M2.3 ورود داده + QC",
    heroEyebrow: "ماژول ۲ · ۱۳/۱۴ مه · متیلاسیون + تمرین manifest", heroTitle: "از شیمی متیلاسیون تا فکر کردن با manifest file", heroSubtitle: "یک درس عملی از ماژول ۲ که شیمی Illumina Infinium، annotation پروب‌ها و بررسی manifest 450K در R را به هم وصل می‌کند.",
    flow: ["beta value", "CpG context", "bisulfite", "Infinium I/II", "manifest", "filtering در R"], resources: "منابع کلاس", slides: "اسلایدها", transcript: "رونوشت", recording: "Recording", open: "باز کردن", zoom: "برای بزرگ‌نمایی کلیک کن", close: "بستن بزرگ‌نمایی", visualLabel: "اسلاید منبع", professor: "تأکید استاد", report: "نکته برای گزارش", more: "باز کردن پاسخ کامل", include: "چه چیزهایی باید بیاید", trap: "دام رایج", model: "عبارت نمونه برای گزارش", checkpoint: "Checkpoint", selected: "انتخاب‌شده", correct: "درست — این همان منطق تمرین است.", wrong: "نه کاملاً — منطق کلاس را دوباره بررسی کن.", lab: "مینی‌لب", code: "کد R", result: "تفسیر مورد انتظار", quiz: "کوئیز سریع", trainer: "تمرین پاراگراف گزارش", placeholder: "توضیح خود را به سبک گزارش اینجا بنویسید...", reveal: "نمایش پاسخ نمونه", hide: "پنهان کردن پاسخ نمونه"
  }
};

const SECTIONS = {
  en: [
    { eyebrow: "1 · What is the measured variable?", title: "Methylation is binary per molecule, but continuous in a sample", body: "The lecture starts with biology, but quickly turns it into data logic: one CpG on one DNA molecule is methylated or unmethylated; a tissue extract is a pool of many molecules, so the measured value is an average methylation fraction.", professor: "He explicitly asks what type of data methylation is. The answer changes with scale: binary at the single-molecule level, percentage/beta value at the sample level.", report: { title: "Explain beta values biologically", include: ["State that beta values summarize a population of molecules.", "Explain why 50% can mean a mixture of methylated and unmethylated molecules, not one half-methylated molecule.", "Mention that beta values range from 0 to 1 or 0% to 100%."], trap: "Do not interpret beta as a direct single-cell genotype. It is an aggregate signal from DNA extracted from many cells.", model: "A beta value represents the fraction of DNA molecules methylated at a CpG locus in the analyzed sample. At the single-molecule level, a CpG is methylated or unmethylated, but tissue DNA is a pool from many cells and alleles. Therefore an intermediate beta value reflects mixed methylation states across molecules or cells." }, slides: [{ key: "dnaMethylation", title: "From molecule to beta value", body: "This slide logic is central for all downstream plots: beta is an average signal, not a direct observation of one molecule." }, { key: "cpgContext", title: "CpG islands, shores, shelves and open sea", body: "The manifest later uses this genomic vocabulary to annotate every probe." }] },
    { eyebrow: "2 · Illumina array family and bisulfite conversion", title: "The array measures a C-versus-T consequence of bisulfite treatment", body: "The core trick is to convert a methylation problem into a sequence/readout problem: unmethylated cytosines become U/T after bisulfite conversion and PCR, while methylated cytosines remain C. Illumina arrays exploit this difference with locus-specific probes.", professor: "He emphasizes that 450K remains useful for learning because it is computationally manageable and widely represented in public datasets, while EPIC/EPIC v2 extend coverage especially in regulatory and non-coding regions.", report: { title: "Report watch: platform choice", include: ["Define 27K, 450K, EPIC and EPIC v2 as generations with increasing CpG coverage.", "Explain that 450K is still useful for practice and public-data availability.", "Explain bisulfite conversion as the chemistry that creates C/T distinguishability."], trap: "Do not say the array directly sees a methyl group after PCR. The methylation information is preserved through bisulfite-driven sequence differences.", model: "Illumina methylation arrays measure methylation indirectly. Sodium bisulfite converts unmethylated cytosines into uracil, which becomes thymine after PCR, whereas methylated cytosines remain cytosine. The array then interrogates known CpG loci using probes designed around these C/T differences." }, slides: [{ key: "arrayFamily", title: "Infinium HumanMethylation family", body: "27K, 450K, EPIC v1 and EPIC v2 differ mainly in the number and genomic distribution of interrogated CpGs." }, { key: "bisulfiteLogic", title: "Bisulfite creates the readable difference", body: "The practical pipeline makes sense only after this conversion logic is clear." }] },
    { eyebrow: "3 · Infinium chemistry", title: "Infinium I and II differ in probe design, bead usage and colour meaning", body: "This is the conceptual heart of the lesson. Infinium I uses two bead types for the same CpG: one probe for the unmethylated version and one for the methylated version. Infinium II uses one bead type and one probe; red/green single-base extension indicates unmethylated or methylated signal.", professor: "A student question clarified a common confusion: the same chip contains both Infinium I and Infinium II probes. The whole array is not either type I or type II.", report: { title: "Report watch: compare Infinium I and II", include: ["Infinium I: two bead types / two probes / one colour channel per locus design.", "Infinium II: one bead type / one probe / two-colour readout.", "Explain why Type I is common in CpG-rich regions and Type II increases capacity."], trap: "For Infinium I, colour is not the methylation-state code in the same way as Infinium II. The address/bead identity tells you whether the signal comes from the M or U probe.", model: "Infinium I probes use two bead addresses for one CpG, one matching the unmethylated bisulfite-converted sequence and one matching the methylated sequence. Infinium II uses one bead address and detects methylated versus unmethylated molecules by the colour of the single-base extension. This allows higher array capacity, but probe design must handle nearby CpGs with degenerate bases." }, slides: [{ key: "infiniumChemistry", title: "Two chemistries on the same array", body: "The manifest encodes this as design type and address information, which becomes inspectable in R." }] },
    { eyebrow: "4 · Manifest file", title: "The manifest is the dictionary that connects probe IDs to biology", body: "The practical part loads the Illumina 450K manifest as a large table. It includes probe identifiers, addresses, design type, colour channel, chromosome, position, gene names and CpG island context. The lecture stresses that meaningful analysis depends on annotation.", professor: "He points out that proprietary software can read these files, but R lets you inspect, filter and understand them directly.", report: { title: "Report watch: why use the manifest?", include: ["Define manifest as probe-level design and annotation metadata.", "Mention IlmnID/cg IDs, AddressA/B, Infinium design type, chromosome, position and gene/context columns.", "Explain that control probes and unmapped rows are not interpreted as genomic CpG loci."], trap: "Do not treat every row as a biological CpG. Some rows are controls or non-CpG probes and must be filtered depending on the analysis.", model: "The manifest file links the array signal to genomic meaning. It tells which probe or bead address corresponds to each Illumina ID, whether the probe uses Infinium I or II chemistry, where it maps in the genome, and whether it belongs to CpG island, shore, shelf or open sea context. This annotation is required before interpreting methylation signals biologically." }, slides: [{ key: "manifestVisual", title: "Manifest columns drive interpretation", body: "The same table supports filtering, annotation and report-ready summaries." }] },
    { eyebrow: "5 · R practical workflow", title: "Load, clean, subset, count and plot the manifest", body: "The practical half reuses R skills from M2.1: object assignment, read functions, indexing, logical conditions, table(), data.frame(), order(), factor levels and barplot(). The new challenge is size: the manifest is large, so efficient formats such as RData/RDS are useful.", professor: "He repeatedly contrasts table() as a quick overview with subsetting as a way to create a new object. This distinction matters for report reproducibility.", report: { title: "Report watch: practical methods paragraph", include: ["State how the manifest was imported and why header lines were skipped.", "Describe removal of control/unmapped probes before genomic interpretation.", "Mention table() for frequency summaries and barplot() for visualization."], trap: "table() does not create a filtered dataset; it only summarizes. To keep selected probes, create a new object by subsetting.", model: "The manifest was imported into R after inspecting the initial file lines and skipping non-tabular metadata rows. The table was then cleaned by removing probes without chromosome annotation, which correspond to control or non-genomic probes. Exploratory functions such as dim(), head(), colnames() and table() were used to inspect the object, while logical subsetting created new manifest objects for specific genomic contexts or probe types." }, slides: [{ key: "rImportVisual", title: "Import and save large tables", body: "Use readLines to inspect the file, skip metadata rows, then save the cleaned object for faster reloading." }, { key: "filterPlotVisual", title: "Filter, count and plot", body: "The same manifest can answer questions about chromosome distribution, CpG context and Infinium design type." }] }
  ]
};
SECTIONS.es = SECTIONS.en.map(s => ({...s, eyebrow: s.eyebrow.replace('What is the measured variable?','¿Qué variable se mide?').replace('Illumina array family and bisulfite conversion','Familia Illumina y conversión con bisulfito').replace('Infinium chemistry','Química Infinium').replace('Manifest file','Manifest file').replace('R practical workflow','Workflow práctico en R'), title: ({"Methylation is binary per molecule, but continuous in a sample":"La metilación es binaria por molécula, pero continua en una muestra","The array measures a C-versus-T consequence of bisulfite treatment":"El array mide una consecuencia C-versus-T del tratamiento con bisulfito","Infinium I and II differ in probe design, bead usage and colour meaning":"Infinium I y II difieren en diseño de probe, uso de beads y significado del color","The manifest is the dictionary that connects probe IDs to biology":"El manifest es el diccionario que conecta probe IDs con biología","Load, clean, subset, count and plot the manifest":"Cargar, limpiar, filtrar, contar y graficar el manifest"}[s.title]||s.title)}));
SECTIONS.fa = SECTIONS.en.map(s => ({...s, title: s.title, body: s.body}));

function cx(...classes){ return classes.filter(Boolean).join(" "); }
function Pill({ children, tone="green" }) { const tones={green:"border-emerald-200 bg-emerald-50 text-emerald-800", red:"border-red-200 bg-red-50 text-red-700", dark:"border-stone-900 bg-stone-950 text-white"}; return <span className={cx("inline-flex rounded-full border px-3 py-1 text-xs font-black uppercase tracking-[0.14em]", tones[tone])}>{children}</span>; }
function TopNav({ copy, isDone, toggle }) { return <nav className="sticky top-0 z-50 border-b border-stone-200 bg-[#fffaf0]/90 backdrop-blur"><div className="mx-auto flex w-[min(1180px,calc(100%-24px))] flex-wrap items-center justify-between gap-2 py-3"><a href="#/lesson/m2-r" className="rounded-full border border-stone-200 bg-white px-4 py-2 text-sm font-black text-stone-800">← {copy.previous}: {copy.previousTitle}</a><a href="#/drd" className="rounded-full border border-stone-200 bg-white px-4 py-2 text-xs font-black uppercase tracking-[0.18em] text-stone-600">{copy.current} · {copy.dashboard}</a><button onClick={toggle} className={cx("rounded-full px-4 py-2 text-sm font-black", isDone ? "bg-emerald-600 text-white" : "bg-stone-950 text-white")}>{isDone ? copy.done : copy.mark}</button><a href="#/lesson/m2-import-qc" className="rounded-full bg-stone-950 px-4 py-2 text-sm font-black text-white">{copy.next}: {copy.nextTitle} →</a></div></nav>; }
function ResourceBox({ copy }) { const linkBase="rounded-2xl border px-4 py-3 text-center text-sm font-black transition"; return <div className="mt-4 rounded-3xl border border-stone-200 bg-stone-50 p-4"><div className="mb-3 text-xs font-black uppercase tracking-[0.18em] text-stone-500">{copy.resources}</div><div className="grid gap-2 sm:grid-cols-3"><a href={SLIDES_URL} target="_blank" rel="noreferrer" className={`${linkBase} border-emerald-200 bg-emerald-50 text-emerald-800 hover:bg-white`}>{copy.slides}</a><a href={TRANSCRIPT_URL} target="_blank" rel="noreferrer" className={`${linkBase} border-stone-200 bg-white text-stone-800 hover:bg-stone-50`}>{copy.transcript}</a><a href={CLASS_RECORDING_URL} target="_blank" rel="noreferrer" className={`${linkBase} border-stone-800 bg-stone-950 text-white hover:bg-emerald-700`}>{copy.recording}</a></div></div>; }
function Hero({ copy }) { return <section className="overflow-hidden rounded-[2.5rem] border border-stone-200 bg-[#fffaf0] shadow-xl"><div className="grid lg:grid-cols-[1.05fr_0.95fr]"><div className="p-8 md:p-12"><Pill tone="green">{copy.heroEyebrow}</Pill><h1 className="mt-6 text-4xl font-black leading-[0.96] tracking-tight text-stone-950 md:text-6xl">{copy.heroTitle}</h1><p className="mt-6 max-w-2xl text-lg font-semibold leading-8 text-stone-700">{copy.heroSubtitle}</p><div className="mt-6 flex flex-wrap gap-2">{copy.flow.map(tag => <Pill key={tag}>{tag}</Pill>)}</div></div><div className="border-t border-stone-200 bg-white/70 p-5 lg:border-l lg:border-t-0"><div className="rounded-[2rem] border border-stone-200 bg-white p-5 shadow-inner"><div className="grid grid-cols-2 gap-3"><HeroStat label="MODULE" value="2"/><HeroStat label="REPORT" value="10+"/><HeroStat label="CORE" value="MANIFEST"/><HeroStat label="DATA" value="450K"/></div><div className="mt-5 rounded-[1.6rem] bg-stone-950 p-5 text-white"><div className="text-xs font-black uppercase tracking-[0.18em] text-emerald-200">BIG IDEA</div><p className="mt-2 text-lg font-black leading-7">Manifest files turn Illumina probe signals into interpretable genomic features. Without probe design and annotation, beta values are numbers without biological coordinates.</p></div><ResourceBox copy={copy}/></div></div></div></section>; }
function HeroStat({ label, value }) { return <div className="rounded-2xl border border-stone-200 bg-stone-50 p-4"><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">{label}</div><div className="mt-2 text-2xl font-black text-stone-950">{value}</div></div>; }
function ProfessorEmphasis({ copy, children }) { if(!children) return null; return <div className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="text-xs font-black uppercase tracking-[0.18em] text-emerald-800">{copy.professor}</div><p className="mt-2 text-sm font-bold leading-6 text-emerald-950">{children}</p></div>; }
function ReportWatch({ report, copy }) { if(!report) return null; return <details className="mt-4 rounded-2xl border border-emerald-200 bg-white p-4"><summary className="cursor-pointer text-sm font-black text-emerald-900">{copy.report}: {report.title}</summary><div className="mt-4 space-y-3"><div><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">{copy.include}</div><ul className="mt-2 list-disc space-y-1 pl-5 text-sm font-semibold leading-6 text-stone-700">{report.include.map(item => <li key={item}>{item}</li>)}</ul></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-3"><div className="text-xs font-black uppercase tracking-[0.18em] text-amber-700">{copy.trap}</div><p className="mt-1 text-sm font-bold leading-6 text-amber-950">{report.trap}</p></div><div className="rounded-2xl border border-stone-200 bg-stone-50 p-3"><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">{copy.model}</div><p className="mt-1 text-sm font-bold leading-6 text-stone-800">{report.model}</p></div></div></details>; }
function SlideCard({ slide, image, copy, onZoom, isFull, professor, report }) { return <article className={cx("overflow-hidden rounded-[2rem] border border-stone-200 bg-stone-50 shadow-sm", isFull && "lg:col-span-2 lg:grid lg:grid-cols-[0.95fr_1.05fr]")}><button type="button" onClick={() => onZoom({ ...slide, ...image })} className={cx("group relative block w-full cursor-zoom-in border-b border-stone-200 bg-white p-3 text-left", isFull && "lg:border-b-0 lg:border-r")}><div className={cx("aspect-[4/3] w-full overflow-hidden rounded-2xl bg-white", isFull && "lg:aspect-auto lg:h-full")}><img src={image.src} alt={slide.title} loading="lazy" className="h-full w-full object-contain transition duration-300 group-hover:scale-[1.02]" /></div><span className="pointer-events-none absolute bottom-6 right-6 rounded-full border border-stone-200 bg-white/95 px-3 py-1 text-[11px] font-black uppercase tracking-[0.16em] text-stone-700 shadow-sm">{copy.zoom}</span></button><div className="p-5"><Pill>{copy.visualLabel} · Slide {image.slide}</Pill><h3 className="mt-3 text-xl font-black text-stone-950">{slide.title}</h3><p className="mt-2 text-sm font-semibold leading-6 text-stone-600">{slide.body}</p><ProfessorEmphasis copy={copy}>{professor}</ProfessorEmphasis><ReportWatch report={report} copy={copy}/></div></article>; }
function SlideGrid({ slides, copy, onZoom, professor, report }) { return <div className="mt-6 grid gap-4 lg:grid-cols-2">{slides.map((slide, idx) => { const image = IMG[slide.key]; const isFull = slides.length % 2 === 1 && idx === slides.length - 1; return <SlideCard key={slide.key} slide={slide} image={image} copy={copy} onZoom={onZoom} isFull={isFull} professor={professor} report={report}/>; })}</div>; }
function SectionBlock({ section, copy, onZoom }) { return <section className="mt-10 rounded-[2.5rem] border border-stone-200 bg-white/80 p-6 shadow-sm md:p-8"><div><Pill>{section.eyebrow}</Pill><h2 className="mt-4 text-3xl font-black tracking-tight text-stone-950 md:text-4xl">{section.title}</h2><p className="mt-3 max-w-4xl text-base font-semibold leading-8 text-stone-600">{section.body}</p></div><SlideGrid slides={section.slides} copy={copy} onZoom={onZoom} professor={section.professor} report={section.report}/></section>; }
function OptionLab({ copy }) { const [selected, setSelected] = useState(null); const items=[{q:"A probe row has AddressA and AddressB",a:"Infinium I",why:"Two addresses indicate two bead types: U and M."},{q:"A probe has one bead address and can be read in red or green",a:"Infinium II",why:"One probe plus two-colour single-base extension."},{q:"CHR column is empty before filtering",a:"Control/unmapped",why:"These rows should not be interpreted as genomic CpGs."},{q:"Relation_to_UCSC_CpG_Island is empty after cleaning",a:"Open sea",why:"After removing controls, an empty island-context field indicates outside island/shore/shelf."}]; return <section className="mt-10 rounded-[2.5rem] border border-stone-200 bg-white/80 p-6 shadow-sm md:p-8"><Pill>{copy.lab}</Pill><h2 className="mt-4 text-3xl font-black text-stone-950">Manifest interpretation sorter</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{items.map((it,idx)=><div key={it.q} className="rounded-3xl border border-stone-200 bg-stone-50 p-4"><div className="font-black text-stone-900">{it.q}</div><div className="mt-3 flex flex-wrap gap-2">{["Infinium I","Infinium II","Control/unmapped","Open sea"].map(opt=><button key={opt} onClick={()=>setSelected(`${idx}-${opt}`)} className={cx("rounded-full border px-3 py-2 text-xs font-black", selected===`${idx}-${opt}` ? (opt===it.a?"border-emerald-300 bg-emerald-100 text-emerald-900":"border-red-300 bg-red-100 text-red-900") : "border-stone-200 bg-white text-stone-700")}>{opt}</button>)}</div>{selected?.startsWith(`${idx}-`) && <p className="mt-3 text-sm font-bold leading-6 text-stone-700">{selected===`${idx}-${it.a}` ? copy.correct : copy.wrong} {it.why}</p>}</div>)}</div></section>; }
function CodeWalkthrough({ copy }) { const [mode, setMode] = useState("skip"); const snippets={skip:{code:'manifest <- read.table(file, sep = ",", header = TRUE, skip = 7)\ndim(manifest)', result:'Use skip when the first lines are metadata and not part of the rectangular table.'}, filter:{code:'manifest.clean <- manifest[manifest$CHR != "", ]\nmanifest.clean$CHR <- droplevels(manifest.clean$CHR)\ndim(manifest.clean)', result:'Rows without chromosome annotation are removed before genomic interpretation.'}, table:{code:'table(manifest.clean$Infinium_Design_Type,\n      manifest.clean$Relation_to_UCSC_CpG_Island)', result:'A two-way table summarizes how Infinium I/II probes distribute across CpG contexts.'}, plot:{code:'chr.counts <- table(manifest.clean$CHR)\nbarplot(chr.counts)', result:'barplot gives a quick distribution check; factor levels may need reordering for chromosome order.'}}; const s=snippets[mode]; return <section className="mt-10 rounded-[2.5rem] border border-stone-200 bg-white/80 p-6 shadow-sm md:p-8"><Pill>{copy.lab}</Pill><h2 className="mt-4 text-3xl font-black text-stone-950">R manifest walkthrough</h2><div className="mt-5 flex flex-wrap gap-2">{Object.keys(snippets).map(k=><button key={k} onClick={()=>setMode(k)} className={cx("rounded-full border px-4 py-2 text-sm font-black", mode===k?"border-emerald-300 bg-emerald-100 text-emerald-900":"border-stone-200 bg-white text-stone-800")}>{k}</button>)}</div><div className="mt-6 grid gap-4 lg:grid-cols-2"><div className="rounded-3xl bg-stone-950 p-5 text-white"><div className="text-xs font-black uppercase tracking-[0.18em] text-emerald-200">{copy.code}</div><pre className="mt-3 whitespace-pre-wrap text-sm font-bold leading-7"><code>{s.code}</code></pre></div><div className="rounded-3xl border border-stone-200 bg-stone-50 p-5"><div className="text-xs font-black uppercase tracking-[0.18em] text-stone-500">{copy.result}</div><p className="mt-3 text-base font-bold leading-8 text-stone-800">{s.result}</p></div></div></section>; }
function Quiz({ copy }) { const [answers,setAnswers]=useState({}); const qs=[{q:"In a tissue sample, a beta value of 0.50 most directly means:",opts:["Half of each DNA molecule is methylated","Average methylation signal is around 50% across molecules","The probe is Infinium II"],a:1},{q:"Which column type helps distinguish Infinium I vs II in the manifest?",opts:["Infinium_Design_Type","Sample_Name","Age"],a:0},{q:"After subsetting factors, why use droplevels()?",opts:["To remove unused factor levels","To convert beta to M values","To perform bisulfite conversion"],a:0}]; return <section className="mt-10 rounded-[2.5rem] border border-stone-200 bg-white/80 p-6 shadow-sm md:p-8"><Pill>{copy.quiz}</Pill><div className="mt-5 grid gap-4">{qs.map((q,i)=><div key={q.q} className="rounded-3xl border border-stone-200 bg-stone-50 p-4"><div className="font-black text-stone-950">{q.q}</div><div className="mt-3 flex flex-wrap gap-2">{q.opts.map((o,j)=><button key={o} onClick={()=>setAnswers({...answers,[i]:j})} className={cx("rounded-full border px-3 py-2 text-sm font-black", answers[i]===j ? (j===q.a?"border-emerald-300 bg-emerald-100 text-emerald-900":"border-red-300 bg-red-100 text-red-900") : "border-stone-200 bg-white text-stone-700")}>{o}</button>)}</div>{answers[i]!==undefined && <p className="mt-2 text-sm font-bold text-stone-700">{answers[i]===q.a ? copy.correct : copy.wrong}</p>}</div>)}</div></section>; }
function Trainer({ copy }) { const [show,setShow]=useState(false); return <section className="mt-10 rounded-[2.5rem] border border-stone-200 bg-white/80 p-6 shadow-sm md:p-8"><Pill>{copy.trainer}</Pill><h2 className="mt-4 text-3xl font-black text-stone-950">Explain why manifest exploration matters for the team report.</h2><textarea className="mt-5 min-h-40 w-full rounded-3xl border border-stone-200 bg-white p-4 text-sm font-semibold leading-7 outline-none focus:border-emerald-300" placeholder={copy.placeholder}/><button onClick={()=>setShow(!show)} className="mt-4 rounded-full bg-stone-950 px-5 py-3 text-sm font-black text-white">{show ? copy.hide : copy.reveal}</button>{show && <div className="mt-4 rounded-3xl border border-emerald-200 bg-emerald-50 p-5 text-sm font-bold leading-7 text-emerald-950">Manifest exploration is necessary because methylation-array output is probe-based. Before interpreting results biologically, the analyst must know whether each row corresponds to a genomic CpG, a SNP/control probe or another probe type; where it maps; whether it uses Infinium I or II chemistry; and whether it belongs to an island, shore, shelf or open-sea context. In R, this requires importing the manifest correctly, removing non-genomic/control rows when appropriate, checking factor levels and using table/subsetting to answer specific annotation questions.</div>}</section>; }
function ZoomModal({ item, copy, onClose }) { if(!item) return null; return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-stone-950/80 p-4" role="dialog" aria-modal="true" onClick={onClose}><div className="max-h-[94vh] w-[min(1100px,96vw)] overflow-auto rounded-[2rem] bg-white p-4 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="mb-3 flex items-center justify-between gap-3"><div><Pill>{copy.visualLabel} · Slide {item.slide}</Pill><h3 className="mt-2 text-xl font-black text-stone-950">{item.title}</h3></div><button onClick={onClose} className="rounded-full bg-stone-950 px-4 py-2 text-sm font-black text-white">{copy.close}</button></div><img src={item.src} alt={item.title} className="w-full rounded-[1.5rem] object-contain"/><p className="mt-3 text-sm font-semibold leading-7 text-stone-600">{item.body}</p></div></div>; }
function BottomNav({ copy, isDone, toggle }) { return <div className="mt-10 rounded-[2rem] border border-stone-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><a href="#/lesson/m2-r" className="rounded-full border border-stone-200 bg-white px-4 py-2 text-sm font-black text-stone-800">← {copy.previous}: {copy.previousTitle}</a><button onClick={toggle} className={cx("rounded-full px-4 py-2 text-sm font-black", isDone ? "bg-emerald-600 text-white" : "bg-stone-950 text-white")}>{isDone ? copy.done : copy.mark}</button><a href="#/lesson/m2-import-qc" className="rounded-full bg-stone-950 px-4 py-2 text-sm font-black text-white">{copy.next}: {copy.nextTitle} →</a></div></div>; }
export default function DRDLesson08({ lang="es", isDone=false, toggle=()=>{} }) { const copy=COPY[lang]||COPY.es; const sections=SECTIONS[lang]||SECTIONS.en; const [zoom,setZoom]=useState(null); return <div className="min-h-screen bg-[#f8f0df] text-stone-950"><TopNav copy={copy} isDone={isDone} toggle={toggle}/><main className="mx-auto w-[min(1180px,calc(100%-24px))] pb-16 pt-8"><Hero copy={copy}/>{sections.map(section=><SectionBlock key={section.title} section={section} copy={copy} onZoom={setZoom}/>) }<OptionLab copy={copy}/><CodeWalkthrough copy={copy}/><Quiz copy={copy}/><Trainer copy={copy}/><BottomNav copy={copy} isDone={isDone} toggle={toggle}/></main><ZoomModal item={zoom} copy={copy} onClose={()=>setZoom(null)}/></div>; }
