export const lessonContent = {
  id: "amla-2026-05-14-convolutional-networks",
  extractionStatus: "source-based complete draft",
  objectives: [
    "Explain autoencoders as self-supervised networks that learn compressed latent representations.",
    "Distinguish encoder, code, decoder, reconstruction loss and undercomplete versus overcomplete architecture choices.",
    "Read the MNIST autoencoder implementation and explain why the target equals the input.",
    "Describe denoising and sparse autoencoders as ways to force useful feature learning.",
    "Explain SVM intuition through large-margin classification, support vectors, scaling, C and kernels.",
    "Recognize when LinearSVC, SVC and SVR are appropriate from a computational point of view.",
    "Connect dimensionality reduction, PCA, explained variance and manifold learning to the same compression theme.",
  ],
  coreConcepts: [
    {
      title: "Efficient representation",
      body: "A compact pattern can replace memorizing every raw value. Autoencoders exploit this by forcing data through a smaller learned code.",
      keywords: ["pattern", "compression", "latent structure"],
    },
    {
      title: "Autoencoder",
      body: "A feed-forward neural network trained to reconstruct its input. The value is not the output itself, but the compressed code learned in the middle.",
      keywords: ["input = target", "reconstruction", "self-supervised"],
    },
    {
      title: "Code / latent space",
      body: "The intermediate representation produced by the encoder. It should contain the information needed to reconstruct the relevant structure of the input.",
      keywords: ["code layer", "bottleneck", "representation"],
    },
    {
      title: "Undercomplete AE",
      body: "An autoencoder whose code dimension is smaller than the input. This prevents trivial copying and pushes pattern learning.",
      keywords: ["small code", "bottleneck", "features"],
    },
    {
      title: "Denoising AE",
      body: "An autoencoder trained with noisy inputs and clean targets, forcing it to recover meaningful signal rather than copy noise.",
      keywords: ["noise", "clean target", "signal recovery"],
    },
    {
      title: "Support vector",
      body: "A training instance on the margin boundary that actually determines the SVM decision boundary.",
      keywords: ["margin", "street", "boundary"],
    },
    {
      title: "Kernel trick",
      body: "A way to compute dot products in an implicit higher-dimensional feature space without explicitly building that transformed space.",
      keywords: ["polynomial kernel", "RBF", "implicit mapping"],
    },
    {
      title: "PCA",
      body: "A projection-based dimensionality reduction method that finds orthogonal axes preserving as much variance as possible.",
      keywords: ["principal components", "SVD", "explained variance"],
    },
    {
      title: "Manifold learning",
      body: "A nonlinear DR approach for data lying near a lower-dimensional curved structure embedded in a higher-dimensional space.",
      keywords: ["manifold", "LLE", "unroll"],
    },
  ],
  walkthroughSections: [
    {
      range: "Module 1 / Lecture5 slides 1-15",
      title: "Autoencoders start from the idea of useful compression",
      intro: "The professor spent real time on intuition before definitions. Study this block as the why: patterns let you store less while preserving what matters.",
      slides: [
        {
          label: "Slide 1",
          deckLabel: "Module 1 / Lecture5",
          page: 1,
          image: "amla-slides/module1-lecture5/slide-01.png",
          title: "Lecture frame",
          comment: "The class starts a long session that covers more than one topic. The first major block is autoencoders.",
          professor: "He warned that the Lecture5 PDF had more material than might fit cleanly, and that he might accelerate or skip parts depending on time.",
          remember: "Treat the class as three connected themes: representation, margins/kernels and dimensionality reduction.",
        },
        {
          label: "Slides 4-7",
          deckLabel: "Module 1 / Lecture5",
          page: 6,
          image: "amla-slides/module1-lecture5/slide-06.png",
          title: "Patterns beat raw memorization",
          comment: "The decreasing even-number sequence is easier because you store the rule, not every value. This is the core autoencoder intuition.",
          professor: "He stressed that machines can memorize, but we deliberately constrain them so they learn structure instead of copying.",
          remember: "Compression is useful only when it captures a pattern, not when it blindly drops information.",
        },
        {
          label: "Slide 8",
          deckLabel: "Module 1 / Lecture5",
          page: 8,
          image: "amla-slides/module1-lecture5/slide-08.png",
          title: "Chess memory experiment",
          comment: "Expert chess players remember realistic boards because they see learned patterns. Random boards break that advantage.",
          professor: "He used this to separate memory from pattern recognition: experts are not simply storing more raw positions.",
          remember: "An autoencoder is useful when the data contains regularities it can learn.",
        },
        {
          label: "Slides 9-12",
          deckLabel: "Module 1 / Lecture5",
          page: 12,
          image: "amla-slides/module1-lecture5/slide-12.png",
          title: "Encoder, code, decoder",
          comment: "The encoder compresses input into a code; the decoder reconstructs the input from that code. The target is the original input.",
          professor: "He compared the code to lecture notes: compact enough to store, rich enough to reconstruct an explanation later.",
          remember: "To build an AE you need an encoder, a decoder and a loss comparing output with input.",
        },
        {
          label: "Slide 13",
          deckLabel: "Module 1 / Lecture5",
          page: 13,
          image: "amla-slides/module1-lecture5/slide-13.png",
          title: "AE is not gzip",
          comment: "Autoencoders are data-specific, lossy and better described as self-supervised rather than classically supervised.",
          professor: "He emphasized that an AE trained on one type of data will not compress arbitrary data meaningfully.",
          remember: "AEs learn compression for data similar to the training distribution.",
          trap: "Do not describe an autoencoder as a general-purpose lossless compressor.",
        },
        {
          label: "Slides 14-15",
          deckLabel: "Module 1 / Lecture5",
          page: 14,
          image: "amla-slides/module1-lecture5/slide-14.png",
          title: "Architecture choices",
          comment: "Input and output must match in dimensionality, but encoder and decoder do not need to be perfectly mirrored.",
          professor: "He called code size a hyperparameter and returned to the sandwich architecture as the usual useful pattern.",
          remember: "Code size, depth, nodes per layer and reconstruction loss are the first AE design choices.",
        },
      ],
    },
    {
      range: "Module 1 / Lecture5 slides 16-40",
      title: "MNIST autoencoder implementation and the overcomplete trap",
      intro: "This block connects the conceptual AE to Keras. The key implementation shift is Functional API and fitting input to itself.",
      slides: [
        {
          label: "Slides 16-19",
          deckLabel: "Module 1 / Lecture5",
          page: 19,
          image: "amla-slides/module1-lecture5/slide-19.png",
          title: "Hands-on AE notebook",
          comment: "The deck names `..._HandsOn_AE.ipynb` and follows the notebook through the slides, but no standalone URL was exposed in the extracted sources.",
          professor: "He said the notebook file is easy to find because it is called AE, and students can follow the slides or the notebook.",
          remember: "Notebook is the experiment surface; slides explain what each part means.",
        },
        {
          label: "Slides 21-26",
          deckLabel: "Module 1 / Lecture5",
          page: 25,
          image: "amla-slides/module1-lecture5/slide-25.png",
          title: "Functional API and self-supervised fit",
          comment: "The AE uses Keras Functional API because the model is better seen as a graph of connected layers. In `fit`, the target is the input data itself.",
          professor: "He asked students to notice what was different from earlier Sequential Keras examples: layers are called on tensors and parts can be grabbed flexibly.",
          remember: "For an AE: `model.fit(x_train, x_train)` is not a typo.",
          trap: "Do not look for class labels in a basic reconstruction AE.",
        },
        {
          label: "Slides 27-30",
          deckLabel: "Module 1 / Lecture5",
          page: 29,
          image: "amla-slides/module1-lecture5/slide-29.png",
          title: "Model summary and visualization",
          comment: "The summary and Net2Vis diagram reveal the sandwich: 784 input, hidden layers, 32-code bottleneck, then reconstruction back to 784.",
          professor: "He recommended Net2Vis as a simple visualization tool for network architecture, not only autoencoders.",
          remember: "Visualizing the model helps catch whether the bottleneck is really there.",
        },
        {
          label: "Slides 31-32",
          deckLabel: "Module 1 / Lecture5",
          page: 31,
          image: "amla-slides/module1-lecture5/slide-31.png",
          title: "Reconstruction output",
          comment: "The reconstructed MNIST digits are close but degraded. That is expected: the code forces compression and the model is simple.",
          professor: "He said AE debugging can be visually easy: if reconstructed digits look broken, the model clearly did not learn the desired representation.",
          remember: "Good AE output is not perfect copying; it should preserve relevant structure.",
        },
        {
          label: "Slides 33-36",
          deckLabel: "Module 1 / Lecture5",
          page: 34,
          image: "amla-slides/module1-lecture5/slide-34.png",
          title: "Shallow versus deep AE",
          comment: "Adding layers can make encoding and decoding more intelligent, improving reconstruction quality for the same task.",
          professor: "He pointed to digit details, especially the reconstructed 2, to show how architecture changes output quality.",
          remember: "More depth can help, but depth alone is not the goal.",
        },
        {
          label: "Slides 37-39",
          deckLabel: "Module 1 / Lecture5",
          page: 39,
          image: "amla-slides/module1-lecture5/slide-39.png",
          title: "Undercomplete versus overcomplete AE",
          comment: "If the code is too large or the model too powerful, the AE may learn the identity function instead of useful latent structure.",
          professor: "He used the notebook metaphor: if the notebook has unlimited pages, you can copy the book instead of extracting important ideas.",
          remember: "Use an undercomplete bottleneck when the goal is representation learning.",
          trap: "Perfect reconstruction on training data can be AE-style overfitting.",
        },
        {
          label: "Slide 40",
          deckLabel: "Module 1 / Lecture5",
          page: 40,
          image: "amla-slides/module1-lecture5/slide-40.png",
          title: "Forcing useful features",
          comment: "Small code, denoising and regularization are three ways to stop the AE from simply copying.",
          professor: "He framed this as the key: force the AE to learn useful features.",
          remember: "The design question is how you constrain the model so the code becomes meaningful.",
        },
      ],
      lab: {
        title: "Mini-lab: MNIST autoencoder sanity checks",
        todo: "Slide 19 names `..._HandsOn_AE.ipynb`, but the extracted sources did not expose a standalone Colab/Drive URL.",
        objective: "Run or mentally trace a simple AE and verify that it learns reconstruction through a bottleneck.",
        steps: [
          "Confirm input images are flattened to 784 values.",
          "Identify the code layer and its size.",
          "Check that the model target is the same array used as input.",
          "Compare original and reconstructed digits on the test set.",
          "Change code size or hidden-layer width and observe reconstruction quality.",
        ],
        parameters: ["code size", "hidden layer size", "activation", "loss function"],
        outputs: ["model summary", "reconstructed digits", "reconstruction loss"],
        explain: [
          "Why the AE target equals the input.",
          "Why a very large code risks trivial copying.",
          "Why reconstruction can be degraded but still meaningful.",
        ],
      },
    },
    {
      range: "Module 1 / Lecture5 slides 41-57",
      title: "Denoising, sparse and convolutional autoencoders",
      intro: "These variants answer the same question in different ways: how do we force the model to learn structure instead of identity?",
      slides: [
        {
          label: "Slides 42-45",
          deckLabel: "Module 1 / Lecture5",
          page: 45,
          image: "amla-slides/module1-lecture5/slide-45.png",
          title: "Denoising AE setup",
          comment: "The input is noisy, but the target is the original clean image. A straight copy cannot solve the task.",
          professor: "He connected this to signal processing: if you can create noisy-clean pairs, you can train a model to remove noise.",
          remember: "Denoising AE: noisy input, clean target.",
        },
        {
          label: "Slides 46-49",
          deckLabel: "Module 1 / Lecture5",
          page: 47,
          image: "amla-slides/module1-lecture5/slide-47.png",
          title: "Noise level matters",
          comment: "Moderate noise can be removed surprisingly well; extreme noise makes the task much harder and output quality drops.",
          professor: "He used the noise-factor examples to make students predict output before revealing the reconstruction.",
          remember: "Denoising performance depends on how much signal remains in the noisy input.",
        },
        {
          label: "Slides 50-54",
          deckLabel: "Module 1 / Lecture5",
          page: 54,
          image: "amla-slides/module1-lecture5/slide-54.png",
          title: "Sparse AE as bonus",
          comment: "Sparse AEs use a penalty so only a fraction of code units activate. The loss may be higher because it includes regularization.",
          professor: "This was marked bonus. The important idea is the constraint: large code can still be meaningful if only a small subset is active.",
          remember: "Sparse does not mean lower loss; it means constrained representation.",
        },
        {
          label: "Slides 55-57",
          deckLabel: "Module 1 / Lecture5",
          page: 57,
          image: "amla-slides/module1-lecture5/slide-57.png",
          title: "AE use cases and convolutional AE",
          comment: "AEs are not universal compressors. Common uses include denoising and dimensionality reduction; images usually call for convolutional AEs.",
          professor: "He tied this back to CNNs: dense AEs are weak for real images unless the images are tiny.",
          remember: "For image autoencoders, use convolutional structure to preserve spatial information.",
        },
      ],
    },
    {
      range: "Module 1 / Lecture5 slides 58-86",
      title: "SVM: large margins, support vectors and kernels",
      intro: "The lecture then jumps out of neural networks. Study SVM as a classical model whose geometry is the main story.",
      slides: [
        {
          label: "Slides 58-63",
          deckLabel: "Module 1 / Lecture5",
          page: 63,
          image: "amla-slides/module1-lecture5/slide-63.png",
          title: "Large-margin classification",
          comment: "SVM chooses the widest possible street between classes. Only the points on the edge matter: those are support vectors.",
          professor: "He emphasized the intuition first: red and purple lines may separate the classes, but the SVM boundary maximizes distance from the closest points.",
          remember: "SVM decision boundary is determined by support vectors, not by every far-away point.",
        },
        {
          label: "Slides 64-67",
          deckLabel: "Module 1 / Lecture5",
          page: 65,
          image: "amla-slides/module1-lecture5/slide-65.png",
          title: "Hard margin, soft margin and C",
          comment: "Hard margin fails with outliers or non-separable data. Soft margin allows violations, with C controlling the trade-off.",
          professor: "He pointed out that SVMs are sensitive to scale, so standardization is not optional decoration.",
          remember: "Lower C means more regularization and more tolerance for margin violations.",
          trap: "Do not compare SVM features without scaling them.",
        },
        {
          label: "Slides 69-73",
          deckLabel: "Module 1 / Lecture5",
          page: 70,
          image: "amla-slides/module1-lecture5/slide-70.png",
          title: "Nonlinear SVM through polynomial features",
          comment: "A nonlinear-looking problem can become linearly separable after adding polynomial features, but this expansion can become expensive.",
          professor: "He used the moons example to motivate why explicit feature expansion works but may not scale.",
          remember: "Nonlinear SVM starts from the idea of mapping data to a space where a linear separator works.",
        },
        {
          label: "Slides 74-79",
          deckLabel: "Module 1 / Lecture5",
          page: 77,
          image: "amla-slides/module1-lecture5/slide-77.png",
          title: "Kernel trick",
          comment: "A kernel computes the dot product in an implicit transformed feature space without explicitly computing the transformation.",
          professor: "He called the math 'magic' for course purposes, but stressed that it explains why scikit-learn kernel parameters work.",
          remember: "Kernel trick: use the transformed-space dot product without building the transformed vectors.",
        },
        {
          label: "Slides 80-81",
          deckLabel: "Module 1 / Lecture5",
          page: 81,
          image: "amla-slides/module1-lecture5/slide-81.png",
          title: "Complexity and class choice",
          comment: "LinearSVC scales roughly with samples and features but no kernel trick; SVC supports kernels but can scale poorly with many samples.",
          professor: "He warned that SVMs can handle many features, but many examples can become painful.",
          remember: "Use LinearSVC when a linear boundary is enough and data is large; use SVC kernels for complex small/medium datasets.",
        },
        {
          label: "Slides 82-86",
          deckLabel: "Module 1 / Lecture5",
          page: 84,
          image: "amla-slides/module1-lecture5/slide-84.png",
          title: "SVM regression and hands-on notebook",
          comment: "SVR reverses the street intuition: fit as many instances as possible inside the margin while limiting violations.",
          professor: "He said the SVM notebook contains the plots and experiments, and students can try the kernels and hyperparameters there.",
          remember: "SVM is not only classification; SVR applies the margin idea to regression.",
        },
      ],
      lab: {
        title: "Mini-lab: SVM margin and kernel decisions",
        todo: "Slide 86 names `_HandsOn_SVM.ipynb`, but the extracted sources did not expose a standalone Colab/Drive URL.",
        objective: "Decide when to use linear SVM, kernel SVM or SVR and explain the role of scaling/C/kernel.",
        steps: [
          "Start with a 2D linearly separable toy dataset.",
          "Fit a linear SVM and identify the closest support vectors.",
          "Change C and observe margin width versus violations.",
          "Try a moons dataset with polynomial features or a polynomial/RBF kernel.",
          "For regression, compare the effect of epsilon on the SVR street.",
        ],
        parameters: ["feature scaling", "C", "kernel", "degree", "epsilon"],
        outputs: ["decision boundary", "support vectors", "margin width", "training time"],
        explain: [
          "Why support vectors determine the boundary.",
          "Why SVMs need scaling.",
          "Why kernel SVM is powerful but not always scalable.",
        ],
      },
    },
    {
      range: "Module 1 / Lecture5 slides 87-118",
      title: "Dimensionality reduction: PCA first, manifold learning as a glance",
      intro: "The final part connects back to autoencoders: reducing dimensions can make training, visualization and communication tractable, but it costs interpretability and information.",
      slides: [
        {
          label: "Slides 87-91",
          deckLabel: "Module 1 / Lecture5",
          page: 89,
          image: "amla-slides/module1-lecture5/slide-89.png",
          title: "Curse of dimensionality",
          comment: "High-dimensional data is slow, sparse, hard to visualize and harder to generalize from. DR can help, but it adds abstraction.",
          professor: "He said he often treats DR like a switch in a pipeline: try with and without it, then judge whether it helps.",
          remember: "Do not apply DR automatically; use it when it solves a real training, visualization or sparsity problem.",
        },
        {
          label: "Slides 93-94",
          deckLabel: "Module 1 / Lecture5",
          page: 94,
          image: "amla-slides/module1-lecture5/slide-94.png",
          title: "Projection versus manifold learning",
          comment: "The two broad DR approaches are projection and manifold learning. PCA is the main projection method; LLE is shown as a manifold example.",
          professor: "He framed PCA as the workhorse: projection/PCA covers most practical DR use in this course context.",
          remember: "Projection flattens onto a subspace; manifold learning tries to unroll curved structure.",
        },
        {
          label: "Slides 96-101",
          deckLabel: "Module 1 / Lecture5",
          page: 99,
          image: "amla-slides/module1-lecture5/slide-99.png",
          title: "Manifold assumption and its risk",
          comment: "A curved low-dimensional manifold may explain high-dimensional data, but unrolling it does not always make the supervised task easier.",
          professor: "He gave both a positive and a negative decision-boundary example to prevent blind faith in manifold learning.",
          remember: "DR can speed training, but it may not improve model performance.",
        },
        {
          label: "Slides 104-107",
          deckLabel: "Module 1 / Lecture5",
          page: 104,
          image: "amla-slides/module1-lecture5/slide-104.png",
          title: "PCA chooses axes preserving variance",
          comment: "PCA finds the hyperplane closest to the data and projects onto axes that preserve maximum variance.",
          professor: "He warned that after PCA, original feature meanings are gone; you become more dependent on the method.",
          remember: "Principal components are new axes, not original variables.",
          trap: "Do not interpret a PCA coordinate as if it were one original feature.",
        },
        {
          label: "Slides 108-111",
          deckLabel: "Module 1 / Lecture5",
          page: 110,
          image: "amla-slides/module1-lecture5/slide-110.png",
          title: "SVD, sklearn and explained variance",
          comment: "PCA is implemented through SVD. In sklearn, `PCA` exposes components and explained variance ratios.",
          professor: "He emphasized choosing dimensions by explained variance or elbow, not by an arbitrary number unless visualization requires 2D/3D.",
          remember: "Explained variance ratio tells you how much variance each principal component captures.",
        },
        {
          label: "Slide 112",
          deckLabel: "Module 1 / Lecture5",
          page: 112,
          image: "amla-slides/module1-lecture5/slide-112.png",
          title: "PCA compression on MNIST",
          comment: "MNIST can be compressed from 784 features to about 150 while preserving 95% variance; reconstruction is not perfect but remains recognizable.",
          professor: "He explicitly tied this back to autoencoder code: the meaningful dimensionality may be much smaller than the raw input dimension.",
          remember: "PCA and AEs both compress, but PCA is linear/projection-based while AEs learn nonlinear neural representations.",
        },
        {
          label: "Slides 113-118",
          deckLabel: "Module 1 / Lecture5",
          page: 116,
          image: "amla-slides/module1-lecture5/slide-116.png",
          title: "Randomized PCA, Incremental PCA and LLE",
          comment: "Randomized and incremental PCA are implementation variants for scale. LLE is quoted as a nonlinear manifold method, but the professor treated it as a glance/bonus.",
          professor: "He said LLE should be considered only for specific datasets that seem to require manifold-style reduction.",
          remember: "For this class, PCA is central; LLE is awareness-level unless a dataset clearly calls for it.",
        },
      ],
      lab: {
        title: "Mini-lab: PCA as compression and visualization",
        todo: "The class discusses sklearn PCA, but no separate PCA notebook URL was visible in the extracted sources for this date.",
        objective: "Use PCA to reduce dimensionality while tracking explained variance and interpretability loss.",
        steps: [
          "Fit `PCA` on a scaled dataset or on flattened MNIST-like data.",
          "Inspect `explained_variance_ratio_`.",
          "Choose dimensions by cumulative variance or elbow.",
          "Project the data and, if possible, inverse-transform it.",
          "Compare original features to PCA coordinates and note what became less interpretable.",
        ],
        parameters: ["n_components", "variance threshold", "svd_solver"],
        outputs: ["explained variance curve", "projected data", "reconstructed examples"],
        explain: [
          "Why PCA can compress data.",
          "Why PCA coordinates are not original variables.",
          "Why dimensionality reduction may help speed but not guarantee better accuracy.",
        ],
      },
    },
  ],
  professorEmphasis: [
    "The Lecture5 deck contains more material than a single class can comfortably cover, so focus on the themes he actually developed.",
    "For autoencoders, the main point is not copying input to output; it is learning a compact code that preserves important structure.",
    "Autoencoders are data-specific and lossy, so they are not equivalent to general compression tools like zip/gzip.",
    "The Keras Functional API matters because it lets you build and reuse graphs of layers more flexibly than Sequential.",
    "Overcomplete AEs can overfit by learning the identity function; undercomplete bottlenecks are usually the useful case.",
    "SVM intuition is the widest street; support vectors are the points that determine the boundary.",
    "SVMs are sensitive to feature scaling and kernel SVMs do not scale well to many examples.",
    "PCA is central for dimensionality reduction here; LLE/manifold methods were presented only as a brief awareness-level extension.",
  ],
  commonTraps: [
    "Thinking an AE is useful because it reproduces the input perfectly.",
    "Calling an AE fully supervised in the same sense as labeled classification.",
    "Making code size too large and then claiming the learned code is meaningful without checking.",
    "Forgetting that denoising AE input and target are different: noisy input, clean output.",
    "Using an SVM without scaling features.",
    "Treating C as accuracy control instead of regularization/margin-violation control.",
    "Using kernel SVC on a large dataset without thinking about computational cost.",
    "Applying PCA and then interpreting principal-component coordinates as original variables.",
    "Assuming dimensionality reduction always improves model performance.",
  ],
  quickQuiz: [
    {
      question: "Why is the second number sequence easier to remember in the opening example?",
      answer: "Because it has a rule: even numbers descending from 50. You store the pattern, not every value.",
    },
    {
      question: "What are the three parts of a basic autoencoder?",
      answer: "Encoder, code/latent representation and decoder.",
    },
    {
      question: "Why is `model.fit(x_train, x_train)` meaningful for an AE?",
      answer: "The AE trains reconstruction: the target is the original input.",
    },
    {
      question: "What is the danger of an overcomplete autoencoder?",
      answer: "It may learn to copy inputs directly instead of learning a useful latent representation.",
    },
    {
      question: "What is the training setup for a denoising AE?",
      answer: "Noisy examples are inputs; clean original examples are targets.",
    },
    {
      question: "What determines the decision boundary of a linear SVM?",
      answer: "The support vectors: the closest points on the margin edge.",
    },
    {
      question: "What is the kernel trick useful for?",
      answer: "It lets the model act as if data were mapped to a higher-dimensional space without explicitly computing that mapping.",
    },
    {
      question: "What does PCA preserve when choosing principal components?",
      answer: "As much variance as possible along orthogonal axes.",
    },
    {
      question: "Why can PCA make interpretation harder?",
      answer: "The new axes are combinations of original variables, so the coordinates no longer directly correspond to original feature meanings.",
    },
  ],
  examQuestions: [
    {
      id: "l07-mcq-1",
      question: "An autoencoder reconstructs every training image almost perfectly, but its code layer is larger than the input. What is the best concern?",
      options: [
        "It may have learned a trivial identity mapping rather than meaningful latent features",
        "The reconstruction loss must be binary cross-entropy",
        "The decoder is no longer a neural network",
        "The model has become a supervised classifier",
      ],
      correct: 0,
      explanation: "Overcomplete AEs can copy too easily. Good reconstruction alone does not prove useful representation learning.",
    },
    {
      id: "l07-mcq-2",
      question: "Which training pair is correct for a denoising autoencoder?",
      options: [
        "Noisy input image, clean target image",
        "Clean input image, random label target",
        "Noisy input image, same noisy target image",
        "Latent code input, class label target",
      ],
      correct: 0,
      explanation: "The dAE learns to remove noise because it receives corrupted inputs but is evaluated against the clean originals.",
    },
    {
      id: "l07-mcq-3",
      question: "A dataset is linearly separable by many boundaries. What does a linear SVM prefer?",
      options: [
        "The boundary with the largest margin from the closest training examples",
        "The boundary that passes through the most points",
        "The boundary with the smallest possible street",
        "A random boundary if all classify training data correctly",
      ],
      correct: 0,
      explanation: "SVM is large-margin classification: it maximizes the street between classes.",
    },
    {
      id: "l07-mcq-4",
      question: "Why should SVM features usually be scaled?",
      options: [
        "The margin geometry is distance-based, so feature scale can dominate the boundary",
        "SVMs cannot accept numeric features without scaling",
        "Scaling converts classification into regression",
        "The kernel trick only works on binary features",
      ],
      correct: 0,
      explanation: "SVM boundaries depend on distances/margins; unscaled features can distort the geometry.",
    },
    {
      id: "l07-mcq-5",
      question: "When is kernel SVC most appropriate compared with LinearSVC?",
      options: [
        "For complex small or medium-sized datasets where nonlinear boundaries are needed",
        "For huge datasets with millions of examples and a linear boundary",
        "Only when the task is regression",
        "Only when no feature scaling is possible",
      ],
      correct: 0,
      explanation: "SVC supports kernels but scales poorly with many samples; LinearSVC is better for large linear settings.",
    },
    {
      id: "l07-mcq-6",
      question: "A PCA transform reduces 784 MNIST features to 150 while preserving 95% variance. What is the safest interpretation?",
      options: [
        "The representation is compressed and loses some information, but likely keeps much of the structure",
        "The 150 features are the original 150 most important pixels",
        "The transform is lossless because 95% is close to 100%",
        "The output is necessarily better for every classifier",
      ],
      correct: 0,
      explanation: "PCA projection is lossy unless all components are kept. The new coordinates are principal components, not original pixels.",
    },
    {
      id: "l07-mcq-7",
      question: "Why might manifold learning help where simple projection fails?",
      options: [
        "The data may lie on a curved lower-dimensional structure that needs to be unrolled",
        "It preserves original feature names better than PCA",
        "It guarantees better classification accuracy",
        "It avoids any information loss",
      ],
      correct: 0,
      explanation: "Manifold methods model curved lower-dimensional structure, but they do not guarantee better downstream performance.",
    },
  ],
  checklistTitle: "L07 final takeaways",
  studyChecklist: [
    "Explain autoencoders through pattern extraction, not memorization.",
    "Draw encoder-code-decoder and label which dimensions must match.",
    "Know why Functional API and `fit(x, x)` appear in the AE notebook.",
    "Keep undercomplete, overcomplete, denoising and sparse AEs separate.",
    "For SVM, explain the widest-street intuition, support vectors, scaling and C.",
    "State when kernel trick helps and when SVC complexity becomes a problem.",
    "For PCA, explain principal components, explained variance and why features become less interpretable.",
    "Treat LLE/manifold learning as awareness-level unless the dataset clearly needs nonlinear unrolling.",
  ],
};
