import { buildSections } from "../shared/buildContent.js";

const deck = "4-HiddenMarkovModels.pdf";
const deckFolder = "04-hidden-markov-models";
const title = "Hidden Markov Models: states, emissions and paths";

export const lessonContent = {
  id: "lb1-04-hidden-markov-models",
  extractionStatus: "real slide screenshots extracted from 4-HiddenMarkovModels.pdf; full deck covered",
  whyThisMatters: "HMMs are the central probabilistic machine of the course. They explain how an observed biological sequence can be generated by an unobserved path of states, and why dynamic programming is needed to reason over many possible paths.",
  objectives: ["Define HMM states, transitions, emissions, alphabet and start/end probabilities.", "Distinguish observed sequence from hidden path.", "Explain sequence probability as a sum over possible paths.", "State what Forward, Backward and Viterbi solve conceptually."],
  coreConcepts: [
    { title: "Observed symbols", body: "The sequence is visible: nucleotides, amino acids or other emitted symbols.", keywords: ["sequence", "alphabet", "emission"] },
    { title: "Hidden path", body: "The state sequence that produced the observations is not directly observed.", keywords: ["path", "states", "hidden"] },
    { title: "Dynamic programming", body: "Algorithms avoid enumerating all paths by reusing repeated subproblems.", keywords: ["Forward", "Viterbi", "recursion"] },
  ],
  routeSteps: [
    { title: "Define the pieces", body: "Name states, transitions, emissions and start/end probabilities." },
    { title: "Follow one path", body: "Compute the probability idea for a single path before summing over paths." },
    { title: "Use dynamic programming", body: "Understand why Forward sums over paths and Viterbi selects the best path." },
  ],
  walkthroughSections: buildSections({
    deckFolder,
    deck,
    title,
    remember: "The observed sequence is visible; the path of states is hidden and inferred probabilistically.",
    trap: "Do not confuse the most probable path with the total probability of the sequence.",
    prompt: "What are the states, emissions, transitions and hidden path in this slide?",
    sections: [
      { start: 1, end: 4, title: "Formal HMM definition", intro: "The opening slides define the model components.", teaching: "Study interpretation: do not explain HMMs only by example; name the formal pieces." },
      { start: 5, end: 9, title: "Observed sequence and hidden path", intro: "This block separates what you observe from the state path that generated it.", teaching: "Study interpretation: hidden means unobserved, not unknowable." },
      { start: 10, end: 14, title: "Algorithms over many paths", intro: "The deck motivates Forward, Backward and Viterbi-style dynamic programming.", teaching: "Study interpretation: dynamic programming solves repeated computation over many possible paths." },
      { start: 15, end: 18, title: "Biological examples and interpretation", intro: "The closing slides connect the formalism to biological sequence patterns.", teaching: "Study interpretation: map states and emissions back to the biological meaning of the example." },
    ],
  }),
  miniLabs: [
    { title: "Path probability dry run", goal: "Practice one path before the full algorithm.", steps: ["Choose a short observed sequence.", "Write a possible hidden path.", "Multiply start, transition and emission terms conceptually."], output: "A symbolic probability expression for one path.", check: "This is one path, not the total sequence probability.", trap: "Do not forget transition probabilities." },
    { title: "Forward vs Viterbi sorter", goal: "Separate the two questions.", steps: ["Write the question answered by Forward.", "Write the question answered by Viterbi.", "Give one biological case where each is useful."], output: "Two algorithm-purpose statements.", check: "Forward sums; Viterbi selects.", trap: "Do not call the Viterbi path the sequence probability." },
  ],
  checkpoints: [
    { question: "Define an HMM.", answer: "An HMM has hidden states, transition probabilities between states, emission probabilities over an alphabet, and start/end probabilities; it produces an observed sequence through a hidden path." },
    { question: "Why is the path hidden?", answer: "Because the emitted symbols are observed but the state that emitted each symbol is not directly observed." },
    { question: "What does the Forward algorithm solve?", answer: "It computes the total probability of an observed sequence under the model by summing over possible hidden paths efficiently." },
  ],
  modelAnswer: { question: "Why is the HMM path called hidden?", answer: "The path is hidden because we observe only the emitted sequence, such as nucleotides or amino acids, not the sequence of internal states that generated those emissions. The model defines transition and emission probabilities, and algorithms infer path probabilities from the observations. This distinction matters because the total sequence probability sums over many possible paths, while Viterbi asks for the single most probable path." },
  sourceNotes: ["Primary source: 4-HiddenMarkovModels.pdf in the Capriotti LB1 Drive folder.", "All slide ranges in the deck are represented with real extracted screenshots.", "Teaching-emphasis boxes are study interpretations from the slides, not direct transcript quotations."],
};
