export const lessonContent = {
  id: "amla-2026-05-22-segmentation-workflow",
  extractionStatus: "source-based complete draft",
  objectives: [
    "Explain semantic segmentation as pixel-level binary classification for Fluocells.",
    "Distinguish semantic and instance segmentation in the context of counting cells.",
    "Describe the U-Net encoder-decoder structure and why skip connections help localization.",
    "Explain the c-ResUNet changes: learned colorspace, ELU, residual paths and larger bottleneck filters.",
    "Use PyTorch/FastAI vocabulary for model, DataLoader, Learner, fit and callbacks.",
    "Explain why data augmentation is valid for image/mask pairs and why it improves robustness.",
    "Compare BCE, weighted BCE, focal loss and Dice loss for imbalanced segmentation.",
    "Assess training with curves, multiple metrics, visual inspection, baselines and error analysis.",
  ],
  coreConcepts: [
    {
      title: "Semantic segmentation",
      body: "Each pixel receives a class label. In Fluocells, the task is background versus cell.",
      keywords: ["pixel", "binary classification", "mask"],
    },
    {
      title: "Instance segmentation",
      body: "Pixels are grouped by individual object identity, which is more directly useful for counting separate cells.",
      keywords: ["individual objects", "counting", "separation"],
    },
    {
      title: "U-Net",
      body: "A biomedical segmentation architecture with a contracting branch for features and an expanding branch for localization.",
      keywords: ["encoder", "decoder", "skip connections"],
    },
    {
      title: "c-ResUNet",
      body: "A ResUNet variant adapted to fluorescence microscopy cell counting.",
      keywords: ["learned colorspace", "ELU", "5x5 filters"],
    },
    {
      title: "FastAI Learner",
      body: "A training object that combines the model, DataLoaders, loss, optimizer, metrics and callbacks.",
      keywords: ["PyTorch", "DataLoader", "fit"],
    },
    {
      title: "Data augmentation",
      body: "Transform images and masks consistently to create more varied training examples at low annotation cost.",
      keywords: ["rotation", "resize", "lighting", "robustness"],
    },
    {
      title: "Dice loss",
      body: "A segmentation-oriented loss derived from overlap between predicted and true masks; lower is better during training.",
      keywords: ["overlap", "mask similarity", "imbalance"],
    },
    {
      title: "Callbacks",
      body: "Hooks that modify training behavior, such as early stopping, logging or learning-rate scheduling.",
      keywords: ["early stopping", "scheduler", "training loop"],
    },
  ],
  walkthroughSections: [
    {
      range: "Module 2 / Lecture4 slides 1-10",
      title: "Semantic segmentation is the deep-learning framing",
      intro: "The class resumes the Fluocells problem after EDA and thresholding. The key move is to frame cell counting as segmentation, not just scalar regression.",
      slides: [
        {
          label: "Slide 1",
          deckLabel: "Module 2 / Lecture4",
          page: 1,
          image: "amla-slides/module2-lecture4/slide-01.png",
          title: "Continuation of object recognition and counting",
          comment: "This deck continues the same Fluocells thread from 21 May, now moving from baseline to deep segmentation.",
          professor: "He opened by saying the goal remains: theory, hands-on and takeaways for the project.",
          remember: "Study L09 and L10 as one applied workflow: understand data, build baseline, then train segmentation.",
        },
        {
          label: "Slide 3",
          deckLabel: "Module 2 / Lecture4",
          page: 3,
          image: "amla-slides/module2-lecture4/slide-03.png",
          title: "Today's goal repeats the project frame",
          comment: "The aim is still object recognition/counting, Fluocells, advanced CNN architectures and PyTorch/FastAI examples.",
          professor: "He explicitly positioned the notebooks as examples of how to prepare and discuss an AML project.",
          remember: "The technical details matter because they support project interpretation.",
        },
        {
          label: "Slides 4-5",
          deckLabel: "Module 2 / Lecture4",
          page: 5,
          image: "amla-slides/module2-lecture4/slide-05.png",
          title: "Segmentation as regions of interest",
          comment: "Segmentation assigns labels to pixels so regions of interest become visible in the output.",
          professor: "He stressed that segmentation is a general imaging technique, not exclusively a machine-learning method.",
          remember: "For Fluocells, the region of interest is the cell area.",
        },
        {
          label: "Slide 6",
          deckLabel: "Module 2 / Lecture4",
          page: 6,
          image: "amla-slides/module2-lecture4/slide-06.png",
          title: "Semantic versus instance segmentation",
          comment: "Semantic segmentation gives all pixels of the same class the same value. Instance segmentation separates objects of the same class.",
          professor: "He contrasted this with counting: semantic segmentation marks cell pixels, but instance segmentation better separates individual counted objects.",
          trap: "Do not assume a semantic mask already tells you how many touching cells are present.",
        },
        {
          label: "Slides 7-8",
          deckLabel: "Module 2 / Lecture4",
          page: 8,
          image: "amla-slides/module2-lecture4/slide-08.png",
          title: "From heatmap to mask",
          comment: "The model predicts a probability heatmap for class 1. A threshold converts probabilities into a binary mask.",
          professor: "He compared this thresholding step to classification: 0.5 is common, but the threshold can be tuned depending on the use case.",
          remember: "Prediction is not only the network output; binarization and post-processing influence the final count.",
        },
        {
          label: "Slide 10",
          deckLabel: "Module 2 / Lecture4",
          page: 10,
          image: "amla-slides/module2-lecture4/slide-10.png",
          title: "Why instance segmentation helps counting",
          comment: "This question revisits the key methodological advantage: separate object identity is useful when counting.",
          professor: "He used the question to make sure students do not collapse semantic and instance segmentation.",
          remember: "For exam answers, say what output each method gives and why it matters.",
        },
      ],
    },
    {
      range: "Module 2 / Lecture4 slides 11-24",
      title: "U-Net, ResUNet and c-ResUNet",
      intro: "The architecture section explains why segmentation networks need both pattern extraction and spatial reconstruction.",
      slides: [
        {
          label: "Slides 11-13",
          deckLabel: "Module 2 / Lecture4",
          page: 13,
          image: "amla-slides/module2-lecture4/slide-13.png",
          title: "U-Net for biomedical segmentation",
          comment: "U-Net is the canonical architecture here: a U-shaped network with contracting and expanding branches.",
          professor: "He introduced U-Net as one of the first and most used architectures for segmentation tasks.",
          remember: "U-Net is not just another classifier; it maps an image to an image-like mask.",
        },
        {
          label: "Slides 14-15",
          deckLabel: "Module 2 / Lecture4",
          page: 14,
          image: "amla-slides/module2-lecture4/slide-14.png",
          title: "Contracting branch",
          comment: "Convolutional blocks extract patterns while max pooling reduces spatial dimensions and increases feature maps.",
          professor: "He repeatedly tied the branch to pattern extraction: smaller maps, richer channels.",
          remember: "Downsampling helps learn features but loses localization detail.",
        },
        {
          label: "Slide 17",
          deckLabel: "Module 2 / Lecture4",
          page: 17,
          image: "amla-slides/module2-lecture4/slide-17.png",
          title: "Expanding branch and skip connections",
          comment: "Upsampling rebuilds spatial resolution and skip connections bring earlier localization information back.",
          professor: "He emphasized that the output should be a segmentation map close to the input shape.",
          remember: "The decoder localizes; skip connections help recover detail lost during downsampling.",
        },
        {
          label: "Slides 18-19",
          deckLabel: "Module 2 / Lecture4",
          page: 19,
          image: "amla-slides/module2-lecture4/slide-19.png",
          title: "ResUNet residual units",
          comment: "ResUNet keeps the U-Net idea but replaces blocks with residual units to simplify training.",
          professor: "He linked residual paths to mitigating vanishing gradients and making training easier.",
          remember: "Residual connections do not change the task; they change how the network is trained.",
        },
        {
          label: "Slides 20-24",
          deckLabel: "Module 2 / Lecture4",
          page: 24,
          image: "amla-slides/module2-lecture4/slide-24.png",
          title: "c-ResUNet for fluorescence microscopy",
          comment: "c-ResUNet adds task-specific changes: 1x1 learned colorspace, ELU, convolutional identity path, extra bottleneck block and 5x5 filters.",
          professor: "He said the implementation notebook uses PyTorch/FastAI to build this network for the Fluocells application.",
          remember: "Architectural tweaks should be explained as responses to the data and task, not as decoration.",
        },
      ],
      lab: {
        title: "Mini-lab: trace the c-ResUNet architecture",
        objective: "Use the linked implementation notebook to map each architecture choice to its role in segmentation.",
        href: "https://drive.google.com/file/d/1kLScbhmBiE9QIwZbwFNoicogMzEQ7v1R/view?usp=drivesdk",
        steps: [
          "Open the c-ResUNet implementation notebook from the course resources.",
          "Find the PyTorch module/classes that define convolutional and residual blocks.",
          "Locate the forward method and follow how input passes through the model.",
          "Identify where the 1x1 convolution, residual blocks and larger bottleneck filters appear.",
          "Check the input/output tensor format expected by PyTorch.",
        ],
        parameters: [
          "Number of input channels.",
          "Number of output classes.",
          "Initial and doubled filters.",
          "Kernel sizes in bottleneck and convolutional blocks.",
        ],
        outputs: [
          "A model summary or printed architecture.",
          "Tensor shape changes across encoder and decoder.",
          "The final output mask dimensions/classes.",
        ],
        explain: [
          "Why PyTorch commonly uses C x H x W image tensors.",
          "Why a 1x1 convolution can act as a learned colorspace transformation.",
          "Why skip connections and residual connections solve different problems.",
        ],
      },
    },
    {
      range: "Module 2 / Lecture4 slide 25 + transcript notebooks",
      title: "FastAI workflow: DataLoaders, Learner and augmentation",
      intro: "The deck only names the hands-on part, while the transcript fills in the practical details: FastAI wraps PyTorch model training with DataLoaders, Learner, transforms and callbacks.",
      slides: [
        {
          label: "Slide 25",
          deckLabel: "Module 2 / Lecture4",
          page: 25,
          image: "amla-slides/module2-lecture4/slide-25.png",
          title: "Hands-on: implementation, augmentation and loop",
          comment: "This slide marks the transition from architecture theory to notebooks: c-ResUNet implementation, data augmentation and training loop.",
          professor: "He clarified that the tutorial uses PyTorch and FastAI rather than TensorFlow/Keras, partly so students can compare styles.",
          remember: "In FastAI, the Learner combines model, data, loss, optimizer, metrics and training behavior.",
        },
        {
          label: "Transcript focus",
          deckLabel: "Module 2 / Lecture4",
          page: 25,
          image: "amla-slides/module2-lecture4/slide-25.png",
          title: "DataLoaders feed images and masks",
          comment: "For segmentation, the data loader must know how to read input images and their corresponding masks.",
          professor: "He said FastAI segmentation DataLoaders read data from disk, decide train/validation membership and apply transforms on the fly.",
          remember: "Augmented images are not precomputed and stored; transformations are applied during loading/training.",
        },
        {
          label: "Transcript focus",
          deckLabel: "Module 2 / Lecture4",
          page: 25,
          image: "amla-slides/module2-lecture4/slide-25.png",
          title: "Data augmentation must preserve the label",
          comment: "Rotations/resizing must be applied consistently to the image and mask. Lighting changes can modify the image while leaving a binary mask unchanged.",
          professor: "He explained that augmentation creates more data at low cost and enforces robustness to transformations.",
          remember: "Only use transformations that keep the biological label valid.",
        },
      ],
      lab: {
        title: "Mini-lab: data augmentation sanity check",
        objective: "Inspect augmentation examples and verify that transformed masks still correspond to transformed images.",
        href: "https://drive.google.com/file/d/12JHNS0uxEVT6cRwMw9TpKlj0_ZNtLQlg/view?usp=drivesdk",
        steps: [
          "Open the augmentation/training notebook resource.",
          "Display an image and its mask before transformation.",
          "Apply rotation, resize/crop or lighting transformations used in the notebook.",
          "Display transformed image and transformed mask together.",
          "Reject or flag any transformation that changes the meaning of the mask.",
        ],
        parameters: [
          "Rotation angle range.",
          "Crop or resize size.",
          "Zoom factor.",
          "Lighting/brightness jitter.",
          "Whether the transform applies to image, mask or both.",
        ],
        outputs: [
          "Before/after image-mask pairs.",
          "Examples of valid invariance.",
          "A short note on which transformations are safe for Fluocells.",
        ],
        explain: [
          "Why the same geometric transform must affect both image and mask.",
          "Why augmentation helps with few data and model robustness.",
          "Why not every image transformation is biologically valid.",
        ],
      },
    },
    {
      range: "Module 2 / Lecture4 slides 26-33",
      title: "Loss functions for imbalanced segmentation",
      intro: "The loss section is not formula trivia. It is about choosing what the optimization process should care about in a highly imbalanced mask problem.",
      slides: [
        {
          label: "Slides 26-27",
          deckLabel: "Module 2 / Lecture4",
          page: 27,
          image: "amla-slides/module2-lecture4/slide-27.png",
          title: "Loss choice changes training",
          comment: "Loss measures performance during learning and determines how weights are updated.",
          professor: "He said every loss highlights some characteristics and hides others.",
          remember: "Tie your loss function to task, data and analysis objective.",
        },
        {
          label: "Slide 28",
          deckLabel: "Module 2 / Lecture4",
          page: 28,
          image: "amla-slides/module2-lecture4/slide-28.png",
          title: "BCE: natural but imbalance-sensitive",
          comment: "Binary cross entropy fits pixel-level binary classification but can be dominated by background pixels.",
          professor: "He warned that the many background pixels can influence the loss more than the cell pixels you care about.",
          trap: "A low BCE does not automatically mean good cell segmentation.",
        },
        {
          label: "Slides 29-30",
          deckLabel: "Module 2 / Lecture4",
          page: 30,
          image: "amla-slides/module2-lecture4/slide-30.png",
          title: "Weighted BCE and focal loss",
          comment: "Weighted BCE compensates class imbalance; focal loss gives less weight to easy cases and focuses difficult examples.",
          professor: "He connected focal loss to putting more focus on examples where the model was previously wrong.",
          remember: "These losses are responses to imbalance and hard examples.",
        },
        {
          label: "Slide 31",
          deckLabel: "Module 2 / Lecture4",
          page: 31,
          image: "amla-slides/module2-lecture4/slide-31.png",
          title: "Dice coefficient and Dice loss",
          comment: "Dice coefficient measures overlap. Dice loss inverts the objective so training can minimize it.",
          professor: "He explicitly contrasted Dice coefficient and Dice loss: coefficient closer to 1 is better; loss closer to 0 is better.",
          remember: "Do not mix metric direction with loss direction.",
        },
        {
          label: "Slides 32-33",
          deckLabel: "Module 2 / Lecture4",
          page: 33,
          image: "amla-slides/module2-lecture4/slide-33.png",
          title: "Project takeaway: justify choices",
          comment: "The project should explain why the selected model, loss and training strategy fit the data challenges.",
          professor: "He said to adapt model, training settings and loss to your data, and to tell the reader why.",
          remember: "Advanced work is not just using a loss; it is justifying the loss.",
        },
      ],
    },
    {
      range: "Module 2 / Lecture4 slides 34-35 + transcript training loop",
      title: "Training loop, learning rate and performance assessment",
      intro: "The last part is about how to read training behavior and how to avoid over-interpreting a single metric or a single epoch.",
      slides: [
        {
          label: "Slide 34",
          deckLabel: "Module 2 / Lecture4",
          page: 34,
          image: "amla-slides/module2-lecture4/slide-34.png",
          title: "Training with Dice loss and inspection",
          comment: "The hands-on moves from training with Dice loss to visual inspection and detection/counting/segmentation performance.",
          professor: "He explained the FastAI loop: fit, epochs, batches, prediction, loss, gradients, backpropagation and weight updates.",
          remember: "Training curves are useful, but visual prediction checks are essential in image segmentation.",
        },
        {
          label: "Transcript focus",
          deckLabel: "Module 2 / Lecture4",
          page: 34,
          image: "amla-slides/module2-lecture4/slide-34.png",
          title: "Learning rate finder and fit one cycle",
          comment: "FastAI can suggest a learning rate by watching how loss changes during short exploratory training.",
          professor: "He cautioned that one epoch is often not enough to compare fit strategies; use a reasonable training run before drawing conclusions.",
          remember: "Learning rate is a training decision, not a default to ignore.",
        },
        {
          label: "Transcript focus",
          deckLabel: "Module 2 / Lecture4",
          page: 34,
          image: "amla-slides/module2-lecture4/slide-34.png",
          title: "Callbacks personalize training",
          comment: "Callbacks can log metrics, stop early, save the best model or change learning rate during training.",
          professor: "He gave early stopping as an example of a callback that reacts when improvement stalls.",
          trap: "Stopping too early can be wrong: he described a case where useful improvement appeared only after many quiet epochs.",
        },
        {
          label: "Slide 35",
          deckLabel: "Module 2 / Lecture4",
          page: 35,
          image: "amla-slides/module2-lecture4/slide-35.png",
          title: "Performance assessment",
          comment: "The final slide asks for convergence/overfitting checks, multiple metrics, baseline comparison, error analysis and interpretation.",
          professor: "He emphasized that several metrics can reveal differences that loss alone hides.",
          remember: "For the project, report numbers and show where predictions work or fail.",
        },
      ],
      lab: {
        title: "Mini-lab: read a segmentation training run",
        objective: "Use the training notebook to interpret Dice-loss training, validation behavior, callbacks and qualitative predictions.",
        href: "https://drive.google.com/file/d/12JHNS0uxEVT6cRwMw9TpKlj0_ZNtLQlg/view?usp=drivesdk",
        steps: [
          "Open the training loop notebook and identify the hyperparameter/configuration cell.",
          "Find the DataLoaders, model and Learner creation.",
          "Inspect the selected loss, optimizer, metrics and callbacks.",
          "Run or inspect the learning-rate finder output.",
          "Read training/validation curves across epochs.",
          "Display predicted masks over original images and compare them with ground truth.",
        ],
        parameters: [
          "Batch size.",
          "Crop/resize size.",
          "Loss function.",
          "Learning rate.",
          "Optimizer.",
          "Number of epochs.",
          "Early stopping and learning-rate scheduler settings.",
          "Prediction threshold and post-processing settings.",
        ],
        outputs: [
          "Training and validation loss curves.",
          "Dice coefficient or other segmentation metrics.",
          "Predicted masks and overlays.",
          "Examples of false positives, missed cells, merged cells and label ambiguity.",
          "Best saved epoch if callbacks are enabled.",
        ],
        explain: [
          "Why a flat loss for several epochs does not always mean training is hopeless.",
          "Why multiple metrics may disagree even when the loss looks similar.",
          "Why visual inspection is part of performance assessment, not an optional illustration.",
        ],
      },
    },
  ],
  professorEmphasis: [
    "Semantic segmentation turns Fluocells into binary classification at pixel level.",
    "Instance segmentation is more naturally aligned with counting separate objects, but this workflow uses semantic segmentation.",
    "The predicted heatmap still needs thresholding to become a binary mask.",
    "U-Net combines downsampling for patterns with upsampling and skip connections for localization.",
    "FastAI is used as a PyTorch interface; the lesson is also meant to expose students to a different style than Keras.",
    "Data augmentation must transform masks consistently with images when the transformation is geometric.",
    "Loss functions have trade-offs; each highlights some aspects and hides others.",
    "Do not stop training or change the whole setup too quickly just because early epochs look flat.",
    "Project evaluation should include convergence, overfitting, multiple metrics, baselines, error analysis and interpretation.",
  ],
  commonTraps: [
    "Confusing semantic segmentation with instance segmentation.",
    "Forgetting the threshold between probability heatmap and binary mask.",
    "Calling Dice coefficient and Dice loss the same thing without noting direction: high coefficient is good, low loss is good.",
    "Treating BCE as automatically appropriate despite extreme background/cell imbalance.",
    "Applying image augmentation without applying the same geometric transform to the mask.",
    "Thinking FastAI hides the training loop completely; it wraps the same model/data/loss/optimizer logic.",
    "Drawing conclusions from one epoch or one metric.",
    "Reporting segmentation performance without visual inspection of predicted masks.",
  ],
  quickQuiz: [
    {
      question: "In this class, what are the two pixel classes for semantic segmentation?",
      answer: "Background is class 0 and cell is class 1.",
    },
    {
      question: "What is the difference between semantic and instance segmentation?",
      answer: "Semantic segmentation labels pixels by class; instance segmentation separates individual objects of the same class.",
    },
    {
      question: "Why is a threshold needed after the model predicts a heatmap?",
      answer: "The heatmap gives probabilities; thresholding turns them into a binary predicted mask.",
    },
    {
      question: "What do U-Net skip connections help recover?",
      answer: "Spatial/localization detail that can be lost during downsampling.",
    },
    {
      question: "What does the FastAI Learner combine?",
      answer: "Model, DataLoaders, loss, optimizer, metrics and training behavior such as callbacks.",
    },
    {
      question: "Why must rotations be applied to both image and mask?",
      answer: "Because the mask is the label for the image; geometric misalignment corrupts supervision.",
    },
    {
      question: "Why can BCE be problematic for Fluocells?",
      answer: "Most pixels are background, so the loss can be dominated by background performance.",
    },
    {
      question: "Why should performance assessment include visual inspection?",
      answer: "Metrics can hide merged cells, split cells, artifacts or biologically suspicious predictions.",
    },
  ],
  examQuestions: [
    {
      id: "l10-q1",
      question: "A Fluocells model outputs a probability for each pixel, then a threshold produces a binary mask. Which task framing is this?",
      options: [
        "Semantic segmentation",
        "Image-level regression",
        "Hard-voting ensemble classification",
        "Principal component analysis",
      ],
      correct: 0,
      explanation: "Each pixel is classified as background or cell, then thresholded into a mask.",
    },
    {
      id: "l10-q2",
      question: "Why is instance segmentation methodologically attractive for cell counting?",
      options: [
        "It ignores object boundaries, which reduces annotation cost.",
        "It predicts one scalar count without localization.",
        "It can distinguish individual objects of the same class.",
        "It removes the need for any loss function.",
      ],
      correct: 2,
      explanation: "Counting needs individual objects; instance segmentation preserves object identity.",
    },
    {
      id: "l10-q3",
      question: "A student applies a random crop to Fluocells images but leaves masks unchanged. What is the main problem?",
      options: [
        "The model will train faster but overfit less.",
        "The label no longer aligns with the input image.",
        "The task changes from segmentation to regression.",
        "The loss function becomes Dice coefficient automatically.",
      ],
      correct: 1,
      explanation: "Geometric augmentations must preserve image-mask alignment.",
    },
    {
      id: "l10-q4",
      question: "Which statement best captures the professor's warning about losses?",
      options: [
        "All segmentation losses optimize the same behavior.",
        "Loss choice is irrelevant once the architecture is c-ResUNet.",
        "Each loss highlights some characteristics and hides others.",
        "BCE is always the best loss for imbalanced masks.",
      ],
      correct: 2,
      explanation: "Losses encode different priorities, so they must be justified against the data and objective.",
    },
    {
      id: "l10-q5",
      question: "During training, Dice loss is low but visual predictions merge touching cells. What should you conclude?",
      options: [
        "The metric is enough; no further analysis is needed.",
        "Visual inspection has revealed a counting-relevant error that metrics may not fully capture.",
        "The task was actually image classification.",
        "The only fix is to delete the baseline.",
      ],
      correct: 1,
      explanation: "Merged objects can hurt counting even when aggregate segmentation metrics look acceptable.",
    },
    {
      id: "l10-q6",
      question: "What is the strongest project-level reason to compare c-ResUNet against thresholding?",
      options: [
        "Thresholding is always a deep learning model.",
        "It quantifies what is gained by using the more complex model.",
        "It avoids the need for validation data.",
        "It guarantees the model is interpretable.",
      ],
      correct: 1,
      explanation: "A meaningful baseline makes the added value of the complex method visible.",
    },
  ],
  checklistTitle: "What to remember after this lesson",
  studyChecklist: [
    "Explain why Fluocells is framed as semantic segmentation for the deep-learning workflow.",
    "Separate semantic segmentation, instance segmentation and post-processing for counting.",
    "Trace U-Net from encoder to decoder and explain the role of skip connections.",
    "List c-ResUNet adaptations and connect them to fluorescence microscopy.",
    "Recognize FastAI objects: DataLoaders, Learner, fit, callbacks and metrics.",
    "Check whether augmentation preserves image-mask consistency.",
    "Justify the loss function based on class imbalance and segmentation objective.",
    "Evaluate with curves, metrics, baselines, visual inspection and error analysis.",
  ],
};
