export const lessonContent = {
  id: "amla-2026-04-20-neural-networks",
  extractionStatus: "source-based complete draft",
  objectives: [
    "Use the Basic written-test feedback as a study calibration tool instead of only as an administrative update.",
    "Explain how the MNIST1 sklearn workflow motivates the Keras MNIST2A continuation.",
    "Build a simple Keras Sequential classifier for MNIST at the conceptual level: data, layers, compile, fit, validation, evaluate.",
    "Distinguish binary MNIST classification from multiclass digit classification.",
    "Read `model.summary()` output in terms of layer shapes and trainable parameters.",
    "Interpret Keras training logs, validation metrics, repeated `.fit()` calls, batch size and epochs correctly.",
    "Separate validation behavior during training from final test evaluation.",
  ],
  coreConcepts: [
    {
      title: "Exam calibration",
      body: "The first part of class used the Basic test to calibrate how students judge their preparation, how carefully they submit and how future tests may become less forgiving.",
      keywords: ["written test", "self-check", "do not rush"],
    },
    {
      title: "MNIST1 to MNIST2A",
      body: "MNIST1 used sklearn and a binary classifier mindset; MNIST2A keeps the same dataset but moves to a Keras neural network for multiclass classification.",
      keywords: ["sklearn", "Keras", "same data"],
    },
    {
      title: "Sequential model",
      body: "Sequential is the right first API when layers form a simple chain: one input path, dense hidden layer, output layer.",
      keywords: ["Sequential", "Dense", "linear stack"],
    },
    {
      title: "Softmax output",
      body: "For MNIST multiclass classification, the final layer should produce one score/probability per digit class, then the largest probability gives the predicted digit.",
      keywords: ["10 classes", "probabilities", "argmax"],
    },
    {
      title: "Compile before fit",
      body: "Keras needs the training recipe before fitting: optimizer, loss and metrics. If compile is missing, the error message points to the missing training information.",
      keywords: ["compile", "optimizer", "loss"],
    },
    {
      title: "Validation split",
      body: "Without validation settings, Keras logs metrics on the training data. Adding validation data or validation_split gives development-time evidence beyond training performance.",
      keywords: ["val_loss", "val_accuracy", "development"],
    },
    {
      title: "Repeated fit",
      body: "Calling `.fit()` again on the same model continues from the last weights. To restart from scratch, reinitialize the model.",
      keywords: ["checkpoint", "epochs", "reinitialize"],
    },
    {
      title: "Evaluate",
      body: "`evaluate()` is the final check on test data after model choices are fixed. It should not be confused with validation metrics used during tuning.",
      keywords: ["test set", "final loss", "generalization"],
    },
  ],
  walkthroughSections: [
    {
      range: "Transcript opening + Module 2 / Lecture2_tmp slides 15-18",
      title: "Use the written test as feedback, then return to the hands-on thread",
      intro: "The lecture starts with Basic-test feedback. This is not model theory, but it matters for study strategy: do not rush, calibrate your self-assessment and expect future tests to require more care.",
      slides: [
        {
          label: "Slide 15",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 15,
          image: "amla-slides/lecture2/slide-15.png",
          title: "Course stack choice: TensorFlow/Keras + sklearn",
          comment: "This slide closes the framework-choice discussion: many tools exist, but the course will use TensorFlow/Keras plus sklearn as the practical baseline.",
          professor: "Before Luca resumed the notebook, Daniele warned that later written tests may be less forgiving and students should not submit too quickly.",
          remember: "For AMLA, study both implementation choices and exam discipline: read carefully, use the time, and check answers.",
        },
        {
          label: "Slide 18",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 18,
          image: "amla-slides/lecture2/slide-18.png",
          title: "MNIST remains the benchmark bridge",
          comment: "The class returns to MNIST because the dataset is already familiar enough to focus on model workflow rather than dataset discovery.",
          professor: "Luca said the goal was to walk through notebook cells after the exam, then leave a few questions for students to solve.",
          remember: "Do not treat this as a brand-new dataset. The point is comparing workflows on the same data.",
        },
      ],
    },
    {
      range: "Module 2 / Lecture2_tmp slides 21-44",
      title: "Recall the sklearn MNIST1 baseline before upgrading",
      intro: "These slides are the baseline context. The full class emphasis on 20/04 is Keras, but the professor explicitly compares it to the earlier sklearn MNIST workflow.",
      slides: [
        {
          label: "Slide 21",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 21,
          image: "amla-slides/lecture2/slide-21.png",
          title: "MNIST1 notebook and code arrows",
          comment: "The first MNIST notebook used guided code arrows and sklearn. Keep this as the baseline style: more guided, more familiar, more Basic-like.",
          professor: "Luca reminded students that Friday's tutorial used `SGDClassifier` on MNIST before moving to the neural-network version.",
          remember: "Use MNIST1 to remember evaluation vocabulary before reading Keras logs.",
        },
        {
          label: "Slides 22, 25-26",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 22,
          image: "amla-slides/lecture2/slide-22.png",
          title: "MNIST structure: images, labels and split",
          comment: "MNIST has 70k labeled digit images. With sklearn you fetch data, inspect it and perform or understand the train/test split.",
          professor: "For Keras, he highlighted that `keras.datasets.mnist.load_data()` already returns train/test arrays, unlike the sklearn flow.",
          remember: "Always know where train/test split comes from. Different libraries hide different steps.",
          trap: "Do not assume two libraries expose the same dataset in the same shape or split format.",
        },
        {
          label: "Slides 37-44",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 37,
          image: "amla-slides/lecture2/slide-37.png",
          title: "Binary-classifier metrics from MNIST1",
          comment: "Confusion matrix, precision, recall, F1, ROC and AUC belong to the binary-classifier recap. They are still useful, but MNIST2A shifts to multiclass softmax.",
          professor: "The transcript explicitly contrasts the previous five-vs-all binary classifier with the new multiclass digit classifier.",
          remember: "Before choosing metrics and output layer, decide whether the task is binary, multiclass or multilabel.",
          trap: "A softmax multiclass model is not the same setup as a one-vs-rest binary classifier.",
        },
      ],
    },
    {
      range: "Module 2 / Lecture2_tmp slides 55-68",
      title: "Build the Keras mental model: library, API and layers",
      intro: "This is the technical core of the day. The notebook moves from sklearn to `tensorflow.keras`, then builds a shallow Sequential neural network.",
      slides: [
        {
          label: "Slides 55-58",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 55,
          image: "amla-slides/lecture2/slide-55.png",
          title: "TensorFlow/Keras as the course implementation layer",
          comment: "TensorFlow provides the backend and Keras gives a high-level API for building, training and evaluating neural networks.",
          professor: "Luca noted that standalone Keras and `tensorflow.keras` are usually aligned enough for course use, but versions can differ.",
          remember: "When reading code, note whether it imports `keras` directly or `tensorflow.keras`.",
        },
        {
          label: "Slide 62",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 62,
          image: "amla-slides/lecture2/slide-62.png",
          title: "Keras interface for a shallow NN",
          comment: "This is the bridge from definitions to code: a simple shallow neural network can be represented with a small set of Keras objects.",
          professor: "He framed this as a first taste of how Keras looks, not as a full theory replacement.",
          remember: "Read this as workflow practice: define, compile, fit, evaluate.",
        },
        {
          label: "Slides 64-66",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 64,
          image: "amla-slides/lecture2/slide-64.png",
          title: "Input, hidden and output layers",
          comment: "The model chain is simple: raw inputs enter, dense hidden layers transform them and the output layer maps to digit classes.",
          professor: "He asked students to recall Sequential vs Functional: Sequential is a linear stack; Functional allows branches and more flexible structures.",
          remember: "Use Sequential for this MNIST model because the layer flow is one clear chain.",
        },
        {
          label: "Slide 68",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 68,
          image: "amla-slides/lecture2/slide-68.png",
          title: "Input shape must match the flattened data",
          comment: "The network expects vectors of length 784 because each 28 x 28 image is flattened. Keras needs this shape to infer downstream layer shapes.",
          professor: "He showed that if the input shape is not known, `summary()` cannot compute shapes and parameter counts properly.",
          remember: "For dense MNIST, reshape 28 x 28 images into 784-dimensional vectors before fitting.",
          trap: "If the data shape and first layer disagree, the model may fail before training starts.",
        },
      ],
      lab: {
        title: "Mini-lab: inspect the MNIST2A model before training",
        todo: "The transcript says the notebook link was shared in class as MNIST 2 Part A, but no standalone URL was visible in the extracted sources.",
        objective: "Before fitting, reconstruct the model setup and explain what each Keras object is doing.",
        steps: [
          "Load MNIST with `keras.datasets.mnist.load_data()`.",
          "Check image and label shapes for train and test arrays.",
          "Flatten images from 28 x 28 to 784 features if using Dense layers.",
          "Define a Sequential model with one hidden Dense layer and one 10-unit output layer.",
          "Run or read `model.summary()` and identify output shapes and parameter counts.",
        ],
        parameters: ["hidden units", "activation", "input shape", "output units"],
        outputs: ["array shapes", "model.summary()", "trainable parameter counts"],
        explain: [
          "Why this is multiclass classification, not the previous binary five-vs-rest setup.",
          "Why the output layer needs 10 units.",
          "Why specifying input shape helps Keras infer the rest of the model.",
        ],
      },
    },
    {
      range: "Module 2 / Lecture2_tmp slides 72-81",
      title: "Train responsibly: compile, fit, validation and evaluate",
      intro: "The professor spent time on the training lifecycle because most Keras mistakes are not exotic. They are simple confusions about what the logs mean.",
      slides: [
        {
          label: "Slide 72",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 72,
          image: "amla-slides/lecture2/slide-72.png",
          title: "Read summary as shapes plus parameters",
          comment: "The summary tells you output shapes and parameter counts. It is the first check that your architecture is what you intended.",
          professor: "He pointed out that the parameter count follows from the previous layer size plus bias terms.",
          remember: "If a parameter count surprises you, pause before training.",
        },
        {
          label: "Slides 74-75",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 74,
          image: "amla-slides/lecture2/slide-74.png",
          title: "compile(): optimizer, loss and metrics",
          comment: "Compile gives Keras the training recipe. For multiclass softmax, the loss must match class-probability training.",
          professor: "Luca intentionally hit a missing-compile error during `.fit()` and used the error message to explain what information was missing.",
          remember: "Architecture alone is not trainable; compile tells Keras how to optimize.",
          trap: "Do not confuse metrics with loss. Loss drives training; metrics monitor performance.",
        },
        {
          label: "Slides 77-80",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 80,
          image: "amla-slides/lecture2/slide-80.png",
          title: "fit() logs training and optional validation metrics",
          comment: "Without validation settings, logs are training metrics. With `validation_split`, Keras adds `val_` metrics computed on held-out validation data.",
          professor: "He asked whether logged accuracy/loss were training, validation or test metrics, because students often collapse them.",
          remember: "Training logs are not final generalization evidence. Use validation during development and test for the final check.",
          trap: "Do not report `val_accuracy` as final test accuracy if you used it to tune choices.",
        },
        {
          label: "Slide 81",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 81,
          image: "amla-slides/lecture2/slide-81.png",
          title: "evaluate(): final test performance",
          comment: "Evaluate takes the test images and labels and returns final loss and accuracy. In class the simple network was around 92 percent accuracy.",
          professor: "He explicitly said this is the performance you expect to generalize to previously unseen samples.",
          remember: "Final evaluation comes after model choices are fixed.",
        },
      ],
    },
    {
      range: "Module 2 / Lecture2_tmp slides 82-90",
      title: "Diagnostics and autonomy: history, repeated fit and less guidance",
      intro: "The end of the lecture is about becoming less dependent on guided slides: save the training history, plot it, understand repeated `.fit()`, then work on MNIST2A questions.",
      slides: [
        {
          label: "Slides 82-84",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 84,
          image: "amla-slides/lecture2/slide-84.png",
          title: "History plots reveal overfitting better than tables",
          comment: "A table of epoch values can be hard to read. Saving the result of `.fit()` lets you plot training and validation curves.",
          professor: "He said looking only at numbers can be confusing and that visualization is often the better diagnostic.",
          remember: "If training loss decreases while validation loss increases, discuss overfitting instead of celebrating training accuracy.",
        },
        {
          label: "Slide 87",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 87,
          image: "amla-slides/lecture2/slide-87.png",
          title: "We play before knowing every detail",
          comment: "The lecture explicitly allows experimenting before full theory, but only as a path to better explanation.",
          professor: "He warned that repeated `.fit()` continues from the last checkpoint; to restart from scratch, reinitialize the model.",
          remember: "Calling `.fit()` twice for 10 epochs is like continuing to epochs 11-20, not a fresh repeat.",
          trap: "Do not compare two runs if one starts from random weights and the other starts from already trained weights.",
        },
        {
          label: "Slides 88-90",
          deckLabel: "Module 2 / Lecture2_tmp",
          page: 90,
          image: "amla-slides/lecture2/slide-90.png",
          title: "MNIST2A: less guidance from here",
          comment: "The deck says there are no more arrows and supporting slides: students should work through the notebook with less in-class guidance.",
          professor: "Luca left students time to work on the notebook questions in groups and then do a short wrap-up.",
          remember: "This is the Advanced-course pattern: run, inspect, explain, and ask why the result changed.",
        },
      ],
      lab: {
        title: "Mini-lab: train, validate and evaluate MNIST2A",
        todo: "Notebook URL pending; use the shared MNIST2A notebook from class if you have it.",
        objective: "Run or mentally rehearse the complete Keras training lifecycle and identify what each output means.",
        steps: [
          "Compile the model with optimizer, loss and accuracy metric.",
          "Fit for 10 epochs with batch size 128.",
          "Repeat with a validation split and identify `val_loss` and `val_accuracy`.",
          "Store the result of `.fit()` in a history variable and plot training vs validation curves.",
          "Call `.evaluate()` once on the test data.",
          "Restart from scratch only by rebuilding/reinitializing the model.",
        ],
        parameters: ["epochs", "batch size", "validation split", "hidden-layer size", "optimizer", "loss"],
        outputs: ["training loss/accuracy", "validation loss/accuracy", "history curves", "test loss/accuracy"],
        explain: [
          "Why validation metrics appear only after validation data is provided.",
          "Why repeated `.fit()` continues training from current weights.",
          "Why smaller batch size changes the number of update steps per epoch.",
          "Why final test evaluation is different from validation monitoring.",
        ],
      },
    },
  ],
  slidePath: [
    {
      range: "Test feedback",
      title: "Study calibration",
      concept: "The Basic written test is feedback for exam behavior and self-assessment.",
      intuition: "Use the score and your expected score to detect whether you overestimate or underestimate preparation.",
      professor: "He warned not to rush submission and said future tests may be slightly more complex or less forgiving.",
      remember: "AMLA exam preparation is not only knowing facts; it is also careful execution.",
    },
    {
      range: "MNIST1 to MNIST2A",
      title: "Same dataset, new workflow",
      concept: "The class moves from sklearn SGDClassifier to a Keras neural network on MNIST.",
      intuition: "Keeping the data fixed makes library and model differences easier to see.",
      professor: "He compared sklearn loading/splitting with Keras `load_data()` behavior.",
      remember: "Different tools hide different steps; verify shapes and splits.",
    },
    {
      range: "Keras model",
      title: "Sequential Dense classifier",
      concept: "Use a linear stack of Dense layers with ReLU hidden activation and softmax output.",
      intuition: "Inputs are flattened pixel vectors; output units correspond to digit classes.",
      professor: "He stressed the difference between binary five-vs-rest classification and multiclass classification.",
      remember: "Output layer design follows the target type.",
    },
    {
      range: "Training lifecycle",
      title: "compile, fit, validation, evaluate",
      concept: "Compile defines the recipe, fit trains, validation monitors, evaluate tests.",
      intuition: "Each method answers a different question about the model.",
      professor: "He used a missing-compile error and a training/validation question as teaching moments.",
      remember: "Never mix up training, validation and test metrics.",
    },
  ],
  professorEmphasis: [
    "Future written tests may be less forgiving; use the available time and recheck answers.",
    "The Basic test should help you calibrate your preparation, not just give a number.",
    "The 20/04 technical work is a notebook walk-through after the exam, so the pace is intentionally lighter.",
    "Keras loads MNIST differently from sklearn; understand what each library does under the hood.",
    "Sequential is for a simple linear stack; Functional is for branches or more complex graphs.",
    "Softmax output with 10 units fits multiclass MNIST; the earlier five-vs-rest classifier was binary.",
    "If `.fit()` fails because compile was not run, read the error: Keras is missing optimizer/loss/metric information.",
    "Validation metrics are not final test metrics.",
    "Repeated `.fit()` continues training from the current weights unless the model is reinitialized.",
  ],
  commonTraps: [
    "Assigning this class to Module 1 Lecture3 because of numbering; the content is Module 2/Lecture2_tmp plus MNIST2A notebook.",
    "Thinking Keras and sklearn load and split MNIST in exactly the same way.",
    "Using a binary-classifier mental model for a 10-class softmax problem.",
    "Forgetting to flatten 28 x 28 images before using plain Dense layers.",
    "Calling `model.summary()` before Keras can infer input shapes, then misunderstanding the missing shapes.",
    "Running `.fit()` repeatedly and assuming each run starts from scratch.",
    "Treating validation accuracy as final test accuracy.",
    "Reporting loss/accuracy without explaining which data split produced them.",
  ],
  miniLab: {
    title: "MNIST2A Keras lifecycle",
    href: null,
    todo: "The transcript says the MNIST2A notebook link was shared in class, but the extracted material does not expose the URL.",
    objective: "Use the shared notebook if available; otherwise rehearse the lifecycle from the slides and transcript.",
    steps: [
      "Load MNIST through Keras and inspect train/test shapes.",
      "Flatten and rescale image arrays for a Dense network.",
      "Build a Sequential model with Dense hidden layer and softmax output.",
      "Compile with optimizer, loss and accuracy metric.",
      "Fit with and without validation split, then compare logged metrics.",
      "Store `history` and plot train/validation curves.",
      "Evaluate on the test data once choices are fixed.",
    ],
    parameters: ["input shape", "hidden units", "activation", "optimizer", "loss", "epochs", "batch size", "validation split"],
    outputs: ["model.summary()", "training logs", "history curves", "test loss", "test accuracy"],
    explain: [
      "Why the notebook uses `tensorflow.keras`.",
      "Why output dimension is 10.",
      "Why `compile()` is required before `fit()`.",
      "Why repeated `fit()` continues the same training run.",
      "Why validation and test data answer different questions.",
    ],
  },
  quickQuiz: [
    {
      question: "Why did the professor spend time discussing the Basic written test at the start?",
      answer: "To calibrate student expectations: future tests may be less forgiving, students should not rush, and the Basic score helps compare perceived preparation with actual performance.",
    },
    {
      question: "What is the key dataset difference between the previous sklearn MNIST tutorial and this Keras tutorial?",
      answer: "The dataset is still MNIST, but Keras loads it through `keras.datasets.mnist.load_data()` and already returns train/test arrays, while the sklearn workflow used a different loading and splitting path.",
    },
    {
      question: "Why is the 20/04 MNIST model multiclass rather than binary?",
      answer: "It predicts one of the ten digit classes 0-9. The earlier five-vs-rest example was a binary classifier.",
    },
    {
      question: "What does `model.compile()` specify?",
      answer: "It specifies how training should happen: optimizer, loss function and metrics to monitor.",
    },
    {
      question: "What does `validation_split` change in the Keras logs?",
      answer: "It makes Keras set aside part of the training data for validation and report `val_loss` and `val_accuracy` during training.",
    },
    {
      question: "What happens if you call `.fit()` again on the same compiled/trained model?",
      answer: "Training continues from the current weights; it does not start from scratch unless the model is rebuilt or reinitialized.",
    },
    {
      question: "What is `evaluate()` used for?",
      answer: "It computes final loss/metrics on test data after model choices are fixed.",
    },
  ],
  examQuestions: [
    {
      id: "l03-mcq-1",
      question: "A student reports the accuracy printed during `fit()` without validation data as final model performance. What is the best critique?",
      options: [
        "It is fine because Keras always uses the test set during fit.",
        "It is training-set feedback, not final generalization evidence.",
        "It must be validation accuracy because all Keras metrics start with `val_`.",
        "It is impossible to compute accuracy during training.",
      ],
      correct: 1,
      explanation: "Without validation data or validation_split, the metrics shown during fit are computed on training data.",
    },
    {
      id: "l03-mcq-2",
      question: "In the MNIST2A setup, why is a 10-unit softmax output appropriate?",
      options: [
        "Because the task is binary five-vs-all classification.",
        "Because each 28 x 28 image has 10 pixels after flattening.",
        "Because the model predicts one probability-like score for each digit class.",
        "Because softmax removes the need for a loss function.",
      ],
      correct: 2,
      explanation: "MNIST multiclass classification has ten possible digit labels, so the output layer needs one unit per class.",
    },
    {
      id: "l03-mcq-3",
      question: "A model is defined with Dense layers, then `model.fit()` raises an error because no training recipe is known. What did the student likely skip?",
      options: ["model.summary()", "model.compile()", "validation_split", "model.evaluate()"],
      correct: 1,
      explanation: "Compile supplies optimizer, loss and metrics. Keras cannot train normally without that information.",
    },
    {
      id: "l03-mcq-4",
      question: "You run `.fit(epochs=10)` twice on the same model without rebuilding it. How should you interpret the second call?",
      options: [
        "A fresh independent training run from new random weights.",
        "A continuation from the weights learned after the first call.",
        "A test-set evaluation step.",
        "A reset of all optimizer and layer parameters.",
      ],
      correct: 1,
      explanation: "The professor emphasized that repeated fit continues from the last checkpoint unless the model is reinitialized.",
    },
    {
      id: "l03-mcq-5",
      question: "Validation loss rises while training loss falls. Which interpretation best matches the lecture?",
      options: [
        "The model may be overfitting and should be inspected with validation curves.",
        "The model is certainly improving because training loss is falling.",
        "The validation set should be merged into the test set.",
        "The optimizer must be missing because validation loss exists.",
      ],
      correct: 0,
      explanation: "Diverging training and validation curves are a warning sign; the lecture emphasized plotting history to see this.",
    },
  ],
  checklistTitle: "What to take from L03",
  studyChecklist: [
    "Use the 20/04 transcript as a Keras notebook walkthrough, not a separate Module 1 theory lecture.",
    "Explain why MNIST2A is multiclass and how this changes the output layer.",
    "State the Keras lifecycle in order: load, inspect, reshape, define, summary, compile, fit, validate, evaluate.",
    "Read `model.summary()` as output shapes plus parameter counts.",
    "Separate training logs, validation curves and final test evaluation.",
    "Remember that repeated `.fit()` continues training from current weights.",
    "Keep notebook TODO explicit until the actual shared Colab/Drive link is recovered.",
  ],
};
