export const lessonContent = {
  id: "amla-2026-05-28-explainable-ai",
  extractionStatus: "source-based complete draft",
  objectives: [
    "Explain why high model performance is not enough when decisions need justification.",
    "Distinguish interpretability as a model property from explainability as post-hoc analysis.",
    "Classify XAI methods by timing, communication style and granularity.",
    "Use feature importance carefully and recognize its limits with interactions and correlated features.",
    "Explain SHAP as fair feature credit assignment based on marginal contributions.",
    "Explain LIME as a local surrogate approximation around one prediction.",
    "Compare SHAP and LIME by scope, guarantees, consistency, cost and use case.",
    "Avoid causal claims from feature importance, SHAP or LIME explanations.",
  ],
  coreConcepts: [
    {
      title: "Interpretability",
      body: "An intrinsic property of a model whose mechanics can be understood by design.",
      keywords: ["linear coefficients", "decision tree paths", "white box"],
    },
    {
      title: "Explainability",
      body: "Post-hoc techniques that explain predictions of models that are not directly interpretable.",
      keywords: ["SHAP", "LIME", "feature importance"],
    },
    {
      title: "Black box model",
      body: "A model whose internal decision process is opaque or too complex to follow directly.",
      keywords: ["neural networks", "CNN", "transformers"],
    },
    {
      title: "Feature importance",
      body: "A global score of how influential each feature is for predictions, often model-dependent.",
      keywords: ["global", "ranking", "model dependency"],
    },
    {
      title: "SHAP",
      body: "A game-theory based method that assigns each feature a contribution to a prediction.",
      keywords: ["Shapley values", "marginal contribution", "local to global"],
    },
    {
      title: "LIME",
      body: "A local method that perturbs one observation, fits a simple surrogate nearby and interprets that surrogate.",
      keywords: ["local", "perturbation", "surrogate model"],
    },
    {
      title: "Local explanation",
      body: "An explanation for one specific prediction or observation.",
      keywords: ["single instance", "why this case", "nearby neighborhood"],
    },
    {
      title: "Global explanation",
      body: "A summary of model behavior across many observations or the full dataset.",
      keywords: ["overall behavior", "averaging", "feature ranking"],
    },
  ],
  walkthroughSections: [
    {
      range: "Module 2 / Lecture5 slides 1-15 + project preface",
      title: "Why explanation matters beyond performance",
      intro: "Before the technical XAI material, the professor reminded students that the Advanced project requires mature interpretation, transparent code use and explanations they can defend orally.",
      slides: [
        {
          label: "Slide 1",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 1,
          image: "amla-slides/module2-lecture5-xai/slide-01.png",
          title: "Interpretability and explainability in AI",
          comment: "This class is the XAI block of AMLA. It starts from why explanations matter and then introduces feature importance, SHAP and LIME.",
          professor: "At the beginning of the class, he also reviewed project expectations: advanced projects need more mature interpretation and advanced models.",
          remember: "For AMLA, do not only apply a model. Explain why it was chosen and how results should be interpreted.",
        },
        {
          label: "Slides 3-5",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 5,
          image: "amla-slides/module2-lecture5-xai/slide-05.png",
          title: "From white boxes to black boxes",
          comment: "Linear models and simple trees are easier to explain. Neural networks, complex ensembles and transformers usually trade interpretability for performance.",
          professor: "He framed this as a real trade-off: what is the right amount of interpretability and performance for the problem?",
          remember: "The acceptable trade-off depends on the stakes of the application.",
        },
        {
          label: "Slides 6-8",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 8,
          image: "amla-slides/module2-lecture5-xai/slide-08.png",
          title: "High performance can hide shortcuts",
          comment: "A model may classify correctly for the wrong reason, such as using background or spurious cues instead of the object.",
          professor: "He used the classic husky/wolf-style example: the model can detect snow or context, not the animal concept we think it learned.",
          remember: "A good metric is not proof that the model learned the right signal.",
        },
        {
          label: "Slides 10-14",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 14,
          image: "amla-slides/module2-lecture5-xai/slide-14.png",
          title: "Sensitive applications make transparency mandatory",
          comment: "Recommenders may be low stakes, but healthcare, courts, finance and public decision systems require more accountability.",
          professor: "He discussed bias in data and the COMPAS case to show that overall performance can hide harm to specific groups.",
          remember: "Bias can be invisible if you only report aggregate performance.",
        },
        {
          label: "Project preface",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 1,
          image: "amla-slides/module2-lecture5-xai/slide-01.png",
          title: "AI tools and project responsibility",
          comment: "The transcript includes a clear warning: tools can speed up work, but cannot replace your own interpretation or justification.",
          professor: "He said the useful question is: if this were an oral exam, could you explain why you used this strategy and interpret the results?",
          remember: "Be transparent about tools and make sure you can defend the final code and choices.",
        },
      ],
    },
    {
      range: "Module 2 / Lecture5 slides 16-25",
      title: "Interpretability versus explainability",
      intro: "This is the conceptual spine of the lecture. The two terms are related, but the professor explicitly warned not to use them as synonyms.",
      slides: [
        {
          label: "Slide 16",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 16,
          image: "amla-slides/module2-lecture5-xai/slide-16.png",
          title: "Two related but distinct concepts",
          comment: "Interpretability is intrinsic: you understand the mechanics by design. Explainability is post-hoc: you explain predictions after training.",
          professor: "He stated directly that interpretability and explainability are different concepts.",
          remember: "Linear coefficients are interpretability; SHAP/LIME are explainability.",
        },
        {
          label: "Slide 17",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 17,
          image: "amla-slides/module2-lecture5-xai/slide-17.png",
          title: "The explainability spectrum",
          comment: "Models and methods lie on a spectrum from directly interpretable to post-hoc explanation techniques.",
          professor: "He used CNNs as an example: we can define filters, but training decides what each filter actually learns.",
          trap: "Do not call a CNN interpretable just because you can list its layers.",
        },
        {
          label: "Slides 19-20",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 20,
          image: "amla-slides/module2-lecture5-xai/slide-20.png",
          title: "Why XAI is useful",
          comment: "XAI helps domain experts, ethics, bias identification, model improvement, regulatory compliance and trust.",
          professor: "He connected explanation to practical reasons: understanding failures, identifying bias and making model use acceptable.",
          remember: "XAI is not decorative. It supports debugging, accountability and trust.",
        },
        {
          label: "Slides 21-24",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 24,
          image: "amla-slides/module2-lecture5-xai/slide-24.png",
          title: "Explainability framework",
          comment: "XAI can happen before, during or after model building; it can use attributes, examples or counterexamples; and it can be local, global or group-level.",
          professor: "He emphasized local explanations for one observation versus global explanations for model behavior across data.",
          remember: "When describing an XAI method, say when it occurs, what form the explanation takes and what granularity it has.",
        },
        {
          label: "Slide 25",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 25,
          image: "amla-slides/module2-lecture5-xai/slide-25.png",
          title: "Exam-style distinction",
          comment: "This question checks the core distinction between interpretability and explainability.",
          professor: "In the transcript, he asked for the key difference and then reinforced the answer: intrinsic property versus after-the-fact strategy.",
          remember: "This is a likely short-answer or MCQ concept.",
        },
      ],
    },
    {
      range: "Module 2 / Lecture5 slides 26-34",
      title: "Tabular XAI and feature importance",
      intro: "The lecture narrows to tabular data so explanations can be connected to rows, columns, observations and features.",
      slides: [
        {
          label: "Slides 26-27",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 27,
          image: "amla-slides/module2-lecture5-xai/slide-27.png",
          title: "Rows as observations, columns as features",
          comment: "Tabular data makes XAI examples concrete because the attributes/features are explicit.",
          professor: "He used attributes, features, variables and predictors as related vocabulary for columns.",
          remember: "Many XAI methods are easiest to introduce on tabular data because features are named.",
        },
        {
          label: "Slides 28-30",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 28,
          image: "amla-slides/module2-lecture5-xai/slide-28.png",
          title: "Before, during and after model building",
          comment: "EDA happens before model building, interpretability during/by design, and post-hoc tools after training.",
          professor: "He tied EDA to spotting anomalies, implausible patterns and biases before they enter a model.",
          remember: "Explainability is broader than SHAP/LIME; EDA and interpretable model choice also matter.",
        },
        {
          label: "Slide 31",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 31,
          image: "amla-slides/module2-lecture5-xai/slide-31.png",
          title: "Linear coefficients as direct interpretation",
          comment: "Coefficients tell direction and magnitude under the model's assumptions.",
          professor: "In the notebook later, he reminded students that logistic regression coefficients change log-odds, not direct probabilities.",
          trap: "Do not interpret every coefficient as a causal effect or as a probability change.",
        },
        {
          label: "Slides 32-34",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 33,
          image: "amla-slides/module2-lecture5-xai/slide-33.png",
          title: "Feature importance: useful but limited",
          comment: "Feature importance gives global insight, can help selection/debugging, but depends on model and can be distorted by correlation or interactions.",
          professor: "He said feature importance usually considers features individually, so interactions may not be captured correctly.",
          remember: "Feature importance ranks influence; it does not automatically explain mechanism or causality.",
        },
      ],
    },
    {
      range: "Module 2 / Lecture5 slides 35-41",
      title: "SHAP: fair credit assignment",
      intro: "SHAP is introduced as Shapley-value based feature attribution: assign each feature a fair contribution to a prediction by averaging marginal contributions.",
      slides: [
        {
          label: "Slides 35-36",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 35,
          image: "amla-slides/module2-lecture5-xai/slide-35.png",
          title: "Shapley values from game theory",
          comment: "The analogy maps reward to importance, players to features and coalition to prediction.",
          professor: "He translated the game-theory idea into data analysis: assign importance to each feature in a prediction.",
          remember: "SHAP is about contribution to a prediction, not about biological or causal truth.",
        },
        {
          label: "Slide 37",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 37,
          image: "amla-slides/module2-lecture5-xai/slide-37.png",
          title: "Order matters, so average over orders",
          comment: "A feature's marginal contribution depends on which other features are already included.",
          professor: "He used the pizza/payment intuition to make the order-dependence problem concrete.",
          remember: "SHAP averages marginal contributions over all possible feature coalitions/orderings.",
        },
        {
          label: "Slide 38",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 38,
          image: "amla-slides/module2-lecture5-xai/slide-38.png",
          title: "Mathematical framework",
          comment: "The formula expresses weighted average marginal contribution over subsets that exclude the feature of interest.",
          professor: "He emphasized the computational issue: all combinations become expensive when feature count grows.",
          trap: "Do not memorize the formula without the intuition: contribution depends on context.",
        },
        {
          label: "Slide 39",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 39,
          image: "amla-slides/module2-lecture5-xai/slide-39.png",
          title: "House price example",
          comment: "With three features, there are six orderings. SHAP averages how much adding rooms changes prediction across contexts.",
          professor: "He pointed to the example as a concrete way to understand why all orderings are considered.",
          remember: "A SHAP value is local to the observation's feature values.",
        },
        {
          label: "Slides 40-41",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 40,
          image: "amla-slides/module2-lecture5-xai/slide-40.png",
          title: "SHAP implementations and cost",
          comment: "The Python `shap` package has model-specific explainers. Exact SHAP is expensive, so optimized or approximate methods are common.",
          professor: "He said SHAP is local by design, but global insight can be obtained by aggregating values across observations.",
          remember: "Know the distinction: local values first, global summaries by aggregation.",
        },
      ],
      lab: {
        title: "Mini-lab: read SHAP outputs",
        objective: "Use the linked XAI notebook to compare model coefficients, global SHAP summaries and local SHAP explanations.",
        href: "https://drive.google.com/file/d/1Ek2bEgyK_P8Csn0Og1o6JxLkhFxgc0Yq/view?usp=drivesdk",
        steps: [
          "Open the SHAP/LIME notebook from the lecture resources.",
          "Identify the dataset, target and features used in the example.",
          "Fit or inspect the model used before SHAP explanations.",
          "Create the SHAP explainer and compute SHAP values.",
          "Inspect a global SHAP bar or beeswarm-style plot.",
          "Inspect one local explanation and connect feature values to prediction movement.",
        ],
        parameters: [
          "Model being explained.",
          "Background/reference data or sampled feature values.",
          "Prediction target: probability, class score or log-odds.",
          "Number of samples used for approximation.",
          "Observation selected for local explanation.",
        ],
        outputs: [
          "Feature ranking from global SHAP summary.",
          "Local feature contributions for one observation.",
          "Positive and negative contributors relative to the baseline prediction.",
          "Comparison with linear/logistic coefficients if present.",
        ],
        explain: [
          "Why SHAP values explain model output, not causal effects.",
          "Why different explainability methods can rank features differently.",
          "Why a local explanation should not be blindly generalized to all observations.",
        ],
      },
    },
    {
      range: "Module 2 / Lecture5 slides 42-48",
      title: "LIME and SHAP versus LIME",
      intro: "LIME is introduced as a local surrogate explanation: perturb around one point, ask the black box for predictions, then fit a simpler local model.",
      slides: [
        {
          label: "Slide 42",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 42,
          image: "amla-slides/module2-lecture5-xai/slide-42.png",
          title: "LIME intuition",
          comment: "LIME assumes a complex model may be locally approximated by a simpler interpretable model near one prediction.",
          professor: "He explained it as changing inputs slightly, observing prediction changes and fitting a local linear approximation.",
          remember: "LIME explains a neighborhood around one case, not the full model globally.",
        },
        {
          label: "Slides 43-44",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 43,
          image: "amla-slides/module2-lecture5-xai/slide-43.png",
          title: "LIME optimization",
          comment: "The optimization balances local fidelity to the black-box model with simplicity of the surrogate explanation.",
          professor: "He emphasized that closer neighbors matter more through proximity weighting.",
          remember: "The explanation is only as trustworthy as the local approximation fidelity.",
        },
        {
          label: "Slide 45",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 45,
          image: "amla-slides/module2-lecture5-xai/slide-45.png",
          title: "LIME versus SHAP",
          comment: "LIME is local-only and faster, but lacks SHAP's mathematical guarantees and consistency. SHAP can be local and aggregated globally.",
          professor: "He said LIME may vary across runs because the perturbed neighborhood sampling can change.",
          remember: "Use LIME for quick local explanations; use SHAP when you need stronger theoretical grounding or global summaries.",
        },
        {
          label: "Slide 46",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 46,
          image: "amla-slides/module2-lecture5-xai/slide-46.png",
          title: "Efficiency axiom check",
          comment: "This question checks one of SHAP's game-theory properties.",
          professor: "Efficiency means the total attribution is distributed across features so contributions add up to the total prediction difference.",
          remember: "SHAP values are additive relative to the baseline/model output being explained.",
        },
        {
          label: "Slide 47",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 47,
          image: "amla-slides/module2-lecture5-xai/slide-47.png",
          title: "SHAP is not causality",
          comment: "The SNP example is a direct warning: importance for prediction does not mean the feature causes the disease.",
          professor: "He used this kind of question to separate model explanation from causal discovery.",
          trap: "Never jump from high SHAP importance to causal intervention without additional evidence.",
        },
        {
          label: "Slide 48",
          deckLabel: "Module 2 / Lecture5 XAI",
          page: 48,
          image: "amla-slides/module2-lecture5-xai/slide-48.png",
          title: "Hands-on XAI with SHAP and LIME",
          comment: "The deck ends with the hands-on link. The transcript confirms the notebook compares coefficient-style interpretation with SHAP and LIME.",
          professor: "He said the notebook deliberately uses a simple model to show that different interpretation/explainability approaches may disagree.",
          remember: "Different explanation tools can produce different rankings, so discuss rather than blindly report them.",
        },
      ],
      lab: {
        title: "Mini-lab: compare SHAP and LIME explanations",
        objective: "Run or inspect the notebook section that applies SHAP and LIME to the same prediction and compare what each explanation claims.",
        href: "https://drive.google.com/file/d/1Ek2bEgyK_P8Csn0Og1o6JxLkhFxgc0Yq/view?usp=drivesdk",
        steps: [
          "Install/import `lime` if the notebook asks for it; `shap` is noted as already available.",
          "Select one observation to explain.",
          "Generate SHAP values for that observation.",
          "Generate a LIME explanation for the same observation.",
          "Compare the top contributing features and direction of contribution.",
          "Write a short interpretation and one limitation for each method.",
        ],
        parameters: [
          "Observation selected for local explanation.",
          "Number of perturbation samples for LIME.",
          "Neighborhood/proximity settings for LIME.",
          "SHAP explainer type and background/sample data.",
          "Prediction output being explained.",
        ],
        outputs: [
          "LIME local feature weights.",
          "SHAP local contributions.",
          "A short agreement/disagreement table.",
          "A note on whether the explanation is local, global or aggregated.",
        ],
        explain: [
          "Why LIME can vary slightly across runs.",
          "Why SHAP can produce global insight by averaging local values.",
          "Why neither method proves causality.",
        ],
      },
    },
  ],
  professorEmphasis: [
    "Advanced projects require mature explanation and interpretation, not just model execution.",
    "AI tools can help, but you must be able to explain the code, choices and result interpretation yourself.",
    "Performance metrics can hide shortcuts, bias or harm to minority groups.",
    "Interpretability and explainability are related but different: intrinsic mechanics versus post-hoc explanations.",
    "XAI can be local, global or group-level; always state the granularity.",
    "Feature importance is useful but model-dependent and weak for interacting/correlated features.",
    "SHAP is local by construction, with global insights obtained by aggregation.",
    "LIME is local-only and may vary because it depends on sampled perturbations.",
    "Feature importance, SHAP and LIME do not justify causal claims.",
  ],
  commonTraps: [
    "Saying a high AUC or accuracy proves the model learned the right biological signal.",
    "Using interpretability and explainability as synonyms.",
    "Calling a neural network interpretable just because its layers can be listed.",
    "Treating global feature importance as a local explanation for one patient/sample.",
    "Ignoring feature interactions or multicollinearity when reading importance rankings.",
    "Assuming LIME explanations are stable and globally valid.",
    "Assuming SHAP importance means causal effect.",
    "Comparing SHAP values, coefficients and LIME weights without checking what output scale they explain.",
  ],
  quickQuiz: [
    {
      question: "What is the key difference between interpretability and explainability?",
      answer: "Interpretability is intrinsic to the model; explainability is a post-hoc strategy to explain predictions after the model is trained.",
    },
    {
      question: "Why is high performance not always enough?",
      answer: "A model may predict correctly using spurious, biased or unacceptable shortcuts.",
    },
    {
      question: "What does feature importance usually provide?",
      answer: "A global ranking or score of feature influence, often dependent on the model and computation method.",
    },
    {
      question: "What is SHAP's core intuition?",
      answer: "Fairly assign prediction credit to features by averaging marginal contributions across possible feature coalitions.",
    },
    {
      question: "Why is exact SHAP computationally expensive?",
      answer: "It requires considering many possible feature subsets/orderings, growing exponentially with feature count.",
    },
    {
      question: "What is LIME's core intuition?",
      answer: "Approximate the black-box model locally around one observation with a simpler interpretable surrogate.",
    },
    {
      question: "Which method is local-only: SHAP or LIME?",
      answer: "LIME is local-only. SHAP is local by construction but can be aggregated for global summaries.",
    },
    {
      question: "Why is the SNP causality conclusion wrong?",
      answer: "High predictive importance does not prove the SNP causes the disease; it only says the model used it for prediction.",
    },
  ],
  examQuestions: [
    {
      id: "l11-q1",
      question: "A CNN obtains 97% accuracy but saliency/explanation suggests it relies mostly on background artifacts. What is the best interpretation?",
      options: [
        "The metric proves the model is scientifically valid.",
        "The model may perform well for the wrong reason, so explanation and error analysis are needed.",
        "The model is intrinsically interpretable because it is a CNN.",
        "The explanation proves the background causes the class.",
      ],
      correct: 1,
      explanation: "High performance can hide shortcuts; XAI helps inspect whether the model uses acceptable signals.",
    },
    {
      id: "l11-q2",
      question: "Which example best represents interpretability rather than post-hoc explainability?",
      options: [
        "Using LIME to explain one random forest prediction.",
        "Using SHAP values to explain a black-box classifier.",
        "Reading a linear regression coefficient under the model assumptions.",
        "Perturbing an image and observing a CNN probability change.",
      ],
      correct: 2,
      explanation: "Linear coefficients are part of the model's intrinsic mechanics.",
    },
    {
      id: "l11-q3",
      question: "A SHAP plot ranks a gene as highly important for cancer prediction. What conclusion is justified?",
      options: [
        "The gene caused cancer in the patients.",
        "The model used that gene strongly for prediction under the analyzed setup.",
        "The gene must be used as a drug target immediately.",
        "No validation or biological interpretation is needed.",
      ],
      correct: 1,
      explanation: "SHAP explains model behavior; causal interpretation requires separate evidence.",
    },
    {
      id: "l11-q4",
      question: "Why can LIME explanations vary slightly across runs?",
      options: [
        "LIME never uses local neighborhoods.",
        "LIME is a white-box model by design.",
        "The sampled perturbations/neighborhood approximation can change.",
        "SHAP axioms force LIME to be inconsistent.",
      ],
      correct: 2,
      explanation: "LIME fits a local surrogate based on perturbed samples around the observation.",
    },
    {
      id: "l11-q5",
      question: "Which comparison between SHAP and LIME matches the lecture?",
      options: [
        "LIME is global by default; SHAP is local-only and cannot be aggregated.",
        "SHAP has game-theory guarantees; LIME is a local surrogate without those guarantees.",
        "Both methods prove causality if feature importance is high.",
        "Neither method can be applied after model training.",
      ],
      correct: 1,
      explanation: "SHAP is based on Shapley values; LIME fits local interpretable approximations.",
    },
    {
      id: "l11-q6",
      question: "A project reports only a global feature-importance ranking. Which missing element would most improve interpretability for a specific surprising prediction?",
      options: [
        "A local explanation for that observation.",
        "A larger font for the same global ranking.",
        "Removing all model metrics.",
        "Calling the ranking causal.",
      ],
      correct: 0,
      explanation: "Global importance summarizes across data; a surprising individual case needs local explanation.",
    },
  ],
  checklistTitle: "What to remember after this lesson",
  studyChecklist: [
    "State why explanation is needed for your application, not only what the metric is.",
    "Separate interpretability, explainability, feature importance, SHAP and LIME.",
    "When using XAI, report whether the explanation is local, global or group-level.",
    "Check the output scale being explained: probability, log-odds, class score or prediction.",
    "Use SHAP values as model-output attributions, not causal effects.",
    "Use LIME as a local approximation and discuss its stability/fidelity.",
    "Compare XAI tools critically when they disagree.",
    "In the AMLA project, explain choices and interpretations as if defending them orally.",
  ],
};
