export const lessonContent = {
  id: "amla-2026-04-17-hands-on-setup",
  extractionStatus: "source-based complete draft",
  objectives: [
    "Compare scikit-learn, TensorFlow, PyTorch, Keras, JAX, Hugging Face and XGBoost at the level needed to choose a tool responsibly.",
    "Explain why the course uses scikit-learn as a benchmark and TensorFlow/Keras for neural-network tutorials.",
    "Describe MNIST as a supervised image-classification benchmark and explain the input/output structure.",
    "Build the mental workflow of a Keras model: define architecture, compile training recipe, fit, evaluate and inspect history.",
    "Distinguish Sequential and Functional Keras APIs and know when Sequential is enough.",
    "Interpret training and validation loss/accuracy curves without confusing them with final test performance.",
  ],
  coreConcepts: [
    {
      title: "Framework choice changes what is easy",
      body: "A framework is not only syntax. Some libraries make certain models, deployment paths, debugging strategies or pretrained-model workflows easier than others.",
      keywords: ["framework", "ecosystem", "trade-off"],
    },
    {
      title: "TensorFlow + Keras",
      body: "TensorFlow is a deep-learning computation framework; Keras is the higher-level interface that hides much of the low-level machinery and is used in the course for accessibility.",
      keywords: ["TensorFlow", "Keras", "high-level API"],
    },
    {
      title: "PyTorch",
      body: "PyTorch is often valued for flexibility, readability and research usage. It is common for recent research models and integrates naturally with ecosystems such as Hugging Face.",
      keywords: ["research", "dynamic", "flexible"],
    },
    {
      title: "MNIST benchmark",
      body: "MNIST contains handwritten digit images and labels. In the tutorial it is a classification task: pixels are inputs and the digit class is the target.",
      keywords: ["70k images", "digits", "classification"],
    },
    {
      title: "Keras compile/fit/evaluate",
      body: "Compile attaches optimizer, loss and metrics; fit trains the model; evaluate computes loss/metrics on held-out data.",
      keywords: ["compile", "fit", "evaluate"],
    },
    {
      title: "Training history",
      body: "The object returned by model.fit stores epoch-by-epoch metrics, which can be plotted to inspect learning dynamics and validation behavior.",
      keywords: ["history", "epochs", "validation"],
    },
  ],
  walkthroughSections: [
    {
      range: "Opening recap",
      title: "Start from implementation, then deepen theory",
      intro: "The class begins by explaining why the tutorial starts with code. The aim is to make the framework workflow visible before spending too long on internal mathematics.",
      slides: [
        {
          label: "Opening slides",
          page: 1,
          image: "amla-slides/lecture2/slide-01.png",
          deckLabel: "Lecture 2 tmp",
          title: "Implementation-first does not mean explanation-free",
          comment: "You are allowed to run a tutorial before understanding every internal detail, but the final goal is still to explain the model and the output.",
          professor: "He explicitly said this is one way to learn, not a universal best method.",
          remember: "For the project, trying a model is fine; submitting unexplained outputs is not.",
        },
        {
          label: "Course bridge",
          page: 3,
          image: "amla-slides/lecture2/slide-03.png",
          deckLabel: "Lecture 2 tmp",
          title: "Basic skills become advanced baselines",
          comment: "Scikit-learn remains useful for benchmarking and sanity checks. Deep learning is added on top, not used as an automatic replacement.",
          professor: "He framed scikit-learn as the familiar Basic tool and TensorFlow/Keras as the new Advanced layer.",
          remember: "A strong report can say why a simple baseline was or was not enough.",
        },
      ],
    },
    {
      range: "Framework landscape",
      title: "Choose frameworks by task and ecosystem, not brand loyalty",
      intro: "This block names many tools. The study goal is not to memorize slogans, but to know what each ecosystem makes easier.",
      slides: [
        {
          label: "Framework overview",
          page: 4,
          image: "amla-slides/lecture2/slide-04.png",
          deckLabel: "Lecture 2 tmp",
          title: "TensorFlow, PyTorch, Keras, JAX, Hugging Face, XGBoost",
          comment: "Each framework sits in a different part of the workflow: classical ML, deep learning, high-level model building, research flexibility, pretrained models or gradient-boosted tabular baselines.",
          professor: "He emphasized that the landscape changes quickly and that no answer is universally best.",
          remember: "Answer framework questions with trade-offs: usability, flexibility, ecosystem, deployment, pretrained models and project constraints.",
        },
        {
          label: "TensorFlow vs PyTorch",
          page: 6,
          image: "amla-slides/lecture2/slide-06.png",
          deckLabel: "Lecture 2 tmp",
          title: "Mature ecosystems with different histories",
          comment: "TensorFlow has strong production history and Keras accessibility; PyTorch is widely used in research and many pretrained-model examples.",
          professor: "He noted that AI coding tools make translation between frameworks easier, but mixed dependencies can still become messy.",
          remember: "For AMLA tutorials, default to TensorFlow/Keras unless there is a clear project reason to choose another stack.",
          trap: "Do not write 'TensorFlow = production, PyTorch = research' as an absolute rule. Context matters.",
        },
      ],
    },
    {
      range: "MNIST tutorial setup",
      title: "Use a simple benchmark to isolate the modeling workflow",
      intro: "MNIST reduces dataset complexity. Because the task is familiar, you can focus on inputs, labels, architecture and training lifecycle.",
      slides: [
        {
          label: "MNIST slides",
          page: 22,
          image: "amla-slides/lecture2/slide-22.png",
          deckLabel: "Lecture 2 tmp",
          title: "Inputs, labels and supervised classification",
          comment: "The input is an image of a handwritten digit; the target is the digit class. This is supervised multiclass classification.",
          professor: "He used MNIST as a standard benchmark, not as proof that the same model will solve harder biomedical images.",
          remember: "Before architecture, always name input shape, target labels, preprocessing and split strategy.",
        },
        {
          label: "Baseline idea",
          page: 33,
          image: "amla-slides/lecture2/slide-33.png",
          deckLabel: "Lecture 2 tmp",
          title: "Benchmark before complexity",
          comment: "A basic scikit-learn model can establish a reference point. Keras is then introduced to show the neural-network workflow.",
          professor: "He connected this directly to the Basic course: you already know enough to build a baseline.",
          remember: "Advanced does not mean skipping baselines; it means interpreting why a more complex model is justified.",
        },
      ],
    },
    {
      range: "Keras architecture APIs",
      title: "Define the model: Sequential first, Functional when shape demands it",
      intro: "This block is about model construction, before optimization. Know when the simple API matches the architecture and when it does not.",
      slides: [
        {
          label: "Sequential API",
          page: 54,
          image: "amla-slides/lecture2/slide-54.png",
          deckLabel: "Lecture 2 tmp",
          title: "A linear stack of layers",
          comment: "Sequential is enough for a simple feed-forward chain: input, hidden layers, output. It is readable and good for first tutorials.",
          professor: "He said the introductory tutorials will use Sequential because it is enough for the first models.",
          remember: "Use Sequential when every layer has one clear previous layer and one clear next layer.",
        },
        {
          label: "Functional API",
          page: 56,
          image: "amla-slides/lecture2/slide-56.png",
          deckLabel: "Lecture 2 tmp",
          title: "A graph for branching or multiple paths",
          comment: "Functional API supports multiple inputs, branches, merges and skip-like structures. It is more flexible but less minimal.",
          professor: "He contrasted it with Sequential to show why not every neural network is just a list of layers.",
          remember: "Two inputs, branches or merges are a strong signal that Sequential is not the right abstraction.",
        },
        {
          label: "model.summary()",
          page: 56,
          image: "amla-slides/lecture2/slide-56.png",
          deckLabel: "Lecture 2 tmp",
          title: "Read the architecture before training",
          comment: "The summary exposes layer order, output shapes and parameter count. It is your first sanity check that the code built what you intended.",
          professor: "He highlighted summary output as useful because parameter count can grow quickly.",
          remember: "If the parameter count surprises you, pause before fitting; the architecture may not be what you think.",
        },
      ],
    },
    {
      range: "Training workflow",
      title: "Compile, fit, evaluate, then inspect history",
      intro: "After architecture comes the training recipe and evidence. This is the sequence you should be able to write from memory.",
      slides: [
        {
          label: "compile",
          page: 55,
          image: "amla-slides/lecture2/slide-55.png",
          deckLabel: "Lecture 2 tmp",
          title: "Attach optimizer, loss and metrics",
          comment: "The architecture says what can be learned. Compile says how learning will be optimized and how progress will be monitored.",
          professor: "He treated compile as a required step before normal Keras training.",
          remember: "Loss drives optimization; metrics summarize performance in a way humans can read.",
        },
        {
          label: "fit",
          page: 24,
          image: "amla-slides/lecture2/slide-24.png",
          deckLabel: "Lecture 2 tmp",
          title: "Run the training loop",
          comment: "fit uses epochs, batch size and training data. If you add validation_split, Keras reports validation metrics after each epoch.",
          professor: "He emphasized validation_split as a convenient way to monitor held-out validation behavior during training.",
          remember: "Validation curves are development evidence, not final unbiased test evidence.",
        },
        {
          label: "evaluate + history",
          page: 43,
          image: "amla-slides/lecture2/slide-43.png",
          deckLabel: "Lecture 2 tmp",
          title: "Separate final evaluation from training diagnostics",
          comment: "evaluate reports model performance on held-out data. history stores epoch-by-epoch curves for training and validation metrics.",
          professor: "He used the history object as the bridge from code execution to interpretation.",
          remember: "If validation loss rises while training loss falls, discuss overfitting controls rather than celebrating training accuracy.",
          trap: "Do not report validation performance as if it were a final untouched test result after using it to tune decisions.",
        },
      ],
      lab: {
        title: "MNIST Keras workflow rehearsal",
        href: null,
        todo: "The transcript says the MNIST tutorial link was on the slide/QR code, but the extracted Drive text did not expose the actual Colab URL.",
        objective: "Stop after the Keras lifecycle slides and rehearse the pipeline in a notebook or from memory.",
        steps: [
          "Load MNIST or another small labeled image dataset.",
          "Flatten/scale inputs if using dense layers.",
          "Define a Sequential model with at least one Dense hidden layer and an output layer for classes.",
          "Compile with optimizer, loss and metrics.",
          "Fit with validation data or validation_split.",
          "Evaluate once on test data and inspect the history curves.",
        ],
        parameters: ["Hidden-layer size", "Activation", "Optimizer", "Loss", "Batch size", "Epochs", "Validation split"],
        outputs: ["model.summary()", "Training loss", "Validation loss", "Training accuracy", "Validation accuracy", "Test loss/accuracy"],
        explain: [
          "Why input shape must match the first layer.",
          "Why softmax is appropriate for multiclass class probabilities.",
          "Why validation curves can warn about overfitting.",
          "Why final test evaluation comes after model choices are fixed.",
        ],
      },
    },
  ],
  slidePath: [
    {
      range: "Opening recap",
      title: "Implementation-first learning",
      concept: "The lecture starts from implementation before full theory, because real work often requires testing new libraries before studying every internal detail.",
      intuition: "Use tutorials to see whether a method works, then deepen theory once the method is relevant.",
      professor: "He explicitly said this is one way to learn, not the only best way; the goal is to get familiar with tools early.",
      remember: "For projects, trying a method is acceptable, but the report must still explain why it works and what the outputs mean.",
    },
    {
      range: "Framework landscape",
      title: "Many tools, different trade-offs",
      concept: "TensorFlow, PyTorch, Keras, scikit-learn, XGBoost, Hugging Face and JAX occupy different parts of the ML/deep-learning ecosystem.",
      intuition: "Choose the tool that matches task, model family, community examples and deployment constraints.",
      professor: "He emphasized that the landscape changed fast and that today's best choice may not be universal in the future.",
      remember: "Do not answer framework questions as fan debates; answer in terms of usability, flexibility, performance, maturity and ecosystem.",
    },
    {
      range: "TensorFlow vs PyTorch",
      title: "Production legacy vs research flexibility",
      concept: "TensorFlow has strong production history and graph-style computation; PyTorch became very popular in research because of flexible, readable workflows.",
      intuition: "Both are mature. The practical choice often depends on the project, existing code and available model implementations.",
      professor: "He noted that AI coding tools make translating between libraries less painful than it used to be, but dependencies and mixed styles can still become messy.",
      remember: "For this course, use TensorFlow/Keras unless a project has a strong reason for another stack.",
    },
    {
      range: "MNIST tutorial",
      title: "Benchmark before advanced models",
      concept: "MNIST is used as a standard classification benchmark: image input, digit label output and a simple pipeline to compare scikit-learn and neural-network approaches.",
      intuition: "A familiar benchmark reduces dataset complexity so you can focus on the modeling workflow.",
      professor: "He framed scikit-learn as the base from Basic, then TensorFlow/Keras as the added deep-learning layer.",
      remember: "Explain inputs, labels, preprocessing and train/test split before discussing architecture.",
    },
    {
      range: "Keras architecture APIs",
      title: "Sequential vs Functional",
      concept: "Sequential builds one linear stack of layers. Functional builds a computational graph and supports branching/multiple paths.",
      intuition: "Sequential is easier for standard feed-forward chains; Functional is needed when the architecture is not a simple chain.",
      professor: "He said the first tutorials will start with Sequential because it is enough for the introductory models.",
      remember: "If a model has two inputs, skip connections or branching, Sequential is probably not expressive enough.",
    },
    {
      range: "Training workflow",
      title: "compile, fit, evaluate and history",
      concept: "A Keras model is compiled with optimizer/loss/metrics, trained with fit, evaluated with evaluate and inspected through the history object.",
      intuition: "Architecture says what can be learned; compile says how learning is optimized; fit runs the learning loop; evaluate checks held-out performance.",
      professor: "He highlighted validation_split as a way to reserve part of training data for validation metrics during epochs.",
      remember: "Validation curves monitor training behavior; final model assessment still needs a separate test set.",
    },
  ],
  professorEmphasis: [
    "The course intentionally starts with implementation and then adds theory, because this mirrors many real-world workflows.",
    "Framework choice can affect what you can implement, not only how the code looks.",
    "For the course, the main stack is scikit-learn as benchmark plus TensorFlow/Keras for neural networks.",
    "Do not mix many deep-learning frameworks in one project unless you have a concrete reason; dependencies and style can become hard to manage.",
    "Sequential API is the beginner-friendly starting point, while Functional API is for more flexible architectures.",
    "model.summary() is useful because it exposes layer structure and number of parameters.",
    "validation_split evaluates metrics after each epoch on held-out validation data, but it is not the same as final test evaluation.",
  ],
  commonTraps: [
    "Saying TensorFlow is always for production and PyTorch always for research; both are mature and context matters.",
    "Treating Keras as unrelated to TensorFlow; in this course Keras is mainly the high-level interface used on top of TensorFlow.",
    "Using MNIST accuracy as proof that a model will work on complex biomedical images.",
    "Forgetting to prepare input shape and label encoding before fitting a neural network.",
    "Confusing loss with metric: loss drives optimization; metrics summarize performance in human-friendly terms.",
    "Using validation data to tune decisions and then reporting it as unbiased final test performance.",
    "Ignoring the number of parameters shown by model.summary(), especially when a small-looking network already has many weights.",
  ],
  miniLab: {
    title: "MNIST Keras workflow rehearsal",
    href: null,
    todo: "The transcript says the MNIST tutorial link was on the slide/QR code, but the extracted Drive text did not expose the actual Colab URL.",
    objective: "Recreate the Keras workflow mentally or in your own notebook: load MNIST, define a simple model, compile, fit, evaluate and plot history.",
    steps: [
      "Load MNIST or another small labeled image dataset.",
      "Flatten/scale inputs if using dense layers.",
      "Define a Sequential model with at least one Dense hidden layer and an output layer for classes.",
      "Compile with optimizer, loss and metrics.",
      "Fit with a validation split or explicit validation data.",
      "Evaluate once on test data and inspect training history.",
    ],
    parameters: ["Hidden-layer size", "Activation function", "Optimizer", "Loss function", "Batch size", "Epochs", "Validation split"],
    outputs: ["model.summary()", "Training loss", "Validation loss", "Training accuracy", "Validation accuracy", "Test loss/accuracy"],
    explain: [
      "Why input shape must match the model's first layer.",
      "Why softmax is used for multiclass class probabilities.",
      "Why validation curves can warn about overfitting.",
      "Why test performance should be reported after model choices are fixed.",
    ],
  },
  quickQuiz: [
    {
      question: "Why did the lecture start from implementation before full theory?",
      answer: "Because practical ML often starts by trying a method or library to see whether it works, then studying the details once the method becomes relevant.",
    },
    {
      question: "What role does scikit-learn keep in AMLA?",
      answer: "It remains useful for classical models, baselines and benchmarking, even when the course shifts toward TensorFlow/Keras neural networks.",
    },
    {
      question: "What does Keras Sequential API assume about architecture?",
      answer: "It assumes a simple linear stack: each layer has one input path and one output path, with no branching or multiple inputs.",
    },
    {
      question: "What does model.compile specify?",
      answer: "It specifies the training recipe: optimizer, loss function and metrics to monitor.",
    },
    {
      question: "What does model.fit return that is useful for study?",
      answer: "It returns a history object with epoch-by-epoch training and validation metrics that can be plotted.",
    },
    {
      question: "Why is validation_split not the same as the final test set?",
      answer: "Validation data is used during model development and hyperparameter decisions; the test set should remain untouched until final evaluation.",
    },
  ],
  examQuestions: [
    {
      id: "l02-framework-choice",
      question: "A project needs a recent pretrained transformer model with many community examples. Which framework/ecosystem argument is strongest?",
      options: [
        "Use only scikit-learn because it was used in Basic.",
        "Consider PyTorch/Hugging Face because many recent research/pretrained models are exposed there.",
        "Use XGBoost because it is a neural-network framework.",
        "Avoid frameworks and implement all tensor operations manually.",
      ],
      correct: 1,
      explanation: "The lecture framed Hugging Face/PyTorch as common for pretrained and research-driven models.",
    },
    {
      id: "l02-sequential-functional",
      question: "You need a model with two input branches that merge before classification. Which Keras API is most appropriate?",
      options: ["Sequential API", "Functional API", "model.evaluate", "validation_split"],
      correct: 1,
      explanation: "Branching and multiple paths require the more flexible computational-graph style of the Functional API.",
    },
    {
      id: "l02-compile",
      question: "A model is defined but not compiled. What is still missing before normal Keras training?",
      options: [
        "The optimizer/loss/metrics recipe.",
        "The final test accuracy.",
        "The dataset labels only.",
        "A second deep-learning framework.",
      ],
      correct: 0,
      explanation: "compile attaches the optimizer, loss and metrics used by fit.",
    },
    {
      id: "l02-validation",
      question: "During fit, validation loss starts increasing while training loss keeps decreasing. What is the most reasonable interpretation?",
      options: [
        "The model is certainly improving on unseen data.",
        "The model may be overfitting and should be checked with regularization, early stopping or simpler architecture.",
        "Validation data should be used as test data because it is lower quality.",
        "Loss cannot be interpreted during neural-network training.",
      ],
      correct: 1,
      explanation: "Divergence between training and validation curves is a classic overfitting warning.",
    },
  ],
  checklistTitle: "What to take from L02",
  studyChecklist: [
    "Know the role of each major framework named in class without turning it into brand preference.",
    "Be able to write the Keras lifecycle in order: define model, compile, fit, evaluate, inspect history.",
    "Explain what MNIST contributes as a benchmark and what it does not prove.",
    "Use model.summary() to reason about layers and parameter count.",
    "Separate training, validation and test data in your language and project reports.",
  ],
};
