export const lessonContent = {
  id: "amla-2026-05-29-project-xai-sequential",
  extractionStatus: "source-based complete draft",
  objectives: [
    "Turn the final project guidance into a concrete report checklist.",
    "Explain when sequential data needs models that preserve order and state.",
    "Describe recurrent neurons, hidden state, memory cells and unrolling through time.",
    "Distinguish seq-to-seq, seq-to-vector, vector-to-seq and encoder-decoder setups.",
    "Explain how RNNs are trained with backpropagation through time and why baselines still matter.",
    "Recognize why long sequences create gradient and memory problems.",
    "Explain the basic roles of LSTM/GRU gates without memorizing every equation.",
    "Connect RNNs to transformers, LLMs, VAEs and GANs as advanced-topic extensions.",
  ],
  coreConcepts: [
    {
      title: "Sequential data",
      body: "Data whose order matters: time series, text, audio, trajectories or experimental processes.",
      keywords: ["order", "time steps", "context"],
    },
    {
      title: "Recurrent neuron",
      body: "A unit that receives current input and its previous output/state, allowing information to persist across steps.",
      keywords: ["feedback", "state", "time"],
    },
    {
      title: "Hidden state",
      body: "The state h(t) summarizes what the recurrent cell retains from previous inputs.",
      keywords: ["memory", "h(t)", "stateful"],
    },
    {
      title: "BPTT",
      body: "Backpropagation through time trains an RNN by unrolling it over time and propagating gradients through that unrolled graph.",
      keywords: ["unrolling", "gradients", "time"],
    },
    {
      title: "Sequence mapping",
      body: "RNNs can map sequence to sequence, sequence to vector, vector to sequence, or encoder-decoder sequence to sequence.",
      keywords: ["seq2seq", "seq2vec", "encoder-decoder"],
    },
    {
      title: "Short memory problem",
      body: "Simple RNNs gradually lose early information when sequences are long.",
      keywords: ["long sequences", "forgetting", "context"],
    },
    {
      title: "LSTM / GRU",
      body: "Gated recurrent cells that learn what to store, forget and output, improving long-term dependency handling.",
      keywords: ["gates", "long-term state", "memory"],
    },
    {
      title: "Transformer",
      body: "A sequence architecture based on attention, now central to modern language models.",
      keywords: ["attention", "tokens", "LLM"],
    },
    {
      title: "Generative model",
      body: "A model that learns a data distribution well enough to generate new plausible examples.",
      keywords: ["VAE", "GAN", "synthetic data"],
    },
  ],
  walkthroughSections: [
    {
      range: "Project guidelines slides 1-10 + Lecture7 slides 2-6",
      title: "Final communications and project expectations",
      intro: "The class begins with logistics, questionnaires and project expectations. For studying, the main point is what the project report must demonstrate.",
      slides: [
        {
          label: "Project slide 1",
          deckLabel: "Project guidelines",
          page: 1,
          image: "amla-slides/project-guidelines/slide-001.png",
          title: "Project guidance as a checklist",
          comment: "The project guidelines are complementary to the class deck, but they summarize the assessment logic more directly than the lecture slides.",
          professor: "He reminded students that the report is what gets evaluated first; code and repository material support the report.",
          remember: "The report must be self-contained: goal, data, methods, results and interpretation.",
        },
        {
          label: "Project slide 2",
          deckLabel: "Project guidelines",
          page: 2,
          image: "amla-slides/project-guidelines/slide-002.png",
          title: "Basic versus Advanced project",
          comment: "Advanced projects must show appropriate use and understanding of advanced methods, not just the basic ML workflow.",
          professor: "The transcript repeats that advanced projects require more maturity in explanation and interpretation.",
          remember: "Use advanced tools only when you can justify them for the dataset and objective.",
        },
        {
          label: "Project slide 4",
          deckLabel: "Project guidelines",
          page: 4,
          image: "amla-slides/project-guidelines/slide-004.png",
          title: "The report workflow",
          comment: "Start with goal and strategy, give enough context, explore data, build baselines, justify model choices and interpret performance.",
          professor: "This recaps the recurring advice from Fluocells and XAI: EDA, baseline, model adaptation, multiple metrics and error analysis.",
          remember: "A polished report with weak methodological reasoning is not an advanced project.",
        },
        {
          label: "Project slides 5-9",
          deckLabel: "Project guidelines",
          page: 8,
          image: "amla-slides/project-guidelines/slide-008.png",
          title: "LLM use: allowed support, not substitution",
          comment: "LLMs can help debug, clarify, refactor and polish, but students remain responsible for choices, code, outputs and interpretation.",
          professor: "He framed the oral-exam test: could you explain why you did this instead of another strategy?",
          remember: "Disclose LLM help and validate everything yourself.",
        },
        {
          label: "Lecture7 slides 2-6",
          deckLabel: "Module 1 / Lecture7",
          page: 3,
          image: "amla-slides/module1-lecture7/slide-003.png",
          title: "Dates and questionnaires",
          comment: "The opening class communications are useful logistically, but not a deep study topic.",
          professor: "He emphasized course feedback and tentative exam sessions, then moved to advanced topics.",
          remember: "Use these slides as administrative reference, not conceptual study core.",
        },
      ],
    },
    {
      range: "Module 1 / Lecture7 slides 7-28",
      title: "Why RNNs: sequences, state and memory",
      intro: "RNNs are introduced as networks for ordered data. The intuition is that a model should preserve some state while inputs arrive step by step.",
      slides: [
        {
          label: "Slide 7",
          deckLabel: "Module 1 / Lecture7",
          page: 7,
          image: "amla-slides/module1-lecture7/slide-007.png",
          title: "Processing sequences",
          comment: "This is the main technical theme of the lecture: ordered data and architectures that preserve context.",
          professor: "He said the class is a broad overview and that some slides are included for future study beyond what he can cover in detail.",
          remember: "Study the core concepts first; treat the long tail of slides as reference material.",
        },
        {
          label: "Slides 8-10",
          deckLabel: "Module 1 / Lecture7",
          page: 8,
          image: "amla-slides/module1-lecture7/slide-008.png",
          title: "Sequential data is not only time",
          comment: "RNNs can process sequences of arbitrary length: numerical time series, sentences, audio samples or signals.",
          professor: "He stressed that the x-axis does not have to be clock time; what matters is that order changes meaning.",
          remember: "If shuffling the entries changes the problem, sequence modeling may matter.",
        },
        {
          label: "Slides 12-15",
          deckLabel: "Module 1 / Lecture7",
          page: 14,
          image: "amla-slides/module1-lecture7/slide-014.png",
          title: "Unrolling through time",
          comment: "A recurrent neuron is shown once, then repeated along the time axis to understand how the same cell processes a sequence.",
          professor: "He clarified that unrolling is a way to visualize the same recurrent unit over different frames/time steps.",
          remember: "Same parameters, repeated through time.",
        },
        {
          label: "Slides 16-18",
          deckLabel: "Module 1 / Lecture7",
          page: 18,
          image: "amla-slides/module1-lecture7/slide-018.png",
          title: "Current input plus previous output",
          comment: "The recurrent layer output depends on X(t) and Y(t-1), so current output is indirectly a function of previous inputs.",
          professor: "He used this to motivate the term memory, while warning that it is a limited, technical kind of memory.",
          remember: "The hidden state is the carrier of past information.",
        },
        {
          label: "Slides 19-21",
          deckLabel: "Module 1 / Lecture7",
          page: 21,
          image: "amla-slides/module1-lecture7/slide-021.png",
          title: "Memory cells and hidden state",
          comment: "A memory cell preserves state across time. Basic recurrent cells can learn only relatively short patterns.",
          professor: "He preferred the neutral term stateful: the system retains a state rather than human-like memory.",
          trap: "Do not overstate RNN memory. Simple RNNs do not retain long context well.",
        },
        {
          label: "Slides 23-27",
          deckLabel: "Module 1 / Lecture7",
          page: 26,
          image: "amla-slides/module1-lecture7/slide-026.png",
          title: "Sequence mapping patterns",
          comment: "The deck separates seq-to-seq, seq-to-vector, vector-to-sequence and encoder-decoder setups.",
          professor: "He connected these to forecasting, sentiment analysis, image captioning and translation.",
          remember: "For an exam, identify input type, output type and why the architecture fits.",
        },
      ],
    },
    {
      range: "Module 1 / Lecture7 slides 29-89",
      title: "Training RNNs and the time-series notebook",
      intro: "The hands-on part uses synthetic time series and progressively compares naive forecasting, FCNNs, SimpleRNNs and deeper/sequence-output variants.",
      slides: [
        {
          label: "Slides 30-33",
          deckLabel: "Module 1 / Lecture7",
          page: 32,
          image: "amla-slides/module1-lecture7/slide-032.png",
          title: "Backpropagation through time",
          comment: "Training unrolls the RNN over time, computes a cost over relevant outputs and backpropagates gradients through the unrolled network.",
          professor: "He summarized it simply: backpropagation still works, but it works through time.",
          remember: "BPTT sums gradient contributions across reused parameters at different time steps.",
        },
        {
          label: "Slides 34-42",
          deckLabel: "Module 1 / Lecture7",
          page: 40,
          image: "amla-slides/module1-lecture7/slide-040.png",
          title: "Synthetic time-series setup",
          comment: "The notebook creates univariate time series, each 50 steps long, and asks the model to forecast the next value.",
          professor: "He said the GitHub notebook is the practical instruction and that students can change functions, frequencies and setup.",
          remember: "RNN input shape is 3D: batch size, time steps, dimensionality.",
        },
        {
          label: "Slides 43-52",
          deckLabel: "Module 1 / Lecture7",
          page: 45,
          image: "amla-slides/module1-lecture7/slide-045.png",
          title: "Baselines before RNNs",
          comment: "Naive forecasting predicts the last observed value; a simple FCNN provides a stronger baseline.",
          professor: "He explicitly warned that without baselines you may think an RNN is good while it is worse than a simple model.",
          remember: "Sequential model does not automatically mean better model.",
        },
        {
          label: "Slides 54-60",
          deckLabel: "Module 1 / Lecture7",
          page: 55,
          image: "amla-slides/module1-lecture7/slide-055.png",
          title: "SimpleRNN can be too simple",
          comment: "The simplest RNN beats naive forecasting but not the FCNN baseline in this example.",
          professor: "He used this result to make a practical point: RNN architecture must still be justified by performance and task.",
          remember: "Compare parameter count and performance before concluding.",
        },
        {
          label: "Slides 63-86",
          deckLabel: "Module 1 / Lecture7",
          page: 86,
          image: "amla-slides/module1-lecture7/slide-086.png",
          title: "Deep RNNs and sequence outputs",
          comment: "Stacking recurrent layers and returning sequences can improve gradient flow by adding losses at each time step.",
          professor: "He highlighted that more output errors can stabilize and speed training, not only improve final prediction.",
          remember: "Use `return_sequences=True` when later recurrent layers or per-time-step outputs need the full sequence.",
        },
        {
          label: "Slide 89",
          deckLabel: "Module 1 / Lecture7",
          page: 89,
          image: "amla-slides/module1-lecture7/slide-089.png",
          title: "Error bars with MC Dropout",
          comment: "Forecasts should include uncertainty when possible. MC Dropout estimates mean and standard deviation by repeated stochastic predictions.",
          professor: "He presented uncertainty as a useful practice for time-series forecasts, not just a decorative plot.",
          remember: "For forecasting, communicate uncertainty as well as point predictions.",
        },
      ],
      lab: {
        title: "Mini-lab: RNN time-series forecasting",
        objective: "Use the linked RNN notebook to reproduce the baseline-to-RNN comparison and explain why the sequence model helps or fails.",
        href: "https://drive.google.com/file/d/1ZqHIZTOj_irE2bN9tQjhQ_1P-rhqN4cB/view?usp=drivesdk",
        steps: [
          "Open the RNN notebook mentioned in the class resources.",
          "Generate the synthetic univariate time series.",
          "Check the array shape: batch size, n_steps and dimensionality.",
          "Compute naive forecasting performance.",
          "Train the FCNN baseline and record its MSE.",
          "Train a SimpleRNN and compare against both baselines.",
          "Try a deeper or sequence-output RNN and compare the validation metric.",
        ],
        parameters: [
          "n_steps.",
          "Noise level and frequency settings in the synthetic generator.",
          "Number of recurrent units.",
          "Number of recurrent layers.",
          "`return_sequences` setting.",
          "Forecast horizon.",
          "Learning rate and epochs.",
        ],
        outputs: [
          "Baseline MSEs.",
          "RNN validation MSE.",
          "Prediction plots against true next values.",
          "Optional uncertainty bands from MC Dropout.",
        ],
        explain: [
          "Why naive forecasting is a real baseline for smooth time series.",
          "Why a SimpleRNN can lose to an FCNN despite being sequence-aware.",
          "Why per-time-step losses can improve training signal.",
        ],
      },
    },
    {
      range: "Module 1 / Lecture7 slides 90-157",
      title: "Long sequences: gradients, memory, LSTM and GRU",
      intro: "This is the difficult middle section. The practical lesson is that long sequences make RNNs behave like very deep networks, with unstable gradients and limited memory.",
      slides: [
        {
          label: "Slides 90-95",
          deckLabel: "Module 1 / Lecture7",
          page: 92,
          image: "amla-slides/module1-lecture7/slide-092.png",
          title: "Long sequences make training hard",
          comment: "Unrolling across many steps creates a very deep graph. RNNs inherit deep-network problems and add sequence-specific forgetting.",
          professor: "He warned that these issues can kill a research direction if the model cannot be trained.",
          remember: "Longer sequence means harder optimization and harder memory retention.",
        },
        {
          label: "Slides 96-103",
          deckLabel: "Module 1 / Lecture7",
          page: 97,
          image: "amla-slides/module1-lecture7/slide-097.png",
          title: "Vanishing and exploding gradients",
          comment: "Gradients can shrink or grow as they are propagated backward, making lower layers or earlier time steps hard to train.",
          professor: "He connected this to general deep networks and then back to RNNs, where exploding gradients are especially visible.",
          remember: "Initialization, activation choice and clipping are not minor details in deep sequence models.",
        },
        {
          label: "Slides 104-115",
          deckLabel: "Module 1 / Lecture7",
          page: 114,
          image: "amla-slides/module1-lecture7/slide-114.png",
          title: "Activation functions for deep networks",
          comment: "ReLU, leaky ReLU, ELU and SELU are discussed as tools for gradient flow, with conditions and trade-offs.",
          professor: "He did not present a universal winner; he emphasized architecture, latency, data size and tuning constraints.",
          remember: "Activation choice must be matched to architecture and training behavior.",
        },
        {
          label: "Slides 118-125",
          deckLabel: "Module 1 / Lecture7",
          page: 120,
          image: "amla-slides/module1-lecture7/slide-120.png",
          title: "Batch normalization",
          comment: "BN normalizes layer inputs using mini-batch statistics and learns scale/shift parameters.",
          professor: "He presented BN as a strong trick for deep feedforward networks, then later warned it is less straightforward inside RNNs.",
          remember: "Normalization can speed convergence, but placement and architecture matter.",
        },
        {
          label: "Slides 129-134",
          deckLabel: "Module 1 / Lecture7",
          page: 132,
          image: "amla-slides/module1-lecture7/slide-132.png",
          title: "RNN-specific stabilization",
          comment: "Some DNN tricks transfer to RNNs, but ReLU and BN can be problematic through time. Layer normalization is often better suited.",
          professor: "He explained that same weights reused across time can amplify outputs and instability.",
          remember: "For RNNs, tanh defaults and gradient clipping are not accidental.",
        },
        {
          label: "Slides 136-148",
          deckLabel: "Module 1 / Lecture7",
          page: 142,
          image: "amla-slides/module1-lecture7/slide-142.png",
          title: "LSTM: learn what to store, forget and read",
          comment: "LSTM splits state into short-term h(t) and long-term c(t), controlled by gates.",
          professor: "He emphasized the black-box intuition: LSTM works like a regular recurrent cell from outside, but preserves longer dependencies better.",
          remember: "Input gate stores, forget gate removes, output gate reads.",
        },
        {
          label: "Slides 152-157",
          deckLabel: "Module 1 / Lecture7",
          page: 154,
          image: "amla-slides/module1-lecture7/slide-154.png",
          title: "GRU as a simplified LSTM",
          comment: "GRU merges states and uses fewer gates, often performing similarly while being simpler.",
          professor: "He framed LSTM/GRU as the main practical answer to simple RNN short-memory limits, though not a perfect solution for very long sequences.",
          remember: "LSTM/GRU extend memory, but transformers largely replaced them in modern large-scale language work.",
        },
      ],
    },
    {
      range: "Module 1 / Lecture7 slides 158-238",
      title: "Generative models, transformers and modern AI",
      intro: "The final part is a broad overview. The professor moved quickly, aiming to give conceptual hooks rather than full implementation detail.",
      slides: [
        {
          label: "Slides 158-161",
          deckLabel: "Module 1 / Lecture7",
          page: 159,
          image: "amla-slides/module1-lecture7/slide-159.png",
          title: "Discriminative versus generative models",
          comment: "Discriminative models learn boundaries or p(y|x). Generative models learn data distributions and can generate new samples.",
          professor: "He warned that generative AI material ages quickly because the field changes fast.",
          remember: "Use the slides for conceptual orientation, then verify modern details when using current tools.",
        },
        {
          label: "Slides 162-183",
          deckLabel: "Module 1 / Lecture7",
          page: 163,
          image: "amla-slides/module1-lecture7/slide-163.png",
          title: "VAEs as generative autoencoders",
          comment: "VAEs extend autoencoder logic into a probabilistic/generative direction by learning latent distributions.",
          professor: "He treated VAEs as a quick conceptual bridge from the autoencoders already seen earlier.",
          remember: "VAE = latent representation plus generation, not just reconstruction.",
        },
        {
          label: "Slides 184-195",
          deckLabel: "Module 1 / Lecture7",
          page: 187,
          image: "amla-slides/module1-lecture7/slide-187.png",
          title: "GANs: generator versus discriminator",
          comment: "A generator tries to produce fake samples that fool a discriminator; the discriminator learns to distinguish real from fake.",
          professor: "He used the counterfeiter/policeman analogy to make the adversarial game intuitive.",
          remember: "GAN training alternates: train D to detect fake, train G to fool D.",
        },
        {
          label: "Slides 189-208",
          deckLabel: "Module 1 / Lecture7",
          page: 194,
          image: "amla-slides/module1-lecture7/slide-194.png",
          title: "GAN training is not ordinary single-loss training",
          comment: "The generator and discriminator have different objectives, so training is an alternating minimax game.",
          professor: "He stressed that this is a true network game, not one simple cost function.",
          trap: "Do not describe GAN training as fitting one classifier end to end.",
        },
        {
          label: "Slides 210-225",
          deckLabel: "Module 1 / Lecture7",
          page: 210,
          image: "amla-slides/module1-lecture7/slide-210.png",
          title: "GAN applications and risks",
          comment: "GANs can generate, edit, augment and synthesize data, but also enable deepfakes and realistic fake content.",
          professor: "He connected generated images back to explainability: artifacts may be hard to verbalize even if humans sense something is wrong.",
          remember: "Generative models are useful, but generated outputs need critical inspection.",
        },
        {
          label: "Slides 227-235",
          deckLabel: "Module 1 / Lecture7",
          page: 231,
          image: "amla-slides/module1-lecture7/slide-231.png",
          title: "From RNN language models to transformers",
          comment: "Older language models used RNN/LSTM sequence processing; modern LLMs use transformer architectures and attention.",
          professor: "He said transformers are not RNNs anymore: the key trick is attention, not sequential memory alone.",
          remember: "GPT = Generative Pre-trained Transformer; the T matters.",
        },
        {
          label: "Slides 232-238",
          deckLabel: "Module 1 / Lecture7",
          page: 235,
          image: "amla-slides/module1-lecture7/slide-235.png",
          title: "Scaling, emergence and foundation models",
          comment: "The deck connects scaling to new abilities and the rise of large foundation models.",
          professor: "He framed this as a fast-moving frontier and mentioned compute/energy cost as a serious issue.",
          remember: "Large scale changes what models can do, but also changes cost, risk and validation requirements.",
        },
      ],
      lab: {
        title: "Mini-lab: choose an advanced topic for a project",
        objective: "Use the final lecture as a menu of advanced methods and decide which, if any, would be justified in a project.",
        href: "https://drive.google.com/file/d/1ZqHIZTOj_irE2bN9tQjhQ_1P-rhqN4cB/view?usp=drivesdk",
        steps: [
          "Pick a dataset type: tabular, image, sequence, text or synthetic/generative.",
          "State the project objective in one sentence.",
          "Choose one advanced method family that matches the data and objective.",
          "Define a simple baseline that the advanced method must beat.",
          "List the metrics and visual/error analysis needed to interpret results.",
          "Write one limitation or risk of the chosen method.",
        ],
        parameters: [
          "Data modality.",
          "Sequence length or image/text size.",
          "Baseline model.",
          "Advanced method family.",
          "Evaluation metric.",
          "Interpretability or uncertainty tool.",
        ],
        outputs: [
          "A short project method rationale.",
          "Baseline versus advanced-model comparison plan.",
          "One paragraph on failure modes and interpretation.",
        ],
        explain: [
          "Why the advanced method is justified by the data.",
          "What it adds beyond a simpler model.",
          "How you would know whether it failed.",
        ],
      },
    },
  ],
  professorEmphasis: [
    "The final class is intentionally broad; some slides are a stimulus for future study rather than fully covered exam depth.",
    "Sequential data means order matters; it does not have to be literal clock time.",
    "RNNs preserve state, but simple RNN memory is short.",
    "Always compare sequence models with baselines; RNNs do not automatically beat simple methods.",
    "Backpropagation through time is backpropagation on the unrolled time graph.",
    "Long sequences create both deep-network gradient problems and RNN-specific forgetting.",
    "LSTM and GRU are practical gated solutions, but still limited for very long contexts.",
    "Modern language models moved from RNNs to transformers and attention.",
    "Generative AI material changes quickly; current details should be checked when used in projects.",
    "Project work must justify choices, interpret outputs and disclose/validate LLM assistance.",
  ],
  commonTraps: [
    "Treating RNNs as always better than dense or convolutional alternatives for sequences.",
    "Forgetting that sequence input tensors are 3D: batch, steps, dimensionality.",
    "Confusing unrolling through time with physically copying different weights at each step.",
    "Ignoring baselines before celebrating a recurrent model.",
    "Saying LSTM has unlimited memory.",
    "Using ReLU/BatchNorm intuitions from feedforward networks without checking RNN-specific behavior.",
    "Describing GANs as one network with one ordinary objective.",
    "Assuming LLMs are just large RNNs.",
    "Submitting a project that looks polished but cannot be defended methodologically.",
  ],
  quickQuiz: [
    {
      question: "What makes data sequential?",
      answer: "The order of observations matters; shuffling the entries changes the meaning or task.",
    },
    {
      question: "What two inputs does a basic recurrent neuron use at time t?",
      answer: "The current input x(t) and the previous output/state from time t-1.",
    },
    {
      question: "What is BPTT?",
      answer: "Backpropagation through time: training an RNN by unrolling it across time steps and propagating gradients backward through that unrolled graph.",
    },
    {
      question: "Why use naive forecasting before an RNN?",
      answer: "It is a simple baseline; without it, you may overestimate the RNN's value.",
    },
    {
      question: "What is the short-memory problem?",
      answer: "Simple RNN state gradually loses information from early inputs in long sequences.",
    },
    {
      question: "What is the core idea of LSTM gates?",
      answer: "The model learns what to forget, what to store and what to output from its state.",
    },
    {
      question: "Why are transformers different from RNN language models?",
      answer: "They rely on attention mechanisms rather than processing context mainly through recurrent state.",
    },
    {
      question: "What is the basic GAN game?",
      answer: "The generator tries to fool the discriminator; the discriminator tries to distinguish real from generated data.",
    },
  ],
  examQuestions: [
    {
      id: "l12-q1",
      question: "You have 50 ordered sensor readings per sample and want to predict the next reading. Which input shape best matches the RNN framing in the lecture?",
      options: [
        "[batch_size, n_steps, dimensionality]",
        "[n_features, batch_size]",
        "[height, width, channels]",
        "[classes, probabilities]",
      ],
      correct: 0,
      explanation: "Sequence data for RNNs is represented as batch, time steps and feature dimensionality.",
    },
    {
      id: "l12-q2",
      question: "A SimpleRNN beats naive forecasting but loses to a simple FCNN baseline. What is the best conclusion?",
      options: [
        "RNNs are useless for all time series.",
        "The SimpleRNN is not justified unless it improves or adds value beyond simpler baselines.",
        "The FCNN must be removed from the report.",
        "Naive forecasting is invalid because it has no trainable parameters.",
      ],
      correct: 1,
      explanation: "The professor used this comparison to stress baseline-driven model justification.",
    },
    {
      id: "l12-q3",
      question: "Why does training an RNN on a long sequence resemble training a very deep network?",
      options: [
        "Because each time step corresponds to another unrolled copy in the training graph.",
        "Because RNNs use only convolutional filters.",
        "Because recurrent networks have no parameters.",
        "Because BPTT ignores all intermediate outputs.",
      ],
      correct: 0,
      explanation: "Unrolling through many steps creates a deep computation graph through time.",
    },
    {
      id: "l12-q4",
      question: "Which statement about LSTM is most aligned with the lecture?",
      options: [
        "It removes the need for training data.",
        "It uses gates to control what is stored, forgotten and read from memory.",
        "It is identical to logistic regression.",
        "It guarantees perfect memory for sequences of any length.",
      ],
      correct: 1,
      explanation: "LSTM uses input, forget and output gates to manage long- and short-term state.",
    },
    {
      id: "l12-q5",
      question: "In a GAN, what happens during the generator training phase?",
      options: [
        "The generator is trained to produce samples the discriminator classifies as real.",
        "The discriminator is deleted.",
        "The generator receives only real images as labels and performs PCA.",
        "Both networks are frozen.",
      ],
      correct: 0,
      explanation: "Generator training uses feedback through the discriminator to make generated samples look real.",
    },
    {
      id: "l12-q6",
      question: "Why should the final project report disclose LLM use?",
      options: [
        "Because LLMs are prohibited for every task.",
        "Because transparency matters and students remain responsible for choices, code and interpretation.",
        "Because disclosure replaces model evaluation.",
        "Because generated text automatically improves the score.",
      ],
      correct: 1,
      explanation: "LLMs can support implementation and communication, but responsibility and understanding remain with the student.",
    },
  ],
  checklistTitle: "Final AMLA checklist",
  studyChecklist: [
    "For the project, write a self-contained report with goal, data, methods, results and interpretation.",
    "Add code/repo links and disclose LLM use when relevant.",
    "Use baselines before advanced models.",
    "For sequence tasks, identify input/output mapping: seq2seq, seq2vec, vec2seq or encoder-decoder.",
    "Explain hidden state and BPTT without getting lost in notation.",
    "Know why simple RNNs struggle with long sequences.",
    "Explain LSTM/GRU gates at intuition level.",
    "Connect transformers to attention and token sequences, not to simple recurrent memory.",
    "Treat VAEs/GANs as conceptual advanced extensions unless you implement and evaluate them carefully.",
    "End every advanced method section with interpretation, limitations and failure modes.",
  ],
};
