export const lessonContent = {
  id: "amla-2026-04-23-deep-learning-frameworks",
  extractionStatus: "source-based complete draft",
  objectives: [
    "Represent an artificial neural network with layers, activations, bias units and weight matrices.",
    "Compute the expected dimensions of a weight matrix between two consecutive layers.",
    "Explain feed-forward propagation as repeated weighted sums plus nonlinear activations.",
    "Explain why hidden layers give MLPs their representational power.",
    "Use the XNOR example to understand why one layer can be insufficient and why hidden layers matter.",
    "Contrast neural networks as black-box feature builders with decision trees as more interpretable white-box models.",
    "Describe how decision trees handle classification, regression, probabilities, overfitting and instability.",
  ],
  coreConcepts: [
    {
      title: "Bias unit",
      body: "A bias unit is an extra input with value 1. It gives the neuron an adjustable offset through its own weight.",
      keywords: ["x0 = 1", "offset", "bias weight"],
    },
    {
      title: "Activation",
      body: "An activation is the output of a neuron after applying a nonlinear function such as sigmoid to a weighted sum.",
      keywords: ["sigmoid", "nonlinearity", "a(j)i"],
    },
    {
      title: "Weight matrix",
      body: "The weights from layer j to layer j+1 form a matrix. If layer j has sj units and layer j+1 has sj+1 units, the matrix has sj+1 rows and sj + 1 columns because of the bias.",
      keywords: ["Theta", "dimensions", "layers"],
    },
    {
      title: "Forward propagation",
      body: "Forward propagation starts from input activations and repeatedly computes the next layer until the output hypothesis is reached.",
      keywords: ["input to output", "z", "a"],
    },
    {
      title: "Hidden-layer horsepower",
      body: "The last layer may look like logistic regression, but hidden layers transform the input into features that make the final decision possible.",
      keywords: ["feature learning", "MLP", "black box"],
    },
    {
      title: "XNOR",
      body: "XNOR is a small logical example showing why a single perceptron is limited and why combining neurons in hidden layers can solve nonlinear patterns.",
      keywords: ["AND", "OR", "NOT", "nonlinear"],
    },
    {
      title: "Decision tree",
      body: "A decision tree recursively splits feature space. It can handle classification and regression, is easy to inspect, but can overfit and be unstable.",
      keywords: ["CART", "white box", "overfitting"],
    },
  ],
  walkthroughSections: [
    {
      range: "Module 1 / Lecture2 slides 1-12",
      title: "Represent the network before training it",
      intro: "The first part of the lecture formalizes what the notebook has been using informally: inputs, activations, weights, bias and the shape of the matrices moving information between layers.",
      slides: [
        {
          label: "Slide 3",
          deckLabel: "Module 1 / Lecture2",
          page: 3,
          image: "amla-slides/module1-lecture2/slide-03.png",
          title: "The hypothesis is the network computation",
          comment: "The goal is to represent how a neural network computes its hypothesis, not yet how it learns the weights.",
          professor: "He said the lecture would be slightly formal but still mainly intuition-level: enough to understand the important components of any network.",
          remember: "Separate representation from training: first know what is computed, then ask how weights are learned.",
        },
        {
          label: "Slides 4-5",
          deckLabel: "Module 1 / Lecture2",
          page: 4,
          image: "amla-slides/module1-lecture2/slide-04.png",
          title: "Jargon: bias, sigmoid, weights",
          comment: "The notation introduces x0 as the bias unit, sigmoid/logistic activation as the nonlinearity, and theta parameters as neural-network weights.",
          professor: "He explicitly shifted vocabulary: for networks he prefers calling theta parameters weights.",
          remember: "A neuron is a nonlinear function applied to a linear combination of inputs plus bias.",
          trap: "Do not forget the bias column when computing weight-matrix dimensions.",
        },
        {
          label: "Slides 6-9",
          deckLabel: "Module 1 / Lecture2",
          page: 6,
          image: "amla-slides/module1-lecture2/slide-06.png",
          title: "Layers, activations and weight matrices",
          comment: "Once a network has more than one layer, every transition between layers has its own matrix of weights.",
          professor: "He emphasized that connections and weights grow quickly when layers and neurons are added.",
          remember: "Layer j activations feed layer j+1 through a weight matrix specific to that transition.",
        },
        {
          label: "Slides 10-11",
          deckLabel: "Module 1 / Lecture2",
          page: 10,
          image: "amla-slides/module1-lecture2/slide-10.png",
          title: "Check-your-understanding: Theta dimensions",
          comment: "If layer 1 has two input nodes and layer 2 has four activation nodes, Theta(1) has four rows and three columns: one row per next-layer neuron, one column per previous unit plus bias.",
          professor: "He used this quiz to make students actively track sj, sj+1 and the extra bias term.",
          remember: "Dimension rule: Theta(j) is sj+1 by (sj + 1).",
          trap: "The +1 belongs to the previous layer because of the bias input, not to the number of next-layer neurons.",
        },
      ],
      lab: {
        title: "Mini-lab: matrix dimensions by hand",
        todo: "No notebook needed for this checkpoint; do it on paper before coding.",
        objective: "Given an architecture, compute the dimensions of each weight matrix before writing code.",
        steps: [
          "Draw an input layer with 3 features, two hidden layers with 5 and 2 neurons, and an output layer with 1 neuron.",
          "Add a bias unit to every non-output layer feeding another layer.",
          "Write the dimension of each Theta matrix.",
          "Check whether your dimensions make matrix multiplication possible.",
        ],
        parameters: ["number of units per layer", "bias term", "Theta row/column convention"],
        outputs: ["Theta(1) dimension", "Theta(2) dimension", "Theta(3) dimension"],
        explain: [
          "Why the bias adds a column to the matrix.",
          "Why the number of rows equals the number of units in the next layer.",
        ],
      },
    },
    {
      range: "Module 1 / Lecture2 slides 13-24",
      title: "Forward propagation: repeated transformations through layers",
      intro: "This block is the mathematical heart of the first half: each layer computes weighted sums, applies activation and passes the result forward.",
      slides: [
        {
          label: "Slides 13-18",
          deckLabel: "Module 1 / Lecture2",
          page: 13,
          image: "amla-slides/module1-lecture2/slide-13.png",
          title: "Vectorizing neuron computations",
          comment: "Instead of writing one weighted sum per neuron, the network groups them into vectors and matrices. This is how the computation becomes efficient.",
          professor: "He said the notation is useful because every layer transforms the previous activation into the next one.",
          remember: "z is the weighted sum; a is the activation after applying the nonlinearity.",
        },
        {
          label: "Slide 24",
          deckLabel: "Module 1 / Lecture2",
          page: 24,
          image: "amla-slides/module1-lecture2/slide-24.png",
          title: "Feed-forward propagation summary",
          comment: "Forward propagation starts from input activations and moves layer by layer to the output.",
          professor: "He described this as the process that explains how a network computes and where its power comes from.",
          remember: "Forward propagation computes predictions. It is not the same thing as learning the weights.",
        },
      ],
    },
    {
      range: "Module 1 / Lecture2 slides 25-42",
      title: "Hidden layers create features: the XNOR example",
      intro: "The lecture uses logical functions to make the role of hidden layers visible. XNOR is small, but historically important because it shows the limitation of a single perceptron.",
      slides: [
        {
          label: "Slides 25-27",
          deckLabel: "Module 1 / Lecture2",
          page: 25,
          image: "amla-slides/module1-lecture2/slide-25.png",
          title: "Complexity goes in the hidden layers",
          comment: "The hidden layers can transform the original inputs into internal features that make the final decision easy.",
          professor: "He repeated that the final layer can look like logistic regression, but it receives digested features, not the raw input.",
          remember: "The horsepower of an MLP is in the hidden layers.",
        },
        {
          label: "Slides 34-42",
          deckLabel: "Module 1 / Lecture2",
          page: 34,
          image: "amla-slides/module1-lecture2/slide-34.png",
          title: "XNOR from simpler logical blocks",
          comment: "AND, OR and NOT-like units can be combined so a hidden layer computes useful intermediate logic and the output layer combines it.",
          professor: "He stressed that something impossible with one layer becomes solvable with two layers.",
          remember: "Adding a hidden layer changes the class of functions the model can represent.",
          trap: "More neurons in one layer do not automatically replace the need for depth when the architecture cannot represent the function.",
        },
        {
          label: "Slide 42",
          deckLabel: "Module 1 / Lecture2",
          page: 42,
          image: "amla-slides/module1-lecture2/slide-42.png",
          title: "Summary: simple neurons can compose complex logic",
          comment: "The slide summarizes the point: individual neurons are simple, but arranged together they can implement nonlinear logical functions.",
          professor: "He warned that this does not mean every real problem is solved by blindly adding layers and neurons; the architecture still matters.",
          remember: "Depth and width are tools, not magic.",
        },
      ],
    },
    {
      range: "Module 1 / Lecture2 slides 43-58",
      title: "Switch to decision trees: a useful non-network model",
      intro: "The second half deliberately leaves neural networks. The professor wants students to stay comfortable in a mixed ML world where simpler models may be the right answer.",
      slides: [
        {
          label: "Slides 43-45",
          deckLabel: "Module 1 / Lecture2",
          page: 44,
          image: "amla-slides/module1-lecture2/slide-44.png",
          title: "Decision trees are versatile baselines",
          comment: "Decision trees can do classification, regression and even multi-output tasks. They are powerful enough to fit complex datasets and are the foundation for random forests.",
          professor: "He said AMLA should not become networks-only: other algorithms exist and may be better for a problem.",
          remember: "Always compare model families. Advanced does not mean neural network by default.",
        },
        {
          label: "Slides 46-50",
          deckLabel: "Module 1 / Lecture2",
          page: 48,
          image: "amla-slides/module1-lecture2/slide-48.png",
          title: "Iris classification and tree structure",
          comment: "The Iris example shows root nodes, internal nodes, leaf nodes and depth. The tree makes explicit feature-threshold decisions.",
          professor: "He noted that decision-tree code is closer to Basic-course sklearn workflows than the Keras workflow.",
          remember: "A decision path is inspectable: feature, threshold, branch, leaf.",
        },
        {
          label: "Slide 54",
          deckLabel: "Module 1 / Lecture2",
          page: 54,
          image: "amla-slides/module1-lecture2/slide-54.png",
          title: "Class probabilities from leaves",
          comment: "A tree estimates class probabilities by routing an instance to a leaf and looking at class proportions among training samples in that leaf.",
          professor: "He used this to show that tree outputs are explainable through the route and the leaf composition.",
          remember: "Tree probability is local to the leaf reached by the instance.",
        },
        {
          label: "Slides 55-58",
          deckLabel: "Module 1 / Lecture2",
          page: 57,
          image: "amla-slides/module1-lecture2/slide-57.png",
          title: "White box versus black box",
          comment: "Decision trees are comparatively transparent because you can follow decisions manually. Neural networks are harder to explain because learned hidden features are not directly human rules.",
          professor: "He explicitly contrasted a tree's visible rules with the difficulty of explaining individual neural-network weights.",
          remember: "Interpretability can be a reason to prefer a simpler model when performance is good enough.",
          trap: "White-box does not mean always better; it means easier to inspect.",
        },
      ],
    },
    {
      range: "Module 1 / Lecture2 slides 58-70",
      title: "CART, regression, overfitting and instability",
      intro: "The final block gives the practical cautions. Decision trees are simple to try, but they need regularization and can be unstable.",
      slides: [
        {
          label: "Slide 58",
          deckLabel: "Module 1 / Lecture2",
          page: 58,
          image: "amla-slides/module1-lecture2/slide-58.png",
          title: "CART produces binary trees",
          comment: "Sklearn uses CART, where non-leaf nodes ask yes/no questions and split into two children.",
          professor: "He did not require every training-detail formula, but wanted students to know what sklearn is doing at a high level.",
          remember: "CART recursively splits the data to reduce impurity or error.",
        },
        {
          label: "Slides 59-63",
          deckLabel: "Module 1 / Lecture2",
          page: 61,
          image: "amla-slides/module1-lecture2/slide-61.png",
          title: "Decision trees also do regression",
          comment: "For regression, a tree predicts numeric values. Each region predicts the average target value of training instances in that region.",
          professor: "He contrasted classification impurity with regression MSE.",
          remember: "Same tree logic, different output and cost function.",
        },
        {
          label: "Slides 64-68",
          deckLabel: "Module 1 / Lecture2",
          page: 64,
          image: "amla-slides/module1-lecture2/slide-64.png",
          title: "Overfitting and instability",
          comment: "Unregularized trees can overfit. Small changes or stochastic training details can produce different trees unless randomness is controlled.",
          professor: "He said if a tree is good enough, keep it; if it cannot compete, then try more complex models such as networks or ensembles.",
          remember: "Use depth, leaf and split constraints as regularization; set random_state when reproducibility matters.",
          trap: "A very interpretable tree can still generalize badly if it is overfit.",
        },
        {
          label: "Slide 70",
          deckLabel: "Module 1 / Lecture2",
          page: 70,
          image: "amla-slides/module1-lecture2/slide-70.png",
          title: "Decision-tree notebook",
          comment: "The slide points to the course GitHub repository and the `AMLAdv_HandsOn_DT.ipynb` notebook.",
          professor: "The notebook is the practical follow-up for training and inspecting trees.",
          remember: "When expanding the practical part later, connect each tree plot to interpretability, overfitting and hyperparameters.",
        },
      ],
      lab: {
        title: "Mini-lab: inspect a decision tree before replacing it",
        href: "https://github.com/dbonacorsi/AML-Adv/",
        objective: "Use the linked repository/notebook to train a small tree and decide whether its transparency is useful enough.",
        steps: [
          "Open `AMLAdv_HandsOn_DT.ipynb` from the repository.",
          "Train a DecisionTreeClassifier on Iris with two features.",
          "Plot or inspect the tree structure.",
          "Change max_depth or max_leaf_nodes and compare boundaries.",
          "Try a DecisionTreeRegressor on the quadratic/noisy regression example.",
        ],
        parameters: ["max_depth", "max_leaf_nodes", "random_state", "criterion", "min_samples_leaf"],
        outputs: ["tree plot", "decision boundaries", "class probabilities", "regression regions", "train/test score"],
        explain: [
          "Why the tree is interpretable.",
          "How overfitting appears when the tree is too unconstrained.",
          "Why random_state matters for reproducibility.",
          "When a tree is a good baseline before trying neural networks.",
        ],
      },
    },
  ],
  slidePath: [
    {
      range: "Slides 3-12",
      title: "NN formalism",
      concept: "Represent networks through activations, bias units, weights and matrix dimensions.",
      intuition: "A network is a chain of computations; notation tells you what flows where.",
      professor: "He kept the formalism at intuition level: enough to read architectures and calculations.",
      remember: "Theta(j) dimensions are sj+1 by (sj + 1).",
    },
    {
      range: "Slides 13-24",
      title: "Forward propagation",
      concept: "Repeatedly transform the previous layer's activations into the next layer.",
      intuition: "Each layer computes more processed features than the previous one.",
      professor: "He said the computation itself explains where networks get their power.",
      remember: "Forward propagation computes the output; training finds the weights.",
    },
    {
      range: "Slides 25-42",
      title: "Hidden-layer power",
      concept: "Hidden layers can compose simple units into nonlinear functions like XNOR.",
      intuition: "The final decision can be simple once hidden layers expose the right internal features.",
      professor: "He used XNOR to show why one layer is not always enough.",
      remember: "Architecture matters: sometimes the missing ingredient is depth.",
    },
    {
      range: "Slides 43-70",
      title: "Decision trees",
      concept: "Decision trees offer an interpretable non-network alternative for classification and regression.",
      intuition: "A tree splits feature space with readable rules; its simplicity is both a strength and a risk.",
      professor: "He contrasted tree interpretability with neural-network black-box behavior.",
      remember: "Try simpler, interpretable baselines before jumping to neural networks.",
    },
  ],
  professorEmphasis: [
    "AMLA should remain a mixed ML world: neural networks are important, but other algorithms can be the right solution.",
    "Bias units are fake constant inputs, but they give neurons useful flexibility.",
    "Weights are the trained object of the network; the trained weight matrices are the model.",
    "Hidden layers transform inputs into features that make the final decision possible.",
    "At the final layer, a network may look like logistic regression, but it acts on learned internal features.",
    "XNOR shows why the history of multilayer perceptrons matters: one layer is not always enough.",
    "Adding layers and neurons is not magic; architecture and trainability still matter.",
    "Decision trees are transparent and easy to inspect, but prone to overfitting and instability.",
    "If a decision tree solves the problem well enough, you may not need a neural network.",
  ],
  commonTraps: [
    "Forgetting the bias column when computing Theta dimensions.",
    "Thinking forward propagation is the training algorithm; it is only the prediction computation.",
    "Saying the network's final logistic-regression-like layer receives raw inputs; it receives hidden-layer activations.",
    "Treating hidden layers as automatically interpretable engineered features.",
    "Assuming more neurons in one layer always replaces the need for additional layers.",
    "Thinking decision trees require feature scaling like many distance/gradient-based methods.",
    "Calling a decision tree good only because it is interpretable; it still needs validation against overfitting.",
    "Ignoring random_state when comparing tree outputs across runs.",
  ],
  miniLab: {
    title: "Two-part practice: dimensions and decision-tree baseline",
    href: "https://github.com/dbonacorsi/AML-Adv/",
    objective: "Practice the two halves of the lecture: NN matrix dimensions and interpretable tree baselines.",
    steps: [
      "Compute Theta dimensions for a small MLP by hand.",
      "Explain one forward-propagation step from input to hidden activation.",
      "Open the decision-tree notebook from the course GitHub repository.",
      "Train a small Iris tree and inspect the path to a prediction.",
      "Change a regularization parameter and describe the new tree.",
    ],
    parameters: ["layer sizes", "bias units", "max_depth", "max_leaf_nodes", "random_state"],
    outputs: ["Theta dimensions", "tree diagram", "decision boundary", "class probability at leaf"],
    explain: [
      "Why hidden layers increase representational power.",
      "Why decision trees are easier to explain than neural networks.",
      "Why tree simplicity does not remove the need for validation.",
    ],
  },
  quickQuiz: [
    {
      question: "Why does Theta(j) have sj + 1 columns?",
      answer: "Because the previous layer contributes sj activations plus one bias unit.",
    },
    {
      question: "What is forward propagation?",
      answer: "It is the computation that starts from input activations and propagates layer by layer until the output hypothesis is produced.",
    },
    {
      question: "Why can the final layer resemble logistic regression?",
      answer: "Because it may apply a familiar final decision function, but to hidden-layer activations rather than raw inputs.",
    },
    {
      question: "What does the XNOR example show?",
      answer: "It shows that a problem impossible for a single layer can become solvable when hidden layers combine simpler logical units.",
    },
    {
      question: "Why are decision trees called white-box models in this lecture?",
      answer: "Because the prediction path can be followed through visible feature-threshold decisions.",
    },
    {
      question: "How does a decision tree estimate class probability?",
      answer: "It routes the instance to a leaf and uses the class proportions of training samples in that leaf.",
    },
    {
      question: "Why can decision trees overfit?",
      answer: "If unconstrained, they can create very specific splits that fit training noise rather than general structure.",
    },
  ],
  examQuestions: [
    {
      id: "l04-mcq-1",
      question: "Layer j has 3 activation units and layer j+1 has 5 units. What is the dimension of Theta(j)?",
      options: ["3 x 5", "5 x 3", "5 x 4", "4 x 5"],
      correct: 2,
      explanation: "There is one row per next-layer unit and sj + 1 columns because the previous layer includes the bias unit.",
    },
    {
      id: "l04-mcq-2",
      question: "Which statement best separates forward propagation from training?",
      options: [
        "Forward propagation learns the weights; training only formats the data.",
        "Forward propagation computes outputs using current weights; training adjusts the weights.",
        "Forward propagation is used only by decision trees.",
        "Forward propagation removes the need for activation functions.",
      ],
      correct: 1,
      explanation: "Forward propagation is the prediction computation. Training is the process that finds useful weights.",
    },
    {
      id: "l04-mcq-3",
      question: "Why is the XNOR example useful for understanding MLPs?",
      options: [
        "It proves one perceptron can solve every Boolean function.",
        "It shows that hidden layers can combine simple units to solve a nonlinear pattern.",
        "It shows that activation functions should always be linear.",
        "It is a decision-tree-only example.",
      ],
      correct: 1,
      explanation: "XNOR is the classic demonstration that a single layer can be insufficient while a hidden layer can make the problem solvable.",
    },
    {
      id: "l04-mcq-4",
      question: "A student says decision trees are always preferable because they are interpretable. What is the best correction?",
      options: [
        "Interpretability is useful, but trees can overfit and may underperform more complex models.",
        "Decision trees are black boxes, so they are never interpretable.",
        "Decision trees cannot do regression.",
        "Decision trees require neural-network activations.",
      ],
      correct: 0,
      explanation: "The lecture presents trees as transparent and useful, but also unstable and prone to overfitting.",
    },
    {
      id: "l04-mcq-5",
      question: "For a decision-tree leaf containing 40 training samples, 30 from class A and 10 from class B, what probability would the tree estimate for class A at that leaf?",
      options: ["0.25", "0.50", "0.75", "1.00"],
      correct: 2,
      explanation: "The class probability is the proportion of training samples in that leaf: 30/40 = 0.75.",
    },
  ],
  checklistTitle: "What to take from L04",
  studyChecklist: [
    "Be able to compute Theta dimensions for any two consecutive layers.",
    "Explain z, activation and forward propagation without jumping to training.",
    "Say why hidden layers create the representational power of MLPs.",
    "Use XNOR as the compact example of why multilayer architectures matter.",
    "Explain decision-tree predictions by following a path from root to leaf.",
    "Know that trees can do both classification and regression.",
    "Remember the trade-off: trees are interpretable but can overfit and be unstable.",
    "Use the DT notebook as a baseline exercise before assuming a neural network is needed.",
  ],
};
