import React from "react";

const toneClasses = {
  stone: "border-stone-200 bg-stone-50 text-stone-900",
  red: "border-red-100 bg-red-50 text-red-950",
  dark: "border-stone-800 bg-stone-950 text-white",
  green: "border-emerald-100 bg-emerald-50 text-emerald-950",
  amber: "border-amber-100 bg-amber-50 text-amber-950",
  sky: "border-sky-100 bg-sky-50 text-sky-950",
  purple: "border-violet-100 bg-violet-50 text-violet-950",
};

const copy = {
  en: {
    eyebrow: "Lesson 04 · Orthology inference and taxon sampling",
    title: "Design a phylogenomic dataset before building the tree.",
    subtitle:
      "This lesson moves from tree thinking and molecular characters to experimental design: which species to sample, which sequencing strategy to use, and which genes are actually comparable for species-tree inference.",
    tags: ["taxon sampling", "orthology", "paralogy", "orthogroups", "sequencing strategy", "reciprocal best hits", "OrthoFinder"],
    coreLabel: "Core idea",
    core:
      "A phylogenetic tree is only as reliable as the dataset behind it: broad taxon sampling reduces artefacts, and orthologous genes are needed because they carry the signal of speciation rather than duplication.",
    pathTitle: "How this lesson is built",
    path: [
      ["1", "Experiment design", "Which species and which data type should be used?"],
      ["2", "Sampling bias", "How missing taxa can distort topology and branch lengths."],
      ["3", "Sequencing choices", "Transcriptomes, genomes, mitogenomes and reduced representation."],
      ["4", "Orthology", "Why genes generated by speciation are central for species trees."],
      ["5", "Orthogroups", "How pairwise orthology becomes a multi-species gene set."],
    ],
    emphasisTitle: "What the professor stressed",
    emphasis: [
      ["Experimental design comes first", "Before alignment, model selection or inference, decide which species and which sequencing strategy fit the biological question.", "sky"],
      ["Sampling is not cosmetic", "Incomplete or biased sampling can cause long branch attraction, artificial clades, loss of signal and misleading rate estimates.", "red"],
      ["Homology is not enough", "For species-tree inference, the most useful genes are orthologs: homologous genes whose divergence traces speciation events.", "green"],
      ["Function is not the definition", "The orthology conjecture connects orthology and function, but in this course the key criterion is the evolutionary mechanism: speciation vs duplication.", "amber"],
      ["Orthogroups are homology groups", "An orthogroup can contain orthologs and in-paralogs. It is defined by a reference speciation event and a single ancestral gene in the LCA of the studied species.", "purple"],
    ],
    sections: {
      big: [
        "Big picture",
        "Lesson 04 starts the real phylogenomic workflow. The professor frames this as the beginning of the experimental arc: taxon sampling, orthology inference, alignment and trimming, phylogenetic subsampling, model selection, phylogenetic inference and statistical support.",
        "The central question is not yet ‘which tree-building algorithm should I use?’ but rather ‘what data should I put into the analysis so that the tree can answer my biological question?’",
      ],
      workflow: [
        "The phylogenomic workflow",
        [
          ["Taxon sampling", "Choose species broadly and representatively, including appropriate outgroups and intermediate taxa."],
          ["Orthology inference", "Find genes whose relationships track speciation rather than duplication."],
          ["Alignment + trimming", "Compare homologous sites and remove regions that are poorly aligned or misleading."],
          ["Phylogenetic subsampling", "Reduce or filter genes/sites when too much data include too much noise or bias."],
          ["Model selection", "Choose an evolutionary model that approximates how sequences changed."],
          ["Inference + support", "Infer the tree and quantify confidence; trees remain hypotheses."],
        ],
      ],
      sampling: [
        "Taxon sampling: which species?",
        "A good sampling strategy should reflect the diversity and age of the group being studied. If one clade has many species and another has few, sampling should roughly respect that imbalance rather than over-representing a convenient subgroup.",
        [
          ["Long branch attraction", "Distant taxa with long branches may cluster together if intermediate taxa are missing."],
          ["Artificial clades", "A group may look monophyletic only because an unsampled taxon that breaks it is absent."],
          ["Loss of signal", "Sparse sampling reduces informative comparisons and can leave relationships unresolved."],
          ["Model inadequacy", "Missing taxa can distort rate estimation, branch lengths and downstream dating."],
        ],
        "Practical rule: use broad sampling, sensible outgroups and intermediate taxa whenever possible.",
      ],
      sequencing: [
        "Sequencing strategy: what are we actually sequencing?",
        [
          ["Transcriptomes", "Many expressed markers, relatively cheap, no reference genome needed; but expression is tissue/stage dependent, assemblies can be incomplete or chimeric, and fresh tissue/RNA quality matters."],
          ["Genomes", "Very rich and future-proof; better gene recovery and structural information, but still expensive and computationally heavier, especially at chromosome scale."],
          ["Mitochondrial genomes", "Cheap, high-copy and useful for degraded samples; but they provide few markers, can saturate, are maternally inherited and may not represent the species history."],
          ["UCEs / reduced representation", "Cost-effective for large sampling and museum specimens; but loci are chosen a priori and may not support full orthology inference."],
          ["RADseq / GBS", "Very cheap and useful especially at shallow scales; less ideal for deep phylogenetics."],
          ["PCR markers", "Historically important but limited, labour-intensive and dependent on prior knowledge for primer design."],
        ],
        "The professor’s practical attitude is the Latin-style middle ground: choose the data type that is feasible and appropriate, not necessarily the most expensive option.",
      ],
      homology: [
        "From homology to orthology",
        "Homology means shared ancestry, but homologous genes are not automatically equally useful for species-tree inference. The key question is which evolutionary event generated the gene split.",
        [
          ["Orthologs", "Homologous genes in different species whose divergence was generated by speciation. These are the primary markers for reconstructing species relationships.", "green"],
          ["Paralogs", "Homologous genes whose divergence was generated by duplication. Their tree can reflect gene duplication history rather than species history.", "amber"],
          ["Xenologs", "Genes whose relationship is shaped by horizontal transfer. Important in some systems, especially microbes, but not the main focus here.", "sky"],
        ],
        "Exam trap: sequence similarity or function is not the definition of orthology. The defining mechanism is speciation.",
      ],
      paralogy: [
        "One-to-one, one-to-many, in-paralogs and out-paralogs",
        [
          ["One-to-one orthologs", "A single copy in one species corresponds to a single copy in another species; these are clean and especially attractive for species-tree analyses."],
          ["One-to-many / many-to-many", "Duplications after speciation can create multiple copies in one or more lineages."],
          ["In-paralogs", "Duplicates that arose after the reference speciation event. They can belong to the same orthogroup."],
          ["Out-paralogs", "Duplicates that arose before the reference speciation event. They belong to different orthogroups relative to that species set."],
        ],
        "The reference speciation event matters: whether a duplication is ‘in’ or ‘out’ depends on the comparison being made.",
      ],
      orthogroup: [
        "Orthogroups: the multi-species version of the problem",
        "Orthology is originally pairwise. In phylogenomics we usually compare many species, so the useful unit becomes the orthogroup: a set of homologous genes descending from a single gene in the last common ancestor of the species considered.",
        [
          ["What it contains", "Orthologs plus in-paralogs that arose after the relevant speciation events."],
          ["What it excludes", "Out-paralogs generated by duplications before the LCA of the studied species."],
          ["Why it matters", "Orthogroups organize thousands of genes into comparable sets for downstream alignment and tree inference."],
        ],
        "Take-home phrase: an orthogroup is a homology group, not a pure set of only one-to-one orthologs.",
      ],
      inference: [
        "How orthology inference works in practice",
        "The practical workflow starts from species and their protein-coding genes. Homology searches are performed across species, best reciprocal hits are retained, and then clustering or gene-tree approaches are used to infer orthogroups.",
        [
          ["All-vs-all search", "Compare proteins across all species pairs using tools such as BLAST or DIAMOND."],
          ["Reciprocal best hits", "Keep pairs where each gene identifies the other as its best match; this helps reduce false matches when genes are missing, lost or too divergent."],
          ["Clustering / gene trees", "Group reciprocal relationships into orthogroups, often with tools such as OrthoFinder."],
          ["Quality check", "A useful metric is how many genes from each species are assigned to orthogroups."],
        ],
      ],
      exam: [
        "How to recognize exam questions",
        [
          ["‘Orthologous genes are…’", "Answer with speciation: homologous genes that diverged after a cladogenetic/speciation event."],
          ["‘Orthogroup’", "A homologous gene set descending from a single ancestral gene in the LCA of the studied species."],
          ["‘Why taxon sampling matters?’", "Think long branch attraction, artificial clades, loss of signal and model/rate problems."],
          ["‘Transcriptome vs genome vs mitogenome’", "Compare feasibility, amount of markers, sample requirements and limitations."],
          ["‘Reciprocal best hit’", "A filtering idea used to identify likely homologs/orthologs across species while controlling for missing or divergent copies."],
        ],
      ],
      checklist: [
        "Before Lesson 05, I can...",
        [
          "Explain why taxon sampling is part of experimental design.",
          "Describe how biased sampling can produce long branch attraction or artificial clades.",
          "Compare transcriptomes, genomes, mitogenomes and reduced representation approaches.",
          "Distinguish homology, orthology and paralogy.",
          "Explain one-to-one, one-to-many, in-paralogs and out-paralogs.",
          "Define an orthogroup and why it is a homology group.",
          "Describe the logic of reciprocal best hits and OrthoFinder-like workflows.",
        ],
      ],
    },
    visual: {
      species: "species",
      genes: "genes",
      speciation: "speciation",
      duplication: "duplication",
      orthologs: "orthologs",
      paralogs: "paralogs",
      search: "all-vs-all search",
      reciprocal: "reciprocal best hits",
      groups: "orthogroups",
    },
  },
  es: {
    eyebrow: "Lección 04 · Inferencia de ortología y muestreo taxonómico",
    title: "Diseñar el dataset filogenómico antes de construir el árbol.",
    subtitle:
      "Esta lección pasa del tree thinking y los caracteres moleculares al diseño experimental: qué especies muestrear, qué estrategia de secuenciación usar y qué genes son realmente comparables para inferir árboles de especies.",
    tags: ["muestreo taxonómico", "ortología", "paralogía", "orthogroups", "secuenciación", "reciprocal best hits", "OrthoFinder"],
    coreLabel: "Idea central",
    core:
      "Un árbol filogenético depende de la calidad del dataset: un muestreo amplio reduce artefactos, y los genes ortólogos son necesarios porque portan señal de especiación y no de duplicación.",
    pathTitle: "Cómo se construye esta lección",
    path: [
      ["1", "Diseño experimental", "¿Qué especies y qué tipo de datos conviene usar?"],
      ["2", "Sesgo de muestreo", "Cómo los taxones ausentes pueden distorsionar topología y ramas."],
      ["3", "Estrategias de secuenciación", "Transcriptomas, genomas, mitogenomas y reducción de representación."],
      ["4", "Ortología", "Por qué los genes generados por especiación son centrales para árboles de especies."],
      ["5", "Orthogroups", "Cómo la ortología por pares se convierte en un conjunto multi-especie."],
    ],
    emphasisTitle: "Lo que el profe remarcó",
    emphasis: [
      ["El diseño experimental va primero", "Antes de alinear, elegir modelo o inferir árboles, hay que decidir qué especies y qué estrategia de secuenciación responden la pregunta biológica.", "sky"],
      ["El muestreo no es decorativo", "Un muestreo incompleto o sesgado puede causar long branch attraction, clados artificiales, pérdida de señal y estimaciones de tasa engañosas.", "red"],
      ["Homología no basta", "Para inferir árboles de especies, los genes más útiles son los ortólogos: genes homólogos cuya divergencia sigue eventos de especiación.", "green"],
      ["La función no define la ortología", "La orthology conjecture conecta ortología y función, pero aquí el criterio clave es el mecanismo evolutivo: especiación vs duplicación.", "amber"],
      ["Los orthogroups son grupos de homología", "Un orthogroup puede contener ortólogos e in-paralogs. Se define por un evento de especiación de referencia y un único gen ancestral en el LCA.", "purple"],
    ],
    sections: {
      big: [
        "Big picture",
        "La lección 04 inicia el flujo filogenómico real. El profesor lo presenta como el arco del experimento: muestreo taxonómico, inferencia de ortología, alineamiento y trimming, subsampling filogenético, selección de modelos, inferencia y soporte estadístico.",
        "La pregunta central todavía no es ‘¿qué algoritmo uso?’, sino ‘¿qué datos debo usar para que el árbol responda la pregunta biológica?’",
      ],
      workflow: ["El flujo filogenómico", [["Muestreo taxonómico", "Elegir especies de forma amplia y representativa, incluyendo outgroups e intermedios adecuados."], ["Inferencia de ortología", "Encontrar genes cuyas relaciones sigan especiación y no duplicación."], ["Alineamiento + trimming", "Comparar sitios homólogos y remover regiones mal alineadas o engañosas."], ["Subsampling filogenético", "Filtrar genes o sitios cuando demasiado dato también trae ruido o sesgo."], ["Selección de modelos", "Elegir un modelo que aproxime cómo cambiaron las secuencias."], ["Inferencia + soporte", "Inferir el árbol y cuantificar confianza; los árboles siguen siendo hipótesis."]]],
      sampling: ["Muestreo taxonómico: ¿qué especies?", "Un buen muestreo debe reflejar la diversidad y edad del grupo. Si un clado tiene muchas especies y otro pocas, el muestreo debería respetar esa diversidad y no solo lo que sea cómodo.", [["Long branch attraction", "Taxones distantes con ramas largas pueden agruparse si faltan taxones intermedios."], ["Clados artificiales", "Un grupo puede parecer monofilético solo porque falta un taxón que lo rompería."], ["Pérdida de señal", "Un muestreo pobre reduce comparaciones informativas y deja relaciones ambiguas."], ["Inadecuación del modelo", "Taxones ausentes pueden distorsionar tasas, longitudes de rama y datación."]], "Regla práctica: muestreo amplio, outgroups sensatos y taxones intermedios siempre que sea posible."],
      sequencing: ["Estrategia de secuenciación: ¿qué estamos secuenciando?", [["Transcriptomas", "Muchos marcadores expresados, relativamente baratos y sin genoma de referencia; pero dependen de tejido/etapa, pueden estar incompletos y requieren buen RNA."], ["Genomas", "Muy ricos y reutilizables; mejor recuperación génica e información estructural, pero más caros y pesados computacionalmente."], ["Mitogenomas", "Baratos, abundantes y útiles con muestras degradadas; pero tienen pocos marcadores, pueden saturarse y solo cuentan una parte de la historia."], ["UCEs / representación reducida", "Útiles para muestreos enormes y especímenes de museo; pero los loci se eligen a priori y no siempre permiten inferencia completa de ortología."], ["RADseq / GBS", "Muy baratos y útiles a escalas someras; menos ideales para filogenética profunda."], ["PCR", "Históricamente importante, pero limitada, laboriosa y dependiente de primers diseñados con conocimiento previo."]], "La idea práctica del profe: escoger el punto medio razonable entre coste, factibilidad e información."],
      homology: ["De homología a ortología", "Homología significa ancestro común, pero no todos los genes homólogos son igualmente útiles para inferir árboles de especies. Lo importante es qué evento generó la divergencia del gen.", [["Ortólogos", "Genes homólogos en especies distintas cuya divergencia fue generada por especiación. Son los marcadores principales para árboles de especies.", "green"], ["Parálogos", "Genes homólogos cuya divergencia fue generada por duplicación. Su árbol puede reflejar historia de duplicaciones más que historia de especies.", "amber"], ["Xenólogos", "Genes cuya relación está marcada por transferencia horizontal; importante en algunos sistemas, especialmente microbios.", "sky"]], "Trampa de examen: similitud de secuencia o función no define ortología. El mecanismo definitorio es la especiación."],
      paralogy: ["One-to-one, one-to-many, in-paralogs y out-paralogs", [["One-to-one orthologs", "Una sola copia en una especie corresponde a una sola copia en otra; son especialmente limpios."], ["One-to-many / many-to-many", "Duplicaciones posteriores a la especiación producen múltiples copias en una o más líneas."], ["In-paralogs", "Duplicados originados después del evento de especiación de referencia."], ["Out-paralogs", "Duplicados originados antes del evento de especiación de referencia."]], "El evento de especiación de referencia importa: una duplicación puede ser ‘in’ u ‘out’ según la comparación."],
      orthogroup: ["Orthogroups: la versión multi-especie", "La ortología es originalmente por pares. En filogenómica comparamos muchas especies, así que usamos orthogroups: conjuntos de genes homólogos que descienden de un único gen en el ancestro común de las especies consideradas.", [["Qué contiene", "Ortólogos e in-paralogs posteriores a los eventos relevantes."], ["Qué excluye", "Out-paralogs generados antes del LCA de las especies estudiadas."], ["Por qué importa", "Organiza miles de genes en conjuntos comparables para alineamiento e inferencia."]], "Frase clave: un orthogroup es un grupo de homología, no un conjunto puro de ortólogos one-to-one."],
      inference: ["Cómo se infiere la ortología en la práctica", "El flujo práctico parte de especies y genes codificantes. Se hacen búsquedas de homología entre especies, se retienen mejores hits recíprocos y luego se agrupan relaciones en orthogroups.", [["All-vs-all search", "Comparar proteínas entre todos los pares de especies con BLAST o DIAMOND."], ["Reciprocal best hits", "Quedarse con pares donde cada gen identifica al otro como su mejor match."], ["Clustering / gene trees", "Agrupar relaciones en orthogroups, por ejemplo con OrthoFinder."], ["Control de calidad", "Mirar cuántos genes de cada especie entran en orthogroups."]]],
      exam: ["Cómo reconocer preguntas de examen", [["‘Orthologous genes are…’", "Responder con especiación: genes homólogos que divergieron tras un evento cladogenético/especiación."], ["‘Orthogroup’", "Conjunto de genes homólogos que desciende de un solo gen ancestral en el LCA de las especies estudiadas."], ["‘Por qué importa el muestreo’", "Pensar en long branch attraction, clados artificiales, pérdida de señal y problemas de tasas/modelo."], ["‘Transcriptoma vs genoma vs mitogenoma’", "Comparar factibilidad, cantidad de marcadores, requisitos de muestra y limitaciones."], ["‘Reciprocal best hit’", "Filtro para identificar matches probables controlando copias faltantes o divergentes."]]],
      checklist: ["Antes de la lección 05, puedo...", ["Explicar por qué el muestreo taxonómico es diseño experimental.", "Describir cómo el muestreo sesgado produce artefactos.", "Comparar transcriptomas, genomas, mitogenomas y UCEs/RADseq.", "Distinguir homología, ortología y paralogía.", "Explicar one-to-one, one-to-many, in-paralogs y out-paralogs.", "Definir orthogroup y por qué es un grupo de homología.", "Describir la lógica de reciprocal best hits y OrthoFinder."]],
    },
    visual: { species: "especies", genes: "genes", speciation: "especiación", duplication: "duplicación", orthologs: "ortólogos", paralogs: "parálogos", search: "búsqueda all-vs-all", reciprocal: "reciprocal best hits", groups: "orthogroups" },
  },
  fa: {
    eyebrow: "درس ۰۴ · استنباط ارتولوژی و نمونه‌برداری تاکسونی",
    title: "پیش از ساختن درخت، دادهٔ فیلوژنومیک را طراحی کنید.",
    subtitle: "این درس دربارهٔ انتخاب گونه‌ها، نوع دادهٔ توالی‌یابی و تشخیص ژن‌های قابل مقایسه برای استنباط درخت گونه‌ها است.",
    tags: ["نمونه‌برداری", "ارتولوژی", "پارالوژی", "ارتوگروه", "توالی‌یابی", "بهترین hit متقابل", "OrthoFinder"],
    coreLabel: "ایدهٔ اصلی",
    core: "درخت فقط به اندازهٔ دادهٔ پشت آن قابل اعتماد است: نمونه‌برداری گسترده artefactها را کاهش می‌دهد و ژن‌های ارتولوگ سیگنال گونه‌زایی را حمل می‌کنند.",
    pathTitle: "ساختار درس",
    path: [["1", "طراحی", "چه گونه‌ها و چه داده‌ای؟"], ["2", "سوگیری", "چگونه taxonهای حذف‌شده درخت را منحرف می‌کنند."], ["3", "توالی‌یابی", "ترنسکریپتوم، ژنوم، میتوژنوم و روش‌های reduced representation."], ["4", "ارتولوژی", "چرا speciation مهم است."], ["5", "ارتوگروه", "واحد چندگونه‌ای برای ژن‌های همولوگ."]],
    emphasisTitle: "نکته‌هایی که استاد تأکید کرد",
    emphasis: [["طراحی آزمایش اول است", "پیش از alignment و inference باید گونه‌ها و نوع داده مشخص شوند.", "sky"], ["نمونه‌برداری مهم است", "نمونه‌برداری ناقص می‌تواند long branch attraction، clade مصنوعی و از دست رفتن سیگنال ایجاد کند.", "red"], ["همولوژی کافی نیست", "برای درخت گونه‌ها ژن‌های ارتولوگ مفیدترند چون واگرایی آن‌ها ناشی از speciation است.", "green"], ["عملکرد تعریف‌کننده نیست", "معیار اصلی ارتولوژی مکانیسم تکاملی است: speciation در برابر duplication.", "amber"], ["ارتوگروه گروه همولوژی است", "ممکن است ortholog و in-paralog داشته باشد و با یک ژن در LCA تعریف می‌شود.", "purple"]],
    sections: {},
    visual: { species: "گونه‌ها", genes: "ژن‌ها", speciation: "گونه‌زایی", duplication: "دوبرابرشدن", orthologs: "ارتولوگ‌ها", paralogs: "پارالوگ‌ها", search: "جستجوی همه در برابر همه", reciprocal: "بهترین hitهای متقابل", groups: "ارتوگروه‌ها" },
  },
};

// Persian page reuses the same conceptual structure while keeping key labels translated.
copy.fa.sections = copy.es.sections;

function Section({ title, children }) {
  return <section className="rounded-[2rem] border border-stone-200 bg-white/90 p-6 shadow-sm md:p-8"><h2 className="mb-5 text-2xl font-black tracking-tight text-stone-950 md:text-3xl">{title}</h2>{children}</section>;
}

function Card({ title, body, tone = "stone" }) {
  return <div className={`rounded-3xl border p-5 ${toneClasses[tone] || toneClasses.stone}`}><h3 className="text-lg font-black">{title}</h3><p className="mt-2 text-sm font-semibold leading-6 opacity-80">{body}</p></div>;
}

function WorkflowDiagram({ c }) {
  const steps = c.sections.workflow[1];
  return <div className="rounded-[2rem] border border-stone-200 bg-white p-4 shadow-inner"><div className="grid gap-3 md:grid-cols-3">{steps.map(([title], i) => <div key={title} className="rounded-2xl border border-stone-200 bg-stone-50 p-4"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-red-700 text-sm font-black text-white">{i + 1}</div><div className="mt-3 text-sm font-black text-stone-950">{title}</div></div>)}</div></div>;
}

function OrthologyDiagram({ t }) {
  return (
    <svg viewBox="0 0 620 360" className="h-full w-full rounded-[2rem] bg-[#fffaf0]">
      <rect x="0" y="0" width="620" height="360" rx="30" fill="#fffaf0" />
      <text x="36" y="40" fontSize="16" fontWeight="800" fill="#991b1b">{t.species} + {t.genes}</text>
      <path d="M110 80 C110 145 110 200 110 285" stroke="#111827" strokeWidth="6" fill="none" strokeLinecap="round" />
      <path d="M110 142 C165 135 185 100 228 78" stroke="#111827" strokeWidth="6" fill="none" strokeLinecap="round" />
      <path d="M110 142 C165 158 188 198 230 228" stroke="#111827" strokeWidth="6" fill="none" strokeLinecap="round" />
      <circle cx="110" cy="142" r="11" fill="#dc2626" />
      <text x="132" y="130" fontSize="13" fontWeight="700" fill="#991b1b">{t.speciation}</text>
      <circle cx="228" cy="78" r="12" fill="#059669" />
      <circle cx="230" cy="228" r="12" fill="#059669" />
      <text x="255" y="82" fontSize="14" fontWeight="800" fill="#065f46">A1</text>
      <text x="255" y="232" fontSize="14" fontWeight="800" fill="#065f46">A2</text>
      <path d="M390 80 C390 130 390 190 390 285" stroke="#111827" strokeWidth="6" fill="none" strokeLinecap="round" />
      <path d="M390 132 C440 104 465 90 515 72" stroke="#111827" strokeWidth="6" fill="none" strokeLinecap="round" />
      <path d="M390 132 C440 153 465 174 515 200" stroke="#111827" strokeWidth="6" fill="none" strokeLinecap="round" />
      <path d="M515 200 C540 210 558 230 578 250" stroke="#111827" strokeWidth="6" fill="none" strokeLinecap="round" />
      <circle cx="390" cy="132" r="11" fill="#d97706" />
      <circle cx="515" cy="200" r="9" fill="#d97706" />
      <text x="412" y="121" fontSize="13" fontWeight="700" fill="#92400e">{t.duplication}</text>
      <circle cx="515" cy="72" r="12" fill="#d97706" />
      <circle cx="578" cy="250" r="12" fill="#d97706" />
      <text x="540" y="76" fontSize="14" fontWeight="800" fill="#92400e">B1</text>
      <text x="550" y="278" fontSize="14" fontWeight="800" fill="#92400e">B2</text>
      <rect x="56" y="304" width="220" height="34" rx="17" fill="#d1fae5" />
      <text x="76" y="326" fontSize="13" fontWeight="800" fill="#065f46">{t.orthologs}: speciation signal</text>
      <rect x="360" y="304" width="210" height="34" rx="17" fill="#fef3c7" />
      <text x="380" y="326" fontSize="13" fontWeight="800" fill="#92400e">{t.paralogs}: duplication signal</text>
    </svg>
  );
}

function InferenceDiagram({ t }) {
  const items = [t.genes, t.search, t.reciprocal, t.groups];
  return <div className="rounded-[2rem] border border-stone-200 bg-stone-950 p-5 text-white"><div className="grid gap-3 md:grid-cols-4">{items.map((item, i) => <div key={item} className="rounded-2xl bg-white/8 p-4"><div className="text-2xl font-black text-red-200">0{i + 1}</div><div className="mt-2 text-sm font-black">{item}</div></div>)}</div></div>;
}

function OrthologyTaxonSamplingLesson({ lang = "es", t, isDone, toggle, lessonNo, titles, shared }) {
  const c = copy[lang] || copy.es;
  const { LessonNavigation, LessonResources, LessonPractical, LessonQuiz } = shared;
  return (
    <main className="mx-auto w-[min(1100px,calc(100%-24px))] pb-16 pt-8">
      <LessonNavigation lang={lang} lessonNo={lessonNo} titles={titles} isDone={isDone} toggle={toggle} />
      <LessonResources lang={lang} lessonNo={lessonNo} />

      <section className="overflow-hidden rounded-[2.5rem] border border-stone-200 bg-[#fffaf0]/92 shadow-xl shadow-stone-900/5">
        <div className="grid gap-0 lg:grid-cols-[1.05fr_0.95fr]">
          <div className="p-7 md:p-10 lg:p-12">
            <div className="mb-5 inline-flex rounded-full border border-red-200 bg-red-50 px-4 py-2 text-xs font-black uppercase tracking-[0.18em] text-red-700">{c.eyebrow}</div>
            <h1 className="max-w-3xl text-4xl font-black leading-[0.96] tracking-tight text-stone-950 md:text-6xl">{c.title}</h1>
            <p className="mt-6 max-w-2xl text-lg leading-8 text-stone-700">{c.subtitle}</p>
            <div className="mt-7 flex flex-wrap gap-2">{c.tags.map((tag) => <span key={tag} className="rounded-full border border-stone-200 bg-white px-4 py-2 text-sm font-bold text-stone-700">{tag}</span>)}</div>
          </div>
          <div className="border-t border-stone-200 bg-white/70 p-5 lg:border-l lg:border-t-0">
            <div className="h-full rounded-[2rem] border border-stone-200 bg-white p-4 shadow-inner">
              <OrthologyDiagram t={c.visual} />
              <div className="mt-4 rounded-3xl bg-stone-950 p-5 text-white"><div className="text-xs font-black uppercase tracking-[0.18em] text-red-200">{c.coreLabel}</div><p className="mt-2 text-lg font-bold leading-7">{c.core}</p></div>
            </div>
          </div>
        </div>
      </section>

      <section className="mt-8 grid gap-4 md:grid-cols-5">{c.path.map(([num, title, body]) => <div key={num} className="rounded-3xl border border-stone-200 bg-white/85 p-5 shadow-sm"><div className="text-2xl font-black text-red-700">{num}</div><h3 className="mt-2 text-lg font-black text-stone-950">{title}</h3><p className="mt-2 text-sm font-semibold leading-6 text-stone-600">{body}</p></div>)}</section>

      <div className="mt-8 space-y-8">
        <Section title={c.sections.big[0]}><div className="grid gap-5 lg:grid-cols-[1.1fr_0.9fr]"><div className="space-y-4 text-lg leading-8 text-stone-700"><p>{c.sections.big[1]}</p><p>{c.sections.big[2]}</p></div><div className="rounded-[2rem] border border-stone-200 bg-stone-50 p-5"><h3 className="text-lg font-black text-stone-950">{c.emphasisTitle}</h3><div className="mt-4 space-y-3">{c.emphasis.map(([title, body, tone]) => <Card key={title} title={title} body={body} tone={tone} />)}</div></div></div></Section>
        <Section title={c.sections.workflow[0]}><WorkflowDiagram c={c} /></Section>
        <Section title={c.sections.sampling[0]}><p className="text-lg leading-8 text-stone-700">{c.sections.sampling[1]}</p><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{c.sections.sampling[2].map(([title, body]) => <Card key={title} title={title} body={body} tone="red" />)}</div><p className="mt-5 rounded-3xl border border-emerald-100 bg-emerald-50 p-5 text-sm font-black leading-6 text-emerald-950">{c.sections.sampling[3]}</p></Section>
        <Section title={c.sections.sequencing[0]}><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{c.sections.sequencing[1].map(([title, body]) => <Card key={title} title={title} body={body} tone="sky" />)}</div><p className="mt-5 rounded-3xl border border-amber-100 bg-amber-50 p-5 text-sm font-black leading-6 text-amber-950">{c.sections.sequencing[2]}</p></Section>
        <Section title={c.sections.homology[0]}><div className="grid gap-6 lg:grid-cols-[0.95fr_1.05fr]"><div><p className="text-lg leading-8 text-stone-700">{c.sections.homology[1]}</p><div className="mt-5 grid gap-4">{c.sections.homology[2].map(([title, body, tone]) => <Card key={title} title={title} body={body} tone={tone} />)}</div></div><div className="rounded-[2rem] border border-stone-200 bg-white p-4 shadow-inner"><OrthologyDiagram t={c.visual} /></div></div><p className="mt-5 rounded-3xl border border-red-100 bg-red-50 p-5 text-sm font-black leading-6 text-red-950">{c.sections.homology[3]}</p></Section>
        <Section title={c.sections.paralogy[0]}><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{c.sections.paralogy[1].map(([title, body]) => <Card key={title} title={title} body={body} tone="amber" />)}</div><p className="mt-5 rounded-3xl border border-violet-100 bg-violet-50 p-5 text-sm font-black leading-6 text-violet-950">{c.sections.paralogy[2]}</p></Section>
        <Section title={c.sections.orthogroup[0]}><p className="text-lg leading-8 text-stone-700">{c.sections.orthogroup[1]}</p><div className="mt-5 grid gap-4 md:grid-cols-3">{c.sections.orthogroup[2].map(([title, body]) => <Card key={title} title={title} body={body} tone="green" />)}</div><p className="mt-5 rounded-3xl border border-stone-200 bg-stone-50 p-5 text-sm font-black leading-6 text-stone-800">{c.sections.orthogroup[3]}</p></Section>
        <Section title={c.sections.inference[0]}><div className="grid gap-6 lg:grid-cols-[1fr_1fr]"><div><p className="text-lg leading-8 text-stone-700">{c.sections.inference[1]}</p><div className="mt-5 grid gap-4">{c.sections.inference[2].map(([title, body]) => <Card key={title} title={title} body={body} />)}</div></div><InferenceDiagram t={c.visual} /></div></Section>
        <Section title={c.sections.exam[0]}><div className="overflow-hidden rounded-[2rem] border border-stone-200">{c.sections.exam[1].map(([cue, meaning]) => <div key={cue} className="grid gap-2 border-b border-stone-200 bg-white px-5 py-4 last:border-b-0 md:grid-cols-[0.8fr_1.2fr]"><div className="text-sm font-black text-stone-950">{cue}</div><div className="text-sm font-semibold leading-6 text-stone-600">{meaning}</div></div>)}</div></Section>
        <Section title={c.sections.checklist[0]}><div className="grid gap-3 md:grid-cols-2">{c.sections.checklist[1].map((item) => <label key={item} className="flex items-start gap-3 rounded-2xl border border-stone-200 bg-stone-50 p-4 text-sm font-bold text-stone-700"><input type="checkbox" className="mt-1 h-4 w-4 accent-red-700" /><span>{item}</span></label>)}</div></Section>
      </div>

      <LessonPractical lang={lang} lessonNo={lessonNo} />
      <LessonQuiz lang={lang} lessonNo={lessonNo} />
      <LessonNavigation lang={lang} lessonNo={lessonNo} titles={titles} isDone={isDone} toggle={toggle} placement="bottom" />
    </main>
  );
}

const enQuiz = [
  { kind: "theory", question: "Why is taxon sampling part of experimental design?", options: ["Because missing or biased taxa can change inferred relationships", "Because it only changes colours in the final plot", "Because all sampling schemes produce the same topology", "Because model selection is unnecessary when sampling is broad"], answer: 0, explanation: "Sampling affects topology, branch lengths and artefacts such as long branch attraction.", optionExplanations: ["Correct. Which species are included can determine whether the data contain enough intermediate and representative taxa.", "Sampling affects the actual analysis, not only visualization.", "Different sampling can change the inferred topology or apparent monophyly.", "Broad sampling helps, but models and support still matter."] },
  { kind: "theory", question: "Long branch attraction is most directly promoted by:", options: ["Missing intermediate taxa that would break long branches", "Too many well sampled intermediate taxa", "Using an outgroup", "Having only short branches"], answer: 0, explanation: "Long branches may cluster erroneously when intermediate diversity is absent.", optionExplanations: ["Correct. Intermediate taxa can break up long branches and reduce artefactual attraction.", "Intermediate taxa usually mitigate, not promote, the problem.", "An outgroup helps root the tree when chosen appropriately.", "Short branches are less associated with this artefact."] },
  { kind: "theory", question: "Orthologous genes are genes whose divergence is due to:", options: ["Speciation", "Gene duplication", "Horizontal transfer", "Identical function"], answer: 0, explanation: "Orthology is defined by speciation, not by function or raw similarity.", optionExplanations: ["Correct. Orthologs diverge after a cladogenetic/speciation event.", "Duplication creates paralogs, not orthologs.", "Horizontal transfer creates xenology-like relationships in this framing.", "Function may be conserved, but it is not the definition."] },
  { kind: "theory", question: "Paralogous genes are generated by:", options: ["Gene duplication", "Speciation only", "Tip rotation", "Taxonomic naming"], answer: 0, explanation: "Paralogy is homology produced by duplication events.", optionExplanations: ["Correct. A duplication produces multiple gene copies whose history may not match the species tree.", "Speciation produces orthologous copies across species.", "Rotating a node changes the drawing, not gene history.", "Taxonomy names units; it does not generate genes."] },
  { kind: "theory", question: "Which statement best describes an orthogroup?", options: ["A set of homologous genes descending from one gene in the LCA of the studied species", "Only one-to-one orthologs and nothing else", "A group of species with similar morphology", "A set of genes sharing exactly the same function"], answer: 0, explanation: "An orthogroup is a multi-species homology group defined by a reference speciation event.", optionExplanations: ["Correct. It can include orthologs and in-paralogs derived after the reference speciation events.", "Orthogroups may include in-paralogs; they are not restricted to one-to-one cases.", "That describes a taxonomic or phenotypic grouping, not an orthogroup.", "Function is not the criterion for orthogroup membership."] },
  { kind: "theory", question: "Which pair best matches the data type and a major limitation?", options: ["Mitogenomes — few markers and maternal inheritance", "Transcriptomes — no need for fresh or preserved RNA", "Chromosome-level genomes — always the cheapest option", "PCR markers — no prior sequence knowledge needed"], answer: 0, explanation: "Mitochondrial genomes are useful but provide a narrow, maternally inherited signal.", optionExplanations: ["Correct. Mitogenomes are easy and cheap but represent only part of the evolutionary story.", "Transcriptomes depend on expression and RNA quality; fresh or well preserved tissue matters.", "Chromosome-level genomes are information-rich but expensive.", "PCR requires primer design, which needs prior knowledge."] },
  { kind: "theory", question: "A one-to-one ortholog is:", options: ["A single-copy gene in one species corresponding to a single-copy gene in another", "A duplicated gene family inside one species", "A gene transferred horizontally", "Any gene with the same function"], answer: 0, explanation: "One-to-one orthologs are especially clean markers because there is one corresponding copy per species.", optionExplanations: ["Correct. One copy in each compared species reduces paralogy complications.", "That describes paralogy within a species.", "Horizontal transfer is a different evolutionary process.", "Same function does not define one-to-one orthology."] },
  { kind: "theory", question: "In-paralogs are gene duplicates that arose:", options: ["After the reference speciation event", "Before the reference speciation event", "Only by horizontal transfer", "Only in mitochondrial genomes"], answer: 0, explanation: "In-paralogs are duplications younger than the reference speciation event.", optionExplanations: ["Correct. They may be included in the same orthogroup.", "Duplications older than the reference speciation event are out-paralogs.", "Horizontal transfer is not the definition of in-paralogy.", "In-paralogy is a general gene-tree concept, not mitochondrial-specific."] },
  { kind: "theory", question: "Why are orthologs preferred for reconstructing species trees?", options: ["Their gene history is expected to track speciation", "They always evolve under positive selection", "They are always mitochondrial", "They never require alignment"], answer: 0, explanation: "Species trees aim to recover speciation history, so genes split by speciation carry the relevant signal.", optionExplanations: ["Correct. Orthologs are preferred because their divergence reflects species divergence.", "Selection is not the reason; it can even mislead in some settings.", "Orthologs can be nuclear, mitochondrial, protein-coding, etc.", "Orthologous sequences still need alignment before many analyses."] },
  { kind: "theory", question: "What is the main reason to keep an appropriate outgroup in taxon sampling?", options: ["To help orient or root the tree", "To force the ingroup to become polyphyletic", "To remove the need for orthology inference", "To make branch lengths meaningless"], answer: 0, explanation: "Outgroups provide direction and context for interpreting the ingroup.", optionExplanations: ["Correct. Outgroups help identify the root/direction of evolution relative to the focal clade.", "A good outgroup should not force artefactual polyphyly.", "Orthology inference is still needed for gene comparisons.", "Branch length interpretation depends on tree type and model, not simply on outgroup use."] },
  { kind: "practical", question: "In the orthology practical, the starting point for orthogroup inference is best described as:", options: ["Species with sets of protein-coding genes/proteins", "A finished species tree with support values", "A chronogram with fossil calibrations", "Only morphological characters"], answer: 0, explanation: "Orthology workflows generally start from gene/protein sets for each species, then search and cluster homologs.", optionExplanations: ["Correct. The practical logic starts with species and their genes/proteins.", "The species tree is a downstream goal, not the starting input for orthology inference.", "Dating comes later and needs different inputs.", "This practical is about molecular gene sets, not morphology."] },
  { kind: "practical", question: "What is the purpose of an all-vs-all homology search in the practical workflow?", options: ["To compare genes across species and find candidate homologs", "To trim poorly aligned columns", "To estimate posterior probabilities", "To choose fossil calibrations"], answer: 0, explanation: "All-vs-all searches create the similarity graph from which likely homologous relationships can be inferred.", optionExplanations: ["Correct. Tools such as BLAST/DIAMOND are used to compare gene or protein sequences across species.", "Trimming is an alignment-cleaning step from a later lesson.", "Posterior probabilities belong to Bayesian inference, not initial homology search.", "Fossil calibration is part of divergence dating, not orthology inference."] },
  { kind: "practical", question: "Why does the practical care about reciprocal best hits?", options: ["They reduce false matches by requiring two genes to identify each other as best matches", "They guarantee every gene is included in an orthogroup", "They replace the need for sequence comparison", "They are the same thing as branch support"], answer: 0, explanation: "Reciprocity is a conservative filter for likely homologous/orthologous relationships across species.", optionExplanations: ["Correct. If gene X best matches gene Y and gene Y best matches gene X, the relationship is more credible.", "Many genes may be excluded due to missing data, loss or high divergence.", "Reciprocal hits are based on sequence comparisons; they do not replace them.", "Branch support evaluates inferred trees, not initial gene matching."] },
  { kind: "practical", question: "A useful quality check after running an orthogroup workflow is:", options: ["How many genes from each species were assigned to orthogroups", "Whether the final tree is drawn in red", "Whether every branch has the same length", "Whether all genes have identical function"], answer: 0, explanation: "The professor mentioned that the proportion of genes assigned to orthogroups is a useful diagnostic of the inference.", optionExplanations: ["Correct. Very low assignment may indicate poor annotation, missing genes or problematic data.", "Plot colour is irrelevant to orthogroup quality.", "Equal branch lengths are not an orthology quality criterion.", "Function is not the defining criterion for orthogroup membership."] },
  { kind: "practical", question: "If a true best-hit gene is missing because it was not sequenced or was lost, what can happen in a best-hit workflow?", options: ["A more distant homolog may appear as the best available hit", "The analysis automatically becomes impossible", "The gene becomes a mitochondrial genome", "The tree is automatically rooted"], answer: 0, explanation: "Missing data can make the second-best or more distant homolog look like the best match, which is why reciprocal filtering and downstream clustering matter.", optionExplanations: ["Correct. Missing, lost or highly divergent genes can distort apparent best hits.", "The analysis can still proceed, but uncertainty and filtering become important.", "Gene absence does not change nuclear genes into mitochondrial genomes.", "Best-hit searches do not root phylogenetic trees."] },
];

function translateQuizEs(q) {
  const map = {
    "Why is taxon sampling part of experimental design?": "¿Por qué el muestreo taxonómico forma parte del diseño experimental?",
    "Long branch attraction is most directly promoted by:": "La long branch attraction se favorece directamente por:",
    "Orthologous genes are genes whose divergence is due to:": "Los genes ortólogos son genes cuya divergencia se debe a:",
    "Paralogous genes are generated by:": "Los genes parálogos se generan por:",
    "Which statement best describes an orthogroup?": "¿Qué frase describe mejor un orthogroup?",
    "Which pair best matches the data type and a major limitation?": "¿Qué par relaciona mejor el tipo de dato y una limitación importante?",
    "A one-to-one ortholog is:": "Un ortólogo one-to-one es:",
    "In-paralogs are gene duplicates that arose:": "Los in-paralogs son duplicados génicos que surgieron:",
    "Why are orthologs preferred for reconstructing species trees?": "¿Por qué se prefieren ortólogos para reconstruir árboles de especies?",
    "What is the main reason to keep an appropriate outgroup in taxon sampling?": "¿Cuál es la razón principal para mantener un outgroup adecuado en el muestreo?",
    "In the orthology practical, the starting point for orthogroup inference is best described as:": "En la práctica de ortología, el punto de partida para inferir orthogroups se describe mejor como:",
    "What is the purpose of an all-vs-all homology search in the practical workflow?": "¿Cuál es el propósito de una búsqueda all-vs-all de homología en el flujo práctico?",
    "Why does the practical care about reciprocal best hits?": "¿Por qué la práctica presta atención a los reciprocal best hits?",
    "A useful quality check after running an orthogroup workflow is:": "Un control de calidad útil después de inferir orthogroups es:",
    "If a true best-hit gene is missing because it was not sequenced or was lost, what can happen in a best-hit workflow?": "Si falta el verdadero best hit porque no fue secuenciado o se perdió, ¿qué puede pasar?",
  };
  return q.map(item => ({ ...item, question: map[item.question] || item.question }));
}

export const lesson04Quiz = { en: enQuiz, es: translateQuizEs(enQuiz), fa: enQuiz };

export default OrthologyTaxonSamplingLesson;
