export const lessonContent = {
  id: "amla-2026-05-07-training-diagnostics",
  extractionStatus: "source-based complete draft",
  objectives: [
    "Distinguish regression MLPs from classification MLPs by output-layer shape, activation and loss.",
    "Explain how gradient descent and backpropagation cooperate during neural-network training.",
    "Use batch, epoch, mini-batch and learning rate correctly when reading a training loop.",
    "Recognize tensor ranks for vector, sequence, image and video data.",
    "Differentiate element-wise operations, broadcasting, dot products and reshaping.",
    "Interpret a dense layer as a chain of tensor operations and a neural network as a geometric transformation.",
    "Explain why optimizers and automatic differentiation matter without treating them as magic.",
  ],
  coreConcepts: [
    {
      title: "Regression MLP",
      body: "For regression, the output layer predicts continuous values. One output neuron is enough for univariate regression; multiple output neurons are used for multivariate regression.",
      keywords: ["continuous target", "output neurons", "MSE"],
    },
    {
      title: "Classification MLP",
      body: "For classification, the output layer encodes class probabilities or class-specific decisions. Binary, multiclass and multilabel settings require different output logic.",
      keywords: ["softmax", "sigmoid", "cross-entropy"],
    },
    {
      title: "Backpropagation",
      body: "Backpropagation efficiently computes gradients for every weight and bias by propagating error information backward through the network.",
      keywords: ["gradients", "reverse pass", "autodiff"],
    },
    {
      title: "Gradient descent",
      body: "Gradient descent uses computed gradients to update trainable parameters in the direction that should reduce the loss.",
      keywords: ["optimizer", "loss", "learning rate"],
    },
    {
      title: "Mini-batch training",
      body: "Training usually processes a mini-batch at a time. A full pass through the training set is an epoch; several epochs are needed for iterative improvement.",
      keywords: ["batch", "epoch", "SGD"],
    },
    {
      title: "Tensor rank",
      body: "The number of tensor axes matters: vector data often uses 2D tensors, sequence data 3D, image data 4D and video data 5D.",
      keywords: ["rank", "shape", "axis"],
    },
    {
      title: "Broadcasting",
      body: "Broadcasting lets operations combine tensors with compatible but different shapes, such as adding a bias vector to a batch matrix.",
      keywords: ["shape compatibility", "bias", "NumPy"],
    },
    {
      title: "Dot product",
      body: "Dot products combine entries across dimensions; they are not the same as element-wise multiplication. Dense layers rely heavily on dot products.",
      keywords: ["matrix multiply", "dense layer", "kernel"],
    },
  ],
  walkthroughSections: [
    {
      range: "Slides 1-8",
      title: "MLPs can solve regression and classification, but the output layer changes",
      intro: "Start by reading these slides as architecture choices. The point is not just that MLPs are flexible; the point is that the final layer must match the task.",
      slides: [
        {
          label: "Slide 1",
          deckLabel: "Lecture 3",
          page: 1,
          image: "amla-slides/lecture3/slide-01.png",
          title: "Lecture frame",
          comment: "This lecture continues neural-network foundations after the first Keras/MNIST exposure. It mixes conceptual slides with comments about hands-on notebooks.",
          professor: "Before the technical material, the professor discussed the written test: future tests may be less forgiving and students should not rush submission without checking.",
          remember: "Exam behavior matters too: read carefully, use the time, and expect slightly more reasoning-oriented questions later.",
        },
        {
          label: "Slides 2-3",
          deckLabel: "Lecture 3",
          page: 3,
          image: "amla-slides/lecture3/slide-03.png",
          title: "What can MLPs do?",
          comment: "The slide asks what MLPs can do and immediately warns that there is no universal working recipe for every applied-ML case.",
          professor: "The transcript reinforces this advanced-course posture: notebooks are study material, but you must explain why the model and outputs make sense.",
          remember: "Do not memorize one recipe. Learn how architecture, loss and target type fit together.",
        },
        {
          label: "Slides 4-6",
          deckLabel: "Lecture 3",
          page: 5,
          image: "amla-slides/lecture3/slide-05.png",
          title: "Regression MLP",
          comment: "For regression, decide how many numeric outputs you need. A house-price predictor is one output; predicting multiple continuous values needs several outputs.",
          professor: "This is a direct continuation of Basic ML: identify the target before choosing the model head.",
          remember: "Regression output neurons represent continuous quantities, not class probabilities.",
          trap: "Do not put a softmax head on a plain continuous regression target.",
        },
        {
          label: "Slides 7-8",
          deckLabel: "Lecture 3",
          page: 7,
          image: "amla-slides/lecture3/slide-07.png",
          title: "Classification MLP",
          comment: "Classification MLPs use output neurons to encode class decisions. Binary, multiclass and multilabel problems do not all use the same final activation/loss.",
          professor: "In the hands-on part, the instructor contrasted binary one-vs-rest MNIST with multiclass digit classification.",
          remember: "First decide: binary, multiclass single-label, or multilabel. Then choose output units, activation and loss.",
          trap: "Multiclass softmax is not the same thing as independent multilabel sigmoid outputs.",
        },
      ],
      lab: {
        title: "Mini-lab: classify the model head before coding",
        todo: "The L05 transcript mentions the shared notebook 'MNIST 2 Part A', but no standalone Colab/Drive URL was visible in the extracted sources.",
        objective: "Given a target description, choose the output layer and loss before writing Keras code.",
        steps: [
          "Write three toy targets: house price, digit 0-9, and multiple disease labels.",
          "For each one, decide output units, activation and likely loss.",
          "Compare your choices with the architecture slides before touching code.",
        ],
        parameters: ["number of output units", "final activation", "loss function"],
        outputs: ["target shape", "prediction shape", "whether predictions are continuous values or probabilities"],
        explain: [
          "Why regression and classification differ at the model head.",
          "Why multiclass and multilabel classification are not interchangeable.",
        ],
      },
    },
    {
      range: "Slides 10, 15-21",
      title: "Training an MLP means combining backpropagation with gradient descent",
      intro: "This is the central theory block. Read it slowly: backpropagation computes gradients; gradient descent uses those gradients to update parameters.",
      slides: [
        {
          label: "Slide 10",
          deckLabel: "Lecture 3",
          page: 10,
          image: "amla-slides/lecture3/slide-10.png",
          title: "Training question",
          comment: "The lecture restarts from the practical question: how do you compute the weights of a neural network?",
          professor: "The professor keeps returning to this as the real training question, not an implementation detail.",
          remember: "A neural network is not useful until you can train its weights and biases from data.",
        },
        {
          label: "Slide 15",
          deckLabel: "Lecture 3",
          page: 15,
          image: "amla-slides/lecture3/slide-15.png",
          title: "Backpropagation",
          comment: "Backpropagation solved the practical gradient-computation problem for MLPs. It is efficient reverse-mode automatic differentiation followed by ordinary parameter updates.",
          professor: "The slide explicitly says BP is still used today and is simply gradient descent with an efficient gradient computation technique.",
          remember: "BP is not the optimizer itself. It computes gradients; GD/optimizer uses them.",
          trap: "Saying 'backprop updates the weights' is imprecise. The optimizer updates weights using gradients obtained by backprop.",
        },
        {
          label: "Slides 16-17",
          deckLabel: "Lecture 3",
          page: 16,
          image: "amla-slides/lecture3/slide-16.png",
          title: "GD versus BP",
          comment: "Use the hiker analogy carefully: gradient descent is the decision process for stepping downhill; backpropagation tells you the slope information for every parameter.",
          professor: "The professor asks for the difference in simple terms, because students often collapse GD and BP into one vague word.",
          remember: "GD: move parameters. BP: compute gradients through layers.",
        },
        {
          label: "Slide 18",
          deckLabel: "Lecture 3",
          page: 18,
          image: "amla-slides/lecture3/slide-18.png",
          title: "Forward pass, error, backward pass",
          comment: "The one-sentence algorithm is: predict forward, measure error, propagate error information backward, then update weights.",
          professor: "This is the clearest exam version of the process: prediction, loss, backward gradient calculation, update.",
          remember: "If you cannot narrate one training step, you cannot interpret a training curve.",
        },
        {
          label: "Slide 19",
          deckLabel: "Lecture 3",
          page: 19,
          image: "amla-slides/lecture3/slide-19.png",
          title: "Mini-batches and epochs",
          comment: "Training handles mini-batches one at a time and repeats full passes over the training set. Batch size and number of epochs are training hyperparameters.",
          professor: "The transcript's Keras hands-on also emphasized fit-time details and validation behavior: check what the implementation is actually doing.",
          remember: "Batch is not epoch. One epoch means the model has seen the training set once.",
        },
        {
          label: "Slides 20-21",
          deckLabel: "Lecture 3",
          page: 20,
          image: "amla-slides/lecture3/slide-20.png",
          title: "Activation and initialization matter",
          comment: "Backprop needs differentiable activations, and hidden-layer weights must be randomly initialized so neurons do not remain identical.",
          professor: "The slides connect the historical move from step functions to logistic functions with trainability.",
          remember: "Nonlinear activation plus broken symmetry are prerequisites for useful multilayer learning.",
          trap: "Initializing all hidden weights to zero can make neurons learn the same thing.",
        },
      ],
    },
    {
      range: "Slides 24-33",
      title: "Tensors are the shape language of neural networks",
      intro: "This block is about reading data shapes. The same neural-network code becomes much less mysterious when you can say what each axis means.",
      slides: [
        {
          label: "Slide 24",
          deckLabel: "Lecture 3",
          page: 24,
          image: "amla-slides/lecture3/slide-24.png",
          title: "Data tensors",
          comment: "The lecture shifts from models to data structures. Tensors are arrays with axes; the rank tells you how many axes you have.",
          professor: "The purpose is to match the tools with the actual data structures you will manipulate.",
          remember: "Before modeling, state the tensor shape and the meaning of each axis.",
        },
        {
          label: "Slides 25-27",
          deckLabel: "Lecture 3",
          page: 26,
          image: "amla-slides/lecture3/slide-26.png",
          title: "Vector data",
          comment: "Vector datasets are usually 2D: samples by features. This is the most familiar tabular setting from Basic ML.",
          professor: "The slides make the batch dimension explicit: a batch of vectors becomes a 2D tensor.",
          remember: "For tabular examples, shape is often `(samples, features)`.",
        },
        {
          label: "Slides 28-29",
          deckLabel: "Lecture 3",
          page: 28,
          image: "amla-slides/lecture3/slide-28.png",
          title: "Sequence data",
          comment: "When order or time matters, add a time axis. Sequence data is typically represented as 3D: samples, timesteps and features.",
          professor: "The slide uses time-series as the concrete example, but the same idea applies to ordered biological sequences once encoded.",
          remember: "If time/order matters, do not flatten it away without a reason.",
        },
        {
          label: "Slides 30-31",
          deckLabel: "Lecture 3",
          page: 30,
          image: "amla-slides/lecture3/slide-30.png",
          title: "Image data",
          comment: "Images add height, width and channels, plus samples. TensorFlow commonly uses channels-last: `(samples, height, width, channels)`.",
          professor: "This matters in practice because frameworks can expect different conventions.",
          remember: "MNIST grayscale can have one channel; RGB images have three channels.",
          trap: "Do not confuse image height/width axes with feature columns in a tabular dataset.",
        },
        {
          label: "Slides 32-33",
          deckLabel: "Lecture 3",
          page: 32,
          image: "amla-slides/lecture3/slide-32.png",
          title: "Video data",
          comment: "Video combines sequence and image structure: samples, frames, height, width and channels. That is why it becomes a 5D tensor.",
          professor: "The slide frames video as one of the few common real-world data types where 5D tensors appear naturally.",
          remember: "Video = time axis plus image axes.",
        },
      ],
    },
    {
      range: "Slides 36-46",
      title: "Inside layers: tensor operations, broadcasting and geometry",
      intro: "This is the mechanics block. Dense layers are not mysterious boxes: they are dot products, bias additions, activations and reshaping arranged in a chain.",
      slides: [
        {
          label: "Slide 36",
          deckLabel: "Lecture 3",
          page: 36,
          image: "amla-slides/lecture3/slide-36.png",
          title: "Coding material: HandsOn_Tensors",
          comment: "The deck names a tensor notebook and says the class proceeds on slides. Treat the notebook as the place to test the operations.",
          professor: "The transcript says the instructor preferred walking through cells and then leaving questions for students to solve.",
          remember: "The notebook is for experimentation; the slides are the conceptual map.",
        },
        {
          label: "Slide 38",
          deckLabel: "Lecture 3",
          page: 38,
          image: "amla-slides/lecture3/slide-38.png",
          title: "Dense layer as tensor function",
          comment: "A dense layer can be read as a function that takes a 2D tensor and returns another 2D tensor after a kernel dot product, bias addition and activation.",
          professor: "In the hands-on transcript, the instructor explained that Dense without activation performs linear combinations; the activation can be added separately or specified inside the layer.",
          remember: "Dense = linear transformation plus optional nonlinearity.",
        },
        {
          label: "Slides 39-41",
          deckLabel: "Lecture 3",
          page: 39,
          image: "amla-slides/lecture3/slide-39.png",
          title: "Element-wise operations and broadcasting",
          comment: "Element-wise operations apply independently to entries. Broadcasting generalizes simple operations to compatible shapes, such as adding a vector bias to a matrix batch.",
          professor: "The lecture highlights that naive Python loops are not how real tensor libraries run these operations.",
          remember: "If shapes differ, ask whether broadcasting rules make the operation valid.",
          trap: "Broadcasting is not reshaping by wishful thinking; dimensions still have to be compatible.",
        },
        {
          label: "Slide 42",
          deckLabel: "Lecture 3",
          page: 42,
          image: "amla-slides/lecture3/slide-42.png",
          title: "Dot products",
          comment: "Dot products are the core operation behind many layers. They combine entries across dimensions and are not element-wise multiplication.",
          professor: "The slide explicitly warns not to confuse tensor/dot product with element-wise product.",
          remember: "Use dot/matmul logic for dense connections; use element-wise logic for independent per-entry operations.",
          trap: "In many libraries `*` means element-wise multiplication, not matrix multiplication.",
        },
        {
          label: "Slides 44-46",
          deckLabel: "Lecture 3",
          page: 45,
          image: "amla-slides/lecture3/slide-45.png",
          title: "Geometric interpretation",
          comment: "Tensor operations transform coordinates. A full neural network is a chain of transformations that progressively reshapes the data representation.",
          professor: "This is the conceptual payoff: neural networks can be interpreted as complex geometric transformations in high-dimensional spaces.",
          remember: "A network learns a transformation, not just a table of parameters.",
        },
      ],
      lab: {
        title: "Mini-lab: tensor operations in a notebook",
        todo: "Slide 36 names `..._HandsOn_Tensors.ipynb`, but the extracted sources do not expose a standalone notebook URL.",
        objective: "Reproduce the layer-level operations that appear inside a Dense network.",
        steps: [
          "Create a small 2D array `x` with shape `(batch, features)`.",
          "Create a kernel matrix and compute a dot product.",
          "Add a bias vector and observe broadcasting.",
          "Apply ReLU element-wise.",
          "Reshape or transpose a tensor and write down what each axis means.",
        ],
        parameters: ["batch size", "feature count", "kernel shape", "bias shape"],
        outputs: ["intermediate tensor shapes", "broadcasted result", "post-activation values"],
        explain: [
          "Why dot product and element-wise multiplication differ.",
          "Why adding a bias vector to a batch matrix is valid.",
          "How a Dense layer can be decomposed into tensor operations.",
        ],
      },
    },
    {
      range: "Slides 48-58",
      title: "The training loop: loss, SGD, optimizers and automatic differentiation",
      intro: "Finish by tying the mechanics back to model fitting. Training is repeated forward passes, losses, gradients and parameter updates.",
      slides: [
        {
          label: "Slides 48-50",
          deckLabel: "Lecture 3",
          page: 49,
          image: "amla-slides/lecture3/slide-49.png",
          title: "One training loop",
          comment: "A training step draws a batch, runs predictions, computes loss, computes gradients and updates weights. Keras hides this loop, but the logic still exists.",
          professor: "In the hands-on part, forgetting `.compile()` before `.fit()` produced an error; the instructor used that to show the model needs optimizer/loss information before training.",
          remember: "Compile defines how to train; fit runs the training loop.",
          trap: "A model architecture alone is not a training recipe.",
        },
        {
          label: "Slide 52",
          deckLabel: "Lecture 3",
          page: 52,
          image: "amla-slides/lecture3/slide-52.png",
          title: "Normal equation versus GD",
          comment: "The lecture reminds you why iterative optimization is desirable: neural networks are too complex for a simple closed-form normal equation approach.",
          professor: "This connects back to Basic ML: gradient descent was not introduced just for neural networks, but neural networks make it essential.",
          remember: "For deep models, think iterative optimization, not analytic solution.",
        },
        {
          label: "Slide 53",
          deckLabel: "Lecture 3",
          page: 53,
          image: "amla-slides/lecture3/slide-53.png",
          title: "SGD training loop",
          comment: "Stochastic gradient descent repeats the training loop on mini-batches. The gradient is computed on the batch loss and used to nudge parameters.",
          professor: "The hands-on transcript compared the previous scikit-learn SGD classifier with a neural network on the same MNIST idea.",
          remember: "SGD is not a model; it is an optimization procedure.",
        },
        {
          label: "Slide 56",
          deckLabel: "Lecture 3",
          page: 56,
          image: "amla-slides/lecture3/slide-56.png",
          title: "Optimizers",
          comment: "Optimizers are variants of SGD that modify how steps are chosen, often using past gradients or adaptive scaling.",
          professor: "The slide names SGD with momentum, Adagrad and RMSProp as examples, without requiring a full derivation yet.",
          remember: "When reading code, optimizer choice is part of the training behavior.",
        },
        {
          label: "Slides 57-58",
          deckLabel: "Lecture 3",
          page: 57,
          image: "amla-slides/lecture3/slide-57.png",
          title: "Chaining derivatives and symbolic differentiation",
          comment: "Modern frameworks can symbolically differentiate known chains of tensor operations. This is why you can define a network and let TensorFlow compute gradients.",
          professor: "The slide closes by stressing that researchers usually rely on frameworks for differentiation rather than implementing backprop manually.",
          remember: "Framework convenience does not remove the need to understand the training loop.",
        },
      ],
    },
  ],
  professorEmphasis: [
    "Future written tests may be less forgiving; use the available time to check answers instead of rushing.",
    "The MNIST notebook is a study tool: you should be able to explain the cells, not just run them.",
    "For classification, know whether the problem is binary, multiclass or multilabel before choosing the output layer.",
    "Backpropagation and gradient descent are related but not the same operation.",
    "Dense layers can be understood as tensor operations, not as black boxes.",
    "Always check framework documentation when you rely on defaults such as validation split or layer activation.",
  ],
  commonTraps: [
    "Treating backpropagation as the optimizer instead of the gradient-computation method.",
    "Confusing one epoch with one mini-batch update.",
    "Using softmax for multilabel outputs where independent sigmoid outputs would be needed.",
    "Forgetting that Dense without an activation is only a linear transformation.",
    "Confusing `*` element-wise multiplication with dot product or matrix multiplication.",
    "Flattening sequence or image data without explaining what structural information is lost.",
    "Assuming TensorFlow/Keras defaults are always what your project needs.",
  ],
  quickQuiz: [
    {
      question: "Why does a univariate regression MLP usually need one output neuron?",
      answer: "Because it predicts one continuous target value per sample. Multiple output neurons are needed only when the model predicts several continuous targets at once.",
    },
    {
      question: "What is the clean difference between backpropagation and gradient descent?",
      answer: "Backpropagation computes gradients efficiently through the network; gradient descent or an optimizer uses those gradients to update parameters.",
    },
    {
      question: "What is an epoch?",
      answer: "One complete pass through the training set. It is not the same as one mini-batch update.",
    },
    {
      question: "Why is random initialization important in hidden layers?",
      answer: "It breaks symmetry. If hidden neurons start identically, they can receive identical updates and fail to learn different features.",
    },
    {
      question: "What shape convention does TensorFlow typically use for image data?",
      answer: "Channels-last: `(samples, height, width, channels)`.",
    },
    {
      question: "Why is dot product not the same as element-wise multiplication?",
      answer: "Element-wise multiplication combines matching entries independently; dot product combines entries across a dimension and reduces/changes shape.",
    },
    {
      question: "What does `.compile()` add to a Keras model?",
      answer: "It specifies training information such as optimizer, loss and metrics. Without it, `.fit()` does not know how to train the model.",
    },
    {
      question: "What does it mean to view a neural network geometrically?",
      answer: "The network is a chain of tensor operations that transforms the input data representation into a space where the task becomes easier.",
    },
  ],
  examQuestions: [
    {
      id: "l05-mcq-1",
      question: "A model predicts three independent disease labels for each sample. Which output design is most appropriate?",
      options: [
        "Three sigmoid outputs with a multilabel-compatible loss",
        "One softmax output with three classes",
        "One linear output with mean squared error",
        "Three outputs with no activation because labels are binary",
      ],
      correct: 0,
      explanation: "Independent labels require independent probabilities. Softmax assumes one class competes with the others.",
    },
    {
      id: "l05-mcq-2",
      question: "Which statement best describes backpropagation in MLP training?",
      options: [
        "It chooses the learning rate for each epoch",
        "It computes gradients efficiently by moving error information backward through the network",
        "It randomly initializes the weights before training starts",
        "It converts classification targets into one-hot vectors",
      ],
      correct: 1,
      explanation: "Backpropagation is the efficient gradient-computation step. The optimizer uses those gradients to update parameters.",
    },
    {
      id: "l05-mcq-3",
      question: "In TensorFlow channels-last convention, what does a batch of 64 RGB images of size 128 x 128 look like?",
      options: [
        "(64, 3, 128, 128)",
        "(128, 128, 3, 64)",
        "(64, 128, 128, 3)",
        "(3, 64, 128, 128)",
      ],
      correct: 2,
      explanation: "Channels-last places the color channel after height and width, with samples first.",
    },
    {
      id: "l05-mcq-4",
      question: "A Dense layer is created without an activation. What is the best interpretation?",
      options: [
        "It cannot compute any output",
        "It performs only the linear combination before any nonlinearity",
        "It automatically uses ReLU in TensorFlow",
        "It becomes equivalent to softmax classification",
      ],
      correct: 1,
      explanation: "Dense without activation performs the affine/linear transformation. A nonlinearity must be specified or added separately.",
    },
    {
      id: "l05-mcq-5",
      question: "Why are optimizers such as momentum, Adagrad or RMSProp introduced after SGD?",
      options: [
        "They remove the need for a loss function",
        "They are different model architectures",
        "They change how parameter updates are computed, often using information from previous gradients or adaptive scaling",
        "They replace backpropagation with a closed-form solution",
      ],
      correct: 2,
      explanation: "Optimizers are update rules. They still use gradients but choose steps in more sophisticated ways than plain SGD.",
    },
  ],
  checklistTitle: "L05 final takeaways",
  studyChecklist: [
    "For any MLP task, identify target type before deciding the output layer.",
    "Say clearly: forward pass, loss, backward gradient computation, optimizer update.",
    "Keep batch, mini-batch and epoch separate in your vocabulary.",
    "For every dataset, write its tensor shape and axis meaning.",
    "Explain a Dense layer through dot product, bias addition and activation.",
    "Use the tensor notebook to test broadcasting, dot products and reshaping.",
    "When reviewing Keras code, check compile, fit, optimizer, loss, metrics and validation behavior.",
  ],
};
