export const lessonContent = {
  id: "amla-2026-05-21-vision-mini-project",
  extractionStatus: "source-based complete draft",
  objectives: [
    "Distinguish counting-by-regression, counting-by-detection and counting-by-segmentation.",
    "Explain why localization matters when the project needs interpretable counting results.",
    "Describe the Fluorescent Neuronal Cells dataset, its pixel-wise masks and its annotation limitations.",
    "Identify the main data challenges: imbalance, overcrowding, noisy labels and artifacts.",
    "Use exploratory image analysis to motivate a simple baseline before using deep learning.",
    "Explain thresholding, post-processing and object-level metrics as a baseline workflow.",
    "Connect the baseline to later segmentation models such as U-Net, ResU-Net and c-ResUNet.",
  ],
  coreConcepts: [
    {
      title: "Object counting",
      body: "The task is not only to say what is in an image, but to estimate how many target objects are present.",
      keywords: ["count", "computer vision", "automation"],
    },
    {
      title: "Counting by regression",
      body: "A model maps the whole image directly to a scalar count. It can work, but it gives little localization evidence.",
      keywords: ["scalar output", "density map", "low interpretability"],
    },
    {
      title: "Counting by detection",
      body: "The model localizes objects, often with points or bounding boxes, and the count is obtained from detections.",
      keywords: ["bounding boxes", "object-level", "localization"],
    },
    {
      title: "Counting by segmentation",
      body: "The model predicts a label for each pixel. Counts come from connected objects in the predicted mask.",
      keywords: ["pixel-wise", "mask", "connected components"],
    },
    {
      title: "Pixel-wise annotation",
      body: "Each pixel is labeled as background or cell. This is powerful for segmentation, but expensive and subjective.",
      keywords: ["mask", "supervised learning", "expert labels"],
    },
    {
      title: "Class imbalance",
      body: "Most pixels are background, so a model or metric can look good while missing the rare cell signal.",
      keywords: ["background", "rare positives", "loss choice"],
    },
    {
      title: "Thresholding baseline",
      body: "A non-ML rule marks pixels above an intensity threshold as cell. It is simple, interpretable and useful as a comparison point.",
      keywords: ["baseline", "intensity", "post-processing"],
    },
    {
      title: "Object-level evaluation",
      body: "After predicting a mask, connected components can be matched to true objects to compute precision, recall, F1 and count error.",
      keywords: ["matching", "precision", "recall", "count error"],
    },
  ],
  walkthroughSections: [
    {
      range: "Module 2 / Lecture3 slides 1-15",
      title: "From classification to object counting",
      intro: "The opening frames set up the central question: if a CNN can recognize visual patterns, how do we turn that into a reliable count with enough explanation for a project?",
      slides: [
        {
          label: "Slide 1",
          deckLabel: "Module 2 / Lecture3",
          page: 1,
          image: "amla-slides/module2-lecture3/slide-01.png",
          title: "Object recognition and counting",
          comment: "This is the applied deep dive for the 21 May class. It shifts from general CNN theory into a concrete microscopy case study.",
          professor: "He framed the session as an application of CNN ideas to recognizing objects in images and then counting them.",
          remember: "The project skill here is translating a broad model family into a task-specific workflow.",
        },
        {
          label: "Slide 3",
          deckLabel: "Module 2 / Lecture3",
          page: 3,
          image: "amla-slides/module2-lecture3/slide-03.png",
          title: "Today's goal",
          comment: "The lesson combines object recognition, the Fluocells use case, more advanced CNN architectures, PyTorch/fastai exposure and AML project guidance.",
          professor: "He explicitly said he would highlight what matters for data analysis projects, not only walk through code line by line.",
          remember: "Study this as a project template: problem, data, baseline, model, evaluation and interpretation.",
        },
        {
          label: "Slides 4-6",
          deckLabel: "Module 2 / Lecture3",
          page: 6,
          image: "amla-slides/module2-lecture3/slide-06.png",
          title: "Why counting is harder than it sounds",
          comment: "Counting appears in surveillance, agriculture and biomedical imaging. Manual counting is slow, tiring and error-prone.",
          professor: "He stressed that a useful automated method should reduce human effort and fatigue, and should be faster than manual work.",
          remember: "A count without a justification is often not enough in scientific workflows.",
        },
        {
          label: "Slides 7-12",
          deckLabel: "Module 2 / Lecture3",
          page: 7,
          image: "amla-slides/module2-lecture3/slide-07.png",
          title: "Three families of counting approaches",
          comment: "The deck separates counting-by-regression, counting-by-detection and counting-by-segmentation.",
          professor: "He contrasted the annotation cost and interpretability of the three strategies: direct count is simpler; detection and segmentation are more explanatory but more demanding.",
          remember: "For exam/project reasoning, compare approaches by output type, annotation burden, localization and interpretability.",
        },
        {
          label: "Slide 8",
          deckLabel: "Module 2 / Lecture3",
          page: 8,
          image: "amla-slides/module2-lecture3/slide-08.png",
          title: "Counting by regression",
          comment: "The input is the image and the output is a number. Localization is not explicitly supervised.",
          professor: "He pointed out that even when trained only for counts, internal features may still learn object-like cues.",
          trap: "Do not claim regression cannot learn visual features. The issue is that the final result is hard to interpret.",
        },
        {
          label: "Slide 11",
          deckLabel: "Module 2 / Lecture3",
          page: 11,
          image: "amla-slides/module2-lecture3/slide-11.png",
          title: "Counting by detection",
          comment: "The model localizes objects, commonly with bounding boxes or points, then counts the localized objects.",
          professor: "He emphasized that detection gives a justification: these are the objects the model counted.",
          remember: "Detection trades annotation effort for interpretability.",
        },
        {
          label: "Slide 12",
          deckLabel: "Module 2 / Lecture3",
          page: 12,
          image: "amla-slides/module2-lecture3/slide-12.png",
          title: "Counting by segmentation",
          comment: "Segmentation predicts object/background at pixel level, giving the finest localization of the three strategies.",
          professor: "He explained the cost clearly: instead of a number or boxes, labels must be assigned pixel by pixel.",
          remember: "Segmentation is powerful for cell counting because cell shape and boundaries matter.",
        },
        {
          label: "Slide 15",
          deckLabel: "Module 2 / Lecture3",
          page: 15,
          image: "amla-slides/module2-lecture3/slide-15.png",
          title: "Project takeaway: start with goal and strategy",
          comment: "The first project reminder is simple: state what the project is trying to achieve and how you plan to tackle it.",
          professor: "He used this slide to connect the technical discussion to the AML project report.",
          remember: "A strong project introduction names the task and the modeling strategy before diving into code.",
        },
      ],
    },
    {
      range: "Module 2 / Lecture3 slides 16-27",
      title: "Fluorescence microscopy and the Fluocells dataset",
      intro: "The use case is not generic image classification. It has domain-specific imaging physics, annotation practices and sources of ambiguity.",
      slides: [
        {
          label: "Slides 16-18",
          deckLabel: "Module 2 / Lecture3",
          page: 18,
          image: "amla-slides/module2-lecture3/slide-18.png",
          title: "Why fluorescence microscopy helps",
          comment: "Fluorescence microscopy marks compounds of interest and filters the emitted wavelength so target structures stand out.",
          professor: "He explained that if the fluorophore is attached correctly, the microscope mostly shows the objects of interest.",
          remember: "The image signal is meaningful, but not perfect: brightness, shape and artifacts still vary.",
        },
        {
          label: "Slides 19-20",
          deckLabel: "Module 2 / Lecture3",
          page: 20,
          image: "amla-slides/module2-lecture3/slide-20.png",
          title: "Manual counting is subjective",
          comment: "Marked cells vary in shape, size and color. Borderline cases can be counted differently by different observers or over time.",
          professor: "He highlighted operator effects and subjective borderline cells as a reason automation is useful but also difficult.",
          remember: "Noisy labels are not only a technical nuisance; they come from real biological and annotation ambiguity.",
        },
        {
          label: "Slide 22",
          deckLabel: "Module 2 / Lecture3",
          page: 22,
          image: "amla-slides/module2-lecture3/slide-22.png",
          title: "Toolkit for the case study",
          comment: "The workflow uses the Fluorescent Neuronal Cells dataset, a thresholding baseline and a CNN segmentation model, c-ResUNet.",
          professor: "He said the baseline is important so the gain from machine learning can be judged against something meaningful.",
          remember: "The baseline is part of the scientific argument, not a throwaway preprocessing step.",
        },
        {
          label: "Slides 23-25",
          deckLabel: "Module 2 / Lecture3",
          page: 25,
          image: "amla-slides/module2-lecture3/slide-25.png",
          title: "Images and pixel-wise annotations",
          comment: "The dataset has 283 high-resolution images with masks: 0 for background and 1 for cell.",
          professor: "He clarified that pixel-wise labels require expert effort; many masks were drafted semi-automatically and refined by researchers.",
          remember: "For supervised segmentation, masks are the training target. Their quality bounds what the model can learn.",
        },
        {
          label: "Slide 26",
          deckLabel: "Module 2 / Lecture3",
          page: 26,
          image: "amla-slides/module2-lecture3/slide-26.png",
          title: "Project takeaway: enough context, not encyclopedic background",
          comment: "The report should include background and method context, but only enough for the reader to follow the analysis.",
          professor: "He warned implicitly against being verbose: background should serve the analysis.",
          remember: "Use domain context to justify the modeling choices, not to pad the report.",
        },
        {
          label: "Slide 27",
          deckLabel: "Module 2 / Lecture3",
          page: 27,
          image: "amla-slides/module2-lecture3/slide-27.png",
          title: "Class imbalance signal",
          comment: "Cell pixels are a small fraction of the image. Most pixels are background.",
          professor: "He connected this to later choices such as loss functions and careful result inspection.",
          trap: "Pixel accuracy can be misleading when the positive class is tiny.",
        },
      ],
    },
    {
      range: "Module 2 / Lecture3 slides 28-39",
      title: "Data peculiarities, EDA and the first hands-on notebook",
      intro: "Before training a deep model, the class pauses on data inspection: what cells look like, where labels are noisy, and what a baseline should beat.",
      slides: [
        {
          label: "Slides 28-35",
          deckLabel: "Module 2 / Lecture3",
          page: 35,
          image: "amla-slides/module2-lecture3/slide-35.png",
          title: "Look at real cases before modeling",
          comment: "These visual examples motivate why the model needs to handle variation in size, brightness, shape, clumps and artifacts.",
          professor: "He talked through close cells, hollow-looking cells, filament-like structures and yellow artifacts that can fool simple rules.",
          remember: "EDA should reveal failure modes before they become unexplained errors in the results section.",
        },
        {
          label: "Slides 36-37",
          deckLabel: "Module 2 / Lecture3",
          page: 36,
          image: "amla-slides/module2-lecture3/slide-36.png",
          title: "Four challenge buckets",
          comment: "The deck summarizes the main problems as class imbalance, overcrowding, noisy labels and artifacts.",
          professor: "He said these peculiarities should influence training settings, loss choice and which corner cases you inspect.",
          remember: "A mature project discussion connects data challenges to model design and evaluation.",
        },
        {
          label: "Slide 38",
          deckLabel: "Module 2 / Lecture3",
          page: 38,
          image: "amla-slides/module2-lecture3/slide-38.png",
          title: "Hands-on part I",
          comment: "The first notebook area is exploratory data analysis plus a thresholding baseline.",
          professor: "He said the notebooks are self-contained and that he would highlight takeaways rather than explain every code detail.",
          remember: "The practical work starts with understanding data and establishing a comparison point.",
        },
        {
          label: "Slide 39",
          deckLabel: "Module 2 / Lecture3",
          page: 39,
          image: "amla-slides/module2-lecture3/slide-39.png",
          title: "Project takeaway: always start with data exploration",
          comment: "The slide makes EDA a project requirement: visualize, summarize and start with a simple baseline.",
          professor: "He explicitly said a meaningful baseline tells you what the complex model is actually gaining.",
          remember: "Do not jump from raw data to deep learning without EDA and a baseline.",
        },
      ],
      lab: {
        title: "Mini-lab: EDA for Fluocells",
        objective: "Use the linked notebook resources to inspect images, masks and object-level summaries before modeling.",
        href: "https://drive.google.com/file/d/1bxhhJBMlrnGdzDBPhXsbcjSRl6E_5Ilg/view?usp=drivesdk",
        steps: [
          "Mount or access the course Drive resources as the notebook instructs.",
          "Load a few image/mask pairs and confirm their shapes, data types and value ranges.",
          "Display original image and mask side by side.",
          "Use connected components to count objects in masks.",
          "Build or inspect a table with object area, axes and per-image counts.",
        ],
        parameters: [
          "Image index or sample name.",
          "Mask cleanup thresholds for tiny objects.",
          "Connected-component labeling settings.",
          "Plot scales for count and object-size distributions.",
        ],
        outputs: [
          "Example image and ground-truth mask.",
          "Number of objects per image.",
          "Distribution of object areas and axis lengths.",
          "Examples of empty masks, crowded cells and borderline labels.",
        ],
        explain: [
          "Why EDA changes what model and loss you would choose.",
          "Why missing cell IDs can coexist with valid image rows when an image has zero cells.",
          "Why class imbalance is expected from the images rather than discovered only after training.",
        ],
      },
    },
    {
      range: "Module 2 / Lecture3 slides 40-58",
      title: "Segmentation route: masks, U-Net and c-ResUNet",
      intro: "The class then connects the dataset to the segmentation family used later: semantic masks, U-Net style architectures and c-ResUNet adaptations.",
      slides: [
        {
          label: "Slides 40-44",
          deckLabel: "Module 2 / Lecture3",
          page: 44,
          image: "amla-slides/module2-lecture3/slide-44.png",
          title: "Semantic segmentation as pixel-level classification",
          comment: "The segmentation target is binary: each pixel is background or cell. The model can output a probability heatmap before binarization.",
          professor: "He used mask, annotation, label and ground truth almost interchangeably for the target image.",
          remember: "For this task, segmentation prediction plus post-processing leads to the final count.",
        },
        {
          label: "Slide 46",
          deckLabel: "Module 2 / Lecture3",
          page: 46,
          image: "amla-slides/module2-lecture3/slide-46.png",
          title: "Semantic vs instance segmentation",
          comment: "Instance segmentation is more directly aligned with counting individual cells, because different objects are separated.",
          professor: "The question asks why instance segmentation can be methodologically useful for counting.",
          trap: "Semantic segmentation marks cell pixels, but it does not automatically separate touching cells into different instances.",
        },
        {
          label: "Slides 47-51",
          deckLabel: "Module 2 / Lecture3",
          page: 48,
          image: "amla-slides/module2-lecture3/slide-48.png",
          title: "U-Net structure",
          comment: "U-Net uses a contracting branch for feature extraction and an expanding branch for localization.",
          professor: "He connected the architecture to biomedical segmentation: downsample to learn patterns, upsample to recover a segmentation map.",
          remember: "Contracting path: more channels, smaller spatial maps. Expanding path: larger spatial maps, fewer channels.",
        },
        {
          label: "Slides 52-53",
          deckLabel: "Module 2 / Lecture3",
          page: 53,
          image: "amla-slides/module2-lecture3/slide-53.png",
          title: "ResUNet and residual units",
          comment: "ResUNet adds residual units to a U-Net-like structure to simplify training and mitigate vanishing gradients.",
          professor: "The slide emphasizes identity paths and modified blocks, not a completely unrelated architecture.",
          remember: "Residual connections are a training aid layered on top of the segmentation architecture.",
        },
        {
          label: "Slides 54-58",
          deckLabel: "Module 2 / Lecture3",
          page: 58,
          image: "amla-slides/module2-lecture3/slide-58.png",
          title: "c-ResUNet customizations",
          comment: "The cell-specific version uses a learned colorspace via 1x1 convolution, ELU, residual identity convolution and larger filters in a bottleneck block.",
          professor: "He presented c-ResUNet as specifically designed and tested for fluorescence microscopy cell counting.",
          remember: "Architectural changes should be justified by the image domain and task constraints.",
        },
      ],
    },
    {
      range: "Module 2 / Lecture3 slides 59-69",
      title: "Losses, thresholding baseline and performance assessment",
      intro: "The final third links the practical baseline to later training choices: loss functions, object-level matching, count error and visual inspection.",
      slides: [
        {
          label: "Slides 59-61",
          deckLabel: "Module 2 / Lecture3",
          page: 61,
          image: "amla-slides/module2-lecture3/slide-61.png",
          title: "Training loop and loss choice",
          comment: "Loss measures performance during learning and determines how model parameters are updated.",
          professor: "He stressed that each loss highlights some characteristics and hides others.",
          remember: "Choose loss based on task, data imbalance and analysis objective.",
        },
        {
          label: "Slides 62-65",
          deckLabel: "Module 2 / Lecture3",
          page: 65,
          image: "amla-slides/module2-lecture3/slide-65.png",
          title: "BCE, weighted BCE, focal loss and Dice loss",
          comment: "BCE is natural for binary classification, weighted BCE compensates class imbalance, focal loss focuses hard examples and Dice targets overlap.",
          professor: "He connected class imbalance directly to why plain BCE may be insufficient.",
          trap: "Do not pick a loss because it is popular. Explain what error pattern it emphasizes.",
        },
        {
          label: "Slide 66",
          deckLabel: "Module 2 / Lecture3",
          page: 66,
          image: "amla-slides/module2-lecture3/slide-66.png",
          title: "BCE vs Dice for segmentation",
          comment: "This Slido-style question is exam-like: compare losses by what they reward and what can go wrong in imbalanced segmentation.",
          professor: "The intended reasoning is not a formula recitation; it is about how the loss behaves on this kind of data.",
          remember: "For rare foreground objects, overlap-aware metrics/losses often reveal behavior pixel accuracy hides.",
        },
        {
          label: "Slide 68",
          deckLabel: "Module 2 / Lecture3",
          page: 68,
          image: "amla-slides/module2-lecture3/slide-68.png",
          title: "Hands-on part III",
          comment: "The final practical segment points to Dice-loss training, visual inspection, detection/counting performance and segmentation performance.",
          professor: "In the transcript, he used the baseline notebook to motivate later comparison with ML models.",
          remember: "Report training behavior, count performance, segmentation performance and qualitative errors together.",
        },
        {
          label: "Slide 69",
          deckLabel: "Module 2 / Lecture3",
          page: 69,
          image: "amla-slides/module2-lecture3/slide-69.png",
          title: "Performance assessment and interpretation",
          comment: "The final takeaway is about convergence, overfitting, multiple metrics, comparisons, error analysis and interpretation.",
          professor: "He insisted that a baseline can reveal whether a more complex method is actually worth it.",
          remember: "Advanced project maturity means explaining results, not just reporting a score.",
        },
      ],
      lab: {
        title: "Mini-lab: adaptive thresholding baseline",
        objective: "Create a non-ML baseline that converts image intensity into a mask, post-processes objects and evaluates count/object performance.",
        href: "https://drive.google.com/file/d/1Pv9q32z_IrqMpQryCN3dfugg5w1W14Ob/view?usp=drivesdk",
        steps: [
          "Choose or inspect an adaptive threshold based on each image intensity distribution.",
          "Convert pixels above threshold into predicted cell mask.",
          "Remove tiny objects and separate touching objects when possible.",
          "Match predicted objects to ground-truth objects using a distance rule.",
          "Compute precision, recall, F1 and average absolute count difference.",
          "Compare qualitative mask outputs against the original image and ground truth.",
        ],
        parameters: [
          "Threshold quantile.",
          "Minimum object size for removal.",
          "Watershed or separation settings.",
          "Matching distance threshold.",
          "Train/validation split used to tune threshold and post-processing.",
        ],
        outputs: [
          "Predicted threshold mask.",
          "Connected-component object count.",
          "Precision, recall, F1 and accuracy at object level.",
          "Average absolute count error per image.",
          "Failure examples: merged cells, split cells, yellow artifacts and missed weak cells.",
        ],
        explain: [
          "Why the best threshold on one image may fail on another.",
          "Why recall can be higher than precision when the baseline creates many false positives.",
          "Why a simple baseline is necessary before claiming a deep model improves the workflow.",
        ],
      },
    },
  ],
  professorEmphasis: [
    "Counting is not just classification: you must decide whether the model should output a scalar, objects or pixels.",
    "Interpretability matters because scientific users need to know what was counted.",
    "Annotation burden increases from regression to detection to segmentation.",
    "Masks, labels, annotations and ground truth all refer to the target image in the segmentation notebook context.",
    "The Fluocells data is difficult because of imbalance, crowded cells, noisy labels and artifacts.",
    "Notebooks are self-contained; the class goal was to extract project takeaways, not memorize every code cell.",
    "Always start with EDA and a meaningful baseline.",
    "Performance assessment should include training behavior, several metrics, visual inspection and error analysis.",
  ],
  commonTraps: [
    "Treating a direct count regressor as interpretable just because its numeric error is low.",
    "Forgetting that segmentation masks require much heavier annotation than image-level counts.",
    "Using pixel accuracy as the main success metric on highly imbalanced masks.",
    "Assuming semantic segmentation automatically separates touching cells into instances.",
    "Comparing a deep model only to no baseline or to a meaningless dummy baseline.",
    "Ignoring empty images when interpreting object tables: nCells can be valid while cell-level fields are missing.",
    "Choosing BCE, Dice or focal loss without explaining which data problem the choice addresses.",
  ],
  quickQuiz: [
    {
      question: "What output does counting-by-regression predict?",
      answer: "A scalar count for the whole image, usually without explicit localization of objects.",
    },
    {
      question: "Why is detection more interpretable than direct regression for counting?",
      answer: "Because the predicted objects or boxes show which items were counted.",
    },
    {
      question: "What is the target in semantic segmentation for this cell-counting task?",
      answer: "A pixel-wise binary mask: background pixels are 0 and cell pixels are 1.",
    },
    {
      question: "Why can class imbalance make pixel accuracy misleading?",
      answer: "Because most pixels are background, so a model can score high while missing many cell pixels.",
    },
    {
      question: "What does connected-component labeling add to a mask?",
      answer: "It separates contiguous foreground regions into candidate objects that can be counted or measured.",
    },
    {
      question: "Why is thresholding a useful baseline?",
      answer: "It is simple, interpretable and gives a concrete comparison for more complex models.",
    },
    {
      question: "Why can one adaptive threshold still fail across images?",
      answer: "Image brightness, cell shape, artifacts and local distributions vary, so the same rule may over-detect or under-detect.",
    },
    {
      question: "What is the project-level lesson of slide 69?",
      answer: "Evaluate models through convergence, overfitting, multiple metrics, comparisons, error analysis and interpretation.",
    },
  ],
  examQuestions: [
    {
      id: "l09-q1",
      question: "A model predicts the exact number of cells per image but gives no mask, point or box output. Which critique is most aligned with the lecture?",
      options: [
        "It cannot be a CNN because CNNs always output masks.",
        "It may be useful for count accuracy, but it provides weak justification for what was counted.",
        "It is necessarily worse than thresholding because it uses no post-processing.",
        "It solves detection because the count implies object locations.",
      ],
      correct: 1,
      explanation: "Counting-by-regression can learn useful visual features, but the final scalar does not localize the objects.",
    },
    {
      id: "l09-q2",
      question: "You need to count crowded cells and also explain individual borderline cases. Which approach gives the finest localization but requires the heaviest annotation?",
      options: [
        "Counting by regression with image-level counts.",
        "Counting by detection with only image-level labels.",
        "Counting by segmentation with pixel-wise masks.",
        "Hard voting over three classifiers.",
      ],
      correct: 2,
      explanation: "Pixel-wise segmentation provides detailed contours, but it requires pixel-level labels.",
    },
    {
      id: "l09-q3",
      question: "A segmentation model reports very high pixel accuracy on Fluocells but misses many cells. What is the most likely reason this metric is misleading?",
      options: [
        "Cells are the majority class, so accuracy penalizes them too much.",
        "Most pixels are background, so predicting background can dominate the score.",
        "Pixel accuracy cannot be computed for binary masks.",
        "The model must be using instance segmentation instead of semantic segmentation.",
      ],
      correct: 1,
      explanation: "The dataset is highly imbalanced; background pixels dominate the image.",
    },
    {
      id: "l09-q4",
      question: "A thresholding baseline detects many yellow artifacts as cells. Precision is low but recall is relatively high. Which interpretation fits?",
      options: [
        "The baseline finds many true cells but also creates many false positives.",
        "The baseline misses almost every true cell and creates no false positives.",
        "The baseline is overfitting because it has too many learned parameters.",
        "The baseline has solved instance segmentation.",
      ],
      correct: 0,
      explanation: "Lower precision with higher recall means many predicted positives are wrong, even if many true cells are found.",
    },
    {
      id: "l09-q5",
      question: "Why did the professor insist on EDA and a non-ML baseline before c-ResUNet?",
      options: [
        "Because deep learning models cannot be used for microscopy.",
        "Because the baseline replaces the need for train/validation splits.",
        "Because it reveals data challenges and creates a meaningful comparison for complex models.",
        "Because thresholding always outperforms CNNs on imbalanced data.",
      ],
      correct: 2,
      explanation: "EDA and baseline results help justify whether a more complex model improves the workflow.",
    },
    {
      id: "l09-q6",
      question: "Which statement best separates semantic from instance segmentation for this counting task?",
      options: [
        "Semantic segmentation predicts one scalar count; instance segmentation predicts a probability distribution.",
        "Semantic segmentation marks all cell pixels as the same class; instance segmentation distinguishes individual objects.",
        "Semantic segmentation needs no annotations; instance segmentation needs image-level counts only.",
        "Semantic segmentation is a regression method; instance segmentation is an ensemble method.",
      ],
      correct: 1,
      explanation: "Semantic masks tell cell vs background; instance masks preserve object identity.",
    },
  ],
  checklistTitle: "What to remember after this lesson",
  studyChecklist: [
    "Given a counting problem, choose regression, detection or segmentation and justify the trade-off.",
    "Explain why localization is a form of interpretability in object counting.",
    "Describe the Fluocells dataset as images plus pixel-wise masks with noisy, subjective boundaries.",
    "List the four main data difficulties: imbalance, overcrowding, noisy labels and artifacts.",
    "Use EDA outputs to motivate model choice, loss choice and error analysis.",
    "Explain adaptive thresholding and why post-processing is needed.",
    "Compare BCE, weighted BCE, focal loss and Dice loss at the level of intuition.",
    "Report both quantitative metrics and visual failure cases in the project.",
  ],
};
