export const lessonContent = {
  id: "amla-2026-04-16-intro-advanced",
  extractionStatus: "source-based complete draft",
  objectives: [
    "Explain what changes when moving from AML Basic to AML Advanced: less hand-holding, more neural networks, deeper code and more autonomous experimentation.",
    "Summarize the exam/project logistics that affect how to study: multiple-choice written test, project/report work and advanced-level interpretation.",
    "Connect biological neural networks, artificial neurons, perceptrons, MLPs, FFNNs and DNNs without treating the biological analogy too literally.",
    "Explain why a single perceptron is a linear classifier and why stacking layers plus nonlinear activations increases representational power.",
    "Use the TensorFlow Playground demo to reason about activation functions, decision boundaries, convergence, capacity and overfitting.",
    "Recognize why domain knowledge can sometimes solve a problem more efficiently than simply making a network larger.",
  ],
  coreConcepts: [
    {
      title: "Advanced course mindset",
      body: "AMLA assumes Basic material is already usable: Python, NumPy, pandas, plotting, scikit-learn, train/validation/test logic and metric interpretation. The new value is neural-network reasoning and more mature model interpretation.",
      keywords: ["Basic as prerequisite", "less guidance", "interpretation"],
    },
    {
      title: "Artificial neuron",
      body: "A neuron receives numeric inputs, combines them through weights and bias, applies an activation function and passes an output forward. The biology is inspiration, not an exact model.",
      keywords: ["weights", "bias", "activation"],
    },
    {
      title: "Perceptron / TLU",
      body: "A threshold logic unit computes a weighted sum and applies a step-like decision. A single TLU creates a linear decision boundary, similar in spirit to logistic regression or a linear SVM.",
      keywords: ["linear boundary", "step function", "TLU"],
    },
    {
      title: "Bias term",
      body: "The bias shifts the activation threshold, just like the intercept in y = ax + b. Without it, the model may be forced through the wrong origin or threshold.",
      keywords: ["intercept", "threshold shift", "x0 = 1"],
    },
    {
      title: "MLP / FFNN / DNN",
      body: "A multilayer perceptron stacks dense layers. If information flows only forward it is a feed-forward neural network; if the stack is deep, it becomes a deep neural network.",
      keywords: ["dense", "hidden layers", "feed-forward"],
    },
    {
      title: "Capacity vs domain knowledge",
      body: "More layers and neurons increase expressivity, but a smart feature transformation can sometimes solve a nonlinear task with a simpler model.",
      keywords: ["capacity", "feature engineering", "x1 squared"],
    },
  ],
  walkthroughSections: [
    {
      range: "Lecture 0 slides 4-16",
      title: "Start with the course logistics before touching models",
      intro: "The first part of the material is not model theory. It tells you how to study Advanced: where the source material lives, how slides/notebooks are updated, and what kind of autonomy the course expects.",
      slides: [
        {
          label: "Slides 4-8",
          deck: "extraSlides",
          deckLabel: "Lecture 0",
          page: 5,
          image: "/amla-slides/lecture0/slide-05.jpg",
          title: "Virtuale / Drive are the source of truth",
          comment: "Read these slides as the map of the course material: slides, notebooks, project information and later updates. The study guide should sit on top of those sources, not replace them.",
          professor: "He warned that slides can be updated after class, especially when preliminary TMP files are used.",
          remember: "When reviewing, open the current PDF first and use this page to decide what deserves attention.",
        },
        {
          label: "Slides 9-16",
          deck: "extraSlides",
          deckLabel: "Lecture 0",
          page: 16,
          image: "/amla-slides/lecture0/slide-16.jpg",
          title: "Advanced means less guided repetition",
          comment: "The course continues from AML Basic but changes the rhythm. You are expected to recognize familiar ML vocabulary and spend more time exploring notebooks independently.",
          professor: "He framed Advanced as a place where hands-on work becomes less step-by-step and more home exploration.",
          remember: "If a Basic concept blocks you, pause and review it; AMLA will use it rather than re-teach it slowly.",
        },
      ],
    },
    {
      range: "Lecture 0 slides 21-27",
      title: "Exam and project expectations shape how you study",
      intro: "These slides matter because they define the products you are studying for: multiple-choice reasoning and a project/report where model interpretation counts.",
      slides: [
        {
          label: "Slides 21-23",
          deck: "extraSlides",
          deckLabel: "Lecture 0",
          page: 21,
          image: "/amla-slides/lecture0/slide-21.jpg",
          title: "Different student categories, different assessment paths",
          comment: "Bioinformatics LM students have written test plus project/report work; PhD paths can differ. The practical point is that studying only for code execution is not enough.",
          professor: "He repeatedly separated administrative exam rules from the technical project expectations.",
          remember: "Prepare explanations for choices, outputs and limitations. That is the advanced-level part.",
        },
        {
          label: "Slides 24-27",
          deck: "extraSlides",
          deckLabel: "Lecture 0",
          page: 25,
          image: "/amla-slides/lecture0/slide-25.jpg",
          title: "Multiple-choice does not mean memorization only",
          comment: "Because material consultation can be allowed in controlled ways, the stronger questions are likely to test reasoning and confusion between close concepts.",
          professor: "He suggested that simple definition lookup is not the useful target; interpretation matters more.",
          remember: "Study by asking: what would change if I modify the model, data split, activation, metric or project objective?",
        },
      ],
    },
    {
      range: "Lecture 1 slides 2-8",
      title: "The Advanced jump: from classical ML to neural-network workflows",
      intro: "The lecture begins by reconnecting with Basic, then immediately positions neural networks as the new tool family.",
      slides: [
        {
          label: "Slides 2-4",
          deck: "slides",
          deckLabel: "Lecture 1",
          page: 3,
          image: "/amla-slides/lecture1/slide-03.jpg",
          title: "Basic remains the baseline",
          comment: "Scikit-learn, train/validation/test logic, metrics and overfitting vocabulary are assumed. Advanced adds deep-learning architecture and implementation decisions.",
          professor: "He made clear that Basic is not discarded; it becomes the benchmark for more advanced models.",
          remember: "In projects, a neural network should be compared against simpler baselines when possible.",
        },
        {
          label: "Slides 5-8",
          deck: "slides",
          deckLabel: "Lecture 1",
          page: 7,
          image: "/amla-slides/lecture1/slide-07.jpg",
          title: "Implementation and theory will alternate",
          comment: "Do not wait for a perfect theoretical derivation before opening a tutorial. The course expects you to learn by running, observing and then explaining.",
          professor: "He presented this as a practical learning strategy, not as permission to skip interpretation.",
          remember: "A notebook result is not a conclusion until you can explain what produced it.",
        },
      ],
    },
    {
      range: "Lecture 1 slides 10-18",
      title: "From biological inspiration to artificial neurons",
      intro: "This block introduces the analogy, then immediately limits it. The exam-safe language is: inspired by neurons, but implemented as mathematical units.",
      slides: [
        {
          label: "Slides 10-13",
          deck: "slides",
          deckLabel: "Lecture 1",
          page: 12,
          image: "/amla-slides/lecture1/slide-12.jpg",
          title: "Biological neural networks are the metaphor",
          comment: "The slides use dendrites, soma, axon and synapse to motivate connected units, but the model is not trying to reproduce brain biology faithfully.",
          professor: "The material explicitly calls the biological analogy oversimplified.",
          remember: "Avoid writing that ANNs are realistic brain models; say they are simplified computational models inspired by neural connectivity.",
        },
        {
          label: "Slides 14-18",
          deck: "slides",
          deckLabel: "Lecture 1",
          page: 17,
          image: "/amla-slides/lecture1/slide-17.jpg",
          title: "Artificial neurons are weighted computations",
          comment: "Inputs are multiplied by weights, shifted by bias and passed through an activation. This is the mental model you need for every later architecture.",
          professor: "He connected the bias term to the intercept intuition: the model needs a way to shift the threshold.",
          remember: "Weights decide direction/importance; bias shifts the activation; activation controls the output shape.",
        },
      ],
    },
    {
      range: "Lecture 1 slides 19-24",
      title: "Perceptron logic and the first limitation",
      intro: "The perceptron block is important because it shows both the power and the weakness of a single linear decision unit.",
      slides: [
        {
          label: "Slides 19-21",
          deck: "slides",
          deckLabel: "Lecture 1",
          page: 21,
          image: "/amla-slides/lecture1/slide-21.jpg",
          title: "Threshold logic unit / perceptron",
          comment: "A perceptron adjusts weights after wrong predictions and can separate classes when a linear boundary is enough.",
          professor: "He emphasized that perceptrons are useful but do not naturally output calibrated class probabilities.",
          remember: "A perceptron is closer to a linear classifier than to a flexible deep model.",
        },
        {
          label: "Slides 22-24",
          deck: "slides",
          deckLabel: "Lecture 1",
          page: 23,
          image: "/amla-slides/lecture1/slide-23.jpg",
          title: "Bias and linear boundaries",
          comment: "The bias term moves the separating line; without nonlinear transformations, the boundary remains linear.",
          professor: "He used the intercept idea to make the bias less abstract.",
          remember: "If the data shape requires a curved or XOR-like boundary, one perceptron is structurally limited.",
          trap: "Do not say the perceptron fails because it is badly trained; sometimes the architecture cannot represent the target boundary.",
        },
      ],
    },
    {
      range: "Lecture 1 slides 25-26 + live playground",
      title: "MLP, activation functions and the live decision-boundary demo",
      intro: "This is where the lecture becomes most study-useful: change the architecture and watch how the learned boundary changes.",
      slides: [
        {
          label: "Slides 25-26",
          deck: "slides",
          deckLabel: "Lecture 1",
          page: 26,
          image: "/amla-slides/lecture1/slide-26.jpg",
          title: "Stack layers to create representational power",
          comment: "A multilayer perceptron combines dense layers. With nonlinear activations, the network can build more complex decision boundaries than a single perceptron.",
          professor: "He contrasted multilayer perceptron, feed-forward neural network and deep neural network terminology.",
          remember: "Depth alone is not enough if activations are linear; nonlinear activation is what makes stacking useful.",
        },
        {
          label: "Live demo",
          deck: "slides",
          deckLabel: "Lecture 1",
          page: 26,
          image: "/amla-slides/lecture1/slide-26.jpg",
          title: "TensorFlow Playground: activation, capacity and feature choice",
          comment: "The demo asks you to compare tanh, ReLU and linear activation; then inspect loss, convergence, decision boundary and stability after restart.",
          professor: "He pointed out that a smarter representation, such as squared inputs for circular separation, can outperform blindly adding neurons.",
          remember: "For project work, always connect metric behavior with visual/diagnostic behavior.",
          trap: "Low loss can hide an odd boundary or over-specialized behavior. Inspect the output, not just the number.",
        },
      ],
      lab: {
        title: "TensorFlow Playground: decision boundaries and capacity",
        href: null,
        todo: "The class used a web playground and discussed Colab/GitHub material later, but no standalone notebook URL for L01 was visible in the extracted sources.",
        objective: "Pause after the MLP/playground slides and reproduce the class reasoning by changing architecture, activation and input features.",
        steps: [
          "Open the playground or an equivalent local reproduction.",
          "Start with a circular or XOR-like dataset using x1 and x2 only.",
          "Train with tanh, ReLU and linear activation.",
          "Repeat with fewer neurons and then with many layers/neurons.",
          "Add transformed features such as x1 squared and x2 squared when available.",
        ],
        parameters: ["Activation", "Hidden layers", "Neurons per layer", "Learning rate", "Batch size", "Input features"],
        outputs: ["Training loss", "Test loss", "Boundary shape", "Restart stability", "Inactive neurons"],
        explain: [
          "Why linear activation fails on nonlinear data without feature transformation.",
          "Why ReLU can create polygon-like boundaries in the demo.",
          "Why domain-informed features can reduce architecture complexity.",
        ],
      },
    },
  ],
  slidePath: [
    {
      range: "Lecture 0 slides 4-16",
      title: "Course organization and material",
      concept: "The course uses English material, Virtuale as the access point, slides plus notebooks, and later GitHub/Colab resources.",
      intuition: "Treat Virtuale/Drive as the source of truth and the guide as a study layer on top of it.",
      professor: "He stressed that Bioinformatics students are expected in presence, while special remote cases are negotiated; recordings are not planned as official student material.",
      remember: "For study planning, check updated PDFs after class and do not rely only on preliminary TMP slides.",
    },
    {
      range: "Lecture 0 slides 21-27",
      title: "Exam and project shape",
      concept: "Bioinformatics LM students do written test plus project; PhD students mainly do project work; written tests are multiple choice on course topics.",
      intuition: "The written exam checks conceptual reasoning; the project checks whether you can run and explain a complete analysis.",
      professor: "He repeated that dates are visible later on Almaesami and that exam rules differ by student category.",
      remember: "For AMLA, prepare both MCQ reasoning and project/report interpretation; do not study only code snippets.",
    },
    {
      range: "Lecture 1 slides 2-8",
      title: "Basic recap and Advanced jump",
      concept: "The first part used mostly scikit-learn; Advanced adds Keras/TensorFlow and assumes Basic competence.",
      intuition: "The course deliberately jumps from classical ML to neural networks, then fills methodology as needed.",
      professor: "He said the hands-on will become less step-by-step in class and more something to explore at home.",
      remember: "If you cannot explain train/validation/test, regularization, bias-variance and metrics, review AMLB before continuing.",
    },
    {
      range: "Lecture 1 slides 10-18",
      title: "From biological to artificial neurons",
      concept: "BNNs motivate artificial neurons, but ANNs are simplified computational units with numeric inputs, weights and outputs.",
      intuition: "Use the biology only to remember the idea of connected units; use the math to explain the model.",
      professor: "The slides explicitly call the biological analogy vastly oversimplified.",
      remember: "In exam answers, avoid saying ANNs reproduce the brain; say they are simplified inspired computational models.",
    },
    {
      range: "Lecture 1 slides 19-24",
      title: "Bias, perceptron training and limitation",
      concept: "A perceptron updates weights after wrong predictions, but each output neuron keeps a linear decision boundary.",
      intuition: "A perceptron can move a line, but it cannot bend that line around XOR-like patterns.",
      professor: "He connected the bias to the intercept and highlighted that perceptrons work nicely but do not output class probabilities.",
      remember: "The limitation is not that perceptrons are useless; it is that one layer is not expressive enough for complex patterns.",
    },
    {
      range: "Lecture 1 slides 25-26 + live playground",
      title: "MLP and nonlinear boundaries",
      concept: "Stacking perceptrons/layers plus nonlinear activations turns simple linear units into more flexible models.",
      intuition: "Depth and width let the model combine many simpler boundaries; activation function changes geometry.",
      professor: "In the playground he asked students to compare tanh, ReLU and linear activations, and to watch loss, boundary shape and convergence.",
      remember: "Do not choose a network only by low loss; inspect stability, overfitting behavior and whether the learned boundary makes sense.",
    },
  ],
  professorEmphasis: [
    "Advanced assumes the Basic part as known; the course will use Python and scikit-learn with less mercy.",
    "Slides can change after each lecture; study from the final material when available.",
    "The written exam questions should be more reasoning-oriented because the exam allows material consultation under controlled conditions.",
    "The project is not only about running code; the advanced part requires stronger explanation, interpretation and use of advanced models.",
    "Linear activation cannot solve a nonlinear separation unless the input representation already encodes the needed nonlinear feature.",
    "Low test loss is not the full story: visual inspection and error analysis can reveal suspicious decision boundaries.",
    "Random initialization matters more when the network has low representational power.",
  ],
  commonTraps: [
    "Confusing the advanced course with a pure theory course; it is applied, but still expects conceptual explanation.",
    "Thinking a larger network is always better; it may overfit or learn unintuitive boundaries.",
    "Calling any neural network a deep network; depth refers to multiple hidden layers.",
    "Forgetting that nonlinear activation is what makes stacked layers more than just a larger linear model.",
    "Interpreting playground neuron plots as literal biological neurons instead of visual summaries of learned transformations.",
    "Assuming batch size always speeds up or improves classification; it changes update variability and convergence behavior.",
    "Using an LLM-generated project interpretation without being able to defend every choice orally.",
  ],
  miniLab: {
    title: "TensorFlow Playground: decision boundaries and capacity",
    href: null,
    todo: "The class used a web playground and discussed Colab/GitHub material later, but no standalone notebook URL for L01 was visible in the extracted sources.",
    objective: "Reproduce the reasoning from the live demo: change architecture and activation, then explain how the decision boundary and losses react.",
    steps: [
      "Open the neural-network playground used in class or an equivalent local reproduction.",
      "Start with a simple circular or XOR-like dataset using x1 and x2 only.",
      "Train with tanh, then ReLU, then linear activation.",
      "Repeat with fewer neurons and then with many layers/neurons.",
      "Add transformed features such as x1 squared and x2 squared when the interface allows it.",
    ],
    parameters: ["Activation function", "Number of hidden layers", "Neurons per layer", "Learning rate", "Batch size", "Input features"],
    outputs: ["Training loss", "Test loss", "Decision boundary shape", "Boundary stability after restart", "Inactive/near-zero neurons"],
    explain: [
      "Why ReLU tends to build polygon-like boundaries in this demo.",
      "Why linear activation fails on nonlinear data without feature transformation.",
      "Why a small network can converge differently after each restart.",
      "Why adding domain-informed squared features can beat blindly increasing capacity.",
    ],
  },
  quickQuiz: [
    {
      question: "What does AMLA assume from AML Basic?",
      answer: "It assumes basic Python/Colab, NumPy/pandas/plotting, scikit-learn, supervised-learning evaluation, bias-variance, regularization and metric interpretation are already usable.",
    },
    {
      question: "Why is a perceptron a linear classifier?",
      answer: "Its output is based on a weighted sum of inputs plus a threshold or activation. The boundary defined by that weighted sum is linear in the input space.",
    },
    {
      question: "What does the bias neuron do?",
      answer: "It provides a constant input, usually x0 = 1, so the model can shift the threshold or activation function, like the intercept term in a linear equation.",
    },
    {
      question: "Why does a linear activation collapse the benefit of stacking layers?",
      answer: "A composition of linear transformations is still linear, so stacking linear layers does not create nonlinear decision boundaries.",
    },
    {
      question: "What should you compare when deciding whether training is good enough?",
      answer: "Look at training and test/validation loss, convergence or plateau behavior, stability and whether the learned boundary/output makes sense for the data.",
    },
    {
      question: "Why can domain knowledge reduce the need for a large network?",
      answer: "If you know the right transformation, such as squared features for circular separation, a simpler model can solve the task because the input representation already exposes the structure.",
    },
  ],
  examQuestions: [
    {
      id: "l01-linear-activation",
      question: "A student stacks four dense layers but uses only linear activations. On a nonlinear XOR-like task, what is the best interpretation?",
      options: [
        "The model is deep, so it can represent any nonlinear boundary.",
        "The stack is still equivalent to a linear transformation, so nonlinear separation remains a problem.",
        "The model will work if the learning rate is small enough, regardless of representation.",
        "The output layer alone guarantees nonlinearity.",
      ],
      correct: 1,
      explanation: "Without nonlinear activations, composing layers does not add nonlinear representational power.",
    },
    {
      id: "l01-low-loss",
      question: "In the playground, a very large network gets low loss but learns a strange boundary around isolated points. What should you conclude?",
      options: [
        "Low loss always proves the model is conceptually correct.",
        "The model may be over-specializing; inspect the boundary, data and error cases before trusting it.",
        "The solution is automatically better because it uses more parameters.",
        "The test loss should be ignored whenever the boundary is visible.",
      ],
      correct: 1,
      explanation: "The lecture emphasized that metrics alone can hide subtle failure modes.",
    },
    {
      id: "l01-bias",
      question: "Why is the bias term important in an artificial neuron?",
      options: [
        "It removes all overfitting.",
        "It shifts the activation threshold and lets the unit represent boundaries not forced through the origin.",
        "It replaces the need for weights.",
        "It makes the neuron biologically exact.",
      ],
      correct: 1,
      explanation: "The professor used the y = ax + b analogy: the bias acts like an intercept.",
    },
    {
      id: "l01-domain-knowledge",
      question: "For circular separation, adding x1^2 and x2^2 lets a simple model converge quickly. What lesson does this illustrate?",
      options: [
        "Feature engineering and domain knowledge can sometimes reduce architecture complexity.",
        "Squared features always remove the need for neural networks.",
        "The model is no longer supervised learning.",
        "Only ReLU can use engineered features.",
      ],
      correct: 0,
      explanation: "A good representation can make a hard nonlinear task easier for a simpler model.",
    },
  ],
  checklistTitle: "What to take from L01",
  studyChecklist: [
    "Review AMLB concepts that AMLA assumes: evaluation, regularization, bias-variance and metrics.",
    "Be able to define perceptron, bias, MLP, FFNN and DNN in one or two precise sentences each.",
    "Explain why nonlinearity matters between layers.",
    "Use playground outputs as evidence: loss curves, boundary shape, restart stability and inactive neurons.",
    "Connect project expectations to interpretation maturity, not only model application.",
  ],
};
