export const lessonContent = {
  id: "amla-2026-04-16-intro-advanced",
  extractionStatus: "source-based complete draft",
  objectives: [
    "Explain what changes when moving from AML Basic to AML Advanced: less hand-holding, more neural networks, deeper code and more autonomous experimentation.",
    "Summarize the exam/project logistics that affect how to study: multiple-choice written test, project/report work and advanced-level interpretation.",
    "Connect biological neural networks, artificial neurons, perceptrons, MLPs, FFNNs and DNNs without treating the biological analogy too literally.",
    "Explain why a single perceptron is a linear classifier and why stacking layers plus nonlinear activations increases representational power.",
    "Use the TensorFlow Playground demo to reason about activation functions, decision boundaries, convergence, capacity and overfitting.",
    "Recognize why domain knowledge can sometimes solve a problem more efficiently than simply making a network larger.",
  ],
  coreConcepts: [
    {
      title: "Advanced course mindset",
      body: "AMLA assumes Basic material is already usable: Python, NumPy, pandas, plotting, scikit-learn, train/validation/test logic and metric interpretation. The new value is neural-network reasoning and more mature model interpretation.",
      keywords: ["Basic as prerequisite", "less guidance", "interpretation"],
    },
    {
      title: "Artificial neuron",
      body: "A neuron receives numeric inputs, combines them through weights and bias, applies an activation function and passes an output forward. The biology is inspiration, not an exact model.",
      keywords: ["weights", "bias", "activation"],
    },
    {
      title: "Perceptron / TLU",
      body: "A threshold logic unit computes a weighted sum and applies a step-like decision. A single TLU creates a linear decision boundary, similar in spirit to logistic regression or a linear SVM.",
      keywords: ["linear boundary", "step function", "TLU"],
    },
    {
      title: "Bias term",
      body: "The bias shifts the activation threshold, just like the intercept in y = ax + b. Without it, the model may be forced through the wrong origin or threshold.",
      keywords: ["intercept", "threshold shift", "x0 = 1"],
    },
    {
      title: "MLP / FFNN / DNN",
      body: "A multilayer perceptron stacks dense layers. If information flows only forward it is a feed-forward neural network; if the stack is deep, it becomes a deep neural network.",
      keywords: ["dense", "hidden layers", "feed-forward"],
    },
    {
      title: "Capacity vs domain knowledge",
      body: "More layers and neurons increase expressivity, but a smart feature transformation can sometimes solve a nonlinear task with a simpler model.",
      keywords: ["capacity", "feature engineering", "x1 squared"],
    },
  ],
  slidePath: [
    {
      range: "Lecture 0 slides 4-16",
      title: "Course organization and material",
      concept: "The course uses English material, Virtuale as the access point, slides plus notebooks, and later GitHub/Colab resources.",
      intuition: "Treat Virtuale/Drive as the source of truth and the guide as a study layer on top of it.",
      professor: "He stressed that Bioinformatics students are expected in presence, while special remote cases are negotiated; recordings are not planned as official student material.",
      remember: "For study planning, check updated PDFs after class and do not rely only on preliminary TMP slides.",
    },
    {
      range: "Lecture 0 slides 21-27",
      title: "Exam and project shape",
      concept: "Bioinformatics LM students do written test plus project; PhD students mainly do project work; written tests are multiple choice on course topics.",
      intuition: "The written exam checks conceptual reasoning; the project checks whether you can run and explain a complete analysis.",
      professor: "He repeated that dates are visible later on Almaesami and that exam rules differ by student category.",
      remember: "For AMLA, prepare both MCQ reasoning and project/report interpretation; do not study only code snippets.",
    },
    {
      range: "Lecture 1 slides 2-8",
      title: "Basic recap and Advanced jump",
      concept: "The first part used mostly scikit-learn; Advanced adds Keras/TensorFlow and assumes Basic competence.",
      intuition: "The course deliberately jumps from classical ML to neural networks, then fills methodology as needed.",
      professor: "He said the hands-on will become less step-by-step in class and more something to explore at home.",
      remember: "If you cannot explain train/validation/test, regularization, bias-variance and metrics, review AMLB before continuing.",
    },
    {
      range: "Lecture 1 slides 10-18",
      title: "From biological to artificial neurons",
      concept: "BNNs motivate artificial neurons, but ANNs are simplified computational units with numeric inputs, weights and outputs.",
      intuition: "Use the biology only to remember the idea of connected units; use the math to explain the model.",
      professor: "The slides explicitly call the biological analogy vastly oversimplified.",
      remember: "In exam answers, avoid saying ANNs reproduce the brain; say they are simplified inspired computational models.",
    },
    {
      range: "Lecture 1 slides 19-24",
      title: "Bias, perceptron training and limitation",
      concept: "A perceptron updates weights after wrong predictions, but each output neuron keeps a linear decision boundary.",
      intuition: "A perceptron can move a line, but it cannot bend that line around XOR-like patterns.",
      professor: "He connected the bias to the intercept and highlighted that perceptrons work nicely but do not output class probabilities.",
      remember: "The limitation is not that perceptrons are useless; it is that one layer is not expressive enough for complex patterns.",
    },
    {
      range: "Lecture 1 slides 25-26 + live playground",
      title: "MLP and nonlinear boundaries",
      concept: "Stacking perceptrons/layers plus nonlinear activations turns simple linear units into more flexible models.",
      intuition: "Depth and width let the model combine many simpler boundaries; activation function changes geometry.",
      professor: "In the playground he asked students to compare tanh, ReLU and linear activations, and to watch loss, boundary shape and convergence.",
      remember: "Do not choose a network only by low loss; inspect stability, overfitting behavior and whether the learned boundary makes sense.",
    },
  ],
  professorEmphasis: [
    "Advanced assumes the Basic part as known; the course will use Python and scikit-learn with less mercy.",
    "Slides can change after each lecture; study from the final material when available.",
    "The written exam questions should be more reasoning-oriented because the exam allows material consultation under controlled conditions.",
    "The project is not only about running code; the advanced part requires stronger explanation, interpretation and use of advanced models.",
    "Linear activation cannot solve a nonlinear separation unless the input representation already encodes the needed nonlinear feature.",
    "Low test loss is not the full story: visual inspection and error analysis can reveal suspicious decision boundaries.",
    "Random initialization matters more when the network has low representational power.",
  ],
  commonTraps: [
    "Confusing the advanced course with a pure theory course; it is applied, but still expects conceptual explanation.",
    "Thinking a larger network is always better; it may overfit or learn unintuitive boundaries.",
    "Calling any neural network a deep network; depth refers to multiple hidden layers.",
    "Forgetting that nonlinear activation is what makes stacked layers more than just a larger linear model.",
    "Interpreting playground neuron plots as literal biological neurons instead of visual summaries of learned transformations.",
    "Assuming batch size always speeds up or improves classification; it changes update variability and convergence behavior.",
    "Using an LLM-generated project interpretation without being able to defend every choice orally.",
  ],
  miniLab: {
    title: "TensorFlow Playground: decision boundaries and capacity",
    href: null,
    todo: "The class used a web playground and discussed Colab/GitHub material later, but no standalone notebook URL for L01 was visible in the extracted sources.",
    objective: "Reproduce the reasoning from the live demo: change architecture and activation, then explain how the decision boundary and losses react.",
    steps: [
      "Open the neural-network playground used in class or an equivalent local reproduction.",
      "Start with a simple circular or XOR-like dataset using x1 and x2 only.",
      "Train with tanh, then ReLU, then linear activation.",
      "Repeat with fewer neurons and then with many layers/neurons.",
      "Add transformed features such as x1 squared and x2 squared when the interface allows it.",
    ],
    parameters: ["Activation function", "Number of hidden layers", "Neurons per layer", "Learning rate", "Batch size", "Input features"],
    outputs: ["Training loss", "Test loss", "Decision boundary shape", "Boundary stability after restart", "Inactive/near-zero neurons"],
    explain: [
      "Why ReLU tends to build polygon-like boundaries in this demo.",
      "Why linear activation fails on nonlinear data without feature transformation.",
      "Why a small network can converge differently after each restart.",
      "Why adding domain-informed squared features can beat blindly increasing capacity.",
    ],
  },
  quickQuiz: [
    {
      question: "What does AMLA assume from AML Basic?",
      answer: "It assumes basic Python/Colab, NumPy/pandas/plotting, scikit-learn, supervised-learning evaluation, bias-variance, regularization and metric interpretation are already usable.",
    },
    {
      question: "Why is a perceptron a linear classifier?",
      answer: "Its output is based on a weighted sum of inputs plus a threshold or activation. The boundary defined by that weighted sum is linear in the input space.",
    },
    {
      question: "What does the bias neuron do?",
      answer: "It provides a constant input, usually x0 = 1, so the model can shift the threshold or activation function, like the intercept term in a linear equation.",
    },
    {
      question: "Why does a linear activation collapse the benefit of stacking layers?",
      answer: "A composition of linear transformations is still linear, so stacking linear layers does not create nonlinear decision boundaries.",
    },
    {
      question: "What should you compare when deciding whether training is good enough?",
      answer: "Look at training and test/validation loss, convergence or plateau behavior, stability and whether the learned boundary/output makes sense for the data.",
    },
    {
      question: "Why can domain knowledge reduce the need for a large network?",
      answer: "If you know the right transformation, such as squared features for circular separation, a simpler model can solve the task because the input representation already exposes the structure.",
    },
  ],
  examQuestions: [
    {
      id: "l01-linear-activation",
      question: "A student stacks four dense layers but uses only linear activations. On a nonlinear XOR-like task, what is the best interpretation?",
      options: [
        "The model is deep, so it can represent any nonlinear boundary.",
        "The stack is still equivalent to a linear transformation, so nonlinear separation remains a problem.",
        "The model will work if the learning rate is small enough, regardless of representation.",
        "The output layer alone guarantees nonlinearity.",
      ],
      correct: 1,
      explanation: "Without nonlinear activations, composing layers does not add nonlinear representational power.",
    },
    {
      id: "l01-low-loss",
      question: "In the playground, a very large network gets low loss but learns a strange boundary around isolated points. What should you conclude?",
      options: [
        "Low loss always proves the model is conceptually correct.",
        "The model may be over-specializing; inspect the boundary, data and error cases before trusting it.",
        "The solution is automatically better because it uses more parameters.",
        "The test loss should be ignored whenever the boundary is visible.",
      ],
      correct: 1,
      explanation: "The lecture emphasized that metrics alone can hide subtle failure modes.",
    },
    {
      id: "l01-bias",
      question: "Why is the bias term important in an artificial neuron?",
      options: [
        "It removes all overfitting.",
        "It shifts the activation threshold and lets the unit represent boundaries not forced through the origin.",
        "It replaces the need for weights.",
        "It makes the neuron biologically exact.",
      ],
      correct: 1,
      explanation: "The professor used the y = ax + b analogy: the bias acts like an intercept.",
    },
    {
      id: "l01-domain-knowledge",
      question: "For circular separation, adding x1^2 and x2^2 lets a simple model converge quickly. What lesson does this illustrate?",
      options: [
        "Feature engineering and domain knowledge can sometimes reduce architecture complexity.",
        "Squared features always remove the need for neural networks.",
        "The model is no longer supervised learning.",
        "Only ReLU can use engineered features.",
      ],
      correct: 0,
      explanation: "A good representation can make a hard nonlinear task easier for a simpler model.",
    },
  ],
  checklistTitle: "What to take from L01",
  studyChecklist: [
    "Review AMLB concepts that AMLA assumes: evaluation, regularization, bias-variance and metrics.",
    "Be able to define perceptron, bias, MLP, FFNN and DNN in one or two precise sentences each.",
    "Explain why nonlinearity matters between layers.",
    "Use playground outputs as evidence: loss curves, boundary shape, restart stability and inactive neurons.",
    "Connect project expectations to interpretation maturity, not only model application.",
  ],
};
