export const lessonContent = {
  id: "amla-2026-05-08-model-regularization",
  extractionStatus: "source-based complete draft",
  objectives: [
    "Explain why CNNs are preferred over fully connected MLPs for image-like data.",
    "Connect local receptive fields, hierarchy and weight sharing to the CNN design.",
    "Describe a convolutional layer in terms of filters/kernels, feature maps, stride, padding and activation.",
    "Distinguish convolution, pooling, flattening and fully connected classification blocks.",
    "Read basic CNN hyperparameters without losing track of tensor shape changes.",
    "Interpret feature maps, filter visualizations and class-output visualizations as evidence of learned representations.",
    "Recognize the high-level ideas behind LeNet, AlexNet, GoogLeNet/Inception, ResNet, Xception and SENet without memorizing every detail.",
  ],
  coreConcepts: [
    {
      title: "Local receptive field",
      body: "A neuron or filter looks only at a local region of the input. This matches the idea that nearby pixels contain useful local patterns.",
      keywords: ["locality", "visual cortex", "partial connection"],
    },
    {
      title: "Weight sharing",
      body: "The same filter is applied across many image locations. This reduces parameters and supports translation-aware feature detection.",
      keywords: ["filter reuse", "translation", "parameter sharing"],
    },
    {
      title: "Convolution",
      body: "A filter/kernel slides over the input. At each location it computes element-wise products, sums them and produces one value in a feature map.",
      keywords: ["kernel", "sliding window", "feature map"],
    },
    {
      title: "Feature map",
      body: "One feature map is the spatial output produced by one filter. Multiple filters produce multiple feature maps stacked along depth.",
      keywords: ["depth channels", "activation", "features"],
    },
    {
      title: "Stride",
      body: "Stride controls how far the filter moves at each step. Larger stride reduces overlap and makes the output smaller.",
      keywords: ["step size", "downsampling", "output size"],
    },
    {
      title: "Padding",
      body: "Padding adds values around the input so borders can contribute fairly and feature maps do not shrink too quickly.",
      keywords: ["same", "valid", "zero padding"],
    },
    {
      title: "Pooling",
      body: "Pooling downsamples each feature map independently, usually reducing height and width while keeping depth.",
      keywords: ["max pooling", "compression", "overfitting"],
    },
    {
      title: "CNN representation hierarchy",
      body: "Early layers tend to detect edges and simple shapes; deeper layers combine them into more abstract, class-related features.",
      keywords: ["edges", "parts", "abstraction"],
    },
  ],
  walkthroughSections: [
    {
      range: "Module 1 / Lecture4 slides 1-13",
      title: "Why CNNs exist: images, locality and parameter sharing",
      intro: "Read the opening slides as motivation. CNNs are not just bigger MLPs; they encode assumptions about images and local patterns.",
      slides: [
        {
          label: "Slide 1",
          deckLabel: "Module 1 / Lecture4",
          page: 1,
          image: "amla-slides/module1-lecture4/slide-01.png",
          title: "Lecture frame",
          comment: "This class starts a new model family after the tensor and training-loop material. The date on the deck matches the 2026-05-08 transcript.",
          professor: "The professor framed CNNs as one of the most important families in the course, useful beyond the domain where they were first designed.",
          remember: "This is the transition from generic dense networks to architecture that exploits image structure.",
        },
        {
          label: "Slides 4-5",
          deckLabel: "Module 1 / Lecture4",
          page: 4,
          image: "amla-slides/module1-lecture4/slide-04.png",
          title: "CNNs became dominant because they work",
          comment: "CNNs dominate computer vision, but the professor also notes their surprising usefulness in other domains such as time series or NLP baselines.",
          professor: "He stressed the pragmatic lesson: if you need something beyond an MLP, trying a CNN can be a reasonable baseline because the logic is powerful.",
          remember: "CNN success comes from automatic feature extraction, computational efficiency and parameter sharing.",
        },
        {
          label: "Slide 5",
          deckLabel: "Module 1 / Lecture4",
          page: 5,
          image: "amla-slides/module1-lecture4/slide-05.png",
          title: "Automatic feature extraction",
          comment: "Instead of manually selecting image features, the network learns filters that identify useful visual patterns from image-label examples.",
          professor: "The instructor contrasted this with hand-designed feature selection: the CNN learns which pixels/patterns matter for the task.",
          remember: "CNNs reduce manual feature engineering, but they still depend strongly on data and architecture choices.",
        },
        {
          label: "Slide 7",
          deckLabel: "Module 1 / Lecture4",
          page: 7,
          image: "amla-slides/module1-lecture4/slide-07.png",
          title: "Vision inspiration, not literal brain code",
          comment: "CNNs are inspired by visual cortex ideas, but the professor explicitly warned that this is not a faithful implementation of human vision.",
          professor: "He said the brain does not simply run the Python-style convolutions we use; CNNs are used because they work, not because they fully explain biology.",
          remember: "Use biological inspiration as intuition, not as a literal equivalence.",
          trap: "Do not claim CNNs are exactly how human visual perception works.",
        },
        {
          label: "Slides 9-10",
          deckLabel: "Module 1 / Lecture4",
          page: 9,
          image: "amla-slides/module1-lecture4/slide-09.png",
          title: "Receptive fields and hierarchy",
          comment: "The visual-cortex story gives three ideas: local receptive fields, pattern-sensitive neurons and hierarchical combination of simple patterns into complex ones.",
          professor: "He used the soldier/general analogy: some units look for simple local patterns; higher-level units combine their information.",
          remember: "Locality plus hierarchy is the conceptual core of CNN feature extraction.",
        },
        {
          label: "Slide 11",
          deckLabel: "Module 1 / Lecture4",
          page: 11,
          image: "amla-slides/module1-lecture4/slide-11.png",
          title: "LeNet introduced the new blocks",
          comment: "LeNet-5 is the historical bridge: it still uses familiar fully connected layers and activations, but adds convolutional and pooling layers.",
          professor: "The professor linked LeNet to handwritten digits and MNIST, emphasizing that the task was simple enough to study but economically important.",
          remember: "CNN architecture adds convolution and pooling before the final classifier.",
        },
        {
          label: "Slide 13",
          deckLabel: "Module 1 / Lecture4",
          page: 13,
          image: "amla-slides/module1-lecture4/slide-13.png",
          title: "Why not a fully connected MLP?",
          comment: "Flattening large images into dense layers explodes the number of connections. CNNs solve this with partial connectivity and weight sharing.",
          professor: "He returned to the difference between MNIST-scale examples and larger images: dense layers may work on tiny images, but they become impractical fast.",
          remember: "CNNs are not only more accurate; they are parameter-efficient for image-like inputs.",
          trap: "Do not argue that CNNs are useful only because they are deeper. Their connection pattern matters.",
        },
      ],
    },
    {
      range: "Module 1 / Lecture4 slides 17-30",
      title: "Convolution builds feature maps from filters",
      intro: "This is the mechanics block. Follow the slides as a shape story: input, kernel, local multiplication/sum, feature map, activation.",
      slides: [
        {
          label: "Slide 17",
          deckLabel: "Module 1 / Lecture4",
          page: 17,
          image: "amla-slides/module1-lecture4/slide-17.png",
          title: "Low-level to high-level features",
          comment: "The simple diagram captures the hierarchy: first layers detect local low-level features, later layers assemble them into higher-level features.",
          professor: "He repeatedly emphasized that layers build on previous layers: lines combine into shapes, shapes into object-like parts.",
          remember: "CNN depth is useful because representation becomes progressively more abstract.",
        },
        {
          label: "Slide 19",
          deckLabel: "Module 1 / Lecture4",
          page: 19,
          image: "amla-slides/module1-lecture4/slide-19.png",
          title: "Translation and weight sharing",
          comment: "If the same object appears in a different image location, recognition should not collapse. Weight sharing applies the same filter across positions.",
          professor: "The professor used this as the bridge from intuition to convolution: the same detector scans different locations.",
          remember: "Weight sharing is the CNN answer to location variability and parameter explosion.",
        },
        {
          label: "Slides 21-24",
          deckLabel: "Module 1 / Lecture4",
          page: 21,
          image: "amla-slides/module1-lecture4/slide-21.png",
          title: "1D convolution: signal and kernel",
          comment: "The finite signal is the data; the small function is the filter or kernel. Sliding the kernel merges local information into a new signal.",
          professor: "He described it as scanning a filter through the signal and computing simple products/sums at each position.",
          remember: "A filter is a learned or chosen pattern detector applied repeatedly across the input.",
        },
        {
          label: "Slide 25",
          deckLabel: "Module 1 / Lecture4",
          page: 25,
          image: "amla-slides/module1-lecture4/slide-25.png",
          title: "A kernel controls the effect",
          comment: "The Gaussian smoothing example shows that changing the kernel changes what the operation extracts or suppresses.",
          professor: "He asked how one could control smoothing strength: the answer is to change properties of the filter, such as width/shape.",
          remember: "Filter choice determines the kind of feature/effect produced.",
        },
        {
          label: "Slide 26",
          deckLabel: "Module 1 / Lecture4",
          page: 26,
          image: "amla-slides/module1-lecture4/slide-26.png",
          title: "2D convolution creates a feature map",
          comment: "In 2D, a small kernel slides over an image patch. At each location the element-wise products are summed and written into a feature map.",
          professor: "He walked through the green input patch, blue input, red feature map logic to make the operation concrete.",
          remember: "One filter produces one feature map; the receptive field is the local patch being read.",
        },
        {
          label: "Slides 28-29",
          deckLabel: "Module 1 / Lecture4",
          page: 29,
          image: "amla-slides/module1-lecture4/slide-29.png",
          title: "3D convolution and depth",
          comment: "For RGB images, the filter has height, width and depth. One 5x5x3 filter over a 32x32x3 image produces one 2D feature map; multiple filters produce multiple maps.",
          professor: "He clarified that each additional filter generates a separate feature map, so depth after convolution equals the number of filters.",
          remember: "Input channels are consumed by each filter; output channels are created by the number of filters.",
          trap: "Do not confuse image RGB depth with the number of output feature maps.",
        },
        {
          label: "Slide 30",
          deckLabel: "Module 1 / Lecture4",
          page: 30,
          image: "amla-slides/module1-lecture4/slide-30.png",
          title: "Activation still matters",
          comment: "The diagrams often omit nonlinearities for clarity, but convolutional weighted sums still pass through activations such as ReLU.",
          professor: "He pointed out that raw convolution is linear; nonlinearity is needed just like in previous neural networks.",
          remember: "Conv layer = local linear operation plus activation, not only sliding sums.",
        },
      ],
      lab: {
        title: "Mini-lab: compute one convolution by hand",
        todo: "No standalone notebook URL was visible in the extracted sources for this lecture.",
        objective: "Make the feature-map calculation concrete before relying on Keras layers.",
        steps: [
          "Write a 4x4 input matrix and a 3x3 kernel.",
          "Place the kernel on the top-left 3x3 patch.",
          "Multiply element-wise and sum to get the first output value.",
          "Slide one step to the right and repeat.",
          "Write the resulting output shape for valid padding and stride 1.",
        ],
        parameters: ["kernel values", "kernel size", "stride", "padding mode"],
        outputs: ["first feature-map value", "output height", "output width"],
        explain: [
          "Why a local patch is called the receptive field.",
          "Why one kernel gives one feature map.",
          "How changing the kernel changes the detected pattern.",
        ],
      },
    },
    {
      range: "Module 1 / Lecture4 slides 31-43",
      title: "Stride, padding, pooling and the basic CNN architecture",
      intro: "These slides are the shape-control toolkit. They explain how CNNs shrink, preserve or compress representations before the final classifier.",
      slides: [
        {
          label: "Slide 31",
          deckLabel: "Module 1 / Lecture4",
          page: 31,
          image: "amla-slides/module1-lecture4/slide-31.png",
          title: "Stride",
          comment: "Stride defines how far the filter jumps each time. Larger stride means fewer positions are evaluated and the feature map becomes smaller.",
          professor: "He described stride as deciding how big the jump is when scanning the input.",
          remember: "Increasing stride is a direct way to reduce spatial resolution.",
        },
        {
          label: "Slides 32-33",
          deckLabel: "Module 1 / Lecture4",
          page: 33,
          image: "amla-slides/module1-lecture4/slide-33.png",
          title: "Padding and borders",
          comment: "Without padding, borders are underrepresented and outputs shrink. Same/valid/full are different choices about how the kernel may overlap the input.",
          professor: "A student question led to a careful explanation: padding gives edge pixels a fair chance to influence the output.",
          remember: "Use padding to preserve information and control shape; valid padding intentionally shrinks.",
          trap: "Padding is not the same as pooling. Padding can preserve size; pooling intentionally compresses.",
        },
        {
          label: "Slide 35",
          deckLabel: "Module 1 / Lecture4",
          page: 35,
          image: "amla-slides/module1-lecture4/slide-35.png",
          title: "Pooling",
          comment: "Pooling reduces height and width independently for each feature map. Max pooling keeps the strongest activation in each window.",
          professor: "He framed pooling as clever compression: take good notes, then summarize them before continuing.",
          remember: "Pooling reduces parameters and training cost while trying to preserve useful signals.",
        },
        {
          label: "Slides 37-39",
          deckLabel: "Module 1 / Lecture4",
          page: 37,
          image: "amla-slides/module1-lecture4/slide-37.png",
          title: "Padding vs pooling is not a contradiction",
          comment: "Padding prevents accidental shrinking and border bias; pooling performs deliberate compression after useful features have been extracted.",
          professor: "He stressed that you do want dimensionality reduction, but you want to do it intelligently.",
          remember: "First preserve enough useful feature information; then compress it with pooling.",
        },
        {
          label: "Slide 40",
          deckLabel: "Module 1 / Lecture4",
          page: 40,
          image: "amla-slides/module1-lecture4/slide-40.png",
          title: "CNN hyperparameters",
          comment: "Filter size, filter count, stride and padding are the first CNN degrees of freedom. More filters increase power but also overfitting risk.",
          professor: "He said that if in doubt, padding is usually used, and filter counts often grow as the network gets deeper.",
          remember: "Typical starting point: 3x3 filters, stride 1, padding, and increasing filter counts with depth.",
        },
        {
          label: "Slides 41-42",
          deckLabel: "Module 1 / Lecture4",
          page: 42,
          image: "amla-slides/module1-lecture4/slide-42.png",
          title: "From feature extraction to classification",
          comment: "Convolution and pooling produce 3D volumes; fully connected layers expect a 1D vector, so flattening connects feature extraction to classification.",
          professor: "He emphasized that flattening is only rearranging data; the real feature learning has happened in the convolutional part.",
          remember: "Basic CNN = conv/pool feature extractor + flatten + dense classifier.",
        },
        {
          label: "Slide 43",
          deckLabel: "Module 1 / Lecture4",
          page: 43,
          image: "amla-slides/module1-lecture4/slide-43.png",
          title: "The two parts of a CNN",
          comment: "Convolutional layers are the horsepower: they learn features. Fully connected layers use those features to assign class probabilities.",
          professor: "He explicitly called convolutional layers the horsepower of CNNs; pooling manages information, but convolutions do most of the representational work.",
          remember: "When interpreting a CNN, separate feature extraction from classification.",
        },
      ],
      lab: {
        title: "Mini-lab: trace CNN shapes",
        todo: "Use any local scratch notebook or calculator; no standalone Colab link was exposed in the source material.",
        objective: "Predict how height, width and depth change through a small CNN.",
        steps: [
          "Start with a 32x32x3 RGB image.",
          "Apply a 3x3 convolution with 16 filters, stride 1 and same padding.",
          "Apply 2x2 max pooling with stride 2.",
          "Apply a second 3x3 convolution with 32 filters and same padding.",
          "Flatten the final volume and state the vector length.",
        ],
        parameters: ["input shape", "filter count", "padding", "pooling window", "stride"],
        outputs: ["post-convolution shape", "post-pooling shape", "flattened vector size"],
        explain: [
          "Why convolution changes depth to the number of filters.",
          "Why pooling reduces height and width but not depth.",
          "Why flattening is needed before dense layers.",
        ],
      },
    },
    {
      range: "Module 1 / Lecture4 slides 45-64",
      title: "Visualizing feature maps, filters and class outputs",
      intro: "This is the interpretability block. It does not make CNNs fully transparent, but it helps you see what representations become at different depths.",
      slides: [
        {
          label: "Slides 45-46",
          deckLabel: "Module 1 / Lecture4",
          page: 46,
          image: "amla-slides/module1-lecture4/slide-46.png",
          title: "Why VGG is used for visualization",
          comment: "VGG is not the newest architecture, but it is simple enough to inspect while still being a serious ImageNet-era CNN.",
          professor: "He said VGG is useful here because ResNet would be more accurate but much more complex to inspect.",
          remember: "For learning representations, choose an architecture simple enough to reason about.",
        },
        {
          label: "Slides 49-54",
          deckLabel: "Module 1 / Lecture4",
          page: 54,
          image: "amla-slides/module1-lecture4/slide-54.png",
          title: "Feature maps become abstract and sparse",
          comment: "Early feature maps still resemble the input and detect edges/shapes. Deeper feature maps become abstract, sparser and more class-related.",
          professor: "He used the cat example: early maps still look like a cat; deeper maps no longer look like a picture to us but encode more useful class evidence for the model.",
          remember: "Less human-readable does not mean less useful to the network.",
        },
        {
          label: "Slides 55-56",
          deckLabel: "Module 1 / Lecture4",
          page: 55,
          image: "amla-slides/module1-lecture4/slide-55.png",
          title: "Many feature maps, many detectors",
          comment: "A layer contains many feature maps. Some may activate weakly for a given image because the corresponding feature is absent.",
          professor: "When asked whether inactive-looking filters could be removed, he explained that a filter may be irrelevant for one image but useful elsewhere.",
          remember: "A quiet feature map for one image is not automatically a useless filter.",
        },
        {
          label: "Slides 58-61",
          deckLabel: "Module 1 / Lecture4",
          page: 60,
          image: "amla-slides/module1-lecture4/slide-60.png",
          title: "Filter visualization through activation maximization",
          comment: "Instead of displaying tiny kernels, the method generates an input image that maximally activates a filter. Deeper filters respond to increasingly complex patterns.",
          professor: "He noted this is not the most important practical notebook operation, but it gives a visual feel for what a filter is looking for.",
          remember: "Filter visualization asks: what input pattern would make this filter fire strongly?",
        },
        {
          label: "Slides 63-64",
          deckLabel: "Module 1 / Lecture4",
          page: 64,
          image: "amla-slides/module1-lecture4/slide-64.png",
          title: "Class-output visualization",
          comment: "The final softmax can be probed by asking the network to generate an image that maximizes one class probability.",
          professor: "The tennis-ball example shows data dependence: a racket pattern may become part of what the model associates with tennis balls if the training data often contains both.",
          remember: "Model concepts are statistical patterns learned from training data, not human semantic understanding.",
          trap: "Do not say the model knows what a crocodile or tennis ball is in a human sense.",
        },
      ],
      lab: {
        title: "Mini-lab: interpret feature maps without overclaiming",
        todo: "The slide says filter visualization is not in the Colab notebook, and no independent URL was visible in the extracted sources.",
        objective: "Practice cautious interpretation of CNN internal visualizations.",
        steps: [
          "Pick one early-layer feature-map image and describe only visible patterns.",
          "Pick one deeper-layer feature-map image and note what became sparse or abstract.",
          "For a class-output visualization, list which visual cues might have been learned from training data.",
          "Write one sentence that avoids anthropomorphic claims.",
        ],
        parameters: ["layer depth", "selected feature map", "class label"],
        outputs: ["visible pattern notes", "abstraction notes", "data-bias hypothesis"],
        explain: [
          "Why early layers are easier for humans to inspect.",
          "Why deeper representations may look strange but still support classification.",
          "Why training-data correlations can mislead class predictions.",
        ],
      },
    },
    {
      range: "Module 1 / Lecture4 slides 65-118",
      title: "CNN architecture evolution: know the ideas, not every detail",
      intro: "This section is explicitly marked as general-course material plus educational detail. Study the names and core innovations; do not drown in every hyperparameter.",
      slides: [
        {
          label: "Slides 65-67",
          deckLabel: "Module 1 / Lecture4",
          page: 67,
          image: "amla-slides/module1-lecture4/slide-67.png",
          title: "Architecture history as a map of ideas",
          comment: "The deck frames the architecture tour as a way to understand how CNNs evolved through ImageNet/ILSVRC improvements.",
          professor: "He explicitly said the names and general ideas matter more than detailed descriptions of every architecture.",
          remember: "Know the broad evolution: LeNet, AlexNet, GoogLeNet/Inception, VGG, ResNet, Xception, SENet.",
        },
        {
          label: "Slide 70",
          deckLabel: "Module 1 / Lecture4",
          page: 70,
          image: "amla-slides/module1-lecture4/slide-70.png",
          title: "LeNet-5",
          comment: "LeNet is the classic handwritten-digit CNN: convolution/pooling blocks followed by fully connected layers.",
          professor: "He linked it back to MNIST and noted that older pooling details differ from modern max pooling.",
          remember: "LeNet is the historical template, not the modern performance ceiling.",
        },
        {
          label: "Slides 72-75",
          deckLabel: "Module 1 / Lecture4",
          page: 73,
          image: "amla-slides/module1-lecture4/slide-73.png",
          title: "AlexNet",
          comment: "AlexNet made CNNs famous in 2012 by scaling depth, ReLU, regularization and data augmentation for ImageNet.",
          professor: "He used AlexNet as the start of the modern explosion: from eight layers to much deeper architectures in only a few years.",
          remember: "AlexNet is the turning point for deep CNNs in modern computer vision.",
        },
        {
          label: "Slides 81-85",
          deckLabel: "Module 1 / Lecture4",
          page: 84,
          image: "amla-slides/module1-lecture4/slide-84.png",
          title: "GoogLeNet and Inception",
          comment: "Inception modules run multiple filter sizes in parallel and concatenate outputs, allowing different scales to be captured efficiently.",
          professor: "He described an inception module as convolutions in parallel rather than simply stacking everything deeper.",
          remember: "Inception trades simple depth for multi-scale parallel feature extraction.",
        },
        {
          label: "Slides 94-101",
          deckLabel: "Module 1 / Lecture4",
          page: 96,
          image: "amla-slides/module1-lecture4/slide-96.png",
          title: "ResNet and skip connections",
          comment: "ResNet uses residual blocks and skip connections so very deep networks can still pass signals and learn effectively.",
          professor: "He highlighted ResNet as still understandable in broad strokes: convolutional stacks plus shortcut connections.",
          remember: "Skip connections help train very deep networks by letting information flow across layers.",
        },
        {
          label: "Slides 106-109",
          deckLabel: "Module 1 / Lecture4",
          page: 106,
          image: "amla-slides/module1-lecture4/slide-106.png",
          title: "Xception and separable convolutions",
          comment: "Xception separates spatial filtering from cross-channel mixing, reducing parameters and computation in many settings.",
          professor: "He treated these later details as useful intuition rather than likely written-test derivations.",
          remember: "Separable convolutions assume spatial and channel patterns can be modeled separately.",
        },
        {
          label: "Slides 113-118",
          deckLabel: "Module 1 / Lecture4",
          page: 115,
          image: "amla-slides/module1-lecture4/slide-115.png",
          title: "SENet and feature recalibration",
          comment: "SENet adds small blocks that recalibrate feature maps by learning which channels should be emphasized together.",
          professor: "The final takeaway was not to memorize every architecture, but to see how later improvements build on the original CNN principles.",
          remember: "Modern CNN progress often refines feature extraction and channel weighting rather than replacing the whole idea.",
        },
      ],
    },
  ],
  professorEmphasis: [
    "CNNs are central in the course because they are powerful, practical and often useful beyond pure image classification.",
    "The visual-cortex analogy is inspiration only; CNNs are not a literal model of how the brain sees.",
    "The motivation matters: fully connected layers on large images explode in parameters, while CNNs use locality and weight sharing.",
    "Convolutional layers are the horsepower of CNNs; pooling mainly manages/compresses information.",
    "Padding and pooling are not contradictory: padding avoids unfair/accidental shrinkage, pooling performs deliberate compression.",
    "For architecture history, know names and key ideas; detailed hyperparameters of every architecture are not the main written-exam target.",
    "Feature maps and filter visualizations are useful, but interpretations must stay cautious and data-dependent.",
  ],
  commonTraps: [
    "Saying a CNN is just an MLP with more layers.",
    "Confusing input channels with output feature maps.",
    "Forgetting that convolutional outputs still pass through nonlinear activation functions.",
    "Treating padding as the opposite of pooling instead of a different shape-control operation.",
    "Assuming max pooling always preserves every important detail.",
    "Interpreting feature maps as if the model had human semantic understanding.",
    "Memorizing AlexNet/GoogLeNet/ResNet details while missing the shared CNN principles.",
    "Thinking an inactive feature map in one image means the filter is globally useless.",
  ],
  quickQuiz: [
    {
      question: "Why do fully connected MLPs become problematic for larger images?",
      answer: "Flattening large images creates a huge number of input features and dense connections, leading to many parameters and poor scalability.",
    },
    {
      question: "What does weight sharing mean in a CNN?",
      answer: "The same filter/kernel is applied across different spatial locations, reducing parameters and detecting the same pattern wherever it appears.",
    },
    {
      question: "What is one feature map?",
      answer: "The spatial output produced by applying one filter across the input.",
    },
    {
      question: "If a convolutional layer has 32 filters, how many output feature maps does it produce?",
      answer: "Thirty-two feature maps, one per filter.",
    },
    {
      question: "Why is padding often used?",
      answer: "It prevents rapid shrinking, lets edge pixels contribute more fairly and can preserve output size.",
    },
    {
      question: "What does pooling usually change in a feature volume?",
      answer: "It reduces height and width while preserving depth, because pooling is applied independently to each feature map.",
    },
    {
      question: "What is the role of flattening in a basic CNN?",
      answer: "It converts the final 3D feature volume into a 1D vector that dense classifier layers can consume.",
    },
    {
      question: "Why do deeper feature maps often look less like the original image?",
      answer: "They encode more abstract, class-related patterns rather than pixel-level visual details.",
    },
  ],
  examQuestions: [
    {
      id: "l06-mcq-1",
      question: "A student says: 'CNNs work for images because every pixel is connected to every neuron, so the model sees everything at once.' What is the best correction?",
      options: [
        "CNNs rely on local receptive fields and shared filters, not dense all-to-all image connections",
        "CNNs avoid hidden layers entirely",
        "CNNs work only because they use softmax instead of sigmoid",
        "CNNs remove the need for training data",
      ],
      correct: 0,
      explanation: "The CNN advantage comes from local connectivity and weight sharing, which reduce parameters and exploit image structure.",
    },
    {
      id: "l06-mcq-2",
      question: "A 32x32x3 image is passed through one 5x5x3 filter with padding that preserves spatial size. What is the output of that one filter?",
      options: [
        "A 32x32x1 feature map",
        "A 32x32x3 RGB image",
        "Five 32x32 feature maps",
        "A flattened vector with 32 entries",
      ],
      correct: 0,
      explanation: "One 3D filter spans the input channels and produces one scalar per spatial location, yielding one feature map.",
    },
    {
      id: "l06-mcq-3",
      question: "Why can padding and pooling coexist in the same CNN without contradicting each other?",
      options: [
        "Padding preserves/control shapes and edge information; pooling later performs deliberate compression",
        "Padding and pooling are mathematically identical",
        "Pooling is used only during inference, while padding is used only during training",
        "Padding removes channels and pooling restores them",
      ],
      correct: 0,
      explanation: "Padding prevents accidental shrinkage or border disadvantage; pooling intentionally downsamples after feature extraction.",
    },
    {
      id: "l06-mcq-4",
      question: "In a basic CNN, what is the cleanest division of labor between convolutional layers and final fully connected layers?",
      options: [
        "Convolutional layers extract learned features; fully connected layers classify from those features",
        "Convolutional layers compute only the final probabilities; fully connected layers do feature extraction",
        "Convolutional layers only reduce dimensionality; pooling layers do all pattern detection",
        "Fully connected layers are used only to add padding",
      ],
      correct: 0,
      explanation: "The professor explicitly framed conv layers as the feature-extraction horsepower and dense layers as the classifier on top.",
    },
    {
      id: "l06-mcq-5",
      question: "Which interpretation of a deep feature map is most careful?",
      options: [
        "It may encode abstract class-related evidence, but it should not be treated as human semantic understanding",
        "It always shows the original image more clearly than early layers",
        "It proves the model knows the object in the same way humans do",
        "It is useless if it looks sparse",
      ],
      correct: 0,
      explanation: "Deeper feature maps often become abstract and sparse; they can support classification without being human-readable.",
    },
  ],
  checklistTitle: "L06 final takeaways",
  studyChecklist: [
    "Explain CNNs through locality, hierarchy and weight sharing.",
    "For any convolution layer, identify input shape, filter shape, filter count, stride and padding.",
    "Remember: one filter produces one feature map; many filters produce a depth stack.",
    "Separate padding from pooling in your vocabulary.",
    "Describe a basic CNN as feature extraction plus classification.",
    "Use visualizations as clues about learned representations, not as complete explanations.",
    "For architecture history, keep the headline ideas: LeNet template, AlexNet breakthrough, Inception parallel filters, ResNet skip connections, Xception separable convolutions, SENet recalibration.",
  ],
};
