import { buildSections } from "../shared/buildContent.js";

const deck = "1-Structure-Alignment.pdf";
const deckFolder = "01-structure-alignment";
const title = "Protein and RNA structure alignment";

export const lessonContent = {
  id: "lb1-01-structure-alignment",
  extractionStatus: "real slide screenshots extracted from all 54 slides of 1-Structure-Alignment.pdf",
  whyThisMatters: "Structure alignment is one of the cleanest examples of why bioinformatics is not only sequence comparison. Two proteins or RNAs can keep a similar three-dimensional organization after their sequences diverge, so structural comparison can reveal relationships and functional clues that sequence identity alone may miss.",
  objectives: [
    "Define structure superimposition as fitting two structures when the correspondence between atoms or residues is already known.",
    "Define structure alignment as the harder problem of first finding the correspondence set and then optimizing the superimposition.",
    "Explain RMSD as a distance measure after optimal rigid-body transformation.",
    "Choose the right level of comparison: atom, residue, domain, whole chain, multi-domain protein or RNA structure.",
    "Compare major structural-alignment representations: coordinates, torsion angles, distance matrices, fragments, SSE graphs and unit vectors.",
    "Explain what CE, PDBeFold, MAMMOTH and SARA contribute conceptually without memorizing implementation details.",
    "Interpret structural similarity with statistical significance, alignment length, biological context and feature choice.",
  ],
  coreConcepts: [
    {
      title: "Correspondence set",
      body: "A correspondence set states which residue or atom in structure A is compared to which residue or atom in structure B. Superimposition assumes this mapping; alignment must discover it.",
      keywords: ["mapping", "residue pairs", "hard part"],
    },
    {
      title: "Rigid-body transformation",
      body: "Once correspondence is known, the structures can be rotated and translated to minimize distance. The molecule is not bent or refolded; only its position in space changes.",
      keywords: ["rotation", "translation", "no deformation"],
    },
    {
      title: "RMSD and aligned length",
      body: "RMSD summarizes distance between matched points after fitting, but it is meaningful only together with the chosen atoms, correspondence, aligned region and alignment length.",
      keywords: ["RMSD", "matched points", "coverage"],
    },
    {
      title: "Level of comparison",
      body: "A comparison can be made at the level of local motifs, domains, whole chains, flexible multi-domain proteins or RNA structural elements. The biological question decides the level.",
      keywords: ["domains", "hinge", "local vs global"],
    },
    {
      title: "Representation controls the method",
      body: "Structural alignment tools differ because they compare different features: C-alpha atoms, all atoms, secondary-structure elements, torsion angles, distance matrices, contact maps, surfaces or unit vectors.",
      keywords: ["features", "descriptors", "method choice"],
    },
    {
      title: "Statistics makes the score interpretable",
      body: "Algorithms such as CE, MAMMOTH and SARA need background distributions, p-values, Z-scores or E-value-like reasoning to decide whether an alignment is surprising.",
      keywords: ["significance", "background", "score"],
    },
    {
      title: "RNA follows the same logic with different features",
      body: "RNA structural alignment still needs representation, correspondence, scoring and significance, but atom selection, secondary structure and RNA-specific metrics matter.",
      keywords: ["RNA", "SARA", "PSI/PSS/PID"],
    },
  ],
  routeSteps: [
    {
      title: "Start with the task distinction",
      body: "If residue/atom correspondence is known, it is superimposition. If correspondence must be found, it is structural alignment.",
    },
    {
      title: "Choose the comparison level",
      body: "Decide whether you are comparing local geometry, domains, whole proteins, flexible multi-domain structures or RNA folds.",
    },
    {
      title: "Identify the representation",
      body: "Ask what the method compares: coordinates, fragments, torsion angles, distance matrices, SSE graphs or unit vectors.",
    },
    {
      title: "Evaluate significance and meaning",
      body: "Interpret RMSD, score, aligned length and statistical significance in the biological context.",
    },
  ],
  walkthroughSections: buildSections({
    deckFolder,
    deck,
    title,
    remember: "Every structural-alignment answer should name the representation, correspondence problem, scoring/evaluation and biological interpretation.",
    trap: "Do not use RMSD or a tool score as an automatic biological conclusion without checking aligned length, correspondence, method assumptions and significance.",
    prompt: "What is being compared on this slide, and what evidence would make the comparison biologically meaningful?",
    sections: [
      {
        start: 1,
        end: 5,
        title: "Definitions: superimposition versus structural alignment",
        intro: "The deck opens with the core exam distinction: superimposition fits a known correspondence, while structural alignment must first find the correspondence set.",
        teaching: "Study interpretation: say this contrast before discussing RMSD. Superimposition is the geometric fitting step; alignment includes the harder search for matching atoms or residues.",
        trap: "Do not say superimposition discovers which residues correspond. It only optimizes the fit after correspondence is known.",
        prompt: "What information must be known before superimposition, and what additional problem must structural alignment solve?",
      },
      {
        start: 6,
        end: 9,
        title: "Structure comparison pipeline, domains and topology",
        intro: "After the definitions, the deck broadens to feature extraction, statistical significance, domains, hinge movement and topology-independent alignments.",
        teaching: "Study interpretation: a poor whole-chain fit can hide good domain-level similarity, and similar spatial arrangements can exist even when topology differs.",
        remember: "Choose the level of comparison before interpreting the score.",
        trap: "Do not conclude that two proteins are unrelated just because a single rigid whole-chain alignment is poor.",
        prompt: "When should a domain-level or topology-aware comparison be preferred over a whole-chain rigid alignment?",
      },
      {
        start: 10,
        end: 16,
        title: "Tool landscape and method classification",
        intro: "These slides classify structural alignment methods by flexibility, pairwise versus multiple alignment, and the structural features they compare.",
        teaching: "Study interpretation: learn the axes of classification rather than memorizing more than one hundred tool names.",
        remember: "Method choice follows the expected structural change and the biological question.",
        trap: "Do not compare scores from two tools as if they used the same representation, constraints and significance model.",
        prompt: "Which method features would you choose for a flexible multi-domain protein?",
      },
      {
        start: 17,
        end: 23,
        title: "CE algorithm: aligned fragment pairs and significance",
        intro: "The CE slides show how a real structural-alignment algorithm compares local fragment pairs, stitches them into paths and evaluates statistical significance.",
        teaching: "Study interpretation: CE is a model example of representation plus search plus statistical evaluation.",
        remember: "CE searches coherent paths through aligned fragment pairs, then uses RMSD, gaps, distance and Z-score-like criteria.",
        trap: "Do not present CE as simply 'calculate RMSD'. The algorithm first builds and optimizes a path of local similarities.",
        prompt: "What are aligned fragment pairs, and why does CE need a path through them?",
      },
      {
        start: 24,
        end: 28,
        title: "PDBeFold: secondary-structure-element graphs",
        intro: "PDBeFold represents proteins as graphs of secondary-structure elements and compares vertices, edges and connectivity rules.",
        teaching: "Study interpretation: this is a different representation of structural similarity: compare the architecture of helices and strands rather than only atom coordinates.",
        remember: "SSE graph matching can provide correspondences between groups of residues.",
        trap: "Do not assume all structural alignment methods operate directly on C-alpha coordinates.",
        prompt: "What is gained and what is lost when a method compares secondary-structure elements instead of all atoms?",
      },
      {
        start: 29,
        end: 33,
        title: "MAMMOTH: unit-vector representation and background scores",
        intro: "The MAMMOTH block represents local protein structure with unit vectors between C-alpha atoms, aligns local vector patterns and evaluates scores against background distributions.",
        teaching: "Study interpretation: the algorithm is fast because it reduces local structure to vectors, but it still needs dynamic programming and statistical calibration.",
        remember: "MAMMOTH = local unit-vector representation + DP alignment + score distribution.",
        trap: "Do not forget the statistical layer; a structural score needs a background distribution.",
        prompt: "Why would unit vectors be useful for comparing protein local structure?",
      },
      {
        start: 34,
        end: 34,
        title: "Protein superimposition exercise",
        intro: "The exercise asks students to build a Biopython script using SVDSuperimposer and cytochrome C structures.",
        teaching: "Study interpretation: this exercise is superimposition, not full alignment, because the user supplies corresponding atoms.",
        remember: "SVD optimizes the rigid-body fit for known corresponding coordinates.",
        trap: "Do not claim the SVD exercise discovers remote homologs; it only fits a supplied correspondence.",
        prompt: "Which part of the slide tells you this is superimposition rather than structural alignment?",
      },
      {
        start: 35,
        end: 42,
        title: "RNA structural alignment: representation, background and optimization",
        intro: "The RNA block introduces primary, secondary and tertiary RNA structure, atom selection, random background distributions, score parameters and SARA optimization.",
        teaching: "Study interpretation: the protein alignment framework transfers to RNA, but the representation and validation metrics must be RNA-specific.",
        remember: "RNA alignment needs atom selection, secondary-structure awareness and length-dependent significance.",
        trap: "Do not copy a protein C-alpha strategy directly onto RNA without changing the structural features.",
        prompt: "Which RNA-specific choices affect structural-alignment accuracy?",
      },
      {
        start: 43,
        end: 48,
        title: "SARA, structure identity and RNA function prediction",
        intro: "These slides compare SARA with other approaches and use structural alignments to infer RNA function from annotated structural databases.",
        teaching: "Study interpretation: the same transfer-of-knowledge logic appears again: structural similarity can support function prediction, but only with significance and validation.",
        remember: "Function assignment depends on alignment quality, p-values and the specificity of the functional label.",
        trap: "Do not transfer RNA function from one good-looking overlay without checking statistical support.",
        prompt: "How does structural alignment support RNA function prediction?",
      },
      {
        start: 49,
        end: 54,
        title: "RNA structural space and the RNA twilight zone",
        intro: "The final slides define RNA structural space, compare sequence, secondary-structure and tertiary-structure identities, show examples and derive an RNA twilight-zone curve.",
        teaching: "Study interpretation: this is the RNA analogue of the protein lesson: sequence identity alone can be weak, while structural and secondary-structure identity may better preserve functional signal.",
        remember: "For RNA, PID, PSS, PSI, RMSD and p-value-like measures must be interpreted together.",
        trap: "Do not assume sequence identity is the best predictor of RNA structural similarity.",
        prompt: "What does the RNA twilight zone add to the general message of structure alignment?",
      },
    ],
  }),
  miniLabs: [
    {
      title: "Superimposition or alignment?",
      goal: "Train the core distinction until it becomes automatic.",
      steps: [
        "Scenario A: you are given two PDB chains plus a list of paired C-alpha atoms. Classify the task.",
        "Scenario B: you are given two unrelated residue-numbering schemes and must discover which residues correspond. Classify the task.",
        "For each scenario, write which step is hard and which score you would report.",
      ],
      output: "Two classifications with one-sentence justifications.",
      check: "A is superimposition; B is structural alignment followed by superimposition.",
      trap: "If your explanation says RMSD before correspondence, the order is wrong.",
    },
    {
      title: "RMSD interpretation drill",
      goal: "Avoid treating RMSD as a standalone truth.",
      steps: [
        "Compare a 1.5 A RMSD over 18 residues with a 2.8 A RMSD over 180 residues.",
        "Write which result may be more biologically meaningful and what extra information you need.",
        "Add one sentence about atom selection: C-alpha only, backbone or all atoms.",
      ],
      output: "A cautious interpretation paragraph.",
      check: "You should ask about alignment length, coverage, domain boundaries, correspondence and statistical significance.",
      trap: "Do not rank alignments by RMSD alone without checking how much structure was aligned.",
    },
    {
      title: "Method classifier",
      goal: "Practice classifying structural-alignment tools by representation and assumptions.",
      steps: [
        "Classify CE as fragment/path-based, PDBeFold as SSE-graph-based, and MAMMOTH as unit-vector/local-structure-based.",
        "For each method, write one thing it can capture well.",
        "For each method, write one possible limitation.",
      ],
      output: "A three-row method comparison table.",
      check: "A good answer names representation, search strategy and statistical evaluation.",
      trap: "Do not describe all tools as interchangeable RMSD calculators.",
    },
    {
      title: "SVDSuperimposer dry run",
      goal: "Connect the deck's exercise to the theory without needing to run code during review.",
      steps: [
        "Choose two structures and decide which atoms are corresponding C-alpha positions.",
        "Center the coordinate sets conceptually, then find the rotation/translation that minimizes squared distances.",
        "Report RMSD and explain that the correspondence was supplied by you.",
      ],
      output: "A workflow checklist for a Biopython superimposition script.",
      check: "The correct wording is: SVD finds the optimal rigid-body fit for a known correspondence.",
      trap: "Do not claim the SVD step discovers remote homologs; it only optimizes the fit.",
    },
    {
      title: "RNA alignment evidence audit",
      goal: "Transfer the protein structure-alignment logic to RNA without copying the wrong features.",
      steps: [
        "List the RNA evidence types: sequence identity, secondary-structure identity, structural identity, RMSD and p-value/significance.",
        "Explain why atom selection matters for RNA.",
        "Write a cautious function-transfer claim for an RNA structural hit.",
      ],
      output: "A short RNA structure-function inference with a caveat.",
      check: "Strong answers mention PID, PSS, PSI or equivalent evidence types.",
      trap: "Do not infer RNA function from sequence identity alone in the twilight-zone region.",
    },
  ],
  checkpoints: [
    {
      question: "What is the difference between structure superimposition and structure alignment?",
      answer: "Superimposition assumes the correspondence between residues or atoms is already known and finds the best rigid-body transformation. Structure alignment must first find the correspondence set, then superimpose and evaluate the match.",
    },
    {
      question: "What does RMSD measure in this context?",
      answer: "RMSD summarizes the average distance between matched atoms or residues after optimal superimposition. It depends on the chosen correspondence, atom set and aligned region.",
    },
    {
      question: "Why can a global rigid alignment be misleading for multi-domain proteins?",
      answer: "Domains can move relative to each other through hinge motion. A whole-chain rigid fit may look poor even when individual domains are structurally similar.",
    },
    {
      question: "What are the three ingredients to mention when describing CE, PDBeFold, MAMMOTH or SARA?",
      answer: "Name the representation, the search/alignment strategy and the statistical evaluation used to judge significance.",
    },
    {
      question: "Why should RNA structural alignment not simply copy protein C-alpha methods?",
      answer: "RNA uses different structural features and atom choices, and secondary-structure identity can be strongly informative for tertiary structural similarity.",
    },
  ],
  modelAnswer: {
    question: "What is the difference between structure superimposition and structure alignment?",
    answer: "Structure superimposition starts from a known correspondence between residues or atoms in two structures. The task is then geometric: find the optimal rigid-body rotation and translation that minimize distances, often summarized by RMSD. Structure alignment is harder because the correspondence is not known in advance. It must first identify which residues or structural elements match, then perform the superimposition and evaluate the result. Therefore, superimposition fits a known mapping, while alignment searches for the mapping and then fits it.",
  },
  sourceNotes: [
    "Primary source: 1-Structure-Alignment.pdf in the Capriotti LB1 Drive folder.",
    "All 54 slide screenshots were extracted from the source PDF and are shown with slide/page labels.",
    "Teaching-emphasis boxes are study interpretations from the slides, not direct transcript quotations.",
  ],
};
