export const lessonContent = {
  id: "lb1-01-structure-alignment",
  extractionStatus: "slide-attached walkthrough from 1-Structure-Alignment.pdf; raster screenshots still pending",
  whyThisMatters: "Structure alignment is one of the cleanest examples of why bioinformatics is not only sequence comparison. Two proteins can keep a similar fold and related function even after their sequences diverge, so structure can reveal relationships that are weak or invisible at the sequence level.",
  objectives: [
    "Define structure superimposition as fitting two structures when the correspondence between atoms or residues is already known.",
    "Define structure alignment as the harder problem of first finding the correspondence set and then optimizing the superimposition.",
    "Explain RMSD as a distance measure after optimal rigid-body transformation.",
    "Distinguish rotation/translation of a rigid body from changing the internal structure of the molecule.",
    "Explain why structural similarity can support homology or family reasoning even at low sequence identity.",
  ],
  coreConcepts: [
    {
      title: "Correspondence set",
      body: "A correspondence set states which residue or atom in structure A is compared to which residue or atom in structure B. Superimposition assumes this mapping; alignment must discover it.",
      keywords: ["mapping", "residue pairs", "hard part"],
    },
    {
      title: "Rigid-body transformation",
      body: "Once correspondence is known, the structures can be rotated and translated to minimize distance. The molecule is not bent or refolded; only its position in space changes.",
      keywords: ["rotation", "translation", "no deformation"],
    },
    {
      title: "RMSD",
      body: "Root-mean-square deviation summarizes the average distance between matched points after superimposition. It is meaningful only relative to the chosen correspondence and structural region.",
      keywords: ["distance", "matched points", "region"],
    },
    {
      title: "Structure alignment",
      body: "Structure alignment searches for the correspondence that gives a biologically meaningful structural match, then evaluates the fit. This is harder than superimposition because the mapping is unknown.",
      keywords: ["search", "correspondence", "fit"],
    },
  ],
  routeSteps: [
    {
      title: "First ask: do I know which residues correspond?",
      body: "If yes, the problem is superimposition. If no, the problem is alignment, and correspondence search becomes central.",
    },
    {
      title: "Then optimize the spatial fit",
      body: "Use a rigid-body transformation to place the structures in the same coordinate frame without changing their internal geometry.",
    },
    {
      title: "Finally interpret the score",
      body: "RMSD and structural overlap are evidence. They must be interpreted with alignment length, domain boundaries and biological context.",
    },
  ],
  walkthroughSections: [
    {
      range: "Slides 1-8",
      title: "The first distinction: superimposition is not alignment",
      intro: "The most important exam-safe distinction is whether the residue/atom correspondence is already known.",
      slides: [
        {
          label: "Core definition",
          page: 3,
          deckLabel: "1-Structure-Alignment.pdf",
          slideTitle: "Structure superimposition",
          slideBullets: ["Two coordinate sets", "Known correspondence", "Optimal rigid-body transformation", "RMSD after fitting"],
          title: "Superimposition assumes known correspondence",
          comment: "If you already know which residues or atoms should be compared, the task is to find the best rigid-body transformation that places one structure over the other.",
          teaching: "Study interpretation: superimposition is a geometry optimization after the biological mapping has already been chosen.",
          remember: "Known correspondence first; then rotation/translation; then RMSD.",
          trap: "Do not say superimposition discovers the alignment. It fits structures after the correspondence is given.",
          prompt: "What information must be known before superimposing two structures?",
        },
        {
          label: "Core definition",
          page: 6,
          deckLabel: "1-Structure-Alignment.pdf",
          slideTitle: "Structural alignment",
          slideBullets: ["Find an optimal correspondence set", "Then compute the alignment transform", "Correspondence search is the hard part"],
          title: "Alignment must find the correspondence first",
          comment: "Structure alignment is harder because it must decide which residues or structural elements correspond, often across proteins with insertions, deletions or low sequence identity.",
          teaching: "Study interpretation: the computational difficulty is the search over possible correspondences, not merely drawing two structures on top of each other.",
          remember: "Unknown correspondence first; search for matching regions; then superimpose and evaluate.",
          trap: "Do not treat a low RMSD as meaningful if it comes from a tiny or cherry-picked region.",
          prompt: "Why is structure alignment harder than superimposition?",
        },
        {
          label: "Exam contrast",
          page: 8,
          deckLabel: "1-Structure-Alignment.pdf",
          slideTitle: "Superimposition vs alignment",
          slideBullets: ["Superimposition: atoms are already selected", "Alignment: atoms/residues must be determined", "Position optimization is simpler than correspondence search"],
          title: "The deck explicitly separates the two tasks",
          comment: "The slide's contrast is the sentence to memorize: superimposition optimizes position for a known set of matched atoms; alignment must identify that matched set first.",
          teaching: "Study interpretation: in an oral exam, say the contrast before you talk about RMSD.",
          remember: "Fit a known mapping versus search for the mapping.",
          trap: "Calling every 3D comparison a 'superimposition' loses the key algorithmic difficulty.",
          prompt: "Give a two-sentence definition of both terms without using them as synonyms.",
        },
      ],
    },
    {
      range: "Slides 3-7",
      title: "How the fit is evaluated",
      intro: "Once residue pairs are fixed, the structures are placed in the same coordinate frame and their distance can be summarized.",
      slides: [
        {
          label: "Transformation",
          page: 4,
          deckLabel: "1-Structure-Alignment.pdf",
          slideTitle: "Y = G(X) = A*X + B",
          slideBullets: ["A is the rotation matrix", "B is the translation vector", "The structure is moved as a rigid object"],
          title: "Rigid-body transformation preserves internal geometry",
          comment: "The optimal transformation rotates and translates one coordinate set relative to the other. It does not stretch helices, move side chains independently or change the protein fold.",
          teaching: "Study interpretation: imagine moving a physical model in your hand, not reshaping it.",
          remember: "Rigid-body means the structure is moved as a whole.",
          trap: "If an answer implies the algorithm changes the protein shape to improve the score, it is describing the wrong operation.",
        },
        {
          label: "RMSD",
          page: 5,
          deckLabel: "1-Structure-Alignment.pdf",
          slideTitle: "Root mean square deviation",
          slideBullets: ["Distance over matched points", "Computed after optimal transformation", "Depends on atom selection and alignment length"],
          title: "RMSD depends on what you compare",
          comment: "RMSD is computed over matched positions after the optimal transformation. Its value depends on the selected atoms, aligned residues and length of the aligned region.",
          teaching: "Study interpretation: RMSD is compact, but not self-sufficient. Always ask: over which correspondence and how much of the structure?",
          remember: "RMSD is a fit summary, not an automatic biological conclusion.",
          prompt: "Why should RMSD be interpreted together with alignment length and correspondence?",
        },
      ],
    },
    {
      range: "Slides 9-17",
      title: "From coordinates to comparison algorithms",
      intro: "After the definitions, the deck broadens the question: what features do algorithms compare, and how do they decide a match is significant?",
      slides: [
        {
          label: "Comparison pipeline",
          page: 9,
          deckLabel: "1-Structure-Alignment.pdf",
          slideTitle: "Structures comparison",
          slideBullets: ["Feature extraction", "Algorithm", "Statistical significance", "Score"],
          title: "Structure comparison is a pipeline",
          comment: "A method first represents structures through features, then aligns or compares those features, assigns a score and finally asks whether the score is meaningful.",
          teaching: "Study interpretation: always identify what the method compares: C-alpha atoms, all atoms, secondary-structure elements, contact maps, surfaces or descriptors.",
          remember: "The representation controls what the algorithm can see.",
          trap: "Do not compare method scores as if all tools used the same features and assumptions.",
          prompt: "Why does feature choice matter in structure comparison?",
        },
        {
          label: "Domains and flexibility",
          page: 11,
          deckLabel: "1-Structure-Alignment.pdf",
          slideTitle: "Level of comparison / multi-domain alignment",
          slideBullets: ["Domains can be independently stable units", "Multi-domain proteins can move by hinges", "Flexible movement complicates global RMSD"],
          title: "Global alignment can hide domain movement",
          comment: "The deck uses domains and multi-domain examples to show that one rigid global fit may not describe flexible proteins well.",
          teaching: "Study interpretation: if two domains move relative to each other, a high global RMSD may reflect hinge motion rather than loss of domain similarity.",
          remember: "Choose the level of comparison: residue, domain, whole chain or complex.",
          trap: "Do not conclude two proteins are unrelated because a whole-chain rigid fit is poor.",
        },
        {
          label: "Method families",
          page: 15,
          deckLabel: "1-Structure-Alignment.pdf",
          slideTitle: "Structural alignment tools",
          slideBullets: ["Flexible or rigid", "Pairwise or multiple", "C-alpha, all atoms, SSE, contact maps, torsion angles, surfaces"],
          title: "There is no single structure-alignment method",
          comment: "The deck lists many possible algorithmic choices. The practical point is that tools differ because they encode different assumptions about what similarity means.",
          teaching: "Study interpretation: learn the categories rather than memorizing a catalog of tool names.",
          remember: "Method choice follows the biological question and the expected structural change.",
          prompt: "When would a flexible method be more appropriate than a rigid one?",
        },
      ],
    },
    {
      range: "Slides 18-32",
      title: "Descriptors, algorithms and significance",
      intro: "The later part of the deck shows concrete ways to represent structures and search for alignments.",
      slides: [
        {
          label: "Torsion angles",
          page: 18,
          deckLabel: "1-Structure-Alignment.pdf",
          slideTitle: "Comparing torsion angles",
          slideBullets: ["Local structural descriptor", "Invariant to rotation and translation", "Compact O(n)", "Can miss whole-structure relationships"],
          title: "Local descriptors are useful but limited",
          comment: "Torsion angles describe local backbone geometry and avoid the need for global coordinate superposition, but local similarity does not always solve whole-structure comparison.",
          teaching: "Study interpretation: ask whether the descriptor captures the biological level you care about.",
          remember: "Invariant descriptors remove coordinate-frame problems, not biological interpretation problems.",
          trap: "Do not assume a compact descriptor captures every aspect of 3D similarity.",
        },
        {
          label: "Distance matrix",
          page: 19,
          deckLabel: "1-Structure-Alignment.pdf",
          slideTitle: "Distance matrix",
          slideBullets: ["Rotation/translation invariant", "Pairwise residue distances", "O(n^2)", "Insensitive to chirality"],
          title: "Distance matrices compare internal geometry",
          comment: "A distance matrix stores distances between residues inside a structure. It is naturally invariant to where the molecule sits in space, but comparing matrices is computationally heavier.",
          teaching: "Study interpretation: this is another way to avoid coordinate-frame dependence while still comparing structure.",
          remember: "Distance matrices preserve internal distances, not atom labels by themselves.",
          prompt: "What is the benefit of using a distance matrix instead of raw coordinates?",
        },
        {
          label: "Algorithm input-output",
          page: 21,
          deckLabel: "1-Structure-Alignment.pdf",
          slideTitle: "Input/output of an alignment algorithm",
          slideBullets: ["Input: proteins and constraints", "Output: alignment and scores", "Constraints can include gap limits, RMSD and aligned length"],
          title: "Algorithms search under constraints",
          comment: "The deck describes structure alignment as an optimization problem with inputs, constraints, an alignment output and scores that must be interpreted.",
          teaching: "Study interpretation: constraints are not decoration; they control what counts as an acceptable alignment.",
          remember: "An alignment result is produced under specific constraints and scoring choices.",
          trap: "Do not compare two alignments without checking whether they used the same constraints.",
        },
        {
          label: "CE and MAMMOTH",
          page: 25,
          deckLabel: "1-Structure-Alignment.pdf",
          slideTitle: "CE algorithm / MAMMOTH algorithm",
          slideBullets: ["CE stitches aligned fragment pairs", "Dynamic programming searches an optimal path", "MAMMOTH uses unit-vector representations", "Scores need background distributions"],
          title: "Real tools combine representation, search and statistics",
          comment: "CE and MAMMOTH are examples of complete algorithms: define local structural units, search for a coherent alignment and evaluate whether the result is significant.",
          teaching: "Study interpretation: you do not need to rederive each algorithm, but you should explain what kind of structural signal it uses.",
          remember: "A tool is representation plus search strategy plus statistical evaluation.",
          prompt: "What three ingredients should you mention when describing a structural alignment tool?",
        },
      ],
    },
    {
      range: "Exercise and RNA slides",
      title: "Practice and extension beyond proteins",
      intro: "The deck ends by turning the concept into an exercise and extending the same alignment logic to RNA structures.",
      slides: [
        {
          label: "Python exercise",
          page: 33,
          deckLabel: "1-Structure-Alignment.pdf",
          slideTitle: "Structure superimposition exercise",
          slideBullets: ["Use Biopython SVDSuperimposer", "Select corresponding atoms", "Compute rotation/translation", "Read RMSD"],
          title: "The exercise is superimposition, not full alignment",
          comment: "The proposed script uses known corresponding coordinates and computes the best fit. That is exactly the superimposition case from the first slides.",
          teaching: "Study interpretation: this exercise is a perfect way to test whether you understand the definitions.",
          remember: "If you provide atom pairs, SVD solves the fit. It does not discover biological correspondence for you.",
          trap: "Do not present the exercise as if it implemented a full structural alignment algorithm.",
        },
        {
          label: "RNA structures",
          page: 38,
          deckLabel: "1-Structure-Alignment.pdf",
          slideTitle: "RNA structural alignment",
          slideBullets: ["Primary, secondary and tertiary RNA structure", "Atom selection matters", "RNA has its own twilight-zone behavior", "SARA is one example tool"],
          title: "The same principles apply to RNA with different features",
          comment: "RNA alignment still needs representation, correspondence, scoring and significance, but the relevant structural features are not identical to protein C-alpha comparisons.",
          teaching: "Study interpretation: transfer the conceptual framework, not the protein-specific details.",
          remember: "Structure-alignment logic generalizes; feature choice is molecule-specific.",
          prompt: "Why should RNA structure alignment not simply copy a protein C-alpha strategy?",
        },
      ],
    },
    {
      range: "Biological interpretation",
      title: "Why structure can reveal relationships sequence misses",
      intro: "Structure is often more conserved than sequence. This makes structure alignment valuable for distant relationships, but it does not remove the need for careful interpretation.",
      slides: [
        {
          label: "Low sequence identity",
          page: 10,
          deckLabel: "1-Structure-Alignment.pdf",
          slideTitle: "Structural similarity under low sequence identity",
          slideBullets: ["Fold can remain conserved", "Functional sites may be preserved", "Evidence depends on aligned region and significance"],
          title: "Similar folds can survive sequence divergence",
          comment: "Proteins can accumulate many substitutions while preserving a fold or active-site geometry. Structural alignment can therefore detect family or homology relationships that pairwise sequence identity alone may miss.",
          teaching: "Study interpretation: this is a transfer-of-knowledge argument, so state the evidence and its limits.",
          remember: "Structure similarity is strong evidence when it covers the relevant domain and functionally important regions.",
          trap: "Do not claim same fold always means same precise function.",
          prompt: "Given two proteins with similar fold but low sequence identity, why can structure alignment still detect homology or family relationships?",
        },
      ],
    },
  ],
  miniLabs: [
    {
      title: "Superimposition or alignment?",
      goal: "Train the core distinction until it becomes automatic.",
      steps: [
        "Scenario A: you are given two PDB chains plus a list of paired C-alpha atoms. Classify the task.",
        "Scenario B: you are given two unrelated residue-numbering schemes and must discover which residues correspond. Classify the task.",
        "For each scenario, write which step is hard and which score you would report.",
      ],
      output: "Two classifications with one-sentence justifications.",
      check: "A is superimposition; B is structural alignment followed by superimposition.",
      trap: "If your explanation says RMSD before correspondence, the order is wrong.",
    },
    {
      title: "RMSD interpretation drill",
      goal: "Avoid treating RMSD as a standalone truth.",
      steps: [
        "Compare a 1.5 A RMSD over 18 residues with a 2.8 A RMSD over 180 residues.",
        "Write which result may be more biologically meaningful and what extra information you need.",
        "Add one sentence about atom selection: C-alpha only, backbone or all atoms.",
      ],
      output: "A cautious interpretation paragraph.",
      check: "You should ask about alignment length, coverage, domain boundaries, correspondence and statistical significance.",
      trap: "Do not rank alignments by RMSD alone without checking how much structure was aligned.",
    },
    {
      title: "SVDSuperimposer dry run",
      goal: "Connect the deck's exercise to the theory without needing to run code during review.",
      steps: [
        "Choose two structures and decide which atoms are corresponding C-alpha positions.",
        "Center the coordinate sets conceptually, then find the rotation/translation that minimizes squared distances.",
        "Report RMSD and explain that the correspondence was supplied by you.",
      ],
      output: "A workflow checklist for a Biopython superimposition script.",
      check: "The correct wording is: SVD finds the optimal rigid-body fit for a known correspondence.",
      trap: "Do not claim the SVD step discovers remote homologs; it only optimizes the fit.",
    },
    {
      title: "Pick a structure descriptor",
      goal: "Practice choosing a method feature from the biological problem.",
      steps: [
        "For a local motif question, choose torsion angles, local fragments or active-site geometry.",
        "For a fold-level comparison, choose C-alpha coordinates, distance matrices or secondary-structure arrangements.",
        "For flexible multi-domain proteins, explain why a single global rigid fit may be misleading.",
      ],
      output: "Three method choices with one reason each.",
      check: "The representation should match the scale of the question.",
    },
  ],
  checkpoints: [
    {
      question: "What is the difference between structure superimposition and structure alignment?",
      answer: "Superimposition assumes the correspondence between residues or atoms is already known and finds the best rigid-body transformation. Structure alignment must first find the correspondence set, then superimpose and evaluate the match.",
    },
    {
      question: "What does RMSD measure in this context?",
      answer: "RMSD summarizes the average distance between matched atoms or residues after optimal superimposition. It depends on the chosen correspondence, atom set and aligned region.",
    },
    {
      question: "Why is a rigid-body transformation important?",
      answer: "It means the structure is only rotated and translated as a whole. The algorithm is not changing the internal geometry of the molecule to artificially improve the fit.",
    },
    {
      question: "Why can structure alignment detect relationships at low sequence identity?",
      answer: "Protein folds and functional geometries can be more conserved than primary sequence. If the aligned region is meaningful, structural similarity can support family or homology inference even after sequence divergence.",
    },
  ],
  modelAnswer: {
    question: "What is the difference between structure superimposition and structure alignment?",
    answer: "Structure superimposition starts from a known correspondence between residues or atoms in two structures. The task is then geometric: find the optimal rigid-body rotation and translation that minimize distances, often summarized by RMSD. Structure alignment is harder because the correspondence is not known in advance. It must first identify which residues or structural elements match, then perform the superimposition and evaluate the result. Therefore, superimposition fits a known mapping, while alignment searches for the mapping and then fits it.",
  },
  sourceNotes: [
    "Primary source: 1-Structure-Alignment.pdf in the Capriotti LB1 Drive folder.",
    "Teaching-emphasis boxes are study interpretations from the slide topic and requested course focus, not direct professor quotations.",
    "Slide cards are attached to the source PDF with slide/page labels. Local raster screenshots are still a follow-up because no PDF rasterizer is available in this workspace.",
  ],
};
