export const lessonContent = {
  id: "amla-2026-05-15-cnn-practice",
  extractionStatus: "source-based complete draft",
  objectives: [
    "Explain ensemble learning as aggregating multiple predictors instead of trusting one model.",
    "Distinguish hard voting, soft voting and the conditions needed for soft voting.",
    "Explain why diversity and uncorrelated errors are essential for ensemble gains.",
    "Compare bagging and pasting, including sampling with versus without replacement.",
    "Describe random forests as optimized bagged decision-tree ensembles with extra feature randomness.",
    "Explain AdaBoost and Gradient Boosting as sequential methods that correct previous mistakes.",
    "Recognize XGBoost as a powerful gradient-boosting implementation with many hyperparameters.",
  ],
  coreConcepts: [
    {
      title: "Ensemble",
      body: "A group of predictors whose outputs are aggregated to produce a final prediction.",
      keywords: ["crowd", "aggregation", "predictors"],
    },
    {
      title: "Hard voting",
      body: "Each classifier votes for one class. The class with the majority of votes wins.",
      keywords: ["majority", "classification", "simple aggregation"],
    },
    {
      title: "Soft voting",
      body: "Class probabilities are averaged, so more confident predictions influence the final class more.",
      keywords: ["predict_proba", "confidence", "probabilities"],
    },
    {
      title: "Diversity",
      body: "Ensembles improve most when predictors make different, uncorrelated errors.",
      keywords: ["independence", "uncorrelated errors", "team"],
    },
    {
      title: "Bagging",
      body: "The same algorithm is trained many times on random samples with replacement.",
      keywords: ["bootstrap", "replacement", "parallel"],
    },
    {
      title: "Pasting",
      body: "Like bagging, but random samples are drawn without replacement.",
      keywords: ["no replacement", "subsets", "parallel"],
    },
    {
      title: "Random forest",
      body: "An ensemble of decision trees trained with bagging-style sampling plus extra randomness in feature selection.",
      keywords: ["decision trees", "feature importance", "variance"],
    },
    {
      title: "Boosting",
      body: "A sequential ensemble strategy where each new predictor tries to fix what previous predictors missed.",
      keywords: ["AdaBoost", "Gradient Boosting", "sequential"],
    },
    {
      title: "XGBoost",
      body: "A fast, scalable gradient-boosted tree implementation that is powerful but hyperparameter-heavy.",
      keywords: ["GBRT", "competitions", "regularization"],
    },
  ],
  walkthroughSections: [
    {
      range: "Module 1 / Lecture6 slides 1-9",
      title: "Voting ensembles: the wisdom of a diverse crowd",
      intro: "The class begins with the simplest ensemble idea: combine several decent predictors and let the group decide.",
      slides: [
        {
          label: "Slide 1",
          deckLabel: "Module 1 / Lecture6",
          page: 1,
          image: "amla-slides/module1-lecture6/slide-01.png",
          title: "Lecture frame",
          comment: "The date and deck title match the 2026-05-15 transcript. The main class content is ensemble learning.",
          professor: "The professor had a meeting at 4 p.m., so he focused the session and stopped after boosting rather than expanding the final stacking/hands-on part.",
          remember: "Module2 Lecture0 is linked as an extra resource, but the transcripted class is ensemble learning.",
        },
        {
          label: "Slide 3",
          deckLabel: "Module 1 / Lecture6",
          page: 3,
          image: "amla-slides/module1-lecture6/slide-03.png",
          title: "Wisdom of the crowd",
          comment: "The ensemble idea is pragmatic: train multiple predictors and aggregate their predictions instead of betting everything on one model.",
          professor: "He framed it as a group of experts being wiser than one expert, especially when each expert sees the problem differently.",
          remember: "An ensemble is useful because different predictors can cover each other's mistakes.",
        },
        {
          label: "Slide 5",
          deckLabel: "Module 1 / Lecture6",
          page: 5,
          image: "amla-slides/module1-lecture6/slide-05.png",
          title: "Hard voting",
          comment: "Hard voting counts predicted classes. Each model gets one vote, and the majority class becomes the ensemble prediction.",
          professor: "He used logistic regression, SVC and random forest as examples of diverse classifiers that can be placed in one voting ensemble.",
          remember: "Hard voting uses labels, not probabilities.",
        },
        {
          label: "Slide 6",
          deckLabel: "Module 1 / Lecture6",
          page: 6,
          image: "amla-slides/module1-lecture6/slide-06.png",
          title: "Better than the best single model?",
          comment: "A voting classifier can beat the best individual classifier when learners are sufficiently diverse and their errors are not correlated.",
          professor: "He used the biased-coin and student-test analogies to explain how many slightly better-than-random predictors can become a strong learner.",
          remember: "The magic is not averaging alone; it is diversity plus uncorrelated errors.",
          trap: "Adding many copies of the same flawed model does not create the same benefit.",
        },
        {
          label: "Slide 7",
          deckLabel: "Module 1 / Lecture6",
          page: 7,
          image: "amla-slides/module1-lecture6/slide-07.png",
          title: "VotingClassifier in sklearn",
          comment: "The code fits individual classifiers and the voting ensemble, then compares accuracy. The ensemble slightly beats the best component.",
          professor: "He pointed out that random forest is already an ensemble, so ensembles can be nested inside larger ensembles.",
          remember: "In sklearn, the voting classifier stores named estimators and a `voting` mode.",
        },
        {
          label: "Slides 8-9",
          deckLabel: "Module 1 / Lecture6",
          page: 9,
          image: "amla-slides/module1-lecture6/slide-09.png",
          title: "Soft voting",
          comment: "Soft voting averages class probabilities. It requires every classifier to expose `predict_proba()`.",
          professor: "He corrected the flow of the code/slides: the hard-voting code appears first, and changing `voting='soft'` is the key modification.",
          remember: "For SVC, probability estimates require `probability=True`, which slows training because probabilities are estimated with cross-validation.",
          trap: "Soft voting is unavailable if one selected classifier cannot produce class probabilities.",
        },
      ],
      lab: {
        title: "Mini-lab: hard versus soft voting",
        todo: "The source slide names `..HandsOn_Ensemble.ipynb`, but the extracted sources did not expose a standalone Colab/Drive URL.",
        objective: "Compare individual classifiers, hard voting and soft voting on the same dataset.",
        steps: [
          "Train logistic regression, random forest and SVC on a small classification dataset.",
          "Build a `VotingClassifier` with `voting='hard'`.",
          "Enable probability estimates where needed and switch to `voting='soft'`.",
          "Compare component accuracy with ensemble accuracy.",
        ],
        parameters: ["voting mode", "SVC probability", "classifier list"],
        outputs: ["accuracy per classifier", "hard voting accuracy", "soft voting accuracy"],
        explain: [
          "Why soft voting can improve over hard voting.",
          "Why diverse classifiers matter.",
          "Why an ensemble can still fail if all models make the same errors.",
        ],
      },
    },
    {
      range: "Module 1 / Lecture6 slides 10-16",
      title: "Bagging, pasting and random forests reduce variance",
      intro: "Voting combines different algorithms. Bagging/pasting often use the same algorithm many times, but change the sampled training data.",
      slides: [
        {
          label: "Slide 11",
          deckLabel: "Module 1 / Lecture6",
          page: 11,
          image: "amla-slides/module1-lecture6/slide-11.png",
          title: "Bagging versus pasting",
          comment: "Bagging samples with replacement; pasting samples without replacement. Both train many predictors on different random subsets.",
          professor: "He described this as voting over random slices of the data rather than voting over different algorithms.",
          remember: "Bagging = bootstrap aggregation = replacement. Pasting = no replacement.",
        },
        {
          label: "Slide 12",
          deckLabel: "Module 1 / Lecture6",
          page: 12,
          image: "amla-slides/module1-lecture6/slide-12.png",
          title: "BaggingClassifier setup",
          comment: "`n_estimators`, `max_samples`, `bootstrap` and `n_jobs` control the ensemble size, sample size, replacement and parallelism.",
          professor: "He emphasized that bagging and pasting can train in parallel, which is one reason they scale well.",
          remember: "`bootstrap=False` turns bagging into pasting.",
        },
        {
          label: "Slide 13",
          deckLabel: "Module 1 / Lecture6",
          page: 13,
          image: "amla-slides/module1-lecture6/slide-13.png",
          title: "Bias-variance effect",
          comment: "A bagging ensemble of decision trees has similar bias but lower variance than one tree, producing a smoother boundary.",
          professor: "He used this to explain why a collection of unstable learners can generalize better.",
          remember: "Bagging is especially useful for high-variance predictors such as decision trees.",
        },
        {
          label: "Slide 14",
          deckLabel: "Module 1 / Lecture6",
          page: 14,
          image: "amla-slides/module1-lecture6/slide-14.png",
          title: "Out-of-bag evaluation",
          comment: "With replacement sampling, about 37% of instances are left out for a given predictor. Those out-of-bag examples can estimate performance.",
          professor: "He spent time on the 63/37 idea: sampled subsets differ per predictor, so OOB examples form a useful internal evaluation signal.",
          remember: "`oob_score=True` can evaluate the ensemble without a separate validation split.",
        },
        {
          label: "Slide 15",
          deckLabel: "Module 1 / Lecture6",
          page: 15,
          image: "amla-slides/module1-lecture6/slide-15.png",
          title: "Random forests",
          comment: "A random forest is a bagged ensemble of decision trees with extra randomness in feature selection at splits.",
          professor: "He said to use `RandomForestClassifier` directly instead of manually building the same thing from lower-level bagging blocks.",
          remember: "Random forests trade a bit more bias for lower variance and better generalization.",
        },
        {
          label: "Slide 16",
          deckLabel: "Module 1 / Lecture6",
          page: 16,
          image: "amla-slides/module1-lecture6/slide-16.png",
          title: "Feature importance",
          comment: "Random forests can estimate feature importance by averaging how much tree splits using each feature reduce impurity.",
          professor: "He said feature importance can be useful even if the final model is not random forest, because it reveals which variables or pixels carry signal.",
          remember: "Random forests are both predictors and exploratory tools for feature relevance.",
        },
      ],
      lab: {
        title: "Mini-lab: bagging tree versus one tree",
        todo: "Use the ensemble notebook named on slide 41 when available; no standalone URL was exposed in the extracted sources.",
        objective: "See how bagging changes variance while keeping the base model simple.",
        steps: [
          "Fit one decision tree to a noisy two-class dataset.",
          "Fit a bagging ensemble with many decision trees.",
          "Compare decision boundaries.",
          "Enable OOB evaluation and compare it with validation accuracy.",
          "Train a random forest and inspect feature importances.",
        ],
        parameters: ["n_estimators", "max_samples", "bootstrap", "oob_score", "max_features"],
        outputs: ["decision boundary", "OOB score", "feature importance plot"],
        explain: [
          "Why bagging lowers variance.",
          "Why OOB examples can be used for evaluation.",
          "Why random forest adds feature-level randomness.",
        ],
      },
    },
    {
      range: "Module 1 / Lecture6 slides 17-28",
      title: "Boosting: sequential correction instead of parallel averaging",
      intro: "Boosting is the second major family in the lecture. It often performs extremely well, but it is sequential and can overfit if pushed too far.",
      slides: [
        {
          label: "Slide 18",
          deckLabel: "Module 1 / Lecture6",
          page: 18,
          image: "amla-slides/module1-lecture6/slide-18.png",
          title: "Boosting concept",
          comment: "Boosting trains weak learners sequentially. Each new learner focuses on correcting what previous learners missed.",
          professor: "He contrasted this with bagging: bagging/pasting can be parallel; boosting is conceptually sequential.",
          remember: "Boosting improves along a chain, not by independent parallel models.",
        },
        {
          label: "Slide 19",
          deckLabel: "Module 1 / Lecture6",
          page: 19,
          image: "amla-slides/module1-lecture6/slide-19.png",
          title: "AdaBoost",
          comment: "AdaBoost increases the relative weight of misclassified training instances so later classifiers focus more on hard cases.",
          professor: "He used the word adaptive: the algorithm adapts by changing instance weights based on previous mistakes.",
          remember: "AdaBoost = reweight difficult examples.",
        },
        {
          label: "Slides 20-23",
          deckLabel: "Module 1 / Lecture6",
          page: 23,
          image: "amla-slides/module1-lecture6/slide-23.png",
          title: "Gradient Boosting",
          comment: "Gradient Boosting adds predictors that fit residual errors left by the current ensemble. Predictions are summed across trees.",
          professor: "He explained it as learning from the deltas: what the previous predictor did not explain becomes the next training target.",
          remember: "Gradient Boosting = fit residuals sequentially.",
        },
        {
          label: "Slide 24",
          deckLabel: "Module 1 / Lecture6",
          page: 24,
          image: "amla-slides/module1-lecture6/slide-24.png",
          title: "Learning rate and early stopping",
          comment: "Lower learning rate means each tree contributes less, often requiring more trees but improving generalization. Too many trees can overfit.",
          professor: "He pointed at the visual overfit: when boosting is pushed too far, the curve starts following noise and detail.",
          remember: "Tune learning rate and number of estimators together; use validation/early stopping.",
        },
        {
          label: "Slides 25-27",
          deckLabel: "Module 1 / Lecture6",
          page: 27,
          image: "amla-slides/module1-lecture6/slide-27.png",
          title: "XGBoost",
          comment: "XGBoost is a fast, scalable implementation of gradient boosted trees, very strong for tabular ML competitions.",
          professor: "He called it the strongest non-neural-network 'small beast': powerful, but hard to drive because hyperparameters are intimidating.",
          remember: "Start with a small set of XGBoost hyperparameters before expanding the search.",
          trap: "Do not grid-search every XGBoost hyperparameter blindly.",
        },
        {
          label: "Slide 28",
          deckLabel: "Module 1 / Lecture6",
          page: 28,
          image: "amla-slides/module1-lecture6/slide-28.png",
          title: "Bagging versus boosting summary",
          comment: "The visual summary separates parallel variance-reduction logic from sequential error-correction logic.",
          professor: "He said they would stop before going through the remaining visual summary in detail, but the contrast is still useful.",
          remember: "Bagging: parallel/random subsets/lower variance. Boosting: sequential/errors/residuals/high performance.",
        },
      ],
      lab: {
        title: "Mini-lab: Gradient Boosting tuning intuition",
        todo: "Slide 41 names `..HandsOn_Ensemble.ipynb`, but the extracted sources did not expose a standalone Colab/Drive URL.",
        objective: "See how residual fitting, learning rate and estimator count interact.",
        steps: [
          "Fit one shallow tree regressor to a noisy nonlinear dataset.",
          "Fit a second tree on residuals and then a third on new residuals.",
          "Compare manual residual-sum predictions with a GradientBoosting model.",
          "Lower learning rate and increase `n_estimators`.",
          "Use validation or early stopping to avoid too many trees.",
        ],
        parameters: ["learning_rate", "n_estimators", "max_depth", "early stopping"],
        outputs: ["prediction curves", "validation error", "overfit/underfit comparison"],
        explain: [
          "Why Gradient Boosting cannot be fully parallelized.",
          "Why residuals are the new target.",
          "Why XGBoost is powerful but hyperparameter-heavy.",
        ],
      },
    },
    {
      range: "Module 1 / Lecture6 slides 29-41 and Module 2 / Lecture0 slides 1-5",
      title: "Stacking and the linked hands-on resources",
      intro: "The final slides mostly act as reference material. Stacking is introduced, but the professor stopped before walking through it deeply.",
      slides: [
        {
          label: "Slides 29-34",
          deckLabel: "Module 1 / Lecture6",
          page: 32,
          image: "amla-slides/module1-lecture6/slide-32.png",
          title: "Visual summary questions",
          comment: "These slides compare ensemble families by number of learners, bias/variance behavior, data use, training flow and classification mechanism.",
          professor: "He explicitly said they did not need the visual summary in detail at the end because of time.",
          remember: "Use this as a review grid after studying voting, bagging and boosting.",
        },
        {
          label: "Slides 36-38",
          deckLabel: "Module 1 / Lecture6",
          page: 38,
          image: "amla-slides/module1-lecture6/slide-38.png",
          title: "Stacking",
          comment: "Stacking trains a final meta-learner, or blender, on the predictions of earlier learners instead of using a simple vote or average.",
          professor: "He originally said stacking would be mostly a reference because it is more convoluted than voting, bagging and boosting.",
          remember: "Stacking = learn how to combine predictions.",
        },
        {
          label: "Slides 39-41",
          deckLabel: "Module 1 / Lecture6",
          page: 41,
          image: "amla-slides/module1-lecture6/slide-41.png",
          title: "Hands-on ensemble notebook",
          comment: "The deck names `..HandsOn_Ensemble.ipynb` and says to practice on the notebook.",
          professor: "Near the end he said the notebook was already in the repo and encouraged students to experiment with ensemble methods.",
          remember: "Practice matters here: many ensemble choices are best understood by comparing curves and metrics.",
        },
        {
          label: "Module 2 / Lecture0 slides 1-5",
          deckLabel: "Module 2 / Lecture0",
          deck: "extraSlides",
          page: 3,
          image: "amla-slides/module2-lecture0/slide-03.png",
          title: "Complementary Module 2 setup deck",
          comment: "This short deck contains course structure and Python-intro information from Luca, but it was not the main content of the 2026-05-15 transcript.",
          professor: "The transcript says Luca would continue with other parts later. Treat this as linked administrative/setup material.",
          remember: "Keep Module2 Lecture0 visible as a resource, but do not study it as the ensemble-learning lecture.",
        },
      ],
    },
  ],
  professorEmphasis: [
    "Voting, bagging and boosting were the main focus; stacking was left mostly as a reference.",
    "An ensemble is strongest when its members are diverse and do not make the same errors.",
    "Hard voting counts labels; soft voting averages probabilities and requires `predict_proba()`.",
    "Bagging and pasting are popular partly because they can be parallelized.",
    "Bagging with decision trees lowers variance and smooths unstable decision boundaries.",
    "Random forests are convenient, optimized and useful for feature importance.",
    "Boosting is powerful but sequential, so it does not scale as naturally as bagging.",
    "XGBoost is a very strong non-neural-network tool, but its hyperparameter space can be difficult to control.",
  ],
  commonTraps: [
    "Assuming an ensemble always improves performance regardless of member diversity.",
    "Confusing hard voting with soft voting.",
    "Using soft voting with a classifier that cannot estimate probabilities.",
    "Mixing up bagging and pasting: replacement versus no replacement.",
    "Forgetting that OOB examples are not the same for every predictor.",
    "Thinking random forest is just one decision tree with randomness.",
    "Treating AdaBoost and Gradient Boosting as identical because both are sequential.",
    "Pushing boosting with too many trees and ignoring overfitting.",
    "Blindly tuning all XGBoost hyperparameters at once.",
  ],
  quickQuiz: [
    {
      question: "Why can an ensemble outperform its best individual member?",
      answer: "Because different learners may be wrong on different instances. Aggregation can preserve correct signals if errors are sufficiently uncorrelated.",
    },
    {
      question: "What is hard voting?",
      answer: "A majority vote over predicted class labels.",
    },
    {
      question: "What extra requirement does soft voting have?",
      answer: "Every classifier must provide class probabilities, typically through `predict_proba()`.",
    },
    {
      question: "What is the difference between bagging and pasting?",
      answer: "Bagging samples with replacement; pasting samples without replacement.",
    },
    {
      question: "Why can OOB evaluation work in bagging?",
      answer: "Each predictor leaves out some training instances during bootstrap sampling, so those unseen instances can evaluate that predictor.",
    },
    {
      question: "What extra randomness does a random forest add?",
      answer: "At each split, it searches among a random subset of features rather than all features.",
    },
    {
      question: "How does AdaBoost focus on hard cases?",
      answer: "It increases the weights of misclassified instances so later learners pay more attention to them.",
    },
    {
      question: "What does Gradient Boosting fit at each stage?",
      answer: "The residual errors left by the current ensemble.",
    },
    {
      question: "Why is XGBoost powerful but tricky?",
      answer: "It is fast and highly optimized, but it exposes many hyperparameters that can overfit or make search explode.",
    },
  ],
  examQuestions: [
    {
      id: "l08-mcq-1",
      question: "A voting ensemble contains five classifiers that all make the same mistakes on the same outliers. What is the main problem?",
      options: [
        "The ensemble lacks error diversity, so voting cannot correct those shared mistakes",
        "The ensemble has too many classifiers for hard voting",
        "The ensemble must use regression instead of classification",
        "The ensemble cannot be trained in sklearn",
      ],
      correct: 0,
      explanation: "Voting works best when errors are uncorrelated. Shared mistakes persist through aggregation.",
    },
    {
      id: "l08-mcq-2",
      question: "Which change is required to use soft voting with an SVC inside sklearn's VotingClassifier?",
      options: [
        "Enable probability estimates for SVC, accepting slower training",
        "Set bootstrap to False",
        "Remove all other classifiers from the ensemble",
        "Use only decision-tree base learners",
      ],
      correct: 0,
      explanation: "Soft voting averages probabilities, so SVC needs `probability=True` to expose `predict_proba()`.",
    },
    {
      id: "l08-mcq-3",
      question: "A bagging ensemble trains 500 decision trees, each on random samples drawn with replacement. What is this sampling called?",
      options: [
        "Bootstrap sampling",
        "Pasting",
        "Soft voting",
        "Residual fitting",
      ],
      correct: 0,
      explanation: "Bagging uses bootstrap sampling: random sampling with replacement.",
    },
    {
      id: "l08-mcq-4",
      question: "Why does bagging often help decision trees?",
      options: [
        "It reduces variance by averaging many unstable trees trained on different samples",
        "It makes each individual tree linear",
        "It removes the need for training data",
        "It forces every tree to use all features at every split",
      ],
      correct: 0,
      explanation: "Decision trees are high-variance learners. Bagging averages many variants and smooths the boundary.",
    },
    {
      id: "l08-mcq-5",
      question: "What is the key difference between AdaBoost and Gradient Boosting as presented in class?",
      options: [
        "AdaBoost changes instance weights; Gradient Boosting fits residual errors",
        "AdaBoost is parallel; Gradient Boosting uses hard voting",
        "AdaBoost only works for random forests; Gradient Boosting only works for PCA",
        "AdaBoost requires neural networks; Gradient Boosting requires SVM kernels",
      ],
      correct: 0,
      explanation: "Both are sequential, but AdaBoost reweights mistakes while Gradient Boosting fits residuals.",
    },
    {
      id: "l08-mcq-6",
      question: "A Gradient Boosting model underfits with too few trees. You lower the learning rate substantially. What usually needs to happen?",
      options: [
        "Increase the number of trees and monitor validation error",
        "Disable all regularization and ignore validation",
        "Switch to hard voting because learning rate no longer matters",
        "Use OOB evaluation from bagging",
      ],
      correct: 0,
      explanation: "Lower learning rate makes each tree contribute less, so more estimators are usually needed. Early stopping helps avoid overfitting.",
    },
    {
      id: "l08-mcq-7",
      question: "What does stacking add compared with simple voting?",
      options: [
        "A meta-learner that learns how to combine lower-level predictions",
        "Sampling with replacement for each tree",
        "A guarantee of no overfitting",
        "A rule that only one classifier can be used",
      ],
      correct: 0,
      explanation: "Stacking trains a blender/meta-learner on predictions from earlier learners.",
    },
  ],
  checklistTitle: "L08 final takeaways",
  studyChecklist: [
    "Explain ensemble learning through aggregation and diversity.",
    "Use hard voting for class labels and soft voting for probabilities.",
    "Remember that independence/uncorrelated errors are the key assumption behind the crowd effect.",
    "Separate bagging from pasting by replacement.",
    "Use OOB logic to understand why bagging can evaluate without a separate validation set.",
    "Describe random forest as bagged decision trees plus random feature subsets.",
    "Keep AdaBoost and Gradient Boosting separate: weights versus residuals.",
    "Treat XGBoost as powerful but requiring careful, limited hyperparameter search.",
    "Mark Module2 Lecture0 as complementary setup material, not the core 2026-05-15 lesson.",
  ],
};
