export const PHYLO_WRITTEN_PRACTICE = {
  fillBlanks: [
    {
      prompt: "In maximum likelihood, the likelihood is usually written as P(____ | ____).",
      answer: "data; model",
      accepted: ["data model", "data; model", "data, model", "d m"],
      explanation: "ML asks how probable the observed data are if a given model is true. In phylogenetics, the model includes the tree, branch lengths and substitution model.",
    },
    {
      prompt: "A model such as GTR includes six exchangeability parameters and equilibrium base ____.",
      answer: "frequencies",
      accepted: ["frequencies", "base frequencies", "equilibrium frequencies"],
      explanation: "GTR allows different exchangeabilities between nucleotide pairs and different equilibrium frequencies for A, C, G and T.",
    },
    {
      prompt: "The method used to efficiently sum over all possible ancestral states in ML is Felsenstein’s ____ algorithm.",
      answer: "pruning",
      accepted: ["pruning", "tree pruning", "felsenstein pruning"],
      explanation: "The pruning algorithm recursively computes conditional likelihoods instead of enumerating every complete ancestral-state assignment directly.",
    },
    {
      prompt: "In Bayesian inference, the probability of a tree/model after observing the data is called the ____ probability.",
      answer: "posterior",
      accepted: ["posterior", "posterior probability"],
      explanation: "The posterior combines likelihood and prior information: it is the probability of the model given the data.",
    },
    {
      prompt: "MCMC stands for Markov Chain ____ ____.",
      answer: "Monte Carlo",
      accepted: ["monte carlo", "Monte Carlo"],
      explanation: "The Markov-chain part describes how each sampled state depends on the current state; Monte Carlo refers to random sampling used to approximate a complex distribution.",
    },
    {
      prompt: "The early part of an MCMC chain that is discarded because it has not yet reached the target distribution is called ____.",
      answer: "burn-in",
      accepted: ["burn-in", "burnin", "burn in"],
      explanation: "Burn-in removes the initial phase before the chain is sampling from the stationary posterior distribution.",
    },
    {
      prompt: "A bootstrap replicate is produced by resampling alignment columns with ____.",
      answer: "replacement",
      accepted: ["replacement", "with replacement"],
      explanation: "Bootstrap columns are sampled with replacement, so some sites can appear multiple times and others may be absent.",
    },
    {
      prompt: "The jackknife differs from bootstrap because it samples/removes data without ____.",
      answer: "replacement",
      accepted: ["replacement", "without replacement"],
      explanation: "Jackknifing removes a subset of data without duplicating columns, whereas bootstrapping resamples with replacement.",
    },
    {
      prompt: "A split or bipartition divides the tips of a tree into two ____ groups.",
      answer: "complementary",
      accepted: ["complementary", "complementary groups"],
      explanation: "Each internal branch defines two complementary sets of taxa; support metrics often evaluate whether that split reappears.",
    },
    {
      prompt: "Incomplete lineage sorting is caused by ancestral ____ persisting across speciation events.",
      answer: "polymorphism",
      accepted: ["polymorphism", "polymorphisms", "ancestral polymorphism", "ancestral polymorphisms"],
      explanation: "ILS occurs when ancestral variants persist through speciation and then sort differently in descendant lineages.",
    },
    {
      prompt: "Robinson–Foulds distance compares trees by counting incompatible/private ____.",
      answer: "splits",
      accepted: ["splits", "bipartitions", "private splits"],
      explanation: "RF distance compares the split sets of two trees and counts splits found in one tree but not the other.",
    },
    {
      prompt: "ASTRAL is a summary coalescent method that uses gene trees and maximizes quartet ____.",
      answer: "compatibility",
      accepted: ["compatibility", "quartet compatibility", "support"],
      explanation: "ASTRAL searches for a species tree that agrees as much as possible with quartets induced by the input gene trees.",
    },
    {
      prompt: "Stochastic bias is mainly caused by too little phylogenetic ____.",
      answer: "signal",
      accepted: ["signal", "phylogenetic signal"],
      explanation: "Stochastic error is a sampling problem: the data contain too little informative signal relative to noise.",
    },
    {
      prompt: "Systematic bias becomes worse when more data reinforce a wrong ____ assumption.",
      answer: "model",
      accepted: ["model", "model assumption", "assumption"],
      explanation: "If the model is misspecified, more data can strengthen the wrong signal instead of correcting it.",
    },
    {
      prompt: "Saturation occurs when multiple substitutions happen at the same ____.",
      answer: "site",
      accepted: ["site", "position", "alignment site"],
      explanation: "After repeated substitutions at the same position, observed differences underestimate the true amount of evolutionary change.",
    },
    {
      prompt: "Long branch attraction is especially problematic for maximum ____.",
      answer: "parsimony",
      accepted: ["parsimony", "maximum parsimony"],
      explanation: "Parsimony can mistake convergent changes on long branches for shared ancestry because it does not use an explicit substitution model.",
    },
    {
      prompt: "In divergence dating, fossil calibrations usually provide a minimum age for a ____.",
      answer: "node",
      accepted: ["node", "clade", "internal node"],
      explanation: "A fossil shows that the corresponding lineage or clade existed by that time, so it often constrains a node to be at least that old.",
    },
    {
      prompt: "A fossil outside the living diversification of a clade belongs to the ____ group.",
      answer: "stem",
      accepted: ["stem", "stem group"],
      explanation: "Stem fossils are outside the crown group of living descendants, so they calibrate a deeper branch than crown fossils.",
    },
    {
      prompt: "The ratio dN/dS is often represented by the Greek letter ____.",
      answer: "omega / ω",
      accepted: ["omega", "ω", "w"],
      explanation: "Omega is the ratio of nonsynonymous to synonymous substitution rates and is used as a rough signal of selective pressure.",
    },
    {
      prompt: "A codon alignment should preserve gaps in multiples of ____ nucleotides.",
      answer: "three",
      accepted: ["three", "3"],
      explanation: "Indels that disrupt the reading frame break codon structure, which is essential for codon models and dN/dS analyses.",
    },
    {
      prompt: "In trait evolution, the Mk model is commonly used for ____ traits.",
      answer: "discrete",
      accepted: ["discrete", "categorical", "discrete traits"],
      explanation: "Mk is a Markov model for transitions among discrete character states, such as presence/absence or habitat categories.",
    },
    {
      prompt: "Brownian Motion is often used as a model for ____ trait evolution.",
      answer: "continuous",
      accepted: ["continuous", "quantitative", "continuous traits"],
      explanation: "Brownian Motion models continuous trait change as a random walk whose variance accumulates through time.",
    },
    {
      prompt: "Pagel’s λ measures phylogenetic ____ in trait data.",
      answer: "signal",
      accepted: ["signal", "phylogenetic signal"],
      explanation: "Pagel’s lambda scales the expected covariance among species according to the phylogeny.",
    },
    {
      prompt: "PIC stands for phylogenetically independent ____.",
      answer: "contrasts",
      accepted: ["contrasts", "contrast"],
      explanation: "PIC transforms species trait values into contrasts that are independent under a Brownian-motion model.",
    },
    {
      prompt: "PGLS corrects regression models by accounting for phylogenetic non-____ among species.",
      answer: "independence",
      accepted: ["independence", "independent", "non-independence"],
      explanation: "PGLS models the covariance among species induced by shared evolutionary history.",
    },
  ],
  openQuestions: [
    {
      prompt: "Explain why maximum likelihood is described as a tree-scoring method rather than simply a tree-finding method.",
      modelAnswer: "Maximum likelihood evaluates how probable the observed sequence data are given a model, which includes the tree topology, branch lengths and substitution model. By itself, ML gives a score to a proposed tree. To find a good tree, software must combine this scoring function with a search algorithm that proposes new trees, evaluates them and keeps better solutions.",
      checklist: ["Mentions P(data | model)", "Explains that the model includes the tree", "Separates scoring from search/proposal algorithms"],
    },
    {
      prompt: "Compare maximum likelihood and Bayesian inference in phylogenetics.",
      modelAnswer: "Maximum likelihood focuses on finding the tree or model that maximizes P(data | model). Bayesian inference estimates P(model | data), combining the likelihood with prior information. ML usually returns a best tree, while Bayesian inference samples many trees and parameters through MCMC, then summarizes the posterior distribution using posterior probabilities or consensus trees.",
      checklist: ["Contrasts P(data | model) and P(model | data)", "Mentions priors", "Mentions MCMC/posterior tree samples"],
    },
    {
      prompt: "What does bootstrap support measure, and why should it not be interpreted as the probability that a clade is true?",
      modelAnswer: "Bootstrap support measures how robust a split is to resampling of the alignment. If a clade appears in many bootstrap trees, it means the signal for that split is widespread enough across the data to reappear after perturbation. It is not the direct probability that the clade is true, because it depends on the dataset, model, method and resampling procedure.",
      checklist: ["Describes resampling columns", "Frames support as robustness", "Avoids interpreting it as truth probability"],
    },
    {
      prompt: "Explain incomplete lineage sorting and how it can produce gene tree/species tree discordance.",
      modelAnswer: "Incomplete lineage sorting occurs when ancestral polymorphisms persist through speciation events and are later fixed differently in descendant lineages. As a result, the history of a particular gene may group species differently from the actual species tree. This discordance is biological, not necessarily an error of phylogenetic inference.",
      checklist: ["Mentions ancestral polymorphism", "Mentions persistence across speciation", "Explains biological discordance"],
    },
    {
      prompt: "Why can concatenation be useful, and what is its main risk?",
      modelAnswer: "Concatenation combines multiple gene alignments into a large supermatrix, increasing phylogenetic signal and reducing stochastic error. Its main risk is that it assumes, at least broadly, that one tree can describe all genes. If different genes have different histories due to ILS, HGT, introgression or strong heterogeneity, concatenation can give a strongly supported but misleading result.",
      checklist: ["Mentions supermatrix", "Explains increased signal/reduced stochastic error", "Explains the single-tree assumption"],
    },
    {
      prompt: "Distinguish stochastic bias from systematic bias in phylogenetics.",
      modelAnswer: "Stochastic bias comes from limited data or weak signal. It often produces low support and can be improved by adding more informative data. Systematic bias comes from model violation, such as compositional heterogeneity, saturation or long branch attraction. Adding more data can make systematic bias worse because the wrong signal becomes more strongly supported.",
      checklist: ["Defines stochastic as low signal", "Defines systematic as model violation", "Explains why more data can worsen systematic bias"],
    },
    {
      prompt: "Why can dN/dS be useful for detecting selection, and why must it be interpreted carefully?",
      modelAnswer: "dN/dS compares the rate of nonsynonymous substitutions to synonymous substitutions. Values much lower than 1 suggest purifying selection, values around 1 suggest relaxed or neutral evolution, and values above 1 may suggest positive selection. However, a gene-wide dN/dS above 1 is often suspicious because it may reflect misalignment, wrong orthology, pseudogenization or averaging problems. Selection is often localized to particular sites or branches.",
      checklist: ["Defines dN and dS", "Gives the omega interpretation", "Warns about gene-wide values and data problems"],
    },
    {
      prompt: "Explain the difference between tip dating and node dating.",
      modelAnswer: "Tip dating uses samples whose collection time is known, such as viral genomes sampled in different years or ancient DNA. These dated tips help calibrate the rate of evolution. Node dating uses external information, often fossils, to constrain the age of internal nodes. Fossil calibrations usually provide minimum ages and must be assigned carefully to crown or stem groups.",
      checklist: ["Defines tip dating", "Defines node dating", "Mentions fossils/crown/stem placement"],
    },
    {
      prompt: "Why are phylogenetic comparative methods needed when comparing traits across species?",
      modelAnswer: "Species cannot be treated as independent datapoints because closely related species tend to resemble each other due to shared ancestry. Phylogenetic comparative methods incorporate the tree structure into the analysis, allowing trait evolution, correlations and regressions to be interpreted while accounting for phylogenetic non-independence.",
      checklist: ["Mentions non-independence", "Links similarity to shared ancestry", "Explains why tree-aware methods are needed"],
    },
    {
      prompt: "Explain the difference between Brownian Motion and Ornstein–Uhlenbeck models of trait evolution.",
      modelAnswer: "Brownian Motion models trait evolution as a random walk, where variance increases with time since divergence. Ornstein–Uhlenbeck also includes random change, but adds attraction toward an optimum. BM is useful for neutral-like continuous trait divergence, while OU is often used when traits evolve under stabilizing selection around an adaptive optimum.",
      checklist: ["Defines BM as random walk", "Defines OU as attraction to an optimum", "Connects OU to stabilizing selection"],
    },
  ],
};
